### ISSUE TITLE
BaseEncoding ignoreCase() option for base16 decoder

### ISSUE THREAD

**Issue by lambdaupb** [google/guava#1886]
When dealing with hex encoded input, I have to handle both lower and uppercase input. Since decoder ist strict, I would have to `String.toLowerCase()` the input before passing it to the decoder, which is another copy process.

Nicer would be `BaseEncoding hex = BaseEncoding.base16().ignoreCase();`

**Comment by kofemann** [comment]
:+1:  if .lowerCase() or .upperCase()  is not specified, makes sense to ignore case sensitivity.

**Comment by Xiaoshuai** [comment]
I think `BaseEncoding.base16().decode(str.toUpperCase())` is perfect

**Comment by dnault** [comment]
Case doesn't matter when decoding base 16, so it would be nice if it just *worked* no matter what case the input is. The lowerCase() and upperCase() methods should only affect encoding.

**Comment by Glamdring** [comment]
It's certainly non-intuitive that it's case-sensitive. Which violates the principle of least astonishment

**Comment by kgarn** [comment]
I don't understand why this closed in 2015 @haozhun ?  
It maybe related to  "[Allow mixed case in from base functions #2669](https://github.com/prestodb/presto/issues/2669)" but only if you limit your scope to strings.  I need to be able to use the encodingStream and decodingStream and I need to be able to accept mixed case input streams for base16 decoding. I can be pretty sure the inputs will be consistent but can have no guaranty  that they will be upper or lower cased

**Comment by tholenst** [comment]
+1: I would find this useful: I sometimes hard code values into tests which I get from the C++ function absl::BytesToHexString("...") which outputs lower case letters. Now I have to always go through the additional step of converting these.

**Comment by cpovirk** [comment]
This will be coming in the next release. Sorry that we missed updating this issue:

https://github.com/google/guava/commit/9c1e5dea4b980202ba003b90fcb64183d42031b3

**Comment by cpovirk** [comment]
[released in 32.0.0](https://github.com/google/guava/releases/tag/v32.0.0#:~:text=baseencoding.ignorecase)
