### ISSUE TITLE
Guava library violates Google Java Style guide

### ISSUE THREAD

**Issue by romani** [google/guava#1891]
Affected Files:796
Violations: 4071

Google Java Style guide (version of March 21, 2014): 
https://google-styleguide.googlecode.com/svn-history/r130/trunk/javaguide.html

Checkstyle Maven plugin report for Guava 17.0:
http://checkstyle.sourceforge.net/reports/google-style/guava/
All violations are thoroughly rechecked, but some very occasional false-positives could be present.

Detailed report (match of each Google Java Style rule to Checkstyle):
http://checkstyle.sourceforge.net/google_style.html

How to run (command line): 

```
~ $ cd /var/tmp
/var/tmp $ git clone https://code.google.com/p/guava-libraries/

/var/tmp $ wget -O checkstyle-6.1-all.jar http://downloads.sourceforge.net/project/checkstyle/checkstyle/6.1/checkstyle-6.1-all.jar?r=&ts=1416082535&use_mirror=tcpdiag

/var/tmp $ wget https://raw.githubusercontent.com/checkstyle/checkstyle/master/google_checks.xml

/var/tmp $ time java -jar checkstyle-6.1-all.jar -c google_checks.xml -o checkstyle-report-guava.txt -r guava-libraries

real    2m55.599s
user    3m12.596s
sys 0m1.056s
```

PS: all work was done during Google Summer of Code 2014

**Comment by kevinb9n** [comment]
EmptyBlock:  yes, that's what we do too. The guide may not *say* you can name it 'expected' and skip the comment in production code, but checkstyle will let you.

WhitespaceAround: agreed.

Most of the rest of your comment looks like just echoing what we already know needs to be fixed. I can't promise a fixed version of the document will be coming *soon* though.

**Comment by romani** [comment]
@kevinb9n , it will also bee good to clarify what code is preferable (discussion at https://github.com/checkstyle/checkstyle/issues/533): 
```
boolean same = Util.<Integer, String>compare(p1, p2);  // Generic preceded method name
```
vs
```
boolean same = Util.<Integer, String> compare(p1, p2);  // Generic preceded method name, extra space between
```

will be good to put that in style document to resolve any further discussions.

**Comment by kevinb9n** [comment]
That one is addressed here:

https://google-styleguide.googlecode.com/svn/trunk/javaguide.html#s4.6.2-horizontal-whitespace

"Beyond where required by the language or other style rules, and apart from literals, comments and Javadoc, a single ASCII space also appears in the following places *only* ."

**Comment by romani** [comment]
Empty Catch Block is implemented and released in Checkstyle 6.4, report was updated - "Last Published: 2015-02-28  | Version: 19.0-SNAPSHOT" 
http://checkstyle.sourceforge.net/reports/google-style/guava/

in case you need to regenerate report please use that simple steps: https://github.com/checkstyle/checkstyle/wiki/How-to-generate-Checkstyle-report-for-Google-Guava-project

FYI:
so the only item that is left to be done by Checkstyle team is "4.8.6.1 Block comment style", but will be addressed in next release.

**Comment by Vladlis** [comment]
New options "ignoreInlineTags" and "ignoredTags" for Single Line Javadoc were added and released in Checkstyle 6.8.
<b>ignoreInlineTags</b> allows inline tags (such as {@code}, {@link} etc.) to be put in a single line javadoc. Report generated with Checkstyle 6.9 over Guava 19.0-SNAPSHOT with this option switched on shows a lot less violations: <b>53</b> (http://vladlis.github.io/reports/google_style/) against <b>227</b> (http://checkstyle.sourceforge.net/reports/google-style/guava/). So it makes sense to extend the Style Guide (http://google.github.io/styleguide/javaguide.html#s7.1.3-javadoc-at-clauses) and make it more precise in order to allow inline tags. Some googlers already reported that issue at https://github.com/checkstyle/checkstyle/pull/1545, but to change config with new option we need to have update in Google Java Style first.
<b>ignoredTags</b> could also be used if some tags, for instance @see, were allowed by the Guide in a single line javadoc.

**Comment by MEZk** [comment]
CommentsIndentationCheck was introduced and reliased in Checkstyle 6.12. The Check covers the section [4.8.6.1 Block comment style](http://checkstyle.sourceforge.net/reports/google-java-style.html#s4.8.6.1-block-comment-style) from Google Java Style Guide. Report generated with Checkstyle 6.12 over Guava 19.0-SNAPSHOT with CommentsIndentationCheck shows [11 violations](http://checkstyle.sourceforge.net/reports/google-style/guava/).
So, Google Java Style Guide was covered by Checkstyle as much as it was possible. See [Google's Java Style Checkstyle Coverage](Google's Java Style Checkstyle Coverage).

**Comment by romani** [comment]
> 926 ParameterName

guide is updated - https://google.github.io/styleguide/javaguide.html#s5.2.6-parameter-names

> 263 LocalVariableName

Clarification issue request was created to style project - https://github.com/google/styleguide/issues/214

> 185 SingleLineJavadoc
Single-line javadoc is explicitly allowed by 7.1.1.

confirmation request - https://github.com/google/styleguide/issues/215

**Comment by kevinb9n** [comment]
I think this issue doesn't constitute a Guava bug (anymore), right?
