### ISSUE TITLE
Optional.or(Supplier<? extends Optional<T>> supplier)

### ISSUE THREAD

**Issue by kilotaras** [google/guava#1901]
Would be useful for usecases like:

`someOptional = firstSuplier().or(secondSupplier).or(thirdSupplier)`

Right now it should be written as

```
if (!someOptional.isPresent()) {
  someOptional = secondSupplier();
}

if (!someOptional.isPresent()) {
  someOptional = thirdSupplier();
}
```

**Comment by kilotaras** [comment]
Added in Java 9. Could still be useful to people on Java 8

**Comment by nikhilbarar** [comment]
Is it open? I'd like to send a PR for this

**Comment by cpovirk** [comment]
Kevin [recently said](https://github.com/google/guava/issues/3135#issuecomment-387107841):

> I'm sorry, but the legacy Optional class is indeed frozen.

I'll close this and any other `Optional` feature requests I see floating around.
