### ISSUE TITLE
Support for Context in EventBus

### ISSUE THREAD

**Issue by jukowski** [google/guava#1914]
Let me start explaining the problem through my use-case:
I have a set of POJO classes generated with `xjc` from XML schemas. I would like to use these classes as events, so that I can do `eventBus.post(someReceivedXMLEvent)`. The problem is that processing these events requires information (e.g. network connection from which `someReceivedXMLEvent` was received) that is independent of `someReceivedXMLEvent` itself and hence not part of either its XML schema or POJO signature. 

EventBus is based on the premise that event objects contain all the information required to process them. While this is a good assumption for hand-written event classes that can be extended anytime, it does not work for event classes for which no control over the source code is given. Generics would normally help here but type erasure gets in the way...

Proposed solution:
1) extend `EventBus` object with method `eventBus.post(event, context);`
2) extend the `AnnotatedSubscriberFinder` to accept methods with a second parameter specifying required context type.
3) when searching the subscribers to be notified we have two cases 
a) an `eventBus.post(event)` - would match only subscribers that are context independent
b) an `eventBus.post(event, context)` - would match subscribers that are context independent and those that are context dependent and are compatible with the provided context.

**Comment by nglorioso** [comment]
We're unlikely to add significant features to EventBus anymore.
