### ISSUE TITLE
Idea: DoubleMath#fuzzyEquals(...) supporting nullables

### ISSUE THREAD

**Issue by JensRantil** [google/guava#1919]
**Background:** I have a use case where I need to implement/override `equals(...)` method for a class holding `Double` fields. Since `Double` rarely can be compared directly I'd like to make a fuzzy comparison between my class instances using some tolerance.

**Issue:** [`DoubleMath#fuzzyEquals(...)`](http://docs.guava-libraries.googlecode.com/git/javadoc/com/google/common/math/DoubleMath.html#fuzzyEquals%28double,%20double,%20double%29) would be a useful utilify method for doing my comparison. The issue is, it doesn't support nullable doubles.

**Proposal:** To remedy this I have put together a utility method that solves this for me:

``` java
public class Doubles {

    /**
     * Like {@link DoubleMath#fuzzyEquals(double, double, double)}, but supports nullables.
     * 
     * @param a
     *            first nullable element
     * @param b
     *            second nullable element
     * @param tolerance
     *            absolute difference tolerance. See {@link DoubleMath#fuzzyEquals(double, double, double)} for details.
     */
    public static boolean fuzzyEquals(Double a, Double b, double tolerance) {
        if (a==null && b==null)
            return true;
        else if (a != null && b != null)
            return DoubleMath.fuzzyEquals(a, b, tolerance);
        else /* (a != null ^ b != null) */
            return false;
    }

}
```

Would a similar method be useful to add to Guava? An alternative approach would be to relax `DoubleMath#fuzzyEquals(...)` method signature to accept `Double`s instead of `double`.

**Additional:** It could also be debatable if fuzzy comparison should be done in an `equals(...)` implementation. In my case, I think it's fair to say it is.

**Comment by nglorioso** [comment]
Given the age of this feature request, I'm going to close it. I don't see any more evidence inside Google that this feature would be widely used.
