### ISSUE TITLE
How to use own Map implementation to store cached values in Guava Cache?

### ISSUE THREAD

**Issue by LostOverflow** [google/guava#1920]
I came up own Map impl that will not stores multiple Values, if it equals, and avoid duplicating of data. (just store only one of them).
Description of map impl is available on  (http://stackoverflow.com/questions/27472712/compact-java-util-map-implementation)
The question is : how to use this map for caching results , or is it possible at all?

**Comment by nglorioso** [comment]
Sounds like lowasser@'s suggestion is what I would do (e.g.: use the CacheLoader entry point to use your interner).
