### ISSUE TITLE
Make AsMapView and subclasses Serializable

### ISSUE THREAD

**Issue by ghost** [google/guava#1922]
`AsMapView` (as returned by `Maps.asMap`) is not `Serializable`. As I can see, there's no fundamental reason why it shouldn't be serializable, if the set and function are (a lot of the functions returned by the `Functions` methods are indeed serializable). This applies to the subclass `SortedAsMapView` and related class `NavigableAsMapView` as well

**Comment by cpovirk** [comment]
While I'm not ruling out that we'd someday make some type serializable, it seems unlikely that we'll do it for many, given all the trouble that serialization can cause (including increasing the surface for security problems, even for users who don't "use" a type).
