### ISSUE TITLE
Add @CheckReturnValue for a few specific methods

### ISSUE THREAD

**Issue by cpovirk** [google/guava#1931]
- `Lists.reverse`
- `Futures.immediate*Future`
- `*.filter`

See https://github.com/google/error-prone/issues/276

The trick will be cleaning up Google-internal callers of those methods so that we don't break builds.

**Comment by cpovirk** [comment]
We could get a small bit of value out of also doing these methods, too:

- `Iterables.transform` (3 bugs, 2 ambiguous)
- `Collections2.transform` (1 bug)
- `Lists.transform` (1 bug, 1 harmless call)

**Comment by cpovirk** [comment]
- `Iterables.elementsEqual` (2 bugs)
- `Futures.successfulAsList` (1 bug, 1 probably harmless)

After that, we're scraping the bottom of the barrel (at least for the classes that I checked): lots of "sketchy but not really buggy" code, like people calling `Iterators.size` to exhaust an iterator or people making harmless no-op calls to the no-arg or varargs `Lists.newArrayList` and other factory methods.

**Comment by cpovirk** [comment]
- `Strings.nullToEmpty` (1 bug, 1 harmless, maybe others that my search didn't find)

**Comment by kluever** [comment]
- Futures.allAsList/successfulAsList (bug 17205818)
- filter() and transform() methods (bug 9072648)

**Comment by cpovirk** [comment]
As best I can tell, these are all done except for `Collections2.transform`.

**Comment by kluever** [comment]
Collections2 has `@CheckReturnValue` on the entire class, so this can probably be closed?

**Comment by cpovirk** [comment]
Oops, thanks :)
