### ISSUE TITLE
Iterators.exhaust(Iterator)

### ISSUE THREAD

**Issue by cpovirk** [google/guava#1932]
During some investigation of potential `@CheckReturnValue` methods (https://github.com/google/error-prone/issues/276), I found a number of users who call `Iterators.getLast` (~3 times) or especially `Iterators.size` (~17 times) solely for the side effect of exhausting the iterator. The calls to `size` feel particularly questionable. `getLast` feels more acceptable but still pretty strange, and if users use the one-arg version (as all 3 users I found do), they need to think to guard it with a `hasNext` check. (Of the 3, 1 did, and the other 2 are in tests where at least one element is expected.)

One thing arguing against the addition of this method is that advancing iterators shouldn't typically have side effects. For the particular case in which cleanup at the end is necessary, the iterator should perhaps instead implement `Closeable`. Would we want to add a method to support what we consider to be a questionable use case simply because it would let users do their questionable thing in a more explicit way?

**Comment by kluever** [comment]
So I'm trying to add `@CheckReturnValue` to `com.google.common.collect.Lists`, and there are *lots* of folks using Lists.newArrayList(iterable/iterator) just to force iteration of their underlying iterator. Lots of these are in tests, where they're expecting an exception to get thrown during iteration or something.

I don't think `Iterables.exhaust()` makes sense (what does it mean to exhaust an iterable?), but `Iterators.exhaust()` is sounding more and more appealing.

The alternative is to just write silly loops for all of these.

For an iterable:
```
for (String foo : iterable) {
  // do nothing
}
```
For an iterator:
```
while (iterator.hasNext()) {
  iterator.next();
}
```

Both of these could be better served by an `Iterators.exhaust()` method.

**Comment by cpovirk** [comment]
I would rather make them write the loops :) Mainly, I don't want to signal that such an `Iterable`/`Iterator` is a good idea. I think we'd be sending that signal if we added an `exhaust` method. (Yes, I know that I'm the one that filed this issue :))

**Comment by kluever** [comment]
So the "iterators that throw exceptions" thing is kind of gross, but I've also seen folks do this to preload the underlying data. I guess a for-loop is reasonable there too though.

**Comment by kevinb9n** [comment]
I think I'm with Chris.

On Fri, Jan 22, 2016 at 1:16 PM, Chris Povirk <notifications@github.com>
wrote:

> I would rather make them write the loops :) Mainly, I don't want to signal
> that such an Iterable/Iterator is a good idea. I think we'd be sending
> that signal if we added an exhaust method. (Yes, I know that I'm the one
> that filed this issue :))
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/guava/issues/1932#issuecomment-174051563>.
>



-- 
Kevin Bourrillion | Java Librarian | Google, Inc. | kevinb@google.com

**Comment by kluever** [comment]
Also to be clear, the for-each loop above needs to be:
```
for (String unused : iterable) {
  // do nothing
}
```

Otherwise you'll get an unused variable warning ;-)

**Comment by nglorioso** [comment]
Given the discussion above, we're unlikely to want to provide a utility method to exhaust an iterator.

Most of the time, it's not a good idea to have an Iterator that needs to be exhausted for *some reason*, and if you do, there's a perfectly serviceable-if-awkward construct to do it. (If the reason is to close up resources, `Closeable` and try-with-resource is the better solution for it anyway).
