### ISSUE TITLE
Feature request: A new callback for receiving status updates before callback completion

### ISSUE THREAD

**Issue by ssumit** [google/guava#1934]
There are cases where the actual work done takes substantial amount of time and the consumer might want to receive any progress updates if possible. It is fine for the task to get failed or completed after zero or more updates. 

I m expecting a new callback which could be like:
public interface NewCallback<V, W> extends FutureCallback<V> {
    void onUpdate(W w);
}

**Comment by nglorioso** [comment]
Unfortunately, this would require coordination between the future execution and the callback system (as currently implemented, FutureCallbacks are processed at the end of the execution of the future, so it'll be too late to post updates to NewCallback).

If you need something like this, I would suggest registering a listener or callback in the normal execution flow of the long process you're looking to get updates on, and then adding a normal `addCallback` to be notified when the long process future is done.
