### ISSUE TITLE
Need a Maps class method that receives Iterator<V> values and a Function<? super V, K> keyFunction an returns a Map<K, Iterable<V>>

### ISSUE THREAD

**Issue by alexzm1** [google/guava#1938]
As the description says, I need a way to group the received Iterator based on what the function returns as K value.

Is not hard to do and I can even work on it, it could be like method [Maps#uniqueIndex]( http://docs.guava-libraries.googlecode.com/git/javadoc/com/google/common/collect/Maps.html#uniqueIndex(java.util.Iterator,%20com.google.common.base.Function) )

**Comment by PhilippWendler** [comment]
Are you looking for [Multimaps.index] (http://docs.guava-libraries.googlecode.com/git/javadoc/com/google/common/collect/Multimaps.html#index(java.util.Iterator,%20com.google.common.base.Function))?
You can call `asMap()` on the result to get a `ImmutableMap<K,Collection<V>>`.

**Comment by alexzm1** [comment]
That's exactly what I wanted, Thank you so much.

We can close this issue.
