### ISSUE TITLE
Line comment on requiring Java 6

### ISSUE THREAD

**Issue by mafagafogigante** [google/guava#1942]
Please see https://github.com/google/guava/blob/master/guava/src/com/google/common/primitives/Booleans.java#L235.

Isn't Java 6 available?
If it is, should that comment be removed?
Should the method be removed? (It is private and only used in a single place).

**Comment by kevinb9n** [comment]
I think you're right. Seems like just the reason we left this comment. That
said, there's probably no hurry to do this.

On Sun, Jan 11, 2015 at 10:28 PM, Bernardo Sulzbach <
notifications@github.com> wrote:

> Please see
> https://github.com/google/guava/blob/master/guava/src/com/google/common/primitives/Booleans.java#L235
> .
>
> Isn't Java 6 available?
> If it is, should that comment be removed?
> Should the method be removed? (It is private and only used in a single
> place).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/guava/issues/1942>.
>



-- 
Kevin Bourrillion | Java Librarian | Google, Inc. | kevinb@google.com

**Comment by mafagafogigante** [comment]
Thank you for your answer.
Can something like this by merged?
https://github.com/mafagafogigante/guava/commit/ef1eb44e37a10e30266f5f026405b56c890d8f07

**Comment by kluever** [comment]
We actually need to do this for all of the primitive utility classes in c.g.common.primitives. I'm submitting a fix internally and it'll get mirrored out within the next few days. Thanks for finding this!

**Comment by mafagafogigante** [comment]
Glad I could help.

**Comment by mafagafogigante** [comment]
Maybe [this](https://github.com/google/guava/blob/master/guava/src/com/google/common/base/Strings.java#L76) is also of interest .

**Comment by kluever** [comment]
Actually...as it turns out we can't fix this quite yet, because the methods don't exist in GWT 2.6.1 (they do in GWT 2.7.0). So we can't fix this until we upgrade to GWT 2.7.0.
