### ISSUE TITLE
Improve invalid character exceptions from BaseEncoding

### ISSUE THREAD

**Issue by cslee00** [google/guava#1947]
When decoding Base64/32/16 data an exception is thrown if an invalid character is found:

BaseEncoding.java:501:
```java
    int decode(char ch) throws IOException {
      if (ch > Ascii.MAX || decodabet[ch] == -1) {
        throw new DecodingException("Unrecognized character: " + ch);
      }
      return decodabet[ch];
    }
```
The exception message prints out the character itself, which isn't terribly helpful when that is a non-printable character.  Recommend that the hex value of the character be printed instead.

**Comment by kluever** [comment]
Hmm, can't figure out how to assign this to a non-team member, but @marceljuenemann is gonna take care of this for us.
