### ISSUE TITLE
InternetDomainName toString() method unexpected behavior

### ISSUE THREAD

**Issue by ffr4nz** [google/guava#1955]
.toString() method returns  "InternetDomainName{name=**domainORtldORwhatever**}" Should not simply return the **domainORtldORwhatever**?

Example code:

InternetDomainName owner = InternetDomainName.from("www.elmundo.es").topPrivateDomain();
System.out.println(owner.toString());

Print:

InternetDomainName{name=elmundo.es}

What I expect is:

elmundo.es

Is it an error? is it an expected behavior?

I'm using: 

<dependency>
	<groupId>com.google.guava</groupId>
	<artifactId>guava</artifactId>
	<version>18.0</version>
</dependency>

Thanks!

**Comment by devoncrouse** [comment]
+1, kind of annoying, since name() was removed. Seems like the best way to get the actual value now is to concatenate parts() back together. I don't think anyone really wants the class name coming back in toString(), fwiw.

**Comment by cpovirk** [comment]
toString() has worked as you describe since 15.0. Do you have an older version of Guava on your classpath alongside 18.0?

**Comment by cpovirk** [comment]
(sorry, "worked as you describe" meaning "returns the name")

**Comment by devoncrouse** [comment]
Yeah, deleted my comment when I realized Storm 0.9.2 was overriding with Guava 13. Pardon me.

**Comment by chethan** [comment]
I have the same problem , storm is overriding guava with a older version. Is there any solution to this problem?

**Comment by jbduncan** [comment]
@chethan Is this Apache Storm, or another Storm? :)
