### ISSUE TITLE
EventBus does not like generic events

### ISSUE THREAD

**Issue by thomasnield** [google/guava#1959]
When I utilize generic methods that infer an event type off a generic, and pass it as a parameter in a @Subscribe method inside an anonymous object, it seems to break the EventBus. It no longer is able to distinguish event types resulting in class casting errors. Reflection issue maybe?

http://stackoverflow.com/questions/28229374/passing-generic-event-to-guava-eventbus?noredirect=1#comment44821654_28229374

**Comment by nglorioso** [comment]
I don't think we can do much with generic event subscribers (since the type is erased, we only see `subscribe(Object event)`).
