### ISSUE TITLE
De-@Beta Splitter.withKeyValueSeparator

### ISSUE THREAD

**Issue by bacar** [google/guava#1964]
Any plans to take this out of beta?

**Comment by kluever** [comment]
We'll discuss this at our weekly API review meeting on Monday and I'll get back to you.

**Comment by bacar** [comment]
Any news on this one?

**Comment by kluever** [comment]
@bacar Sorry for not getting back to you on this.  We did discuss it at our API meeting, and we decided to leave it as Beta for now.  There's a few open issues w.r.t. MapSplitter, but following issues were the most worrisome:

https://github.com/google/guava/issues/1900 : MapSplitter should ignore key-value separator after first
https://github.com/google/guava/issues/870 : MapSplitter doesn't trim keys and values as expected

And unfortunately those issues are pretty low priority for us, so it might be a while until we revisit this decision.
