### ISSUE TITLE
Add Maps.asMap and toMap overloads that don't take a transform function

### ISSUE THREAD

**Issue by bacar** [google/guava#1965]
...and assume the identify function.

**Comment by kluever** [comment]
I took a look at existing callers inside Google, and only found about 2% (of both asMap/toMap) that pass the identity function to these methods. I'm not sure I really see this as a comment enough operation to warrant adding these new APIs.

Can you try to make a stronger case for why we should add these?

Thanks,
-kak

**Comment by bacar** [comment]
Thanks. A default of identity seemed likely to be useful, but it's no big deal.
Our use case is:
- we have a Set<X>, a small number of which need to be remapped to some other value (whilst retaining the original X).
- we create a Map<X, X> using the identity function, then immediately override the values of the ones that need remapping.

Perhaps there are better ways of doing this anyway.

**Comment by kluever** [comment]
I think what you have now (passing Functions.identity()) is probably OK...marking this as won't fix.

Thanks for the feedback though!

**Comment by kevinb9n** [comment]
Concur: a reasonable idea, but just not common enough.

**Comment by bacar** [comment]
NP, thanks for the rapid response.

**Comment by bacar** [comment]
FWIW, I'm targeting Java 6, which can't infer the type parameters of Functions.identity(), and have to do the annoying dance of having to supply redundant parameters explicitly, which is probably what sparked my desire to sort this.
