### ISSUE TITLE
Functions.forMap should accept Map<? extends K, ? extends V>, like Collections.unmodifiableMap

### ISSUE THREAD

**Issue by fleaflicker** [google/guava#1968]
The function returned by Functions.forMap is like a limited read-only map. So it should be able to accept more inputs.

This is similar to `java.util.Collections.unmodifiableMap`, which has the following signature:

```public static <K,V> Map<K,V> unmodifiableMap(Map<? extends K, ? extends V> m)```

For example, the following is only possible by wrapping the input map:

```java
Map<Integer,String> map = ...;
Function<Number,CharSequence> f = 
    Functions.forMap(Collections.<Number,CharSequence>unmodifiableMap(map));
```

**Comment by lowasser** [comment]
This use case seems a little odd to me: you're returning a Function that claims to accept Number, but it really only works on Integers, and I believe it throws on other inputs.  Is that really behavior it makes sense to encourage?

**Comment by kevinb9n** [comment]
You say that it "should be able to accept more inputs", but it will already accept your `Map<Integer, String>` just fine as it is. It returns you a `Function<Integer, String>` which is the correct type for what it is. Now, if you have a reason to want to cast that to a different type, that's up to you.

**Comment by fleaflicker** [comment]
Fair enough, thanks for the reply.
