### ISSUE TITLE
Javadoc of HashBiMap#containsValue #inverse

### ISSUE THREAD

**Issue by Louis-Cyphre** [google/guava#1973]
The inherited doc should be overridden and mentioned that containsValue works in O(1) time in contrast to O(N) with a normal HashMap.

The javadoc for #inverse should mention that it always returns the same Inverse instance and thus saving the Inverse as a separate instance variable is not mandatory to reduce overhead.

**Comment by kevinb9n** [comment]
I'll put this on my list, thanks.

On Fri, Feb 13, 2015 at 5:05 AM, Louis-Cyphre <notifications@github.com>
wrote:

> The inherited doc should be overridden and mentioned that containsValue
> works in O(1) time in contrast to O(N) with a normal HashMap.
>
> The javadoc for #inverse should mention that it always returns the same
> Inverse instance and thus saving the Inverse as a separate instance
> variable is not mandatory to reduce overhead.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/guava/issues/1973>.
>



-- 
Kevin Bourrillion | Java Librarian | Google, Inc. | kevinb@google.com

**Comment by keerthikorivi** [comment]
Is this issue approved?
