### ISSUE TITLE
Logging for EventBus

### ISSUE THREAD

**Issue by clackbib** [google/guava#1976]
Hello,

I'm working on a project that sometimes relies very heavily on bus events. Would it be possible to expose a setter which lets us provide a logger implementation, and:
1) Logs data whenever an event is posted
2) Logs data when a subscribed method is executed.

Doesn't have to be tied to logging also. Could be a simple callback:
onEventPosted(String eventName, Object eventPosted)
onMethodFired(Object receivedEvent , String ... paramsNames)

Or something similar.The goal is to easily identify which methods gets triggered when a event is posted.

**Comment by smetarom** [comment]
Hi clackbib,

I like your idea. I have similar experience, but I need it only for debugging so there was a workaround. But for logging callbacks could be useful. I would like to try to implement it and do pull request with changes. Are there more callbacks you would find useful?

**Comment by clackbib** [comment]
Got an early implementation of it here:
dc0bb0105e6cb6f8f40c1fa821293d53e4bfd734

I went ahead and just implemented an incomplete version of it. If it's something that you expect or would be valuable as a feature, i'll go ahead and clean up/ implement the rest.

**Comment by cgdecker** [comment]
I'm closing this issue because we are no longer going to be making changes to `EventBus` other than important bug fixes. The reasons we're discouraging it and some alternatives are listed in the [EventBus javadoc](https://guava.dev/EventBus).
