### ISSUE TITLE
 Present.or should "short circuit"

### ISSUE THREAD

**Issue by yhartanto** [google/guava#1978]
Currently Present.or(argument) does null check on argument causing it not to "short circuit" the or. So if a.or(b()) is called, b() will always be executed even though a isPresent(). This is not consistent to Java's standard or operator.

**Comment by thiagokronig** [comment]
.a.or( whatever() ) will always run whatever(); thats nothing you can do.

**Comment by aaylward** [comment]
You can do `[optional.or(supplier)](http://docs.guava-libraries.googlecode.com/git/javadoc/com/google/common/base/Optional.html#or%28com.google.common.base.Supplier%29)`
