### ISSUE TITLE
Add methods to Preconditions without varags - with 1 and 2 message parameters

### ISSUE THREAD

**Issue by ljubove** [google/guava#1985]
Is it planned to add to Preconditions methods checkNotNull, checkState, checkArgument with 1 or 2 arguments for string template instead of using varargs only?
for example:
public static void checkState(boolean expression, String template, Object arg1) {
        if(!expression) {
            ...
        }
    }
So new Object[] will be created only if expression is false but not each time method is called.

**Comment by cpovirk** [comment]
We finally did this, I think in 20.0.
