### ISSUE TITLE
Observable collections

### ISSUE THREAD

**Issue by beradrian** [google/guava#1987]
Wouldn't be useful to have collections that can fire events every time an element is added or removed? I can contribute code for generic collections and lists.

**Comment by lowasser** [comment]
The FriendsOfGuava wiki page (https://code.google.com/p/guava-libraries/wiki/FriendsOfGuava) mentions another library, Glazed Lists, that can do this.  It's not immediately obvious what Guava can do to improve on solutions that already exist through other libraries?

**Comment by beradrian** [comment]
I wasn't aware of it. That library contains only observable lists, not collections too. But adding other observable collection types will make sense to be added there. So I will close the issue.
