### ISSUE TITLE
Generic args of CacheLoader.from can be variant

### ISSUE THREAD

**Issue by simonmcooper** [google/guava#1993]
The two CacheLoader.from methods can be variant in their generic arguments like so:

    public static <K, V> CacheLoader<K, V> from(Function<? super K, ? extends V> function);
    public static <V> CacheLoader<Object, V> from(Supplier<? extends V> supplier);

I also think that `from(Supplier)` should take a `K` parameter, so it can be used for any variable taking a `CacheLoader<K, V>`:

    public static <K, V> CacheLoader<K, V> from(Supplier<? extends V> supplier);

**Comment by cpovirk** [comment]
See https://github.com/google/guava/issues/1927#issuecomment-68305122
