### ISSUE TITLE
Make it easier to implement Cache with similar functionality to LocalCache

### ISSUE THREAD

**Issue by ghost** [google/guava#1994]
I'm implementing my own `Cache`, and there are several features of `LocalCache` that I would like to copy that I currently can't because the relevant methods are package-access:
1. `RemovalNotification` constructor is package-private, meaning `RemovalListener` can't be used in custom caches
2. `CacheLoader.UnsupportedLoadingOperationException` is package-private, so custom caches cannot replicate the LocalCache behaviour of falling back on `load` if `loadAll` is not implemented.

Also, `AbstractCache` could do a bit more with default implementations of the `Cache` methods. For example, `get(K, Callable)` could have a basic body using `getIfPresent` and `put`, and `AbstractLoadingCache` could check for and throw `InvalidCacheLoadException` or `ExecutionException` itself when loading.

**Comment by ben-manes** [comment]
1. While ugly, the best short-term solution is to write a factory class that resides in the Guava package.
2. The reason that the `UnsupportedLoadingOperationException` is package-private is that it should never be thrown by user code. Instead the intent was to switch to using reflection to determine at configuration-time if the `loadAll` method was implemented. That would avoid the unnecessary exception bloat that occurs. I think that performance change was lost in the backlog so the rational isn't obvious.

**Comment by nglorioso** [comment]
`RemovalNotification` now has a public factory: https://guava.dev/releases/23.0/api/docs/com/google/common/cache/RemovalNotification.html

But I don't think we're at a point where all you want is public.

**Comment by cpovirk** [comment]
We're unlikely to make significant changes to common.cache. We recommend [Caffeine](https://github.com/ben-manes/caffeine).
