### ISSUE TITLE
Reduce object creation in Futures?

### ISSUE THREAD

**Issue by cpovirk** [google/guava#1995]
- Avoid allocating `rejectionPropagatingRunnable` when given an explicit `directExecutor()`? This would just be an `if()`.
- Avoid allocating `asAsyncFunction` wrapper when given a `Function`? We could parameterize `ChainingListenableFuture` and `CatchingFuture` on the actual type, and we could have a subclass for each actual type to invoke `set`/`setFuture`. (I think we have to do that or something similarly ugly, since we need for the function to be available during the constructor.)
- anything else?

**Comment by lukesandberg** [comment]
catching/catching async could use similar specialization

**Comment by cpovirk** [comment]
Everything on my list is done. I'm sure we'll find more possible improvements, but those can wait for another bug. Thanks, Luke.
