### ISSUE TITLE
JDK8: TestsForMapsInJavaUtil fails with ConcurrentHashMap

### ISSUE THREAD

**Issue by ben-manes** [google/guava#1997]
In JDK8, the entrySet view supports additions which the previous version did not. The existing tests fails due because it assumes that all collection views either support additions or disallow it. An addition through the key or value views would not make sense, while the entry view easily supported. Due to the testlib feature set not being able to distinguish the different features that the views may support, this test is not forward compatible as is.

This was discovered when using testlib to validate the `Cache.asMap()` view which should provide similar semantics except serialization support. The following additions have to be added for JDK8, but it would be nice if the features could be specified for the applicable views to avoid disabling tests.

```java
.suppressing(
    // Suppressed due to entrySet() view supporting additions, while the keySet() and
    // values() views do not. The Guava tests are unable to understand this rational.
    CollectionAddTester.class.getMethod("testAdd_unsupportedNotPresent"),
    CollectionAddAllTester.class.getMethod("testAddAll_unsupportedNonePresent"),
    CollectionAddAllTester.class.getMethod("testAddAll_unsupportedSomePresent"))
```

**Comment by cpovirk** [comment]
I think we suppressed these in 20bb6c3c898185ca87294a7e5405415b0e337543, which I think is in 18.0. Is there any chance that you have an older version?

We've been meaning to report this to upstream, as we think it's bogus: The `add()` method can't follow its contract:

    map.put("foo", 1);
    map.entrySet().add(entry("foo", 2)); // removes <foo, 1>, inserts <foo, 2>, returns false(!)

**Comment by ben-manes** [comment]
Interesting, that commit suppresses those tests for `OpenJdk6MapTests`, whereas I copied from `TestsForMapsInJavaUtil` which does not. What is the rational for the duplication between the two and is the latter enabled?

It **can** support the add contract, but you're right that there is a bug! It should be delegating to `putIfAbsent()`, which is how I implemented it. It appears that there is a typo in OpenJDK which passes `false` to the internal put's `onlyIfAbsent` method. That bug exists in Doug's CVS repo so it should be reported.

**Comment by kevinb9n** [comment]
On Thu, Mar 12, 2015 at 10:45 AM, Ben Manes <notifications@github.com>
wrote:

> Interesting, that commit suppresses those tests for OpenJdk6MapTests,
> whereas I copied from TestsForMapsInJavaUtil which does not. What is the
> rational for the duplication between the two and is the latter enabled?
>
Suppressing a test in TFMIJU means that that test *shouldn't* pass for any
java.util implementation; it's just an invalid test. Suppressing in OJ6MT
just means OpenJDK has a bug.


> It *can* support the add contract, but you're right that there is a bug!
> It should be delegating to putIfAbsent(), which is how I implemented it.
> It appears that there is a typo in OpenJDK which passes false to the
> internal put's onlyIfAbsent method. That bug exists in Doug's CVS repo so
> it should be reported.
>
The whole thing is just weird. If there was an existing value for that key,
you have to throw an exception.


-- 
Kevin Bourrillion | Java Librarian | Google, Inc. | kevinb@google.com

**Comment by ben-manes** [comment]
Closing as it appears to be my mistake of borrowing from the wrong test class.
