### ISSUE TITLE
Cache#getIfPresent() variant returning Optional

### ISSUE THREAD

**Issue by fluentfuture** [google/guava#1998]
Today I ran into a code snippet like this:

```
V value = cache.getIfPresent(key);
return (value == null) ? 0 : value.getFoo();
```

The code would have been more concise if the lookup method returned an Optional:

```
return cache.peek(key).or(defaultValue()).getFoo();
```

Could Cache be added with a method returning Optional? (Although, with Java 8 adding its own Optional, I can imagine us not investing into Guava's Optional any further).

**Comment by ben-manes** [comment]
If you are in Java 8, you could write this as

```
cache.asMap().getOrDefault(key, value.getFoo());
```

The only negative with that version is that it can't be lazy by accepting a `Supplier`.

**Comment by kluever** [comment]
I'm going to close this, as it's unlikely that we're going to add additional APIs using our own `Optional` type, and we'd prefer not to diverge the pre-Java8 fork and Java8 fork very much. There's also plenty of easy work arounds, including the `asMap()` view or just using `ofNullable(cache.getIfPresent(key)).orElse(0)`
