### ISSUE TITLE
InternetDomainName topPrivateDomain resolution error

### ISSUE THREAD

**Issue by rferreira** [google/guava#2000]
```
InternetDomainName.from("bucket.s3.amazonaws.com").topPrivateDomain()
```
 returns bucket.s3.amazonaws.com instead of "amazonaws.com". Strangely enough 
```
InternetDomainName.from("a.b.c.com").topPrivateDomain()
```
works just fine

**Comment by cpovirk** [comment]
`s3.amazonaws.com` is a public suffix, so `bucket.s3.amazonaws.com` is the top private domain. See https://publicsuffix.org/list/effective_tld_names.dat

This is similar to #1890. It's a common question that we get, so we should probably improve documentation here.

**Comment by rferreira** [comment]
thanks! I'll close this then
