### ISSUE TITLE
Documentation Error in CachesExplained, section "Interruption"

### ISSUE THREAD

**Issue by VishalRao** [google/guava#2004]
https://code.google.com/p/guava-libraries/wiki/CachesExplained#Interruption

"(wrapped in an ExceptionException)"
should probably be
"(wrapped in an ExecutionException)"

**Comment by lowasser** [comment]
I don't see the difference?

**Comment by VishalRao** [comment]
ExceptionException vs ExecutionException???

**Comment by lowasser** [comment]
Ah, that was silly.  Done.
