### ISSUE TITLE
Documentation Error in CachesExplained, section "Features"

### ISSUE THREAD

**Issue by VishalRao** [google/guava#2005]
https://code.google.com/p/guava-libraries/wiki/CachesExplained#Features

"So, for example, iterating through cache.entrySet() does not reset access time for the entries you retrieve."

should probably be

"So, for example, iterating through cache.asMap().entrySet() does not reset access time for the entries you retrieve."

**Comment by ronshapiro** [comment]
Thanks for the report! This is fixed (in the Guava Wiki). cl/171543884 internally has the fix as well for when we start syncing this all out to gh-pages.
