### ISSUE TITLE
Iterators.concat is not gc friendly

### ISSUE THREAD

**Issue by devinrsmith** [google/guava#2008]
I ran into a situation where I was using recursion and lazy iteration to emulate the in-order traversal path of a binary tree, but wasn't able to use `Iterators.concat` due to its non gc friendly implementation.

(Note: the amount of memory that should be needed to run this is `O(maxDepth)` or `O(log N)`)

Here's code to trigger the issue, and a potential solution: https://gist.github.com/devinrsmith/121d9a5ebd460c3bbaa0

**Comment by devinrsmith** [comment]
To clarify a bit:

```public static <T> Iterator<T> concat(
      final Iterator<? extends Iterator<? extends T>> inputs)```

*is* gc friendly if and only iff the given iterator is gc friendly.

The other `concat` methods are backed by `ImmutableList.iterator()` which doesn't allow `concat` to be gc friendly.

**Comment by lowasser** [comment]
If you're trying to traverse a binary tree, why not use BinaryTreeTraverser? 
http://docs.guava-libraries.googlecode.com/git/javadoc/com/google/common/collect/BinaryTreeTraverser.html

**Comment by devinrsmith** [comment]
Hi @lowasser,

That's not a bad idea for this specific example's use case... this example's use case was a bit simplified though to try and clearly isolate and illustrate the `concat` issue.

But the larger issue still stands: the helper `concat` methods aren't gc friendly. 

I should have specified this in the initial comment: the guava concat runs out of heap space, whereas my suggested modification does not.

**Comment by devinrsmith** [comment]
I've added an example that more clearly isolates the gc unfriendliness of `concat`.

https://gist.github.com/devinrsmith/121d9a5ebd460c3bbaa0#file-guavaconcatissuebigobject-java

**Comment by lowasser** [comment]
Fixed internally; fix will be mirrored out soon.
