### ISSUE TITLE
Add Functions.allAsList

### ISSUE THREAD

**Issue by orionll** [google/guava#2015]
Add a method that transforms a list of functions to a function which returns a list:

```java
public static <I, A> Function<I, List<A>> allAsList(Iterable<Function<I, A>> list)
```

**Comment by kevinb9n** [comment]
We're not inclined to add more functional APIs to Guava at this point, now that jdk 8 addresses FP so much more thoroughly.  Once Guava requires jdk 8 you may wish to re-file this as being about java.util.function.Function.  I am rather skeptical that this is will be a common need, though.
