### ISSUE TITLE
ImmutableSortedMultiset::naturalOrder has wrong generic type

### ISSUE THREAD

**Issue by ogregoire** [google/guava#2016]
Please fix the `ImmutableSortedMultiset::naturalOrder` generic type so that classes that are subclasses of classes implementing `Comparable` can be used.

Here is a snippet showing the issue:

    public class ImmutableSortedCollectionsComparison {
      public static void main(String[] args) {
        ImmutableSortedSet     <MySubComparable> sortedSet      = ImmutableSortedSet     .<MySubComparable>naturalOrder().build();
        ImmutableSortedMultiset<MySubComparable> sortedMultiset = ImmutableSortedMultiset.<MySubComparable>naturalOrder().build();
      }
    }
    class MyComparable implements Comparable<MyComparable> {
      @Override public int compareTo(MyComparable o) { return 1; }
    }
    class MySubComparable extends MyComparable { }

The line of the `ImmutableSortedSet` will compile nicely, but the one of the `ImmutableSortedMultiset` won't.

Here's the faulty signature of `ImmutableSortedMultiset::naturalOrder`:

    public static <E extends Comparable<E>> ImmutableSortedMultiset.Builder<E> naturalOrder()

And here is the expected signature:

    public static <E extends Comparable<?>> ImmutableSortedMultiset.Builder<E> naturalOrder()

Which will then be similar to the working `ImmutableSortedSet::naturalOrder`:

    public static <E extends Comparable<?>> ImmutableSortedSet.Builder<E> naturalOrder()

**Comment by ogregoire** [comment]
Given the fact that the change is rather trivial and cannot have negative impact, I was kind of hoping it would make it for the next release, but I see it doesn't.

So can someone explain why this single character change didn't make it for Guava 19 rc1?

**Comment by lowasser** [comment]
I confess that we just didn't notice this in time to pick it up.  The fix has been submitted internally; I think it should go in 19?  Not sure if we're going to have another RC...

**Comment by cgdecker** [comment]
I think we will have another RC, there's a couple `@since 19.0` things that were added around the time I made the first rc. I'll probably do the next rc in a week when I'm back from vacation.

**Comment by ogregoire** [comment]
Thank you!
