### ISSUE TITLE
Broken link: ElementCostInDataStructures

### ISSUE THREAD

**Issue by ben-manes** [google/guava#2018]
The project [memory-measurer](https://code.google.com/p/memory-measurer) was removed. Guava's documentation link [Footprint of JDK/Guava data structures](https://code.google.com/p/memory-measurer/wiki/ElementCostInDataStructures) is 403 (Forbidden).

I wanted to verify my [analysis](https://github.com/ben-manes/caffeine/wiki/Memory-overhead) using [jamm](https://github.com/jbellis/jamm). Using OpenJDK's [Java Object Layout](http://openjdk.java.net/projects/code-tools/jol/) will be the best, but due to its immaturity it isn't as easy to quickly script.

**Comment by kluever** [comment]
It's been moved here:
https://github.com/DimitrisAndreou/memory-measurer/blob/master/ElementCostInDataStructures.txt

Sorry for the confusion.

On Mon, Mar 30, 2015 at 8:13 PM, Ben Manes <notifications@github.com> wrote:

> The project memory-measurer <https://code.google.com/p/memory-measurer>
> was removed. Guava's documentation link Footprint of JDK/Guava data
> structures
> <https://code.google.com/p/memory-measurer/wiki/ElementCostInDataStructures>
> is 403 (Forbidden).
>
> I wanted to verify my analysis
> <https://github.com/ben-manes/caffeine/wiki/Memory-overhead> using jamm
> <https://github.com/jbellis/jamm>. Using OpenJDK's Java Object Layout
> <http://openjdk.java.net/projects/code-tools/jol/> will be the best, but
> due to its immaturity it isn't as easy to quickly script.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/guava/issues/2018>.
>



-- 
kak

**Comment by dimo414** [comment]
There's a broken link to this page in the sidebar still.

**Comment by kluever** [comment]
@dimo414 Which sidebar? Can you give a link please? Thanks!

**Comment by dimo414** [comment]
Sorry, "the sidebar" isn't very helpful, is it?  At the bottom of the [*Wiki* sidebar](https://github.com/google/guava/wiki) there's a link titled "Footprint of JDK/Guava data structures" that points to `http://code.google.com/p/memory-measurer/wiki/ElementCostInDataStructures`.

**Comment by kluever** [comment]
Cool, fixed. Thanks!
