### ISSUE TITLE
ExplicitOrdering of collection with 1 element doesn't throw exception

### ISSUE THREAD

**Issue by mgh520** [google/guava#2022]
the javadoc for ExplicitOrdering says it will throw a ClassCastException if any elements are not in the explicit list defined for the ordering.  However, this depends on the comparator actually getting called.  In the case of sorting a list with a single item that is not present in the explict ordering list, an exception is not thrown because the underlying call to Arrays.sort will not call the comparator for a 1 item array.

**Comment by kevinb9n** [comment]
Okay, so we *could* override methods like sortedCopy and isOrdered and add special-case code for 1-element collections. I believe we do this for a 1-element ImmutableSortedSet, 1-entry TreeMultiset, etc. In those cases it's a little more clear that we shouldn't allow "bad" elements into the collection. In these cases it seems a little less clear that it's worth the bother. But not clear that it isn't, either.
