### ISSUE TITLE
Allow use of Longs.toByteArray without allocation

### ISSUE THREAD

**Issue by brianfromoregon** [google/guava#2023]
Request for Longs.toByteArray and Ints.toByteArray (maybe others?) to add overload accepting a byte[] argument to avoid the new byte[8] allocation.

**Comment by kevinb9n** [comment]
I think this gets into the territory that ByteBuffer is already there for.

**Comment by cgdecker** [comment]
Agreed, this is what `ByteBuffer.putLong(long)` is for.

**Comment by brianfromoregon** [comment]
Ah yep, thanks!
