### ISSUE TITLE
CharSource to CharSink line by line

### ISSUE THREAD

**Issue by orionll** [google/guava#2027]
Sometimes it is necessary to replace line endings in some text with platform line endings. One way to do it is to call CharSource.readLines() and then pass the returned list to CharSink.writeLines(). While this   solves the problem, this is not very efficient, because it allocates an intermediate ImmutableList which can be huge.

It would be nice to have a method CharSource.writeLinesTo(CharSink), which does the same job without allocating an intermediate list.

**Comment by cgdecker** [comment]
This feels like a relatively uncommon use case to me, and something that would just be confusing for most people who should probably be using `CharSource.copyTo(CharSink)` instead.

You can of course already do this yourself relatively easily like this:

```java
try (final Writer writer = sink.openStream()) {
  source.readLines(new LineProcessor<Void>() {
    @Override public boolean processLine(String line) throws IOException {
      writer.write(line);
      writer.write(System.getProperty("line.separator"));
      return true;
    }

    @Override public Void getResult() {
      return null;
    }
  });
}
```
