### ISSUE TITLE
Iterables.transform and Suppliers.compose are inconsistent

### ISSUE THREAD

**Issue by simonmcooper** [google/guava#2028]
`Iterables.transform` and `Iterators.transform` are declared like so:

```
public static <F, T> Iterator<T> transform(Iterator<F> fromIterator, Function<? super F, ? extends T> function);
public static <F, T> Iterable<T> transform(Iterable<F> fromIterable, Function<? super F, ? extends T> function);
```

`Suppliers.compose` is declared like so:

```
public static <F, T> Supplier<T> compose(Function<? super F, T> function, Supplier<F> supplier);
```

These 3 methods are conceptually doing the same thing - taking values out of a 'producer' object (iterator/iterable/supplier) and lazily transforming them using a function. So they should all look the same, and in particular, have arguments in the same order.

To make them consistent, I suggest that `Suppliers.compose` is deprecated in favour of the following method:

```
public static <F, T> Supplier<T> transform(Supplier<F> supplier, Function<? super F, ? extends T> function);
```

**Comment by lowasser** [comment]
FWIW, Suppliers.compose matches Functions.compose, which is also a reasonable point of comparison?  A Supplier seems as much like an argumentless Function as it seems like an Iterable/Iterator.

**Comment by orionll** [comment]
Transformation and composition are different things:
* Transformation is a mapping from A → B to F<A> → F<B>, where F is a functor (e.g. Iterable, List, Iterator).
* Composition is the result of combining A → B and B → C (which gives A → C).

However, Supplier<A> can be treated as both a function of type () → A and a functor. This means that:
* Suppliers.compose should definitely not be deprecated, because Supplier is a function.
* Suppliers.transform would make sense.

**Comment by cpovirk** [comment]
We discussed this almost 4 years ago but didn't have the motivation to do anything about it :)

I strongly agree that "compose" is a bad name here. I can see the case that "composition" is technically a broad enough concept to cover this, but "composition" is technically a broad enough to cover all sorts of methods, e.g., `Iterables.transform`. It's *too* generic. Better to restrict it to the case in which both inputs are functions that accept a "real" input.

If we could justify the effort, I would like to see:

- `Suppliers.compose` -> `Suppliers.transform`
- `Predicates.compose` -> `Predicates.onResultOf` (while we're stamping out "compose")

But again, I don't know how much effort it's worth spending on these classes. What is their future in the JDK8 world?

**Comment by cpovirk** [comment]
(Well... I'm not sure if `onResultOf` works well as a two-parameter static method. It *might* still be better than what we have, but it's not as good a name here as it is as an instance method on `Ordering`.)

**Comment by cpovirk** [comment]
Much as I regret various things about this, we're stuck with it. Sorry.
