### ISSUE TITLE
Collections should override spliterator()

### ISSUE THREAD

**Issue by cowwoc** [google/guava#2029]
Because Guava's collection classes (e.g. `ImmutableList`) do not override `spliterator()` they inherit the default implementation which has a characteristics of `SIZED` and `SUBSIZED`. This means that they cannot be used for parallel processing with ForkJoin.

Expected behavior: `Immutable*` should provide a more efficient `spliterator()` implementation.

**Comment by lowasser** [comment]
This will absolutely be part of Guava as soon as we support Java 8, but I'm not sure there is much we can do until then?

**Comment by cowwoc** [comment]
I found posts going back 1-2 years talking about adding Java8 support in the near future: http://www.reddit.com/r/java/comments/1y9e6t/ama_were_the_google_team_behind_guava_dagger/cfjd2qi and https://groups.google.com/forum/#!topic/guava-discuss/fEdrMyNa8tA

Is there an open issue tracking this work?

Is there a short-term workaround I can use in the meantime?

**Comment by lowasser** [comment]
I don't think so - the primary issue is Google internal?

As it stands, for essentially all immutable collections, a good implementation is

IntStream.range(0, collection.size()).mapToObj(collection.asList()::get)

**Comment by cowwoc** [comment]
> The primary issue is Google internal?

I don't understand the question.

> As it stands, for essentially all immutable collections, a good implementation is
>
> IntStream.range(0, collection.size()).mapToObj(collection.asList()::get)

This won't do because `spliterator().characteristics()` will return `ORDERED | SIZED | SUBSIZED`. It is missing `IMMUTABLE`.

**Comment by lowasser** [comment]
The Google internal Comment was a statement, not a question.

I'm not certain the IMMUTABLE characteristic is actually used for anything?  That should still be an adequate substitute for most use cases I can think of...

**Comment by cowwoc** [comment]
> The Google internal Comment was a statement, not a question.

It had a question mark after it... :)

> I'm not certain the IMMUTABLE characteristic is actually used for anything?

Agreed. I thought that this was being used for parallelization but it looks like it is not. So for now I don't have a concrete use-case for this characteristic.

> That should still be an adequate substitute for most use cases I can think of...

Okay, but it is worth noting that the only characteristic it adds over the default is `ORDERED`. That said, it is useful for clients that wishs to jump to the end of a list: http://stackoverflow.com/a/29553490/14731.
