### ISSUE TITLE
Could we add a getFirstValue(K key) method to Multimap and return Optional<V>

### ISSUE THREAD

**Issue by songofsp3** [google/guava#2035]
In some cases, I know that there will be at most one value for some key in a multimap, and it is pretty annoying to get the value out by the iterator and then check hasNext() and get by next(), especially if the multimaps are nested in each other.

could we wrap it and provide a method on Multimap
public Optional<V> getFirstValue(K key);
Just return the first Value by Iterator or Absent.

Similar to XMLNode.getFirstChild()

**Comment by kluever** [comment]
Multimap.get() never returns null (it'll return an empty collection if there isn't a mapping).

Optional<T> value = Optional.fromNullable(Iterables.getFirst(multimap.get(key), null));

**Comment by kluever** [comment]
Also I should mention that changing the Multimap interface is basically a non-starter at this point. It's non-@Beta and it would cause immense pain to all of our open source users.
