### ISSUE TITLE
Optional.hashCode()

### ISSUE THREAD

**Issue by alexei-zaycev** [google/guava#2037]
Uncorrect hashCode() implementation at com.google.common.base.Absent and com.google.common.base.Present - for example if hashCode() of reference at Present return 0 then it hashCode() equal Absent.

example: Optional.absent() has same hash code as Optional.of(0.0) or Optional.of(0)

**Comment by kevinb9n** [comment]
Oops. This was probably my mistake.

We can fix this by changing Absent.hashCode() to return some other random
number.

On Mon, Apr 20, 2015 at 4:04 AM, Alexei <notifications@github.com> wrote:

> Uncorrect hashCode() implementation at com.google.common.base.Absent and
> com.google.common.base.Present - for example if hashCode() of reference at
> Present return 0 then it hashCode() equal Absent.
>
> example: Optional.absent() has same hash code as Optional.of(0.0) or
> Optional.of(0)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/guava/issues/2037>.
>



-- 
Kevin Bourrillion | Java Librarian | Google, Inc. | kevinb@google.com

**Comment by lowasser** [comment]
For what it's worth, this isn't actually *wrong* per se, and there will always be Optional.present values with the same hash as Optional.absent.  We can certainly make it a rarer case, though?

**Comment by kevinb9n** [comment]
Right.  The standard we have tried to apply is that "at least there
shouldn't be an obvious / trivially explained way to generate collisions."

So it's okay if Optional.of(6639813) collides with absent(), but
Optional.of(emptySet) colliding with absent() is pretty sad.



On Mon, Apr 20, 2015 at 12:35 PM, Louis Wasserman <notifications@github.com>
wrote:

> For what it's worth, this isn't actually *wrong* per se, and there will
> always be Optional.present values with the same hash as Optional.absent. We
> can certainly make it a rarer case, though?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/guava/issues/2037#issuecomment-94548795>.
>



-- 
Kevin Bourrillion | Java Librarian | Google, Inc. | kevinb@google.com

**Comment by kevinb9n** [comment]
(Another way to explain what we're shooting for is that collisions should
only happen via dumb luck.)


On Mon, Apr 20, 2015 at 12:38 PM, Kevin Bourrillion <kevinb@google.com>
wrote:

> Right.  The standard we have tried to apply is that "at least there
> shouldn't be an obvious / trivially explained way to generate collisions."
>
> So it's okay if Optional.of(6639813) collides with absent(), but
> Optional.of(emptySet) colliding with absent() is pretty sad.
>
>
>
> On Mon, Apr 20, 2015 at 12:35 PM, Louis Wasserman <
> notifications@github.com> wrote:
>
>> For what it's worth, this isn't actually *wrong* per se, and there will
>> always be Optional.present values with the same hash as Optional.absent. We
>> can certainly make it a rarer case, though?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/google/guava/issues/2037#issuecomment-94548795>.
>>
>
>
>
> --
> Kevin Bourrillion | Java Librarian | Google, Inc. | kevinb@google.com
>



-- 
Kevin Bourrillion | Java Librarian | Google, Inc. | kevinb@google.com
