### ISSUE TITLE
Possible duplicate tests? - testElapsed_millis() and testElapsedMillis()

### ISSUE THREAD

**Issue by daveschaefer** [google/guava#2039]
Hello, I was reading through the set of tests at https://github.com/google/guava/blob/master/guava-tests/test/com/google/common/base/StopwatchTest.java , and I noticed there are two tests that appear to do the same thing - testElapsed_millis() and testElapsedMillis(). Is this expected? Could one test perhaps be an old test under a different naming convention? From the history it looks like they were added independently.

The contribution guide recommends creating an issue as the first step, so I thought I would ask.

GitHub suggests that both functions are only called from guava-gwt/test/com/google/common/base/StopwatchTest_gwt.java . Would it be appropriate to create a pull request to remove one of the tests? (Or of course, feel free to simply remove one yourself if the workflow is easier; I just wanted to ask)

Cheers!

**Comment by kluever** [comment]
This is probably my fault. We used to have 2 APIs:
Stopwatch.elapsedMillis()
Stopwatch.elapsed(TimeUnit)

When cleaning up elapsedMillis(), I probably just migrated it to elapsed(MILLISECONDS) and left the old test. I'll get it fixed up.

**Comment by kluever** [comment]
There were a few other redundant tests in that file...nuked em all. It should be mirrored upstream in a few days.

Thanks!

**Comment by daveschaefer** [comment]
@kluever Hey, fantastic! :) Thanks for the fast reply. Wasn't trying to assign any blame; just asking questions ;)

Thanks very much!

**Comment by daveschaefer** [comment]
@kluever Hello again,

Thanks very much for the fixes :)

Reading through the tests it seems like there might still be some possible duplication - `testStop_new()` and `testStop_alreadyStopped()` seem to be doing mostly the same thing. Would you be interested in a pull request to combine those two tests? I can create a new issue for that if you prefer.

I also noticed that the `StopwatchTest` class starts with

    private final Stopwatch stopwatch = new Stopwatch(ticker);

, but according to the `Stopwatch` class docs, the `Stopwatch()` style constructors are deprecated. Should the `StopwatchTest` class be using the `createUnstarted()` interface to create its private variables instead?

Lastly, some tests - such as `testElapsed_multipleSegments()` - have multiple uses of numbers where they check things like "9 + 25 should equal 34". Would it be appropriate/would you be interested in a pull request to use some variables for those, to make sure that matching numbers will always be the same?

e.g. rather than

    ticker.advance(9);
    ..
    ticker.advance(25);
    ..
    assertEquals(34, stopwatch.elapsed(NANOSECONDS));

something like

    long firstAdvance = 9;
    long secondAdvance = 25;
    assertEquals(firstAdvance + secondAdvance, stopwatch.elapsed(NANOSECONDS));


Would that improve maintainability? Or just make it more unreadable? I tried to find a preference in the [Google Java Style doc](https://google-styleguide.googlecode.com/svn/trunk/javaguide.html) but perhaps I'm missing something.


Thanks for your time, let me know if you have thoughts.

**Comment by kluever** [comment]
Re. the other duplication in that test...I already deleted those when I removed the first test you mentioned.

Re. the constructors: it's not a big deal...but I'll end up fixing that at some point when the constructors become private (and thus that line will no longer compile).

This issue can probably stay closed.

Thanks!

**Comment by daveschaefer** [comment]
Aha! Thanks for the fast reply. I had assumed that your commit of 08a3fbf meant that https://github.com/google/guava/blob/master/guava-tests/test/com/google/common/base/StopwatchTest.java was back to being HEAD revision code. If you've already sorted out `testStop_new()` and `testStop_alreadyStopped()` then awesome.

Thanks!
