### ISSUE TITLE
AsyncEventBus  with  CyclicBarrier

### ISSUE THREAD

**Issue by fromcth** [google/guava#2049]
hi，  

I use AsyncEventBus  in my project , and sometime i want  the AsyncEventBus   have  "CyclicBarrier " function.  

Can guava write a  version of  "AsyncEventBusWithCyclicBarrier" ?  or  make the "subscribersByType， EventSubscriber" class public , so  i can override AsyncEventBus's dispatch function  by myself

best wishes

**Comment by lukesandberg** [comment]
What would this do?  just provide a way for the posting thread to wait for all listeners to receive the event?

**Comment by Rexh** [comment]
No，I mean all listeners wait each other，one listener complete it's job, wait others , until  all listeners done.
But in class AsyncEventBus, the method "dispatch" only new Runnable function ,then i lose the controll.

so ，I want  simply post  many event, and all event complete it's job,  then main thread go on,like "CyclicBarrier" mode.

thx for your reply！
best wishes

**Comment by Rexh** [comment]
@lukesandberg  Can u  help me ? thx~~

**Comment by nglorioso** [comment]
We're unlikely to add significant features to EventBus anymore.
