### ISSUE TITLE
ImmutableMap.Builder should have a public constructor which takes an initial capacity

### ISSUE THREAD

**Issue by rgolden** [google/guava#2051]
When I use the builder and put multiple entries into the map, the capacity keeps getting resized. I know the desired capacity before hand, so should be able to construct an immutable map of the correct size, and avoid this performance tax.

The builder already has a package private capacity constructor. I can not find documentation as to why this is not public (https://code.google.com/p/memory-measurer/wiki/ElementCostInDataStructures may have explained, but it is no longer available).

**Comment by azarudeen90** [comment]
Thumbs on this suggestion. Yeah by defining the initial size cosf of adding the each entry in a map will be reduced in time complexity in expanding the bucket

**Comment by slovdahl** [comment]
This would be really useful. And same thing goes for all other Immutable* classes.

**Comment by schlosna** [comment]
Having the ability to to specify the capacity for builders when known a priori would be very beneficial for us.

**Comment by lowasser** [comment]
Dupe of https://github.com/google/guava/issues/196

**Comment by rgolden** [comment]
Verified #196 is a duplicate of my request. Closing this issue.
