### ISSUE TITLE
Don't swallow interruption state in Throwables.propagate

### ISSUE THREAD

**Issue by electrum** [google/guava#2054]
When using `Throwables.propagate` with a method that throws `Exception` or `Throwable`, using it properly requires some boilerplate to avoid swallowing `InterruptedException`. An example of such a method is `MethodHandle.invoke`. While it is true that such a method is very unlikely to throw `InterruptedException`, the pedant in me requires handling it correctly. It would be nice if this check could be added to `propagate`.

```java
try {
    method.invoke();
}
catch (Throwable t) {
    if (t instanceof InterruptedException) {
        Thread.currentThread().interrupt();
    }
    throw Throwables.propagate(t);
}

**Comment by cpovirk** [comment]
Would you take a look at http://stackoverflow.com/a/12824556 (mostly the "Then again, consider this caller, which catches ExecutionException e..." part) and let me know what you think?

**Comment by cpovirk** [comment]
We have begun working to remove `Throwables.propagate`, so I'm marking this as obsolete.
