### ISSUE TITLE
Collections

### ISSUE THREAD

**Issue by vrstest** [google/guava#2056]
Guava should improve sorting. in a way that the every type of list is supported. like right now ArrayList are supported. it should the same with CopyOnWriteArrayList.

**Comment by kluever** [comment]
Sorry - I don't understand your request. java.util.Collections.sort() let's you sort any List (not just ArrayList).

CopyOnWriteArrayList<String> cowal = ...;
Collections.sort(cowal);

Note that sorting a CopyOnWriteArrayList might be wildly inefficient because it, well, copies the underlying array on every mutate. Is that what you're asking about?

**Comment by cgdecker** [comment]
Actually, I think `Collections.sort` doesn't work on a `CopyOnWriteArrayList` since it uses `ListIterator.set`, and `CopyOnWriteArrayList`'s `ListIterator` is a snapshot that doesn't support `set`.

**Comment by kevinb9n** [comment]
That sounds like a straight-up JDK bug, then?

On Thu, May 21, 2015 at 8:26 AM, Colin Decker <notifications@github.com>
wrote:

> Actually, I think Collections.sort doesn't work on a CopyOnWriteArrayList
> since it uses ListIterator.set, and CopyOnWriteArrayList's ListIterator
> is a snapshot that doesn't support set.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/guava/issues/2056#issuecomment-104318922>.
>



-- 
Kevin Bourrillion | Java Librarian | Google, Inc. | kevinb@google.com

**Comment by cgdecker** [comment]
It's not technically a bug since apparently `Collections.sort` does specify this:

> Throws:
> UnsupportedOperationException - if the specified list's list-iterator does not support the set operation.

**Comment by kluever** [comment]
Related:
http://www.javacreed.com/sorting-a-copyonwritearraylist/
http://comments.gmane.org/gmane.comp.java.jsr.166-concurrency/933

**Comment by vrstest** [comment]
Yes, I know about that. See here's an example. 
I am making an application. which contains heavy real-time updates. so it uses more memory and guava's collection is more fast than androids built-in.

So i can use ArrayList to sort, No Matter but i did try that, Takes huge amount of memory and time. It always gives Fatal-Exception of Non-Thread safe operations. See after sometime i tried CopyOnWriteArrayList to avoid non-thread safe operations. But you can't Sort them with Collections it will generate UnsupportedOperationException.

So making more loops in actual code is more costly and while theres no Guava usage need then because we can use CopyOnWriteArrayList for no Exceptions and can sort with iterators. if it's durable so i can suggest that guava can implement Sorting for More ArrayListTypes inbuilt. 

Thanks.

**Comment by lowasser** [comment]
@vrstest There is no thread-safe way to sort CopyOnWriteArrayList given its exposed API.  I'm not sure what you'd want us to do that would actually solve your problem.

It sounds, though, like you need to build your application to be actually thread-safe, perhaps using synchronization.
