### ISSUE TITLE
WeakHashMap

### ISSUE THREAD

**Issue by ensirius** [google/guava#2057]
I like to create new collections using static classes like Maps, Lists, Sets, but guava missies some types of collections. For example WeakHashMap. Do it's done for some purpose?

**Comment by lowasser** [comment]
`MapMaker.weakKeys().makeMap()` ?

**Comment by cgdecker** [comment]
In general, with methods like `Maps.newHashMap()`, I think we only intended to provide the most commonly used types. And with Java 7, the static factory methods are mostly redundant: the diamond operator allows you to write `new WeakHashMap<>()` to avoid repeating the type arguments, so we're almost certainly not going to add new static factory methods like `Maps.newHashMap()` in the future.

**Comment by kevinb9n** [comment]
Louis has it. This is a superior choice to WeakHashMap.

On Thu, May 21, 2015 at 10:01 AM, Louis Wasserman <notifications@github.com>
wrote:

> MapMaker.weakKeys().makeMap() ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/guava/issues/2057#issuecomment-104355121>.
>



-- 
Kevin Bourrillion | Java Librarian | Google, Inc. | kevinb@google.com
