### ISSUE TITLE
Skips null values from ComparisonChain

### ISSUE THREAD

**Issue by javlaks** [google/guava#2061]
It would be great if it were possible to ignore null values received in the ComparisonChain class.

I solve this problem by using the Optional class, but it would be better to use a condition to ignore null values of comparison

**Comment by cpovirk** [comment]
Can you go into some more detail about what you're looking for? A common pattern for dealing with null values is to pass a custom comparator:

    .compare(left.getCreateDate(), right.getCreateDate(), Ordering.natural().nullsFirst())

**Comment by javlaks** [comment]
I have a class "MyClass" that is filled from a sql query. It has 3 String fields: equip, family and shift. That class implements Comparator<MyClass> and I use ComparisonChain that compares equip, family and shift, in that order.

Well, the query returns some null values for Equip, of 100 elements, 5 has null values for equip. So the ComparisonChain throws a NullPointerException.

So, I use a Optional<String> to replace the null values with empty, just to continue the comparison correctly.

But, if the ComparisonChain has the ability to test null values before compare the values, this doesn't throws the NullPointerException, and it doesn't break the code.

I don't know, but I think that with a boolean parameter passed to constructor to define if the ComparisonChain needs test for null values before it do the comparison. And with this our code will be less.

**Comment by kevinb9n** [comment]
It wouldn't know whether you want the nulls to go first or last... why not
just do what Chris is suggesting?

On Thu, May 28, 2015 at 12:53 PM, Víctor Pineda <notifications@github.com>
wrote:

> I have a class "MyClass" that is filled from a sql query. It has 3 String
> fields: equip, family and shift. That class implements Comparator and I use
> ComparisonChain that compares equip, family and shift, in that order.
>
> Well, the query returns some null values for Equip, of 100 elements, 5 has
> null values for equip. So the ComparisonChain throws a NullPointerException.
>
> So, I use a Optional to replace the null values with empty, just to
> continue the comparison correctly.
>
> But, if the ComparisonChain has the ability to test null values before
> compare the values, this doesn't throws the NullPointerException, and it
> doesn't break the code.
>
> I don't know, but I think that with a boolean parameter passed to
> constructor to define if the ComparisonChain needs test for null values
> before it do the comparison. And with this our code will be less.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/guava/issues/2061#issuecomment-106578950>.
>



-- 
Kevin Bourrillion | Java Librarian | Google, Inc. | kevinb@google.com

**Comment by lowasser** [comment]
I'm with Chris and Kevin -- this should be easily addressable just by comparing the nullable values with Ordering.natural().nullsFirst() or nullsLast().

**Comment by javlaks** [comment]
Yeah, that solution is good. I just wanted to simplify the third parameter, but it's ok.

Thanks my friends! ;)

**Comment by lowasser** [comment]
It's not clear whether users would actually want nullsFirst or nullsLast.  Keeping it this way lets users make the choice explicitly and follows the principle of least surprise.
