### ISSUE TITLE
Provide EvictingQueue::of method for easier testing

### ISSUE THREAD

**Issue by scr** [google/guava#2065]
As a follow up to https://github.com/google/guava/issues/2064, for testing, it would be handy to have

`EvictingQueue.of(1,2,3,4,5)` that would just create a new EvictingQueue of size 5 with the passed in elements.

Something like this, perhaps:

```
class EvictingQueue {
    //...
    public static <T> EvictingQueue<T> of(Collection<T> elements) {
        EvictingQueue<T> ret = EvictingQueue.create(elements.size());
        ret.addAll(elements);
        return ret;
    }

    public static <T> EvictingQueue<T> of(T... elements) {
        return EvictingQueue.of(Arrays.asList(elements));
    }
}
```

**Comment by kevinb9n** [comment]
Sounds at least reasonable.

I always feel weird about the use of the factory method name "of" for a *mutable* collection type. It seems wrong when what you're really expressing is just "*initially* containing" -- and in this case it's something a bit less than that. (Ironically, it was a mutable collection type (EnumSet) that created that naming precedent in the first place.)

**Comment by kevinb9n** [comment]
Actually, now I'm wondering:  just why does it make sense to create a hard-coded EQ, whether in a test or not?

**Comment by kluever** [comment]
I searched through google's internal code base and could only find 1 potential user of these static factory methods. I don't think we have enough supporting use cases to proceed with this issue.

Thanks for submitting it though!
