### ISSUE TITLE
containsIgnoreCase method for collection of strings

### ISSUE THREAD

**Issue by jefjos** [google/guava#2066]
To check if a list of strings contains the input string case-insensitively.

List<String> lisr= new List<String>();
list.add("Apple")t
list.add("Orange");
list.add("Mango");
if(list.containsIgnoreCase("ApPle")) {
   System.out.println("List contains input string");
}

This should print the output "List contains input string"

**Comment by lowasser** [comment]
I don't expect this to get very far, for a couple reasons:

- easy in Java 8: iterable.stream().anyMatch("ApPle"::equalsIgnoreCase)
- the logic used in Java's equalsIgnoreCase is noticeably problematic; it tries to deal with more than ASCII and doesn't do a very good job of it; you either want to be using Ascii.equalsIgnoreCase or something significantly more sophisticated for all of Unicode; Guava doesn't really try to address this itself
- this would be more usefully/broadly expressed as a general Predicate passed to Iterables.any
