### ISSUE TITLE
Add FluentSource wrapping up CharSource into an object source

### ISSUE THREAD

**Issue by freddfy** [google/guava#2069]
Just like a `FluentIterable` to `Iterable`, a `FluentSource` may wrap a `CharSource` into an "object source" and provide fluent interfaces for further operations like transform (by `Function`), filter (by `Predicate`)...etc. 

The use case being usually it is more convenient to marshall the source content into higher level objects to be processed accordingly.

Even though I understand codes come later than discussion, but I reckon starting with some simple code snippets like below may save thousand words of description:

``` java

FluentSource.splitOn(CharSource.wrap("1,2,3,4,5,6"), ",")
                .transform(toInteger())
                .filter(isEven())
                .readAll(sum()) //12, i.e. 2 + 4 + 6

```

**Comment by netdpb** [comment]
As of v22, `CharSource.lines()` returns a `Stream<String>` (although that's still `@Beta`). I think that is close enough to what you're asking for here (although splitting on lines, not arbitrary strings), so I'll close this request. Please reopen it if you think there's a strong use case that isn't covered.
