### ISSUE TITLE
Guava-testlib 18 uses Truth APIs that are deleted in 0.25+ releases of Truth

### ISSUE THREAD

**Issue by cgruber** [google/guava#2073]
Guava 18 uses Truth, but truth is not API stable, so using it in an intermediary library like Guava-testlib is problematic - it forces that fragility onto non-guava consumers of our testlibs.

For Guava 19, we should remove use of Truth within the testlib, since it's a convenience for us, but only marginally helpful to users of guava-testlib.

For Guava 18, it is broken for anyone who attempts to upgrade to a version of Truth past 0.24. We should consider rolling an 18.0.1 of guava-testlib to rectify this, so that existing users are not hampered.

**Comment by cgruber** [comment]
I think an 18.0.1 quick-release of testlib-only on a branch is probably not too burdensome, and we can unblock people from waiting for a fix in 19.

**Comment by cgdecker** [comment]
Truth dependency removed from testlib in e9a23fe5ef043723c428a47ca96049306fcf813d.
