### ISSUE TITLE
Javadoc documentation of method AbstractMapBasedMultiset.add(Integer, int)

### ISSUE THREAD

**Issue by AlbertoGoffi** [google/guava#2074]
When the method `AbstractMapBasedMultiset.add(Integer, int)` is invoked with a negative number as second argument, an `IllegalArgumentException` is thrown.

Example:
```
HashMultiset<Integer> multiset = HashMultiset.create();
multiset.add(1, -10);
```
This behavior is reasonable, but not specified in the Javadoc comment of the method. Do you think it should be described in the Javadoc?

**Comment by kluever** [comment]
`AbstractMapBasedMultiset` isn't a public type. The `add(E, int)` method is defined in `Multiset.java`, which specifies:

```
@throws IllegalArgumentException if {@code occurrences} is negative, or if
    this operation would result in more than {@link Integer#MAX_VALUE}
    occurrences of the element
```
