### ISSUE TITLE
MoreExecutors: submitAsync(Executor, AsyncCallable), submit(Executor, Callable)

### ISSUE THREAD

**Issue by cpovirk** [google/guava#2076]
I looked at ~30 callers of `Futures.dereference`, and about a third of them were implementing something like this. (A lot of the rest were doing `dereference(transform(...))`, which should be `transformAsync(...)`, so the `submit` case might be the majority of "good" use cases.

There was at least one person writing `dereference(schedule(...))`, so `dereference` may yet have reason to live.

**Comment by cpovirk** [comment]
@lukesandberg adds: "I guess we could create an `TrustedListenableFutureAsyncTask` that calls `setFuture` instead of set much like the difference between `transform` and `transformAsync`."

Also, I'm wondering if `submitAsync` is a better name, given that (IIRC) all our other `AsyncFunction`/`AsyncCallable` methods have the `Async` suffix (albeit to keep them from being overloads of the `Callable` versions, which isn't a concern here).

We should also decide whether `MoreExecutors` or `Callables` is a better place for this. I would think `MoreExecutors` (home of `invokeAnyImpl`, the closest analog to this method).

**Comment by cpovirk** [comment]
@lukesandberg also suggests that we may want `submit(Executor, Callable)` for users who have an `Executor` rather than an `ExecutorService`. Currently these users have to use `ListenableFutureTask` manually. (And I have some thoughts about that, which I've dumping in a posting on similar issue #1989.)

**Comment by cpovirk** [comment]
People also call `dereference(ScheduledExecutorService.schedule(task))`, so we may need to provide a method for that, too.

**Comment by cpovirk** [comment]
I think my March 22 comment may be saying something that was already covered by my initial report :)

Anyway, it appears to be possible to hack around that problem by writing `executor.schedule(doNothing()).transformAsync(ignored -> executeTheTask(), executor)` -- or perhaps other formulations, but at least one tempting one, `executor.schedule(task).transformAsync(x -> x, executor)`, is not going to propagate cancellation in some cases, much like the current `dereference` version is not!). But we could also consider adding `MoreExecutors.scheduleAsync(ScheduledExecutorService, long, TimeUnit, Callable)`.

**Comment by cpovirk** [comment]
Update: We added `submitAsync` (though to `Futures`) in 23.0:

https://google.github.io/guava/releases/snapshot-jre/api/docs/com/google/common/util/concurrent/Futures.html#submitAsync-com.google.common.util.concurrent.AsyncCallable-java.util.concurrent.Executor-

**Comment by netdpb** [comment]
So, @cpovirk, is this issue now fixed?

**Comment by cpovirk** [comment]
`submitAsync` is in; `submit` is not. There's a submitted API Review doc about it, but I need to give it some attention, mostly to think about parameter order.

**Comment by cpovirk** [comment]
We subsequently added `submit` in Guava 28.2.
