### ISSUE TITLE
InternetDomainName: Include percent decoding during normalization

### ISSUE THREAD

**Issue by ericedens** [google/guava#2078]
`com.google.common.net.InternetDomainName` performs a couple of useful normalizations: converting to lowercase and replacing Unicode dot separators with an Ascii period.

An additional normalization -- which is supported by the WHATWG URL spec, RFC 3986, and Chrome -- is percent decoding. Here are some examples:

    %47ithub.com => github.com
    github%2ecom => github.com

Without percent decoding, `InternetDomainName.from` throws an IllegalArgumentException.

**References:**
RFC 3986:
   2.4.  When to Encode or Decode:
   https://www.ietf.org/rfc/rfc3986.txt

   When a URI is dereferenced, the components and subcomponents
   significant to the scheme-specific dereferencing process (if any)
   must be parsed and separated before the percent-encoded octets within
   those components can be safely decoded, as otherwise the data may be
   mistaken for component delimiters.  The only exception is for
   percent-encoded octets corresponding to characters in the unreserved
   set, which can be decoded at any time.  For example, the octet
   corresponding to the tilde ("~") character is often encoded as "%7E"
   by older URI processing implementations; the "%7E" can be replaced by
   "~" without changing its interpretation.
   
   unreserved  = ALPHA / DIGIT / "-" / "." / "_" / "~"
   
 
 WHATWG:
   3.3. Host parsing
   https://url.spec.whatwg.org/#host-parsing
   
   3. Let domain be the result of utf-8 decode without BOM on the percent decoding of utf-8 encode on input.

**Comment by swankjesse** [comment]
Presumably `InternetDomainName` is not assuming the input is a partial URI. The URL API should do the percent decoding.

**Comment by ericedens** [comment]
One goal of `InternetDomainName`, though, is to determine if the input string *could* be an addressable domain. 

>  might browsing to {@code "http://xxx/"} result in a webpage being displayed? 

Which suggests that [%47ithub.com](http://%47ithub.com) should return true.

Regarding where this type of normalization should occur, I agree that it could happen during while parsing a URL. A candidate domain name could come from somewhere else -- user input, web crawl, etc --  which is maybe why the class already does these other normalizations:

    // * ASCII characters to lowercase
    // * All dot-like characters to '.'
    // * Strip trailing '.'

**Comment by ericedens** [comment]
Hmm, it sounds like there's not a lot if interest here, so I'll go ahead and close this.
