### ISSUE TITLE
Guava can't be compiled by JDT

### ISSUE THREAD

**Issue by GerardPaligot** [google/guava#2082]
I'm a [Spoon](https://github.com/INRIA/spoon) contributor, an open source project to analyse and transform Java source code. This project have a dependency to [JDT](https://eclipse.org/jdt/) to compile target source code. Recently, I tried to analyse Guava with Spoon but JDT can't compile our project.

What is the problem?

In [`ImmutableMap`](https://github.com/google/guava/blob/master/guava/src/com/google/common/collect/ImmutableMap.java) class, we have these methods:

```java
// If the map is an EnumMap, it must have key type K for some <K extends Enum<K>>.
@SuppressWarnings({"unchecked", "rawtypes"})
private static <K, V> ImmutableMap<K, V> copyOfEnumMapUnsafe(Map<? extends K, ? extends V> map) {
	return copyOfEnumMap((EnumMap) map);
}

private static <K extends Enum<K>, V> ImmutableMap<K, V> copyOfEnumMap(EnumMap<K, ? extends V> original) {
	EnumMap<K, V> copy = new EnumMap<K, V>(original);
	for (Map.Entry<?, ?> entry : copy.entrySet()) {
		checkEntryNotNull(entry.getKey(), entry.getValue());
	}
	return ImmutableEnumMap.asImmutable(copy);
}
```

This code is valid but there is an error from JDT:

> Type mismatch: cannot convert from `<Enum<Enum<K>>>` to `<K>`

Before the creation of this issue, I reported the bug in the bugtracker of JDT (issue [here](https://bugs.eclipse.org/bugs/show_bug.cgi?id=469404)). In 2 words, the conclusion was that: "Yes, JDT don't support this usage of Java but there is a better practice". This better practice is explained [here](https://bugs.eclipse.org/bugs/show_bug.cgi?id=469404#c3):

```java
private static <K extends Enum<K>> ImmutableMap<K, V> copyOfEnumMap(EnumMap<K, ? extends V> original) {
	return copyOfEnumMap((EnumMap<K,?>) map);
}
```

I tried some tricky solutions but, unfortunately, this solution can't be applied in your project. So I come to notify you that your project can't be compiled by JDT.

**Comment by cpovirk** [comment]
I'm surprised that we haven't heard about this from internal Eclipse users. Thanks for pointing it out.

We might as well got off raw types where we can. I've found another approach that I'll submit shortly.

**Comment by eamonnmcmanus** [comment]
It seems that the bug is new in the Eclipse compiler since the introduction of support for Java 8. I'm guessing internal users who might have looked at this code with Eclipse aren't on a version with that support yet.
