### ISSUE TITLE
Add pluggable hashCode()/equals() support to MapMaker

### ISSUE THREAD

**Issue by archiecobbs** [google/guava#2084]
*Motivating example*: Suppose you want a `Map` with `byte[]` keys, where the keys are compared by array contents (e.g., "deep equals").

You can't used any normal hash-based `Map` implementation because those hash and compare using `hashCode` and `equals()`, which for `byte[]` arrays uses object identity, not array contents. The only option is to use e.g. `TreeMap` and supply a custom comparator. But `TreeMap` requires a lot more memory per entry, provides unnecessary sorting, and moreover this workaround doesn't always work: in some cases, your keys may not have any total ordering at all.

I've encountered this problem repeatedly: I want a `HashMap` of some objects but need it to be based on custom hashing and equality methods.

*Request*: give `MapMaker` the ability to be configured with a pluggable hash/equality delegate, e.g.:

    public interface Hasher<T> {
        boolean equals(T t1, T t2);
        int hashCode(T t);
    }
    
    public class MapMaker {
        ...
        public void <T> hasher(Hasher<T> hasher);
    }

This would solve this problem in a nice way.

You could also provide `EqualsHasher` and `IdentityHasher` implementations of the two standard "hashers" already used by `MapMaker`, using them for normal and weak keys, respectively.

**Comment by lowasser** [comment]
It seems to me like we already have sort of what you want, in `Equivalence`.  You can't plug an `Equivalence` directly into `MapMaker` -- that was rejected in https://github.com/google/guava/issues/576, with the justification

> I know that many people want this, but we have come to the conclusion that Java's collection APIs are not cut out for this. Josh was right to leave this functionality out. We recommend you just pay the extra cost of the EquivalenceWrappers, just as we use Strings instead of char[]s. This will lead to less surprising code.

What you can do, easily enough, is use the `Equivalence.Wrapper` to wrap your byte arrays, which works just fine.  (Or you can create your own class directly wrapping the `byte[]` and implementing your `hashCode` and `equals` as desired.)

**Comment by cpovirk** [comment]
Our usual suggestion in this case is to use a class like [`ByteString`](https://github.com/google/guava/issues/1281) instead of a `byte[]`.

We expected the more general feature of a pluggable `keyEquivalence` to be useful, but we found that [it wasn't providing much value](https://github.com/google/guava/issues/940#issuecomment-61342592).

(I see that Louis has posted while I'm typing, but conveniently, there seems to be almost no overlap between our responses.)

**Comment by archiecobbs** [comment]
OK, thanks. I didn't know about `Equivalence`... should have looked there.

I strongly disagree however with not providing a public way to specify an `Equivalence` to `MapMaker`. Just seems spiteful. Oh well.
