### ISSUE TITLE
Make SettableFuture not final

### ISSUE THREAD

**Issue by archiecobbs** [google/guava#2087]
I was writing a subclass of `SettableFuture` that takes some additional action when `cancel()` is invoked, but _Oops_ the class is `final`...

Marking a class in a general purpose library `final` is a pretty drastic thing to do, so I assume there is a good reason.... ?

If there is no good reason, how 'bout let's make it extensible.

**Comment by cpovirk** [comment]
You can use `AbstractFuture`, which does everything `SettableFuture` does but is extensible.

**Comment by archiecobbs** [comment]
Thanks, didn't realize that. Sorry for the noise.
