### ISSUE TITLE
Add equivalent of Range.span() for multiple ranges

### ISSUE THREAD

**Issue by rgabbard-bbn** [google/guava#2088]
Guava provides `Range.span(Range otherRange)` for getting the minimal `Range` which encloses both `this` and `otherRange`.  A natural thing to want is to determine the minimal span enclosing a collection of `Range`s, but as far as I can tell no method is provided for this.

if you want to implement it yourself, you either have to:
* call `Range.span` repeatedly, one `Range` at a time
* write your own logic to go through the list and correctly deal with closed, open, and unbounded endpoints.  This is what we have done, but it's not particularly simple, and someone trying to implement it could easily make an error.

Within Guava, it would be trivial to implement this using the ordering on the package-private `Cut` object currently used by `Range` to implement `Range.span`.

**Comment by lowasser** [comment]
Are you looking for `RangeSet.span()`?

**Comment by rgabbard-bbn** [comment]
Yes, I'm looking for the same behavior as if you created a `RangeSet` and called `.span()` on it.  However, I'm suggesting it might be worthwhile to make it its own static method because implementing it with `RangeSet` is somewhat inelegant.

`ImmutableRangeSet.Builder` forbids adding overlapping ranges (which might be present) so we must use `TreeRangeSet` like this:

    RangeSet<T> rs = TreeRangeSet.create();
    for (final Range<T> range : ranges) {
       rs.add(range); // no addAll 
    }
    final Range<T> span = rs.span();

Code-wise, this isn't bad and could easily wrapped up in a method. But at a glance at least, it looks like under the hood this involves creating a `NavigableMap<Range>` and then applying the rather complex logic of `TreeRangeSet.add()`, which at the very least creates another `Range` object for each input range.

It seems inelegant to be sorting the ranges and creating lots of objects for something which could be done in a single linear pass through the ranges without creating any.  But perhaps the use case is too rare for Guava,

**Comment by lowasser** [comment]
It's not immediately clear to me, I confess, what your objection is to the simple for loop of repeatedly calling `Range.span`?

**Comment by rgabbard-bbn** [comment]
It was more aesthetic than practical.  Repeatedly calling `span` allocates a new `Range` on every call [1], while if you go through the list tracking end points you can avoid creating any objects at all (except the returned answer).  But perhaps the compiler can optimize away the allocation of the temporary `Ranges`, and it is unlikely to be a performance bottleneck, anyway, so I will close the ticket.  Thanks for your all's work on Guava by the way - we use it constantly.

[1] Actually, it happened on every call only in the older version of the code I was looking at. The current version is cleverer and will reuse one if the input `Ranges` if it can.  In the case of a large collection of random `Ranges` this will happen often, though not if they are somewhat sorted, which I'd imagine is a common case.
