### ISSUE TITLE
NewCollectionTypesExplained wiki page wrong href tag.

### ISSUE THREAD

**Issue by afonsolage** [google/guava#2095]
There is a error on the wiki page [NewCollectionTypesExplained - implementations](https://github.com/google/guava/wiki/NewCollectionTypesExplained#implementations-1): 

```
<A href="http://google.github.io/guava/releases/snapshot/api/docs/com/google/common/collect/LinkedListMultimap.html">

LinkedListMultimap

Unknown end tag for <\/a>
```

and also on [NewCollectionTypesExplained - BiMap](https://github.com/google/guava/wiki/NewCollectionTypesExplained#bimap):

```
<A href="http://google.github.io/guava/releases/snapshot/api/docs/com/google/common/collect/Table.html">

Table

Unknown end tag for </a>
```

**Comment by kevinb9n** [comment]
Is this still broken?
