### ISSUE TITLE
Include package-list in browsable API docs

### ISSUE THREAD

**Issue by pushbit** [google/guava#2096]
https://google.github.io/guava/releases/18.0/api/docs/package-list should be available so that we can Javadoc link to it.  I see that the file exists at `gh-pages/_releases/18.0/api/docs/package-list`, but for some reason it doesn't make it to the website.

**Comment by archiecobbs** [comment]
I think this has something to do with use of Jekyll.

In a "plain" publishing of Javadocs to `gh-pages`, the `package-list` file is obtainable.

**Comment by pushbit** [comment]
Might we be able to look forward to this in the 19.0 release?

**Comment by cgdecker** [comment]
This should be fixed now.
