### ISSUE TITLE
bloom filter use "final long[] data" memorize bit data cause OutOfMemoryError when a huge number of expected insertions

### ISSUE THREAD

**Issue by moremoretree** [google/guava#2098]
bloom filter apply to filter big data usually, maybe billions of records, when the number of expected insertions is 10 billion and the false positive probability is 0.0001, it will take about 22G RAM, it not appropriate memorize by long array, I changed the type to "HashMap&lt;Integer, Long[]&gt;", ensure long array less than 20M, does this feather useful to somebody others ?

**Comment by kevinb9n** [comment]
I'm afraid this is not a use case that Guava's BloomFilter support will be addressing. Most of our users by far have far less extreme requirements.
