### ISSUE TITLE
Wrong RemovalCause published on cache.invaldateAll()

### ISSUE THREAD

**Issue by ben-manes** [google/guava#2101]
When the cache is being cleared, either through `Cache.invalidateAll()` or `asMap().clear()`, the removal cause is always `EXPLICIT`. However the map may contain expired or GC'd entries that would be removed on the next maintenance cycle. The removal cause should indicate the actual state of the entry, not merely the action that triggered the eventual removal.

Due to weak and soft references the key or value may be null. A listener should only expect to receive a null key or value if the cause is `COLLECTED`, as indicated by `RemovalNotification`:
>The key and/or value may be null if they were already garbage collected.

Therefore a listener might decide to inspect the properties without a null guard, leading to an NPE.

```java
@Test
public void clear_expireAfterAccess() {
  FakeTicker ticker = new FakeTicker();
  RemovalListener<Integer, Integer> listener = Mockito.mock(RemovalListener.class);
  ArgumentCaptor<RemovalNotification<Integer, Integer>> captor =
      ArgumentCaptor.forClass(RemovalNotification.class);
  Cache<Integer, Integer> cache = CacheBuilder.newBuilder()
      .expireAfterAccess(1, TimeUnit.MINUTES)
      .removalListener(listener)
      .ticker(ticker)
      .build();
  cache.put(1, 1);
  ticker.advance(10, TimeUnit.MINUTES);
  cache.invalidateAll();

  verify(listener).onRemoval(captor.capture());
  assertThat(captor.getValue().getCause(), is(RemovalCause.EXPIRED));
}
```

The fix is to change `LocalCache$Segment#clear()` to inspect the key, value, and expiration status when determining the cause. 

Unfortunately this race condition is more widespread due to `enqueueNotification` not being tolerant to a garbage collection nulling out the key/value. Prior to constructing the notification, the method must take a strong reference to the key and value, check if either was collected, and if so publish a `COLLECTED` instead of the caller's cause.

**Comment by lowasser** [comment]
If you (or anyone else) has a patch for this particular issue, we would love to accept it, I think; this looks like a valid bug.

**Comment by ben-manes** [comment]
I would have the bandwidth (be incentivized) if the Guava team was able to provide obfuscated traces (#1110) for policy simulation.
