### ISSUE TITLE
BaseEncoding.encodingStream closes output stream when calling close()

### ISSUE THREAD

**Issue by sancoder** [google/guava#2102]
In my case I'm using BaseEncoding.base64() encoder to write the base64-encoded data into another stream.
It seems there is no way to write the data correctly without the target stream being closed at the end.
I'm using the following code

        String lineSeparator = System.lineSeparator();
        BaseEncoding encoder = BaseEncoding.base64().withSeparator(lineSeparator, 64);

        String data;
        data = "{\"en_US\",0,0,\"\",-1,\"\",\"\",\"\",\"\"}";
        byte[] bytes = data.getBytes();
        ByteArrayInputStream stream = new ByteArrayInputStream(bytes);

        ByteArrayOutputStream writerStream = new ByteArrayOutputStream(100);
        Writer writer = new OutputStreamWriter(writerStream);
        OutputStream target = encoder.encodingStream(writer);
        ByteStreams.copy(stream, target);
        //target.close();
        writer.write("\n}, other text to be written");
        writer.close();

When I'm running the following snippet the result is 

        eyJlbl9VUyIsMCwwLCIiLC0xLCIiLCIiLCIiLCIif
        }, other text to be written

But the correct result should be

        eyJlbl9VUyIsMCwwLCIiLC0xLCIiLCIiLCIiLCIifQ==
        }, other text to be written

If I uncomment the line with target.close call I get an exception that output stream has been closed.
If I comment the line with writer.write I get the correct result but the other text has not been written and output stream has been closed.

Maybe this is a documentation issue and subject class shouldn't be used in such a scenario. In that case this should be stated in the documentation.

**Comment by lowasser** [comment]
Looking at the [Javadoc](http://docs.guava-libraries.googlecode.com/git/javadoc/com/google/common/io/BaseEncoding.html#encodingStream(java.io.Writer)), it already says

> When the returned OutputStream is closed, so is the backing Writer.

This behavior is consistent with just about every other stream wrapper I'm aware of -- BufferedReader/Writer, InputStreamReader/OutputStreamWriter, ObjectInput/OutputStream, and so on, all close their backing streams when you close the outer stream.

I'm not sure what documentation or implementations changes you think would be reasonable here?

**Comment by ogregoire** [comment]
The problem, Louis, is that the `BaseEncoding::encodingStream::close` method still modifies the underlying stream. And that is an unexpected behavior.

For instance, I used the following code:

    String lineSeparator = System.lineSeparator();
    BaseEncoding encoder = BaseEncoding.base64().withSeparator(lineSeparator, 64);

    byte[] bytes = "{\"en_US\",0,0,\"\",-1,\"\",\"\",\"\",\"\"}".getBytes();
    
    ByteArrayOutputStream writerStream = new ByteArrayOutputStream(100);
    try (Writer writer = new OutputStreamWriter(writerStream);
        OutputStream target = encoder.encodingStream(writer)) {
      try (ByteArrayInputStream stream = new ByteArrayInputStream(bytes)) {
        ByteStreams.copy(stream, target);
      }
      writer.write("\n}, other text to be written");
    }
    System.out.println(new String(writerStream.toByteArray()));

Writes

    eyJlbl9VUyIsMCwwLCIiLC0xLCIiLCIiLCIiLCIif
    }, other text to be writtenQ==

`BaseEncoding::encodingStream` should definitely return a custom stream (`EncodingOutputStream`?) where *we* can say "it's over" and if we don't say "it's over", the current behavior applies.

**Comment by lowasser** [comment]
I was under the impression that this was still consistent with built-in JDK stream wrappers, some of which required close() to finish up the stream (and closed the underlying stream) at the same time.  I'd very much prefer to avoid creating new types if at all possible.

**Comment by sancoder** [comment]
Louis, I haven't found the close() call you're referring to in BufferedWriter.close().
It does set underlying stream reference to null though.

**Comment by lowasser** [comment]
You haven't?  http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/6-b14/java/io/BufferedWriter.java#265  Line 265 does it.

**Comment by sancoder** [comment]
I didn't look at all possible implementations. The one I have sources for contains this snippet

    @SuppressWarnings("try")
    public void close() throws IOException {
        synchronized (lock) {
            if (out == null) {
                return;
            }
            try (Writer w = out) {
                flushBuffer();
            } finally {
                out = null;
                cb = null;
            }
        }
    }

**Comment by lowasser** [comment]
That try-with-resources block `try (Writer w = out) {` will close the backing writer, too.

**Comment by sancoder** [comment]
You're right.

**Comment by ogregoire** [comment]
@lowasser The ticket is now closed but I still believe that the use case I underlined is totally appropriate, even if you're reluctant to create new types. I re-read `flush()` carefully and it actually might be appropriate to call it. Should a new ticket be opened?
