### ISSUE TITLE
InPredicate#equals broken (or test passing unintentionally)

### ISSUE THREAD

**Issue by mttkay** [google/guava#2103]
This is Guava 18.0.

I just noticed that the equality test for `Predicates.in` uses sets to test predicate equality:

```
  public void testIn_equality() {
    Collection<Integer> nums = ImmutableSet.of(1, 5);
    Collection<Integer> sameOrder = ImmutableSet.of(1, 5);
    Collection<Integer> differentOrder = ImmutableSet.of(5, 1);
    Collection<Integer> differentNums = ImmutableSet.of(1, 3, 5);

    new EqualsTester()
        .addEqualityGroup(Predicates.in(nums), Predicates.in(nums),
            Predicates.in(sameOrder), Predicates.in(differentOrder))
        .addEqualityGroup(Predicates.in(differentNums))
        .testEquals();
  }
```

This test passes, but only accidentally. What it appears to test is that two `InPredicate`s are equal, if their `target` collections contain the same elements in any order. This test will fail, however, when you replace `ImmutableSet` with an ordered type like List. It only passes because `equals` on `Set`s is true despite of element order, and `InPredicate` simply forwards `equals` to its targets. From what I understand, `InPredicate#equals` should be true even if its target collections are ordered collections.

So this is either a misleading test, or `InPredicate#equals` does not work as intended.

**Comment by lowasser** [comment]
I'm not sure why you think that InPredicate.equals is required to hold for collections that are not equal by Collection.equals.  The predicates are equivalent, sure, but I don't believe there's any requirement for the predicates to actually be equal.

**Comment by mttkay** [comment]
That's fine--but then the test is wrong, or at least misleading? It seems to test that equality on the predicate is order-insensitive, but this is only true right now because the test uses sets... it would fail for any ordered collection.

If this tests what you say it should, then why go through this whole `sameOrder` `differentOrder` business?

**Comment by mttkay** [comment]
(i.e. lack of order is a property of sets, not of the predicate)

**Comment by lowasser** [comment]
No, this is WAI; the intention is to test equality of the predicate by testing equality of the collection, and the test accomplishes that.

Look at the doc of Predicate.equals:

> Most implementations will have no reason to override the behavior of Object.equals(java.lang.Object). However, an implementation may also choose to return true whenever object is a Predicate that it considers interchangeable with this one. "Interchangeable" typically means that this.apply(t) == that.apply(t) for all t of type T). Note that a false result from this method does not imply that the predicates are known not to be interchangeable.
