### ISSUE TITLE
Documentation: Broken link

### ISSUE THREAD

**Issue by JensRantil** [google/guava#2104]
https://github.com/google/guava/wiki/ImmutableCollectionsExplained#why refers to https://code.google.com/p/memory-measurer/wiki/ElementCostInDataStructures (link text: analysis), which doen't exist anymore.

The old equivalent https://code.google.com/p/guava-libraries/wiki/ImmutableCollectionsExplained#Why? also points to that same broken link.

**Comment by ben-manes** [comment]
See the answer to #2018

**Comment by JensRantil** [comment]
Duplicate.

**Comment by JensRantil** [comment]
Actually, I'll reopen this. The documentation links need to be update.

**Comment by cgdecker** [comment]
Yeah, we do need to update our link. Also, we should perhaps consider making a copy of that page so that it can be viewed as rendered markdown rather than as text.

**Comment by lowasser** [comment]
I think this is fixed?
