### ISSUE TITLE
Feature: Be able to check if Cache#stats is enabled

### ISSUE THREAD

**Issue by JensRantil** [google/guava#2114]
**Use case:** I have a helper class that regularly polls a `Cache`'s `stats` and pushes them to metric storage. However, when the helper class is given a `Cache` I have no idea whether stats is initialized or not. If would be useful for me to be able to check whether enabled or not.

**Feature request:** To be able to check whether stats has been enabled on a cache or not.

Possibly related to #1054.

**Comment by lowasser** [comment]
The docs seem to specify t hat if a cache does not record stats, then all statistics will be zero.  Does that not suffice?

**Comment by JensRantil** [comment]
No, unfortunately not because that could be the case of the cache not having been used yet. Two options that comes to my head are:
 * Return `-1` for stats if disabled. Stated as an option in https://github.com/google/guava/issues/1054#issuecomment-61349528.
 * Add a `boolean statsEnabled()` method to `Cache`.

**Comment by kevinb9n** [comment]
I remember agonizing over whether to try to change the behavior to return -1s years ago, and unfortunately we already felt it was too late.  It's also not feasible to add new interface methods at this point.  We are sorry.

**Comment by JensRantil** [comment]
@kevinb9n Just curious, could you elaborate as to why adding a new interface method isn't feasible? Sounds very much like a backward compatible change to me (and a small one, too).

**Comment by kevinb9n** [comment]
With interfaces *no* changes are ever backward-compatible; it must always break either a consumer or an implementor. In this case every concrete class implementing Cache outside Guava would break.  After we're on Java 8, we can add interface methods by supplying a reasonable "default" implementation.  But note that in this case the best we could do is probably "throw new UnsupportedOperationException();" which isn't too exciting.
