### ISSUE TITLE
java.lang.NoSuchMethodError: com.google.common.util.concurrent.Futures.withFallback

### ISSUE THREAD

**Issue by umesh9794** [google/guava#2116]
![jar](https://cloud.githubusercontent.com/assets/7439619/8873965/a6db4cee-3229-11e5-9d75-20f2c128e269.png)
I am using Guava v 17.0 dependency in Maven and Cassandra connection is established successfully.
But when I run same JAR on Hadoop 2.0.0-CDH4.3.1, It throws me error 

java.lang.NoSuchMethodError: com.google.common.util.concurrent.Futures.withFallback(Lcom/google/common/util/concurrent/ListenableFuture;Lcom/google/common/util/concurrent/FutureFallback;Ljava/util/concurrent/Executor;)Lcom/google/common/util/concurrent/ListenableFuture;

When I look at the Guava v17.0 JAR I cant find Futures.withFallback static method. 
Is it related to Hadoop's version compatibility with Guava as Cassandra got connected when not running on Hadoop.

**Comment by kevinb9n** [comment]
This is a classic symptom of classpath conflicts.  Please ask Hadoop to follow the "important warnings" on https://github.com/google/guava.

**Comment by kabanfaly** [comment]
I'm using guava version 14.0.1.
I'm using storm with cassandra and i came accross the same issue. I discovered that my storm  was using guava-13.0 which overrided the guava version included in cassandra driver while lauching my topology. 
To fix it i removed the guava jar (version:13.0) from my storm lib directory and everything worked fine

**Comment by sankalpanand** [comment]
kabanfaly: Only your strategy worked out for me. I had to replace this library with the updated on in some 7-8 locations in Hadoop.

**Comment by mariofonseca** [comment]
If you are using Maven, you coud create a "fat jar" with the dependencies of guava14 (or higher) and override (shade) the package of the dependencies with conflicts, in this case "com.google" with for example "hidden.google". Maven has a Shade plugin to do that. Add this lines to your pom file:`
<build>
	<finalName>nameoffatjar</finalName>
	<plugins>
		
		<plugin>
			<groupId>org.apache.maven.plugins</groupId>
			<artifactId>maven-shade-plugin</artifactId>
			<version>2.3</version>
			<executions>
				
				<execution>
					<phase>package</phase>
					<goals>
						<goal>shade</goal>
					</goals>
					<configuration>
						<transformers>
							
						</transformers>
						<relocations>
							<relocation>
								<pattern>com.google</pattern>
								<shadedPattern>hidden.google</shadedPattern>
							</relocation>
						</relocations>
					</configuration>
				</execution>
			</executions>
		</plugin>
	</plugins>
</build>
`
