### ISSUE TITLE
Introduce a MinMaxPriorityQueue#builder

### ISSUE THREAD

**Issue by JensRantil** [google/guava#2119]
**Related**: This issue came out of #2118.

**Background**: Most Guava data structures has a `builder()` method to instantiate a builder and it seems that's the default way of constructing/finding a builder.

**Proposal**: Introduce `MinMaxPriorityQueue#builder` to adhere to the above principle. Currently the API is somewhat unclear how the builder works. Is there a reason why the builder method doesn't exist?

**Comment by kevinb9n** [comment]
The big problem with MMPQ is that it's very rarely used and most of the time when it is used, a careful reading of the Javadoc would have told the user something better. It's an extremely niche utility, and we're unlikely to spend time improving it futher - sorry.

**Comment by JanecekPetr** [comment]
While I understand Kevin's point, the fix to this issue would be 15 minutes of thinkng, then _one_ method, and possibly a few tests. An hour, maybe two, an ideal candidate for a lazy Friday afternoon when nothing really productive gets done?

I'm sorry if this sounds inconsiderate, I do not and can not know how much work there is to be done by your team. This shows that you might want to post a status update and an optional roadmap, somewhere public ;).

**Comment by lowasser** [comment]
To be honest, I'd guess the most likely thing we would like to do with MinMaxPriorityQueue is deprecate it and schedule it for deletion rather than expand it.  As Kevin said, most of the time when it is used, there is something better, and in the past we've tended to delete APIs that are used incorrectly more often than not.
