### ISSUE TITLE
simplifyPath for windows paths

### ISSUE THREAD

**Issue by mattnathan** [google/guava#2121]
It would be nice if there was a way to simplify a Windows path - i.e. one separated by `\` instead of `/`. Whether the existing `Files.simplifyPath` method is modified to use `File.separator{Char}` or whether a new method is required I don't know.

As a work around `Files.simplifyPath(path.replace('\\', '/')).replace('/', '\\')` would work.

**Comment by cgdecker** [comment]
If possible, I'd strongly recommend using Java 7's file API for this. If you have a `Path`, calling [`normalize()`](http://docs.oracle.com/javase/7/docs/api/java/nio/file/Path.html#normalize()) on it will simplify the path for you in a file-system dependent way. We should actually probably consider removing `Files.simplifyPath`.
