### ISSUE TITLE
New Collection type: PredicateMap

### ISSUE THREAD

**Issue by Invizible** [google/guava#2123]
I would like to have a new collection type like RangeMap, but instead of Range, I would like to retrieve values using Predicate. For instance, assume we are writing class which generates random values for given type.
If we use ordinary map we have to duplicate keys:

```java
  private final ImmutableMap<Class<?>, Randomizer> RANDOMIZERS = ImmutableMap.<Class<?>, Randomizer>builder()
          .put(byte.class, byteRandomizer)
          .put(Byte.class, byteRandomizer)
          .put(short.class, shortRandomizer)
          .put(Short.class, shortRandomizer)
          .put(Collection.class, collectionRandomizer)
          .put(List.class, collectionRandomizer)
          .put(ArrayList.class, collectionRandomizer)
          //...
          .build();

   public Object getRandomValueOf(Class<?> type) {
        Randomizer randomizer = RANDOMIZERS.get(type);

        if (randomizer == null) {
            randomizer = new DefaultRandomizer(this);
        }

        return randomizer.random(type);
    }
```

If we were able to use Predicates this code would be shorter:

```java
 private final PredicateMap<Class<?>, Randomizer> RANDOMIZERS = MutablePredicateMap.<Class<?>, Randomizer>builder()
            .put(Predicates.<Class<?>>in(Arrays.asList(byte.class, Byte.class)), byteRandomizer)
            .put(Predicates.<Class<?>>in(Arrays.asList(short.class, Short.class)), shortRandomizer)
            .put(isEnum(), enumRandomizer)
            .put(instanceOf(Collection.class), collectionRandomizer)
            .build();
```

Why did I use maps? I think it's better than long if-else operators.

**Comment by lowasser** [comment]
This seems deeply weird to me, and I really don't get why you think this is better than long if-else chains.  Maps are generally expected to have efficient get methods, which are outright impossible here.  Simple if conditions seem more readable and efficient here.

**Comment by cpovirk** [comment]
In some cases, if you're interested in constructing a `Map` more concisely, you can probably build the inverse `Multimap` and then invert it. Something like this:

    private final ImmutableSetMultimap<Class<?>, Randomizer> RANDOMIZERS = new ImmutableSetMultimap.<Class<?>, Randomizer>builder()
        .putAll(byteRandomizer, byte.class, Byte.class)
        .putAll(shortRandomizer, short.class, Short.class)
        .putAll(collectionRandomizer, Collection.class)
        .build().inverse();

But:

- This returns a `Multimap`, not a `Map`. You can call `getOnlyElement(RANDOMIZERS.get(...))`, or you could use a `Multimap`-to-`Map` converter. I don't think we have one before JDK8.

- This won't work if you need arbitrary predicates, as it sounds like you do.

So it probably doesn't work for you. But I think it will eat away at the users of a utility like this. In your case, you probably are better served with `if`-`else`. (`if`-`else` also gives you a way to break "ties" in which multiple `Predicates` would match, for better or for worse.)

**Comment by Invizible** [comment]
@lowasser  It's maybe because I saw a lot of long ugly if-else chains in current project :) Yes, you are right it's weird and well refactored if-else chain can resolve my problems and it would be better.
