### ISSUE TITLE
Reducing redundant & simple subscribers for simple reference-change events

### ISSUE THREAD

**Issue by Groostav** [google/guava#2126]
Hey guys,

Following our project's format, worded as generally as I can, a user story:

> as a developer & guava-user I would like to register my stateful services/controllers with some kind of registrar service that will update my component's 'current' models as they are changed by processes outside the scope of my object, so that I can avoid having to burden myself with listening for the appropriate changes and fetching those references myself.

We develop a desktop java app that uses guava. We have developed a custom component similar in principal to the EventBus with slightly different syntax for handling life cycle management.

I think some code might be worth a thousand words. In the case where the user closes our applications project file (similar to an excel workbook) and opens another one, we need a number of components to get a reference to the resulting deserialized model objects (from the opened project file). This could be handled by posting a plethora of events using the `EventBus` along the lines of

``` Java
public class StatefulServiceObject{
    private ModelA currentA;

    //constructor registers this component with an EventBus

    @Subscribe 
    public void acceptNewProjectOn(CurrentModelAChangedEvent event){
        this.a = event.a;
    }
}

//and then in the project file loading service
eventBus.post(new CurrentModelAChangedEvent(currentModelA));
```

But it requires that each service that keeps a reference to the `currentA` to have a subscriber. We could do something with inheritance to reduce this problem, but that opens a whole new can of worms.

To avoid this our project has created and evolved a component called the `ModelUpdaterService` that allows you to express this same concept a little more concisely.

``` Java
public class StatefulServiceObject{
    @UpdateServiced ModelA currentA;

     //constructor registers this component with a model updater service
}

//and then in the project file loading service
modelUpdaterService.push(currentModelA);
```

There are a couple benefits I've noticed to this approach:
- this separates the writing portion from the reading portion of each subscriber, which means we're more likely to be in a consistent state when any one one event is published. In the event that two stateful services that interact with each other both keep a 'current' ModelA, without this updater service, when the event is published there is a good chance that one will have a different reference from the other, possibly pushing us to an error state and ultimately, likely, causing the bug-fixer to add a second event.
- this (helps) keep events stateless, which I really think is a general good thing. For one it means that events can be serialized more easily, and for another it typically simplifies testing. I've found that when I've given a field to an event, it is only used by some minority of the subscribers, meaning that when I go to test things that use this event, the tests have to supply the context for the field on the event even though the component under test may not even use it. 
- this (helps) reduce the complexity of the number of events that need to be posted. In the case where our user loads a Project file, there is 1 top-level model that needs to be considered 'current', three second-level... well ill just pseudo code it
  
  ``` Java
  openNewProject(Path pathToFile){
     Project projectFromFile = deserialize(pathToFile);
     modelUpdaterService.push(
         projectFromFile,
         projectFromFile.configurations.get(0),
         projectFromFile.resultSheets.get(0),
         projectFromFile.visualizations.get(0),
     );
     eventBus.post(new ProjectChangedEvent());
  }
  ```
  
  The thing to note here is there is only 1 place where control is passed to other objects. Using pure events, this would require multiple events, meaning that control is passed to other objects in multiple places.

We did go through architectural discussions about what it meant to be the most 'current' of any one model, and how we could either traverse the object tree from the most current root, or use providers to do that for us, but ultimately it was decided that the least wierd/redundant strategy would be to have a field that was updated automagically by a service, akin to the event bus.

Does this sound like a problem you guys have? Would you be interested in our solution / a new one based largely off the eventBus code?

**Comment by netdpb** [comment]
We're unlikely to add features to EventBus, as there are newer frameworks such as [RxJava](https://github.com/ReactiveX/RxJava) out there.
