### ISSUE TITLE
19rc1 regression in sliced bytesource: offset + length may overflow for large length values

### ISSUE THREAD

**Issue by jbgi** [google/guava#2127]
An algorithm similar to ```java.lang.Math.addExact()``` should be used to compute ```offset + length```  and fallback to ```Integer.MAX_VALUE``` or ```Long.MAX_VALUE``` in case of overflow. 
There is 3 occurrences of this possibly overflowing addition in ```ByteSource.java```.

I found this bug because I regularly slice bytesources with a length equals to Long.MAX_VALUE.

**Comment by jbgi** [comment]
thanks!
while not a regression, I think the addition ```offset + length``` could also overflow in SlicedByteSource.sizeIfKnown()

**Comment by cgdecker** [comment]
Thanks, this should all be fixed now.
