### ISSUE TITLE
BUG: ScheduledListeningDecorator schedule(Callable<V>....) delegates to schedule(Runnable

### ISSUE THREAD

**Issue by norru** [google/guava#2133]
`MoreExecutors.java:541`

```java
    @Override
    public <V> ListenableScheduledFuture<V> schedule(
        Callable<V> callable, long delay, TimeUnit unit) {
      TrustedListenableFutureTask<V> task = TrustedListenableFutureTask.create(callable);
      ScheduledFuture<?> scheduled = delegate.schedule(task, delay, unit);
      return new ListenableScheduledTask<V>(task, scheduled);
    }
```
`delegate.schedule(Runnable...)` is invoked here instead of the (intended?) `delegate.schedule(Callable<V>...)`. As a result, the `ScheduledListeningDecorator` is unusable for `Callable<?>`.

**Comment by cpovirk** [comment]
I do feel weird that the `Callable` version calls the `Runnable` version. It's not what you'd expect of a pure "decorator." As far as I know, though, submitting a `Callable` should still work. Are there cases in which it gives undesired results?

**Comment by norru** [comment]
No, submitting a `Callable` does not work. The return value of the decorated Callable<T> always resolves to null. This behaviour was not present in guava 14.0.x. I believe it was introduced in 15.0.

**Comment by cpovirk** [comment]
Oh! I was thinking that this was one of the recurring methods, for which the return value is always `null`, anyway. Thanks. I'll see what we can do.

**Comment by norru** [comment]
Thanks :) If you need assistance on resolving this, I may have some hours to spare during the weekend.

**Comment by cpovirk** [comment]
Now I'm confused: `delegate.schedule(Callable, ...)` appears to be returning a `Future` with the correct value. It sounds like you're saying that it doesn't do so for certain delegate executors. What kind of executors do I need to reproduce this problem? I would expect any executor, upon a call to `delegate.schedule(runnable, ...)`, to call `runnable.run`, which should be enough to get the proper return value.

**Comment by norru** [comment]
Even if `delegate.schedule(Callable, ...)` returns the future correctly, the`ScheduledListeningDecorator.schedule(Callable<V> callable...)` wrapping it doesn't (and returns a null future).

I'll put together a repro test and send it to you.

**Comment by norru** [comment]
Cannot reproduce the "null" issue with 19-SNAPSHOT in a simple test. Conditions must be more subtle. I can dig in a bit but probably have to get back to the office to narrow it down.

A simpler failure can be synthesized as follows:

```java
	    ScheduledThreadPoolExecutor delegate = new ScheduledThreadPoolExecutor(1) {
	      @Override
			public <V> ScheduledFuture<V> schedule(Callable<V> callable,
					long delay, TimeUnit unit) {
				return super.schedule(callable, delay, unit);
			}

			@Override
			public ScheduledFuture<?> schedule(Runnable command, long delay,
					TimeUnit unit) {
				//behavior may be different for Runnable
				throw new IllegalArgumentException("Schedule of Runnable not supported");
			}
		};
		// this one works
		delegate.schedule(Callables.returning(42), 1, TimeUnit.MILLISECONDS);
		// this one throws!
		ListeningScheduledExecutorService service = listeningDecorator(delegate);
		service.schedule(Callables.returning(42), 1, TimeUnit.MILLISECONDS);
```

**Comment by norru** [comment]
More investigation here.

You were right about the decorator itself not returning null. The real case is a bit more convoluted. Long story short, we have "special" schedulers in which we keep track of the executed/submitted tasks. The `null` comes as a side effect of those submitted tasks records.

Here's a repro case which mimics the problem (our original code is a lot more complicated, too much perhaps).

```java
public void testListeningDecorator_customSchedulerFailure()
			throws Exception {
		// we keep track of all the tasks this executor has completed
		final List<FutureTask<?>> taskList = Collections
				.synchronizedList(new ArrayList<FutureTask<?>>());
		ScheduledThreadPoolExecutor delegate = new ScheduledThreadPoolExecutor(
				1) {
			@Override
			public <V> ScheduledFuture<V> schedule(Callable<V> callable,
					long delay, TimeUnit unit) {
				final FutureTask<V> task = new FutureTask<V>(callable);
				taskList.add(task);
				return super.schedule(new Callable<V>() {
					@Override
					public V call() throws Exception {
						task.run();
						return task.get();
					}
				}, delay, unit);
			}

			@Override
			public ScheduledFuture<?> schedule(final Runnable command,
					long delay, TimeUnit unit) {
				final FutureTask<Void> task = new FutureTask<Void>(command,
						null);
				taskList.add(task);
				return super.schedule(new Runnable() {
					@Override
					public void run() {
						task.run();
					}
				}, delay, unit);
			}
		};
		
		ListeningScheduledExecutorService service = listeningDecorator(delegate);
		
		// we do the same thing twice. 
		// This goes through the decorator	
		ListenableFuture<Integer> future = service.schedule(
				Callables.returning(42), 1, TimeUnit.MILLISECONDS);
		// This bypasses the decorator
		ScheduledFuture<Integer> bypass = delegate.schedule(Callables.returning(41), 1, TimeUnit.MILLISECONDS);

		assertThat(future.get()).isEqualTo(42);
		assertThat(bypass.get()).isEqualTo(41);

		assertTrue(future.isDone());
		assertListenerRunImmediately(future);
		assertEquals(0, delegate.getQueue().size());

		assertThat(taskList).hasSize(2);
		
		assertThat(taskList.get(1).get()).isEqualTo(41);
		assertThat(taskList.get(0).get()).isEqualTo(42); // boom!
	}
```

**Comment by cpovirk** [comment]
Thanks for the investigation.

For starters, we should document that this "decorator" doesn't always forward calls to the corresponding methods.

Going beyond that is likely to be tricky. Is there any chance that your `schedule(Runnable, ...)` method could check whether the input is already a `Future` and avoid wrapping in that case?

**Comment by norru** [comment]
You're welcome :)

That's the very inelegant workaround I've put in place - but it really
looks awful and it's not at all general.

The main problem is that the decorator is not a decorator but the
definition of the interface suggests otherwise. If it helps, it started
failing when I upgraded from Guava 14 to Guava 18. At that point it was
behaving "as expected".

To avoid bad surprises, it should follow a completely different contract
and as such implement a different interface. Anything short of that is
going to cause confusion at best.

On 18 August 2015 at 16:01, Chris Povirk <notifications@github.com> wrote:

> Thanks for the investigation.
>
> For starters, we should document that this "decorator" doesn't always
> forward calls to the corresponding methods.
>
> Going beyond that is likely to be tricky. Is there any chance that your schedule(Runnable,
> ...) method could check whether the input is already a Future and avoid
> wrapping in that case?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/guava/issues/2133#issuecomment-132240673>.
>



-- 
Cheers,
Nico

**Comment by cpovirk** [comment]
OK, it looks like we do document this:

> Creates an ExecutorService whose submit and invokeAll methods submit ListenableFutureTask instances to the given delegate executor. Those methods, as well as execute and invokeAny, are implemented in terms of calls to delegate.execute.

http://google.github.io/guava/releases/18.0/api/docs/com/google/common/util/concurrent/MoreExecutors.html#listeningDecorator(java.util.concurrent.ExecutorService)

It's possible that we could change that behavior, but I'm not sure what the implementation would look like. It seems like what you ultimately want is for the `Future` returned by the delegate to match the `Future` returned by the decorator, but keeping two `Future` instances in sync is something that's impossible to guarantee in general. We could maybe get it closer, and that might be good enough in your case, but we already have a workaround there, so I hesitate to complicate things. (I think we've already had bugs in `listeningDecorator`.)

**Comment by norru** [comment]
Probably not necessary.

In this specific case the unwanted behaviour was triggered by a Guava
upgrade.

In the light of the l, it's not worth reworking the innards of the lib just
for this one corner case, as long as there is a clear and well defined
alternative.

But now it's my turn to be confused

> This implies that the returned ListeningScheduledExecutorService __never
calls the delegate's__ submit, invokeAll, and invokeAny methods, so any
special handling of tasks must be implemented in the delegate's execute
method or by wrapping the returned ListeningScheduledExecutorService.

Is it still the case? I'm pretty sure it wasn't the case in Guava 14. It
appears that we relied on a specific implementation detail (submit<X>
delegates to submit<X>) and assumed it was part of the contract.

Adding a caveat clause to the documentation in the tune of "while in older
versions of Guava this appeared to be not the case, the behaviour of the
wrapper is no longer guaranteed to mirror the behaviour of the delegated
executor" might help, perhaps?


On 20 August 2015 at 17:19, Chris Povirk <notifications@github.com> wrote:

> OK, it looks like we do document this:
>
> Creates an ExecutorService whose submit and invokeAll methods submit
> ListenableFutureTask instances to the given delegate executor. Those
> methods, as well as execute and invokeAny, are implemented in terms of
> calls to delegate.execute.
>
>
> http://google.github.io/guava/releases/18.0/api/docs/com/google/common/util/concurrent/MoreExecutors.html#listeningDecorator(java.util.concurrent.ExecutorService)
>
> It's possible that we could change that behavior, but I'm not sure what
> the implementation would look like. It seems like what you ultimately want
> is for the Future returned by the delegate to match the Future returned
> by the decorator, but keeping two Future instances in sync is something
> that's impossible to guarantee in general. We could maybe get it closer,
> and that might be good enough in your case, but we already have a
> workaround there, so I hesitate to complicate things. (I think we've
> already had bugs in listeningDecorator.)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/guava/issues/2133#issuecomment-133064805>.
>



-- 
Cheers,
Nico

**Comment by cpovirk** [comment]
This was definitely a behavior change from 14 to 15. We should have put this in our release 15 release notes. I've gone back and done so, but of course this is of much less help to you now :( That's probably the best place to put it, at least, since anyone upgrading is more likely to read it there than the Javadoc.

> `ListeningScheduledExecutorService` now returns the new `ListenableScheduledFuture` type from its `schedule*` methods. To implement this, methods on `MoreExecutors.listeningDecorator` executors have been changed to no longer directly call the corresponding methods on the delegate. For example, the decorator's `schedule(Callable, long, TimeUnit)` now calls the delegate's `schedule(Runnable, long, TimeUnit)`.

It looks like this happened in https://github.com/google/guava/commit/fc6a72e81f6cbf81de64105105f296f0c84abdd0, the commit that made `ListeningScheduledExecutorService` actually return `ListenableFuture` from the `schedule*` methods.
