### ISSUE TITLE
Exhume the Enumerator -> Iterable idea?

### ISSUE THREAD

**Issue by lukeu** [google/guava#2135]
Hi folks, I'm hessitant to raise a suggestion already discussed and closed, but since last time Java 8 has come along, which might give the idea merit again(?)

It seems that the "impossible" `Iterables` equivalant of `Iterators.forEnumeration` could be implemented by taking a `Supplier<Enumeration<T>>`. With lambdas & method references this can yeild uses which aren't even too horrible, such as:

    for (MyTreeNode node : Iterables.forEnumerationSupplier(tree::preorderEnumeration)) {
      //...
    }

and which also save a bit of memory churn c.f. `Collections.list`. 

If you're reaching for the duplicate button already, the tickets you're looking for are: #1399 and #796 ;-)  Still I think the Supplier makes this well-defined, and hence different from the "single-use iterator as an iterable" graveyard-suggestion made within those tickets.

**Comment by lowasser** [comment]
If you're presuming Java 8, then I'm not sure why it wouldn't be easiest to do this yourself:  `(Iterable<T>) () -> Iterators.forEnumeration(tree.preorderEnumeration())` _is_ the `Iterable` you're looking for.

**Comment by lukeu** [comment]
Oh, that's nice, and I agree this isn't *too* horrible:

    Iterable<MyTreeNode> nodes = () -> Iterators.forEnumeration(tree.preorderEnumeration());
    for (MyTreeNode node : nodes) { ...

Yet since Java can't infer that the type needs to be `Iterable<T>` on the right-side of a for-each, I'd still be tempted to write my own utility to avoid either the cast or variable declaration. Simply extracting this line leads to the dangerous API:

    public final class Enumerations {
      public static <T> Iterable<T> asIterable(Enumeration<T> en) {
        return () -> Iterators.forEnumeration(en);
      }

which might encourage the accident of using an exhausted Enumeration. So I think I'll still end up with this utility when rolling my own:

    public static <T> Iterable<T> asIterable(Supplier<Enumeration<T>> factory) {
      checkNotNull(factory);
      return new Iterable<T>() {
        public UnmodifiableIterator<T> iterator() {
          return Iterators.forEnumeration(factory.get());
        }
      };
    }
 
It would also allow this:

        Iterables.forEnumerationSupplier(this::preorderEnumeration)
            .forEach(node -> node.doSomething());

which has a lot less punctuation than:

        ((Iterable<MyTreeNode>) () -> Iterators.forEnumeration(tree.preorderEnumeration()))
            .forEach(node -> node.doSomething());

**Comment by ogregoire** [comment]
If you have an `Enumeration` and want an `Iterable` (not an `Iterator`) out of it, why don't you use [Collections::list](http://docs.oracle.com/javase/8/docs/api/java/util/Collections.html#list-java.util.Enumeration-), available since JDK 1.4?

**Comment by lowasser** [comment]
Without saying yes or no yet, some thoughts:

a) It's not clear where a Supplier<Enumeration<T>> would come from that couldn't be changed to provide an Iterable in the first place.
b) 
  
    ((Iterable<MyTreeNode>) () -> Iterators.forEnumeration(tree.preorderEnumeration()))
        .forEach(node -> node.doSomething());

can also be written

    Iterators.forEnumeration(tree.preorderEnumeration()))
        .forEachRemaining(node -> node.doSomething());

...without bringing `Iterable` into it at all.

**Comment by lukeu** [comment]
(a) My motivating case was `DefaultMutableTreeNode`, which has a few different methods returning Enumerations; and in some scenarios we may not be able to use a derived class; anyway...
(b) is nice: both concise and efficient. Between that and `Collections.asList` (for traditional loops) I'm happy to drop the request. While it might add a little symmetry, it's hard to argue for much 'utility' given this good alternative in Java 8. (The requested method could probably only be used 'concisely' in Java 8.)

Thanks!
