### ISSUE TITLE
FluentIterable::toList doesn't infer return type of List<? super E> like Java 8 Stream can do

### ISSUE THREAD

**Issue by scr** [google/guava#2137]
FluentIterable::toList doesn't infer return type of List<? super E> like Java 8 Stream can do.

```
class BaseClass {
    final String name;
    
BaseClass(String name) {
        this.name = name;
    }
}
class SubClass extends BaseClass {
    SubClass(String name) {
        super(name);
    }
}
// This should compile, but can't because the LHS is BaseClass, but after transform, we have FluentIterable<SubClass> and toList() can't adapt.
List<BaseClass> ret = FluentIterable.from(Splitter.on(CharMatcher.WHITESPACE).split("Foo bar baz"))
    .transform(t -> new SubClass(t))
    .toList();

// This compiles, FWIW in Java 8
List<BaseClass> ret = Splitter.on(CharMatcher.WHITESPACE).splitToList("Foo bar baz")
    .stream()
    .map(t -> new SubClass(t))
    .collect(Collectors.toList());
```

/cc @kuangchen

**Comment by lowasser** [comment]
I'm not sure this can be compatibly fixed?  Java 8's approach with the Collector sidesteps some of these issues.

That said, it's relatively trivial to work around this by just using t -> (BaseClass) new SubClass(t)) instead.

**Comment by scr** [comment]
Darn - I tinkered with it.  I really wish there were lower bounds for type parameters, but apparently there are not - very clever how Stream did it - Collectors has a concrete unbounded type, but the collect method uses the lower bound wildcard `? super T` - which allows the higher type that is inferred from the LHS to be used to satisfy the unbound type of the collector.

Man, what hoops to jump through ugly and you're right… not a hard solution/workaround. I'll close this.

**Comment by scr** [comment]
http://www.angelikalanger.com/GenericsFAQ/FAQSections/TypeParameters.html#FAQ107
