### ISSUE TITLE
Indicate memory allocation pitfall of Preconditions methods with varargs

### ISSUE THREAD

**Issue by advayDev1** [google/guava#2138]
Recommend adding to 
https://github.com/google/guava/wiki/PreconditionsExplained
or maybe also in the Javadoc a reminder that a call to Preconditions.checkXX(condition, format, formatValues...) allocates an Object[] on every call, regardless of whether the condition is true or false.

While this is a property of Java and not specific to this API, it is easy to miss.
This can add a lot of garbage, and is especially bad in a UI loop on Android for example.

**Comment by kevinb9n** [comment]
I think this should go in the Preconditions javadoc.

**Comment by netdpb** [comment]
I think this has been addressed, both in the Javadoc and in having added non-varargs overloads.
