### ISSUE TITLE
Add transform/filters shortcuts for common data types, to FluentIterables or a new Fluent class

### ISSUE THREAD

**Issue by ignaciotcrespo** [google/guava#2140]
Hi,

FluentIterable is very useful but lacks some shortcuts for transform/filtering of primitives and common data types (String, Date, Calendar).

Suggestion for transform shortcuts:
- asInt(), asLong(), asString(), asShort(), asByte(), asChar(), asDouble(), asFloat(), asDate(TimeZone), asDate(TimeZone, Format)

Suggestion for filter shortcuts:
- All: isNotNull(), isNull(),
- String: isEmpty(), isNotEmpty()
- Numbers: isNotZero(), isZero(), isPositive(), isNegative()
- Dates: isToday(), isThisWeek(), isThisMonth(), isThisYear(), isWeekEnd(), isNotWeekEnd()

The shortcuts could be clever enough to do the conversion before filtering. E.g. If I use isEmpty() as filter then asString() is executed first

In case is too specific for FluentIterable a new Fluent class can be created.

I can contribute with this change, but I prefer to talk about it first. I have some draft implementations.

Some examples of combinations:

- given a list of dates in numeric string format, get a filtered set of dates which are today
```java
from(list).asLong().isPositive().asDate(TimeZone).isToday().toSet()
```

- given a list of text numbers, get a filtered list with the positive values as integer:
```java
from(list).isNotNull().asInt().isPositive().toList()
```

**Comment by cgdecker** [comment]
The value of adding these specializations of `FluentIterable` (particularly for JDK types like `Date` and `Calendar` which people really shouldn't be using) would be extremely minor and the added complexity would be huge. We won't be doing this.
