### ISSUE TITLE
Add License to Maven / Jar

### ISSUE THREAD

**Issue by schmitch** [google/guava#2141]
Hello is there any chance to have a license included inside the JAR/MVN?

The Guava POM includes a lot of stuff, but is missing the license:

> https://repo1.maven.org/maven2/com/google/guava/guava/19.0-rc1/guava-19.0-rc1.pom

It should look nearly like that:
`
<licenses>
<license>
<name>Apache 2</name>
<url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
<distribution>repo</distribution>
</license>
</licenses>
`

**Comment by ben-manes** [comment]
Its part of the [parent pom](https://repo1.maven.org/maven2/com/google/guava/guava-parent/19.0-rc1/guava-parent-19.0-rc1.pom). That should be an acceptable location for license validators.

**Comment by cgdecker** [comment]
Agreed, I think it should be enough that we have it in the parent pom.
