### ISSUE TITLE
GWT can't compile ImmutableMap in 19.0-rc1

### ISSUE THREAD

**Issue by ekuefler** [google/guava#2142]
My project is using GWT 2.7.0 and Guava 18.0. When switching from 18.0 to 19.0-rc1 and making no other changes, I get the following error during GWT compilation:

```
   Tracing compile failure path for type 'com.google.common.collect.ImmutableMapEntrySet'
      [ERROR] Errors in 'com/google/common/collect/super/com/google/common/collect/ImmutableMapEntrySet.java'
         [ERROR] Line 35: Weak cannot be resolved to a type
         [ERROR] Line 20: The import com.google.j2objc cannot be resolved
   [ERROR] Hint: Check that the type name 'com.google.common.collect.ImmutableMapEntrySet' is really what you meant
   [ERROR] Hint: Check that your classpath includes all required source roots
```

**Comment by cpovirk** [comment]
Are you using Maven or some other dependency-aware build system? If not, you'll need to download [J2Objc Annotations](http://mvnrepository.com/artifact/com.google.j2objc/j2objc-annotations/0.1) yourself.

**Comment by ekuefler** [comment]
Thanks, that worked. Didn't realize there was a new dependency. I'm using Bazel, which doesn't do automatic dependency management.
