### ISSUE TITLE
Add direct support for Java 8 versions of Predicate, Function, etc.

### ISSUE THREAD

**Issue by durron597** [google/guava#2145]
I'm thinking about adding support for all the Java 8 [`java.util.function`](https://docs.oracle.com/javase/8/docs/api/java/util/function/package-summary.html) classes to the methods that use similar Guava classes.

For example, there would be both (type parameters removed for brevity):

- `Multimaps.filterEntries(Multimap map, google.common.base.predicate.Predicate predicate)`
-  `Multimaps.filterEntries(Multimap map, java.util.function.Predicate predicate)`

This would allow Guava to have the more convenient syntax of Java 8 lambdas without breaking backwards compatibility.

This has the obvious drawback of Guava having Java 8 as a compile time dependency. However, now that we are past Java 7 end of life, it is time to at least consider doing that anyway.

I'm proposing that I do some/most/all the work for this, but I wanted to run it by the Guava team before I began the process.

**Comment by lowasser** [comment]
Hi,

We already have extensive plans for Java 8 support, but this feature in particular would actively hurt, not help.  Lambdas can already be used with c.g.c.base.Function, and every other single-method interface anywhere.  If we added overloads for two different interfaces -- e.g. our Predicate and j.u.f.Predicate -- that would actively break lambdas; you would have to explicitly cast the lambda to the desired type, which would make the code significantly less readable for everyone.  You would *have* to write

    Multimaps.filterEntries(multimap,
        (java.util.function.BiPredicate<K, V>) (key, value) -> test(key, value));

...which would be very bad.

Even if you do have a java.util.function.Function stored as a constant or returned from a method somewhere, and you want to pass it to a method expecting a com.google.common.base.Function, all you have to write is myFunction::apply.

**Comment by durron597** [comment]
Oh, goodness, this stemmed from me not understanding how lambdas work, specifically, that Java is smart enough to figure out whether to use `c.g.c.base.Function` vs `j.u.f.Function` based on the method parameter. I had put the lambda in a local variable in my test and it didn't work (obviously). My mistake, thanks for the clarification!
