### ISSUE TITLE
add CharSource.asByteSource

### ISSUE THREAD

**Issue by dankarp** [google/guava#2146]
`ByteSource.asCharSource` is present, and very useful. But I'm finding several cases where it'd be nice to have a `ByteSource` view of a `CharSource` without first serializing out to `String` and then calling `String.getBytes(Charset)`. Additionally, having both `ByteSource.asCharSource` and `CharSource.asByteSource` would let us chain the two to transcode from a `ByteSource` in one charset to a `ByteSource` in another.

**Comment by cgdecker** [comment]
This is actually something I'd considered and done some work on at one point. I think the main reason it hasn't been added is that there's a very limited number of situations where you'd actually want this and not something else, and having it there would probably lead to people using it when they really shouldn't. Despite that, it's probably worth considering again.

**Comment by kevinb9n** [comment]
And mostly likely if it is a CharSource backed by a byte source and you give this the same encoding it's already using, it would skip the round trip.

**Comment by cgdecker** [comment]
Oh hey, we added this in 20.0.
