### ISSUE TITLE
Where's the code that generates PublicSuffixPatterns.java

### ISSUE THREAD

**Issue by jasonculverhouse** [google/guava#2147]
I'm out of luck as this file https://raw.githubusercontent.com/publicsuffix/list/master/public_suffix_list.dat always changes at a faster rate than guava releases.

**Comment by cpovirk** [comment]
See #475.

**Comment by jasonculverhouse** [comment]
@cpovirk All links in that pull request are dead or deleted 

https://wiki.magnolia-cms.com/display/WIKI/TldPatterns+(public+suffix+list)+generator
![image](https://cloud.githubusercontent.com/assets/286258/9805541/c862fe9e-57ee-11e5-9b19-54431a3d8303.png)

magnolia-domainnameutils package does not exist

**Comment by suchasplus** [comment]
just fyi https://documentation.magnolia-cms.com/display/WIKI/Magnolia+Domain+Name+Utils
