### ISSUE TITLE
Benchmark report on memory performance of Immutable Collection is blocked from normal users.

### ISSUE THREAD

**Issue by legatoo** [google/guava#2150]
https://code.google.com/p/guava-libraries/wiki/ImmutableCollectionsExplained#Why?
There is an analysis in this section, however, this report is protected from normal users, why? Could you open this benchmark report?

**Comment by lowasser** [comment]
Fixed.  The problem is just that the project in question was migrated from Google Code to Github.

**Comment by legatoo** [comment]
https://code.google.com/p/memory-measurer/wiki/ElementCostInDataStructures
This link still can not be opened.  @lowasser

**Comment by lowasser** [comment]
That link is dead to everyone; it's on Google Code, which is getting shut
down.  (Additionally, the Guava team doesn't own the project with that
page.) The new link on the wiki page should be to the new correct
destination.
