### ISSUE TITLE
Tables.synchronizedTable

### ISSUE THREAD

**Issue by Javaru** [google/guava#2156]
We make heavy use of `Table` collections. A need to do so across threads is common for us. A Guava Thread Safe `ConcurrentTable` implementation of the `Table` interface would be very useful and appreciated.

**Comment by lowasser** [comment]
I'm not certain such a thing would be even possible while supporting both row and column concurrent access.  Do you have an implementation in mind?

**Comment by cpovirk** [comment]
Hmm, we seem to not even have a `synchronizedTable` method.

**Comment by lowasser** [comment]
That'd certainly be doable...

**Comment by kevinb9n** [comment]
Pull request welcome.

**Comment by cpovirk** [comment]
Looks like we have this filed as #1297, too.
