### ISSUE TITLE
Add SparseArray from AOSP

### ISSUE THREAD

**Issue by timroes** [google/guava#2157]
In Android a `SparseArray` implementation exists, that should be a more performant alternative to `Map<Integer, ?>` . It would be nice to have this class available in guava. Since it is already Apache licensed there shouldn't be much of a problem adding it to Guava.

**Comment by JakeWharton** [comment]
Performance is explicitly called out by SparseArray as being worse than
HashMap.

**Comment by timroes** [comment]
Sorry I meant more memory efficient, not more performant :-/

**Comment by lowasser** [comment]
It's not clear what Guava could offer here that isn't offered in more detail by libraries like fastutil.

**Comment by kevinb9n** [comment]
We explicitly decided long ago for Guava to not get into the specialized primitive collections business.
