### ISSUE TITLE
ComparisonChain should support not performing expensive transforms: provide onResultOf variants

### ISSUE THREAD

**Issue by scr** [google/guava#2160]
Consider the following snippet - even though comparison would be avoided beyond the first compare call, the parameter evaluation for the second one (`this.expensiveCalculation()`) would still be done.

```
ComparisonChain.start()
    .compare(this.lessThanThat(), that.greaterThanThis())
    .compare(this.expensiveCalculation(), that.expensiveCalculation())
    .result();
```

I propose an extension similar to `Ordering::onResultOf` that can be used to avoid operations that are not needed because the comparison chain is "inactive" (result has already been determined).

```
ComparisonChain.start()
    .compare(this.lessThanThat(), that.greaterThanThis())
    .compare(this, that, ThisClass::expensiveCalculation)
    .result();
```

**Comment by lowasser** [comment]
Your example uses Java 8 method reference syntax, but Java 8 already has a solution to this problem that makes ComparisonChain more-or-less unnecessary: you would write

    import static java.util.Comparator.*;
    
    Comparator<Foo> comparator = 
        comparing(ThisClass::cheapProperty)
            .thenComparing(ThisClass::expensiveProperty);

**Comment by lowasser** [comment]
In the absence of Java 8, an existing solution to this problem -- similar to the solution you've already proposed -- is just to write

    Ordering.natural().onResultOf(function1)
        .compound(Ordering.natural().onResultOf(function2))

**Comment by kevinb9n** [comment]
We have an internal disagreement over whether java 8's Comparator upgrades actually make ComparisonChain obsolete; Louis is clearly on that side, but it's not settled.

If we do decide ComparisonChain has lasting value then at this moment I think this seems like a pretty good feature for it.

**Comment by cpovirk** [comment]
Dump of notes from our discussion:

boilerplate:

If using ComparisonChain with Compara*tor*, need:

    new Comparator<Foo>() {
      @Override
      public int compare(Foo left, Foo right) {
        ...
      }
    };

vs.

If using Java 8 with Compara*ble*, need:

    return ....compare(this, other)


Which is the more common use case? If I'm doing my search right, ComparisonChain is used 2.5x as often with Comparator as with Comparable. Googlers can look at https://paste.googleplex.com/6704089245155328


ComparisonChain saves on allocation if implementing compareTo


do we want compare(object, object, function) or other "best of both worlds" solutions?
former requires you to repeat "left, right, " ever time
do we want ComparisonChain2.on(left, right).compare(function).compare(function2)? but this interferes with the singleton nature and uses unfamiliar tools in comparison to JDK8 methods


thenComparingInt exists (though apparently with a different method name, unlike in ComparisonChain)


lambdas don't work for fields. but how often does this come up? we disagree on this. need numbers.


ComparisonChain failure modes:

1. people write "left.foo" on both sides. We could write an Error Prone check. Internal users can see https://paste.googleplex.com/6193752238456832

2. people write "left.foo" vs. "right.bar"

3. Java 8 is lazy, whereas ComparisonChain only "sounds lazy" -- can even fail with an exception if first checking "is null" and then checking a computed property on that variable

**Comment by kevinb9n** [comment]
correction: lambdas work with fields, just not method references, but that shouldn't be a problem.

**Comment by eamonnmcmanus** [comment]
The 2015 [comment](https://github.com/google/guava/issues/2160#issuecomment-141509099) by @cpovirk showed two places where people in Google code were comparing a value with itself. When I ran the same search again (sorry it's not visible to external people) I found five places. I think that this shows that `ComparisonChain` is somewhat error-prone, and when our team discussed it recently we didn't see reasons to prefer it to the static `Comparator` methods. I think we can close this.

**Comment by kevinb9n** [comment]
Agreed.

**Comment by cpovirk** [comment]
Anyone stuck without the new `Comparator` methods might be able to write:

```java
ComparisonChain.start()
    .compare(this.foo, that.foo)
    .compare(this, that, (x, y) -> expensiveCalculation(x).compareTo(expensiveCalculation(y)))
    .result();
```

(also, cross-reference to https://github.com/google/guava/issues/3584)
