### ISSUE TITLE
Serialized instances of ArrayListMultimap under guava 18 cannot be deserialized under version 19

### ISSUE THREAD

**Issue by martinm1000** [google/guava#2168]
More information and code here:
https://github.com/martinm1000/g18vs19

**Comment by lowasser** [comment]
Guava's README on the front page specifies

> Serialized forms of ALL objects are subject to change unless noted otherwise. Do not persist these and assume they can be read by a future version of the library.

**Comment by martinm1000** [comment]
I was afraid of this... ;-(
