### ISSUE TITLE
LocalCache Segment remove() surplus newCount = this.count -1

### ISSUE THREAD

**Issue by matthewshannon** [google/guava#2169]
Hi,

This is being pedantic, but there seems to be no specific reason for the local newCount variable to be set to this.count -1 twice in the method.

Current code ...

    @Nullable
    V remove(Object key, int hash) {
      lock();
      try {
        long now = map.ticker.read();
        preWriteCleanup(now);

        int newCount = this.count - 1;
        AtomicReferenceArray<ReferenceEntry<K, V>> table = this.table;
        int index = hash & (table.length() - 1);
        ReferenceEntry<K, V> first = table.get(index);

        for (ReferenceEntry<K, V> e = first; e != null; e = e.getNext()) {
          K entryKey = e.getKey();
          if (e.getHash() == hash && entryKey != null
              && map.keyEquivalence.equivalent(key, entryKey)) {
            ValueReference<K, V> valueReference = e.getValueReference();
            V entryValue = valueReference.get();

            RemovalCause cause;
            if (entryValue != null) {
              cause = RemovalCause.EXPLICIT;
            } else if (valueReference.isActive()) {
              cause = RemovalCause.COLLECTED;
            } else {
              // currently loading
              return null;
            }

            ++modCount;
            ReferenceEntry<K, V> newFirst = removeValueFromChain(
                first, e, entryKey, hash, valueReference, cause);
            newCount = this.count - 1;
            table.set(index, newFirst);
            this.count = newCount; // write-volatile
            return entryValue;
          }
        }

        return null;
      } finally {
        unlock();
        postWriteCleanup();
      }
    }

**Comment by matthewshannon** [comment]
Replacement


@Nullable
V remove(Object key, int hash) {
  lock();
  try {
    long now = map.ticker.read();
    preWriteCleanup(now);

    AtomicReferenceArray<ReferenceEntry<K, V>> table = this.table;
    int index = hash & (table.length() - 1);
    ReferenceEntry<K, V> first = table.get(index);

    for (ReferenceEntry<K, V> e = first; e != null; e = e.getNext()) {
      K entryKey = e.getKey();
      if (e.getHash() == hash && entryKey != null
          && map.keyEquivalence.equivalent(key, entryKey)) {
        ValueReference<K, V> valueReference = e.getValueReference();
        V entryValue = valueReference.get();

        RemovalCause cause;
        if (entryValue != null) {
          cause = RemovalCause.EXPLICIT;
        } else if (valueReference.isActive()) {
          cause = RemovalCause.COLLECTED;
        } else {
          // currently loading
          return null;
        }

        ++modCount;
        ReferenceEntry<K, V> newFirst = removeValueFromChain(
            first, e, entryKey, hash, valueReference, cause);
        int newCount = this.count - 1;
        table.set(index, newFirst);
        this.count = newCount; // write-volatile
        return entryValue;
      }
    }

    return null;
  } finally {
    unlock();
    postWriteCleanup();
  }
}

**Comment by cgdecker** [comment]
I'm not positive that this can be removed, because it _might_ be being used as a volatile read for memory consistency reasons. It's not commented with `// read-volatile` like some other reads of `count` are and it's slightly weird, but it doesn't seem worth trying to change on its own.
