### ISSUE TITLE
Enum LexicographicalComparator in Booleans

### ISSUE THREAD

**Issue by jasonqiang** [google/guava#2171]
If the param left is {false} and the param right is {true}, method compare returns -1.
If the param left is  {false} and the param right is {false,true},method compare also returns -1.
How could you distinguish these two situations using the return value -1 ?

**Comment by lowasser** [comment]
I'm not sure why you expect to be able to?  Comparator specifies only that some negative number is returned to indicate the first argument is less than the second argument; it doesn't specify any greater detail.

**Comment by jasonqiang** [comment]
OK，^_^，got it
