### ISSUE TITLE
Documentation on RangesExplained "encloses" appears to be wrong

### ISSUE THREAD

**Issue by VishalRao** [google/guava#2175]
https://github.com/google/guava/wiki/RangesExplained#encloses

Following statement needs review:
"[3..6] does not enclose (1..1] even though it contains every value contained by the latter range"

since the second part of the statement is not accurate.

**Comment by kevinb9n** [comment]
This is one of those things that is technically absolutely correct, but still confusing.

**Comment by VishalRao** [comment]
Oh, I'm sorry. I think I see it now.   The second statement is a vacuous truth.
https://en.wikipedia.org/wiki/Vacuous_truth
