### ISSUE TITLE
Formatting error in PreconditionsExplained table

### ISSUE THREAD

**Issue by feedm3** [google/guava#2187]
The `IndexOutOfBoundsException` is not in its correct column (4th row, `checkElementIndex(int index, int size)`)

https://github.com/google/guava/wiki/PreconditionsExplained

The table is correctly formatted in the [old google wiki](https://code.google.com/p/guava-libraries/wiki/PreconditionsExplained).

**Comment by kluever** [comment]
@lowasser just fixed this...thanks for the report!
