### ISSUE TITLE
Consider sparse arrays?

### ISSUE THREAD

**Issue by ogregoire** [google/guava#2188]
Would it be interesting to consider having [sparse arrays](https://en.wikipedia.org/wiki/Sparse_array) in Guava?

I don't have any specific need or use case at this time, except some `Map<Integer,?>` that I'd like to change to something more efficient and where I'm forced into autoboxing.

**Comment by kluever** [comment]
Without a specific use case or need, we probably won't be adding this.  Have you looked at http://fastutil.di.unimi.it/ ?
