### ISSUE TITLE
Enums.getIfPresent's cache might as well store Optional<E> instances rather than E instances

### ISSUE THREAD

**Issue by cpovirk** [google/guava#2195]
Very, very low priority.

**Comment by tavianator** [comment]
Would this even be a win?  The advantage to code like `return Optional.of(...)` is that Java might scalarize the whole `Optional` instance.

**Comment by cpovirk** [comment]
True, we'd need to measure. My thinking had been that caching the instances might help under Android, where we don't have Hotspot, but probably Android users won't want to use this method, anyway, as it's hostile to Proguard.

It's possible that this would still be a win on the server, since from what little I understand, escape analysis is rarely good enough to perform these optimizations. But that could always change someday.

In the absence of any current motivation, I'll close this.
