### ISSUE TITLE
ContiguousSet.intersection doesn't handle singleton results.

### ISSUE THREAD

**Issue by perceptron8** [google/guava#2196]
Let a < x < b:

- [x].intersection([x]) should return [x], returns [],
- [x].intersection([a..b]) should return [x], returns [],
- [a..b].intersection([x]) should return [x], returns [],
- [a..x].intersection([x..b]) should return [x], returns [].

I'll create a PR in a minute.

**Comment by cpovirk** [comment]
Thanks. I'm sending the PR for internal review now.

Incidentally, does this mean that you use `ContiguousSet.intersection`, or did you come across the bug some other way? I ask because I see that `intersection` has found zero users in its four years of existence inside Google. Perhaps we should deprecate and eventually remove it. (We'll still take the fix in any case.)

**Comment by perceptron8** [comment]
Yes, I use `ContiguousSet.intersection`. I believe it has no users at Google - this bug would be discovered so long time ago! But... IMO it doesn't mean it should be deprecated and removed. I can be really useful as I'll try to show in a moment. Moreover, people often don't use something because they don't know it exists: `ContiguousSet` seems to be one of the less known classes.

My use case was to count the number of days common to two intervals. I could use `Range` for intersection and then `DiscreteDomain` for distance (or something more, well, domain specific, like `java.time.ChronoUnit.DAYS`), but it wouldn't be so... compact. I can't, for instance, safely intersect two ranges without ensuring that they are connected; or I can, but I must be prepared to catch an exception - so it's either if-else or try-catch.

My code would look like:
```
Range<LocalDate> range1 = Range.closed(...);
Range<LocalDate> range2 = Range.closed(...);
int count;
if (range1.isConnected(range2)) {
	Range<LocalDate> intersection = range1.intersection(range2);
	count = (int) intersection.lowerEndpoint().until(intersection.upperEndpoint(), ChronoUnit.DAYS) + 1;
} else {
	count = 0;
}
```

instead of:

```
ContiguousSet<LocalDate> interval1 = ContiguousSet.create(...);
ContiguousSet<LocalDate> interval2 = ContiguousSet.create(...);
int count = interval1.intersection(interval2).size();
```

(assuming I've created `DiscreteDomain<LocalDate>` already).

Also, I very often use `ContiguousSet` as `Iterable` - it's not just `size` that matters...

`ContiguousSet.intersection` is a tiny, simple method that shouldn't be hard to maintain. There are no alternatives (`Sets.intersection` creates view, etc.). I'd be happy if it stays with us.

**Comment by cpovirk** [comment]
Thanks. That should be enough to get `intersection` out of my eye for now :)

`ContiguousSet` probably does deserve more users than it has. It would be nice to promote it a little more somehow.

**Comment by cpovirk** [comment]
I suppose that @cgdecker could try to get this into 19.0-rc3...? But I do feel bad that we keep holding that up.
