### ISSUE TITLE
Consider making two Guava 19 releases for GWT

### ISSUE THREAD

**Issue by jnehlmeier** [google/guava#2202]
Guava 19 is currently incompatible to GWT 2.8 because commit https://github.com/google/guava/commit/9e56ef17c335319d21f1f2c454176c9d32687a59 has been reverted in Guava 19 release branch.

Given that GWT 2.8 is around the corner (within a month or so, see https://groups.google.com/forum/#!topic/google-web-toolkit-contributors/lq82Uc7JMIQ) its probably a good idea to create two Guava 19 releases: One that is compatible with 2.6.1/2.7 and one that is compatible with 2.8.

Otherwise GWT people have to wait for Guava 20+ or use SNAPSHOT builds before they can switch to GWT 2.8.

**Comment by cpovirk** [comment]
The plan is to release Guava 19 with support for GWT <2.8 and then quickly Guava 20 with support for GWT >=2.8: https://github.com/google/guava/wiki/Release19#gwt-notes

Does that sound OK

**Comment by jnehlmeier** [comment]
Oh ok, didn't read that in the notes. Sounds fine to me as long as emphasis is put on "quickly" ;-) People are eagerly awaiting Java8 syntax and I just wanted to avoid that they can not upgrade GWT because of Guava.

Feel free to close this issue. Alternatively I would rewrite the title accordingly for tracking purpose.

**Comment by cpovirk** [comment]
The easiest thing is probably for you to follow https://github.com/google/guava/issues/1999. I've retitled it to better emphasize what it's about now.
