### ISSUE TITLE
Maps.transformValues()

### ISSUE THREAD

**Issue by tonycody** [google/guava#2203]
``` java
support：
Map<K1,V1> ——>Map<K1,V2>

not support：Convert Map Type ???
Map<K1,V1> ——>Map<K2,V2>

You can support in the future？？？

```

**Comment by cpovirk** [comment]
Our `transform*` methods return views, not copies. As a result, when the user calls `get(k2)`, we would need a way to compute the corresponding `k1` value to find it in the original map.

We could support this if we required a two-way function, but this has its own dangers. See the similar case of `Sets.transform`: https://code.google.com/p/guava-libraries/wiki/IdeaGraveyard#Sets.transform()

Someone can probably suggest a way to do this with streams if you [ask on StackOverflow](https://stackoverflow.com/questions/ask?tags=guava+java).

**Comment by kevinb9n** [comment]
Dup of issue 2115.

**Comment by cgdecker** [comment]
#2115

**Comment by tonycody** [comment]
http://commons.apache.org/proper/commons-collections/javadocs/api-3.2.1/org/apache/commons/collections/MapUtils.html#transformedMap(java.util.Map, org.apache.commons.collections.Transformer, org.apache.commons.collections.Transformer)

Sometimes such demand
Such as redis return Map < byte [], byte [] > To Map < String, the String > OR Map < String, Object >...

希望可以支持 key 类型转换
