### ISSUE TITLE
Request: Add X-Forwarded-Port to HttpHeaders

### ISSUE THREAD

**Issue by skylarsutton** [google/guava#2206]
The HttpHeaders class contains a listing of known HTTP Header keys. It already contains "X-Forwarded-Proto" (X_FORWARDED_PROTO)... but is missing "X-Forwarded-Port" (suggestion: X_FORWARDED_PORT). 

These values are commonly sent as a pair when using an SSL load ballencer in front of a cluster.

**Comment by kluever** [comment]
I only see about 3200 hits on a popular search engine for `X_FORWARDED_PORT`.

If you can dig up an RFC, or some official-looking source, that would help justify it's addition.

**Comment by Quurks** [comment]
X_FORWARDED_PORT is the suggested java name, X-Forwarded-Port has 1.8 million results, [Amazon Elastic Load Balancing](http://docs.aws.amazon.com/ElasticLoadBalancing/latest/DeveloperGuide/x-forwarded-headers.html#x-forwarded-port) seems to use it.

**Comment by kluever** [comment]
https://www.google.com/search?q="X-Forwarded-Port"
"About 7,450 results (0.26 seconds) "

Thanks for the Amazon link. However, since it's not an official standard, I don't think we should add it.
