### ISSUE TITLE
It should be possible to provide a custom StatsCounter Supplier in CacheBuilder

### ISSUE THREAD

**Issue by jebl01** [google/guava#2209]
To simplify the process of collecting cache stats using e.g. *io.dropwizard.metrics*, ```CacheBuilder.recordStats()``` should have an overloaded version that accepts a StatsCounter Supplier.

See PR: https://github.com/google/guava/pull/2208

**Comment by ben-manes** [comment]
The concern with this is that it allows making foreign calls in critical sections. The code would need to be audited to ensure that an exception thrown by a custom implementation does not leave the cache in an invalid state. A fast but ugly solution would be to wrap a custom `StatsCounter` to consume and log any throwables. There's also the problem of slow foreign calls in critical sections, e.g. network calls, which can't be worked around. So the main task involved is ensuring that the cache is tolerant to custom implementations behaving poorly.

**Comment by jebl01** [comment]
I agree to some point. Since it's an easy task to wrap a custom ```StatsCounter``` in a *guarded StatsCounter* it's arguable something that should be done. **The PR is now updated with a quick take on this**.

The issue with slow foreign calls could be adressed by being crystal clear about this in the doc. I believe it's a bit diminishing to think that that shouldn't be enough ;-)

> No heavy work should be done in your custom ```StatsCounter``` this might affect the performance of the cache in a negative and unpredictable way!

**Comment by ben-manes** [comment]
Yep, this is now pretty much what I had in mind and considered doing in my [rewrite](https://github.com/ben-manes/caffeine). However I'd still like to hear feedback from @kevinb9n and friends, because I have a hard time justifying that this customization is useful in practice. I think that's why its been left in a state where it seems intended (by public interface), but not currently provided.

The main reason is to integrate with a framework like JMX, [Dropwizard Metrics](http://metrics.dropwizard.io/), or similar. Most of those approaches support both push and pull based accumulation, so integration is only slightly more painful by pulling the `CacheStats` and diffing if necessary. The other argument I've seen has been to clear the stats by resetting the values to zero. However that is a broken approach for many reasons, and is best done using a snapshot as a baseline to diff from. That leaves the only remaining justification being lighter weight recording, e.g. thread local or non-atomic counters. That's never brought up and, while ugly, can be worked around via decorators.

So I'm neutral and would like to hear what the Guava team thinks.

**Comment by kevinb9n** [comment]
I am similarly unconvinced.

**Comment by jebl01** [comment]
AFAIK, having this is the only way to collect e.g. success and fail load times (total load time is supported in CacheStats though). Getting rates/histograms directly without the need of a "cache stats collecting worker" is also compelling.

Without having a more complex *"cache stats worker"* this is what I can come up with using `Cache.stats()`:
```java
//registering gauges...
Gauge<Long> hitCountGauge = () -> loadingCache.stats().hitCount();
Gauge<Long> missCountGauge = () -> loadingCache.stats().missCount();
Gauge<Long> loadCountGauge = () -> loadingCache.stats().loadCount();
Gauge<Long> evictCountGauge = () -> loadingCache.stats().evictionCount();
Gauge<Long> requestCountGauge = () -> loadingCache.stats().requestCount();

metricRegistry.register(cacheName + ".hit_count", hitCountGauge);
metricRegistry.register(cacheName + ".miss_count", missCountGauge);
metricRegistry.register(cacheName + ".load_count", loadCountGauge);
metricRegistry.register(cacheName + ".evict_count", evictCountGauge);
metricRegistry.register(cacheName + ".request_count", requestCountGauge);
```
I even end up with a situation where `Cache.stats()` (with all its stats aggregation etc) needs to be called for every gauge.

By having a *custom StatsCounter*, more data can be harvested, and it will be more effective. Using e.g. *Dropwizard Metrics*, you will get things like load time histograms etc right "out of the box":

```java
public static class MetricsStatsCounter implements StatsCounter {
    private final Meter hitsMeter;
    private final Meter missesMeter;
    private final Timer loadSuccessTimer;
    private final Timer loadErrorTimer;
    private final Meter evictionMeter;

    public MetricsStatsCounter(String metricsPrefix, MetricRegistry registry) {
        this.hitsMeter = registry.meter(metricsPrefix + "." + "hits");
        this.missesMeter = registry.meter(metricsPrefix + "." + "misses");
        this.loadSuccessTimer = registry.timer(metricsPrefix + "." + "load.success");
        this.loadErrorTimer = registry.timer(metricsPrefix + "." + "load.error");
        this.evictionMeter = registry.meter(metricsPrefix + "." + "eviction");
    }

    @Override
    public void recordHits(final int count) {
        hitsMeter.mark(count);
    }

    @Override
    public void recordMisses(final int count) {
        missesMeter.mark(count);
    }

    @Override
    public void recordLoadSuccess(final long loadTime) {
        loadSuccessTimer.update(loadTime, TimeUnit.MILLISECONDS);
    }

    @Override
    public void recordLoadException(final long loadTime) {
        loadErrorTimer.update(loadTime, TimeUnit.MILLISECONDS);
    }

    @Override
    public void recordEviction() {
        evictionMeter.mark();
    }

    @Override
    public CacheStats snapshot() {
        //since we push stats to a MetricRegistry, we will never pull stats using Cache.stats()...
        throw new UnsupportedOperationException();
    }
}
```

@kevinb9n convinced now? ;-)

**Comment by kevinb9n** [comment]
The bar is very high for adding new configuration methods to CacheBuilder; to me, I don't think this clears it.  If even stronger arguments (like hard performance data) emerge, please reopen.
