### ISSUE TITLE
Use Truth exhaustively... if that's OK for Android

### ISSUE THREAD

**Issue by cpovirk** [google/guava#2218]
I did a bunch of automatic migrations to Truth a while back. I'm wondering if we should just convert all the ones that are "OK" as JUnit tests -- like `assertThat(foo).isEqualTo(bar)` -- too.

My main concerns are:
- small payoff (slightly nicer source code)
- code of allocations on Android+GWT

If we go to the trouble, we should measure the impact on these allocation-sensitive platforms.

**Comment by netdpb** [comment]
I don't think we should care about allocations/speed in unit tests.

**Comment by kevinb9n** [comment]
For what it's worth this seems like a very barely useful thing to do.....

**Comment by swankjesse** [comment]
Seems like it would be prudent to cut Truth 1.0 first?
Is there a refaster plugin to migrate?

**Comment by cpovirk** [comment]
- It would be nice if we didn't have to worry about speed in unit tests, but our Android tests already time out too often, so we'll want to make sure that we aren't making them worse.
- I agree that this is barely useful. I filed the bug mostly so that I had a place to put the warning about Android. I'll close it, and we can reopen if we are motivated.
- We could wait for Truth 1.0, but we already use Truth heavily, so the timing probably doesn't make a difference.
- We do have a Refaster plugin to migrate to Truth. I assume that one day we will release it.
