### ISSUE TITLE
Preconditions links is dead

### ISSUE THREAD

**Issue by KiGniark** [google/guava#2219]
https://github.com/google/guava/wiki/PreconditionsExplained

The first link seems broken:
([How to do this easily in Eclipse.](http://piotrjagielski.com/blog/working-with-static-imports-in-eclipse/))

**Comment by cgdecker** [comment]
I've removed the broken links from this page... not sure they were adding much value anyway.

**Comment by KiGniark** [comment]
I agree, it doesn't really have any added value.
Thanks! :-)
