### ISSUE TITLE
Consider releasing SameThreadScheduledExecutorService

### ISSUE THREAD

**Issue by zhaoyan1117** [google/guava#2221]
Guava test lib has a well implemented same thread scheduled executor service at `com.google.common.util.concurrent.testing. SameThreadScheduledExecutorService`. 

However, this class only has package level accessibility.

Is there any plan considering release this class as a public API? 

Thanks,
Yan

**Comment by tavianator** [comment]
It seems publically accessible as [`TestingExecutors.sameThreadScheduledExecutor()`](https://github.com/google/guava/blob/master/guava-testlib/src/com/google/common/util/concurrent/testing/TestingExecutors.java#L98)
