### ISSUE TITLE
Add a context to {Byte,Char}{Source,Sink}

### ISSUE THREAD

**Issue by ogregoire** [google/guava#2222]
For transformative sources and sink, it's useful to keep track of the context the stream.

Consider the use case: I want to read a ciphered, gzipped text file. This is done using the following code:

    File file = ... ;
    String text = Gzip.unzip(Cipher.uncipher(Files.asByteSource(file), cipher)).asCharSource(UTF_8);

It's rather straightforward. If I want to rewrite the file, it's easy, I just do the opposite :

    Gzip.zip(Cipher.cipher(Files.asByteSource(file), cipher)).asCharSource(UTF_8).write(modifiedText);

First, I have to keep the information about the file, the cipher and the encoding myself. It's not really good.

Second, not everything is that straightforward. Sometimes, decisions at runtime, based on the content itself (various formats, encoding). This happens directly in the `{Byte,Char}Source` and has to be preserved when writing into the `{Byte,Char}Sink`. Here comes the context.

Each level of writing should have its own context, but that context should also be publicly accessible so that the information can be retrieved by the user when actually using the streams.

A way I thought about implementing this is maybe to have chained streams containing their own context and which can return the final `{Byte,Char}Source` and its corresponding `{Byte,Char}Sink`.

For instance:

| Level | ByteSource | Stream | ByteSink |
| ---- | ---- | ---- | ---- |
| File | FileByteSource | FileStream (holds path) | FileByteSink |
| byte <-> char | ByteToCharSource | ToCharStream (holds charset) | ByteToCharSink |
| gzip | GzipSource | GzipStream (holds zip level) | GzipSink |

Example of usage:

    CharStream stream = Gzip.wrap(Cipher.wrap(Files.asByteStream(file), cipher)).asCharStream(UTF_8);
    CharSource usableSource = stream.asSource();
    CharSink usableSink = stream.asSink();

    Charset charset = usableSource.getContext(ByteToCharContext.class).getCharset();
    File file = usableSink.getContext(FileContext.class).getFile();

**Comment by kevinb9n** [comment]
It seems to us that your methods should just return your own subtypes of CharSink/Source and those can have whatever useful contextual methods on them that you want.

**Comment by ogregoire** [comment]
The main disadvantage if I write a single wrapper is that I have to write all the wrappers. Let's imagine I have the following:

    File file = ... ;
    ContextualByteSource byteSource = ContextualFiles.asByteSource(file);
    ContextualCharSource charSource = byteSource.asCharSource(UTF_8);

What you're saying is that I'd have to totally rewrite the API to support this.

This is why I requested it in the first place. Because I think it's a win for the API (keeping the context is not so rare) and because implementing it myself, while entirely possible, is basically writing the whole Byte/CharSource/Sink (including relevant factory methods) api but with an extra method.
