### ISSUE TITLE
c.g.c.c.ImmutableMap.of(k,v) etc doesn’t read well when imported statically

### ISSUE THREAD

**Issue by mrmanc** [google/guava#2224]
I regularly use `ImmutableMap.of(k,v)` to make up for the lack of a Map literal in Java as I find the syntax to be cleaner than initialising a map and putting stuff into it (and immutability is an added bonus). Since my use of this class is for brevity, I like to statically import the method as the immutability is not part of my intent. However the method name `of` does not read well as it does not indicate that I’m building a map. As a result I have been using a [wrapper class](https://gist.github.com/mrmanc/8a290b9cf4d59964e8e0) to achieve the same result:

`assertThat(result).isEqualTo(mapOf("version","61d85376"));`

Each time I can’t help wondering whether the community would embrace something like this in the original code, so I thought I’d raise an issue to discuss this :smile:

An alternative would be to use `ImmutableMap.builder().put(key, value).build()`, and that would be nice if `ImmutableMap.builder()` was `ImmutableMap.map()` but I prefer the one-less-hop method I’m using.

Of course there might be a much nicer option that I’ve completely missed, and if that is the case I look forward to finding out!

**Comment by lowasser** [comment]
For what it's worth, the JDK upstream appears to be doing something along these lines.

That said, off the cuff: I suspect we'd prefer that you just not static import this, rather than having us provide multiple methods that do the same thing?

**Comment by ogregoire** [comment]
I believe this is a duplicate of #1062.

**Comment by mrmanc** [comment]
@lowasser That's great to hear! I thought the dropping of literals in Java 8 was the end of it.

@ogregoire Thanks, you're absolutely right; this is a duplicate of #1062, which didn't come up in my searches. Closing this issue.
