### ISSUE TITLE
Cache should respect expireAfterWrite

### ISSUE THREAD

**Issue by doit-ceo** [google/guava#2225]
We are using the cache to cache some textures in our game, lets say you have a cache with a max size of 10 textures, if you tried to you use the cache to cache 11 textures, the cache becomes useless because it will keep evicting randomly old textures, which cost us rebuilding the texture, if the cache respect the size, then it will just keep the 10 textures in cache and we only need to reload/rebuild texture-11.   This way the cache will save us 95% of the cost of build textures1-10, now it simply like you don't have a cache !

Am I missing something ?

if (cache.isFull()){
cacheloader.load
//don't add it to the cache
}else{
cacheloader.load
//add to the cache
}

**Comment by ben-manes** [comment]
Guava uses the least-recently-used (LRU) policy, which evicts from the cache the entry that was last accessed the furthest in the past. This means that new entries are given priority over older ones by predicting that there will be a burst of new activity. In a game when a player enters inside a building, this prediction guesses that the player will stay in doors for a while, so keeping recently viewed content in the cache makes sense. Of course, that prediction may be wrong as the player may more frequently stay outside (least-frequently-used - LFU), so other policies try to find an [optimal balance](https://github.com/ben-manes/caffeine/wiki/Efficiency).

A caveat that may also be causing confusion is that Guava's Caches evict prior to reaching the maximum size threshold. This is a documented implementation quirk, with good arguments on both sides of whether this is preferable. Regardless, the cache will likely stay slightly below the maximum so a small cache (10) will be more affected by this detail.

**Comment by doit-ceo** [comment]
Using LRU or LFU are fine as long as you're respecting expireAfterWrite or expireAfterAccess. This is not about a game, it's about showing that if you overshot the size of the cache even by one item then the whole cache will become useless. I wrote some code and I'll share code, but first I'll share the results.
==========================================================
[Cache max size (9) and trying to load (10) items]
[Default Guava][Total Time:10082][Loading Count:100][Removal Count:91]
[Respect Max Size][Total Time:1907][Loading Count:19][Removal Count:0]
==========================================================
This code will simply load 10 items , 10 times, I added some delay (Thread.sleep(100)) to make loading expensive. The code does this through 2 methods and compare the benefits of the cache, the first is the default method (i.e. get(key)), the second method I will check  if the cache is full and simply skip loading the item from the cache (or adding it to cache) and as you see the default method made the cache useless (100% loading) also notice the total time in the second method (20%).

====================================
Example Code
====================================
import java.util.concurrent.TimeUnit;
import com.google.common.cache.CacheBuilder;
import com.google.common.cache.CacheLoader;
import com.google.common.cache.LoadingCache;
import com.google.common.cache.RemovalListener;
import com.google.common.cache.RemovalNotification;

public class GuavaTest {
	public final int MAX_CACHE_SIZE = 9;
	public int removalCount = 0;
	public int loadingCount = 0;
	private RemovalListener<String, String> removalListener = new RemovalListener<String, String>() {

		@Override
		public void onRemoval(RemovalNotification<String, String> notification) {
			// System.out.println("Removal [Count:" + removalCount + "][" +
			// notification.getKey() + ":" + notification.getValue() + "] ");
			removalCount++;
		}
	};

	LoadingCache<String, String> uselessCache = null;

	public void newCache() {
		uselessCache = CacheBuilder.newBuilder().maximumSize(MAX_CACHE_SIZE).expireAfterWrite(10, TimeUnit.SECONDS).removalListener(removalListener).build(new CacheLoader<String, String>() {
			public String load(String key) {
				return doLoad(key);
			}
		});
	}

	public String doLoad(String key) {
		// loading expensive item
		String value = key + "-LOADED";
		try {
			Thread.sleep(100);
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
		//System.out.println("Loading [Count:" + loadingCount + "][" + key + ":" + value + "] ");
		loadingCount++;
		return value;
	}

	public String get(String key, boolean defaultGuava) {
		String value = null;
		if (defaultGuava) {
			value = uselessCache.getUnchecked(key);
		} else {
			value = uselessCache.getIfPresent(key);
			if (value == null) {
				if (uselessCache.size() >= MAX_CACHE_SIZE) {
					value = doLoad(key);
				} else {
					value = uselessCache.getUnchecked(key);
				}
			}
		}

		return value;
	}

	public static void main(String[] args) {
		GuavaTest gt = new GuavaTest();
		gt.newCache();
		System.out.println("[Cache max size (9) and trying to load (10) items]");
		long lastTime = System.currentTimeMillis();
		for (int l = 0; l < 10; l++) {
			for (int i = 0; i < 10; i++) {
				String item = gt.get("" + i, true);
				// System.out.println("Got item:" + item);
			}
		}
		long totalTime = System.currentTimeMillis() - lastTime;
		System.out.println("[Default Guava][Total Time:" + totalTime + "][Loading Count:" + gt.loadingCount + "][Removal Count:" + gt.removalCount + "]");
		gt.loadingCount = 0;
		gt.removalCount = 0;
		gt.newCache();
		lastTime = System.currentTimeMillis();
		for (int l = 0; l < 10; l++) {
			for (int i = 0; i < 10; i++) {
				String item = gt.get("" + i, false);
				// System.out.println("Got item:" + item);
			}
		}
		totalTime = System.currentTimeMillis() - lastTime;
		System.out.println("[Respect Max Size][Total Time:" + totalTime + "][Loading Count:" + gt.loadingCount + "][Removal Count:" + gt.removalCount + "]");
	}
}

**Comment by lowasser** [comment]
I'm not sure what behavior you're expecting.  If you cap _any_ LRU cache at 9 items, and then rotate through fetching 10 items in order, yes, you won't get any cache hits.  Configuring a Guava cache with maximumSize and with expireAfterWrite means that entries will be expired whenever the cache exceeds maximumSize _or_ an entry is old enough.

More or less, that means that this particular access pattern is the worst case for LRU.  If cache entries aren't accessed cyclically, but, say, in random order, then the cache will work relatively well.  Off the top of my head, an example:

    Cache<Integer, Integer> cache = CacheBuilder.newBuilder().maximumSize(9).build(CacheLoader.from(Functions.identity()));
    Random rng = new Random();
    for (int i = 0; i < 100000; i++) {
      cache.getUnchecked(rng.nextInt(10));
    } 

...then I'd expect a ~90% hit rate.  I don't think this has anything to do with expireAfterAccess, it's just that your access pattern happens to be the worst case for LRU.

**Comment by doit-ceo** [comment]
@ben-manes thanks for the educated link (I liked Window TinyLfu)
@lowasser 
I did the your modification (Random access) and you're right about the 0.9 hit rate, but my method also provides the same results in both cases. There are many use cases where you would need to cycle through items, for examples; files in a directory or GUI children, etc.

**Comment by ben-manes** [comment]
If you compare your example to a different policy, like W-TinyLFU, then the hit rates are much better. As @lowasser said, this is because you're access patterns are very unfriendly for LRU so it makes the wrong predictions. Your `Respect Max Size` is the optimal hit rate since you know the access pattern is uniformly a full loop so the manual load will be best to evict / not admit. Adding Caffeine I get,

```
[Cache max size (9) and trying to load (10) items]
[Default Caffeine][Total Time:3109][Loading Count:30][Removal Count:21]
[Default Guava][Total Time:10082][Loading Count:100][Removal Count:91]
[Respect Max Size][Total Time:1967][Loading Count:19][Removal Count:0]
```

**Comment by ben-manes** [comment]
Also, your case of not admitting a new entry is better matched by `TinyLFU` (which doesn't have an admission window). Then the results are,

```
[TinyLfu][Total Time:2278][Loading Count:22][Removal Count:13]
```

**Comment by lowasser** [comment]
@doit-ceo, part of the issue is that "your method" also has worst cases that can come up in practice.  For example, imagine that your cache is YouTube, and you (naturally) fill your cache as big as it can get, and suddenly someone posts Gangnam Style and now everybody is searching for that.  But now that new thing will never get into the cache, because the cache is full already, and you'll never put that new hot element into the cache.  Once the cache gets filled up once, new entries will never enter the cache.

That may be different if you also use expireAfterWrite and the like, but CacheBuilder *should* work effectively even if you just specify maximumSize, and your caching algorithm would accept maximumSize elements and then the cache would never change again, even if 90% of users start looking up an entry that was added after the cache got filled.

Guava's Cache implementation uses LRU because it is simple to implement, has low overhead, and reasonably effective in many realistic test cases.  The CacheBuilder spec does not tie Guava to LRU, but changing that implementation would be a massive undertaking for us.  Caffeine's use of TinyLFU represents one direction -- a very impressive, highly promising direction -- this might go in the future.

**Comment by kevinb9n** [comment]
It's not clear that there is a specific, actionable feature request or bug report here. If so please reopen and make that request very clear.
