### ISSUE TITLE
why Cache.getIfPresent(Object key) is not Java Generic?

### ISSUE THREAD

**Issue by missedone** [google/guava#2227]
Hi folks

as we can see the methods of Cache interface, most of them are generic except `getIfPresent(Object key)`:
```java
public interface Cache<K, V> {
...
  @Nullable
  V getIfPresent(Object key);

  V get(K key, Callable<? extends V> valueLoader) throws ExecutionException;
...
  void put(K key, V value);
...
```

is it intended? why not `V getIfPresent(K key)` to be consistent?

thanks

**Comment by kevinb9n** [comment]
It's consistent with the rest of Guava and all of the JDK Collections: an
object that might be *stored* is of type K; otherwise it's Object.


On Sun, Nov 15, 2015 at 10:11 PM, Nick Tan <notifications@github.com> wrote:

> Hi folks
>
> as we can see the methods of Cache interface, most of them are generic
> except getIfPresent(Object key):
>
> public interface Cache<K, V> {...
>   @Nullable
>   V getIfPresent(Object key);
>
>   V get(K key, Callable<? extends V> valueLoader) throws ExecutionException;...
>   void put(K key, V value);...
>
> is it intended? why not V getIfPresent(K key) to be consistent?
>
> thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/guava/issues/2227>.
>



-- 
Kevin Bourrillion | Java Librarian | Google, Inc. | kevinb@google.com

**Comment by SimonWang1996** [comment]
你在说什么 XD

2015-11-16 14:12 GMT+08:00 Nick Tan <notifications@github.com>:

> Hi folks
>
> as we can see the methods of Cache interface, most of them are generic
> except getIfPresent(Object key):
>
> public interface Cache<K, V> {...
>   @Nullable
>   V getIfPresent(Object key);
>
>   V get(K key, Callable<? extends V> valueLoader) throws ExecutionException;...
>   void put(K key, V value);...
>
> is it intended? why not V getIfPresent(K key) to be consistent?
>
> thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/guava/issues/2227>.
>



-- 
*达则兼济天下 穷则独善其身*

**Comment by ogregoire** [comment]
It's the [robustness principle](https://en.wikipedia.org/wiki/Robustness_principle). Consider the following case:

    interface Foo { }
    interface Bar { }
    class Key implements Foo, Bar { }

    Key key = new Key();
    Foo foo = key;
    Bar bar = key;

    Cache<Foo,String> cache = ...
    cache.put(foo, "key");
    String str = cache.getIfPresent(bar);
    assertNotNull(str);

It's certain that I can retrieve `"key"` using `foo` as key. But since `foo == bar`, why shouldn't I be able to retrieve `"key"` using `bar` as key?

**Comment by lowasser** [comment]
This is deliberately consistent with the rest of Java, which made this design decision deliberately.  There have been some explanations above; http://stackoverflow.com/questions/857420/what-are-the-reasons-why-map-getobject-key-is-not-fully-generic has some more.

Marking WAI.
