### ISSUE TITLE
Add ClassPath.ResourceInfo.asByteSource()

### ISSUE THREAD

**Issue by PhilippWendler** [google/guava#2228]
If I want to load a resource I have found by classpath scanning with `ClassPath`, I need to use `Resources.asByteSource(resourceInfo.url())`. This is only little code, but hard to discover because it uses a third class `Resources` which is neither related to what I have (`ResourceInfo`) nor what I want (`ByteSource`). I also need to remember that I should go via the URL and that I cannot use `ResourceInfo.getResourceName()`.

A direct method to get a `ByteSource` from a `ResourceInfo` would make this easier. Alternatively, this should be documented at least.

**Comment by kluever** [comment]
This sounds reasonable, but adding this API would require a new dependency from reflect -> io, which doesn't currently exist (...but it's probably OK, since we'd never want an io -> reflect dependency).

**Comment by kluever** [comment]
Colin is going to see if this is a common pattern inside google code.

**Comment by cgdecker** [comment]
So, the number of callers of `ResourceInfo.url()` is quite low, but 100% of them want to read the bytes from that URL either as bytes or a string.

Given that, I'm in favor of adding this (and `asCharSource(Charset)`).

**Comment by cgdecker** [comment]
`ResourceInfo.asByteSource()` and `asCharSource(Charset)` have been added and should be mirrored out soon.
