### ISSUE TITLE
Very small values breaks com.google.common.util.concurrent.RateLimiter

### ISSUE THREAD

**Issue by dominicbertolino** [google/guava#2231]
### Problem:

Very small double values break the RateLimiter resulting in it allowing many more permits than it should. The tests below are similar to the ones in com.google.common.util.concurrent.RateLimiterTest but do not use a stopwatch. 
### Test Case 1: Create with limit of Double.MIN_VALUE

```
    RateLimiter r = RateLimiter.create(Double.MIN_VALUE);
    assertTrue("Unable to acquire initial permit", r.tryAcquire());
    assertFalse("Capable of acquiring an additional permit", r.tryAcquire());
    Thread.sleep(5000);
    assertFalse("Capable of acquiring an additional permit after sleeping", r.tryAcquire());
```

> Fails the second assertion ("Capable of acquiring an additional permit")
### Test Case 2: Create with limit of .0001

```
    RateLimiter r = RateLimiter.create(.0001);
    assertTrue("Unable to acquire initial permit", r.tryAcquire());
    assertFalse("Capable of acquiring an additional permit", r.tryAcquire());
    Thread.sleep(5000);
    assertFalse("Capable of acquiring an additional permit after sleeping", r.tryAcquire());
```

> Succeeds
### Test Case 3: Create with limit of 1E-13

```
    RateLimiter r = RateLimiter.create(0.0000000000001);
    assertTrue("Unable to acquire initial permit", r.tryAcquire());
    assertFalse("Capable of acquiring an additional permit", r.tryAcquire());
    Thread.sleep(5000);
    assertFalse("Capable of acquiring an additional permit after sleeping", r.tryAcquire());
```

> Fails the second assertion ("Capable of acquiring an additional permit")

**Comment by kluever** [comment]
Thanks for the report. This sounds like a bug and something we should look into.

**Comment by bhdrkn** [comment]
Hi,

I do not know if this is correct way to contribute but I added a test case that shows RateLimiter works even for small values. I also sent a PR for that. 

Regards,
Bahadir

**Comment by cpovirk** [comment]
We've submitted #2594, which shows that the first test passes rather than fails as suggested in the original post. If you believe there's a bug here, can you clarify what it is?
