### ISSUE TITLE
FilteredCollection.contains() fails if the predicate uses a field not used in equals()

### ISSUE THREAD

**Issue by dougmill** [google/guava#2232]
Toss this code block in a test class somewhere with appropriate imports.

    static class Foo {
        int value;
        boolean fieldThatEqualsDoesNotUse;

        Foo(int i, boolean b) {
            value = i;
            fieldThatEqualsDoesNotUse = b;
        }

        public int hashCode() {
            return Objects.hashCode(value);
        }

        public boolean equals(Object o) {
            if (o instanceof Foo) {
                return value == ((Foo) o).value;
            }
            return false;
        }
    }

    @Test
    public void test() {
        Foo f1 = new Foo(1, false);
        Foo f2 = new Foo(2, true);
        Foo f3 = new Foo(1, true);

        Set<Foo> s1 = ImmutableSet.of(f1, f2);

        // filter removes f1, leaving only f2
        Set<Foo> filtered = Sets.filter(s1,
                new Predicate<Foo>() {
            public boolean apply(Foo foo) {
                return foo.fieldThatEqualsDoesNotUse;
            }
        });

        assert !filtered.contains(f3);
    }

The assert fails.

`f3.equals(f1)` is true, so a `.contains(f3)` check on the unfiltered set passes. This is correct. `f3` also passes the filter's predicate. These two facts combine in the current implementation of `FilteredCollection.contains()` to say that the filtered set contains `f3`, which is not correct.

**Comment by cpovirk** [comment]
I think this is adequately covered by [the existing docs](http://google.github.io/guava/releases/18.0/api/docs/com/google/common/collect/Collections2.html#filter(java.util.Collection, com.google.common.base.Predicate)):

> **Warning:** `predicate` must be _consistent with equals_, as documented at Predicate.apply(T). Do not provide a predicate such as Predicates.instanceOf(ArrayList.class), which is inconsistent with equals.
