### ISSUE TITLE
Consider exposing Cut as a public abstraction

### ISSUE THREAD

**Issue by joshrose** [google/guava#2233]
At present, the Range abstraction is implemented in terms of Cut, but the Cut type (and the Range constructor that utilizes that type) is package-private.

Cut seems like a mathematically-sound concept -- something that's unlikely to change soon. And there are a number of Range construction use cases where the ability to define a new Range in terms of Cuts would be a useful public operation to support. One common use case has to do with Nullable (or Optional, as you will) bounds. It's often the case that APIs, particularly external APIs like RESTful interfaces, might provide either or none of the endpoints of a range, particularly as part of a filtering request from a client. It's difficult to use the existing bounds-based static factories on Range to construct an appropriate Range easily because they (understandably) don't accept null bounds. So there's typically a lot of branching code to call the correct static factory such as .all(), .atLeast(), .atMost(), or closed() depending on whether none, either, or both of the bounds have been specified by a client

But, if code that wanted to use Guava could use Cuts directly, it could express the range constraints it wants much more directly, such as:
```
// Assume lowBound and highBound are Optional<T extends Comparable<T>>
final Cut<T> lowCut = lowBound.isPresent() ? Cut.<T>belowValue(lowBound.get()) : Cut.<T>belowAll();
final Cut<T> highCut = highBound.isPresent() ? Cut.<T>aboveValue(highBound.get()) : Cut.<T>aboveAll();
return new Range<T>(lowCut, highCut);
```

Without the ability to express the range conditions a bit more abstractly, code like that above leads to a lot of branching code to determine the correct static factory to invoke on Range.

If Cut is not the abstraction to expose publicly, maybe there's some other compact solution to this (at least in my experience) common use case of Optional / Nullable bounds?

**Comment by lowasser** [comment]
To solve your example problem with the current API, you might write

    // Assume lowBound and highBound are Optional<T extends Comparable<T>>
    Range<T> lowCut = lowBound.isPresent() ? Range.atLeast(lowBound.get()) : Range.all();
    Range<T> highCut = highBound.isPresent() ? Range.atMost(highBound.get()) : Range.all();
    return lowCut.intersection(highCut);

Could this approach address your problems more generally, by just using the exposed Range APIs with intersection?

**Comment by kevinb9n** [comment]
I always felt pleased with my little implementation choice there, but I've
never thought it would be an appropriate abstraction to expose. It's very
implementationy and just doesn't really *represent* anything in the real
world.

A Bound that is like a Cut that also knows whether it's being used as a
lower or upper (and therefore actually knows whether it's closed or not!)
is easier for a user to deal with, and I guess I can't rule out the
possible value of adding Bound-based methods.


On Fri, Nov 20, 2015 at 1:07 PM, Josh Rosenblum <notifications@github.com>
wrote:

> At present, the Range abstraction is implement in terms of Cut, but the
> Cut type (and the Range constructor that utilizes that type) is
> package-private.
>
> Cut seems like a mathematically-sound concept -- something that's unlikely
> to change soon. And there are a number of Range construction use cases
> where the ability to define a new Range in terms of Cuts would be a useful
> public operation to support. One common use case has to do with Nullable
> (or Optional, as you will) bounds. It's often the case that APIs,
> particularly external APIs like RESTful interfaces, might provide either or
> none of the endpoints of a range, particularly as part of a filtering
> request from a client. It's difficult to use the existing bounds-based
> static factories on Range to construct an appropriate Range easily because
> they (understandably) don't accept null bounds. So there's typically a lot
> of branching code to call the correct static factory such as .all(),
> .atLeast(), .atMost(), or closed() depending on whether none, either, or
> both of the bounds have been specified by a client
>
> But, if code that wanted to use Guava could use Cuts directly, it could
> express the range constraints it wants much more directly, such as:
>
> // Assume lowBound and highBound are Optional<T extends Comparable<T>>
> final Cut<T> lowCut = lowBound.isPresent() ? Cut.<T>belowValue(lowBound.get()) : Cut.<T>belowAll();
> final Cut<T> highCut = highBound.isPresent() ? Cut.<T>aboveValue(highBound.get()) : Cut.<T>aboveAll();
> return new Range<T>(lowCut, highCut);
>
> Without the ability to express the range conditions a bit more abstractly,
> code like that above leads to a lot of branching code to determine the
> correct static factory to invoke on Range.
>
> If Cut is not the abstraction to expose publicly, maybe there's some other
> compact solution to this (at least in my experience) common use case of
> Optional / Nullable bounds?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/guava/issues/2233>.
>



-- 
Kevin Bourrillion | Java Librarian | Google, Inc. | kevinb@google.com

**Comment by joshrose** [comment]
Thanks, @lowasser -- your alternative may help in a number of cases I've run into. I'll close this issue based on the quick replies.
