### ISSUE TITLE
Initialization of ClassPath ends with NullPointerException

### ISSUE THREAD

**Issue by display-none** [google/guava#2239]
An attempt to call _com.google.common.reflect.ClassPath#from_ ends with NullPointerException on IBM WebSphere 8.5.5.5. The following snippet from _com.google.common.reflect.ClassPath#getClassPathEntries_ causes issues:
```java
URLClassLoader urlClassLoader = (URLClassLoader) classloader;
for (URL entry : urlClassLoader.getURLs()) {
```
_getURLs()_ on _com.ibm.ws.bootstrap.ExtClassLoader_ returns null:

```java
    public URL[] getURLs() {
        return null;
    }

    public URL[] _getURLs() {
        return super.getURLs();
    }
```

It looks like IBM made this on purpose, so I guess reporting to Guava is more appropriate here.

**Comment by lowasser** [comment]
Is that a spec-compliant implementation?  https://docs.oracle.com/javase/7/docs/api/java/net/URLClassLoader.html#getURLs() doesn't seem to suggest the possibility of returning null there.

**Comment by kluever** [comment]
As Louis points out, `URLClassLoader.getURLs()` doesn't say anything about returning null. Since `_getURLs()` isn't part of the public `URLClassLoader` API, we couldn't call it anyways.

Please open a bug against IBM WebSphere.
