### ISSUE TITLE
UseGuavaInYourBuild wiki-page out of date

### ISSUE THREAD

**Issue by leksak** [google/guava#2240]
[UseGuavaInYourBuild](https://github.com/google/guava/wiki/UseGuavaInYourBuild) is out-of-date as it refers to old versions of guava, specifically 12.0 and 10.0.1 as opposed to the latest release 18.0.

As the latest releases are documented in the [README](https://github.com/google/guava/blob/master/README.md) file this wiki-page does not really serve a purpose, and can probably be removed.

**Comment by cgdecker** [comment]
For now I've updated the numbers to 19.0, but yeah, we may want to get rid of this page.
