### ISSUE TITLE
Add a validation result class

### ISSUE THREAD

**Issue by djeang** [google/guava#2245]
When some data are pushed to a system, we often need to get feed back mentioning if the pushed data were correct or not. If there is some errors or warnings, the client system expects to get an object containing all errors or warnings. It can be a simple list of `String` but it is more convenient if : 
   
* Prebuild severity level are possible : "error", "warn".. and "info" ?
* The object has method such as `hasErrors`, `hasWarnings`, ...
* The obkect is nestable : an item can be a validation result itsef and not only a string
* The class has fluent style factory methods (or builder) for creating  the validation result.

Martin Fowler exposes this pattern as "Notification" : http://martinfowler.com/eaaDev/Notification.html

As it is a very common and generic pattern, I would like it available directly in Guava.

**Comment by kluever** [comment]
This seems out of scope for Guava.
