### ISSUE TITLE
I want to be able to overlay Map instances in the ImmutableMap.Builder.putAll() and .put() methods.

### ISSUE THREAD

**Issue by jarrodhroberson** [google/guava#2252]
Here is the scenario.

I have a `Map<String,Object>` of defaults for something.

I want to build up a customized set of things that can be a partial set of those defaults.

I want to be able to overlay these customized things over the default and produce an `ImmutableMap` union of these two ( or more ) maps.

Right now I have to do this with a mutable map implementation and then wrap that with `.copyOf()`, I would rather be able to do it directly with the existing `Builder` implementations but I can not because they will throw exceptions because of the duplicate keys.

`Map<String,Object> mergedMaps = ImmutableMap.builder().putAll(defaults).put("custom","value").build();`

or

`Map<String,Object> mergedMaps = ImmutableMap.builder().putAll(defaults).putAll(partialOverlay).build();`

Is this something you will consider implementing?

**Comment by Stephan202** [comment]
Assuming the map of defaults specifies the complete domain, I suppose you could do the following:

```java
Map<String, Object> defaults = ...;
Map<String, Object> custom = ..;
Map<String, Object> merged = ImmutableMap.copyOf(Maps.transformEntries(defaults, custom::getOrDefault));
```

Note that `Maps::transformEntries` produces a view, so there's no unnecessary copying here.

**Comment by jarrodhroberson** [comment]
This is just as good if not better because of the unnecessary copying!

I am on Java 7 so I ended up with this.

```
final Map<Fields,Object> merged = ImmutableMap.copyOf(ImmutableMap.copyOf(Maps.transformEntries(defaults, new Maps.EntryTransformer<Fields, Object, Object>() {
                        final Map<Fields,Object> custom = imb.build();
                        @Override public Object transformEntry(@Nullable final Fields key, @Nullable final Object value)
                        {
                            return custom.containsKey(key) ? custom.get(key) : value;
                        }
                    })));
```

**Comment by jarrodhroberson** [comment]
Here is a [link to a complete Gist](https://gist.github.com/jarrodhroberson/780d38e41df96f2be980) that I use all the time now!

**Comment by lowasser** [comment]
I'm not sure what `ImmutableMap.copyOf(ImmutableMap.copyOf(...))` is doing for you?  I wouldn't expect the double copying to have any effect.
