### ISSUE TITLE
`or` methods on `Present` always check for non-nullness of argument (or the result of its evaluation)

### ISSUE THREAD

**Issue by marcthehappy** [google/guava#2253]
The semantics of `or` on an `Optional` constructed using `Optional.fromNullable` surprised me. For the sake of example, consider this sample:

```java
// Assume `possiblyAssignValue` returns type `String` which may per-execution randomly be
// either `"A"` or `null`
String maybeNotNull = possiblyAssignValue();
String definitelyNull = null;
String definitelyNotNull = "C";

System.out.println(Optional.fromNullable(maybeNotNull).or(definitelyNull).or(definitelyNotNull);
```

I would *expect* that the code would sometimes print out `A` and other times `C`, pursuant to the nullness of `maybeNotNull`; however, the `or` methods will always cause a runtime exception, because they check that the argument is not `null` (or doesn't evaluate to `null`).

In my case, I am using `Optional` to help parse a response from a server, which might contain one element or another, mutually-exclusively: if I try and use `or` to do this (which I think is reasonable), then the code throws a runtime exception anytime the first element is present. In this case, the contract with the server says that the second can (and should!) be missing.

I'm not sure if it's the best solution, but one solution that presents itself to me is having a complementary set of methods on `Optional` for the two signatures which do not accept an `Optional` argument, such as `orNullable` which checks whether `defaultValue` or `supplier.get()` evaluate to `null` and return `Optional.absent` instead of throwing an exception. Such a solution would allow developers to both idiomatically code against their own assumptions about the mutual-exclusivity of two values' nullness, and explicitly handle edge cases (e.g. where the supplied default value is unexpectedly `null`) themselves.

**Comment by ogregoire** [comment]
Can't you use the following?

    Optional<String> maybePresent = Optional.fromNullable(possiblyAssignValue());
    Optional<String> definitelyAbsent = Optional.absent();
    Optional<String> definitelyPresent = Optional.of("C");
    String value = maybePresent.or(definitelyAbsent).or(definitelyPresent);

**Comment by kluever** [comment]
We're hesitant to make any changes to the behavior of Optional given Java 8. Also ogregoire's work around sounds reasonable.
