### ISSUE TITLE
Read file failed on android platform

### ISSUE THREAD

**Issue by gengjiawen** [google/guava#2257]
I use this api to read file to String in android(guava 19.0)
```
s = Files.toString(file, Charsets.UTF_8);
```
The traditional plain ugly java works fine.

**Comment by cpovirk** [comment]
Can you provide the Android version, the equivalent Java code, and the error you see when using Guava?

**Comment by gengjiawen** [comment]
Android Build Version Info
```android
    compileSdkVersion 23
    buildToolsVersion "23.0.2"
```
Equivalent Java code
```java
    public static String readFileContent(File file) {
        InputStream inputStream;
        StringBuilder total = new StringBuilder();
        try {
            inputStream = new FileInputStream(file);
            BufferedReader r = new BufferedReader(new InputStreamReader(inputStream));
            String line;
            while ((line = r.readLine()) != null) {
                total.append(line);
            }
        } catch (FileNotFoundException e) {
            LogUtil.d(TAG, String.format("e = %s", e));
        } catch (IOException e) {
            LogUtil.d(TAG, String.format("e = %s", e));
        }

        return total.toString();
    }
```
Guava doesn't report any error.
I tried the guava 18.0, it can't read the file contents too.

**Comment by lowasser** [comment]
It's not clear what you mean?  If Guava doesn't report any error, then what
does happen?

**Comment by gengjiawen** [comment]
@lowasser it doesn't get the file content.

**Comment by gengjiawen** [comment]
And there is a weird thing about this: when i try to print the string, the expression seems not been executed at all.It not even show "s = null" or something like that.
```android
 LogUtil.d(TAG, "s = " + s);
```

**Comment by gengjiawen** [comment]
So I tried in another way, I write a simple gradle-java project use the same file and guava 19.0.
It works fine.

**Comment by gengjiawen** [comment]
will you look up to this, on android platform i still can't read the file using guava library.

**Comment by cpovirk** [comment]
Your `LogUtil` message suggests that you're not running `Files.toString` at all. There's probably a bug you need to track down. I recommend [asking on StackOverflow](https://stackoverflow.com/questions/ask?tags=guava+java).
