### ISSUE TITLE
20.0-SNAPSHOT missing from google-snapshots

### ISSUE THREAD

**Issue by Dominator008** [google/guava#2259]
Our project (https://github.com/google/closure-compiler) cannot build with GWT 2.8.0-beta1 and Guava 19.0 release. The Travis CI has been broken for a week. Can we expect a 20.0-SNAPSHOT to be published to google-snapshots soon?

**Comment by cpovirk** [comment]
Hmm, are you looking [here](https://oss.sonatype.org/content/repositories/google-snapshots/com/google/)? As far as I know, Guava has hasn't used that `google-snapshots` repository.

I would expect for the Guava snapshot to be [here](https://oss.sonatype.org/content/repositories/snapshots/com/google/guava/guava/20.0-SNAPSHOT/). Our continuous build [seems to think that it's uploaded it](https://s3.amazonaws.com/archive.travis-ci.org/jobs/98136478/log.txt), and your Maven build works for me if I switch `pom-gwt.xml` to `20.0-SNAPSHOT`.

**Comment by lindner** [comment]
Why use a SNAPSHOT at all?  Just use 19.0, better yet inherit the version from the parent pom

I had to hack the release process for v20151216 because gwt was broken in multiple places.

**Comment by Dominator008** [comment]
@cpovirk Thanks. I was looking at the wrong place.
@lindner The 19.0 release does not work with GWT 2.8.0-beta1, at least for Closure Compiler.
