### ISSUE TITLE
Maps document page has two uniqueIndex descriptions.

### ISSUE THREAD

**Issue by honeyAndSw** [google/guava#2263]
I'm watching here: [Maps.uniqueIndex](http://google.github.io/guava/releases/snapshot/api/docs/com/google/common/collect/Maps.html#uniqueIndex(java.lang.Iterable,%20com.google.common.base.Function))
I think those two are equivalent :)

**Comment by lowasser** [comment]
Are you referring to the uniqueIndex overloads taking an Iterable in one
case and an Iterator in the other?  I couldn't follow your link.

**Comment by honeyAndSw** [comment]
@lowasser oops I didn't notice that one is for Iterator, and the other one is for Iterable. will close this issue! thanks.
