### ISSUE TITLE
Generic specialization of Graph methods parameters

### ISSUE THREAD

**Issue by perceptron8** [google/guava#2341]
I think I know the argument for using Object-type parameters in this new Graph thing (is it similarity to the Collections API?), but I believe it is a good time to reconsider this in view of:
- Java changes that are (hopefully) going to come sooner or later (http://mail.openjdk.java.net/pipermail/valhalla-spec-experts/2015-December/000001.html),
- Graph being a totally new interface (at least for wider public), not released, still in beta.

It's always beneficial to have as much type-constrained API as possible. It would be especially nice in case of Graph, as it has many similarly named methods that are easy to confuse (that's my experience as of now).

I'll understand if you do nothing, but, please, at least think about doing something else.

**Comment by jrtom** [comment]
We did consciously decide to go with Object-type parameters for the reason that you guessed (congruence with the JCL interfaces), but it may be worth revisiting in light of Valhalla.  We'll discuss it and get back to this issue when we've resolved it.  Thanks.

**Comment by cpovirk** [comment]
Migrating out some comments I made internally:

> The linked Valhalla thread has been very interesting. My impression, though, is that they still feel that Object is the right signature. For example:
> 
> http://mail.openjdk.java.net/pipermail/valhalla-spec-experts/2015-December/000009.html
> 
> Now, they're probably going to change methods like contains() somehow -- for example, to have contains(T) if T is a primitive -- but the old versions will remain, and they don't [seem] too sad about that. If there's anything they wish for, it seems to be more methods like getOrDefault.
> 
> On the other hand:
> 
> - As noted on the public issue, it may be easier to call containsEdge() when you mean containsNode() (or vice versa) than it is to make the analogous error with Map (or with Collection, where there's no such thing as an analogous error).
> 
> - My impression [based on some internal research that I can't easily link here] has been that the need for Object is rarer than my link above suggests. And if you do need it -- mainly in implementing equals() -- you can always cast to `Graph<Object, Object>`.

jrtom's response to part of it:

> I assume you mean things like incidentEdges() vs. incidentNodes(), since containsEdge() isn't a thing (it would be edges().contains(), because we made an explicit decision to just let the Set interface do the talking except for the *degree() methods).
> 
> I think that confusing edges for nodes is something that's a sufficiently broken mistake that I'm not too worried about it (although I do generally advise people to use different types for the two, just to make it easier to spot things like that).  If you ask for containsKey() when you meant containsValue(), or vice versa, you're gonna have a Bad Time (TM).
> 
> I'll note that because we're tending to use Maps (or other Collections) under the hood of the Graph implementations, we probably wouldn't get a lot of mileage (if any) out of having the actual type present in the signature; we're just going to call Map.get() on the input(s) anyway, so until and unless the Map signature changes, I don't think it would change how we're doing anything internally.

I should also remind myself that methods like `adjacentNodes` throw an exception if given a node that isn't present. So we at least have checking at runtime (not as good as compile time, but something).

Also, if we stick with `Object`, we should extend Error Prone's checks to cover `Graph`.

**Comment by perceptron8** [comment]
@cpovirk I think that de8d63f and 206a5ac resolved this one (hooray!). Could you confirm, please?

**Comment by cpovirk** [comment]
Yeah, we ended up doing this, albeit motivated by the creation of [`SuccessorsFunction`](http://google.github.io/guava/releases/snapshot/api/docs/com/google/common/graph/SuccessorsFunction.html) and [`PredecessorsFunction`](http://google.github.io/guava/releases/snapshot/api/docs/com/google/common/graph/PredecessorsFunction.html), where the tighter type parameter makes it easier for users to write implementations.
