### ISSUE TITLE
Add comparison operators to Ordering

### ISSUE THREAD

**Issue by rafalkrupinski** [google/guava#2346]
Please consider adding following comparison operators to Ordering class:
- `eq(a,b)` as shortcut for `comparator.compare(a,b)==0`
- `nq(a,b)` as shortcut for `comparator.compare(a,b)!=0`
- `lt(a,b)` as shortcut for `comparator.compare(a,b)<0`
- `lte(a,b)` as shortcut for `comparator.compare(a,b)<=0`
- `gt(a,b)` as shortcut for `comparator.compare(a,b)>0`
- `gte(a,b)` as shortcut for `comparator.compare(a,b)>=0`

**Comment by cpovirk** [comment]
Duplicate of #897.
