### ISSUE TITLE
com.google.common.collect.ImmutableMap -- lacks >5 support.

### ISSUE THREAD

**Issue by danielmorozoff** [google/guava#2347]
Trying to intialize a static map larger than 5

```
static final Map<Integer, Integer> MY_MAP = Map.of(
		0x043D,0, 
		0x041D,0, 
		0x043E,1, 
                .
                .
                .                
);
```

My personal use case is a crypto mapping. But I can see this being useful in a number of other contexts.

This is the code from the lib that handles this case - com.google.common.collect.ImmutableMap 
(line 101)
```
  /**
   * Returns an immutable map containing the given entries, in order.
   *
   * @throws IllegalArgumentException if duplicate keys are provided
   */
  public static <K, V> ImmutableMap<K, V> of(
      K k1, V v1, K k2, V v2, K k3, V v3, K k4, V v4, K k5, V v5) {
    return RegularImmutableMap.fromEntries(
        entryOf(k1, v1), entryOf(k2, v2), entryOf(k3, v3), entryOf(k4, v4), entryOf(k5, v5));
  }
```
Looking at the code it seems this will require a serious rewrite to support varargs, since currently it is doing the following
```
/**
  /**
   * Returns an immutable map containing a single entry. This map behaves and
   * performs comparably to {@link Collections#singletonMap} but will not accept
   * a null key or value. It is preferable mainly for consistency and
   * maintainability of your code.
   */
  public static <K, V> ImmutableMap<K, V> of(K k1, V v1) {
    return ImmutableBiMap.of(k1, v1);
  }

   * Returns an immutable map containing the given entries, in order.
   *
   * @throws IllegalArgumentException if duplicate keys are provided
   */
  public static <K, V> ImmutableMap<K, V> of(K k1, V v1, K k2, V v2) {
    return RegularImmutableMap.fromEntries(entryOf(k1, v1), entryOf(k2, v2));
  }

  /**
   * Returns an immutable map containing the given entries, in order.
   *
   * @throws IllegalArgumentException if duplicate keys are provided
   */
  public static <K, V> ImmutableMap<K, V> of(K k1, V v1, K k2, V v2, K k3, V v3) {
    return RegularImmutableMap.fromEntries(entryOf(k1, v1), entryOf(k2, v2), entryOf(k3, v3));
  }

  /**
   * Returns an immutable map containing the given entries, in order.
   *
   * @throws IllegalArgumentException if duplicate keys are provided
   */
  public static <K, V> ImmutableMap<K, V> of(K k1, V v1, K k2, V v2, K k3, V v3, K k4, V v4) {
    return RegularImmutableMap.fromEntries(
        entryOf(k1, v1), entryOf(k2, v2), entryOf(k3, v3), entryOf(k4, v4));
  }
```

As an aside...
Looking at com.google.common.collect.RegularImmutableMap. I noticed this that I was confused by, but seem by design. 

On line 84 - the creation of the map, why do you not allow for same K -> V mappings? This seems intentional to me, but breaks my implementation as I am trying to create a crypto mapping that has multi K -> one V mapping.

```checkNoConflictInKeyBucket(key, newEntry, existing);```

**Comment by lowasser** [comment]
If you need more than five entries, the Builder supports that; providing of() factory methods for n>5 is already requested in https://github.com/google/guava/issues/2071.

As far as the "multi K -> one V" issue, I'm not sure I follow what you are asking for.  The possibilities are
- if you want to be able to put one key in more than once with different values and have them all collected, use a Multimap
-if you want the last value put for a key to win, use a normal mutable Map and then copy it at the end
-if you want multiple keys mapped to the same value, that will work just fine without problems

**Comment by danielmorozoff** [comment]
Thanks for the quick reply.

Didn't see #2071 --  same issue. Thanks for the builder link.
And yep-- the ImmutableMultimap is what I am looking for thanks again.

**Comment by danielmorozoff** [comment]
Here is the apache commons implementation:

https://commons.apache.org/proper/commons-collections/apidocs/org/apache/commons/collections4/map/MultiKeyMap.html

**Comment by lowasser** [comment]
That looks like a completely different thing than anything provided by Guava?  That appears to be a fancy way of using tuples to map to a single value, as far as I can tell.  The closest thing to that provided by Guava is Table, but the general recommendation is that you go ahead and make an actual tuple type.
