### ISSUE TITLE
List<T> from (size, IntFunction<T>)

### ISSUE THREAD

**Issue by michaelhixson** [google/guava#2348]
Sometimes I have elements that are effectively indexed like a list and I want to view them as a `java.util.List`.  I've found it handy to have a utility method that creates a list from a generator function.  This would be similar to Dart's [List.generate](https://api.dartlang.org/1.13.1/dart-core/List/List.generate.html) factory, except it wouldn't copy the source elements into new storage.

Example usage:

```
public List<Path> getNames(Path path) {
  return Lists.onDemandList(path.getNameCount(), path::getName);
}
```

Here's the javadoc I wrote for my implementation of the method, in case it clarifies what I'm requesting here:

```
/**
 * Returns a fixed-size, unmodifiable list whose elements are supplied on
 * demand by a function.  Invoking {@linkplain List#get(int) list.get(i)}
 * for a valid index {@code i} returns the result of
 * {@linkplain IntFunction#apply(int) indexToElement.apply(i)}.
 *
 * <p>The list is a <em>view</em> of the function.  If the output of the
 * function changes over time, then so will the elements in the list.  If
 * the function is a pure function, then the list is effectively
 * immutable.
 *
 * <p>The list and its sublist views are serializable if the function is
 * serializable.
 *
 * @param <T> the type of elements in the list
 * @param size the size of the list
 * @param indexToElement a function accepting an index and supplying the
 *                       element at that index
 * @return a list of elements supplied by the given function
 * @throws IllegalArgumentException if {@code size < 0}
 * @throws NullPointerException if {@code indexToElement == null}
 */
public static <T> List<T> onDemandList(
    int size, IntFunction<? extends T> indexToElement) { ... }
```

**Comment by PhilippWendler** [comment]
This can be relatively easily done with [`java.util.AbstractList`](https://docs.oracle.com/javase/7/docs/api/java/util/AbstractList.html), except that it does not allow you to use method references:

```
public List<Path> getNames(final Path path) {
  return new AbstractList<String>() {
    public int size() { return path.getNameCount(); }
    public String get(int i) { return path.getName(i); }
  );
}
```

**Comment by michaelhixson** [comment]
@PhilippWendler Yes, the minimal implementation of this method looks a lot like that.  A more complete implementation can make improvements:

* Validate the size and indexes, throwing the right exceptions for bad arguments.
* Implement `RandomAccess` and `Serializable`, and make the `subList` views do the same (`subList`s can be instances of the same concrete class as the outer list).
* Optimize performance, especially for `forEach`, `iterator`, `listIterator`, and `spliterator`.

**Comment by cpovirk** [comment]
We mostly regret our APIs that perform on-demand computation like this (`Iterables.transform`, etc.). The JDK's model of a single-use `Stream` that can be materialized into a collection is less prone to surprises. (Your use case here would be fine, but occasionally we see transformations that create new mutable objects, like `Future` instances.) And as noted above, `AbstractList` offers an alternative, and it has the virtue of making clear to that every call to `list.get(...)` will run whatever logic you put in the implementation of `get`.

(As an aside, I'm just mildly surprised that [the JDK offers `Arrays.setAll(T[], IntFunction)` but not `Lists.setAll(List, IntFunction)`.)
