### ISSUE TITLE
bug: Cache.weakKeys() doesn't work.

### ISSUE THREAD

**Issue by yuhanz** [google/guava#2352]
I am expecting the cache to evict keys after System.gc(). This requires:
- cache.getIfPresent(v) works
- cache is cleared after System.gc()

But unfortunately it couldn't satisfy both conditions.

Here is how I created the cache:
```
        Cache cache = CacheBuilder.newBuilder()
                .weakKeys().build();
```
- Eviction works when the key is created and not assigned to a variable
```
        cache.put(Math.random(), "a");
        System.out.println("cache: " + cache.asMap());
        System.gc();
        System.out.println("cache: " + cache.asMap());
```

This showed the correct output:
```
cache: {0.7254227566649404=a}
cache: {}
```

- Eviction doesn't work if the the key is assigned to a local variable:
```
        Cache cache = CacheBuilder.newBuilder()
                .weakKeys().build();
        {
        Double r = Math.random();
        cache.put(r, "a");
        }
        System.out.println("cache: " + cache.asMap());
        System.gc();
        System.out.println("cache: " + cache.asMap());
```
This showed the wrong output:
```
cache: {0.006581944795823524=a}
cache: {0.006581944795823524=a}        //  <=== notice here, the value is still in cache.
```

- Eviction works with primitive, but cache doesn't work
```
        double r = Math.random();
        cache.put(r, "a");
        System.out.println("cache: " + cache.asMap());
        System.out.println("v: " + cache.getIfPresent(r));
        System.gc();
        System.out.println("cache: " + cache.asMap());
```
This showed the wrong output:
```
cache: {0.3569447241229746=a}
v: null                     // <===  autoboxed Double at different time will give different segment hashes.
cache: {}
```

So, with Cache.weakKeys(), we don't have eviction on System.gc(), or cache with keys that don't have a match.

**Comment by lowasser** [comment]
> Eviction doesn't work if the the key is assigned to a local variable:

Eviction isn't supposed to happen in this case: weakly referenced objects are only supposed to be garbage collected if there are no strong references to them remaining, and by assigning the key to a local variable, you create a strong reference to it.

> Eviction works with primitive, but cache doesn't work

This is also working as intended.  Note the line from the `weakKeys` Javadoc:

> Warning: when this method is used, the resulting cache will use identity (==) comparison to determine equality of keys.

A re-boxed `double` will not be `==` to the earlier boxing, so `getIfPresent` is supposed to return null here.  Generally speaking, `weakKeys` does not make sense to use with objects that have a notion of equality other than reference equality.

**Comment by yuhanz** [comment]
@lowasser Is there a way to construct the key when using .weakKeys(), then?

because
- when key is primitive, getIfPresent() doesn't work as using ==
- when key is object, getIfPresent() works; but we have to keep a reference of the object for future matching, which is a strong reference.

**Comment by lowasser** [comment]
@yuhanz, what that information tells me is that `weakKeys()` is a bad idea for your use case.  Garbage collection based caching just doesn't make sense for your problem.

**Comment by yuhanz** [comment]
I think the use case is very general for expectation on .weakKeys(). not quite satisfied with this answer.

**Comment by lowasser** [comment]
It's not clear to me why you think `.weakKeys()` is a good idea for your use case.  All of this is based around how weak references work, at a fundamental level.  Guava doesn't even control when weak references are GC'd; that's implemented as part of the Java language.

**Comment by yuhanz** [comment]
I will explore other alternative then. I don't think the current implementation of .weakKeys() works for me if it behaves this way.

**Comment by lowasser** [comment]
@yuhanz, it sounds like you would be better off with `maximumSize` or some other size-based constraint, then.  All the details of how `weakKeys()` works pretty much inevitably follow from what weak references are and how they're implemented in the Java language.

**Comment by yuhanz** [comment]
Thanks for the information on weakKeys(). Good to find out it is only intended for comparison with == operator, and not intended for the GC based caching.

**Comment by lowasser** [comment]
It is intended for the GC based caching, it's just that if you want to GC the cache entry as soon as there are no other `==` references -- which is how weak references work in Java -- then there's not much point in using `.equals`, as if you don't have another `==` reference, your cache entry will be GC'd before you can do anything with it.

**Comment by yuhanz** [comment]
ah I see. I constructed the demo code to examine wrongly. (I thought out of scope with {} would remove the reference.) GC removes the cache entry after I refactored the demo code into a method.

you are right that it doesn't fit my use case.
