### ISSUE TITLE
testEquals_otherContainsNull looks up null value even if CollectionFeature.ALLOWS_NULL_QUERIES is not specified

### ISSUE THREAD

**Issue by cdman** [google/guava#2356]
[testEquals_otherContainsNull](https://github.com/google/guava/blob/a9f8b899c07a33c2203b4e6cf84861646952aeed/guava-testlib/src/com/google/common/collect/testing/testers/SetEqualsTester.java#L67) looks up the "null" value in the set-under-test (indirectly, by comparing it with a test that contains null), even if CollectionFeature.ALLOWS_NULL_QUERIES was not specified.

IMHO this test should be conditioned on CollectionFeature.ALLOWS_NULL_QUERIES being specified during the generation of the test suite.

**Comment by lowasser** [comment]
Hmmm.  It's not entirely clear to me whether throwing on equals(collectionContainingNull) is actually allowed by the spec, even in cases where e.g. containsAll is permitted to throw.

**Comment by cdman** [comment]
Just to give some context: I'm trying to test the [fastutil](http://fastutil.di.unimi.it/) collections using guava-testlib and that's how I run into this scenario ([IntOpenHashSet](http://fastutil.di.unimi.it/docs/it/unimi/dsi/fastutil/ints/IntOpenHashSet.html) throws NPE for example on equals if the "other" collection contains null).

Agreed, this is an ambiguous case. I will also try to bring it up on the fastutil mailing list, perhaps it can be resolved there.

**Comment by tavianator** [comment]
@lowasser I'm pretty sure `equals()` is not permitted to throw in that case.  Otherwise it would be non-symmetric with `HashSet`.

**Comment by kluever** [comment]
`equals()` shouldn't be allowed to throw. The collection under test sounds faulty.
