### ISSUE TITLE
com.google.common.base.Joiner append

### ISSUE THREAD

**Issue by aqzwss** [google/guava#2358]
Hi, can I just append a String variable at the start or end of this Joiner, before invoking its join method.
For example:
build a dynamic sql string like below:
("a", "b", "c")
now there is a set named "container" contains these three elements
and I can use Joiner.on(",").join(container) to build a String "a,b,c"
after that I must add "(" and ")" manually.
Is there a exist method to let me append the fixed String "(" and ")" to this instance of Joiner so that I can build up automatically.

**Comment by lowasser** [comment]
This is a duplicate of https://github.com/google/guava/issues/463.

**Comment by aqzwss** [comment]
thx
