### ISSUE TITLE
EventBus hasSubscriberFor event type

### ISSUE THREAD

**Issue by bentatham** [google/guava#2359]
In some cases, generating an event can be expensive.  If there are no subscribers for that event, it would be nice to be able to check that before doing the work of creating such an event, and thus skip it.  

This is similar to logging frameworks that can check that logging level before constructing the log message.

I think the race condition that there may be a subscription for that event type shortly after the check is something we can live with and can be documented as such in this new method.

I imagine the API on `EventBus` would have something like:

``` java
  boolean hasSubscriberFor(Class<?> eventType);
```

**Comment by JLLeitschuh** [comment]
Couldn't you just lazily initialize the data for the event? Have your event take a supplier in the constructor. Then the object won't be initialized unless some subscriber asks for it.

**Comment by cgdecker** [comment]
I'm closing this issue because we are no longer going to be making changes to `EventBus` other than important bug fixes. The reasons we're discouraging it and some alternatives are listed in the [EventBus javadoc](https://guava.dev/EventBus).
