### ISSUE TITLE
XTestSuiteBuilder not suitable for collections with less than 5 elements

### ISSUE THREAD

**Issue by cdman** [google/guava#2364]
SampleElements requires 5 distinct elements in the constructor (if they are not distinct some tests) but some collections (like the [Boolean collections from fastutil](http://fastutil.di.unimi.it/docs/it/unimi/dsi/fastutil/booleans/package-summary.html)) only have two distinct values.

**Comment by kevinb9n** [comment]
We believe addressing this would add a lot of complexity compared to very small payoff, but if anyone wants to make a specific proposal, please reopen.
