### ISSUE TITLE
Map::replaceAll breaks HashBiMap::inverse

### ISSUE THREAD

**Issue by muued** [google/guava#2367]
Hi, I just tried updating a HashBiMap using replaceAll and a second HashBiMap, but kept getting the error "java.lang.IllegalArgumentException: value already present: null".
After checking my own code, I set up a minimal code example to see what was going wrong.
It seems like calling replaceAll on an inverse of a HashBiMap doesn't work.

The println lines are just there to show you that it should work as in the line where I combine the two maps.

	final int upperBound = 2;
	final HashBiMap<Integer, Integer> b2a = HashBiMap.create();
	IntStream.range(0, upperBound).forEach(i -> b2a.put(i, 100 + i));
	System.out.println("b2a" + b2a);
	final HashBiMap<Integer, Integer> b2c = HashBiMap.create();
	IntStream.range(0, upperBound).forEach(i -> b2c.put(i, 200 + i));
	System.out.println("b2c" + b2c);
	final BiMap<Integer, Integer> a2b = b2a.inverse();
	System.out.println("a2b" + a2b);
	System.out.println("a2c" + Maps.asMap(a2b.keySet(), k -> b2c.get(a2b.get(k))));
	a2b.replaceAll((a, b) -> b2c.get(b));
	System.out.println("a2b'" + a2b);

It is interesting to note, that putAll for a copy of the combined map works.

**Comment by lowasser** [comment]
There's definitely nothing we can do about this until we actually support Java 8; the default implementation of replaceAll is almost certainly not recoverable.

It's not immediately obvious to me that there's any good default implementation in the BiMap interface.  We can patch AbstractBiMap, but the only fully general implementation I can think of involves copying all the keys into a separate data structure, clearing the map, and then rebuilding the map from scratch.

**Comment by kevinb9n** [comment]
As Louis says, we don't think this can be fixed except in the forthcoming Java 8 version of Guava (where it is already fixed).
