### ISSUE TITLE
Add *Math.nextPowerOfTwo

### ISSUE THREAD

**Issue by ghost** [google/guava#2370]
There are existing `*Math.isPowerOfTwo` methods, it seems like a `nextPowerOfTwo` method is a good method to go alongside it, to return the smallest integer >= `n` that is a power of two (I was surprised this doesn't exist in guava already, TBH)

This is a simple operation that has a wide range of applications (sizing buffers, primarily, but it also has uses in collection implementations etc), and it's not immediately obvious what the bit-twiddling algorithm is doing when it appears in a codebase. Would seem like a prime candidate for an addition to guava.

There's a simple bit-twiddling algorithm for ints & longs; doubles & bigintegers can probably use a combination of the existing log, floor & pow methods, unless there are clever ways of doing the same for those types (also see http://stackoverflow.com/questions/466204/rounding-up-to-nearest-power-of-2)

**Comment by ogregoire** [comment]
`return Integer.highestOneBit(n) << 1` ?

**Comment by simonmcooper** [comment]
When `n` is already a power of two, this will return the next highest one (I want >=, not >). Admittedly, this can be solved using a check for `IntMath.isPowerOfTwo`, but it's still not exactly obvious. There is a related method `BigInteger.bitCount` that can be used for bigintegers, but nothing for doubles that I can see...

**Comment by ogregoire** [comment]
Well, if I have `int n = 4;` and I call `int x = Blah.nextPowerOfTwo(n)`, I logically expect that `x == 8`. Because "next", to me, means "not this one, but the one after".

**Comment by ben-manes** [comment]
A simple version of that would then be below, which is what I use when needed. As its a one-liner I just put the method in the class since its only rarely needed.

```java
static int ceilingNextPowerOfTwo(int x) {
  // From Hacker's Delight, Chapter 3, Harry S. Warren Jr.
  return 1 << (Integer.SIZE - Integer.numberOfLeadingZeros(x - 1));
}
```

**Comment by tworec** [comment]
+1 :)

**Comment by ogregoire** [comment]
With Ben's insight, you can still write:

    return Integer.highestOneBit(n - 1) << 1;

Note the `n - 1`.

**Comment by tworec** [comment]
doesn't work for n <= 0

**Comment by ogregoire** [comment]
Powers of two are positive, it makes no sense to use negative values...

**Comment by tworec** [comment]
but your code returns 0 for 0 and all negative integers, and should return 1

**Comment by lowasser** [comment]
If we were to implement this, then we'd almost certainly just throw on
negative input rather than guessing at what behavior is "most sensible."

**Comment by tworec** [comment]
If this is purpose (as @simonmcooper originallly wrote)
> nextPowerOfTwo
> return the smallest integer >= n that is a power of two
than you should return at least 1 for all inputs
see http://graphics.stanford.edu/~seander/bithacks.html#RoundUpPowerOf2Float
or throw

**Comment by leventov** [comment]
Strange that this is not in Guava

**Comment by ben-manes** [comment]
Are you looking for `IntMath#ceilingPowerOfTwo(x)`? I think it was implemented due to this issue, but accidentally not closed.

**Comment by leventov** [comment]
@ben-manes thank you. Google (the search engine, not the company) is somehow bad at finding methods in published Guava's Javadocs.
