### ISSUE TITLE
Range.closedOpen(0, Integer.MIN_VALUE) shouldn't fail

### ISSUE THREAD

**Issue by cowwoc** [google/guava#2374]
`Range.closedOpen(0, Integer.MIN_VALUE)` throws `IllegalArgumentException: Invalid range: [0?-2147483648)` but by my understanding, it should not.

The implementation seems to fail because it sees `upper` as being less than `lower` but in practice it should be comparing `upper-1` to lower since the upper cut is open. `upper-1` is indeed greater than `lower` so I am expecting this Range to be valid. Is this a bug or a misunderstanding on my part?

**Comment by lowasser** [comment]
I think it's a misunderstanding.  `Range`, by itself, knows nothing about the type except that it is `Comparable`; it certainly can't do `upper-1` for non-integer types.  This is definitely working as intended.

Depending on what behavior you want, `Range.atLeast(0)` might be what you want?

**Comment by cowwoc** [comment]
@lowasser I understand but this is definitely non-intuitive. My API takes an inclusive `min` and exclusive `max` parameters. I need users to be able to specify a range that includes `[0, Integer.MAX_INTEGER]` or even spans the entire range of possible Integers.

How would I check whether some value is included in `[min, max)` if `max` can't be equal to `Integer.MAX_INTEGER`?

**Comment by lowasser** [comment]
> How would I check whether some value is included in [min, max) if max can't be equal to Integer.MAX_INTEGER?

Do you mean `x >= min && x < max`?

**Comment by lowasser** [comment]
The `Range` API is intended to work simply and correctly for arbitrary `Comparable`s.  `Range.closedOpen(a, b)` contains exactly those elements `x` for which `x.compareTo(a) >= 0 && x.compareTo(b) < 0`.  That avoids off-by-one shenanigans and keeps everything clean and simple.

If your API takes an inclusive `min` and an exclusive `max`, then it sounds like it can't include `Integer.MAX_VALUE` as a valid element inside the range.

**Comment by lowasser** [comment]
If it helps, think of it as working exactly like normal mathematics.  If we're just talking about arbitrary integers mathematically, [0, -2147483648) makes no sense.  [0, infinity) makes sense; [0, 2147483647] makes sense.  Guava's just staying consistent with that.

I'm not sure there's anything we _could_ do to support what you're going for; again, `Range.closedOpen` accepts `Comparable` arguments, not `Integer`s specifically, so we can't do any arithmetic with them.

**Comment by cowwoc** [comment]
Correct. That is the condition I want to check for but I want to express this in terms of a `Range`. The expression you mentioned (`x.compareTo(a) >= 0 && x.compareTo(b) < 0`) holds true for my case but `a > b` does not for the aforementioned reasons.

So if I understand you correctly, you are saying that it is strictly impossible for `Range.closedOpen()` to contain the value `Integer.MAX_VALUE`? If so, I have two comments:

1. Does it really makes sense for `Range` to enforce `a > b` if it doesn't have the ability to translate `b` from open to closed? Wouldn't it better to leave out this check and let the user assert it outside the API?
2. Is it reasonable to use this as a workaround? `Range.closed(min, max-1)` If so, perhaps it makes sense to mention this in the Javadoc? Example: "Please note that closedOpen() cannot contain the maximum value of the underlying type. Consider using closed(min, max-1) for such cases instead of closedOpen(min, max)."

Update (having read your last post): Is there a way to represent `[0, infinity]` as you mentioned using `Range` for Integers? If so, how?

**Comment by lowasser** [comment]
> Does it really makes sense for Range to enforce a > b if it doesn't have the ability to translate b from open to closed? Wouldn't it better to leave out this check and let the user assert it outside the API?
If `a < b`, then by the contract for `Comparable`, nothing can be `>= a` and `< b`.  The ability to translate between open and closed is handled optionally with e.g. `Range.canonical` for those types that support it with `DiscreteDomain`, but not for all ranges generally.

> Update (having read your last post): Is there a way to represent [0, infinity] as you mentioned using Range for Integers? If so, how?
Yes.  `Range.atLeast(0)` will do that.

> Is it reasonable to use this as a workaround? Range.closed(min, max-1) If so, perhaps it makes sense to mention this in the Javadoc? Example: "Please note that closedOpen() cannot contain the maximum value of the underlying type. Consider using closed(min, max-1) for such cases instead of closedOpen(min, max)."
That doesn't make sense for many or even most types used with `Range`, which don't necessarily have addition or even a maximum value.  The docs for `closedOpen` say

> Returns a range that contains all values greater than or equal to lower and strictly less than upper.

which seems relatively unambiguous.

**Comment by cowwoc** [comment]
Fair enough. Thank you for the explanation.
