### ISSUE TITLE
EventBus identifier can't be set for constructor with SubscriberExceptionHandler

### ISSUE THREAD

**Issue by JLLeitschuh** [google/guava#2375]
If you are using the EventBus constructor that that takes the `SubscriberExceptionHandler` you can't set the identifier.

Should an additional constructor be added so you can set the identifier?

http://google.github.io/guava/releases/19.0/api/docs/com/google/common/eventbus/EventBus.html#EventBus(com.google.common.eventbus.SubscriberExceptionHandler)

**Comment by cgdecker** [comment]
At some point (I have a plan but just haven't found time to actually finish doing it) I want to add a builder for `EventBus` since constructors are bad for optional parameters like this.

**Comment by JLLeitschuh** [comment]
Awesome.
Thanks!

**Comment by poseidon42** [comment]
I just ran into the same issue missing the two-arg constructor - maybe its addition would be an easy but effective fix? a builder is cool, but needs more time to implement and test, i assume.

**Comment by aschatten** [comment]
@cgdecker Is it being worked on by anyone? Do you have any specific design in mind? I would like to submit a PR for this.

**Comment by cpovirk** [comment]
Realistically, we're unlikely to add functionality to EventBus at this point.
