### ISSUE TITLE
Preconditions.checkState throws NoSuchMethodError

### ISSUE THREAD

**Issue by Dominator008** [google/guava#2380]
I'm getting many
java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkState(ZLjava/lang/String;I)V
exceptions with 20.0-SNAPSHOT

To reproduce:
1. Checkout https://github.com/google/closure-compiler/commit/583b50ce47215846ef8e81025ac27e8fc1cac448
2. Run "mvn test"
3. Will see errors like:
java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkState(ZLjava/lang/String;I)V

I suspect https://github.com/google/guava/commit/1ef638f369964c1d1f56bd0ae588535c6abd99a4
might have something to do with this?

**Comment by cpovirk** [comment]
Yuck. Thanks for the report.

I'm wondering if `closure-compiler` is somehow getting two separate versions of Guava. (After all, I don't think that 1ef638f _removed_ anything.) I see a reference to 19.0 [here](https://github.com/google/closure-compiler/blob/7278fff6e7f76c9a789245ae5fed4c2ecac00731/pom-main.xml#L73). Can that be changed to 20.0-SNAPSHOT to match `pom-gwt.xml`?

**Comment by kevinb9n** [comment]
This should be reported to closure-compiler; they have a classpath issue.
For example they may be somehow involving both a released Guava and a
snapshot Guava the same time.



On Tue, Feb 2, 2016 at 9:03 AM, Michael Zhou <notifications@github.com>
wrote:

> I'm getting many
> java.lang.NoSuchMethodError:
> com.google.common.base.Preconditions.checkState(ZLjava/lang/String;I)V
>
> exceptions with 20.0-SNAPSHOT
>
> To reproduce:
> 1. Checkout google/closure-compiler@583b50c
> <https://github.com/google/closure-compiler/commit/583b50ce47215846ef8e81025ac27e8fc1cac448>
> 2. Run "mvn test"
> 3. Will see errors like:
> java.lang.NoSuchMethodError:
> com.google.common.base.Preconditions.checkState(ZLjava/lang/String;I)V
>
> I suspect 1ef638f
> <https://github.com/google/guava/commit/1ef638f369964c1d1f56bd0ae588535c6abd99a4>
> might have something to do with this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/guava/issues/2380>.
>



-- 
Kevin Bourrillion | Java Librarian | Google, Inc. | kevinb@google.com

**Comment by kevinb9n** [comment]
(Hadn't seen Chris's reply yet, but looks like my suspicion may have been
right on the money :-))

On Tue, Feb 2, 2016 at 9:25 AM, Chris Povirk <notifications@github.com>
wrote:

> Yuck. Thanks for the report.
>
> I'm wondering if closure-compiler is somehow getting two separate
> versions of Guava. (After all, I don't think that 1ef638f
> <https://github.com/google/guava/commit/1ef638f369964c1d1f56bd0ae588535c6abd99a4>
> *removed* anything.) I see a reference to 19.0 here
> <https://github.com/google/closure-compiler/blob/7278fff6e7f76c9a789245ae5fed4c2ecac00731/pom-main.xml#L73>.
> Can that be changed to 20.0-SNAPSHOT to match pom-gwt.xml?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/guava/issues/2380#issuecomment-178699974>.
>



-- 
Kevin Bourrillion | Java Librarian | Google, Inc. | kevinb@google.com

**Comment by Dominator008** [comment]
@cpovirk @kevinb9n Bumping the one in pom-main.xml to 20.0-SNAPSHOT works, thanks!
