### ISSUE TITLE
Add functionality for base85 'ascii85'

### ISSUE THREAD

**Issue by fzakaria** [google/guava#2381]
It would be useful to add missing functionality to BaseEncoding for base85 or ascii85 as its called.
There doesn't seem to many libraries that offer it (actually none) and it would be another leg up over apache.

https://en.wikipedia.org/wiki/Ascii85

**Comment by kluever** [comment]
Do you have an immediate use for this (compatibility reasons)? We tend not to add features just to add features.

(I did search internally in google's codebase, and found very few usages of base85 encoding in Java.)

**Comment by kevinb9n** [comment]
Thanks. I suspect no other libraries offer it because, most likely, for 99.9% of purposes base 64 is perfectly fine. If there are very compelling reasons for ascii85 then those should be argued. But we really don't compare ourselves to Apache.

**Comment by fzakaria** [comment]
Fair enough.
I'll close.

I found it personally useful and thought it might have a good fit here.
