### ISSUE TITLE
Need clarifications on the behaviour of the map returned from `Maps.transformValues()`

### ISSUE THREAD

**Issue by ratanasv** [google/guava#2388]
```
@Test
public void thisWillPass() {
    Map<String, AtomicInteger> map = ImmutableMap.of("foo", new AtomicInteger(0));

    increment(map);

    verify(map);
}

@Test
public void thisWillFail() {
    Map<String, Integer> map = ImmutableMap.of("foo", 0);
    Map<String, AtomicInteger> aMap = Maps.transformValues(map, number -> {
        return new AtomicInteger(number);
    });

    increment(aMap);

    verify(aMap);
}

private void increment(final Map<String, AtomicInteger> map) {
    map.get("foo").incrementAndGet();
}

private void verify(final Map<String, AtomicInteger> map) {
    Assertions.assertThat(map.get("foo").get()).isEqualTo(1);
}
```

I have two test cases where one fails and the other passes. In both cases I attempt to increment an instance of AtomicInteger in a map by one. A map constructed manually works fine with the increment() method, while a map returned from Maps.transformValues() fails.

Is this by design? It's not clear to me from reading the API doc.

**Comment by lowasser** [comment]
This is definitely working as intended -- `transformValues` does no storage of its own; it you pass it the function you've passed it here, you'll get a new `AtomicInteger` every time.

The doc isn't quite as explicit about this as it could be, but it's the only implementation that would satisfy the spec.  Particularly relevant is the last paragraph:

>  The function is applied lazily, invoked when needed. This is necessary for the returned map to be a view, but it means that the function will be applied many times for bulk operations like Map.containsValue(java.lang.Object) and Map.toString(). For this to perform well, function should be fast. To avoid lazy evaluation when the returned map doesn't need to be a view, copy the returned map into a new map of your choosing.

**Comment by ratanasv** [comment]
I see. When I first read that paragraph, I interpreted "applied lazily" as lazy initialization, i.e. the function will be invoked eventually once. Your comment that it "does no storage of its own" really clarifies that. Thanks!
