### ISSUE TITLE
Incoherent miss count in cache stats

### ISSUE THREAD

**Issue by rrevol** [google/guava#2389]
Sometimes, after a lot of concurrent GET on a guava cache with the same key, the miss count may not be coherent.

My current understanding of the cache behavior is that threads performing concurrent GET for an un-cached key will all be blocked but one, the one performing the load, until the latter returns and then each thread gets the value. This will increment the miss count by the number of threads that were blocked. Any subsequent GET for the same key by one of these threads should hit the cache (no eviction assumed here) and so miss counter should not be incremented anymore.

Assuming this behavior, I've developped the following test to emphasize the wrong counts I've observed. 

[See test gist](https://gist.github.com/rrevol/8ab557eeb3b9f1185256)

**Comment by ben-manes** [comment]
It appears that both the initial computation that missed (`lockedGetOrLoad`) and the subsequent reads waiting for the computation (`waitForLoadingValue`) both increment the miss count. I don't know why `waitForLoadingValue` is incrementing, but I only took a cursory glance.

The gist passes when running against [Caffeine](https://github.com/ben-manes/caffeine) (using the guava adapters).

**Comment by cpovirk** [comment]
This sounds bad but (as you can see) something that we're not likely to fix, given that we recommend Caffeine over common.cache nowadays.
