### ISSUE TITLE
Characters from the unicode in cpXXX not displayed

### ISSUE THREAD

**Issue by Polyakov-Andrey** [google/guava#2391]
Characters from the unicode in cpXXX not displayed 
D:\Projects\Scripte\gam-3.63-windows>gam info user ********
User: *********
Traceback (most recent call last):
  File "<string>", line 9136, in <module>
  File "<string>", line 6352, in doGetUserInfo
  File "C:\Users\jlee\Documents\GitHub\gam363\src\build\gam\out00-PYZ.pyz\encodings.cp866", line 12, in encode
UnicodeEncodeError: 'charmap' codec can't encode character u'\u0456' in position 16: character maps to <undefined>

**Comment by lowasser** [comment]
It is not at all clear how or even if this is related to Guava.  Can you provide more details?

**Comment by Polyakov-Andrey** [comment]
Console in cp866 - Cyrillic script
User information have same fields in UTF-8 with char Cyrillic (not English)
Error: It is not translation ftom UTF-8 (not English) to cpXXX
Note: UTF-8 - 2-byte vs cpXXX - 1-byte

**Comment by lowasser** [comment]
How is Guava involved in this?

**Comment by Polyakov-Andrey** [comment]
:) Sorry. Wrong project
