### ISSUE TITLE
Performance of reading from cache

### ISSUE THREAD

**Issue by gogainda** [google/guava#2393]
In my case average time of reading from cache is about 4.567693ms, but in some cases this time could slow down to 13ms. What could be an issue here?

``` java
private final val cachedData = CacheBuilder.newBuilder
    .expireAfterWrite(5, TimeUnit.MINUTES)
    .recordStats()
    .build(new CacheLoader[Set[String], Set[String]] {
      override def load(aggregateIds: Set[String]): Set[String] = {        
        fetchSomeDataFromDB
      }
    })
```

I have a file with 40000 row, for each row  I read from cache. For first file reading from cache is really fast, but when I process this file again - reading from cache slows down to 13ms. aggregateIds for 2 files the same, so I expect the same performance.

Stats are following

```
hitCount = 67172
missCount = 4
loadSuccessCount = 4
loadExceptionCount = 0
totalLoadTime = 13476244193
evictionCount = 3
```

**Comment by ben-manes** [comment]
Can you create a reproducible example?

A possible slow down could be due to the `Set`-based key having a slow hash/equality check on a collision in a full cache. Running your code through a profiler should quickly identify the hot spots.

**Comment by gogainda** [comment]
Seems you are right, I made a string out of Set aggregateIds and used it as a key. The speed of retrieving a value from cache reduced to roughly 0 or 1 ms

**Comment by gogainda** [comment]
I had very long set as key (about 30k entries), don't do it.

**Comment by milovtim** [comment]
@gogainda, if it is not guava cache issue it could be closed

**Comment by slyr91** [comment]
Is this a guava issue? CodeTriage sent this one to me today but there doesn't appear to be an issue here. Maybe just accidentally left open?

**Comment by chaminiPrashakthi** [comment]
I also use
` LoadingCache<String, List<ArchetypeConceptData>> loadingCache= CacheBuilder.newBuilder().expireAfterAccess(5, TimeUnit.MINUTES).build(cacheLoader);`

when loading dataI saw that some datas are missing there.(Data which was saved just now)
Is it alos happens due to guava issue?
