### ISSUE TITLE
Throwables.propagate should throw UncheckedIOException where appropriate

### ISSUE THREAD

**Issue by simonmcooper** [google/guava#2397]
Currently, `Throwables.propagate` wraps all checked exceptions in a `RuntimeException`. Java 8 added `UncheckedIOException` specifically to wrap an `IOException` in an unchecked exception. `Throwables.propagate` should check for `IOException` and use this class rather than the raw `RuntimeException`.

This is a compatible change, as `UncheckedIOException` extends `RuntimeException`.

**Comment by pivovarit** [comment]
Well, the idea is fine, but it would ruin the compatibility with previous Java versions.

**Comment by simonmcooper** [comment]
Well, this is for Java 8 only, obviously...

**Comment by pivovarit** [comment]
Guava is supposed to work not only in Java8. It's even shown in tests that verify validity against different java versions

**Comment by cpovirk** [comment]
As @pivovarit notes, we want to work on older versions of Java. And while we will be [requiring Java 8 soon (except on Android)](https://groups.google.com/d/topic/guava-discuss/ZRmDJnAq9T0/discussion), we would prefer to minimize differences in behavior between the Java 8 and Android versions.
