### ISSUE TITLE
Empty ranges

### ISSUE THREAD

**Issue by messo** [google/guava#2400]
I believe a more generic **empty** range could be introduced, because `(v..v]` and `[v..v)` have their side-effects.

Given `a = (5..5]`, `b = [10..15]` currently `a.span(b)` is equal to `(5..15]`. This is because `[10..15]` doesn't currently _encloses_ `(5..5]` but since it is basically an empty range I believe general empty ranges should be enclosed by every other range.

Introducing a generic empty range would have the benefit of having the followings:
* `range.encloses(empty) == true`, for every `range`
* `empty.encloses(range) == false`, for every `range` except `range === empty`
* `empty.span(range) == range` and `range.span(empty) == range` for every `range`

What do you think?

**Comment by cpovirk** [comment]
Forbidding the empty `Range` was an intentional choice that has been baked pretty deeply into the class's model at this point, so we won't be changing it. Users who require it may be able to get by with using `RangeSet` objects (which can be empty), using `Optional<Range>`, or rolling their own.

**Comment by messo** [comment]
I thought this would be the case, but I had to ask, because it would make it a bit better, it would make `Range<C>` I believe a ring (in mathematical sense), where `+` would be the _span_ operation, `⋅` would be the _intersect_ operation. The additive identity would be the `Range.empty()` and the multiplicative identity would be `Range.all()`.

Yeah, `Optional` could work, but just for the sake of being "empty" it isn't worth making the API uglier at the user side. `RangeSet` is a bit heavy because it would allow disconnected ranges.

**Comment by plap979** [comment]
> Forbidding the empty `Range` was an intentional choice 

This conflicts with the presence of a boolean isEmpty() method available on Range objects.
