### ISSUE TITLE
Test Map.entrySet()....setValue(...)

### ISSUE THREAD

**Issue by cpovirk** [google/guava#2406]
As far as I can tell, our suites don't exercise this. I noticed because a non-Guava user of our collection testers fails the forthcoming Java 8 `replaceAll()` tests, and that's precisely because it doesn't support `setValue()`.

**Comment by ben-manes** [comment]
@cdibona When do you expect the Java 8 version of the testlib to be available? Any possibility of providing snapshots so that I can experiment with it?

**Comment by cpovirk** [comment]
@lowasser might know our plans for the Java 8 branch generally and testlib specifically.

**Comment by lowasser** [comment]
We haven't focused much on getting our Java 8 branch set up to work with open source correctly -- I'm not certain what issues would be involved in getting MOE to work correctly there -- but we might be able to dump something over the wall in the short term.
