### ISSUE TITLE
EnumMaps#forAllKeys

### ISSUE THREAD

**Issue by lpandzic** [google/guava#2407]
One common issue when dealing with enums and enummaps (and switches with enums for that matter) is that with introduction of new enum values adding new entries into enummaps (or switches) for them can be easily forgotten.
Static factory methods (or a builder) could be used to fail fast when such a situation arises.
For example:
EnumMaps.forAllKeys(K1, V1, K2, V2)
Internally, when the construction of immutable enummap is done, validation is executed so that all possible enum keys are present and not null. Additionally, by enforcing that all enums are not null any of them could be used to get enum class (getDeclaringClass) which would bring an additional benefit to callers who wouldn't need to specify the enum type explicitly.

What do you think?

**Comment by cpovirk** [comment]
In fact, I think some people were just talking about this today.

It also came up in #91, but we closed that once we added `immutableEnumMap`, and AFAICT no one ever opened a new issue about exhaustiveness checking. So I guess this issue takes care of that :)

It's something that we should probably do someday.

**Comment by lpandzic** [comment]
Well, I'm willing to implement it and contribute but would first like to discuss API specifics.
Where should it be located and how should those static factory methods be named?
Should non null be enforced for both keys and values or only for keys, etc. :)

**Comment by cpovirk** [comment]
Yeah, designing the API is the tricky part :) That design probably won't be a priority in the near future, but maybe someone else on the team will surprise me and pick it up.

**Comment by lpandzic** [comment]
Ok, when you get some free time on your hands, please take a look at the pull request, I've also opened a topic on guava google group. GWT tests seem to fail and last time I used GWT was about 3 years ago so any help would be appreciated :).

**Comment by lowasser** [comment]
For what it's worth, here's what I had in mind:

- don't make ImmutableEnumMap public; it's more an implementation difference than a semantic difference
- expose it through the builder: something like
      ImmutableMap.enumBuilder(MyEnum.class)
   with possibly an "exhaustive" modifier, maybe ImmutableMap.exhaustiveEnumBuilder or ImmutableMap.enumBuilder().exhaustive().
- note that those have different ordering behavior from normal ImmutableMaps (insertion order); is that a doc thing, or actually worth splitting off a different API?  (Technically, it's consistent with ImmutableSortedMap...)

**Comment by lpandzic** [comment]
I think a builder is not enough and static factory methods should also be provided. I think putting both static factory methods and a builder in ImmutableMap and encoding enum in their name is a bad design choice. How many more use cases before ImmutableMap becomes too overloaded with ImmutableEnumMap stuff? I would also like to explicitly use ImmutableEnumMap type in my code or at least EnumMap since EnumMap is usually used different (at least from what I've seen) than a regular map.

**Comment by lowasser** [comment]
I'm not sure I follow.

ImmutableMap is supposed to correspond to the Map interface; ImmutableSortedMap is supposed to correspond to the SortedMap interface.  EnumMap is just another implementation of Map, just as HashMap is; it just happens to be more efficient for its specific use case.

**Comment by lpandzic** [comment]
> ImmutableMap is supposed to correspond to the Map interface; ImmutableSortedMap is supposed to correspond to the SortedMap interface. EnumMap is just another implementation of Map, just as HashMap is; it just happens to be more efficient for its specific use case.

Isn't ImmutableMap just another implementation of Map? Why is ImmutableMap public and why isn't everything in Maps? Why does Java API include a public EnumMap class and no explicit class similar to ImmutableMap?

Key difference between a regular Map and an EnumMap is that key is always an enum meaning there is a finite number of possible keys, always, for every possible EnumMap instance. Usually EnumMap is an alternative to a switch statement. But there is more than [that](https://docs.oracle.com/javase/7/docs/api/java/util/EnumMap.html):
> Enum maps are maintained in the natural order of their keys.
> Null keys are not permitted.

Similar to that, ImmutableMap never allows modifying operations, is naturally thread safe if you don't modify keys/values etc.

Both the ImmutableMap and ImmutableEnumMap diverge from the Map contract more than enough that you would want an explicit type for both of them. So to sum it up, a reader will want to know that this is an EnumMap same as he wants to know it is an ImmutableMap. You don't want to check what is behind that Map definition same as you don't want to check what is the key type.

**Comment by lowasser** [comment]
Of course ImmutableMap diverges from Map, and EnumMap diverges from Map in some ways, but the only way I see that ImmutableEnumMap would diverge from ImmutableMap is the iteration order?

**Comment by lpandzic** [comment]
> Of course ImmutableMap diverges from Map, and EnumMap diverges from Map in some ways, but the only way I see that ImmutableEnumMap would diverge from ImmutableMap is the iteration order?

I have already answered that:

> Key difference between a regular Map and an EnumMap is that key is always an enum meaning there is a finite number of possible keys, always, for every possible EnumMap instance.

Second thing:
> but the only way I see that ImmutableEnumMap would diverge from ImmutableMap is the iteration order?

Same logic can be applied to ImmutableMap and Map, also like I've said in my previous response.

One more thing you didn't address:

> I think a builder is not enough and static factory methods should also be provided. I think putting both static factory methods and a builder in ImmutableMap and encoding enum in their name is a bad design choice. How many more use cases before ImmutableMap becomes too overloaded with ImmutableEnumMap stuff?

**Comment by oliviercailloux** [comment]
It would be very valuable to have a _type_, say, `CompleteEnumMap`, that guarantees that the enum map is “complete” (in supplement of being immutable), in the following sense: the key set of the map equals the set of possible enum values.

I could then design a method that returns `CompleteEnumMap` and the user of my class would know immediately that she can query whatever key from the corresponding enum and be guaranteed a result. And this information would stick around and be kept when this result is used somewhere else where the contract of the class that produced it is out of sight.

This is a supplementary and important guarantee that should appear in the contract of the returned class, therefore deserving a special type.

**Comment by lowasser** [comment]
What is inadequate about `Function<Enum, Value>` for that API?

**Comment by oliviercailloux** [comment]
I’ve thought a bit more about this in the meantime and think that the name `ImmutableCompleteMap` would fit better for the concept I proposed (previously named `CompleteEnumMap`).

An `ImmutableCompleteMap` provides more service than a `Function`: it also permits to deal with the function’s co-domain, through the methods `containsValue` and `values()`. Also, `keySet()` is useful, even though it only depends on `K`, because someone may not have `K` underhand. 

The set of implicit, natural assumptions when receiving a map differ from those when receiving a function. A function conveys the idea that it will compute its results on the fly, perhaps expensively, when called; whereas a map conveys the idea that it is O(log n) to get the value corresponding to a key. I fully admit that it is not explicit in the contract, and therefore one should check when it matters much, but still, this is a really reasonable and natural assumption, and if it is untrue, then it’d be nice from the provider of the map to explicitly warn the user about its special performance.

An `ImmutableCompleteMap` is type-substitutable with a `Map` and naturally extends it, so the user would naturally expect to receive an `ImmutableCompleteMap` in cases that feel like particular cases of natural cases one would receive a `Map`. It is very natural, given some enum values as keys and pre-computing some results, to put this in a `Map` and return it to the user; therefore, in the special case where we know that all possible enum values are used as key, it feels strange to suddently switch to a `Function`.

A `Map` has, per contract, a useful concept of equality, contrary to a `Function`.

Finally, the contract of the `ImmutableCompleteMap` type would guarantee immutability (and thus, thread-safety, etc.). A `Function` does not.

**Comment by oliviercailloux** [comment]
Please see [this draft interface](https://github.com/oliviercailloux/JARiS/blob/draft-immutable-complete-map/src/main/java/io/github/oliviercailloux/jaris/collections/ImmutableCompleteMap.java) that illustrates what I have in mind.

**Comment by cpovirk** [comment]
Now that Java offers switch expressions, including compile-time exhaustiveness checking, it's clearer that, whatever might have been the right course of action 8 years ago, we're not going to add an API now that it would compete with that. (Switch expressions don't help much if you actually need a `Map`, of course. Still, switch expressions eat enough into the use cases for `EnumMaps.forAllKeys` that we're not going to get any better at prioritizing this.)
