### ISSUE TITLE
Remove @Beta from com.google.common.base.Verify

### ISSUE THREAD

**Issue by jpangamarca** [google/guava#2409]
At work we use a lot the Verify utility class to make postconditions checks, it's a simple and effective way to do such checks. Nevertheless, it's marked with the Beta annotation. I read about Beta APIs https://github.com/google/guava/wiki/PhilosophyExplained#beta-apis and would like to ask for Beta removal from Verify, taking into account that the usage of Verify in our codebase has grown. Would it be possible? Thanks for your attention.

**Comment by kevinb9n** [comment]
Thanks for poking us on that -- I'm going to review what things are overdue
to be out of beta.

On Thu, Mar 3, 2016 at 9:28 AM, jpangamarca <notifications@github.com>
wrote:

> At work we use a lot the Verify utility class to make postconditions
> checks, it's a simple and effective way to do such checks. Nevertheless,
> it's marked with the Beta annotation. I read about Beta APIs
> https://github.com/google/guava/wiki/PhilosophyExplained#beta-apis and
> would like to ask for @Beta <https://github.com/Beta> removal from
> Verify, taking into account that the usage of Verify in our codebase has
> grown. Would it be possible? Thanks for your attention.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/guava/issues/2409>.
>



-- 
Kevin Bourrillion | Java Librarian | Google, Inc. | kevinb@google.com

**Comment by jpangamarca** [comment]
Thanks for your kind response, have a nice day!

**Comment by andreas-schilling** [comment]
Can't this be closed now as well?

**Comment by kluever** [comment]
`Verify` is still labeled `@Beta`

**Comment by kevinb9n** [comment]
Sorry that this didn't make the cut for de-betaing last year. Trying it again.
