### ISSUE TITLE
Wrong url for AutoValue on the IdeaGraveyard wiki page

### ISSUE THREAD

**Issue by enitihas** [google/guava#2415]
In the last line under the heading : **Tuples for n>=2**, there is a link to AutoValue, which points to : 
https://docs.google.com/document/d/1THRUCIzIPRqFSHb67pHV8KMbo55HphSXqlQcIx9oUiI/edit#heading=h.7ojt6jg2vdwc

which leads the user to a google doc asking to update whatever url lead them there to https://github.com/google/auto/tree/master/value

**Comment by kluever** [comment]
Thanks!
