### ISSUE TITLE
Map tests assert on .toString even when CollectionFeature.NON_STANDARD_TOSTRING is specified

### ISSUE THREAD

**Issue by cdman** [google/guava#2418]
See a unit test demonstrating the issue here: https://github.com/gpanther/fastutil-guava-tests/blob/master/src/test/java/net/greypanther/guava/tests/tests/CustomToStringTest.java

It shows a HashMap subclass which overrides toString and as a result fails tests, even if CollectionFeature.NON_STANDARD_TOSTRING passed to MapTestSuiteBuilder.

I believe that methods like https://github.com/google/guava/blob/2cd4d629a2b6f1a462643b248e0972f44c5133b7/guava-testlib/src/com/google/common/collect/testing/testers/MapToStringTester.java#L45 should be marked with `@CollectionFeature.Require(absent = NON_STANDARD_TOSTRING)`.

**Comment by cpovirk** [comment]
Agreed. Thanks for the report. I will take care of this.

I briefly wondered if maybe we should have a separate `MapFeature.NON_STANDARD_TOSTRING`. But if anything, we should probably try to eliminate the cases in which we duplicate a property between `MapFeature` and `CollectionFeature` (internal bug 6238930).
