### ISSUE TITLE
Equivalent CharMatchers, even though built differently, are not .equals()

### ISSUE THREAD

**Issue by fge** [google/guava#2421]
This is version 19.0

This:

```java
    public static void main(final String... args)
    {
        final CharMatcher m1 = CharMatcher.is('a');
        final CharMatcher m2 = CharMatcher.isNot('a').negate();

        System.out.println(m1.equals(m2));
        System.out.println(m1);
        System.out.println(m2);
    }
```

prints:

```
false
CharMatcher.is('\u0061')
CharMatcher.is('\u0061')
```

Aiie...

**Comment by kluever** [comment]
`CharMatcher` doesn't implement `equals` (or `hashCode`), so the only way 2 instances will be equal is if they are the same constants.

Is there a reason you need or want `CharMatcher` to define equality? It would be nearly impossible to normalize CharMatcher instances. For example, should these instances be `equal`?

```
CharMatcher.is('a')
CharMatcher.inRange('a', 'b').and(CharMatcher.isNot('b'))
```

**Comment by fge** [comment]
@kluever pretty much so, yes; the logic is there anyway so that those two matchers are _functionally_ equivalent.

Since the logic is there to do that, what prevents equality to be computed accurately?

**Comment by kluever** [comment]
There is no logic to collapse or normalize CharMatchers other than simple cases like negation.

The two functionally equivalent CharMatchers from my example above will have very different `toString()` representations:

```
CharMatcher.is('\u0061')
CharMatcher.and(CharMatcher.inRange('\u0061', '\u0062'), CharMatcher.isNot('\u0062'))
```

**Comment by fge** [comment]
OK, well, you can close this issue, I guess. I'd have expected however that such a collapse would have been made...

Nevermind, I'll use something else, then.

**Comment by kluever** [comment]
@fge Like I said, it would be nearly impossible for us to normalize complex chains of `CharMatchers`.

You still never explained why you want functionally equivalent CharMatchers to be equal. What is your use case?

**Comment by eamonnmcmanus** [comment]
We already normalize `CharMatcher`s in the `precomputed()` method. So we _could_ say that `equals` works as expected on the result of `precomputed()`, or (since `precomputed()` can be expensive) we could provide an `expensiveEquals(CharMatcher)` method. I agree that the use case has yet to be established, though.

**Comment by fge** [comment]
@kluever this is for [grappa](https://github.com/fge/grappa). In this package, there is a cache mechanism for `Matcher`s (note: those are not `java.util.regex.Matcher`s) taking arguments.

My goal was to replace the custom Java `char` matchers in here (which rely right now on `Characters` instances) with `CharMatcher`s. Should the latter have implemented `.equals()` (and consequently `.hashCode()`), the swap would have been easy.

So, I guess I'll have to improve `Characters` here, because it's not ideal... I'd have somewhat expected `CharMatcher` to fit the bill however.

@eamonnmcmanus well, I don't care about "initial" precomputation. Actually I haven't tested with `.precomputed()` instances... But even that additional `.expensiveEquals()` wouldn't fit the bill.

In detail, how the key of the rules to be cached is by using a stupid, simple wrapper class which just calls back to `Arrays.deep{equals,hashCode}()`, which means it is expected that the individual parameters implement `.equals()` and `.hashCode()` as expected by the user.

But again, this is a specific use case. I was just surprised that `CharMatcher` would not do this from the get go, that's all :)
