### ISSUE TITLE
Wiki title going too far in CollectionUtilitiesExplained

### ISSUE THREAD

**Issue by Dominator008** [google/guava#2425]
https://github.com/google/guava/wiki/CollectionUtilitiesExplained#listsin-addition-to-static-constructor-methods-and-functional-programming-methods-lists-provides-a-number-of-valuable-utility-methods-on-list-objects seems too long for a title :)

**Comment by cpovirk** [comment]
:)

Fixed, thanks: https://github.com/google/guava/wiki/CollectionUtilitiesExplained#lists

**Comment by cgdecker** [comment]
This reminds me that I should sync out the changes I made to these files when bringing them into our internal repository... I cleaned up the markdown when doing that, which should have fixed issues like this. Unfortunately I changed the filenames and changed wiki links to normal markdown links which means it's not just a matter of copying the files back out. So I'll probably just wait until I'm ready to move this content to the Github Pages site.
