### ISSUE TITLE
Add a constant for X-Forwarded-Host and X-Forwarded-Port to HttpHeaders

### ISSUE THREAD

**Issue by MiErnst** [google/guava#2430]
As they are [common headers](https://en.wikipedia.org/wiki/List_of_HTTP_header_fields#Common_non-standard_request_fields) (at least the `X-Forwarded-Host`) it would be nice if they are defined in the class `HttpHeaders`. The `X-Forwared-Port` is used for example in [AWS](http://docs.aws.amazon.com/ElasticLoadBalancing/latest/DeveloperGuide/x-forwarded-headers.html).

**Comment by kluever** [comment]
These are non-standard headers, but if they are very "common", then I think we should include them. We'll need to dig up some good reference links for the javadocs.

For `X-Forwarded-Port`, I found http://httpd.apache.org/docs/2.2/mod/mod_proxy.html#x-headers
For `X-Forwarded-Host`, I found https://en.wikipedia.org/wiki/X-Forwarded-For

Do you know of any better (more official) links we could use? (BTW, your AWS link doesn't go anywhere - did you have a good reference for that?)

**Comment by MiErnst** [comment]
Hi, thanks for the quick reply. I'm sorry that I could not provide any reference to a RFC or something like this. I have seen both parameters only in a few nginx and httpd configs. As I want to evaluate them in my code I thought I could use the class `HttpHeaders` but then I missed them.

I updated the AWS link. I also like the definition they use there.

**Comment by kluever** [comment]
Thanks - this should be mirrored out shortly.
