### ISSUE TITLE
urlPathSegmentEscaper().escape() should escape '@'

### ISSUE THREAD

**Issue by mavjop** [google/guava#2434]
The Escaper returned by com.google.common.net.UrlEscapers.urlPathSegmentEscaper() should escape '@'.

Per http://tools.ietf.org/html/rfc3986#section-2.2 -

"""
   If data for a URI component would conflict with a reserved
   character's purpose as a delimiter, then the conflicting data must be
   percent-encoded before the URI is formed.

      reserved    = gen-delims / sub-delims

      gen-delims  = ":" / "/" / "?" / "#" / "[" / "]" / "@"

      sub-delims  = "!" / "$" / "&" / "'" / "(" / ")"
                  / "*" / "+" / "," / ";" / "="
"""

'@' is a reserved delimiter (used for separating username[:password] from host name/address).

If urlPathSegmentEscaper() were to percent-encode '@', I think it would be an acceptable Escaper for escaping the host address part of a URL.

While it is less likely to cause a parsing problem in a path segment than in the host part it is strictly speaking incorrect for it not to be percent-encoded.

- Stephen

**Comment by cpovirk** [comment]
The spec is not super clear here.

"If data for a URI component would conflict with a reserved character's purpose as a delimiter" means more than "If the character is ever a delimiter." There has to be potential for a conflict -- as in your hostname example.

Path segments can contain `@`:

- https://url.spec.whatwg.org/#syntax-url-path-segment
- https://url.spec.whatwg.org/#url-units
- https://url.spec.whatwg.org/#url-code-points

The old RFC 3986 (which I should stop linking to in the Javadoc -- will fix) agrees here:

```
      segment-nz-nc = 1*( unreserved / pct-encoded / sub-delims / "@" )
```
