### ISSUE TITLE
Sensitive<T>, for values that shouldn't be logged

### ISSUE THREAD

**Issue by tomfitzhenry** [google/guava#2435]
Occasionally I deal with values that I don't want logged (e.g. passphrases, user personal details). I tend to use [Sensitive<T>](https://gist.github.com/tomfitzhenry/ceacc3dad4f693ad22da) for this. Key features are that toString doesn't output the underlying T, and that the getter is called something scaryish like `retrieveSensitiveValue` rather than `get`.

It'd be neat if this was Guava-ified.

Perhaps this is a problem better tackled by an Information Flow library, however.

**Comment by lowasser** [comment]
I'd tend to expect this sort of problem to be best solved with Java 8 type annotations, and passing a variable around as a `@Sensitive String` rather than a `Sensitive<String>`?

**Comment by tomfitzhenry** [comment]
I hadn't seen that.

http://types.cs.washington.edu/checker-framework/current/checker-framework-manual.html#tainting-checker
looks
like it might be what I'm after. Thanks!
