### ISSUE TITLE
Proposal: Make `Ticker` an interface

### ISSUE THREAD

**Issue by JensRantil** [google/guava#2438]
I am writing a unit test and want to mock time. I am using the `Sleeper` `interface` and the `Ticker` abstract class. Something like this:

    private static class FakeTime extends Ticker implements Sleeper {

        private static final long READ_DURATION_DELTA_NANOS = TimeUnit.MILLISECONDS.toNanos(50);

        private long total = 0;
        private long now;

        public FakeTime() {
            this.now = System.nanoTime();
        }

        @Override
        public void sleep(long millis) throws InterruptedException {
            this.total += millis;
            this.now += TimeUnit.MILLISECONDS.toNanos(millis);
        }

        public long getTotal() {
            return total;
        }

        @Override
        public long read() {
            long result = now;
            now += READ_DURATION_DELTA_NANOS;
            return now;
        }

    }

Problems:
 * If I need to extend another class, I would need some weird construct since multiple inheritance isn't possible in Java.
 * `Ticker` feels more like an `interface` than an `abstract class`.

Proposal: Make `Ticker` an `interface`.

Thoughts?

**Comment by ben-manes** [comment]
Guava's testlib contains `FakeTicker` which is a handy utility similar to yours. Due to the static method a change to an interface wouldn't be possible until the Java 8 release. It might still be frowned upon as a breaking change.

**Comment by kluever** [comment]
Also FWIW, Ticker used to be an interface and I intentionally changed it to an abstract class back in 2011.

It looks like your FakeTime class is trying to do too much. You could keep a ticker internally, and then expose it via a `ticker()` method on your class.
