### ISSUE TITLE
Provide a Converter<TimeUnit, ChronoUnit>

### ISSUE THREAD

**Issue by kluever** [google/guava#2443]
> currently there's no official way (in JDK 8) for converting between `java.util.concurrent.TimeUnit` and `ChronoUnit` (there will be in [JDK 9](https://bugs.openjdk.java.net/browse/JDK-8141452), though).

So we should consider providing one. Maybe it's time to start selectively open sourcing our `com.google.common.time` package?

**Comment by vharuty** [comment]
@kluever hi, please let me know what is the status for this issue, I would like to contribute.

**Comment by kluever** [comment]
There won't be any progress on this until we've completed the Guava for JDK8 transition.

**Comment by SimenB** [comment]
@kluever Is there a way to track that transition? Just the [label](https://github.com/google/guava/labels/platform%3A%20java8)?

**Comment by kluever** [comment]
We just made the transition to Java 8 internally last week, and we plan on releasing a Guava 21 (with Java8 support) sometime next quarter.

**Comment by SimenB** [comment]
Cool! Looking forward to it 😄

**Comment by Xaerxess** [comment]
Is it implemented internally? I'd really like to use the conversion with Guava 21.

**Comment by kluever** [comment]
I have a pending CL with this...I'll try to prioritize getting it API reviewed and released. Thanks for the bump.

**Comment by Xaerxess** [comment]
...or maybe in Guava 22? ;)

**Comment by kluever** [comment]
The reason we've been on the fence about adding this is that it already exists in [`threeten-extra`](www.threeten.org/threeten-extra/) as:

* [`Temporals.chronoUnit(TimeUnit)`](http://www.threeten.org/threeten-extra/apidocs/org/threeten/extra/Temporals.html#chronoUnit-java.util.concurrent.TimeUnit-)
* [`Temporals.timeUnit(ChronoUnit)`](http://www.threeten.org/threeten-extra/apidocs/org/threeten/extra/Temporals.html#timeUnit-java.time.temporal.ChronoUnit-)

And we're hesitant to add competing solutions when a reasonable solution already exists.

**Comment by kevinb9n** [comment]
We've decided not to compete with threeten-extra.

**Comment by jbduncan** [comment]
@kevinb9n I think this would be good to note in the Ideas Graveyard, so that people are less likely to ask for this feature again in the future
