### ISSUE TITLE
TreeMultimap put method replaces existing value if key exists.

### ISSUE THREAD

**Issue by OliverColeman** [google/guava#2444]
I was surprised to discover that the `put(K key, V value)` method of `TreeMultimap` will replace the existing value if the given key already exists. This defeats the purpose of a Multimap. (Yes the Java docs describe this behaviour, but that does not mean the behaviour is sensible or expected.)

I suppose there now exists code using TreeMultimap that expects this behaviour, so the put method likely should not be changed. I argue that a new method be introduced that allows adding new values for the same key. Perhaps `add(K key, V value)`.

**Comment by lowasser** [comment]
That seems odd -- can you post reproduction instructions?

From a glance, TreeMultimap is just delegating to TreeSet.add, so I'd expect `TreeMultimap` to just be getting whatever `TreeSet`'s behavior is.

**Comment by OliverColeman** [comment]
I cannot post reproduction instructions, mostly because when I tried to I discovered TreeMultimap.put behaves exactly as expected! Turned out the values I was adding had a custom implementation of Comparable for which compareTo returned 0 for the different objects I was adding. Oops. Sorry for wasting your time!
