### ISSUE TITLE
add covariant return type to ImmutableSortedMap

### ISSUE THREAD

**Issue by Groostav** [google/guava#2445]
This is something very minor, but it will let me sleep easy;

I'm writing some extensions to [RichTextFX](https://github.com/TomasMikula/RichTextFX) using [ANTLR](https://github.com/antlr/antlr4), which means indexes galore, and it would make my life easier if I could get the `ImmutableSortedMap` to commit to a `List` return type, by covariantly overloading `ImmutableSortedMap.values()` to return an `ImmutableList` instead of an `ImmutableCollection`. 

```diff
   @Override
-  public ImmutableCollection<V> values() {
+  public ImmutableList<V> values(){
     return valueList;
   }
```

Any thoughts?

Specifically I'm building a `RangeMap<Integer, antlr.runtime.Token>` which represents text ranges as keys to the tokens as values. The tokens themselves know their text indices but its annoying to sort through them to find the token you want, much easier to keep a RangeMap of them.

**Comment by lowasser** [comment]
I'm not sure we'd want to commit to the current implementation.  Can you use values().asList() or ImmutableList.copyOf(values()), either of which would return what you want in O(1)?

**Comment by Groostav** [comment]
ah but this is no good,

`ImmutableRangeMap` is transformed into a `Map<Range, Value>` by `asMapOfRanges()`, which does a check to special-case an empty map, using an empty `ImmutableBiMap` instead.

**Comment by Groostav** [comment]
>I'm not sure we'd want to commit to the current implementation. Can you use values().asList() or ImmutableList.copyOf(values()), either of which would return what you want in O(1)?

I can, and thats what I'll do.

You'd need an exceptionally large text file for linear time on the number of tokens to be a problem.
