### ISSUE TITLE
Upgrade to guava r19 broke my build: javax.annotation.CheckReturnValue not found

### ISSUE THREAD

**Issue by patric-r** [google/guava#2450]
I'm facing an interesting problem:
After upgrading guava from r18 to r19, I cannot compile my project anymore, at least not with oracle javac (JDK 8u60 on linux): 

[javac verbose logging enabled]

```
[javac] [loading ZipFileIndexFileObject[/myproduct/lib/common/log4j/apache-log4j-2.5-bin/log4j-core-2.5.jar(org/apache/logging/log4j/core/config/plugins/PluginVisitorStrategy.class)]]
[javac] error: cannot access CheckReturnValue
[javac]   class file for javax.annotation.CheckReturnValue not found
[javac] Note: Some input files use or override a deprecated API.
[javac] Note: Recompile with -Xlint:deprecation for details.
[javac] 1 error
```

Switching back to guava r18 will make the build successful again.

I don't know exactly yet why this happens but I realized that compared to r18, with r19 now more class files contain references to `javax.annotation.CheckReturnValue`
Interestingly, the last logging statement before the error is related to a log4j2 class although I can not see how the class and the compile error are related.

**Comment by cpovirk** [comment]
I wonder if this is something that can be worked around by adding the dep that includes `CheckReturnValue`:

      <dependency>
        <groupId>com.google.code.findbugs</groupId>
        <artifactId>jsr305</artifactId>
        <version>1.3.9</version>
      </dependency>

Guava's dependency on `jsr305` is marked `optional`, so it makes sense that the `.class` file would be missing. The weird part is that `javac` cares. My understanding is that `javac` shouldn't error out for mere missing annotations. But I can't find this specified anywhere, and I even found a [bug report](https://bugs.openjdk.java.net/browse/JDK-6331821) that suggests more or less the opposite.

My first suspicion would be that an annotation processor or other compiler plugin is causing the problem -- [e.g., Lombok](https://github.com/rzwitserloot/lombok/issues/425). Do you know if you're using any?

**Comment by patric-r** [comment]
I'm not using any sort of compiler plugins / processors.
It's plain javac (invoked from ant).

Interesting fact: Eclipse compiles the same project without any errors.

**Comment by cpovirk** [comment]
Should be fixed now that we have "real" deps on jsr305.

See, e.g,. https://github.com/google/guava/issues/2721#issuecomment-340440883
