### ISSUE TITLE
Remove StandardSystemProperty from Guava's Beta

### ISSUE THREAD

**Issue by jpangamarca** [google/guava#2451]
I would like to ask for removal of com.google.common.base.StandardSystemProperty from Guava's Beta, as it's a really convenient way to reference system properties, and keeps devs from using hardcoded values or mantaining our own sets of constants. Could it be possible? Thanks for your attention.

**Comment by kevinb9n** [comment]
Thanks - as it happens, I do have this on the list, and I think chances are good.

**Comment by jpangamarca** [comment]
Glad to hear that, thanks a lot for your response.

**Comment by cpovirk** [comment]
Done later that year.
