### ISSUE TITLE
Feature Addition / Extending Functionality : Fast Data Shifting .

### ISSUE THREAD

**Issue by Anonymousingly** [google/guava#2453]
I was wondering if an algorithm mentioned at http://github.com/Anonymousingly/URA can be included in Google-Guava .
I contribute to this algorithm and it's implementations . It is faster than Array , OBST , BST etc. in the cases when a data is to be inserted at a pre-occupied position , SHIFTING is needed instead of replacement.
Kindly see README at above link for complete description .
When used on AVL_TREE , it provides O(log n) time complexity for insert , delete ,retrieve .It can be modified / enhanced for performing operations via data also(along with index).
**Faster than Array by 48 minutes for 10^6 elements on an i3 processor .**

**Comment by cpovirk** [comment]
Realistically, we are unlikely to add new general-purpose collection implementations to Guava. Sorry for taking so long to even acknowledge this post.
