### ISSUE TITLE
Exception handling is not very elegant

### ISSUE THREAD

**Issue by 0opslab** [google/guava#2454]
public class ExceptionTest {
    @Test
    public void testExceptionToString(){
        try{
           throw new RuntimeException("RuntimeException-test");
        }catch (Exception e){
            String ss = Throwables.getStackTraceAsString(e);
            System.out.println("exception:"+ss);
        }
    }

```
@Test
public void testExceptionCausalChain(){
    try{
        throw new RuntimeException("RuntimeException-test");
    }catch (Exception e){
        List<Throwable> chain = Throwables.getCausalChain(e);
        for(Throwable t :chain) {
            System.out.println("exception:" + String.valueOf(t));
        }
        e.printStackTrace();
    }
}
```
## }

I just want to focus on special package callstack!

**Comment by cpovirk** [comment]
Can you clarify what you're requesting?

**Comment by 0opslab** [comment]
I just want to get the call chains under the specific package 
as
```java
    String ss = Throwables.getStackTraceAsString(e,specialPackageName);
```

**Comment by javaProgrammer44** [comment]
Can you please elaborate it ? what exactly you are asking about ?
Sorry but could not get clear picture of your request .
