### ISSUE TITLE
Don't null-pad groups in Iterables.partition()

### ISSUE THREAD

**Issue by mcandre** [google/guava#2459]
My use case for `Iterables.partition()` is to construct precisely sized batches, not batches with dangerous null values in some of them.

Could partition offer a parameter to disable null padding, or better yet, offer a different method that doesn't pad at all?

**Comment by lowasser** [comment]
My understanding from glancing at the Javadocs is that Iterables.partition already does what you want, and that it is only Iterables.paddedPartition that does the padding.  Are you certain this is actually a problem for you?

**Comment by mcandre** [comment]
@lowasser Thanks for clearing this up. I'll make a note to my team.
