### ISSUE TITLE
Feature Request: BiMap with support for weak/soft references

### ISSUE THREAD

**Issue by mrswadge** [google/guava#2462]
Hi Guava Developers,

I've been using a BiMap previously, but I discovered that the items I'm placing into this BiMap is responsible for a memory leak in my application. Cleaning up the map is likely to be tricky and having the bi-directional mapping has been a great help to my project, so ideally I'd like to keep this. I've scoured the API documentation and I couldn't see a BiMap with support for weak/soft references. I wondered if the concept would be something Guava would consider for inclusion into the API. Is it possible?

The original code I used was using HashBiMap.create(), obviously this meant using hard references for the values.

```
private HashBiMap<K, V> uiComponents = HashBiMap.create();
```

I've tried to solve my issue with a Map<K, V> implementation that internally maintains two HashMaps created via MapMaker, but I'm sure there will be pitfalls. I additionally added an inverse() method to get an unmodifiable map for the inverse. I have included my basic implementation as an example of what I am trying to achieve. It's not been tested at the current time, so there are likely to be issues with it. 

It would be nice to have something out-of-the-box.

Thanks,
Stuart

```
class WeakValueBiDirectionMap<K, V> implements Map<K, V> {
        private final Map<K, V> forward = new MapMaker().weakValues().makeMap();
        private final Map<V, K> inverse = new MapMaker().weakKeys().makeMap();

        public synchronized Set<K> keySet() {
            return forward.keySet();
        }

        @Override
        public synchronized Set<java.util.Map.Entry<K, V>> entrySet() {
            return forward.entrySet();
        }

        @Override
        public synchronized Collection<V> values() {
            return forward.values();
        }

        @Override
        public synchronized int size() {
            return forward.size();
        }

        @Override
        public synchronized boolean isEmpty() {
            return forward.isEmpty();
        }

        @Override
        public synchronized boolean containsKey( Object key ) {
            return forward.containsKey( key );
        }

        @Override
        public synchronized boolean containsValue( Object value ) {
            return forward.containsValue( value );
        }

        @Override
        public synchronized V get( Object key ) {
            return forward.get( key );
        }

        @Override
        public synchronized V put( K key, V value ) {
            V v = forward.put( key, value );
            inverse.put( value, key );
            return v;
        }

        @Override
        public synchronized V remove( Object key ) {
            V v = forward.remove( key );
            if ( v != null ) {
                inverse.remove( v );
            }
            return v;
        }

        @Override
        public synchronized void putAll( Map<? extends K, ? extends V> m ) {
            Set<Entry<K, V>> entrySet =  ( (Set<Entry<K, V>>)( (Set) m.entrySet() ) );
            for ( Entry<K, V> entry : entrySet ) {
                forward.put( entry.getKey(), entry.getValue() );
                inverse.put( entry.getValue(), entry.getKey() );
            }
        }

        @Override
        public synchronized void clear() {
            forward.clear();
            inverse.clear();
        }

        public synchronized Map<V, K> inverse() {
            return Collections.unmodifiableMap( inverse );
        }
    }
```

**Comment by Adrodoc55** [comment]
I need this too!

**Comment by cpovirk** [comment]
We have tried to get out of the business of supplying collections that use weak/soft references, leaving that to caching libraries (like Caffeine). A `BiMap`-like cache would require maintaining a cache in each direction, of course. It's a pain, but it has the benefit of being possible today :(
