### ISSUE TITLE
event filtering beyond Java Type based filter

### ISSUE THREAD

**Issue by mingzhou** [google/guava#2464]
Hi, all,
Can event bus dispatch events beyond Java Type based filter?
For example, I have the following scenario. QuoteEventListener only want to listen events filtering by ticker instead of just java type QuoteEvent.class. 

```
// stock quote event
public class QuoteEvent {
    private final String ticker;
    private final double price;
    public QuoteEvent(String ticker_, double price_) {
        ticker = ticker_;
        price = price_;
    }
    public String getTicker() {
        return ticker;
    }
    public double getPrice() {
        return price;
    }
}

QuoteEventListener listener1 = new QuoteEventListener("MSFT");
QuoteEventListener listener2 = new QuoteEventListener("GOOG");


EventBus eventBus = new EventBus("feeder");
eventBus.post(new QuoteEvent("MSFT", 12.34)); // only listener1 will be notified
eventBus.post(new QuoteEvent("GOOG", 12.34)); // only listener2 will be notified

```

**Comment by lowasser** [comment]
Is there a reason you couldn't do this filtering in the listener itself?

**Comment by mingzhou** [comment]
@lowasser Yes, I can filtering this in listener. But I think it would be better that listeners should never touch events that they have not subscribed. What kind of event should they touch have been decided by EventBus. Which events of this kind should they touch? I think it's better that EventBus handles too.

**Comment by ShiroYacha** [comment]
@mingzhou I strongly agree... There should be an option to register some kind of ID or allow content-based filtering at the registration stage...

**Comment by mingzhou** [comment]
@lowasser @ShiroYacha Yeah, may be something like `@Subscribe(filter=EventPredicate.class)` while `EventPredicate implements java.functional.Predicate`...

**Comment by cpovirk** [comment]
Realistically, we're unlikely to add functionality to EventBus at this point.
