### ISSUE TITLE
Add methods to close several objects safely

### ISSUE THREAD

**Issue by simonmcooper** [google/guava#2465]
Often, when you're writing a close method, you do this:

    @Override
    public void close() throws IOException {
        field1.close();
        field2.close();
    }

But there's a leak here - if the first `field1.close()` throws an exception, field2 will not be closed. If the IOException is handled and the program continues running, then field2 will never be closed and will leak.

I propose adding a series of methods that will close several objects safely, in a similar way to try-with-resources, with the proposed outline:

    public static void closeAll(Closeable... closeables) throws IOException {
        Exception ex = null;
        for (Closeable c : closeables) {
            try {
                closeables.close();
            }
            catch (Exception e) {
                if (ex == null)
                    ex = e;
                else
                    ex.addSuppressed(e);
            }
        }

        if (ex != null) {
            Throwables.propagateIfPossible(ex, IOException.class);
            throw Throwables.propagate(ex);
        }
    }

With similar variants for `AutoCloseable`, `Iterator<? extends Closeable>`, etc... that could be used like so:

    @Override
    public void close() throws IOException {
        Closeables.closeAll(field1, field2);
    }

**Comment by JakeWharton** [comment]
http://docs.guava-libraries.googlecode.com/git/javadoc/com/google/common/io/Closer.html

**Comment by lowasser** [comment]
Closer is definitely the thing to use here.  Also note that if you have AutoCloseable, you have try-with-resources, which works better and more cleanly than anything Guava could do.

**Comment by simonmcooper** [comment]
Hmm, so the Closer could be used for Closeable:

    public void close() throws IOException {
        Closer.create().register(f1).register(f2).close();
    }

However, this only works for `Closeable`, there's no class that deals with `AutoCloseable` (throwing `Exception`). And it's a lot of boilerplate for taking a series of fields and closing them safely - could static members be added to Closer that just take the fields as an array or `Iterable`, allowing several objects in a collection to be closed in the same way?

**Comment by lowasser** [comment]
@simonmcooper I discussed that some above -- I'm not sure I follow in what sort of situation you might have an unbounded collection of resources in need of closing?  Or do you just want more of them in one line, in which case a varargs overload might make sense?

Again -- the low-boilerplate way of dealing with both Closeables and AutoCloseables is try-with-resources, which you must have available if you have AutoCloseables.

**Comment by simonmcooper** [comment]
This request is specifically in the situation of member variables of a class being closeable, where the containing class itself implements `Closeable` (or `AutoCloseable`). If you're creating and destroying a `Closeable` within a single method, then try-with-resources works. But if the `Closeable` is a field on a class, then you can't using try-with-resources, you have to do it manually within the containing class's `close` implementation. You can use `Closer` within that method, but, as I've said above, it's quite verbose. A static method where you just pass in the variables to be closed would be better.

One situation where you'll have a collection is, for example, a class maintaining a pool of connections to external servers. When the pool is closed, you want to close all the open connections (presumably stored in a collection), and if an exception is thrown when closing, you don't want to leak any.
