### ISSUE TITLE
Port Google Guava for .NET (C# and VB.NET)

### ISSUE THREAD

**Issue by gabrielsimas** [google/guava#2466]
I ask you permission to start the project to port Google Guava for .NET Framework. I can do?

**Comment by ooxi** [comment]
Why would you need a permission? Guava has a very [permissive license](https://raw.githubusercontent.com/google/guava/master/COPYING) :)

**Comment by gabrielsimas** [comment]
Thanks Bro!

**Comment by quenttelma** [comment]
"Licensor" shall mean the copyright owner or entity authorized by
      the copyright owner that is granting the License.

      "Legal Entity" shall mean the union of the acting entity and all
      other entities that control, are controlled by, or are under common
      control with that entity. For the purposes of this definition,
      "control" means (i) the power, direct or indirect, to cause the
      direction or management of such entity, whether by contract or
      otherwise, or (ii) ownership of fifty percent (50%) or more of the
      outstanding shares, or (iii) beneficial ownership of such entity.

      "You" (or "Your") shall mean an individual or Legal Entity
      exercising permissions granted by this License.
I need a License so I can drive Lol

**Comment by gabrielsimas** [comment]
Yes. We Can! Lol

**Comment by gabrielsimas** [comment]
Let´s Beginning the Avocado Project, a port of Google Guava for .NET

**Comment by quenttelma** [comment]
Quenttel Mathis 2016/4/26

**Comment by quenttelma** [comment]
T o be  honest I don't know how I got here I was looking for information  too getting Player Pro to work II was just reading something online and saw the word License I never thought would _ was ever going to get the Licesne_

**Comment by lowasser** [comment]
@ooxi seems to have covered it: Guava is Apache 2 licensed, and you would just need to follow the restrictions of that license.

**Comment by quenttelma** [comment]
Thanks for reaching out

**Comment by joymon** [comment]
Does the Guava for C# started? Please share the link if so..I am willing to contribute
