### ISSUE TITLE
Request for removal of com.google.common.collect.TreeTraverser from Guava's Beta

### ISSUE THREAD

**Issue by jpangamarca** [google/guava#2471]
Hi, I would like to ask for removal of com.google.common.collect.TreeTraverser from Guava's Beta, since it's a simple and convenient way to traverse hierarchies; one concrete usage (amongst many) we give to it is traversing a class hierarchy in annotation processors. Could it be done? Thanks for your attention.

**Comment by kluever** [comment]
@jrtom Josh: what's our plan w.r.t `TreeTraverser` and the new graph APIs?

**Comment by jpangamarca** [comment]
Hi, any thoughts on this request?

**Comment by jrtom** [comment]
Sorry, I think I missed this when it first came around.

We're currently looking at some changes that would affect what TreeTraverser is and how it would fit in with the common.graph APIs.  I hope that we'll have this resolved for Guava 22, but I don't think that we're ready to remove the @Beta annotation just yet.

Is the @Beta annotation causing you problems?

**Comment by jpangamarca** [comment]
Thanks for your kind response. I'm not having any kind of problems, it's only that today I was reassigned to a project where we make use of TreeTraverser a lot, and was a bit concerned about the plans the Guava devs have for that particular API.

**Comment by jrtom** [comment]
@jpangamarca Noted.  It is possible that we may end up exposing that functionality differently if we end up integrating it with common.graph, but if your main concern is that we might end up removing it entirely, I'd say that's rather less likely.  :)

**Comment by jrtom** [comment]
Calling this closed because `TreeTraverser` is going to be deprecated in favor of the new `Traverser` class in `common.graph`.  (Unfortunately, if you care about the @Beta status, the new API is likely to be in beta for a while.)
