### ISSUE TITLE
FileBackedOutputStream should have overridable temp file name 

### ISSUE THREAD

**Issue by vitamon** [google/guava#2473]
```
 private void update(int len) throws IOException {
    if (file == null && (memory.getCount() + len > fileThreshold)) {
      File temp = File.createTempFile("FileBackedOutputStream", null);
```

This is not convenient when you want to set your own prefix for the temp file name or location, there should be protected method createTempFile()

**Comment by nikhilbarar** [comment]
Any update on this? Can i work on this?

**Comment by kevinb9n** [comment]
There is no justification given for why this is a useful feature.
