### ISSUE TITLE
Javadoc links broken and domain redirecting to this repo

### ISSUE THREAD

**Issue by hflynn** [google/guava#2474]
Hi,
http://docs.guava-libraries.googlecode.com/git/javadoc/com/google/common/cache/CacheBuilderSpec.html is returning a 404 error and http://docs.guava-libraries.googlecode.com is redirecting to this repo. Is this a temporary issue or have your javadocs moved? If the latter, what is the preferred reference URL? http://google.github.io/guava/releases/18.0/api/docs/ or something else?

**Comment by cpovirk** [comment]
The entire Google Code project-hosting service has been turned down, so the links are permanently broken. You've found the right new location, though 19.0 is out, so you can use that: http://google.github.io/guava/releases/19.0/api/docs/

**Comment by kluever** [comment]
Wrote a G+ post about this last night, but sadly those links won't work anymore
https://plus.sandbox.google.com/+googleguava/posts/e1ATtGUxSy7

**Comment by hflynn** [comment]
Thanks both, we'll use the github links from now on.
