### ISSUE TITLE
googlecode returns 404 - can't search for guava javadocs

### ISSUE THREAD

**Issue by maiergre** [google/guava#2475]
Looks like googlecode now returns 404 for the guava API docs. While the docs are also hosted on google.github.io this site is poorly indexed / has poor page rank in google search. So it's basically impossible to reliably google search for the docs. I'm navigating the docs manually now but that's a pain. 

Is it possible to get 301 redirects from googlecode to github.io until the search index picks it up? And/or another way to fix the index? 

thanks

**Comment by kluever** [comment]
See https://github.com/google/guava/issues/2474

**Comment by kluever** [comment]
Also I've reported the bad search results internally...not sure how easy it is to get those fixed, but we'll see.

**Comment by maiergre** [comment]
Thanks! FWIW, I didn't notice #2474 since I didn't look for closed issues. Might want to consider leaving it open for a couple of days. Otherwise you might get more dups.

**Comment by ogregoire** [comment]
> So it's basically impossible to reliably google search for the docs. I'm navigating the docs manually now but that's a pain.

You can always search Google with `<your query> site:google.github.io/guava/releases/19.0/api/docs/`.
