### ISSUE TITLE
Feature Request:  Typescript port of library for use in client-side apps

### ISSUE THREAD

**Issue by icfantv** [google/guava#2476]
Hey, what do you guys think about a potential port of this library to Typescript?  The ES6 spec is missing many things and while it's getting better, it's still really kludgy working with Arrays, e.g.

Yes, there would be some redundant functionality between a potential new lib and both Ramda and Lodash, but curious as to your thoughts.

**Comment by cpovirk** [comment]
We are in favor of good common libraries for programming languages in general. We just won't be the right people to write a TypeScript library, since we lack expertise there.
