### ISSUE TITLE
Links to JSR 305 in Javadoc are broken

### ISSUE THREAD

**Issue by arend-von-reinersdorff** [google/guava#2479]
For example [Javadoc for package `base`](http://google.github.io/guava/releases/19.0/api/docs/com/google/common/base/package-summary.html) link to [`@ParametersAreNonnullByDefault`](http://jsr-305.googlecode.com/svn/trunk/javadoc/javax/annotation/ParametersAreNonnullByDefault.html?is-external=true) results in 404.

Affects all links to JSR 305 annotations.

As far as I can tell JSR 305 is not maintained anymore. Maybe the easiest solution would be to not link to the JSR 305 annotations in the Javadoc.

**Comment by lowasser** [comment]
Google Code is being turned down, but I'm not sure whether or not JSR 305 has just moved?

**Comment by ispringer** [comment]
There doesn't appear to be a new home. Perhaps you could just update the Guava build to download https://repo1.maven.org/maven2/com/google/code/findbugs/jsr305/3.0.1/jsr305-3.0.1-javadoc.jar, unzip it, and then point javadoc at the dir where it was unzipped.

**Comment by arend-von-reinersdorff** [comment]
@ispringer Or point to javadoc.io which does what you describe:
http://www.javadoc.io/doc/com.google.code.findbugs/jsr305/3.0.1
