### ISSUE TITLE
I really wanna know, why not store "volley" on github.com?

### ISSUE THREAD

**Issue by normalhh** [google/guava#2482]
As a developer working in an insurance company which registered in Shanghai, I have a lot of problems in checking out and pulling the volley repository through a proxy server in this insurance company. I highly recommend you store the volley repository on github.com! Thank you all very much!

**Comment by kluever** [comment]
What is the volley repository? Are you sure you reported this to the correct project?

**Comment by JakeWharton** [comment]
Volley is part of AOSP
