### ISSUE TITLE
Support Iterables.frequency with predicate

### ISSUE THREAD

**Issue by youngrafi** [google/guava#2483]
Currently Iterables.frequency() only supports finding object based on equals() method, and for getting frequency by custom predicate, user has to resort to doing something like Iterables.size(Iterables.filter(iterable, predicate));

Would be nice to have a convince method to enable getting frequency by predicate.

**Comment by cpovirk** [comment]
For compound operations, try `FluentIterable`:

`FluentIterable.from(iterable).filter(predicate).size()`

(Or, if you can use Java 8, use similar `Stream` code.)
