### ISSUE TITLE
Build with javac-with-errorprone

### ISSUE THREAD

**Issue by cpovirk** [google/guava#2484]
We use it internally. It would be nice for external contributors if we extended that to our open-source build. And it would set a good example. Possibly we could even turn on some compile errors that haven't been enabled for all of Google. Further, this may make it easier for us to switch from Animal Sniffer to the (currently internal but maybe to be released someday?) Error Prone version checker.

**Comment by keerthikorivi** [comment]
Hi,

Can I take up this task? If I understand correctly error-prone is like static checking tool and we include it as part of the maven compiler plugin as shown [here | https://errorprone.info/docs/installation]

**Comment by cpovirk** [comment]
We wouldn't mind a PR for this, though ideally someday we'll move to Bazel and get it for free :)

**Comment by cpovirk** [comment]
This would also be a nice opportunity to enable NullAway: NullAway's nullness checking should be largely redundant with what we have internally, but:
- It would be nice to make some of that checking available to external contributors.
- It could help us avoid causing problems like https://github.com/google/guava/issues/6126 in the future.

**Comment by cpovirk** [comment]
Some notes on the impact on build performance: https://github.com/google/guava/pull/7093#issuecomment-2040355786
