### ISSUE TITLE
Tests fail for version 19.0 under Windows

### ISSUE THREAD

**Issue by tschoening** [google/guava#2488]
I tried building version 19.0 under Windows from source using maven, simply cloned the git repo and issued "mvn install" until the following error occured:

	org/mockito/internal/stubbing/ConsecutiveStubbing.class,
	com\google\common\collect\FilteredCollectionsTest$AbstractFilteredCollectionTest.class,
	com\google\common\util\concurrent\AbstractFutureTest$3.class,
	com\google\common\collect\TableCollectionTest$TreeRowMapHeadMapTests.class,
	com/google/common/util/concurrent/testing/AbstractListenableFutureTest$4.class,
	com/google/common/base/AbstractIterator.class,
	com/google/common/truth/PrimitiveCharArraySubject.class, 
	com\google\common\reflect\TypeTokenTest$324.class,
	com/google/gson/LongSerializationPolicy.class,
	com/google/inject/spi/InjectionPoint$Position.class,
	org/joda/time/tz/data/Europe/Lisbon,
	javax/annotation/meta/TypeQualifierDefault.java,
	com/google/common/collect/BiMap.class,
	com/google/common/collect/Lists$TransformingRandomAccessList$1.class, 
	org/mockito/asm/tree/analysis/SmallSet.java, 
	org/junit/runner/manipulation/Sorter$1.class, 
	com\google\common\collect\MultimapsCollectionTest$2.class, 
	com/google/common/util/concurrent/AbstractService$3.class, 
	org/joda/time/tz/data/Africa/, 
	net/sf/cglib/core/EmitUtils$3.class, 
	com/google/common/base/CharMatcher.class, 
	com/google/common/collect/MapMakerInternalMap$WeakEvictableEntry.class, 
	com/google/common/util/concurrent/SettableFuture.class, 
	org/joda/time/YearMonthDay.class, 
	com/google/common/collect/Cut.class, 
	org/mockito/internal/invocation/InvocationsFinder$RemoveNotMatching.class, 
	com\google\common\hash\HashTestUtils$RandomHasherAction$1.class, 
	com\google\common\reflect\TypeTokenTest$30.class]>

	should have contained <com/google/common/reflect/ClassPathTest.class>
	testGetClassPathEntry(com.google.common.reflect.ClassPathTest):

	expected:<file:/C:/usr/test/dep.jar> 
	but was:<file:/usr/test/dep.jar> 

	testGetClassPathFromManifest_absoluteDirectory(com.google.common.reflect.ClassPathTest): 

	Not true that <[\with\absolute\dir]> contains exactly <[C:\with\absolute\dir]>. It is missing <[C:\with\absolute\dir]> and has unexpected items <[\with\absolute\dir]>

	testGetClassPathFromManifest_multiplePaths(com.google.common.reflect.ClassPathTest):

	Not true that <[\with\absolute.jar,
	C:\Users\tschoening\Documents\Svn\Src\Libs\trunk\Java\Google\Guava\19.0\src\guava-tests\base\relative.jar,
	C:\Users\tschoening\Documents\Svn\Src\Libs\trunk\Java\Google\Guava\19.0\src\guava-tests\base\relative\dir]>
	contains exactly <[C:\with\absolute.jar,
	C:\Users\tschoening\Documents\Svn\Src\Libs\trunk\Java\Google\Guava\19.0\src\guava-tests\base\relative.jar,
	C:\Users\tschoening\Documents\Svn\Src\Libs\trunk\Java\Google\Guava\19.0\src\guava-tests\base\relative\dir]>.
	It is missing <[C:\with\absolute.jar]> and has unexpected items <[\with\absolute.jar]>

	testGetClassPathFromManifest_absoluteJar(com.google.common.reflect.ClassPathTest):

	Not true that <[\with\absolute.jar]> contains exactly <[C:\with\absolute.jar]>.
	It is missing <[C:\with\absolute.jar]> and has unexpected items <[\with\absolute.jar]>

	Tests run: 726068, Failures: 7, Errors: 0, Skipped: 0

**Comment by cpovirk** [comment]
Thanks. Unfortunately, this is expected right now, as we don't have a convenient continuous build to verify that things work on Windows.

https://github.com/google/guava#important-warnings
