### ISSUE TITLE
Overload Joiner.join with a function parameter

### ISSUE THREAD

**Issue by RoiEXLab** [google/guava#2496]
Currently when calling `Joiner.on(String).join(Iterable<E>)` the `toString()` method is called to get a String from the given Object.
Sometimes you want to use `getName()` or `getText()` in order to get a String instead...
To achieve this the join method could be overloaded accepting a java.util.function.Fuction<T,R> parameter, with T being the generic type of the given Iterable Object, and R being a String.
This way the developer could choose how he wants to get a string from the object.

**Comment by cpovirk** [comment]
We have a way of doing this, but it requires a slightly different approach:

`FluentIterable.from(...).transform(...).join(joiner)`

Maybe we should document this pattern on `Joiner`.

**Comment by RoiEXLab** [comment]
That would be useful...
But still,,, I think my attempt would be more intentional...
```
List<JButton> buttons = new ArrayList<>();
//Initializing
Joiner.on(",").join(buttons, button -> button.getText());//returns text
```

**Comment by cpovirk** [comment]
One difficulty with an overload of `join` is that

**Comment by RoiEXLab** [comment]
`specialJoin()` ?

**Comment by RoiEXLab** [comment]
Also you could change
```
 private static Iterable<Object> iterable(
      final Object first, final Object second, final Object[] rest) {
    checkNotNull(rest);
    return new AbstractList<Object>() {
      @Override
      public int size() {
        return rest.length + 2;
      }

      @Override
      public Object get(int index) {
        switch (index) {
          case 0:
            return first;
          case 1:
            return second;
          default:
            return rest[index - 2];
        }
      }
    };
  }
```

to
```
 private static <E> Iterable<E> iterable(
      final E first, final E second, final E[] rest) {
    checkNotNull(rest);
    return new AbstractList<E>() {
      @Override
      public int size() {
        return rest.length + 2;
      }

      @Override
      public E get(int index) {
        switch (index) {
          case 0:
            return first;
          case 1:
            return second;
          default:
            return rest[index - 2];
        }
      }
    };
  }
```
In order to avoid errors of that kind, since therefore the Objects have to be all the same...

**Comment by lowasser** [comment]
Adding transform functionality directly to Joiner has been discussed and ruled out in #1392 and #1064.

In any event, in Java 8 you have access to the superior `collection.stream().map(function).collect(joining(...))`.

**Comment by cpovirk** [comment]
Thanks, Louis. I filed https://github.com/google/guava/issues/2497 for the possible doc change.
