### ISSUE TITLE
ClassPath.getTopLevelClasses not returning class files in a war file if deployed using Wildfly

### ISSUE THREAD

**Issue by AndrewWu1123** [google/guava#2501]
Hello,

Guava 19.0
Wildfly 10.0.0
Java 8u74

I am using Wildfly 10.0.0, and getTopLevelClasses is not returning my custom java classes inside the war file and only the classes, digged in to the code of ClassPath class under guava.jar and noticed that in getClassPathEntries(ClassLoader classloader) it will only include if the ClassLoader is an instance of URLClassLoader, however JBoss/Wildfly seems to use ModuleClassLoader (http://docs.jboss.org/jbossmodules/1.3.0.Final/api/org/jboss/modules/ModuleClassLoader.html). Any work around or is it a limitation of guava?

* Note code works perfectly in tomcat

**Comment by eamonnmcmanus** [comment]
The base ClassLoader API doesn't include a way to list all classes that might be loaded. URLClassLoader implicitly does have a way to do that (read the files or the jar that each URL points to), but it looks as if ModuleClassLoader doesn't. So I would say this isn't a limitation of Guava: there just isn't any way to do what you want to do.

**Comment by AndrewWu1123** [comment]
Noted, thank you, we did a work around, using ServletContext.getResourcePaths(<WEB-INF/classes/pck>) then load using File.

Thanks for your help.

**Comment by dherges** [comment]
One workaround around the issue is to wrap the Wildfly/JBoss ModuleClassLoader in an URLClassLoader. Also give it the URLs for the virtual file system ("vfs:" protocol):

```java
        final List<URL> toScan = new ArrayList<>();
        final Enumeration<URL> classLoaderResources = classLoader.getResources("/");
        while (classLoaderResources.hasMoreElements()) {
          final URL resourceUrl = classLoaderResources.nextElement();

          if ("file".equals(resourceUrl.getProtocol())) {
            toScan.add(resourceUrl);
          } else if ("vfs".equals(resourceUrl.getProtocol())) {
            // examine virtual file system
            URLConnection urlConnection = resourceUrl.openConnection();
            Object content = urlConnection.getContent();

            if (content instanceof VirtualFile) {
              VirtualFile vf = (VirtualFile) urlConnection.getContent();

              if (StringUtils.endsWith(vf.getName(), ".war") || StringUtils.endsWith(vf.getName(), ".jar")) {
                File archiveFile = new File(vf.getParent().getPhysicalFile(), vf.getName());
                toScan.add(archiveFile.toURI().toURL());
              } else {
                toScan.add(vf.getPhysicalFile().toURI().toURL());
              }
            }

          }
        }

        return new URLClassLoader(toScan.toArray(new URL[]{}), classLoader);
```
