### ISSUE TITLE
ComparisonChain require check null

### ISSUE THREAD

**Issue by wshen324** [google/guava#2503]
At ComparisonChain.java line 81.
Argument left can be null, if left is null, will throw NullPointException.
Must write as below code, not elegant.

`return ComparisonChain.start()`
`.compareFalseFirst(firstName != null, o.firstName != null)`
`.compare(firstName, o.firstName)`

**Comment by lowasser** [comment]
Generally speaking nulls usually indicate a bug you should actually deal
with rather than just silently accepting them.

Anyway, why not use compare(firstName, o.firstName,
Ordering.natural().nullsFirst())?

**Comment by samwho** [comment]
My use case for `ComparisonChain` was implementing an `equals()` method while avoiding the usual pitfalls involved.

Consider the following example:

```
public final class Foo implements Comparable<Foo> {
  private String bar;

  public Foo(String bar) {
    this.bar = bar;
  }

  @Override
  public int compareTo(Foo other) {
    return ComparisonChain.start()
      .compare(other.foo, foo)
      .result();
  }

  @Override
  public int hashCode() {
    return Objects.hash(foo);
  }

  @Override
  public boolean equals(Object other) {
    if (this == other) return true;
    if (other == null) return false;
    if (this.getClass() != other.getClass() return false;

    return this.compareTo((Foo)other) == 0;
  }
}
```

In this example, a `NullPointerException` is thrown if the private member `foo` is null.

I know that I could use `compare(this.foo, foo, Ordering.natural().nullsFirst())` but it feels, to me, that accepting nulls by default is not always bad. Null members aren't always indicative of bugs in your code, and if my use case for `ComparisonChain` is common then having some sensible default that takes nulls in to account isn't a bad idea.

What do you think?

**Comment by ronshapiro** [comment]
Closing this given @jrtom and @lowasser's comments - if you have new data/examples for consideration, feel free to comment and we can rediscuss.
