### ISSUE TITLE
EventBus: Duplicating handlers 

### ISSUE THREAD

**Issue by kronar** [google/guava#2504]
Looks like that there is an issue in EventBus - there is a way to register same handler class with one handler method two times and event will be handled 2 times 

Here is gist with test to reproduce this issue 
https://gist.github.com/kronar/4614b636ec5c379f1cd5df2a6fed1ec4

**Comment by lowasser** [comment]
I'm not certain why this wouldn't be working as intended, or even breaking to other users who depended on this behavior.  Registering two of the same handlers seems like an indication that the user specifically wants events to be handled twice.

**Comment by kronar** [comment]
@lowasser I've  implemented builder for event bus which scans package in classpath and filters classes having methods annotated with @Subscribe annotation.  Couple of classes have multiple methods with this annotation so list of those classes contains duplicates. Therefore some pieces of business logic we're executed twice.

**Comment by lowasser** [comment]
It sounds like that's an issue your builder should be addressing, not EventBus.
