### ISSUE TITLE
Iterators.forArray can return a ListIterator

### ISSUE THREAD

**Issue by ghost** [google/guava#2505]
`Iterators.forArray` returns `UnmodifiableIterator`, but that just calls an overload, that returns an `UnmodifiableListIterator`

It would be useful if the public method returned a `ListIterator`, rather than restricting it to `Iterator`.

Plus, it would be good if the various overloads (array, offset, length) and (array, offset, length, index) were publically accessible, seeing as one `forArray` method is public already.

**Comment by kluever** [comment]
That API is non-@Beta, and this might be an incompatible change. Can you confirm @cpovirk ?

**Comment by eamonnmcmanus** [comment]
It would be binary-incompatible, since the return type of a method is part of its signature, as encoded in the invokestatic instruction in class files.

**Comment by cpovirk** [comment]
We could hack around this by creating a package-private superclass of `Iterators` with the old signature. Probably it's not worth the trouble, though. Returning `ListIterator` would have been better, but you can call `asList(array).listIterator()` or `asList(array).subList(x, y).listIterator()` where necessary.

**Comment by cpovirk** [comment]
This would have been nice to do differently, but given how infrequently people need a `ListIterator`, I'm guessing that the small chance of breaking people (if they build against a version of Guava with the new version but run against the old) outweighs the utility.
