### ISSUE TITLE
Small update for Listenable Futures Explained docs

### ISSUE THREAD

**Issue by codemonkey800** [google/guava#2507]
Specifically [here](https://github.com/google/guava/wiki/ListenableFutureExplained#application).

For the method that accepts an `AsyncFunction`, it should be renamed from `transform` to `transformAsync` instead. I would contribute but I'm not sure how to access the wiki as an intern.

:smiley:

**Comment by cgdecker** [comment]
Thanks, fixed! The wiki is only editable by team members currently.
