### ISSUE TITLE
StringsExplained doesn't mention c.g.c.b.Strings

### ISSUE THREAD

**Issue by dimo414** [google/guava#2508]
[StringsExplained](https://github.com/google/guava/wiki/StringsExplained) mentions several useful `String` utilities, but leaves out the [`Strings`](https://google.github.io/guava/releases/snapshot/api/docs/com/google/common/base/Strings.html) class.

**Comment by cpovirk** [comment]
It is at least technically mentioned nowadays: https://github.com/google/guava/wiki/StringsExplained#strings
