### ISSUE TITLE
DoubleMath incorrectly rounds 0.99999999999999994 to 2 with rounding mode UP or CEILING

### ISSUE THREAD

**Issue by terzerm** [google/guava#2509]
**Failure cases:**
_1) Positive_
Values rounded incorrectly: `0.99999999999999984` to `0.99999999999999994`
Rounding modes: CEILING or UP
Expected: `1`
Actual: `2`

_2) Negative_
Values rounded incorrectly:` -0.99999999999999984` to `-0.99999999999999994`
Rounding modes: FLOOR or UP
Expected: `-1`
Actual: `-2`

**Remarks:**
The reason is that values between 0 and 1 have higher fraction precision than values between 1 and 2. The code adds 1.0 to the value x, and double arithmetic uses HALF_EVEN rounding by default. This leads to unexpected results for edge cases when HALF_EVEN triggers rounding UP to 2.

**Proposed FIX:**
The FIX is to cast the double value `x` to a long before the addition of `1.0`:
Current:` x + 1.0`
Fixed: `(long)x + 1.0`

**Pull Request:**
See pull request [#2511](https://github.com/google/guava/pull/2511)

**Comment by lowasser** [comment]
Fixed the bug; I think we ended up slightly changing the implementation (and doing much more aggressive testing).  The fix should be mirrored out shortly.
