### ISSUE TITLE
Feature request: add partition method to Sets utility class

### ISSUE THREAD

**Issue by lpbak** [google/guava#2516]
The utility class `Sets` could use a new method `<T> Set<Set<T>> partition(Set<T> set, int size)`, similar to the one in `Lists` class. Such a method would be useful for various applications, e.g. for batch processing elements for which order is unspecified/unimportant, and I don't think there is a straightforward way of achieving the same effect with Java 8 streams API.

**Comment by lowasser** [comment]
I'm not sure what's unsuitable about Iterables.partition for this use case?

**Comment by lpbak** [comment]
It's simply a matter of convenience. Let's say I have a method `void processElements(Set<Element> elements)`, a set of elements `Set<Element> elements` and I'd like to process these elements in batches. I can achieve that using `Iterables.partition`, e.g. like that:

    StreamSupport.stream(Iterables.partition(elements, batchSize).spliterator(), false)
        .map(list -> new HashSet<Long>(list)).forEach(batch -> {
            processElements(batch);
        });

But I'd much prefer to be able to do it like that:

    Sets.partition(elements, batchSize).forEach(batch -> {
        processElements(batch);
    });

I find the latter more concise and more readable.

**Comment by lowasser** [comment]
I'm not sure why you wouldn't write

    Iterables.partition(elements, batchSize)
        .forEach(batch -> processElements(new HashSet<>(batch)))

I'm also a bit concerned about issues like Sets.partition(myTreeSet, batchSize) not being able to identify which set implementation to use.  It's not even clear what set implementation we'd want -- immutable?  LinkedHashSet? -- where there's no real ambiguity for lists.

**Comment by liach** [comment]
Or one like `partition(Set<T> set, int size, Supplier<Set<T>> setCreator)`?

**Comment by cpovirk** [comment]
Another complication: `Iterables.partition` can be done in a "mostly streaming" fashion, but `Sets.partition` would need to be done eagerly (or else inefficiently). That means that switching from `Iterables.partition` to `Sets.partition` has performance implications -- different (IIRC) from comparable switches like from `Iterables.filter` to `Sets.filter`.
