### ISSUE TITLE
Typo in the javadoc of StatsAccumulator's and Stats's populationVariance() method

### ISSUE THREAD

**Issue by omega09** [google/guava#2522]
The snapshot API has the following typos:

`com.google.common.math.StatsAccumulator`: `public final double populationVariance()` and
`com.google.common.math.Stats`: `public double populationVariance()` say

> This is guaranteed to return zero if **the the** dataset contains only exactly one finite value.

Instead of

> This is guaranteed to return zero if **the** dataset contains only exactly one finite value.

**Comment by kluever** [comment]
Good eye! Will get this fixed up
