### ISSUE TITLE
getTopLevelClassesRecursive with spaces within the execution path

### ISSUE THREAD

**Issue by flashpixx** [google/guava#2524]
Hello,

I try to get all classes within a package:

``` java
ClassPath.from( Thread.currentThread().getContextClassLoader() ).getTopLevelClassesRecursive( "my.package" );
```

This works fine, except the jar file contains spaces. My jar stores all dependencies so I can get the classes from my jar:

```
test.jar/
    my/
         package/
               someclass.class
```

If I run the test.jar within a path without spaces e.g. c:\Users\MyUser\ with java -jar test.jar everything is fine, but on c:\Users\MyUser\Dir With Spaces\ and java -jar test.jar the getTopLevelClassRecursive returns an empty set.

Same error exists under OSX, if I run the jar under /User/MyUser/ with java -jar test.jar everything is fine but under /User/MyUser/New Folder/ I get also an empty set.

**Comment by perceptron8** [comment]
Duplicate of https://github.com/google/guava/issues/2152?

**Comment by 3xp0n3nt** [comment]
Yes, it's a duplicate. `#getTopLevelClassesRecursive` delegates to `#getTopLevelClasses`.

**Comment by swaggalolz** [comment]
see parsing spaces when it changed for '%20' in cmd or classLoader 

Example: file:/C:/Program%20Files/

**Comment by perceptron8** [comment]
@flashpixx #2152 has been resolved, I think you can close this one.

**Comment by cpovirk** [comment]
Thanks.
