### ISSUE TITLE
Typo in the javadoc of Ordering's explicit(List<T>) method

### ISSUE THREAD

**Issue by omega09** [google/guava#2525]
The [snapshot Javadoc of Ordering#explicit(java.util.List)](http://google.github.io/guava/releases/snapshot/api/docs/com/google/common/collect/Ordering.html#explicit(java.util.List))  contains the sentnece:

> The returned comparator throws **an ClassCastException** when it receives an input parameter that isn't among the provided values.

instead of

> The returned comparator throws **a ClassCastException** when it receives an input parameter that isn't among the provided values.

**Comment by govindpatel** [comment]
can I fix this issue?
