### ISSUE TITLE
ImmutableMap compile time error when using <Class,Function<Type, ?>>

### ISSUE THREAD

**Issue by 0ndorio** [google/guava#2529]
Today I tried to build a few ImmutableMaps which store class objects and related conversion functions. This worked well for primitive types and the related Wrapper functions but not for Lists and Collections. As soon as I started to add multiple related classes java compilation broke with 

> error: incompatible types: Object is not a functional interface 

and nothing more. IntelliJ and other IDEs do not show any related error hints and when I change Immutable map to JDK classses like HashMap the error disappears.

Success:

```java
private static final Map<Class, Function<List, ?>> convertListToType  
        = ImmutableMap.<Class, Function<List, ?>>builder()  
            .put(String.class, Object::toString)  
            .put(Set.class, HashSet<Object>::new)
            .build();  
```

```java
    private static final Map<Class, Function<Integer, ?>> convertIntegerToType
        = ImmutableMap.<Class, Function<Integer, ?>>builder()
            .put(double.class, Double::new)
            .put(Double.class, Double::new)
            .put(float.class, Float::new)
            .put(Float.class, Float::new)
            .put(long.class, Long::new)
            .put(Long.class, Long::new)
            .put(String.class, Object::toString)
            .build();
```

Different Error Cases:

```java
private static final Map<Class, Function<List, ?>> convertListToType  
        = ImmutableMap.<Class, Function<List, ?>>builder()  
            .put(Set.class, HashSet<Object>::new)
            .put(String.class, Object::toString)  
            .build();  
```
(This is the first success case with rows switched.)

```java
private static final Map<Class, Function<List, ?>> convertListToType  
        = ImmutableMap.<Class, Function<List, ?>>builder()  
            .put(String.class, Object::toString)  
            .put(Set.class, HashSet<Object>::new)
            .put(HashSet.class, HashSet<Object>::new)
            .build();  
```
(This is the first success case with an additional row containing the  "HashSet.class"  information.)

**Comment by lowasser** [comment]
This sounds like a problem with compiler type inference and not something Guava can do anything about.

**Comment by michaelhixson** [comment]
Interesting find.  Java 9's javac and Eclipse's compiler can both handle this, so it does look like a bug in Java 8's javac.

I don't know how Guava could work around this.  Consider this other code which demonstrates the same problem:

```java
import java.util.List;
import java.util.Map;
import java.util.function.Function;

class GenericsTest {
  static class Builder<K, V> {
    Builder<K, V> put(K k, V v) { return this; }
    Map<K, V> build() { return null; }
  }

  static Map<Class, Function<List, ?>> convertListToType =
      new Builder<Class, Function<List, ?>>()
          .put(Integer.class, GenericsTest::foo)
          .put(String.class, Object::toString)
          .build();

  static <T> Integer foo(List<T> list) {
    return null;
  }
}
```

Is something wrong with the signatures of `Builder`?  If so, I don't see it.

I think the only choice is to work around this application side, for example by avoiding raw `List` in favor of wildcard `List<?>`.

**Comment by 0ndorio** [comment]
Okay. If it isn't a failure on guavas site I will close this issue.
