### ISSUE TITLE
add a simple isNullOrEmpty to Lists class

### ISSUE THREAD

**Issue by jonathanbeber** [google/guava#2532]
Just adding a method similar to already existing in Strings class, I'm thinking in something like [this](https://github.com/google/guava/compare/master...jonathanbeber:master)

**Comment by lowasser** [comment]
This is explicitly in the list of features that have been rejected for Guava; see https://github.com/google/guava/wiki/IdeaGraveyard#iterablesisnullorempty, which also links to a discussion of the issue on StackOverflow.

**Comment by jbduncan** [comment]
@lowasser got there just before me! :smiley:
