### ISSUE TITLE
Cache with sliding window (or moving average) statistics

### ISSUE THREAD

**Issue by marembo2008** [google/guava#2536]
## Summary

Currently guava cache statistics collect stats over an extended period of the lifetime of the cache.
This is barely useful, as after an extended period of time, the statistics starts to flatten out, with current specific intervals contributing barely to the overall statistics.
## Proposal
- Design the cache stats with a sliding window or moving average statistics.
- The design would require a change to the in line of

```
CacheBuilder
    .newBuilder()
    .recordStarts(CacheStats.withSlidingWindowSize(60000ms)) // 1-minute sliding window or recordStarts(CacheStats.withMovingAverage())
    .build()
```

Then the CacheStats would introduce new properties such as:

```
CacheStats.hitCount(1000ms) //per second
CacheStats.missCount(1000ms) //per second
CacheStats.averageLoadLatency(1000ms)// per second
...
```

**Comment by ben-manes** [comment]
This would break the contract for `Cache.stats()` which states,
> All stats are initialized to zero, and are monotonically increasing over the lifetime of the cache.

The [design rational](https://groups.google.com/d/msg/guava-discuss/rGCI9dbpCS8/eNFErJKoEUAJ) is nicely described by Kevin's forum post, so I won't repeat it. I think its an insightful perspective and negates the need for this enhancement.

**Comment by marembo2008** [comment]
@ben-manes The proposal is a breaking change.
The idea and the functionality is thus: At any arbitrary time, i would like to get the average request counts of the last minute. At the said instant, i do not have ```CacheStats``` at ```n-1``` minutes, and hence i cannot get the difference between the current instance ```CacheStats``` and the ```CacheStats``` at the ```n-1``` minute. 

The other solution i may have is to listen to all events of cache such as put, eviction etc, and record instantaneous ```CacheStats``` on a different sliding window counter, which is way too verbose.

I was hoping that an implementation on top of the ```CacheStats```, without breaking existing usage, can still be implemented.

**Comment by ben-manes** [comment]
The suggested approach would be to use a library like Dropwizard metrics to aggregate and report on statistics. Then Guava doesn't need to provide this directly, only facilitate collection of statistics for you to view in the appropriate tool.

**Comment by cgdecker** [comment]
I don't think this is something we're going to do.
