### ISSUE TITLE
The Javadoc link is broken.

### ISSUE THREAD

**Issue by ekimber** [google/guava#2537]
The Javadoc link just 404s to the broken Googlebot.

**Comment by kluever** [comment]
Which link? Can you be more specific?

**Comment by ekimber** [comment]
The one on the front page for the latest release.  This one:
http://google.github.io/guava/releases/19.0/api/docs/

**Comment by kluever** [comment]
That link seems to work for me...is it not working for you?

**Comment by ekimber** [comment]
Hmmm it may be something to do with the network administration here, I will investigate that first.  Sorry to have bothered you.
