### ISSUE TITLE
Waiting Thread , Concurrency Issue with guava cache 

### ISSUE THREAD

**Issue by sjaini44u** [google/guava#2538]
We are using Loading cache which has specific eviction timeout set for entries. We are encountering issue of hanging thread while accessing the cache values.
6 threads were trying to access the cache . Out of that 3 had stack trace:-

State: RUNNABLE
Total blocked: 52  Total waited: 56

Stack trace: 
sun.misc.Unsafe.park(Native Method)
java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:445)
com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:79)
com.google.common.util.concurrent.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:143)
com.google.common.cache.LocalCache$LoadingValueReference.waitForValue(LocalCache.java:3573)
com.google.common.cache.LocalCache$Segment.waitForLoadingValue(LocalCache.java:2306)
com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195)
com.google.common.cache.LocalCache.get(LocalCache.java:3953)
com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3957)
com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4875)

Other 3 were at :-  
State: WAITING on com.google.common.util.concurrent.SettableFuture@23106645
Total blocked: 3,086  Total waited: 3,371

Stack trace: 
sun.misc.Unsafe.park(Native Method)
java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:445)
com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:79)
com.google.common.util.concurrent.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:143)
com.google.common.cache.LocalCache$LoadingValueReference.waitForValue(LocalCache.java:3573)
com.google.common.cache.LocalCache$Segment.waitForLoadingValue(LocalCache.java:2306)
com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195)
com.google.common.cache.LocalCache.get(LocalCache.java:3953)
com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3957)
com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4875)

Could someone tell , is this an existing issue ?

**Comment by sjaini44u** [comment]
Not concern any more

**Comment by ryber** [comment]
I've seen the same issue. Can I ask what you found that made you close this?

**Comment by sjaini44u** [comment]
In my case, it was some other third party lib issue, it was not directly guava lib. So i closed this.

**Comment by aqua3090** [comment]
can you please name the third party library and also what changes you had to make to resolve this issue?

**Comment by mrapelly** [comment]
Please provide the resolution that helped you to fix this issue

**Comment by rady66** [comment]
You can easily reproduce that by passing a Function which throws an exception (e.g. ClassNotFoundException for missing dependency on 3rd library)... Not sure what the pattern should be like, but I guess, it may need the Function to consume/catch all the exceptions and then exposed to the created object...
