### ISSUE TITLE
Iterables.toString() throwing NPE

### ISSUE THREAD

**Issue by guyman** [google/guava#2553]
I think this code:
```
 public static String toString(Iterable<?> iterable) {
    return Iterators.toString(iterable.iterator());
  }
```
Should perform a Null check, like:
```
 public static String toString(Iterable<?> iterable) {
if (iterable == null) {
    return "null";
}
    return Iterators.toString(iterable.iterator());
  }
```

Currently I have a very complex object that I can't toString() because some field in its fifth hierarchy uses this toString() and I get a NPE.

**Comment by kluever** [comment]
This would be a backwards incompatible change, and thus unlikely for us to do.

Assuming you control the types inside the nested iterables, can you have your type return an empty list instead of null? (e.g., `ImmutableList.of()`)?

**Comment by guyman** [comment]
Hi, I can't control the types inside the nested iterables.
About the backwards incompatibility:
1) Do you mean that there might be some consumer code that relies on this to throw NPE and you don't want to break it?
2) The "normal" way in Java when you try to print null to a log, is to write the string 'null' and not throw an NPE.

**Comment by kluever** [comment]
1) yes. generally Guava is "nullergic" and throws a NPE when passed a null reference.
2) yes, that's the case for `Objects.toString()` and `String.valueOf()`, but very few other APIs use the magic string "null".

Presumably somewhere you're calling `Iterables.toString(possiblyNullList)`, right? Why not just wrap that call in a conditional (or use a ternary as I suggested above)?

**Comment by guyman** [comment]
Thanks for the quick respond.
I can't control those places because I am using a third party and these objects are not in my control.

**Comment by lowasser** [comment]
This sounds like a bug in the third party library if it is passing
iterables that may be null to Iterables.toString.
