### ISSUE TITLE
ByteStreams.copy(InputStream, WriteableByteChannel)

### ISSUE THREAD

**Issue by leventov** [google/guava#2559]
It would be nice to have such method, which is just another version of `ByteStreams.copy(InputStream, OutputStream)` or `ByteStreams.copy(ReadableByteChannel, WriteableByteChannel)` with minimal modifications.

It seems that currently using only JDK and Guava, the only way to move bytes from InputStream to WriteableByteChannel is `ByteStreams.copy(Channels.newChannel(inputStream), writeableByteChannel)`, which does double buffering (first inside a channel, returned from newChannel(), second in the body of the ByteStreams.copy() method).

**Comment by cgdecker** [comment]
While there's certainly conceivably some value in this, I mostly feel like it's preferable to keep the worlds of streams and channels separate and not add methods that deal with both.
