### ISSUE TITLE
Potential memory (& speed?) optimisation for Graphs::transitiveClosure

### ISSUE THREAD

**Issue by jbduncan** [google/guava#2563]
To continue the conversation I started at https://github.com/google/guava/commit/0f0f616ef7962d97748e2b1bbbd539e96dcbc7b4#commitcomment-18709801, I found a potential replacement for lines 76-84 which both removes the need to copy `reachableNodes` set into an `ImmutableList` and, like the current solution, carefully avoids iterating over all reachable nodes within the inner loop unless necessary.

```java
...
Set<N> reachableNodes = reachableNodes(graph, node);
visitedNodes.addAll(reachableNodes);
Iterator<N> outerIterator = reachableNodes.iterator();
for (int a = 0; outerIterator.hasNext(); a++) {
  N nodeU = outerIterator.next();
  for (N nodeV : Iterables.limit(reachableNodes, a + 1)) {
    transitiveClosure.putEdge(nodeU, nodeV);
  }
}
...
```

However, although I'm reasonably certain that the above solution uses less memory and runs faster than the old one for sufficiently large graphs, I've not actually created any benchmarks (JMH or otherwise) or done any profiling to prove so.

When I run all of the tests under `com.google.common.graph` (including some new ones which I wrote myself and put under my local copy of `GraphsTest.java`) with the above code change applied on my Windows machine, they all pass without any problems.

Has the Guava team already considered a solution like this? If not, would it be worthwhile for me to submit a Pull Request for this?

**Comment by jrtom** [comment]
We have gone ahead and made this change, and it should show up soon.  Thanks for the suggestion, @jbduncan!  :)

**Comment by jbduncan** [comment]
Oh wow, fantastic! How thrilling! :blush: 

I look forward to seeing it pop up in source code.

**Comment by jbduncan** [comment]
Will I be given credit in the commit message or somewhere else when it rolls in?

I ask because since I didn't actually submit a PR, it I doubt it'll credit me as the author in GitHub's records.

**Comment by Bezier89** [comment]
I did mention your name in the change description. I don't believe GitHub
will register you as the author though (but if that's important I'm sure
there's a way to do it).

**Comment by jrtom** [comment]
@jbduncan You're mentioned in the commit message ("Credit to jbduncan for the idea").  :)

**Comment by jbduncan** [comment]
@Bezier89 @jrtom If I could be registered as the author then that would be great. If not, as long as I'm given credit in the commit message then that's fine with me too. :)
