### ISSUE TITLE
FluentIterable#isEmpty is misleading

### ISSUE THREAD

**Issue by shestakov-m-a** [google/guava#2566]
Javadoc at FluentIterable#isEmpty() says:
"Determines whether this fluent iterable is empty."

However, in reality it checks whether underlying iterator is exhausted yet and never checks for emptiness. Either the method  behaviour or the javadoc is misleading.

**Comment by lowasser** [comment]
I'm not sure what you mean here? iterator() should be returning a fresh iterator every time, so the FI should be empty if and only if if a fresh iterator doesn't have a single element.
