### ISSUE TITLE
Warning about forked jvm being killed on Travis

### ISSUE THREAD

**Issue by TimvdLippe** [google/guava#2568]
On Travis there appears to be a warning regarding a forked jvm. An example build is https://travis-ci.org/google/guava/jobs/143991838#L5029

> [INFO] Running com.google.gwt.junit.tools.GWTTestSuite@53d5264c
[WARNING] Forked JVM has been killed on time-out after 600 seconds

This seems to be happening on all builds and I can also reproduce this error locally running on Ubuntu 16.04.

**Comment by cpovirk** [comment]
Thanks. We'll bump the timeout.

**Comment by TimvdLippe** [comment]
Sadly the errors have returned after commit https://github.com/google/guava/commit/c298e2dcfed6c3f42407477b9fc6fc5094d88468, see builds https://travis-ci.org/google/guava/jobs/161959726#L5083 and https://travis-ci.org/google/guava/jobs/161705406#L5065

**Comment by cpovirk** [comment]
That helped a little, but it looks like we're hitting a limit set by Travis:
https://travis-ci.org/google/guava/jobs/162808090
https://github.com/prov-suite/interop-test-harness/issues/13#issuecomment-228038376

Possibly we should just disable GWT tests for Travis entirely.
