### ISSUE TITLE
Making hasLowerBound()/hasUpperBound() nullsafe!?

### ISSUE THREAD

**Issue by rekx** [google/guava#2570]
If you call hasLowerBound()/hasUpperBound() without checking for null you are getting a NPE if the Range itself wasn't initalized. It should return false if the lower/upper Endpoint is null.

`
  public boolean hasLowerBound() {
    return lowerBound != Cut.belowAll();
  }
`

**Comment by cpovirk** [comment]
Can you provide a failing test that shows the behavior you'd like changed?
