### ISSUE TITLE
ImmutableMap.Builder.computeIfAbsent?

### ISSUE THREAD

**Issue by cgrushko** [google/guava#2573]
If there's a plan to implement this method in ImmutableMap.Builder, I'm happy to send a CL.

**Comment by lowasser** [comment]
We've historically resisted making Builders any more full featured than just basic add-only APIs.  Note ImmutableMap.Builder's internal implementation is just a list of entries, not a map that supports efficient contains queries...and messing with that implementation would impose costs on all existing users of ImmutableMap.Builder, not just the ones who want computeIfAbsent.

At the moment there's a super easy workaround: use a LinkedHashMap, computeIfAbsent on it, and then ImmutableMap.copyOf that.  That's essentially the implementation we'd be using internally anyway if we supported this feature.

**Comment by cgrushko** [comment]
Yep, we're using copyOf on a hash map. Thought I'd save some memory,
though.

**Comment by lowasser** [comment]
I don't believe there's an implementation of the Builder we could write
that would support computeIfAbsent efficiently that would be any better
than the hash map you're already using.
