### ISSUE TITLE
Security scan reported problem with com.google.common.cache.Striped64

### ISSUE THREAD

**Issue by venusjain10** [google/guava#2574]
We are using google commons APIs in our project and security scan on our code has reported following problem. Could you please let me know if this is of any concern or it can be fixed in new version of this API.

**Problem:** Standard random number generators do not provide a sufficient amount of entropy when used for security purposes. Attackers can brute force the output of pseudorandom number generators such as rand().
**Recommendations (Generated by tool)**
If this random number is used where security is a concern, such as generating a session identifier or cryptographic key, use a trusted cryptographic random number generator instead

com.google.common.cache.Striped64

**Comment by lowasser** [comment]
No, this is not "used where security is a concern."

**Comment by abhisheksharma43** [comment]
Does that mean one should look for an Alternative API in case security is a concern for the project?

**Comment by lowasser** [comment]
In this case, no.  Even if security is a concern for your project, this API is fine; it's perfectly okay if the randomness is predictable or controllable.

**Comment by abhisheksharma43** [comment]
Can you provide some link that provides details information of randomness prediction and control?
I need to understand how do I make sure that the randomness is Controlled and predictable as I have not invoked the Striped64 class directly in my application code.

**Comment by lowasser** [comment]
I am not sure I follow.

You do not have to do anything.  Randomness is an optimization here.  The worst that can happen is hash collisions.

**Comment by abhisheksharma43** [comment]
And in case I am looking for optimized code, what is my option? The issue is that the code scan has reported it as a major problem.

**Comment by lowasser** [comment]
Not sure what you're asking here.  You don't need to do anything.  This is not a plausible attack vector.

The tool's advice is "If this random number is used where security is a concern, such as generating a session identifier or cryptographic key, use a trusted cryptographic random number generator instead."

This random number is not used where security is a concern.  There is nothing you need to do.

**Comment by abhisheksharma43** [comment]
I was just trying to confirm that the API internally does not use the class for security purposes. i understand that is not the case. Thanks for your help!
