### ISSUE TITLE
Security scan reported problem with com.google.common.io.Files

### ISSUE THREAD

**Issue by venusjain10** [google/guava#2576]
We are using Google Commons APIs in our project and security scan on our code has reported following problem. Could you please let me know if this is of any concern or it can be fixed in new version of this API.

**Problem:** The application fails to release (or incorrectly releases) a system resource before it is made available for re-use. This condition often occurs with resources such as database connections or file handles. Most unreleased resource issues result in general software reliability problems, but if an attacker can intentionally trigger a resource leak, it may be possible to launch a denial of service attack by depleting the resource pool.

**Recommendations (Generated by tool)**
When a resource is created or allocated, the developer is responsible for properly releasing the resource as well as accounting for all potential paths of expiration or invalidation. Ensure that all code paths properly release resources

Class:
com.google.common.io.Files

**Comment by lowasser** [comment]
This might be the case for a user of Files, but each method in Files should properly document its semantics and whether or not it closes the stream.  It's the user of the Files API who has the responsibility to deal with that correctly.

**Comment by lowasser** [comment]
Actually...let's check.  Is your tool any more specific about what part has the potential issue?

**Comment by abhisheksharma43** [comment]
This is the complete information that the tool provides.
It relates to improper closing of connections that are created in the class com.google.common.io.Files.

**Comment by lowasser** [comment]
I suspect the tool is just complaining that c.g.c.io.Files has helper methods to create new streams, including newReader and newWriter.  If there's a more specific issue, we can look into it, but I would expect this to be a false positive.

**Comment by smadasu** [comment]
After looking at the Files class, I came to a conclusion that java doc of Files should be updated to say that users of the API are responsible for closing resources. Secondly, I think the tool is reporting correctly since the class opens files but does not close them. So @venusjain10 , look at places where the Files API is used and check if the resources are closed properly and you should be OK. And for guava, someone should update the java doc.
