### ISSUE TITLE
Dispatcher with "yielding" behaviour makes EventBus more usable on UI threads

### ISSUE THREAD

**Issue by Groostav** [google/guava#2577]
Keeping the UI thread lively is a major concern for a developer of a desktop application.

The best strategy to do this is to perform major blocking workloads asynchronously and preferably on non-UI threads. This is easily implementable where the workloads are large and monolithic, concerning few UI components. It is more complex when the workload is faceted and concerns many UI elements. 

Specifically: using Guava's event bus to dispatch an event to roughly 10,000 subscribers that each perform nearly instantaneous workloads (or 1000 subscribers with moderate workloads) can cause a noticeable UI lag. This can be corrected by having each subscriber yield to later jobs on the UI thread between each job.

I've created [a little app](https://gist.github.com/Groostav/638e31d4cd2842aa2f05bd9f50c43156) to better demonstrate the problem and its potential fix (apologies for not making a proper SSCCE, I will if need be).

What I would like is a facility in Guava to make this happen at each subscribers invocation. An `onEventDispatchedTo(Object Event, Subscriber subscriber)` listener would do the trick, or the ability to register a custom `Dispatcher` --though I fear I wont be as careful as you in implementing thread-safe queuing. Similarly, some kind of `ExecutorProvider` would also suffice.

Specifically _it would be nice_ if I was given enough granularity to describe a rule like "yield the event queue between each subscriber dispatch only if the subscriber's class name matches `**Controller`", though a workable solution is simply to have this `yield()` method called between each subscriber invocation, regardless of context.

**Comment by Groostav** [comment]
The implementation of `yield` on JavaFX:

```Java
UUID key = UUID.randomUUID()

Platform.runLater(() -> {
  Toolkit.getToolkit().exitNestedEventLoop(key, null)
});

Toolkit.getToolkit().enterNestedEventLoop(key)
```

and on Swing:

```Java
SecondaryLoop loop = AWTToolkit.getDefaultToolkit().systemEventQueue.createSecondaryLoop()

SwingUtilities.invokeLater { 
  loop.exit()
}
        
loop.enter();
```

**Comment by cgdecker** [comment]
I'm closing this issue because we are no longer going to be making changes to `EventBus` other than important bug fixes. The reasons we're discouraging it and some alternatives are listed in the [EventBus javadoc](https://guava.dev/EventBus).
