### ISSUE TITLE
Release MoreFiles publicly

### ISSUE THREAD

**Issue by cpovirk** [google/guava#2585]
(with `RecursiveDeleteOption` and `InsecureRecursiveDeleteException`)

No rush, of course, but now that we're close to putting our Java 8 features out there, we can finally do the same for our Java 7 features :)

@cgdecker (but again, no rush)

I wonder if we have other Java-7-exclusive classes that we've been holding back? Probably few if any.

**Comment by jbduncan** [comment]
Ooh, really looking forward to this.

No pressure! :wink:
