### ISSUE TITLE
Presentation links under Learn about Guava don't work

### ISSUE THREAD

**Issue by mayankc89** [google/guava#2589]
The presentation links under Learn about Guava don't work.

```
Presentation slides focusing on base, primitives, and io  
Presentation slides focusing on cache  
Presentation slides focusing on util.concurrent
```

It'll be nice to fix the links to the correct path. :)

**Comment by kluever** [comment]
Those presentations are very out of date at this point, so I've just removed them.

For the record, here is what they *were*:

- [Presentation slides focusing on base, primitives, and io](http://guava-libraries.googlecode.com/files/Guava_for_Netflix_.pdf)
- [Presentation slides focusing on cache]( http://guava-libraries.googlecode.com/files/JavaCachingwithGuava.pdf)
- [Presentation slides focusing on util.concurrent](http://guava-libraries.googlecode.com/files/guava-concurrent-slides.pdf)
