### ISSUE TITLE
The example in documentation is wrong

### ISSUE THREAD

**Issue by odalay** [google/guava#2596]
The example ImmutableSet class is wrong. It should have been
`static final ImmutableSet<Color> GOOGLE_COLORS =
       ImmutableSet.Builder<Color>()
           .addAll(WEBSAFE_COLORS)
           .add(new Color(0, 191, 255))
           .build();`
   

Instead of

   `static final ImmutableSet<Color> GOOGLE_COLORS =
       ImmutableSet. <Color> builder()
           .addAll(WEBSAFE_COLORS)
           .add(new Color(0, 191, 255))
           .build();`

**Comment by ozriko** [comment]
I was wrong. Sorry for false alarm.
