### ISSUE TITLE
GWT compatibility

### ISSUE THREAD

**Issue by paulux84** [google/guava#2597]
last master commit GUAVA-GWT not work.
Gwt 2.8 compiler return the following error
`[ERROR] Errors in 'jar:file:/home/paolo/.m2/repository/com/google/guava/guava-gwt/20.0-SNAPSHOT/guava-gwt-20.0-20161005.174957-374.jar!/com/google/common/collect/ConsumingQueueIterator.java'
               [ERROR] Line 33: No source code is available for type java.util.ArrayDeque<E>; did you forget to inherit a required module?`

**Comment by cpovirk** [comment]
Which release candidate of GWT 2.8 are you using?

**Comment by paulux84** [comment]
2.8.0-rc3 and guava 20.0-rc1

**Comment by cpovirk** [comment]
Do you have a project you can reproduce this with that you can share? I've run some GWT tests that use `ConsumingQueueIterator` with GWT 2.8.0-rc3 and Guava 20.0-rc1, and they pass.

**Comment by paulux84** [comment]
All works with latest release
