### ISSUE TITLE
Quantiles.ScaleAndIndex doc comments have wrong return description

### ISSUE THREAD

**Issue by mjustin** [google/guava#2599]
The documentation for [Quantiles.ScaleAndIndex.computeInPlace()](https://google.github.io/guava/releases/snapshot/api/docs/com/google/common/math/Quantiles.ScaleAndIndex.html#computeInPlace%28double...%29) has the wrong description of the return value; from the other methods in the class, it looks like it should say "the quantile value", not "an unmodifiable map of results: the keys will be the specified quantile indexes, and the values the corresponding quantile values".

It looks like maybe this is a copy/paste error from copying this from [Quantiles.ScaleAndIndexes.computeInPlace()](https://google.github.io/guava/releases/snapshot/api/docs/com/google/common/math/Quantiles.ScaleAndIndexes.html#computeInPlace%28double...%29).

**Comment by ronshapiro** [comment]
@cpovirk is did your commit ae80b8a fix this? Or is there more to be done?

/cc @PeteGillinGoogle

**Comment by PeteGillinGoogle** [comment]
I think this is done, I'll let @cpovirk confirm.

**Comment by cpovirk** [comment]
Yep, thanks. I guess my "Fixes" line in the description didn't work.
