### ISSUE TITLE
Multimap remove does not use generic type information

### ISSUE THREAD

**Issue by danbress** [google/guava#2601]
The remove method on the Multimap interface accepts Object's rather than the types specified on the interface.  It should use K and V to preserve type safety.

```
public interface Multimap<K, V> {
  boolean remove(@Nullable Object key, @Nullable Object value);
}
```

**Comment by Bezier89** [comment]
This is per design, see e.g. Java's Set.remove() or Map.remove()

https://docs.oracle.com/javase/8/docs/api/java/util/Set.html#remove-java.lang.Object-

https://docs.oracle.com/javase/8/docs/api/java/util/Map.html#remove-java.lang.Object-
