### ISSUE TITLE
ByteArrayByteSource fails to ensure immutability

### ISSUE THREAD

**Issue by wfhartford** [google/guava#2603]
The `ByteArrayByteSource` implementation of `ByteSource` passes its internal array to objects provided by the user, thus allowing the user to modify the data within the `ByteSource`. This directly contradicts the `ByteSource` javadoc which claims that:

> it is an immutable _supplier_ of `InputStream` instances.

The following methods display this issue:
- `ByteArrayByteSource.copyTo(OutputStream)`
- `ByteArrayByteSource.read(ByteProcessor)`
- `ByteArrayByteSource.hash(HashFunction)`

This clearly involves unexpected implementations of the parameter objects. It should be noted that neither `OutputStream` nor `ByteProcessor` javadocs even suggest that input data should not be modified. `HashFunction` does indicate that implementations should be pure functions, and goes so far as to specify that input data should not be modified, however enforcing that is obviously not possible.

A sample class which demonstrates this issue is below:

``` java
public final class Main {
  public static void main(String[] args) throws IOException {
    final ByteSource byteSource = ByteSource.wrap(new byte[]{0, 0, 0, 0});
    byteSource.copyTo(new OutputStream() {
      @Override
      public void write(final byte[] buf, final int off, final int len) {
        for (int i = 0; i < buf.length; i++) {
          buf[i] = 2;
        }
      }

      @Override
      public void write(final int b) {
        throw new UnsupportedOperationException("write has not been implemented");
      }
    });
    System.out.println(Arrays.toString(byteSource.read()));
  }
}
```

**Comment by smadasu** [comment]
There is a fix possible by cloning the byte array while copying. I will submit a PR soon.

**Comment by cpovirk** [comment]
True, malicious (or careless) callers can mutate the array. We will probably not fix this, given that it doesn't seem to cause problems in practice. (Plus, fixing it would reduce performance.) We should probably document `ByteSource.wrap` and any other affected methods, though.

@cgdecker , what do you think?

**Comment by PhilippWendler** [comment]
Similar case is #1855, where internal arrays are also not guarded against malicious code.

**Comment by wfhartford** [comment]
An alternative to defensive copies would be to pass bytes to the recipient individually, though that would also incur a performance penalty.

I am in favour of simply adding some documentation to warn of potential misuse. The performance hit of a defensive copy would be frustrating.

**Comment by cgdecker** [comment]
I'm adding a note to the Javadoc.
