### ISSUE TITLE
Note about LoadingCache and eviction

### ISSUE THREAD

**Issue by 0cd** [google/guava#2606]
https://github.com/google/guava/wiki/CachesExplained has a line that says 
"In some cases a LoadingCache can be useful even if it doesn't evict entries, due to its automatic cache loading"

This could give an incorrect initial impression that LoadingCache doesn't support evicting entries. 

It might be better to say

"In some cases a LoadingCache can be useful even when it doesn't evict entries, due to its automatic cache loading"

or 

"In some cases a LoadingCache can be useful even if it is configured to not evict entries, due to its automatic cache loading"

**Comment by cgdecker** [comment]
I don't feel like the current wording is particularly confusing, so I'm just going to leave it as-is.
