### ISSUE TITLE
Function.equals has invalid javadoc tag: {@object}

### ISSUE THREAD

**Issue by michaelhixson** [google/guava#2610]
The javadoc for Function.equals has an invalid `{@object}` tag in the first sentence:

```
/**
 * <i>May</i> return {@code true} if {@object} is a {@code Function} that behaves identically to
 * this function.
 *
```

I'm sure that was supposed to be `{@code object}`.  As it is now, the word "object" does not appear in the rendered javadocs and it reads like "May return true if is a Function that..."

The same issue exists in the javadocs of a few non-public APIs, in case you want to fix them:

* `{@from}` in InternetDomainName.validateSyntax
* `{@count}` in PairedStats constructor
* `{@requiredTo}` in Quantiles.chooseNextSelection

**Comment by cpovirk** [comment]
Thanks.
