### ISSUE TITLE
Guava-gwt 20.0 complains about missing annotations

### ISSUE THREAD

**Issue by ciaccia** [google/guava#2622]
Hi all,
I have just downloaded GWT 2.8.0 and guava-20.0 + guava-gwt-20.0.

I added 
```
<inherits name='com.google.common.base.Base'/>
<inherits name="com.google.common.collect.Collect"/>
```
to my .gwt.xml file and the jar file in the ant gwtc classpath. Then I cleaned the gwt-unitCache and I enabled the DEBUG logging in the ant `com.google.gwt.dev.Compiler` target.

```
<target name="gwtc" description="GWT compile to JavaScript (production mode)">
    <java failonerror="true" fork="true" classname="com.google.gwt.dev.Compiler" maxmemory="512m">
      <classpath>
        <pathelement location="src"/>
        <path refid="project.class.path"/>
      </classpath>
      <!--arg line="-strict"/-->
      <arg line="-war"/>
      <arg value="war"/>
      <!-- Additional arguments like -style PRETTY or -logLevel DEBUG -->
      <arg line="-logLevel"/>
      <arg value="DEBUG"/>
      <arg line="${gwt.args}"/>
      <arg value="com.mycompany.mywebapp.MyWebApp"/>
    </java>
  </target>
```

When processing Guava-GWT Java files, the processor complains about missing annotations:

> Line 20: The import com.google.errorprone cannot be resolved
> Line 23: The import com.google.j2objc cannot be resolved

Also adding `<inherits name='java.lang.Lang'/>` to the module definition does not help ([see this stackoverflow topic](http://stackoverflow.com/questions/40360901/gwt-2-8-throws-exception-when-compiling-with-guava-20))

Could it be that latest Guava-GWT 20.0 jar was not packed with all the needed sources?

**Comment by cpovirk** [comment]
Guava-GWT specifies the transitive dependencies it needs in its Maven pom file. If you're manually providing your dependencies, you'll need to include some additional jars. See [here](https://github.com/google/guava/blob/v20.0/pom.xml#L202) and [here](https://github.com/google/guava/blob/v20.0/guava-gwt/pom.xml#L49).

For the two particular errors you're seeing, you can download [error_prone_annotation](http://repo1.maven.org/maven2/com/google/errorprone/error_prone_annotation/2.0.14/) and [j2objc-annotations](http://repo1.maven.org/maven2/com/google/j2objc/j2objc-annotations/1.1/).
