### ISSUE TITLE
Feature request: Utility class in common.graph to visualize graph with GraphWiz notation 

### ISSUE THREAD

**Issue by kronar** [google/guava#2631]
Quite simple and will provide at least some capabilities for visualization

**Comment by jrtom** [comment]
I think that we're unlikely to add visualization capabilities to common.graph, but I'm in the process of porting [JUNG ](http://jrtom.github.io/jung/) to use common.graph as its data model, so please feel free to file a feature request against JUNG for that.

**Comment by liach** [comment]
Guava is a commonly used library, which nearly all of its users do not need this feature. After all, this feature should instead be done in a separate project at best.
