### ISSUE TITLE
GWT Serialization of Guava ImmutableLists problematic

### ISSUE THREAD

**Issue by pdemarino** [google/guava#2633]
Hi all -

I'm experiencing a problem serializing ImmutableLists in GWT. More specifically, the issue I stumbled upon is:

`[INFO] com.google.gwt.user.client.rpc.SerializationException: Type 'com.google.common.collect.SingletonImmutableList' was not included in the set of types which can be serialized by this SerializationPolicy or its Class object could not be loaded. For security purposes, this type will not be serialized.: instance = ...
`
The culprit is an object that contains an ImmutableList with a single object embedded.

Does the serialization test suite include coverage for singletons?

Thanks,
Paolo

**Comment by cpovirk** [comment]
We do test this but only internally, so it's always possible that something went wrong externally.

Is the `ImmutableList` stored in a `final` field in the object you're serializing? If so, GWT won't be able to recognize that it is serialized. I can try to find some docs on this and give some suggestions if that's what's going on.

**Comment by ronshapiro** [comment]
I'm closing this issue as we don't have enough info to properly address it. If you respond back, we can reopen.
