### ISSUE TITLE
BaseEncoding BASE64_URL wrong default padding character

### ISSUE THREAD

**Issue by sedrakpc** [google/guava#2643]
Why for BaseEncoding.base64Url() padding character is '**=**'? In javascript google libraries like:https://github.com/google/closure-library/blob/master/closure/goog/crypt/base64.js padding character is '**.**'. It should be url safe, but '**=**' is a URL reserved character. I think it's easy to get confused, better to force client specify padding character manually.

**Comment by lowasser** [comment]
The BaseEncoding class follows [RFC 4648](https://tools.ietf.org/html/rfc4648) as specified in its Javadoc, and that specifies the '=' padding.

That said, I'm not sure this is something we could realistically change at an API level at this point?  BaseEncoding doesn't appear marked `@Beta`, and this seems like something that would be difficult to transition smoothly in open source.
