### ISSUE TITLE
Graph is not serializable and does not be represented as a json if required

### ISSUE THREAD

**Issue by tarushgpb** [google/guava#2645]
Hi I have a requirement to save or pass it my graph as json to other apis but what I am seeing is graph interfaces are not serializable so any new update has been coming up relating to this requirement. Can you help me in how I can export it as a json.

**Comment by jrtom** [comment]
We generally prefer to avoid implementing Serializable in our interfaces (see Effective Java Item 74 for some reasons why).  

Can you tell us more about what you're trying to accomplish, and whether you're targeting JSON or Java?  It may make more sense for you to do your own serialization and deserialization.

**Comment by tarushgpb** [comment]
Yes I was targeting JSON. It was in my mind to do serialization & deserialization my own but thought to discuss it once with the community.

Thanks alot.

**Comment by jrtom** [comment]
@tarushgpb OK, thanks for the update.  Closing this issue.
