### ISSUE TITLE
Bad errorprone annotations dependency for GWT?

### ISSUE THREAD

**Issue by jnehlmeier** [google/guava#2646]
Guava 20 depends on error prone annotations 2.0.12 which requires Java8. 

However GWT 2.8 still allows Java7 to be used as JVM even tough internally it compiles using JDT and source level 1.8. When using Java 7 + GWT 2.8 + guava-20-gwt you get an unsupported major.minor version 52.0 error when GWT tries to load an error prone annotation from classpath.

In terms of GWT support I think the latest version of error prone annotations you should depend on is 2.0.5 as its the last version build for Java7.

**Comment by jnehlmeier** [comment]
Looks like Guava can not use error prone annotations 2.0.5 as it does not contain LazyInit annotation. So I rebuild error prone annotations 2.0.14 using Java7 which fixes the GWT issue.

**Comment by cpovirk** [comment]
Thanks for reporting this. I've filed https://github.com/google/error-prone/issues/480 to see if we can get Error Prone to build newer versions of its annotation package to be compatible with Java 7.

In the meantime, people should let us know how big a problem this is. We'll add it to the list with your other bug report (#2638) for possible reasons to do a 20.0.1.

**Comment by cpovirk** [comment]
We upgraded `error_prone_annotations` from 2.0.12 to 2.0.15 in https://github.com/google/guava/commit/f81aa2d4ebdd92d2594989eabce878b60327e8a4

However, as best I can tell, 20.0.12 was compatible with Java 7:

    $ JAR=Downloads/error_prone_annotations-2.0.12.jar; for F in `jar -tf $JAR | grep '[.]class$' | a .class 1`; do javap -v -cp $JAR $F; done | grep 'major version' | sort -u
      major version: 51

Now 20.0.13 and 20.0.14 required Java 8, but we don't seem to be depending on them. Do you think there's any way that you could be depending on another version somewhere?

**Comment by jnehlmeier** [comment]
Hmm good question, already a few days ago. I think there is probably a chance that I have used 2.0.14. 

At least I am sure that I did a google search after seeing the error and found https://github.com/google/error-prone/issues/369 . So I thought all versions above 2.0.5 had been built with Java8 and would cause the error.

**Comment by cpovirk** [comment]
Tentatively closing, since I think 2.0.12 was OK, and 20.0.15 should be, as well.
