### ISSUE TITLE
Proposition of new component: Pivot Table

### ISSUE THREAD

**Issue by vbalrog** [google/guava#2647]
For the purpose of work, two colleagues of mine and me we needed a kind of table commonly used in banking and accounting world, a data matrix, a pivot table. So as it doesn't exist already we wrote one in using Java and Guava classes. 

I made a jar application example about how to use it, and with the sources to use it as you want, and also important with documentations (in documentation folder) to explain how to use it, and how it is made. 
[https://drive.google.com/open?id=0B1b5SqhpAYsTNlBOQXlMT1ZMajA](https://drive.google.com/open?id=0B1b5SqhpAYsTNlBOQXlMT1ZMajA)

I hope it can help other developers needed this component, and better, with the appropiated modifications it can need, be one of the many and great Guava component  ;)

**Comment by jbduncan** [comment]
It seems the link is out of date. :)

**Comment by liach** [comment]
@jbduncan [The drive is okay.](https://drive.google.com/file/d/0B1b5SqhpAYsTNlBOQXlMT1ZMajA/view) It is just because the blue link is directing to an invalid url, but the text is the true url.

**Comment by vbalrog** [comment]
Sorry, I fixed the link. Let's use it !

**Comment by cgdecker** [comment]
If you want to propose a new API, please make the proposal in the issue here on GitHub with a description of what it is you want and how you think it should work rather than linking to an external zip file. I'm going to close this, but feel free to reopen if you do that.
