### ISSUE TITLE
symlink cycles create failures in ClassPath scan

### ISSUE THREAD

**Issue by jct-amzn** [google/guava#2648]
Starting in at least r19, https://google.github.io/guava/releases/19.0/api/docs/com/google/common/reflect/ClassPath.html will eagerly traverse circular symlinks during the ClassPath scan.

Depending on the host platform and JVM settings, this can lead to OutOfMemoryError, StackOverflowError, or (depending on the depth limits in underlying file system) inconsistent resource listings.

The symlink cycle doesn't have to occur in the actual class path.  ClassPath  eagerly scans the Class-Path attribute in the manifests of any encountered jars.  So relative paths encountered there, or an empty Class-Path attribute value, causes recursive scans of arbitrary file system paths.

I do have a failing test case and candidate fix prepared.  I can submit a pull request for that, but wanted to file a bug report first, since the "correct" behavior is a little ambiguous in this case.

**Comment by cgdecker** [comment]
Looks like this was fixed by 7c11b8d9220b710d5598b774e22cc774f68f40e7.
