### ISSUE TITLE
Graph: implement Serializable

### ISSUE THREAD

**Issue by mfulton26** [google/guava#2651]
Can support be added to the new graph package classes to support `java.io.Serializable`?

**Comment by kluever** [comment]
We just discussed this in https://github.com/google/guava/issues/2645, where @jrtom asked:

> We generally prefer to avoid implementing Serializable in our interfaces (see Effective Java Item 74 for some reasons why).

> Can you tell us more about what you're trying to accomplish? It may make more sense for you to do your own serialization and deserialization.

**Comment by mfulton26** [comment]
Yes, sorry, to clarify I am more interested in `ImmutableGraph` implementing `Serializable` so that I can easily persist graphs to use in later executions of my software. I might persist it in a database or simply as a file on a file system but ultimately I want to be able to run a process multiple times, each run generates a graph, some time later I will run it again and I'll then want to compare graphs from previous runs with the new runs.

I could create my own serialization and deserialization code for it but it would be nice to be able to simply cache it and retrieve it later.

**Comment by cpovirk** [comment]
Thanks. If you want to persist the data for multiple runs, you might want to avoid Java serialization, since Guava doesn't promise to keep serialized forms from one Guava version readable in the next (https://github.com/google/guava#important-warnings).

**Comment by mfulton26** [comment]
Hm, interesting note, thank you @cpovirk. I suppose if I changed versions then I would need to deserialize my entities with the previous version and then reserailize it with the new version; probably best to avoid it then and roll my own.

Out of curisoity, why does `ImmutableTable` and various other collection implementations in Guava implement `Serializable`?

**Comment by cpovirk** [comment]
We have been inconsistent in deciding when to make something `Serializable`, it's true. Part of the story is that we implemented `Serializable` more frequently in the past, before we really caught on to the many problems of Java serialization. Another part is that we ended up adding it later, anyway, in places where we got requests. I'm not sure what the takeaway is here. "Maybe we'll do it if we get enough demand, but I have no idea?" :)

**Comment by jrtom** [comment]
I would strongly suggest that you do your own serialization/deserialization code.  Or wait (hopefully no more than a couple of months) until [JUNG](jrtom.github.io/jung) is re-released using common.graph as its data model, at which point you'll have at least a couple of different I/O options available.  Serialization is not particularly difficult if you're only trying to maintain the topology; it gets messier when you want to serialize/deserialize element and graph data as well.

**Comment by mfulton26** [comment]
Sounds good. I will do my own for now and watch for a JUNG update as well. Thank you.

P.S. I know some tools like Common JCS and/or Hibernate require some entities to implement `Serializable` but that isn't currently my use case.

**Comment by mfulton26** [comment]
@jrtom Is a JUNG re-release still in the works?

**Comment by jrtom** [comment]
@mfulton26 Yes, I'm actively working on a JUNG re-release, but the migration process is taking longer than I'd hoped (in part because I'm fixing some other issues in the process, and in part because I've recently transferred to a new team at Google and am still ramping up).

You can watch the progress of the JUNG migration on the [common.graph branch](https://github.com/jrtom/jung/tree/common.graph).

**Comment by jrtom** [comment]
Calling this issue closed for now, as it's not something that we anticipate doing in Guava for common.graph.  

JUNG 3.0 still isn't released, but we've made a lot of progress on the common.graph branch and we hope to at least merge it back into master soon, to make it more visible.
