### ISSUE TITLE
duplicate entry: zip exception

### ISSUE THREAD

**Issue by oskarko** [google/guava#2654]
I need to use guava and I must to use google maps m4b (premium), but I get the next error:

Error:Execution failed for task ':app:transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/google/common/base/FinalizableReference.class

this is here too: https://code.google.com/p/gmaps-api-issues/issues/detail?id=10246

any solution?

**Comment by ronshapiro** [comment]
Try filing an issue there? Doesn't seem to be a Guava issue on face value

**Comment by kurcano** [comment]
compile ('com.google.dagger:dagger:2.4') {
        exclude group: 'com.google.guava'
    }
