### ISSUE TITLE
Make a tool that checks at compilation that no Beta functionality is used

### ISSUE THREAD

**Issue by ogregoire** [google/guava#2657]
In order to minimize the risk of integrating `@Beta`-annotated functionalities (especially in libraries), it might be nice to have a tool that we integrate in the compilation process and that produces warnings when a `@Beta`-annotated functionality is used.

I see this as an external Maven artefact that we include if we want to use such functionality, a bit like the tools that generate utilities during the compilation like Dagger or AutoValue.

Hopefully, this is possible without having to change `@Beta`'s retention policy from class to source. I don't really know the arcanes of the compiler so I can't really say...

**Comment by kluever** [comment]
We have one of these internally, but we need to open source it.

**Comment by cgdecker** [comment]
This is finally in the process of being open-sourced, at [google/guava-beta-checker](https://github.com/google/guava-beta-checker).
