### ISSUE TITLE
remove() in MinMaxPriorityQueue<Double> not removing the correct object

### ISSUE THREAD

**Issue by forestier** [google/guava#2658]
A MinMaxPriorityQueue fails at removing the correct object after a series of operations. See output and code below.

> [5.6, 6.0, 5.7, 5.9]
Try to remove 5.7 :
[5.6, 6.0, 5.7]

Obtained from :

> MinMaxPriorityQueue<Double> values = MinMaxPriorityQueue.create();
			values.add(6.2);
			values.pollLast();
			values.add(6.1);
			values.add(6.2);
			values.pollFirst();
			values.add(6.3);
			values.add(6.1);
			values.pollLast();
			values.add(5.1);
			values.pollLast();
			values.add(5.7);
			values.pollFirst();
			values.add(5.5);
			values.pollFirst();
			values.add(6.2);
			values.add(6.3);
			values.pollLast();
			values.add(5.5);
			values.pollLast();
			values.add(5.5);
			values.pollFirst();
			values.add(5.6);
			values.pollFirst();
			values.add(6.2);
			values.pollFirst();
			values.add(5.8);
			values.pollFirst();
			values.add(6.0);
			values.remove(6.2);
			values.add(5.7);
			values.add(5.6);
			values.pollLast();
			values.pollFirst();
			values.add(5.8);
			values.add(5.7);
			values.pollLast();
			values.add(6.0);
			values.pollFirst();
			values.add(6.3);
			values.pollFirst();
			values.pollFirst();
			values.add(6.1);
			values.add(6.4);
			values.pollFirst();
			values.add(5.8);
			values.pollLast();
			values.add(6.4);
			values.pollFirst();
			values.remove(6.3);
			values.add(5.8);
			values.remove(5.8);
			values.add(6.4);
			values.remove(6.0);
			values.add(5.8);
			values.pollFirst();
			values.add(6.3);
			values.pollLast();
			values.add(6.3);
			values.add(5.8);
			values.pollLast();
			values.add(5.5);
			values.pollLast();
			values.pollLast();
			values.add(5.4);
			values.remove(5.4);
			values.add(5.7);
			values.remove(6.1);
			values.add(5.6);
			values.add(5.4);
			values.pollLast();
			values.remove(5.5);
			values.add(5.8);
			values.pollLast();
			values.add(5.6);
			values.add(5.8);
			values.pollFirst();
			values.add(5.8);
			values.pollFirst();
			values.add(5.6);
			values.pollLast();
			values.add(5.8);
			values.pollFirst();
			values.add(5.6);
			values.pollLast();
			values.add(5.8);
			values.pollFirst();
			values.remove(5.8);
			values.add(5.6);
			values.add(6.0);
			values.pollFirst();
			values.pollFirst();
			values.add(5.7);
			values.add(6.0);
			values.pollFirst();
			values.remove(5.7);
			values.add(6.1);
			values.pollLast();
			values.add(5.9);
			values.pollFirst();
			values.add(6.1);
			values.pollFirst();
			values.add(6.1);
			values.add(6.1);
			values.pollFirst();
			values.remove(6.1);
			values.add(6.0);
			values.add(6.0);
			values.pollLast();
			values.remove(6.0);
			values.add(5.9);
			values.remove(6.0);
			values.add(5.7);
			values.add(5.6);
			values.pollLast();
			values.add(6.1);
			values.pollFirst();
			values.add(5.6);
			values.pollLast();
			System.out.println(values);
			System.out.println("Try to remove 5.7 :");
			values.remove(5.7);
			System.out.println(values);

**Comment by perceptron8** [comment]
Same here!

Output:

```
[0, 3, 1, 2]
Try to remove 1:
[0, 3, 1]
```

Source:

```
MinMaxPriorityQueue<Long> values = MinMaxPriorityQueue.create();
values.add(2L);
values.add(3L);
values.add(4L);
values.add(0L);
values.add(1L);
values.pollLast();
System.out.println(values);
System.out.println("Try to remove 1:");
values.remove(1L);
System.out.println(values);
```

**Comment by pong22077** [comment]
Ridx511ask@pong27runner.exmple.onmicrosoft.com

**Comment by kluever** [comment]
Yikes, this does seem like a bug. Thanks for the report @forestier and for the simple repo case @perceptron8 !

    MinMaxPriorityQueue<Long> values = MinMaxPriorityQueue.create(asList(2L, 3L, 0L, 4L, 1L));
    System.out.println("toString():   " + values);
    System.out.println("remove(4L):   " + values.remove(4L));
    System.out.println("toString():   " + values);
    System.out.println("remove(1L):   " + values.remove(1L));
    System.out.println("contains(1L): " + values.contains(1L));
    System.out.println("toString():   " + values);
    System.out.println("remove(1L):   " + values.remove(1L));
    System.out.println("contains(1L): " + values.contains(1L));
    System.out.println("toString():   " + values);

Yields:

    toString():   [0, 3, 4, 2, 1]
    remove(4L):   true
    toString():   [0, 3, 1, 2]
    remove(1L):   true
    contains(1L): true
    toString():   [0, 3, 1]
    remove(1L):   true
    contains(1L): false
    toString():   [0, 3]

**Comment by kluever** [comment]
@Bezier89 found the bug and has a fix for it, which is under review now. Thanks again for the report!

**Comment by forestier** [comment]
Thanks for the quick fix!
