### ISSUE TITLE
ImmutableSortedSet.construct(...) can include bug in method

### ISSUE THREAD

**Issue by MrNikita** [google/guava#2659]
Hi, guys! I have some problem with method construct in ImmutableSortedSet class, cause I've received every time n-1 elements after build ImmutableSortedSet.

I found that this part of code can include a bug:
```
for (int i = 1; i < n; i++) {
      E cur = contents[i];
      E prev = contents[uniques - 1];
      if (comparator.compare(cur, prev) != 0) {
        contents[uniques++] = cur;
      }
    }
```
Why you not process the last one element? I mean this:
`for (int i = 1; i < n; i++)`

**Comment by lowasser** [comment]
I'm not sure what you mean.  contents already includes all elements of the set, and the first element is definitely staying in; this is the deduplication phase, where we only need to check each element against its predecessor.

Could you provide a reproduction test case for returning n-1 elements?

**Comment by MrNikita** [comment]
![1](https://cloud.githubusercontent.com/assets/11968111/20677455/71fcaaa6-b593-11e6-9ee6-b8513a88dc59.png)
![2](https://cloud.githubusercontent.com/assets/11968111/20677467/7b6c4b0a-b593-11e6-96f7-2f2ff97a71a8.png)

**Comment by jbduncan** [comment]
Hi @MrNikita, are you trying to show us in your screenshots above that the element at index 2 (which starts off as "CC-third") is somehow being overwritten with "AA-last", which you believe to be erroneous behaviour?

**Comment by lowasser** [comment]
Based on that behavior I would conclude that BB-second.compareTo(CC-third)
== 0.  Can you show us the details and implementation of that comparison?

**Comment by MrNikita** [comment]
@jbduncan yes, this behavior is result of overriding "E... contents" parameter inside this method, here: 
 ```
if (comparator.compare(cur, prev) != 0) {
        contents[uniques++] = cur;
}
```

That's why one of these elements in "E... contents" array disappeared (was rewrites with the previous element) :)

**Comment by MrNikita** [comment]
@lowasser , here is comparing of these objects:

![screen shot 2016-11-28 at 20 17 00](https://cloud.githubusercontent.com/assets/11968111/20682353/f39ab40e-b5a7-11e6-86cd-94c0902f5481.png)

**Comment by lowasser** [comment]
It's not clear what the implementation of compareTo for these objects is?

**Comment by MrNikita** [comment]
Its compare of "BB-second" and "CC-third" objects:

` if (comparator.compare(cur, prev) != 0) `

![screen shot 2016-11-28 at 20 39 04](https://cloud.githubusercontent.com/assets/11968111/20683025/c02ae64a-b5aa-11e6-87d6-0388f0d439d7.png)

**Comment by lowasser** [comment]
That doesn't answer the question: what is the implementation of the
compareTo method in the RolledSectionRectangularData class?

**Comment by lowasser** [comment]
That is, I want to see the body of the method with the signature int compareTo(RolledSectionRectangularData).

**Comment by MrNikita** [comment]
This is Kotlin:
```
override fun compareTo(other: RolledSectionRectangularData): Int {
        val keyCmp = compareSortKeyTo(other)
        return if (keyCmp != 0) keyCmp
        else priority.compareTo(other.priority)
    }

    protected fun compareSortKeyTo(other: NamedInfo): Int {
        return Integer.compare(priority, other.priority)
    }
```

**Comment by lowasser** [comment]
Your earlier screenshot did not show the priority field for BB-second; could you show us that please?

**Comment by MrNikita** [comment]
![screen shot 2016-11-28 at 21 06 27](https://cloud.githubusercontent.com/assets/11968111/20684034/94bfa5e6-b5ae-11e6-9921-a041b6b19f44.png)

**Comment by lowasser** [comment]
Thank you.

The debug info you've shown shows that BB-second.priority == CC-third.priority.  So BB-second.compareTo(CC-third) will return zero, based on the implementation you've shown us.

ImmutableSortedSet, like TreeSet, eliminates duplicate elements when they compare as equal, which is the case here based on the information you've given us.  TreeSet would do exactly the same thing.  

ImmutableSortedSet is doing exactly what it's supposed to based on the information you've given us.

**Comment by MrNikita** [comment]
Yes, guys, you're right! Thank u a lot for help me with it.
