### ISSUE TITLE
Allow throw exception in eventbus subscriber

### ISSUE THREAD

**Issue by TimYi** [google/guava#2660]
In a database application, transaction support is an important feature.
In some condition, if subscriber throws exception, we'll want the whole transaction roll back, and stop event processing. So allow throw exception in eventbus is a useful feature.
We override handleSubscriberException in our sub type, the package is under com.google.common.eventbus so this method is visible.
```
 /**
  * Just throw a EventHandleException if there's any exception.
  * @param e
  * @param context
 * @throws EventHandleException 
 */
@Override
protected void handleSubscriberException(Throwable e, SubscriberExceptionContext context)
        throws EventHandleException {
    throw new EventHandleException(e);
}
```
I think guava eventbus can just allow throw exception in `SubscriberExceptionHandler` and not catch it.
Now there's no method to throw exception and stop event processing.
```
try {
      exceptionHandler.handleException(e, context);
  } catch (Throwable e2) {
      // if the handler threw an exception... well, just log it
      logger.log(
          Level.SEVERE,
          String.format(Locale.ROOT, "Exception %s thrown while handling exception: %s", e2, e),
          e2);
 }
```
What about add an runtime exception type in guava eventbus package, If SubscriberExceptionHandler throws such exception, then just let throw?

**Comment by TimYi** [comment]
I find another question about this, they also inherit EventBus and override handleSubscriberException method.
http://stackoverflow.com/questions/37130746/bring-up-exceptions-in-google-guava-eventbus

**Comment by hemaodong** [comment]
U can do like this :

```java 
@Component
public class EventBusExceptionHandler implements SubscriberExceptionHandler {

    public static final ThreadLocal<Exception> EVENT_BUS_EXCEPTION_HOLDER = new ThreadLocal<>();

    @SuppressWarnings("NullableProblems")
    @Override
    public void handleException(Throwable exception, SubscriberExceptionContext context) {
        EVENT_BUS_EXCEPTION_HOLDER.remove();
        if (exception instanceof BusinessException) {
            EVENT_BUS_EXCEPTION_HOLDER.set(new BusinessException(((BusinessException)exception).getErrorMessage()));
        } else {
            EVENT_BUS_EXCEPTION_HOLDER.set(new RuntimeException(exception));
        }
    }
}

@Slf4j
@Aspect
@Component
public class AroundClientAspect {

    @Around("execution(com.xxx.client.*.*(..))")
    public Object aroundClient(ProceedingJoinPoint call) throws Throwable {
        MethodSignature signature = (MethodSignature)call.getSignature();
        log.info("service called, method={}, args={}", signature.getMethod(), call.getArgs());
        try {
            if (null != EventBusExceptionHandler.EVENT_BUS_EXCEPTION_HOLDER.get()) {
                throw EventBusExceptionHandler.EVENT_BUS_EXCEPTION_HOLDER.get();
            }
            return result;
        } catch (Exception e) {
            log.error("service system error, method={}, args={}", signature.getName(), call.getArgs(), e);
            TransactionAspectSupport.currentTransactionStatus().setRollbackOnly();

            ResultDTO resultDTO = (ResultDTO)signature.getReturnType().newInstance();
            resultDTO.setSuccess(false);
            resultDTO.setErrorCode(ErrorCodeEnum.SYSTEM_ERROR.name());
            resultDTO.setErrorMessage(ErrorCodeEnum.SYSTEM_ERROR.getMessage());

            return resultDTO;
        } finally {
            EventBusExceptionHandler.EVENT_BUS_EXCEPTION_HOLDER.remove();
        }
    }
}
`

**Comment by yuxiaoyi24** [comment]
> U can do like this :
> 
> ```java
> @Component
> public class EventBusExceptionHandler implements SubscriberExceptionHandler {
> 
>     public static final ThreadLocal<Exception> EVENT_BUS_EXCEPTION_HOLDER = new ThreadLocal<>();
> 
>     @SuppressWarnings("NullableProblems")
>     @Override
>     public void handleException(Throwable exception, SubscriberExceptionContext context) {
>         EVENT_BUS_EXCEPTION_HOLDER.remove();
>         if (exception instanceof BusinessException) {
>             EVENT_BUS_EXCEPTION_HOLDER.set(new BusinessException(((BusinessException)exception).getErrorMessage()));
>         } else {
>             EVENT_BUS_EXCEPTION_HOLDER.set(new RuntimeException(exception));
>         }
>     }
> }
> 
> @Slf4j
> @Aspect
> @Component
> public class AroundClientAspect {
> 
>     @Around("execution(com.xxx.client.*.*(..))")
>     public Object aroundClient(ProceedingJoinPoint call) throws Throwable {
>         MethodSignature signature = (MethodSignature)call.getSignature();
>         log.info("service called, method={}, args={}", signature.getMethod(), call.getArgs());
>         try {
>             if (null != EventBusExceptionHandler.EVENT_BUS_EXCEPTION_HOLDER.get()) {
>                 throw EventBusExceptionHandler.EVENT_BUS_EXCEPTION_HOLDER.get();
>             }
>             return result;
>         } catch (Exception e) {
>             log.error("service system error, method={}, args={}", signature.getName(), call.getArgs(), e);
>             TransactionAspectSupport.currentTransactionStatus().setRollbackOnly();
> 
>             ResultDTO resultDTO = (ResultDTO)signature.getReturnType().newInstance();
>             resultDTO.setSuccess(false);
>             resultDTO.setErrorCode(ErrorCodeEnum.SYSTEM_ERROR.name());
>             resultDTO.setErrorMessage(ErrorCodeEnum.SYSTEM_ERROR.getMessage());
> 
>             return resultDTO;
>         } finally {
>             EventBusExceptionHandler.EVENT_BUS_EXCEPTION_HOLDER.remove();
>         }
>     }
> }
> ```

aop not work!!

**Comment by cgdecker** [comment]
I'm closing this issue because we are no longer going to be making changes to `EventBus` other than important bug fixes. The reasons we're discouraging it and some alternatives are listed in the [EventBus javadoc](https://guava.dev/EventBus).
