### ISSUE TITLE
No public generic impl of Map.Entry in guava

### ISSUE THREAD

**Issue by guai** [google/guava#2661]
guava have several entry impls, but they either private or nongeneric
Joiner in some methods expects the iterator of entries
So I didn't find anything suitable for code like this:
`Joiner.on(", ").withKeyValueSeparator("=").join(Iterators.transform(myIterator, key -> new SomeEntryImpl<>(key, some_transformation(key))));`
Creating a real map may not be desirable because keys may not be unique.

**Comment by tomaszalusky** [comment]
Maps.immutableEntry(K,V) ?

**Comment by ben-manes** [comment]
Java provides SimpleEntry and SimpleImmutableEntry as well.

**Comment by guai** [comment]
ok. closing then
Thanks guys
I've searched for something suitable but found only org.apache.commons.lang3.tuple.Pair which gives me another dopendency
