### ISSUE TITLE
Provide a way to coalesce the entries in a RangeMap

### ISSUE THREAD

**Issue by dimo414** [google/guava#2665]
`RangeMap` doesn't coalesce connected ranges (by design), and it would be nice if there were a built-in way to coalesce connected ranges if they have the same value. For example:

    {[0..1): 1, [1..2): 1, [2..3): 2}

Is roughly equivalent to:

    {[0..2): 1, [2..3): 2}

And it can be both a time and space savings to be working with a smaller data structure. Particularly for a case such as a `RangeMap` built up from `Range.singleton()` keys a `coalesced()` operation could save a lot of resources.

**Comment by lowasser** [comment]
Could you live with a `RangeMaps.coalesced` operation, that is, a one-off coalesce operation rather than doing it online?

**Comment by dimo414** [comment]
Definitely; I'd expect it to be a copy operation as a live view would eliminate the benefit of reducing the underlying number of ranges in use (and probably be much more complex to implement). `ImmutableRangeMap.coalescedFrom(RangeMap)` could also work.

**Comment by dimo414** [comment]
We opted to add a mutating `.putCoalescing()` operation rather than a copy or a view. Please let us know if you have a use case for which this isn't sufficient.

**Comment by perceptron8** [comment]
@dimo414 I'd like to report "merging + coalescing" as a general use case, that `.putCoalescing` doesn't support at all. I think that `.coalesced()` (or similarly named) method could work nicely with #6822, or at least as a way to "clean-up" after series of `RangeMap.merge` calls (see #3641 for details if you like).
