### ISSUE TITLE
HashMultiset, count() and equals()?

### ISSUE THREAD

**Issue by nirsoffer** [google/guava#2670]
Perhaps I'm going crazy and doing something incredibly stupid, but my understanding is that the attached code should output 2, and at some point call TestObject.equals; it returns 0 and seems to never even call my defined equals() method. Everything in the specs that I read says that's how it should work, so either the doc is unclear or something is funky. Needless to say calling Objects.equal(new TestObject(7), new TestObject(7)) returns true. Additionally, Collections.frequency(ms, new TestObject(7)) returns 2, as it should. I was under the understanding they should return the same thing?

Guava version is 20.0.

is this expected behavior?
`
package ExcelMLTesters;

import com.google.common.collect.HashBasedTable;
import com.google.common.collect.HashMultiset;
import com.google.common.collect.Multiset;
import com.google.common.collect.Table;

import java.util.Objects;

public class GuavaTableTester {

    private static class TestObject {
        private int val;

        @Override
        public boolean equals(Object obj) {
            System.out.println("I'm comparing "+ this.toString() +"  and " + obj.toString());

            if (obj instanceof TestObject)
                return this.val == ((TestObject)obj).val;

            return false;
        }

        public int getVal() {
            return val;
        }

        public void setVal(int val) {
            this.val = val;
        }

        public TestObject(int val) {
            this.val = val;
        }

        @Override
        public String toString() {
            return "TestObject{" +
                    "val=" + val +
                    '}';
        }
    }
	public GuavaTableTester() {
		// TODO Auto-generated constructor stub
	}

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		Table table = HashBasedTable.create();

		table.put("a", 1, new TestObject(5));
		table.put("a", 3, new TestObject(3));
        table.put("b", 1, new TestObject(7));
        table.put("c", 1, new TestObject(7));
        table.put("d", 1, 1);
        table.put("e", 1,1);

        Multiset ms = HashMultiset.create(table.column(1).values());

        // Call me crazy, but shouldn't this output 2 and call TestObject.equals() at some point?
        System.out.println(ms.count(new TestObject(7)));
	}

}
`

**Comment by lowasser** [comment]
Your implementation of TestObject does not appear to override hashCode to comply with the contract for that method, which makes essentially all hash based collections, not just HashMultiset but also the JDK built in collections, fail to work correctly.  This should work correctly if you do that: override hashCode to match equals.

**Comment by nirsoffer** [comment]
Yep - that did indeed work - but FYI:

Collections.frequency actually works as expected. And I should note again that TestObject.equals() is **never called**, whereas in Collections.frequency it is. It appears that the library simply shortcuts the equals() test if the hashCodes are different. 

The documentation for Multiset states that the equals() method is called, unless other specified by the implementation, the implementation doc for HashMultiset does not specify otherwise.

**Comment by lowasser** [comment]
Can you specify which line of the documentation you're referring to? If Multiset differs significantly from Map it's probably worth fixing, but I didn't think HashMap/Set offered any more guarantees.

**Comment by nirsoffer** [comment]
The part I'm referring to is, for instance, here:
http://google.github.io/guava/releases/20.0/api/docs/ - the doc for Multiset says under the general heading.

"A multiset uses Object.equals(java.lang.Object) to determine whether two instances should be considered "the same," unless specified otherwise by the implementation."

It also says, under count() : "Note that for an Object.equals(java.lang.Object)-based multiset, this gives the same result as Collections.frequency(java.util.Collection<?>, java.lang.Object) (which would presumably perform more poorly)."

The HashMultiset doc repeats the same - maybe it would be a good idea to make it explicitly understood for idiots like me that you have to make sure that hashCode is implemented.

And yes, I know it was a braindead violation of the contract by me - but it might be worth noting that equals() is not the only thing that is called in these cases (unlikely Collections.frequency which seemed to not care).

**Comment by jrtom** [comment]
@nirsoffer, the fact that the equals() and hashCode() methods must be consistent is probably one of the most-forgotten pieces of Java lore.  Quoting from Object.equals()' Javadoc:

_Note that it is generally necessary to override the hashCode method whenever this method is overridden, so as to maintain the general contract for the hashCode method, which states that equal objects must have equal hash codes._

So on the one hand, I agree that helping people remember this can be useful, but on the other hand, I worry that if we try to say this everywhere, but miss a few places, people might interpret that as "oh, we don't have to worry about that here".

**Comment by nirsoffer** [comment]
Absolutely fair, @jrtom , that was an amateur hour mistake by me, but maybe there's a way to disambiguate the documentation is all.

**Comment by jrtom** [comment]
@nirsoffer I think that this is one of those issues that would really best be fixed with a compiler warning (or other static analysis tool) if it's detected that you've defined equals() but not hashCode() (or the other way around).  I am a big fan of writing and updating documentation, but I'm not sure that this is a problem that can be fixed with documentation.

(And I've made this mistake too.  :) )

**Comment by jrtom** [comment]
@kluever Well, there you go then.  :)  I should have checked Error Prone first.
