### ISSUE TITLE
Missing UnsignedInts.checkedCast

### ISSUE THREAD

**Issue by travisdowns** [google/guava#2672]
Unless I'm missing something, the method `UnsignedInts.checkedCast(long val)` seems to be missing. This method is available for all of the smaller types (e.g., bytes) in both signed and unsigned variants. It is also available in `Ints` for signed values. 

There doesn't seem to be a particular reason for the omission, since there doesn't seem to be any particular implementation difficulty and it exists in almost all the other "unsigned" variants.

This method is needed and useful for the same reason as all the other `checkedCast` variants.

**Comment by travisdowns** [comment]
Just adding a workaround until the method is added:

`UnsignedInteger.valueOf(val).intValue()`

Of course, this unnecessarily creates an UnsignedInteger object, although escape analysis will often be able to eliminate it.

**Comment by lowasser** [comment]
Where are you seeing an `UnsignedShorts` class?  I'm not seeing it at a glance.

(Another workaround, though not one you can use inline, would be the actual implementation: `checkArgument(x >= 0 && x < (1L << 32));`

I'll look at getting this added, though.

**Comment by travisdowns** [comment]
Wow, haha, I had added `UnsignedShorts` locally to work around issue #670 and I failed to notice it was local while writing the above (that's why it had so few methods). I think the rest of the reasoning still holds though.

**Comment by lowasser** [comment]
Added this to the internal API review queue; will keep this updated.

**Comment by ronshapiro** [comment]
Added in 6fff60802ed6d8157b6178842ff9d164aa0fe928
