### ISSUE TITLE
Please add content-type 'audio/vorbis', 'audio/x-wav' and ability to create MimeType using full name

### ISSUE THREAD

**Issue by mayras** [google/guava#2674]
Please add audio content-type 'audio/vorbis', 'audio/x-wav' to com.google.common.net.MediaType and ability to create MimeType using full name of mime-type, for example:

MimeType.create("audio/x-wav")

**Comment by ronshapiro** [comment]
Is there any reason why MediaType.create(type, subtype) doesn't work for you?
