### ISSUE TITLE
AtomicLongMap using custom ConcurrentMap

### ISSUE THREAD

**Issue by blasd** [google/guava#2675]
Hello,

Would it be legit to add an AtomicLongMap.create(ConcurrentMap) method which keeps the provided Map as undelrying ConcurrentMap? it would typically used over a ConcurrentSkipListMap to provide ordering over keys.

Thanks

**Comment by lowasser** [comment]
I'd be a little nervous about this?  I had plans to potentially change the underlying value type in AtomicLongMap's underlying ConcurrentMap, which would break people using this API if it existed.

More generally, I'm not sure how much of a place there is for AtomicLongMap in a Java 8 world; its features are really easy to write using Java 8 features, e.g. `concurrentHashMap.merge(key, 1L, Long::sum)`.

**Comment by blasd** [comment]
I see your points. This is note a strong requirement on my side, and as you said, Java 8 provides nice alternatives. Thanks
