### ISSUE TITLE
List Merge

### ISSUE THREAD

**Issue by memimy2015** [google/guava#2678]
sometimes I need to merge List&lt;A&gt; and List&lt;B&gt; to List&lt;C&gt;, the object of A and B have a combine property such as id. Is there any function like below？
```
List<T> merge(List<F1> list1, List<F2> list2, Function<T, F1, F2> func);
```

**Comment by jbduncan** [comment]
Hmm, I admit it's not entirely clear to me what it is you want to do here @memimy2015.

Are you trying to find a way of
1. creating a list containing `list1`'s elements followed by `list2`'s elements
2. and then transforming the elements in the new list using `func`?

**Comment by memimy2015** [comment]
sorry.  @jbduncan
for example.
```
class Student{
    long studentId;
    String name;
}
class Exam{
    long studentId;
    int score;
}
class ScoreRecord{
    String name;
    int score;
}
List<Student> students;
List<Exam> exams;
List<ScoreRecord> table = somefunction(students, exams, (student, exam) -> {
    if(student.getStudentId == exam.getStudentId) {
        return new ScoreRecord().setName(student.getName).setScore(exam.getScore);
    }else{
        return null;
    }
});
````
use 'somefunction' I can join the two objects by some key into object of other class  and collect as a list.
do I express it clearly?

**Comment by jbduncan** [comment]
I didn't understand what you meant by "by some key", but I think the rest of what you said made sense to me.

Am I right to understand now that you're trying to combine `students` and `exams` in such a way that each corresponding element from the two lists gets transformed into a `ScoreRecord` (so something like the following, except in a more concise way)?

```java
List<String> names = ImmutableList.of("Jonathan", "Mark", "Philip");
List<String> ages = ImmutableList.of("22", "30", "18");
class Record {
	final String name;
	final String age;

	Record(String name, String age) {
		this.name = name;
		this.age = age;
	}
}
ImmutableList.Builder<Record> recordsBuilder = ImmutableList.builder();
for (int i = 0; i < Math.min(names.size(), ages.size()); i++) {
	String name = names.get(i);
	String age = ages.get(i);
	recordsBuilder.add(new Record(name, age));
}
ImmutableList<Record> records = recordsBuilder.build();
```

If so, then you'll probably have to wait until _Guava 21.0_ is released, as it will have a new [`Streams.zip`](http://google.github.io/guava/releases/snapshot/api/docs/com/google/common/collect/Streams.html#zip-java.util.stream.Stream-java.util.stream.Stream-java.util.function.BiFunction-) method which does exactly that but for streams. (I presume from your usage of a lambda expression in your last message that you know how to turn lists into streams.)

I presume that when _21.0_ is released, you'd use `Streams.zip` like this:
```java
Stream<Record> recordsStream = 
    Streams.zip(
        names,
        ages,
        (name, age) -> new Record(name, age));
// or
recordsStream = Streams.zip(names, ages, Record::new);

// you'd then transform it into a list if needed, either an immutable one (recommended if possible)...
ImmutableList<Record> records = recordsStream.collect(ImmutableList.toImmutableList());
// ...or a mutable one.
List<Record> mutableRecords = recordsStream.collect(Collectors.toCollection(ArrayList::new))
// Or if it doesn't matter to you...
List<Record> records2 = recordsStream.collect(Collectors.toList());
```

**Comment by memimy2015** [comment]
There is a litter different. The two object student and exam must match the condition of 'student.getStudentId == exam.getStudentId', when it can generate a new object of ScoreRecord.@jbduncan

**Comment by liach** [comment]
@memimy2015 What type of list would this method return?

**Comment by memimy2015** [comment]
I have not thought about it, any type is ok, ImmutableList, List ... @liach

**Comment by liach** [comment]
An immutable list would be the easiest to implement.

**Comment by jbduncan** [comment]
Hi @memimy2015, there's still a detail which I'm still a bit unsure about regarding what you want to achieve, so I wonder if you could clarify things further for me.

Do you want to compare elements like this (before checking on a particular "key")...
```
students.get(0) <-> exams.get(0)
students.get(1) <-> exams.get(1)
...             <-> ...
students.get(N) <-> exams.get(N)
```

...or like this?
```
students.get(0) <-> exams.get(0)
students.get(0) <-> exams.get(1)
students.get(0) <-> ...
students.get(0) <-> exams.get(N)
students.get(1) <-> exams.get(0)
students.get(1) <-> exams.get(1)
students.get(1) <-> ...
students.get(1) <-> exams.get(N)
...             <-> ...
students.get(N) <-> exams.get(N)
```

**Comment by liach** [comment]
@jbduncan Should be the first one, or you won't pass lists as arguments.

**Comment by jbduncan** [comment]
Hi @liach, could you explain further why you think it should be the first one? I ask as I'm struggling to understand your explanation of "or you won't pass lists as arguments".

**Comment by liach** [comment]
If it is the type below, then the method would be named `cartesianMerge` like `Lists.cartesianProduct`. Although you can also add `cartesianMerge`, though it would be used very rarely. For cartesian merge, you can use two iterables to iterate and get products. But for the two lists, they need the `size()` method to ensure a merge can be done.

**Comment by jbduncan** [comment]
> If it is the type below, then the method would be named cartesianMerge like Lists.cartesianProduct.

Hmm, did you mean to sound so presumptuous? I struggle to see how you came to the conclusion that @memimy2015 definitely wanted a normal merge over a Cartesian merge. As far as I can tell, they've given no indication so far that they wanted one over the other. So may I kindly ask for the future that you do not jump to conclusions so quickly and to wait to hear from @memimy2015 themselves before answering my question for them?

> But for the two lists, they need the size() method to ensure a merge can be done.

Not necessarily. It's possible to "merge" or "zip" (or whatever term you think best describes this idea) two sequences _without_ a predefined size, by simply merging until one of the two sequences is exhausted. See [`Streams.zip`](https://google.github.io/guava/releases/snapshot/api/docs/com/google/common/collect/Streams.html#zip-java.util.stream.Stream-java.util.stream.Stream-java.util.function.BiFunction-) for an example of what I mean.

**Comment by loki-1** [comment]
If I understood the original request correctly, it's not a 'zip' operation because elements should match based on their key, not on their positions. So if lists are not sorted, there should be additional operation to find the matching element by key, something like
```java
Map<Long, Exam> examByStudentId = Maps.uniqueIndex(exams, e -> e.studentId);
List<ScoreRecord> records = Lists.transform(students, student -> {
    Exam exam = examByStudentId.get(student.studentId);
    return new ScoreRecord(student.name, exam.score);
});
```

**Comment by liach** [comment]
@loki-1 The point is that `List`s are ordered, compared to `Collection`s and `Iterable`s. The order of the elements in the list is based their positions instead of some other key.

**Comment by memimy2015** [comment]
@loki-1 Correctly! Your method can solve my request. I want to know if there is a method I can do this by 1 line code.

**Comment by loki-1** [comment]
@liach Sorry, I don't understand what do you mean. List order may or may not be consistent with key order depending on how inputs are generated.

@memimy2015 I doubt if it should be 1 method, because you have at least 2 different operations: matching items from 2 lists and mapping them into output item.

**Comment by liach** [comment]
```
students.get(0) <-> exams.get(0)
students.get(1) <-> exams.get(1)
...             <-> ...
students.get(N) <-> exams.get(N)
```

**Comment by loki-1** [comment]
@liach I still don't see how lists are special here. For this to work, you need both input collections to be sorted in compatible way. It can be achieved with Lists, SortedSets, LinkedHashSets and so on.
```
studentsIterator.next() <-> examsIterator.next()
studentsIterator.next() <-> examsIterator.next()
...
```

**Comment by liach** [comment]
Ok.

**Comment by ronshapiro** [comment]
We're not ready at this time to add a method like this to Guava, sorry.
