### ISSUE TITLE
Explicitly define "parallel edges"

### ISSUE THREAD

**Issue by cpovirk** [google/guava#2681]
https://github.com/google/guava/wiki/GraphsExplained#definitions mentions that they're what makes a multigraph a multigraph, but that doesn't help me :)

It also gives an example with calling `putEdge(2, 3)` twice. That's more helpful, but I can't tell if `putEdge(2, 3); putEdge(3, 2);` would also count as a parallel edge.

**Comment by jrtom** [comment]
The above-linked section now includes material on parallel and anti-parallel edges, with examples.

@cpovirk, since you opened the issue, please let me know whether this says what you need.  If so, close it; if not, please comment here with your continuing concerns.

**Comment by cpovirk** [comment]
LGTM. Thanks.
