### ISSUE TITLE
Consider running CI under Windows

### ISSUE THREAD

**Issue by jbduncan** [google/guava#2686]
As is currently done in [google-java-format](https://github.com/google/google-java-format), I think it's worth testing Guava against Windows using AppVeyor, or at least I think it's worth for the Guava team to consider looking into it.

Currently, Guava makes no guarantees that it will run successfully on Windows, as explained in the README:

> **IMPORTANT WARNINGS**
> ...
> 5, We unit-test and benchmark the libraries using only OpenJDK 1.7 on Linux. Some features, especially in `com.google.common.io`, may not work correctly in other environments.

I do understand that there would need to be a number of changes or improvements before Guava can build successfully on Windows (https://github.com/google/guava/issues/2130), so I suspect this would be a long-term thing to tackle.

**Comment by jbduncan** [comment]
@cpovirk Oh no! Yeah, the potential incompatibility between the new implementations and Windows occurred to me earlier today. 😆

**Comment by cpovirk** [comment]
This probably did get a lot easier with the switch of our CI to GitHub Actions. It might be roughly just this...

https://github.com/google/error-prone/blob/3602ab040d4dc0f7348fe6103ccfd20252ec1af9/.github/workflows/ci.yml#L27-L29

..._and_ then some number of `if (isWindows()) { return; }` or `assumeThat(isWindows()).isFalse()` checks in our tests... :) But #2130 suggests that even that might not be too bad....

I've been trying to remember if the tests would have caught any production problems under Windows (other than, you know, the significant recent one...). I think we knew about `Files.deleteRecursively` (#365) before it was reported (and I think a similar problem exists even for Linux?), and I'm not sure if #3402 was Windows-specific, either—though perhaps the default Windows temporary directory would have triggered the bug, and that would have been useful.

**Comment by cpovirk** [comment]
Now playing with https://github.com/google/guava/pull/6542...

Our "print surefire reports" step seems likely to go poorly, given that it runs a shell script, but maybe I'll be surprised?

**Comment by cpovirk** [comment]
Well, we might need to skip another test, too:

Linux:
```
Running com.google.common.util.concurrent.AbstractFutureFallbackAtomicHelperTest
Tests run: 43, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 102.883 sec
```

Windows:
```
Running com.google.common.util.concurrent.AbstractFutureFallbackAtomicHelperTest
Tests run: 43, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2,072.23 sec
```

**Comment by cpovirk** [comment]
Similarly:

```
Running com.google.common.util.concurrent.AbstractFutureTest
Tests run: 43, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1,096.901 sec
```

```
Running com.google.common.util.concurrent.AbstractFutureTest
Tests run: 43, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 52.41 sec
```

**Comment by cpovirk** [comment]
And the failures so far, as it works to finish testing `util.concurrent`:

```
Running com.google.common.base.ThrowablesTest
Tests run: 44, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.078 sec <<< FAILURE!
Running com.google.common.io.FileBackedOutputStreamAndroidIncompatibleTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.015 sec <<< FAILURE!
Running com.google.common.io.FileBackedOutputStreamTest
Tests run: 4, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 0 sec <<< FAILURE!
Running com.google.common.io.FilesCreateTempDirTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0 sec <<< FAILURE!
Running com.google.common.io.MoreFilesTest
Tests run: 1151, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 2.862 sec <<< FAILURE!
Running com.google.common.io.ResourcesTest
Tests run: 773, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.016 sec <<< FAILURE!
Running com.google.common.reflect.ClassPathTest
Tests run: 44, Failures: 7, Errors: 1, Skipped: 0, Time elapsed: 6.936 sec <<< FAILURE!
```

**Comment by cpovirk** [comment]
I think I generally know what's up. And fortunately, the Surefire logs did get printed after all, so I'm in the process of confirming.
