### ISSUE TITLE
Consistently use j.u.f or c.g.c.b interfaces in Guava Collectors

### ISSUE THREAD

**Issue by perceptron8** [google/guava#2694]
Hi! I checked some of the new brilliant features of 21.0-rc1 (thanks!) and here's what I found.

1. `Multimaps.toMultimap(Function, Function, Supplier)`
    * `com.google.common.base.Function` should be `java.util.function.Function`
    * `com.google.common.base.Supplier` should be `java.util.function.Supplier`

2. `Tables.toTable(Function, Function, Function, Supplier)`
    * change `com.google.common.base.Supplier` to `java.util.function.Supplier`

3. `Sets.toImmutableEnumSet()`
    * the name is confusing as it returns `ImmutableSet`, not `ImmutableEnumSet`
    * is renaming to `Sets.toImmutableSet` possible?
    * how about additional `ImmutableEnumSet.toImmutableEnumSet` returning `Collector<E, ?, ImmutableEnumSet<E>>`?

4. `ImmutableMultiset.toImmutableMultiset(ToIntFunction)`:
    * could you, please - if at all - expose above instead of
`toImmutableMultiset(Function, ToIntFunction)`? *

5. `ImmutableSortedMultiset.toImmutableSortedMultiset(ToIntFunction)`
    * could you, please - if at all - expose above instead of
`ImmutableSortedMultiset.toImmutableSortedMultiset(Comparator, Function, ToIntFunction)`?  *

6. Multisets again; please, consider adding following methods returning Collectors**:
    * `EnumMultiset.toEnumMultiset()`
    * `EnumMultiset.toEnumMultiset(IntFunction)`
    * `HashMultiset.toMultiset()`
    * `HashMultiset.toMultiset(IntFunction)`
    * `LinkedHashMultiset.toMultiset()`
    * `LinkedHashMultiset.toMultiset(IntFunction)`
    * `TreeMultiset.toMultiset()`
    * `TreeMultiset.toMultiset(IntFunction)`
    * `TreeMultiset.toMultiset(Comparator)` for `<E extends Comparable<? super E>>`
    * `TreeMultiset.toMultiset(Comparator, IntFunction)`
    * `ImmutableSortedMultiset.toImmutableSortedMultiset()` for `<E extends Comparable<? super E>>`

*) `Function` parameter seems to be unnecessary. I believe it's more idiomatic to use `Stream.map(Function).collect(toImmutableMultiset(ToIntFunction))` and/or `Collectors.mapping(Function, toImmutableMultiset(ToIntFunction))`.

With the best wishes!

**Comment by perceptron8** [comment]
**) `Multisets.toMultiset(Supplier)` and `Multisets.toMultisets(IntFunction, Supplier)` could be useful for implementing mutable Multisets collectors, but you surely know that...

**Comment by lowasser** [comment]
There are a lot of things in here, but some high-level points:

- Most of the mutable Multiset collectors you mention can be done with just Collections.toCollection(Supplier), which is a major reason we omitted them.  For example, `collect(toCollection(HashMultiset::create))`.
- We consciously do not expose an `ImmutableEnumSet` _type._  `Sets.toImmutableEnumSet()` is a collector to an enum-based _implementation_ of `ImmutableSet` that only works for enum types.  For other types you should be using `ImmutableSet.toImmutableSet()`, and having the distinct name `toImmutableEnumSet` is meant to help avoid confusion on that point.
- As far as the `c.g.c.b` versus `j.u.f` function issues go, we expect ~all users of these functions to be passing in lambdas and method references for which there is no meaningful difference.
- As regards your footnote, I would _absolutely_ expect the `Function` type to be necessary for many uses.  For example, if you already have a `Stream<Multiset.Entry<E>>`, you would want a collector of the form `toImmutableMultiset(Entry::getElement, Entry::getCount)`, and you could not get the result you want with `Stream.map`.  I think, like the JDK does, we'd be inclined to require both functions and just expect you to pass the identity when appropriate.

**Comment by perceptron8** [comment]
Thank you for quick reply!

> Many of the mutable Multiset collectors you mention can be done with the JDK built-in Collectors.toCollection(Supplier) (...)

That's true. If you would like to expose `.toMultiset(IntFunction)` or `.toMultiset(Function, IntFunction)` however, consider no-arg method too.

> We consciously do not expose an ImmutableEnumSet type (...)

My mistake, can't agree more. Forget about it.

> As far as the c.g.c.b versus j.u.f function issues go, we expect ~all users of these functions to be passing in lambdas and method references for which there is no meaningful difference.

Please, be consistent within the same class at least. `toTable(Function, Function, Function, Supplier)` uses `c.g.u.b.Supplier`, but `toTable(Function, Function, Function, Supplier)` - `j.u.f.Supplier`.

And please, be careful with expectations like the above. They may be true for most of the time, but I've already encountered cases where I wanted to pass *named* j.u.f parameters to the latest Guava methods and I couldn't (I've implemented my own multiset collectors; I wanted to deprecate some of them now, temporarily delegating to Guava collectors; couldn't just pass params which were declared as j.u.f since the beginning; not a great problem, but...).

Also, if your assumption was entirely true, c.g.u.b.Function wouldn't extend j.u.f.Function.

> As regards your footnote, I would absolutely expect the Function type to be necessary for many uses (...)

I've always treated `Multiset` as something more similar to `Set` than a `Map`. It is a `Collection`, right? (being a map is an implementation detail). That's why elementFunction suprised me. BTW note that `ImmutableMultiset` *collector* is inconsistent with `ImmutableMap` about duplicates. It may be also an argument against `ToIntFunction` TBH.

**Comment by kluever** [comment]
It does look like we used `c.g.c.b.Function` in `Mutlimaps, but `j.u.f.Function` in `Tables.java`.

@lowasser can you try to resolve these differences?

**Comment by cpovirk** [comment]
Marking the `java.util`-`com.google.common.base` issue as blocking 21.0-final (@cgdecker). It does seem worth standardizing on `java.util` to me (though users can make the methods work as-is by passing `myFunction::apply`, etc.). But maybe lowasser wants to make the case to leave them as they are?

(Other things here might be worth attention, too. I'm trying to focus on things that would be difficult to change later.)

**Comment by cpovirk** [comment]
I'm also seeing `Maps.toImmutableEnumMap` with a `com.google.common.base.Function`.

**Comment by lowasser** [comment]
Good catch, I missed that one.

**Comment by perceptron8** [comment]
Thank you!

**Comment by cpovirk** [comment]
I may have been overeager in closing this bug entirely, since it covered several topics -- sorry. If there's anything else you'd still like to discuss, can you open additional bugs?

**Comment by Xaerxess** [comment]
What about `Suppliers.memoize` family (or any `Funtions` and `Suppliers` stuff) - will there be any changes there? I know it's a bit different case, and supplier::get should work there, I'd just like to know if there will be any overloads / migrations there.

**Comment by lowasser** [comment]
This just got discussed on the mailing list:

> We know we want to make changes to those methods, but it's complicated enough we haven't worked out a full plan yet.  Some utilities around Guava's functional interfaces are rendered completely redundant by Java 8 (see e.g. Predicates.instanceOf(Class) versus Class::isInstance), some like Suppliers.memoize seem still useful -- we want to make sure we have a comprehensive plan for what to do with these methods before we start changing everything, and we're not there yet.  
>
> You'll definitely start seeing work on these issues in future Guava releases, but for now I think we're leaving those methods be -- though we recommend passing in lambdas to these methods in general, in which case the compiler will just Do The Right Thing.

**Comment by Xaerxess** [comment]
Thanks for clarification!
