### ISSUE TITLE
Invalidate cache entry without running removal listener

### ISSUE THREAD

**Issue by JakeAngell** [google/guava#2701]
Is there a way to invalidate an entry without causing removal listeners to be triggered? 

I want the removal listener to execute when an entry expires after a certain amount of time, not when it is invalidated manually.

Thanks.

**Comment by lowasser** [comment]
You can always just modify your removal listener to check that the
RemovalCause is EXPIRED.  Other than that, no, I don't believe there is a
mechanism to not notify the RemovalListener.
