### ISSUE TITLE
Null map field reference in ImmutableMultimap after deserialization

### ISSUE THREAD

**Issue by heuermh** [google/guava#2708]
When attempting to use Guava version 19.0, 20.0, and 21.0 `ImmutableListMultimap` in Apache Spark 2.1.0, I'm getting NPEs in unexpected places, leading me to believe that the transient `map` field reference is not being set when deserialized, e.g.
```
java.lang.NullPointerException
  at com.google.common.collect.ImmutableMultimap.containsKey
    (ImmutableMultimap.java:478)
...
java.lang.NullPointerException
  at com.google.common.collect.ImmutableListMultimap.get
    (ImmutableListMultimap.java:298)
  at com.google.common.collect.ImmutableListMultimap.get
    (ImmutableListMultimap.java:44)
```

**Comment by cgdecker** [comment]
Is this still happening? We have deserialization and reserialization tests for all of our collections but also handle setting these fields in a slightly unusual way which I could imagine having issues in some environments. But we'd need more information to be able to do anything with this.

**Comment by cpovirk** [comment]
Closing since we don't have much to go on and this may be something specific to how Spark implements serialization.

**Comment by heuermh** [comment]
Thanks for following up, this is old enough that I cannot remember the context under which it was occurring originally.
