### ISSUE TITLE
what about using IdentityHashMap for storing constants in Defaults to reduce memory overhead

### ISSUE THREAD

**Issue by zinking** [google/guava#2709]
yeah, the overhead is very `tiny`
but how does this sound ?

**Comment by cpovirk** [comment]
It's probably not worth worrying about, but if we want to optimize it, we might be best off converting it to `if`-`else if`-`else if`-....

**Comment by zinking** [comment]
LOL, you mean manually do the inlining. 
IdentityHashMap, I just felt this new class never gets used.
