### ISSUE TITLE
Add CharSource.readToCharArray()

### ISSUE THREAD

**Issue by PhilippWendler** [google/guava#2713]
Currently there is no easy way in Java to read a complete file into a single `char` array with the minimal amount of copies in memory. Of course using a `String` instead is usually much better, but sometimes there are legacy APIs that only accept `char[]`. In this case I currently have to do one of the following:

- `MoreFiles.asCharSource(file, encoding).read().toCharArray();`:
  Copies the file content first to a `StringBuilder`, then to a `String` and finally to the `char[]`.
- 
      StringBuilder sb = new StringBuilder();
      MoreFiles.asCharSource(file, encoding).copyTo(sb);
      char[] result = new char[sb.length()];
      sb.getChars(0, sb.length(), result, 0);
   Verbose, non-obvious to write and read, especially because of `getChars` modifying its parameter.

By adding a method `char[] readToCharArray()` to `CharSource` this would be nicely solved. Other implementations of `CharSource` such as `CharSequenceCharSource` could even provide optimized versions of this method.

**Comment by atcharatip** [comment]
#[](url)

**Comment by kaustubhmallik** [comment]
Hi Philip, can I work on this. I don't have much experience in open source though, but it seems like I can take this one.

**Comment by PhilippWendler** [comment]
@kaustubhmallik You should read https://github.com/google/guava/blob/master/CONTRIBUTING.md before working on this. As long as the Guava team has not accepted this change it is relatively useless to actually implement it (which is quite trivial anyway).

**Comment by cgdecker** [comment]
I'd rather not add to the `CharSource` API just to support legacy APIs that take `char[]` when they should really take `String` or `CharSequence`. There are workarounds, as you mention... the first one is probably fine in most cases, and there's a better alternative to the second one as well:

```
CharArrayWriter writer = new CharArrayWriter();
charSource.copyTo(writer);
char[] array = writer.toCharArray();
```
