### ISSUE TITLE
Add addRow, moveRow, addColumn, moveColumn, deleteRow, deleteColumn functions to TreeBasedTable class.

### ISSUE THREAD

**Issue by TimYi** [google/guava#2716]
com.google.common.collect.TreeBasedTable represents a real table data structure. Rows and columns are sorted.
Then add, remove, move row(s), column(s) is common functions to a table. Our project needs these functions. I think this is a common need.

**Comment by TimYi** [comment]
> Table

**Comment by lowasser** [comment]
Hi,

Table isn't really designed for this sort of usage.  It's intended more as a sort of two-dimensional map.  The intent is not that rows and columns be explicitly added and deleted, but rather that rows correspond to "the set of first keys of the (key1, key2, value) triples in the data structure" and so on.  You don't need to add rows, you just insert the entries. 

It is a corollary, I'm afraid, that Table does not permit empty rows or empty columns.  There is no real way around this; if you want that sort of behavior you will need to use a `Map<R, Map<C, V>>` explicitly.

If you need to remove an entire row or column from the table, you can do that quite easily with `row(key).clear()` or `column(key).clear()`.

**Comment by TimYi** [comment]
Well, if I want to insert a row or column into a table, index of rows or columns after will be changed, and it only works for number row and column keys. This is not the intend for Table class. I did not think it over。
