### ISSUE TITLE
E-mail addresses from Google Code exposed in GitHub issues

### ISSUE THREAD

**Issue by homeworkprod** [google/guava#2717]
This is kind of a meta issue.

Project contributors' e-mail addresses, which were originally displayed in an incomplete/"obfuscated" form in Google Code issues as per the authors' privacy settings, have become fully visible after migration of the issues to GitHub ([random example](https://github.com/google/guava/issues/6)).

> Original issue created by [FULL E-MAIL ADDRESS] on [TIMESTAMP]

This does not affect authors who had their username displayed instead (though it might be simple to derive their e-mail addresses from that, but that's not the point here).

Why did this happen? Why did anyone think it would be a good idea to expose people's e-mail addresses, and against their accounts' privacy settings stating otherwise?

While damange has been done already (Hello, spam!), I request the full addresses (or at least mine) to be removed from GitHub issues. (People can't do this on their own as the comments were posted by @gissuebot.)

Due to this alarming incident I feel I should refrain from contributing to Google projects for the time being. I consider this a serious breach of trust.

**Comment by cgdecker** [comment]
Thanks for bringing this to our attention, and please accept our apologies for this issue. We've gone through and obscured all email addresses for non-Google contributors in the same way they were obscured on Google Code.

**Comment by homeworkprod** [comment]
Thanks, Colin.

Apologies accepted.
