### ISSUE TITLE
Error:Execution failed for task ':testapp:transformClassesWithPreJackPackagedLibrariesForDebug'. > com.android.build.api.transform.TransformException: com.android.jack.api.v01.CompilationException

### ISSUE THREAD

**Issue by SmileToMe** [google/guava#2722]
how to solve this error？？？

Error:Execution failed for task ':testapp:transformClassesWithPreJackPackagedLibrariesForDebug'.
> com.android.build.api.transform.TransformException: com.android.jack.api.v01.CompilationException

**Comment by jbduncan** [comment]
Hi @SmileToMe, could you provide us with some more context, like what IDE or build tool you're using, or a full stack trace? There's very little we can understand from the information you've currently given us.

**Comment by SmileToMe** [comment]
@jbduncan        Use in the  Android Studio     

here is  my    build.gradle
 
`apply plugin: 'com.android.application'

android {
    compileSdkVersion 25
    buildToolsVersion "25.0.0"

    defaultConfig {
        applicationId "com.global.testapp"
        minSdkVersion 15
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        jackOptions {
            enabled true
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile project(':testlibrary')
    testCompile 'junit:junit:4.12'
    compile 'com.google.guava:guava:21.0'
}
`

if  run, will be wrong.  below is the error message 

`Information:Gradle tasks [:testapp:assembleDebug]
Error:MoreCollectors.java:45-46: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.Supplier
Error:MoreCollectors.java:45-46: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.BinaryOperator
Error:MoreCollectors.java:66-67: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.Supplier
Error:MoreCollectors.java:66-67: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.BinaryOperator
Error:ImmutableMapValues.java:67-68: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.Function
Error:Lists.java:664-665: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.Predicate
Error:Tables.java:72-73: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.BinaryOperator
Error:Tables.java:107-108: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.BinaryOperator
Error:Maps.java:211-212: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.Supplier
Error:Maps.java:211-212: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.BiConsumer
Error:Maps.java:211-212: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.BinaryOperator
Error:Maps.java:211-212: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.Function
Error:Maps.java:213-214: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.BinaryOperator
Error:ArrayTable.java:800-801: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.IntFunction
Error:Iterables.java:621-622: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.Consumer
Error:AtomicLongMap.java:135-136: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.LongBinaryOperator
Error:AtomicLongMap.java:163-164: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.BiFunction
Error:AtomicLongMap.java:184-185: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.LongUnaryOperator
Error:AtomicLongMap.java:198-199: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.LongUnaryOperator
Error:AtomicLongMap.java:257-258: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.ToLongFunction
Error:Maps.java:2165-2166: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.BiConsumer
Error:Multiset.java:491-492: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.Consumer
Error:HashBiMap.java:693-694: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.BiConsumer
Error:ImmutableSortedMultiset.java:90-91: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.Supplier
Error:ImmutableSortedMultiset.java:90-91: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.BinaryOperator
Error:LocalCache.java:4835-4836: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.BiPredicate
Error:ImmutableList.java:580-581: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.IntFunction
Error:Maps.java:3331-3332: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.BiFunction
Error:Streams.java:174-175: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.Function
Error:Streams.java:128-129: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.Function
Error:Streams.java:271-272: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.Consumer
Error:ImmutableMultimap.java:620-621: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.BiConsumer
Error:ImmutableMultimap.java:622-623: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.Consumer
Error:LocalCache.java:4798-4799: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.BiPredicate
Error:StandardTable.java:275-276: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.Function
Error:CollectCollectors.java:36-37: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.Supplier
Error:CollectCollectors.java:57-58: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.Supplier
Error:CollectCollectors.java:45-46: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.BinaryOperator
Error:CollectCollectors.java:57-58: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.BiConsumer
Error:CollectCollectors.java:36-37: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.Function
Error:CollectCollectors.java:57-58: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.Function
Error:CollectCollectors.java:65-66: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.BiConsumer
Error:CollectCollectors.java:65-66: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.Function
Error:CollectCollectors.java:94-95: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.Supplier
Error:CollectCollectors.java:83-84: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.BiConsumer
Error:CollectCollectors.java:83-84: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.BinaryOperator
Error:CollectCollectors.java:83-84: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.Function
Error:ImmutableListMultimap.java:87-88: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.BiConsumer
Error:ImmutableListMultimap.java:87-88: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.BinaryOperator
Error:ImmutableListMultimap.java:87-88: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.Function
Error:ImmutableListMultimap.java:133-134: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.Function
Error:Maps.java:4009-4010: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.BiConsumer
Error:RegularImmutableBiMap.java:205-206: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.BiConsumer
Error:LocalCache.java:4388-4389: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.BiFunction
Error:ImmutableSortedMap.java:649-650: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.IntFunction
Error:Collections2.java:216-217: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.Predicate
Error:Collections2.java:221-222: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.Predicate
Error:ImmutableMultiset.java:67-68: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.ToIntFunction
Error:ImmutableMultiset.java:85-86: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.BiConsumer
Error:ImmutableMultiset.java:85-86: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.Function
Error:Multimaps.java:163-164: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.BiConsumer
Error:Multimaps.java:163-164: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.BinaryOperator
Error:Multimaps.java:1684-1685: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.Function
Error:AbstractTable.java:195-196: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.Function
Error:AbstractMapBasedMultimap.java:1264-1265: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.Function
Error:AbstractMapBasedMultimap.java:1279-1280: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.Consumer
Error:CollectSpliterators.java:246-247: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.Consumer
Error:ImmutableSortedMap.java:106-107: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.Supplier
Error:Sets.java:141-142: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.Supplier
Error:Sets.java:141-142: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.BinaryOperator
Error:Collections2.java:311-312: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.Predicate
Error:ImmutableSet.java:384-385: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.IntFunction
Error:CollectSpliterators.java:115-116: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.Consumer
Error:ImmutableMap.java:100-101: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.Function
Error:LinkedHashMultimap.java:575-576: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.Function
Error:ImmutableTable.java:71-72: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.Supplier
Error:ImmutableTable.java:71-72: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.BiConsumer
Error:ImmutableTable.java:71-72: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.BinaryOperator
Error:ImmutableTable.java:107-108: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.BinaryOperator
Error:ImmutableSortedAsList.java:92-93: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.IntFunction
Error:ImmutableSetMultimap.java:91-92: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.Supplier
Error:ImmutableSetMultimap.java:91-92: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.BinaryOperator
Error:ImmutableSetMultimap.java:145-146: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.Function
Error:ImmutableSetMultimap.java:149-150: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.Supplier
Error:Maps.java:1124-1125: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.Consumer
Error:Maps.java:1119-1120: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.Function
Error:ImmutableEnumMap.java:99-100: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.Function
Error:Iterables.java:382-383: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.Supplier
Error:Iterables.java:578-579: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.Consumer
Error:com.android.jack.JackAbortException
Error:Execution failed for task ':testapp:transformClassesWithPreJackPackagedLibrariesForDebug'.
> com.android.build.api.transform.TransformException: com.android.jack.api.v01.CompilationException
Information:BUILD FAILED
Information:Total time: 21.617 secs
Information:91 errors
Information:0 warnings
Information:See complete output in console`

**Comment by jbduncan** [comment]
Ah okay, the problem you're having is that you cannot use Guava 21.0 on Android. This is because Guava 21.0 depends on Java 8, which Android does not support yet.

Your solution for now is to use Guava 20.0. When Guava 22.0 is released, an android port of Guava will be released which you can then use. (See https://groups.google.com/forum/#!topic/guava-discuss/ZRmDJnAq9T0 and https://groups.google.com/forum/#!topic/guava-discuss/9Nmp4uncCjI for more information on this.)

Hope this helps!

**Comment by SmileToMe** [comment]
every good ！ succeed！

**Comment by liruqi** [comment]
Thanks 👍

**Comment by jbduncan** [comment]
Hi @SmileToMe, does this answer your question for now? If so, I kindly suggest that you close this issue so that the Guava team had one less open issue to sift through. :)

**Comment by gabrieloshiro** [comment]
Can't we add the information here to https://github.com/google/guava/wiki/Compatibility ?

**Comment by MIkeeJY** [comment]
bumps!!!

**Comment by cgdecker** [comment]
Hopefully our documentation makes it clear enough now that you should use a `-android` version of Guava for Android.
