### ISSUE TITLE
Sets.cartesianProduct(Set<? extends B>... sets) is missing @SafeVarargs annotation

### ISSUE THREAD

**Issue by arlampin** [google/guava#2724]
`Lists.cartesianProduct(List<? extends B>... lists)` has it, so I assume Sets version should also have it.

**Comment by sagar-shah94** [comment]
Hey @cpovirk,
This is my first issue as contribution to google guava. I am not sure who i should ask to review my PR.
Can you please review PR (https://github.com/google/guava/pull/3127)
 to fix this issue.

**Comment by sagar-shah94** [comment]
@cpovirk @lowasser Can you please suggest me an issue that i should work on next. since i am new to contributing to google guava, i don't know which issue would be the best to work on next?

Please review PR https://github.com/google/guava/pull/3127 that will fix this issue
