### ISSUE TITLE
NullPointerTester: add method to ignore constructor

### ISSUE THREAD

**Issue by bdworth** [google/guava#2726]
`NullPointerTester` has `ignore()` to ignore methods, but there's no equivalent method for ignoring constructors.

This is easy to work around by calling `testConstructor()` on a set of filtered constructors. But it would be nice if core Guava included a way to ignore constructors before calling `testAllPublicConstructors()` or `testConstructors()`.

**Comment by cpovirk** [comment]
Sounds like something that we could take a pull request for. Otherwise, we might get there eventually, but it will probably never rise to the top of our list.
