### ISSUE TITLE
Make some improvements to Stopwatch

### ISSUE THREAD

**Issue by MrSystem** [google/guava#2735]
I think the current implementation of `Stopwatch` could be improved.
In particular:

- <strike>Concurrent manipulation of its state should be supported.</strike>
- If multiple stopwatch instances are being used, it might be difficult to identify which one the output belongs to. This could be easily addressed by adding an identifier to the stopwatch.
- The logic to implement the "smart" behavior of automatically choosing the most appropriate time unit based on the scale of the result is a bit cumbersome. I think that just using `TimeUnit.toString()` is perfectly acceptable in this case.
- A stopwatch that, once constructed, is not in the running state by default is of no value. The same thing can be achieved by delaying the construction of the object itself.

I often had to develop my own "profiler" utility, so I'd like to contribute my code to this issue.

I've written a [simple draft](https://gist.github.com/MrSystem/579b16a472c756e5d77918bff1714f66) of what I think could qualify as a good API & implementation.
Please note that documentation is missing and that I've used my own code style. Proper backward compatibility support has to be implemented, too. I will commit a new and improved version once the issue has been discussed.
Note that the following issues are being addressed as well: #2593 #2729 #2007.

Here's an example of how I'd use it (a meaningful identifier is passed to the constructor):

```
Stopwatch stopwatch = new Stopwatch("ID Generator");
for (int i = 0; i < 10; i++) {
    UUID.randomUUID();
}
stopwatch.report();
```

The output generated by the previous example is the following:

```
[ID Generator] Elapsed time: 73 milliseconds
```

**Comment by perceptron8** [comment]
This "good" implementation doesn't even pause on `pause()`; `computeAndAddElapsedTime()` uses atomic but then synchronizes; `toString()` alters internal state of object (after many ridiculous nested method calls); and so on.

How are you going to support backward compatibility when you extend `toString()` with "[name]"? Why not "(name)" or "name:"?

Does `Stopwatch` really need to be thread-safe? What are you going to measure? Context switching overhead?

How would you like to extend Stopwatch? Why didn't you mark it final? Just to "resolve" #2729?

It's hard to design an API. Try to learn from other's experience.

For now, just execute the following:

```
Stopwatch s = new Stopwatch();
s.pause();
Thread.sleep(100);
s.report();
Thread.sleep(100);
s.report();
```

Then, think again.

**Comment by perceptron8** [comment]
For the curious:

```
[Stopwatch] Elapsed time: 101 milliseconds
[Stopwatch] Elapsed time: 302 milliseconds
```

**Comment by MrSystem** [comment]
Hi, thank you for your feedback.

Sorry, but I can't reproduce the problem with `pause()`.
The following test succeeds on my machine:

```
@Test
public void shouldAlwaysBeZero() throws InterruptedException {
    Stopwatch stopwatch = new Stopwatch();
    stopwatch.pause();
    Thread.sleep(100);
    assertEquals(stopwatch.toString(), "[Stopwatch] Elapsed time: 0 milliseconds");
    Thread.sleep(100);
    assertEquals(stopwatch.toString(), "[Stopwatch] Elapsed time: 0 milliseconds");
}
```

The synchronization in `computeAndAddElapsedTime()` is necessary, because the equivalent with `elapsedTime` being an `AtomicLong` doesn't describe an atomic operation:

```
elapsedTime.getAndAdd(now - lastCompute.getAndSet(now));
```

Consequently, `elapsedTime` is declared `volatile long` because since it's only being modified by a single synchronized block, it just needs the protection from memory consistency errors provided by the `volatile` keyword.
Similarly, I mixed synchronized blocks and atomic variables for the sake of performance - I didn't want to synchronize everything on the object's lock.

`toString()` alters the internal state of the object in a consistent manner (i.e. it may be called N times, and still the object will have a valid state). It has to do so, in order to provide its caller with up-to-date information about the state of the object.
I propended to use square brackets, but any character would do just as well.
While it may look like that it breaks the API specification, it actually doesn't; it always returns a _concise but informative representation of the object_. Moreover, it's a method that is automatically called in many cases (e.g. when its object is passed to `System.out.println()`), thus allowing for clearer code.

I didn't make the class final mostly because protected methods could be provided to let clients hook into the inner workings of the class. I also partially disagree with Bloch's advice of prohibiting inheritance as the default choice.

**Comment by ogregoire** [comment]
What I just don't get is why you want to use `synchronize` in a class that is supposed to have the smallest time footprint. If you want to time really small portion of code, the overhead of `synchronized` *can* have a non-negligible impact.

Also, just like @perceptron8, I fail to see why Stopwatch needs to be thread-safe. Stopwatch is just a nice wrapper around repetitive calls to `System.nanotime()`. I've been programming for 18 years now, I've never, ever needed to measure time difference in different threads (bar the date-time-related stuff, but that's another topic). Could you explain your use-case that requires thread-safety? I'm quite curious.

**Comment by perceptron8** [comment]
> Sorry, but I can't reproduce the problem with pause().

It's simple. Just use revision#1 of your code, the only one I had access to.

> The synchronization in computeAndAddElapsedTime() is necessary (...)

The code is still messy and not thread-safe at all (as of revision#4) - and you still can't see that.
It's e. g. possible for `computeAndAddElapsedTime()` to be executed in parallel (e. g. by invoking `toString()` twice).

This is how it looks as of revision#4:

```
private void computeAndAddElapsedTime() {
    long now = System.nanoTime();
    synchronized (this) {
        elapsedTime += now - lastCompute.get();
        lastCompute.set(now);
    }
}
```

What can go wrong? Let's assume that every instance attribute eq 0. Remember that `now` variable is local. Create one, shared Stopwatch. Execute `toString()` concurrently by 2 threads.

```
// time flows (100 nanos)...
// -> Thread1:
now@T1 = 100
// time flows (100 nanos)...
// -> Thread2:
now@T2 = 200
elapsedTime = 0 + 200 - 0 = 200
lastCompute = 200
// -> Thread 1:
elapsedTime = 200 + 100 - 200 = 100
lastCompute = 0
```

After 200 nanos, you have an instance with elapsedTime eq 100 and lastCompute eq 0. Not so good.

Concurrency is harder than you think.

**Comment by MrSystem** [comment]
Yeah, I see both problems. In my first tests, the overhead seemed acceptable.
Anyway, I really don't have an use-case. I've transformed it into its singlethreaded equivalent.

**Comment by MrSystem** [comment]
I'm closing this issue because it looks like it wasn't well-received by the community.

In my opinion, however, there are other problems which I haven't addressed in the draft.
In particular:
- I fail to see any good use-case for pausing.
- Partial results should be made available. #2752
