### ISSUE TITLE
LoadingCache: return expired value while recalculating

### ISSUE THREAD

**Issue by errandir** [google/guava#2737]
E.g. there are:

<pre lang="java">
LoadingCache<K, V> cache = CacheBuilder.newBuilder()
        .refreshAfterWrite(w, MINUTES)
        .build(new CacheLoader<K, V>() {
            public V load(K key) throws Exception {
                // long running IO;
            }
        });
</pre>

It would be great if it will be possible to make `cache` return expired value while recalculating.

**Comment by lowasser** [comment]
I can see how this might be useful for some use cases, but I am utterly certain there are people depending on the cache never returning expired values, and we can't change this out from under them.

On the other hand, refresh behavior, unlike expiration, specifically does what you want; if you return a ListenableFuture from the reload method in CacheLoader, it will continue returning the old value until it asynchronously updates the cache with the refreshed value.  Does this satisfy your needs?

**Comment by errandir** [comment]
@lowasser. I had some more experiments and found that I have no idea how to make cache periodically refresh values (without any extra code). The main idea is the possibility to get quite fresh values instantly at any time. Using only `refreshAfterWrite` I have to do some manual polling, otherwise I could get old values or a noticeable delay (in combination with `expireAfterWrite`) after a long silence period.

**Comment by lowasser** [comment]
You are correct that you will have to do some manual polling, and there is currently no way around that.  Refreshes occur on the first request to an entry after its `refreshAfterWrite` interval.

**Comment by errandir** [comment]
I see. The issue in it's current statement is exhausted.
