### ISSUE TITLE
Sets.difference should accept general Collection as second argument

### ISSUE THREAD

**Issue by tomaszalusky** [google/guava#2738]
Current signature of `Sets.difference` method is

    SetView<E> difference(final Set<E> set1, final Set<?> set2)

however, for all usages of `set2` argument everything would work as well if argument was of type `Collection<?>`, without impact on performance for current usages. Why not to make signature less strict?

In my use case, I do following manipulation:

    BiMap<Foo,Foo> specialFoos = ...
    Set<Foo> nonspecialLeftFoos  = Sets.difference(leftFoos ,specialFoos.keySet());
    Set<Foo> nonspecialRightFoos = Sets.difference(rightFoos,specialFoos.values());

where this issue is the only reason why `specialFoos` is a `BiMap`.
Thanks for response.

**Comment by perceptron8** [comment]
> (...) for all usages of set2 argument everything would work as well if argument was of type Collection<?>, without impact on performance for current usages.

`Collection.contains()`, which `Sets.difference()` uses a lot, is _O(1)_ for hash based sets and _O(log(n))_ for tree based sets. You can't guarantee anything below _O(n)_ in general (`List`, `Queue` and so on). Iterating over `Sets.difference()` would be _O(n^2)_ in that case - that's not something you want - it's about _O(n)_ now.

**Comment by lowasser** [comment]
If you really want that behavior you can also always get it with
Sets.filter(set, not(in(Collection))).

**Comment by tomaszalusky** [comment]
@perceptron8 agree, I talked about not worsening performance for sets since no other type could be passed so far. For other types of collections the performance would certainly be worse. This could be emphasized in javadoc in similar manner as for example in the note in `Sets.intersection` method's javadoc. 

Anyway, if you find proposed change too risky and tend to be misused, I am fine with any of workarounds, of which the @lowasser 's one seems to be the best readable.

**Comment by jbduncan** [comment]
> If you really want that behavior you can also always get it with
Sets.filter(set, not(in(Collection))).

Or, if you're on Java 8 and a fan of lambdas: `Sets.filter(set, e -> !collection.contains(e))`.

**Comment by jrtom** [comment]
The other obvious thing that one could do: 

`Sets.difference(rightFoos, ImmutableSet.copyOf(specialFoos.values())`

This would take up more space, but would be more efficient than filtering using collection.contains() (O(n) vs. O(n^2)).

**Comment by cgdecker** [comment]
Given that there are good workarounds when you do want this behavior and the points others have raised about why you would want both to args be `Set`s for this method, I'm going to close this.
