### ISSUE TITLE
CaseFormat does not appear in the Wiki's TOC

### ISSUE THREAD

**Issue by omega09** [google/guava#2741]
The TOC displayed on all the [Wiki](https://github.com/google/guava/wiki) pages is missing `CaseFormat` under `Strings`:

- [Strings](https://github.com/google/guava/wiki/StringsExplained)
  - Joiner
  - Splitter
  - CharMatcher
  - Charsets

The linked page contains an entry `CaseFormat` which isn't shown.

**Comment by kluever** [comment]
Thanks, fixed! Unfortunately it looks like the sidebar is not generated programmatically, so this was a manual fix. Good eye though!

**Comment by omega09** [comment]
Don't know what Wiki type this is, but usually they are auto-generated. Weird. Might mean there are more of these.
