### ISSUE TITLE
com.google.common.cache.LongAddables

### ISSUE THREAD

**Issue by magicsun198910** [google/guava#2742]
hello. i found like this code.
`static {
    Supplier<LongAddable> supplier;
    try {
      new LongAdder();
      supplier = new Supplier<LongAddable>() {
        @Override
        public LongAddable get() {
          return new LongAdder();
        }
      };
    } catch (Throwable t) { // we really want to catch *everything*
      supplier = new Supplier<LongAddable>() {
        @Override
        public LongAddable get() {
          return new PureJavaLongAddable();
        }
      };
    }
    SUPPLIER = supplier;
  }`

why there is have 
`new LongAdder();`
i feel useless.......

maven version
            <dependency>
                <groupId>com.google.guava</groupId>
                <artifactId>guava</artifactId>
                <version>18.0</version>
            </dependency>

**Comment by perceptron8** [comment]
It's here to "trigger static initialization of the LongAdder class". See 6d55c17.

**Comment by ben-manes** [comment]
Probably can be removed due to Guava being Java 8 based now.

**Comment by jbduncan** [comment]
Except that Guava will be getting an Android port soon, so removing that line will introduce yet another difference between the two versions that has to be managed.

**Comment by ben-manes** [comment]
True, but the cache was always a poor choice for Android. It was designed for servers. Most Android users should use `LruCache`. One might argue that an android port should have different implementation or deprecate the cache as not a good fit. But extra code here has no penalty.
