### ISSUE TITLE
Provide overloaded MoreCollectors.toOptional which allows passing exception

### ISSUE THREAD

**Issue by Diagoras** [google/guava#2745]
Hey, thanks for this great library. MoreCollectors.toOptional is great, since I've found myself craving a Collector that makes it easy to assert that only one (or zero) elements exists in a Stream. Thing is, most of the time I also want to throw a custom exception (or a regular one with a custom message) describing the violation when this condition is failed, as opposed to a more general IllegalArgumentException.

So, how do you feel about an overload for MoreCollectors.toOptional - one that takes a supplier for an exception to throw when there is more than one element in a Stream?

**Comment by kluever** [comment]
This would be significantly different than any of our other collectors, and as such it feels rather niche.

Can you provide a bit more background as to why IAE doesn't work for your usecase?

**Comment by cgdecker** [comment]
This doesn't sound to me like something we'd want to add. We don't, for example, have an overload of `Iterables.getOnlyElement` that can throw a custom exception. And in most cases if you _really_ want to throw a different exception you could catch the IAE and throw your own exception, but it's not something I'd generally recommend.
