### ISSUE TITLE
Feature request: method to check whether (Loading)Cache is currently loading a given key

### ISSUE THREAD

**Issue by rrobby86** [google/guava#2746]
I would like to propose the addition to the `LoadingCache` API (or more generally to `Cache`, if appropriate) of a method like `boolean isLoading(K)`, which would allow one thread to check whether the value for the given key is currently being loaded by another thread, returning immediately in any case.

The use case I encountered for this hypothetical feature is the usage of a `LoadingCache` within tasks in a Java `ForkJoinPool`. In order to maintain a target parallelism level, the pool attempts to spawn or resume threads when other threads block, as long as such block is *managed* by the pool by means of a `ManagedBlocker`. In order to implement this, seems to be needed some way to check whether the current thread will be blocked *before* actually blocking it. (I do not have much experience with `ForkJoinPool`s, I hope what I wrote here is correct)

At the moment I resolved this issue by tracking keys being loaded in an external data structure. However, I'm trying to propose such feature as I think it would be relatively unobtrusive (but I may be wrong about this, I don't know about the internals of `LoadingCache`) and it would provide a more efficient solution to the use case above; other cases could also exist, although I can't figure them out at the moment.

**Comment by ben-manes** [comment]
Would an `AsyncLoadingCache`, e.g. retaining a future of the value, work instead? The future can be queried or if using `CompletableFuture` it internally uses `ManagedBlocker`.

**Comment by rrobby86** [comment]
Thinking a bit about it, an `AsyncLoadingCache` could actually be useful in my case: if I understood that correctly, any thread would `get` a `Future` whose `isDone` method can be used as an equivalent of the method I proposed.

In general, it seems to me a nice functionality to have added in Guava. I'm going to give it a try if and when it will be released.

Thank you for your answer.

**Comment by ben-manes** [comment]
You should be able to write one on top of guava with small caveats of skewing stats, expiration, etc. Otherwise you could use an [implementation](https://github.com/ben-manes/caffeine) outside of Guava.

**Comment by rrobby86** [comment]
I'll take a look at it, thanks again.
