### ISSUE TITLE
Guava / Spring GuavaCacheManager - CacheBuilder RemovalListener ClassCastException Possibility

### ISSUE THREAD

**Issue by erdarun** [google/guava#2747]
I have been using Guava version 20.0 and Spring GuavaCacheManager version 4.3.3.RELEASE for caching in my application.

I'm initialising guava cache builder in spring configuration file and using cacheable annotation in cache file. 

As per Guava CacheBuilder RemovalListener docs,

> Warning: after invoking this method, do not continue to use this cache
> builder reference; instead use the reference this method returns. At
> runtime, these point to the same instance, but only the returned
> reference has the correct generic type information so as to ensure
> type safety. For best results, use the standard method-chaining idiom
> illustrated in the class documentation above, configuring a builder
> and building your cache in a single statement. Failure to heed this
> advice can result in a ClassCastException being thrown by a cache
> operation at some undefined point in the future.

*I'm using the reference returned by removal listener in spring configuration file.*

*But still is there any possibility of ClassCastException being thrown by a cache operation at some undefined point in the future for the below code?*

***Since here CacheBuilder is created/initialised with removal listener in a single step then at later point Cache build will be lazily initialised at Spring GuavaCacheManager getCache***

Spring configuration file

    @configuration
    @EnableCaching
    public class SpringConfig {
	
	@Bean
	public CacheBuilder<Object, Object> cacheBuilder() {
	    CacheBuilder<Object, Object> cacheBuilder = CacheBuilder.from("maximumSize=1000,expireAfterAccess=1d").removalListener(addRemovalListener());
	    
	    return cacheBuilder;
	}
	
	@Autowired
	private CacheBuilder<Object, Object> cacheBuilder;
	
	@Bean
	public CacheManager cacheManager() {
	    GuavaCacheManager cacheManager = new GuavaCacheManager();
	    cacheManager.setCacheBuilder(cacheBuilder);
	    cacheManager.setAllowNullValues(false);
	    return cacheManager;
	}
    
    private RemovalListener<Object, Object> addRemovalListener() {
		return new RemovalListener<Object, Object>() {
			public void onRemoval(RemovalNotification<Object, Object> removal) {

				if(RemovalCause.EXPLICIT != removal.getCause()) {

    				try {
    					String key = (String) removal.getKey();
    					String val = (String) removal.getValue();
    					......
                        ......
					} catch (Exception e) {
						logger.error("Cache RemovalListener Exception [{}]", e.getMessage(), e);
					}
				}
			}
		};
	}

    }

Spring Cache File

    @Service
    public class SpringCache {

	@Autowired
	private CacheManager cacheManager;

    @Cacheable(cacheManager="cacheManager", key="#p0", cacheNames="cacheKeysMap", sync=true)
	public String getKeyFromCache(String key) {
        ......
        ......
        return value;
    }

    @CacheEvict(cacheManager="cacheManager", key="#p0", cacheNames="cacheKeysMap")
	public void deleteFromCache(String key) {
		
	}

    }

**Comment by lowasser** [comment]
This frankly sounds like a question for Spring, not Guava.  I have no idea how Spring builds its caches.

That said, nothing here is going to be surprising.  If you only put strings into the cache, then your `RemovalListener` only needs to handle strings.  If this passes even basic tests, it's not going to fail later by surprise.

**Comment by erdarun** [comment]
My only concern is,
_Guava CacheBuilder is created/initialised with removal listener in a single step then at later point Cache build will be lazily created._

My basic tests are working fine. 

**But since Guava docs advices configuring a builder
and building your cache in a single statement for RemovalListener, I'm worried will it have an ClassCastException possibility at some undefined point in future?**

**Comment by lowasser** [comment]
The advice is just there to help the generics all match without any casts; it's just for convenience.  If your basic tests work, the whole thing will work.

**Comment by erdarun** [comment]
My Cache will have key as String and value as CUTOM_OBJECT.

CacheBuilder<Object, Object>
RemovalListener<Object, Object>

RemovalListener logic has type casting,

> String key = (String) removal.getKey();
> CUTOM_OBJECT val = (CUTOM_OBJECT) removal.getValue();

Is that fine?

**Comment by lowasser** [comment]
Yes, that's fine.  That's what Java does under the hood anyway due to type erasure.

**Comment by SarjitaKonj** [comment]
Hi, @erdarun  can you please share this code. I want to refer how to add entries into the cache, my cacheBuiler is always empty after adding also. Thank you in advance.

**Comment by cgdecker** [comment]
Closing this because it doesn't sound like there's any issue with `CacheBuilder` that needs to be fixed here.
