### ISSUE TITLE
ImmutableRange{Map,Set} collectors

### ISSUE THREAD

**Issue by Stephan202** [google/guava#2750]
Similar to #2667, could you please consider adding convenience `Collector` implementations for `ImmutableRangeMap` and `ImmutableRangeSet`?

**Comment by Stephan202** [comment]
I see @dimo414 just added this feature in 719f2c581f4f09f55c2121c6ac469c7f4314ceab; nice, thanks!

(Leaving the ticket over for now; it'd be good to document these new collectors in the [release notes](https://github.com/google/guava/wiki/Release23).)

**Comment by dimo414** [comment]
@cgdecker could you add this to the release notes and close this issue?

**Comment by dimo414** [comment]
Looking at http://google.github.io/guava/releases/23.0/api/docs/com/google/common/collect/ImmutableRangeMap.html it seems this actually missed the 23 release?

**Comment by Stephan202** [comment]
You're right, unfortunately this feature is not in the Guava 23.0 release.
