### ISSUE TITLE
TypeToken.isSubTypeOf() should consider declared bounds for type variables

### ISSUE THREAD

**Issue by cpovirk** [google/guava#2751]
private interface Foo<T extends Number> {}

    public void testUnboundedAndBounded() {
      TypeToken<Foo<?>> a = new TypeToken<Foo<?>>() {};
      TypeToken<Foo<? extends Number>> b = new TypeToken<Foo<? extends Number>>() {};
      assertTrue(a.isSubtypeOf(b)); // fails
      assertTrue(b.isSubtypeOf(a));
    }

I think that we want that to pass. In our `isSubtypeOf()` docs, we claim to implement [a section of the JLS](http://docs.oracle.com/javase/specs/jls/se8/html/jls-4.html#jls-4.5.1). That section mentions "capture conversion," which sounds like maybe something that `isSubtypeOf()` should be doing but isn't (or isn't doing completely)? But I'm in over my head.

**Comment by jbduncan** [comment]
@cpovirk Did you mean to close this or add the `22.0` milestone?

**Comment by cpovirk** [comment]
Yes, thanks. See the commit referenced above (from 12 days ago -- I guess we needed to write "Fixes" rather than "Fix" to get it to happen automatically).

**Comment by jbduncan** [comment]
I _just_ realised that this issue had an associated fix commit. Apologies!
