### ISSUE TITLE
Feature Request: BloomFilter.approximateSize()

### ISSUE THREAD

**Issue by tcbeutler** [google/guava#2755]
From a ten year old paper, there's a [function that approximates the number of items in a bloom filter](https://en.wikipedia.org/wiki/Bloom_filter#Approximating_the_number_of_items_in_a_Bloom_filter). 

All it needs is Bloomfilter's `bits.bitSize()`, `bits.bitCount()`, and `numHashFunctions`. I played around with it and found it to be remarkably accurate for large and small, empty and full filters alike. I was seeing accuracy between 2 and 5 9's based on the size of the filters.

I'd be happy to implement it (properly) if needed. I think there is value in this addition, and since it's just a calculation with some internal values, I don't see any major downsides. I suppose there isn't a way to quantify the accuracy of the results, but between Javadoc and a descriptive method name (like in "mightContain") the approximate nature of the result could be clear.

**Comment by kluever** [comment]
This is interesting...can you elaborate a bit on the use case for knowing the approximate size of the bloom filter? Just for monitoring purposes or something?

**Comment by tcbeutler** [comment]
Just general data introspection purposes. If committing non-unique elements, it lets you use the same data structure in place of a HyperLogLog for cardinality estimates. This is especially useful if you're using bloom filters to represent subsets of data and combining them - you can get very fast union cardinality estimates in O(1) with a small memory footprint.

It's also just a nice sanity check in general. "yeah, that number looks about right". If you get a chance, play with the snippet I posted - I was really impressed at the accuracy with various sizes and fill percents.

**Comment by kluever** [comment]
The approximation seems to be fairly reasonable so as long as you don't exceed `expectedInsertions`. I suppose we could warn about this in the javadocs though.

**Comment by kluever** [comment]
@tcbeutler I'll float this idea internally, but in the meantime, can you please sign the Guava CLA? https://github.com/google/guava/wiki/HowToContribute#new-features Thanks :-)

**Comment by tcbeutler** [comment]
Just FYI - I'm haven't abandoned this, just proceeding through the internal process to do this under the corporate CLA.

**Comment by tcbeutler** [comment]
@kluever I've been added to the Amazon CCLA under my email beutlert@amazon.com

**Comment by kluever** [comment]
Cool, verified. Thanks!

**Comment by peluo** [comment]
is this same?

http://cstheory.stackexchange.com/questions/10023/computing-the-approximate-population-of-a-bloom-filter

**Comment by tcbeutler** [comment]
It is the same. Interesting that the conversation there happened 5-9 years after it was published in a paper... but the derived formula is the same anyhow.

By the way, still waiting to get a green light from @kluever on this.

**Comment by kluever** [comment]
Yep, still on my TODO list...sorry for the wait!

**Comment by kevinb9n** [comment]
Would most users be as well served by a counter that they increment each time put() returns true?  (It doesn't address the combining case, but other than that?)

**Comment by tcbeutler** [comment]
I'd argue that the counter suffers from any of the same drawbacks as the formula above - it's still susceptible to collisions, so it's still an approximation. Users needing perfect precision for cardinality shouldn't be using a BloomFilter anyway. From an implementation standpoint, this requires changes to pretty much everything, including serialization (potentially breaking backward compatibility with serialized filters) and would require a change to BitArray::putAll method signature. I would be very surprised if the differences in approximations were anything but negligible.

**Comment by kluever** [comment]
I think @kevinb9n was advocating for keeping a **separate** counter, external to the `BloomFilter` API.

**Comment by tcbeutler** [comment]
Oh! Sorry about that. I agree that works for most users, although the limitation also extends to situations where the filters are being deserialized. Being a probabilistic data structure, the approximate count is intrinsic to the object the same way mightContain() is, so this would allow the object to be passed around without having to pair it with a count.

**Comment by kevinb9n** [comment]
Note that the formula seems to use an approximation: it divides by `-k/m` instead of dividing by `ln(1 - k/m)` (which is what would fall out of solving `X = m - m * (1 - k/m)^n` for `n`). This is a fair approximation only because `k/m` should be very small.

My assumption is that `k/m` is SO small that this really doesn't matter, though I'm not sure we shouldn't just do the full formula anyway.

If you were interested in applying your same testing methodology to the full formula to see what happens, that might be useful information.

I should also add that we don't currently have good data at hand on what parameters people's Bloom Filters tend to have in the wild, so we don't know if we're evaluating the right scenarios.

**Comment by kevinb9n** [comment]
Although the commit marked this closed, your feedback on it is still welcome, tcbeutler. We made substantial changes.

**Comment by tcbeutler** [comment]
Glad to see this added - thanks you!

Bit of rambling ahead...

For fun @kevinb9n regarding the `ln(1 - k/m)` => `-k/m` substitution - it's just stopping after the first term of the Taylor series expansion for ln. Since `k/m` is constrained to being so close to 0, it's still a very accurate approximation.

If calculating `k` hashes and `m` bits from the given optimal formulas using `p` fpp and `n` expected insertions, the accuracy of the first term Taylor approximation varies almost completely on `n`. At n=100, it's already 99.65% accurate. At n=1000, it's 99.965%, and we get an extra 9 for every order of magnitude n grows. Pretty nifty.
