### ISSUE TITLE
org.sonatype.oss-parents deprecated

### ISSUE THREAD

**Issue by hcoona** [google/guava#2756]
I notice the `org.sonatype.oss-parents` is deprecated. Is there any action planed for it?

> Sonatype OSS Parent poms - oss-parents
> DEPRECATION WARNING:
> This project is no longer active or supported. We suggest to manage parent POM files for your own organization as needed. The POM files from this project no longer work with latest Maven and/or Java versions.

**Comment by ronshapiro** [comment]
Where are you seeing this within Guava?

**Comment by hcoona** [comment]
I see it from https://github.com/sonatype/oss-parents

**Comment by ronshapiro** [comment]
Does that parent pom give us anything? Could we just remove it?
