### ISSUE TITLE
ImmutableEnumMap should create defensive copy when deserializing

### ISSUE THREAD

**Issue by HaasJona** [google/guava#2762]
Currently, the `delegate` is put directly into the instance, violating Effective Java 2nd Edition, Item 76.

**Comment by cpovirk** [comment]
Thanks. We decided a while back that we weren't going to protect against outright malicious callers, so we let through this possible attack and a few others.

> [Our classes are not designed to protect against a malicious caller. You should not use them for communication between trusted and untrusted code.](https://github.com/google/guava#important-warnings)
