### ISSUE TITLE
InternetDomainName.isPublicSuffix() fails for compute.amazonaws.com

### ISSUE THREAD

**Issue by p8a** [google/guava#2763]
"compute.amazonaws.com" is not recognized as a public suffix.

**Comment by cpovirk** [comment]
AFAICT it is not, according to the current list.

Specifically, I see...
`*.compute.amazonaws.com`
...but not...
`compute.amazonaws.com`

https://publicsuffix.org/list/public_suffix_list.dat

**Comment by p8a** [comment]
"hasPublicSuffix" returns false for a few others as well: 

InternetDomainName{name=foobar.bid} has public suffix ? false
InternetDomainName{name=foobar.xyz} has public suffix ? false
InternetDomainName{name=foobar.loan} has public suffix ? false
InternetDomainName{name=foobar.win} has public suffix ? false

My understanding is if it ends in a suffix from PSL it should return true - is that correct ?

Thanks.

**Comment by cpovirk** [comment]
The following tests all pass for me:

    assertTrue(InternetDomainName.from("foobar.bid").hasPublicSuffix());
    assertTrue(InternetDomainName.from("foobar.xyz").hasPublicSuffix());
    assertTrue(InternetDomainName.from("foobar.loan").hasPublicSuffix());
    assertTrue(InternetDomainName.from("foobar.win").hasPublicSuffix());

Is there any chance that you're calling `isPublicSuffix` rather than `hasPublicSuffix`? Or might you have a copy of Guava from a few years ago, before those suffixes were added to the list?

**Comment by cpovirk** [comment]
Tentatively closing, but if you can find a way for us to reproduce this, please do reopen.
