### ISSUE TITLE
get bloomfilter approximate population 

### ISSUE THREAD

**Issue by peluo** [google/guava#2764]
I want to count the number of elements in bloomfilter.
Here is the solution discussed in stackoverflow:

http://cstheory.stackexchange.com/questions/10023/computing-the-approximate-population-of-a-bloom-filter

and here is my implementation.    
public int getPopulationApprox() {
        double proportionOf0s = 1 - bits.bitCount / (double)bitSize() ;
        return Convert.toInteger(Math.log(proportionOf0s) / (numHashFunctions * Math.log(1 - 1.0 / bitSize())) ) ;
    }

Could any one take a look? Should I push a change?

**Comment by lowasser** [comment]
Is there a difference between this issue and #2755?

**Comment by peluo** [comment]
looks different
http://cstheory.stackexchange.com/questions/10023/computing-the-approximate-population-of-a-bloom-filter

**Comment by lowasser** [comment]
Are you certain?  These both seem to be issues asking for ways to measure the approximate number of elements in a bloom filter...

**Comment by lowasser** [comment]
Based on the discussion there, this does seem like a duplicate.
