### ISSUE TITLE
Multimap clear()ing its internal collection upon remove()

### ISSUE THREAD

**Issue by JanecekPetr** [google/guava#2765]
# Our use-case
```
ListMultimap<String, Foo> foosByName = ...;
// First, Foos get added to the map. Then:
List<Foo> foos = foosByName.get("foo");
// this actually hands the object over to another thread which eventually sends it over the wire
output.send(foo);
...
// later
foosByName.removeAll("foo"); // internally calls clear() on the backing collection
```

...which throws this from another thread:
```
java.util.ConcurrentModificationException
    at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
    at java.util.ArrayList$Itr.next(ArrayList.java:851)
    at com.google.common.collect.AbstractMapBasedMultimap$WrappedCollection$WrappedIterator.next(AbstractMapBasedMultimap.java:486)
    ...
```

# Rationale
We're aggregating data into a `ListMultimap<String, Foo>`. Then, when the time is right and all data for a specific foo name has been collected, we want to send it out. This is done via handing the `List<Foo>` returned by `foosByName.get("foo")` to another thread which then _iterates_ over the list's contents and does the actual sending. While this is in progress, we can sometimes observe a `ConcurrentModificationException` being thrown because the original aggregator thread has called `foosByName.removeAll("foo")` in the meantime.

The original aggregator thread cannot instead call `List<Foo> foos = foosByName.remove("foo")` and then send the list out because its actually being sent out multiple times, to multiple destinations, upon multiple signals. But we're sure we're not mutating it in any way anymore.

# Expected behaviour
`foosByName.removeAll("foo")` should not call `clear()` on the underlying collection as it might have been handed out to someone else already. Is there any real-world reason for the call?

P.S. Obviously we changed our design as it was iffy at best. Still, the unexpected `clear()` seems to be unnecessary?

**Comment by kluever** [comment]
`Multimap.get(K)` is very clearly documented to return a view of the values for the given key.

If you're going to hand off the result of `multimap.get(key)` to another thread, you should defensively copy it into a new list (ideally, an `ImmutableList`).
