### ISSUE TITLE
API change suggestion, replace the runtime exception for Ints/Floats etc min/max with a compile time error

### ISSUE THREAD

**Issue by westonal** [google/guava#2769]
I can currently write:

```
    int max = Ints.max();
```

And I will get an exception at runtime. There is a way to enforce at least one argument while keeping the existing version for back compat if they have supplied an actual array.

The existing one changes signature to `public static int min(int[] array)`. Then a new overload would be coded as so, so that `Ints.max()` yields a compile time error.

    /**
    * Returns the greatest value present in {@code head}, {@code tail}.
    *
    * @param head an int {@code int} value
    * @param tail an array of {@code int} values
    * @return the value present in {@code tail} or {@code head} that is greater than or equal to every other value
    *     in the parameters
    */
    public static int max(int head, int... tail) {
      int max = head;
      for (int i = 1; i < tail.length; i++) {
        if (tail[i] > max) {
          max = tail[i];
        }
      }
      return max;
    }

**Comment by kevinb9n** [comment]
You may be right that we should have done this, but it's not worth breaking binary compatibility for. The error you're catching is one that I think developers are exceedingly unlikely to make.

**Comment by cpovirk** [comment]
(I suspect that the change wouldn't break binary compatibility, but I agree that it's not worth worrying about.)

**Comment by kevinb9n** [comment]
Sorry, I missed the part about keeping the method around as (int[]). That probably wouldn't break compatibility; I think it's even similar to something we did with ImmutableList long ago.

**Comment by westonal** [comment]
I suppose the signature I should have proposed would be `max(int a, int b, int... others)` because even max etc with less than 2 args makes no sense. Custom linting could also catch such cases though.
