### ISSUE TITLE
confusing about Streams.mapWithIndex

### ISSUE THREAD

**Issue by hzzz823** [google/guava#2770]
```
List<String> lst = ImmutableList.of("str");
Streams.mapWithIndex(lst.stream(), (c, i) -> {
    System.out.println(c);
    return c;
}).collect(toImmutableList());
```
its print: str
that's ok

but
```
List<String> lst = ImmutableList.of("str");
Streams.mapWithIndex(lst.stream(), (c, i) -> {
    System.out.println(c);
    return c;
});
```
this print nothing.

why that, is this a bug? or just i am a stupid😂

**Comment by hzzz823** [comment]
```
        Map<String, String> map = Maps.newHashMap();
        List<String> lst = ImmutableList.of("str");
        Streams.mapWithIndex(lst.stream(), (c, i) -> {
            map.put(c, c);
            return c;
        });
        System.out.println(map);
```
expect get  {"str", "str"} but {}

**Comment by kluever** [comment]
`mapWithIndex` is an _intermediate operation_ (which transforms a stream). You need a final _terminal operation_ to produce a result/side effect.

From the `java.util.stream.Stream` [javadocs](https://docs.oracle.com/javase/8/docs/api/?java/util/stream/Stream.html):
> computation on the source data is only performed when the terminal operation is initiated

**Comment by hzzz823** [comment]
very helpful for me to understand stream.
thank you!
