### ISSUE TITLE
Issue while using method reference in Optional.transform in version 21.0

### ISSUE THREAD

**Issue by HiteshGarg** [google/guava#2773]
From an API I have a com.google.common.base.Optional object i.e. of the guava library and I am running my project against Java 8 version. Now, if I use transform(Optional.transform) method and use Java 8 syntax of method reference to implement a Function in transform method, it throws the error shown below.

### **Example code -**

```
package guava.optional;

import com.google.common.base.Function;
import com.google.common.base.Optional;

public class MethodReferenceIssue {

    public static void main(String[] args) {
        System.out.println(getValue());
    }
    static Optional<Long> getValue(){
        final Optional<Test> testOptional = Optional.of(new Test(2L));
        return testOptional.transform(Test::getCode);
    }
}

class Test {
    private long code;

    public Test(long code) {
        this.code = code;
    }

    public Long getCode() {
        return code;
    }
}
```
```
Error

error: method transform in class Optional<T> cannot be applied to given types;
[ERROR] ode
[ERROR] reason: cannot infer type-variable(s) V
[ERROR] (argument mismatch; invalid method reference
[ERROR] method getCode in class Test cannot be applied to given types
[ERROR] required: no arguments
[ERROR] found: ? super Test 
[ERROR] reason: actual and formal argument lists differ in length)
[ERROR] where V,T are type-variables:
[ERROR] V extends Object declared in method <V>transform(Function<? super T,V>)
[ERROR] T extends Object declared in class Optional
```

Now I have solved this for now by creating a variable of type Function and then pass it as a parameter then it works fine.

### **Example code -**

```
package guava.optional;

import com.google.common.base.Function;
import com.google.common.base.Optional;


public class MethodReferenceIssue {

    public static void main(String[] args) {
        System.out.println(getValue());
    }
    static Optional<Long> getValue(){
        final Optional<Test> testOptional = Optional.of(new Test(2L));
        Function<Test, Long> testOpt = Test::getCode;
        return testOptional.transform(testOpt);
    }
}

class Test {
    private long code;

    public Test(long code) {
        this.code = code;
    }

    public Long getCode() {
        return code;
    }
}
```

**NOTE :-** this occurs with Guava version 21.0 and it works fine with guava version 20.0

**Comment by HiteshGarg** [comment]
But there is a change in Function interface and that's why there is reference issue while using the method reference. Please try to run the code sample provided here.
it is not because of transform it is because com.google.common.base.Function extends java.util.function.Function.

**Comment by cpovirk** [comment]
Your first example code compiles for me with Guava 19, Guava 20 and Guava 21. If you can share a complete sample Maven project that demonstrates the problem with Guava 21 but not one of the other versions, then we could take a look.

**Comment by HiteshGarg** [comment]
@cpovirk - I have mentioned the exact code sample and I am facing the issue in the same while running it(in this sample only). Yes, it will compile as I am also able to compile it, but it will give the mentioned error if you run the `mvn install` command or try to execute the code.
Please try executing the main and I hope you will get the same error.

**Comment by HiteshGarg** [comment]
@cpovirk - I have faced the similar issue in `public static <F, T> Iterable<T> transform(
      final Iterable<F> fromIterable, final Function<? super F, ? extends T> function) ` function as I can not use Java 8 syntax for method reference as a second parameter.
