### ISSUE TITLE
Stopwatch documentation warning to Android gives bad Ticker implementation

### ISSUE THREAD

**Issue by schallm** [google/guava#2777]
Sample code [provided](https://google.github.io/guava/releases/snapshot/api/docs/com/google/common/base/Stopwatch.html) states to use the following code:
```java
 Stopwatch.createStarted(
      new Ticker() {
        public long read() {
          return android.os.SystemClock.elapsedRealtime();
        }
      });
```
However Ticker's "read" function is supposed to return nanoseconds.  Suggested change:
```java
 Stopwatch.createStarted(
      new Ticker() {
        public long read() {
          return android.os.SystemClock.elapsedRealtimeNanos();
        }
      });
```
Without this change all my times where in μs when logging using:
```
log.info("time: " + stopwatch);
```

**Comment by kevinb9n** [comment]
Thanks so much for telling us -- it should actually be fixed in the next release candidate.

**Comment by kluever** [comment]
Fixed by https://github.com/google/guava/commit/7b2c5ccbf7b1c8c6715a6c5aa9aded6420205d83
