### ISSUE TITLE
cache.cleanUp() doesn't work, and cache.invalidateAll() is ok.

### ISSUE THREAD

**Issue by pumadong** [google/guava#2780]
I met a case in using GuavaCache.

I Create GuavaCache like this:

Cache<String, Object> cache = CacheBuilder.newBuilder()
        .maximumSize(guavaCache.size())
        .expireAfterWrite(600, TimeUnit.SECONDS)
        .build();

When use this cache, I have several cache nesting, a method with cache call another method with cache, then when I want to invalidate the cache manually.
cache.cleanUp() doesn't work, and cache.invalidateAll() is ok.

Can someone provide an explanation?
Thanks.

**Comment by lowasser** [comment]
Please be specific.  What do you mean by "doesn't work"?

cleanUp won't eliminate entries unless they've actually expired after 600 seconds.

**Comment by pumadong** [comment]
https://github.com/google/guava/wiki/CachesExplained#when-does-cleanup-happen

By the document，I thought the cleanUp() method can  eliminate entries, my understanding is wrong?

**Comment by jbduncan** [comment]
Yes I think you're right @pumadong, but I think the document also implies that `cleanUp()` can only eliminate those entries which have expired (that is, those which have existed for 600 seconds or longer).

AFAICT from the javadocs, `cleanUp()` only does "maintenance", which may include removing expired entries if the cache thinks it is necessary to do so. So by my understanding, if it did anything else (like removing non-expired entries) then that would count as errorneous behaviour.

**Comment by lowasser** [comment]
Yep.  `Cache.cleanUp` only deletes entries which have properly expired, etc. but have not yet been evicted from the cache.  It will _not_ evict entries which would not otherwise be evicted.
