### ISSUE TITLE
Refactoring StandardSystemProperty

### ISSUE THREAD

**Issue by ogregoire** [google/guava#2783]
Everytime I wanted to use `StandardSystemProperty`, it was because I was in a testing context, to render the the call to `System.getProperty(String)` abstract. The only reason I see any use to `StandardSystemProperty` is to avoid using hardcoded keys, plus a cherry-on-top access to the real value.

However, when it comes to testing, I was actually stuck with the real value of `System.getProperty(String)` (because that's what `StandardSystemProperty.value()` provides) and had to use an external framework such as [System Rules](http://stefanbirkner.github.io/system-rules/) to change the real values. I couldn't simply "mock" them.

So I never use this enum because it's either too much or too few.

I would suggest to replace `StandardSystemProperty` with an injectable, mockable layer, a bit like what exists with `Stopwatch` and `Ticker`.

My suggested approach is the following:

    public class SystemProperties {
      private static SystemProperties defaultInstance = new SystemProperties(System::getProperty);
      public static SystemProperties getInstance() { return defaultInstance; }
      public static SystemProperties getInstance(Function<String,String> mapper) { return new SystemProperties(mapper); }

      private SystemProperties(Function<String,String> mapper) { this.mapper = mapper; }
      public Optional<String> get(String key) { return Optional.ofNullable(mapper.apply(key)); }
      private String getRequired(String key) {
        String value = mapper.apply(key);
        if (value == null) { throw new RuntimeException("Expected property to exist: " + key); }
        return value;
      }

      public String fileSeparator() { return getRequired("file.separator"); }
      public String javaClassPath() { return getRequired("java.class.path"); }
      ... // All of the properties accessed through appropriately named methods.
    }

I see several advantages to this:

1. The system properties are not hardcoded by the final user (it's already the case with the current enum)
2. The properties accessor becomes injectable (it's not the case with the current enum)
3. The properties accessor isn't hard to mock: just use an existing function. (it's not the case with the current enum)
4. Access to non-standard system properties is also normalized. (it's not the case with the current enum)
5. The properties are accessed by a method to easily change under the hood (it's already the case with the current enum)

--------

The current enum and this suggestion could even live together. If we even add an interface `SystemProperty`, so that custom properties could live with standard ones (and retrofit `StandardSystemProperty` to implement that interface), we could imagine replace the method `getProperty(String)` in the above suggestion with `getProperty(SystemProperty)`.

The usage could then become:

    final SystemProperty CUSTOM_PROPERTY = SystemProperties.define("custom.property");
    @Inject SystemProperties systemProperties;
    ...
    systemProperties.get(CUSTOM_PROPERTY);

But this is already going to the next step.

-----

I could create this class and suggest a PR, but I'd like to have advice before starting it.

**Comment by ronshapiro** [comment]
This isn't something that would fit well in Guava - if you want to create your own injectable wrapper, that's fine. We don't expect injection of system properties in this manner much.
