### ISSUE TITLE
Minor cache documentation errors

### ISSUE THREAD

**Issue by ben-manes** [google/guava#2788]
1. `CacheBuilderSpec$DurationParser` states that the time unit must be in `[dDhHmMsS]` when an exception is thrown. However, the uppercase character is not allowed. Either use `Character.toLowerCase(c)` or the exception message should be changed.

2. `CacheBuilder` methods `expireAfterAccess` and `expireAfterWrite` state that an `IllegalStateException` will be thrown if any expiration setting was previously set. While it may not make sense to use both configurations, it is a supported configuration and no error is thrown. I think this constraint was valid in the first release and when relaxed the JavaDoc wasn't updated.

**Comment by Maaartinus** [comment]
In case both `expireAfterAccess` and `expireAfterWrite` are allowed, their interaction should be documented.

**Comment by ben-manes** [comment]
To clarify, they do not overwrite each others timestamp. This is because a write timestamp would be required if using `refreshAfterWrite` with `expireAfterAccess`, so the two can act independently. I think `refreshAfterWrite` was the driver for refactoring to have separate fields, as it was not part of the initial release of `CacheBuilder`. Because of that, the interaction between the two is probably fairly clear.
