### ISSUE TITLE
Getting the Event -> Subscribers mapping of an EventBus

### ISSUE THREAD

**Issue by jonatan-ivanov** [google/guava#2792]
At application start time (or anytime), I would like to print out the Event -> Subscribers mapping of an `EventBus` for informative/tracing/debugging purposes. Currently, there is no way to get this information from the `EventBus`.
This can be worked around by a wrapping around an `EventBus`, getting the `@Subscribe`d methods with reflection :( for each registration and maintaining another `Map`/`Multimap`.

I think the `EventBus` could provide this information by getting a view of the mapping from the `SubscriberRegistry`.

What do you think, is it something that could worth a pull request?

**Comment by cgdecker** [comment]
I'm closing this issue because we are no longer going to be making changes to `EventBus` other than important bug fixes. The reasons we're discouraging it and some alternatives are listed in the [EventBus javadoc](https://guava.dev/EventBus).
