### ISSUE TITLE
Guava Collections : limit permutation size / or support a sizedSubsets iterable?

### ISSUE THREAD

**Issue by dthkao** [google/guava#2794]
Is it possible to support the use case here:
http://stackoverflow.com/questions/11120985/guava-collections-limit-permutation-size

Or alternatively, provide a static function like Sets#powerSet that returns instead of "the set of all possible subsets.." the set of all possible subsets of a given size?

**Comment by dthkao** [comment]
BTW I'm happy to do the legwork to implement this, provided one of the two solutions above makes sense.

**Comment by jbduncan** [comment]
I believe this has been fixed as of https://github.com/google/guava/commit/8e7ff6a20794497109bcdae369c15d81d35dc3e7, with the introduction of `Sets.combinations(Set, int)`.

I don't know which release - 22.0 or 23.0 -  that it's planned for, however.

**Comment by lowasser** [comment]
The change itself gives it as `@since 23.0`.

**Comment by kevinb9n** [comment]
I'll add that we have every intention of a much shorter time gap between 22 and 23 than you're used to. I understand if that's not credible though. :-)
