### ISSUE TITLE
MoreObjects.ToStringHelper allow user to specify Appendable

### ISSUE THREAD

**Issue by stampy88** [google/guava#2795]
Currently the `ToStringHelper` class constructs a StringBuilder with an initial capacity of 32 in the `toString` method
```
 @Override
    public String toString() {
      // create a copy to keep it consistent in case value changes
      boolean omitNullValuesSnapshot = omitNullValues;
      String nextSeparator = "";
      StringBuilder builder = new StringBuilder(32).append(className).append('{');
```
I think it would be useful to add an instance field to ToStringHelper that holds a Appendable instance that can be given to it, or defaulted to the ` new StringBuilder(32)`. Also additional factory methods would be added to`MoreObjects` to allow the user to specify said instance, e.g. `public static ToStringHelper toStringHelper(Appendable buffer, Object self) `.  This would allow reuse of StringBuilders as opposed to creating them every time.

**Comment by stampy88** [comment]
Scratch the `Appendable`, it can throw an `IOException`. Either `AbstractStringBuilder` or just a `StringBuilder`

**Comment by kluever** [comment]
Are you noticing actual performance problems from this API?

`ToStringHelper` is designed to make writing `toString()'s` easy. If you require a super performant implementation of `toString()`, you're probably better off rolling your own.

**Comment by stampy88** [comment]
I am not having performance problems, but this seems like a good middle ground for people. There are cases were you don't want to allocate large `StringBuilders` over and over again, but want to stick with `ToStringHelper` for consistency sake. How about a `toString(StringBuilder sb)` and the original `toString()` that calls `toString(new StringBuilder(32))`? Having more flexibility seems like a win.

**Comment by stampy88** [comment]
I'd be more than happy to provider a PR

**Comment by kluever** [comment]
I still think providing more flexibility here isn't a great idea. `ToStringHelper` already builds up a linked list of wrapped entries, so it's not designed to be high performance. I worry that by providing the overload, we're going to have users trying to count the number of characters in their `toString()`s by hand, and that seems wasteful.

`StringBuilder` expands by doubling it's internal buffer...the string would have to be pretty enormous for this to happen more than a few times.

**Comment by Maaartinus** [comment]
> `ToStringHelper` already builds up a linked list of wrapped entries

I really wonder why. Building the string immediately in `add` would make it much simpler. The result would change in some strange cases, e.g., for `ToStringHelper.add("a", null).omitNullValues().toString()`, but learning to set an option before use shouldn't be hard. The result would also differ when the object changes between calls, but this doesn't seem important either. Where am I wrong?

I guess, I wouldn't use `toString(StringBuilder sb)`, but what about `appendTo(StringBuilder sb)`, which is more general (like `Joiner#appendTo`)?

**Comment by kluever** [comment]
Yea, the reason we have to store the values is to allow the `omitNullValues()` option to come anywhere in the chain. Unfortunately, changing that behavior would be a breaking change, and therefore is probably off the table.

**Comment by stampy88** [comment]
So there are cases where we get some really large strings (> 5K), so reusing large buffers (via a thread local or something) would be a win for me.

**Comment by kluever** [comment]
>5k strings means ~9 resizes of the buffer, which I'll admit is less than ideal...where are your `toString()`s being invoked? Logging? Output? Is it performance critical code?

**Comment by lowasser** [comment]
(Does it actually mean that many resizes of the buffer, though?  new StringBuilder(32).append(fiveThousandCharString) should do just one resize.  If the 5K characters all come in one append, that shouldn't incur intermediate resizes, I'd expect?

**Comment by stampy88** [comment]
It is multiple things that are appended that cause the re-sizing of the buffer so it won't be a single resize. It is generally for logging. Performance critical is relative. Profiling the code you can see that the object allocation is definitely a drag. Disabling logging which basically no-ops these toStrings across improves performance by about 20%. So I wanted to still use Guava because of the flexibility in generating the toStrings, but wanted to re-use the buffers on a per-thread basis to cut down on those large allocations. It is easy enough to roll my own, but thought this would be a good addition to guava for those folks that like a middle ground.

**Comment by kluever** [comment]
@lowasser Right, sorry, if they come all at once, it'll do 1 resize. My number was worst case.
from 2^5 (32) to 2^13 (8096) means 13-5 = 8 resizes
