### ISSUE TITLE
Is there a community chat room, such as gitter?

### ISSUE THREAD

**Issue by QubitPi** [google/guava#2800]
I'm trying to find tasks to contribute to Guava. I though it would be nice if we have an instant messaging place so we get updated on how we can contribute.(what tasks are there for pick up, which is more urgent, which is easy/time-consuming to finish, etc)

**Comment by jbduncan** [comment]
The closest thing we have a chat room currently is the [guava-discuss](https://groups.google.com/forum/#!forum/guava-discuss) mailing list.

As for setting up a Gitter or equivalent, I'm not sure how useful or feasible that would be at the current time, given how Guava is really a sort of pseudo-open source project (in that new code gets "thrown over the wall" from Google-internal and there are apparently too many issues/PRs for the Guava team to manage on their own).

Does anyone else have any other thoughts?
