### ISSUE TITLE
Guava 20 & 21 causing java.lang.NoSuchMethodError in Payara Server

### ISSUE THREAD

**Issue by aureliensauv** [google/guava#2801]
I'm using guava 21 (same error with 20) under Payara Server 4.1.1.164 (Glassfish4 fork).

The error message is : java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkNotNull(Ljava/lang/Object;Ljava/lang/String;Ljava/lang/Object;)Ljava/lang/Object;

No problem with Guava 19.

Thanks in advance.

**Comment by ogregoire** [comment]
This is a Glassfish/Payara issue: https://java.net/jira/browse/GLASSFISH-20850
