### ISSUE TITLE
Different hashCode of murmur3_128 results between Java guava 19 and c++

### ISSUE THREAD

**Issue by juehuizh** [google/guava#2803]
Here is my Java test code
```
HashCode hashCode = Hashing.murmur3_128(1318007700).hashString("domain1topic1", Charsets.UTF_8);
System.out.println(hashCode.toString()); // print out "6b478d2aa1b3a59004fe736b61c00340"
```
But c++ gives me the result "90a5b3a12a8d476b4003c0616b73fe04"

**Comment by perceptron8** [comment]
This is the same 128-bit number, only written differently. Guava's [`HashCode#toString()`](https://google.github.io/guava/releases/21.0/api/docs/com/google/common/hash/HashCode.html#toString--) returns big-endian representation. Your C++ result is probably little-endian.

**Comment by juehuizh** [comment]
Oh, yes, I missed that.
Thanks for the help!
