### ISSUE TITLE
Nested Iterators.concat breaks

### ISSUE THREAD

**Issue by serddmitry** [google/guava#2804]
Iterator<String> iter1 = Arrays.asList("1", "5").iterator();
        Iterator<String> iter2 = Iterators.concat(Iterators.singletonIterator("2"), iter1);

        assertEquals("2", iter2.next());
        assertEquals("1", iter2.next()); // iterator points to before "5" now

        Iterator<String> iter3 = Iterators.concat(Iterators.singletonIterator("3"), iter2); // prepend 3
        assertEquals("3", iter3.next());

        assertEquals("5", iter3.next()); // here we get NoSuchElementException

**Comment by cpovirk** [comment]
I haven't checked, but I wonder if this was broken by CL 112701959.

**Comment by cpovirk** [comment]
(And thanks very much for reporting this!)
