### ISSUE TITLE
Improvement for 22.0-rc1 Release Notes

### ISSUE THREAD

**Issue by jbduncan** [google/guava#2813]
I've noticed that it's not been mentioned that `BloomFilter` is now thread-safe.

@cgdecker Should this be added?

**Comment by perceptron8** [comment]
@jbduncan `BloomFilter` became thread-safe since 1 commit *after* 22.0-rc1.

**Comment by jbduncan** [comment]
@perceptron8 Oh yes! Good observation.

I'll close this issue then, as I'm sure there are plans to eventually add the thread-safe​ `BloomFilter` to 22.0 proper.
