### ISSUE TITLE
Iterables.getOnlyElement could check for List implementation

### ISSUE THREAD

**Issue by thecoop** [google/guava#2815]
Currently, `Iterables.getOnlyElement` just uses the iterator. A small optimization is to check whether the iterable implements `List` and `RandomAccess`, and if so, use `size()` and `get(0)` to get the only element. This would save an iterator allocation.

**Comment by kluever** [comment]
Interesting idea, but the downside is that every invocation would require the conditional to be executed, regardless of whether it can use the shortcut or not.

Without supporting data, we generally don't make [micro-optimizations](http://wiki.c2.com/?RulesOfOptimization) like these.
