### ISSUE TITLE
ImmutableDoubleArray should document behaviour re NaN

### ISSUE THREAD

**Issue by pmg23** [google/guava#2816]
In `ImmutableDoubleArray`, documentation ([as of 22.0-rc1](http://google.github.io/guava/releases/22.0-rc1/api/docs/com/google/common/primitives/ImmutableDoubleArray.html)) of the behaviour of `equals(Object)`, `indexOf(double)` and `lastIndexOf(double)` is ambiguous as to the treatment of NaNs.

Specific examples:
```java
ImmutableDoubleArray a = ImmutableDoubleArray.of(Double.NaN);
a.equals(a) == ? (hopefully true)
a.equals(ImmutableDoubleArray.of(Double.NaN)) == ?
a.indexOf(Double.NaN) == ?
a.lastIndexOf(Double.NaN) == ?
```

I suppose behaviour with the infinities and `-0.0` is unambiguous, but perhaps this should be documented too.

**Comment by kevinb9n** [comment]
These methods each say, "Values are compared as if by Double.equals(java.lang.Object)." Does that cover it?

**Comment by pmg23** [comment]
Hi. Sorry, I'm not sure quite how I missed that for `indexOf(double)` and `lastIndexOf(double)` - the behaviour is quite clear.

For `equals(Object)` however there is no doc comment, which is the actual problem. (It needs to exist, unlike that of e.g. `ImmutableList<T>`, whose specification is inherited from `List<T>`.)

This also goes for `ImmutableIntArray` and `ImmutableLongArray`, although of course they don't suffer from any NaN weirdness.
