### ISSUE TITLE
Deprecate most of the methods in Unsigned*s classes after move to Java 8

### ISSUE THREAD

**Issue by ykunda** [google/guava#2817]
UnsignedBytes, UnsignedInts and UnsignedLongs all have many methods that can be re-implemented using methods in the primitive wrapper classes new to Java 8, and/or deprecated and scheduled for removal.
Here are the obvious mappings I found in UnsignedInts:

Guava | Java 8
------|------
UnsignedInts.compare(int, int) | Integer.compareUnsigned(int, int)
UnsignedInts.toLong(int) | toUnsignedLong(int)
UnsignedInts.divide(int, int) | Integer.divideUnsigned(int, int)
UnsignedInts.remainder(int, int) | Integer.remainderUnsigned(int, int)
UnsignedInts.parseUnsignedInt(String) | Integer.parseUnsignedInt(String)
UnsignedInts.parseUnsignedInt(String, int) | Integer.parseUnsignedInt(String, int)
UnsignedInts.toString(int) | Integer.toUnsignedString(int)
UnsignedInts.toString(int, int) | Integer.toUnsignedString(int, int)

Similar mapping can be found in UnsignedBytes and UnsignedLongs (and possibly in the yet-to-be-released UnsignedShorts)

**Comment by lowasser** [comment]
We're certainly aware of this, but we haven't yet been deprecating *any* methods that have replacements in Java 8.  We have been documenting the equivalences, though, and we can probably do that here.

That said, I recall that in our previous research, our implementations of some of these methods were faster.  Long term, the preferred solution would probably be to upstream our implementations, but I'm not certain if we should actively recommend transitioning.

**Comment by cpovirk** [comment]
A colleague pointed out that the JDK eventually did pick up optimizations for `divideUnsigned` and `remainderUnsigned`, including intrinsics:
- https://github.com/openjdk/jdk/commit/0efdde188b30e3e62e9e950286924ea499afe18c
- https://github.com/openjdk/jdk/commit/37e28aea27c8d8336ddecde777e63b51a939d281

I don't know how many of the other methods had performance concerns, but the above two, at least, should be in good shape under newer JDKs.
