### ISSUE TITLE
Ordering.immutableSortedCopy should accept wildcard

### ISSUE THREAD

**Issue by turbanoff** [google/guava#2829]
Ordering.immutableSortedCopy should allow to pass wildcard type (Similar to ImmutableList.copyOf()).

    public <E extends T> ImmutableList<E> immutableSortedCopy(Iterable<? extends E> elements).

We use it sometimes, but lack of wildcard forces to use ugly casts.

**Comment by ronshapiro** [comment]
With Java 8's enhanced comparators, we're trying to not make any changes to `Ordering`. The `ImmutableSortedSet.copyOf(Comparator, Iterable)` method should do the trick, right?
