### ISSUE TITLE
null unsupported checks only look for NPEs

### ISSUE THREAD

**Issue by mebigfatguy** [google/guava#2832]
The test
```java
@CollectionFeature.Require(value = SUPPORTS_ADD, absent = ALLOWS_NULL_VALUES)
  public void testAddAll_nullUnsupported() {
    List<E> containsNull = singletonList(null);
    try {
      collection.addAll(containsNull);
      fail("addAll(containsNull) should throw");
    } catch (NullPointerException expected) {
    }
    expectUnchanged();
    expectNullMissingWhenNullUnsupported(
        "Should not contain null after unsupported addAll(containsNull)");
  }
```

only catches NPE. My collection throws IllegalArgumentException when null is presented, and thus testlib fails the test. Seems like any exception really should be caught. or at least IAE

**Comment by lowasser** [comment]
Can you explain in more detail why you think IAE should be accepted?

The `Collection.addAll` Javadoc specifies that an NPE should be thrown "if the specified collection contains a null element and this collection does not permit null elements."  The JDK has a similar policy generally of throwing NPE on null elements.  This looks like it's checking the spec correctly to me?

**Comment by mebigfatguy** [comment]
well, there is this
* @throws IllegalArgumentException if some property of the element
     *         prevents it from being added to this collection

but ok. if NPE is expected to be thrown, then i'll change it. throwing NPEs is just so ugly
