### ISSUE TITLE
Confusion over throwing exception on remove() after a hasNext()

### ISSUE THREAD

**Issue by mebigfatguy** [google/guava#2833]
I am running
```@CollectionFeature.Require(absent = KNOWN_ORDER, value = SUPPORTS_ITERATOR_REMOVE)
  public void testIterator_unknownOrderRemoveSupported() {
    runIteratorTest(MODIFIABLE, IteratorTester.KnownOrder.UNKNOWN_ORDER, getSampleElements());
  }
```
on a set, and the stimuli running is

[hasNext, hasNext, next, hasNext, remove]

My set throws an IllegalStateException on the remove, but the reference does not throw an exception.

thus, it fails, in

```if (referenceException == null) {
      if (targetException != null) {
        Helpers.fail(targetException, "Target threw exception when reference did not");
      }
```

Am i wrong in throwing that exception? i thought once hasNext() was called, the remove couldn't be called...

**Comment by lowasser** [comment]
FWIW: I believe the reference implementation is `ArrayList`?

The Javadoc of `remove()` makes no reference to `hasNext`.  It specifies that ISE can be thrown if next hasn't been called at all, or if remove has been called "after the last call to the next method."  It certainly doesn't say `hasNext()` invalidates a `remove()` call, and the phrasing "after the last call to the next method" pretty strongly implies other calls are acceptable in between.

**Comment by mebigfatguy** [comment]
ok. thank you.
