### ISSUE TITLE
addAll(c) on a values() collection of a Map

### ISSUE THREAD

**Issue by mebigfatguy** [google/guava#2835]
Greetings, 

This test

```java
  @CollectionFeature.Require(SUPPORTS_ADD)
  public void testAddAll_supportedNonePresent() {
    assertTrue(
        "addAll(nonePresent) should return true", collection.addAll(createDisjointCollection()));
    expectAdded(e3(), e4());
  }
```
in CollectionAddAllTester

is called for my Map, and keySet() and entrySet() of the map, which is fine.
but it is also calling for the values() collection of the map. How is that supposed to work? How am i supposed to generated keys?

**Comment by lowasser** [comment]
How are you configuring your MapTestSuiteBuilder?  It sounds like maybe you're passing CollectionFeature.SUPPORTS_ADD, which you shouldn't be doing?  None of the views of a Map should support add methods, as per their Javadoc.

**Comment by mebigfatguy** [comment]
Yes, i am passing SUPPORTS_ADD. ok, will remove. thanks

**Comment by luisvega10** [comment]
Hello. My cell phone device have been hack and I have coming across off a lot of damage that the hacker have cause using my device I have limeted control of the cell phone any how I need help

**Comment by slimshadeey1** [comment]
@luisvega10 I think you might be in the wrong place, maybe try gsm hosting forums.
