### ISSUE TITLE
Version badge points to 22.0-android

### ISSUE THREAD

**Issue by cpovirk** [google/guava#2839]
The badge on https://github.com/google/guava, that is. I guess that it considers 22.0-android to be the newest version? I thought we concluded that Maven considered 22.0 to be greater than 22.0-android, so perhaps this is just a bug in the badge service.

Ideally we'd probably pick 22.0, or really we might do both. I'm not sure if it's worth hacking up something manually, though, or trying to get https://github.com/jirutka/maven-badges to do the right thing.

(The doc links to [instructions on how to depend on Guava](http://search.maven.org/#artifactdetails%7Ccom.google.guava%7Cguava%7C22.0-android%7C), so getting it right would at least be helpful.)

**Comment by cpovirk** [comment]
@elharo pointed out to me that [the Maven metadata](https://repo1.maven.org/maven2/com/google/guava/guava/maven-metadata.xml) also considers 22.0-android to be the most recent :(

We'd seen [some docs](https://docs.oracle.com/middleware/1212/core/MAVEN/maven_version.htm#MAVEN400) that said that all versions with qualifiers come before all versions without qualifiers. It sounds like that [had](https://stackoverflow.com/a/31482463/28465) [changed](http://wayback.archive.org/web/20150520230652/https://docs.codehaus.org/display/MAVEN/Versioning) as of Maven 3.0. [Now](https://maven.apache.org/ref/3.3.3/maven-artifact/apidocs/org/apache/maven/artifact/versioning/ComparableVersion.html) all qualifiers other than the standard ones (alpha, beta, rc, etc.) come after all the final version.

Maybe we should have 23.0-android and 23.0-server or something similar? I'm sure that will surprise people who just try to bump the version to 23.0, though. (I guess we could have 23.0, 23.0-android, *and* 23.0-server, with 23.0 identical to 23.0-server, but I'm not sure that's really buying us a lot, since people who use 23.0 may still end up with 23.0-android.)

**Comment by cgdecker** [comment]
Now that I think about it, I wouldn't be surprised if this (Maven considering 22.0-android to be latest) simply has to do with the fact that I released 22.0 first and 22.0-android second (they can't be done at the same time AFAICT).

**Comment by cpovirk** [comment]
I would like to think that Maven is smart enough to look for the "highest" version in any case (e.g., in case we were to go back and release a 22.0.1 after 23.0), but it's certainly possible that it uses release order as a tiebreaker when it's unsure what to do with the qualifier. After looking at https://cwiki.apache.org/confluence/display/MAVENOLD/Versioning, though, I'm pessimistic: "notice that the proposal reverted the order: in Maven 2, 2.0.1-xyz < 2.0.1 but in Maven 3, 2.0.1 < 2.0.1-xyz." Still, I think it's worth a shot, since presumably releasing the two in the other order isn't hard to try. And for what it's worth, no one has reported a problem other than elharo@.

**Comment by cgdecker** [comment]
That's odd, though, because it sounds like it would mean that 23.0-rc1 > 23.0.

**Comment by perceptron8** [comment]
> Strings are checked for well-known qualifiers and the qualifier ordering is used for version ordering. Unknown qualifiers are considered after known qualifiers, with lexical order (always case insensitive),

https://github.com/apache/maven/blob/master/maven-artifact/src/main/java/org/apache/maven/artifact/versioning/ComparableVersion.java

@cgdecker "" is the same as "final", so 23.0-rc1 < 23.0 = 23.0-final. It's definitely not about release order.

**Comment by cgdecker** [comment]
I see, thanks.

I'd suggest that for starters we just get rid of the Maven version badge since the README itself is generally kept up to date with the latest release.

**Comment by cpovirk** [comment]
Sounds like a good move.

Hopefully Gradle users aren't having too much trouble with 22.0-android as "latest."

**Comment by JakeWharton** [comment]
Anyone using movable dependency resolution deserves trouble. But +1 for
killing the badge.

**Comment by cpovirk** [comment]
(Colin did remove the badge. I'll close this in favor of #2914, which has some more discussion about versioning in general.)
