### ISSUE TITLE
Optimize {Byte,Char}Source.isEmpty() for known-non-empty sources

### ISSUE THREAD

**Issue by michaelhixson** [google/guava#2843]
The default implementations of `{Byte,Char}Source.isEmpty()` seem to do unnecessary work when the size is known to be non-zero.

Here is what `ByteSource` does now:

```java
public boolean isEmpty() throws IOException {
  Optional<Long> sizeIfKnown = sizeIfKnown();
  if (sizeIfKnown.isPresent() && sizeIfKnown.get() == 0L) {
    return true;
  }
  // Fall back to reading a byte from the input stream...
```

I feel like it should do this instead:

```java
public boolean isEmpty() throws IOException {
  Optional<Long> sizeIfKnown = sizeIfKnown();
  if (sizeIfKnown.isPresent()) {
    return sizeIfKnown.get() == 0L;
  }
  // Fall back to reading a byte from the input stream...
```

That way it avoids reading the input stream when the size is known to be non-zero.

I see warnings in the javadocs that some sources report inaccurate sizes, but the example given is non-empty files that report a size of zero.  Are there empty files that falsely report a non-zero size?  If not, I think this change is safe.

**Comment by jbduncan** [comment]
I think both of those source code examples are equivalent, functionality- and performance-wise, because the `&&` operator _short-circuits_ by my understanding. This means that `sizeIfKnown.get() == 0L` will only be evaluated if `sizeIfKnown.isPresent()` evaluates to true.

Consequently, I believe this change doesn't really do anything.

**Comment by JakeWharton** [comment]
The change skips reading a byte in the known, non-empty case.

**Comment by jbduncan** [comment]
> The change skips reading a byte in the known, non-empty case.

I admit I struggle to see why. Can you give an example?

**Comment by JakeWharton** [comment]
When `sizeIfKnown()` returns `Optional.of(1000L)`, compare when the method returns. In the first case `ifPresent()` is true but `get() == 0L` is false thus the `if` is not taken. In the second case `isPresent()` is true so the `if` is taken, and then `false` is returned.

**Comment by jbduncan** [comment]
Oh, I see now! Thanks for enlightening me. :)

**Comment by cpovirk** [comment]
Colin would know if there's a reason that this is the way it is.

**Comment by cgdecker** [comment]
I can't think of a particular reason that it needs to be like it is. The suggested change is probably good. If we trust the known size when it's 0, I don't think there's any reason we shouldn't trust it when it's non-0.
