### ISSUE TITLE
Add Equivalence Relation

### ISSUE THREAD

**Issue by ivan-osipov** [google/guava#2851]
When we have some reflexive symmetric transitive relation between two instances of one class then an equivalence relation is a helpful assistant for check that this relation was accounted in code earlier.
For example we processed a relation between two people (p1, p2) and we don't want to process a relation (p2,p1) because it is the same. We put (p1, p2) to a set and when we invoke 'contains' method for (p2, p1) on the set we will get true.

[More about Equivalence Relation](https://en.wikipedia.org/wiki/Equivalence_relation)
[Example of implementation](https://github.com/ivan-osipov/guava/commit/007e471f459085edea9a04a13e08c40af4659911)

**Comment by Stephan202** [comment]
Guava already provides an [`Equivalence`](https://github.com/google/guava/blob/master/guava/src/com/google/common/base/Equivalence.java) class. If I understand correctly, that seems to be what you're looking for.

**Comment by lowasser** [comment]
It sounds to me instead like this is a request for an unordered pair class that can be put into `Set`s.  This is at least a reasonable API, but we've generally been against pair classes; I'm not sure if unordered pairs are likely to be different.

**Comment by jrtom** [comment]
Why not represent this as an undirected common.graph.Graph with a self-loop incident to each node?  That's an obvious representation of a reflexive symmetric relation; transitivity is either implicit via reachability or you can enforce it when you add an edge.

**Comment by ivan-osipov** [comment]
@Stephan202 as I know the goal of an Equivalence class to define a strategy to check equality of objects, I offer the class for storing a relation between objects
@lowasser exactly, it's sort of an unordered pair. In my opinion, when we use a pair - we try to simplify life for ourself, but when we use Equivalence Relation we try to improve our algorithms
@jrtom perhaps, we can, but if we want to keep our code understandable it becomes a not good idea. And Equivalence Relation can support nullable values.

**Comment by ronshapiro** [comment]
Seems like the options provided here cover most of the requested features. Feel free to comment if you think this issue isn't sufficiently addressed with them and we can reopen.
