### ISSUE TITLE
Guava 22.0 introduced new runtime dependencies

### ISSUE THREAD

**Issue by TheIndifferent** [google/guava#2855]
Annotation libraries do not have `optional` any more, and are now runtime dependencies. In those libraries there are very few `RetentionPolicy.RUNTIME` annotations, and even those are not processed by Guava itself.

Please change scope of those dependencies to `<scope>provided</scope>` to have them at compile time but not to drag them into runtime.

**Comment by JakeWharton** [comment]
Dupe of #2824

**Comment by TheIndifferent** [comment]
Ok, in that case following line is not true any more: https://github.com/google/guava/blob/master/guava/pom.xml#L18

**Comment by cpovirk** [comment]
Thanks. I'll remove that line.
