### ISSUE TITLE
Make Throwables.getCausalChain and Throwables.getRootCause cyclic reference safe

### ISSUE THREAD

**Issue by mehretaban** [google/guava#2866]
Exception cause can be set by initCause method which can lead to a circular reference:
```java
Exception cause = new Exception();
Exception exception = new Exception(cause);
cause.initCause(exception);
```
Calling `Throwables.getCausalChain( exception )` or `Throwables.getRootCause( exception )` could lead to an infinitive loop.

It is good idea to use a `Set` to add cause exceptions to avoid iterating over a circular reference when `Set.add` method returns `false`.

**Comment by kluever** [comment]
Another option (instead of using a set) would be to use the old "fast pointer/slow pointer" trick.

I guess our only option would be to throw a runtime exception if we detect a loop?

**Comment by cpovirk** [comment]
FWIW, I agree that it's _possible_ to cause an infinite loop here, but I'm not sure it's worth the small amount of code and the small runtime cost to avoid it. Then again, we could argue that these two methods are already trivial to write yourself, so it's worth doing everything we can to make them justify their existence.

I suppose that `getCausalChain` already has a `List` that it can call `contains` on (albeit in linear time, but presumably most chains aren't long enough for that to matter)....

I still tend to think it's not worth worrying about, but there are some thoughts, anyway.

**Comment by Maaartinus** [comment]
> Another option (instead of using a set) would be to use the old "fast pointer/slow pointer" trick.

AFAIK this is only useful when you don't have enough memory for the whole loop.

---

kevinb9n has already commented on this: https://stackoverflow.com/a/7586027/581205

I guess, people requesting this got confused by `Throwable` initializing cause to itself, which leaks when using reflection (e.g., converting to JSON). Besides this dirty trick, I doubt that there are loops out there.

**Comment by kluever** [comment]
The only reason that I'm a little sympathetic to this request, is that I could see these APIs being used in exception handling code, which is often untested/unexecuted. If the user did have a causal chain with a loop, they wouldn't know it until the exception handling code was invoked (in production), at which point they'd get tossed into an infinite loop.

**Comment by cpovirk** [comment]
Contrary to what Kevin says, I think that `printStackTrace` is smart enough to avoid this. I forget whether that protection existed from the beginning, though, or whether it was added when suppressed exceptions were. (Suppressed exceptions maybe make it slightly more believable that a loop would exist.)

**Comment by mehretaban** [comment]
As you mentioned `printStackTrace` method is smart enough to avoid this loop by using a `Set` collection. 

I describe importance of this issue through an example: if Guava is used in exceptions processing frameworks/projects which their consumers are unknown and also exceptions could be thrown from many different reliable and unreliable sources it might put exception processing framework into an unknown state which is not acceptable unless to avoid using Guava for this particular case and using a custom solution similar to what JDK does for `printStackTrace`.
