### ISSUE TITLE
"Caches Explained" wiki page should probably mention UncheckedExecutionException as well

### ISSUE THREAD

**Issue by tebello-thejane** [google/guava#2867]
Without reading the Javadocs, there is no way to know that the `get` method -- in addition to `ExecutionException` -- could also throw `UncheckedExecutionException` (and `ExecutionError`).

These are unchecked exceptions, and so the compiler is of little help, and unexpected things happen when the code is run. Programming in Haskell has spoiled me...

In my case, this just bit me as I was using Guava to cache Hibernate DB code, an unchecked `javax.persistence.NoResultException` was throw, and my `catch` clause which unwraps the original, underlying exception failed to work:
```Java
try {
    return theCache.get(theKey);
} catch (ExecutionException e) {
    throw e.getCause();
}
```

Could the wiki please be updated to note these unchecked exceptions?

**Comment by lowasser** [comment]
Updated: https://github.com/google/guava/wiki/CachesExplained/313fe22da68bca83ad5b688a1df39dbcb91a9208

**Comment by vkopichenko** [comment]
@lowasser, the change was soon overwritten by @cgdecker, unfortunately: https://github.com/google/guava/wiki/CachesExplained/_compare/490fcb89f45e798fcbd28b875103079358f51d75...226a3060445716d479981e606f589c99eee517ca
I guess, that was by mistake and should be remerged properly.

**Comment by vkopichenko** [comment]
@kluever, I vote for reopen.

**Comment by cgdecker** [comment]
Re-fixed this.
