### ISSUE TITLE
Algorithm for finding n-cliques, max clique(s) in a Graph

### ISSUE THREAD

**Issue by findepi** [google/guava#2868]
Please enhance `Graphs` with a method finding n-cliques, max clique (or cliques) in  a `Graph`. 
I am aware this cannot be implemented efficiently (finding max clique is a NP-complete problem), but that doesn't unfortunately mean it's useless :)

**Comment by jrtom** [comment]
It's unlikely that we would add something like this to Guava; while there are certainly good reasons to be looking for cliques (of various sorts) in a graph, the use cases are fairly specialized, by Guava's standards.

The next version of  [JUNG](http://jrtom.github.io/jung/), which is a more full-featured graph library, will be using the common.graph types; we're working on that conversion right now (see the common.graph branch for the current state of things).  Feel free to file a feature request there.
