### ISSUE TITLE
Add Uninterruptibles support for Condition

### ISSUE THREAD

**Issue by ChristianSchwarz** [google/guava#2870]
It would be nice to have Uninterruptibles support for Condition.await() and overlaods.

So we could write

```
lock.lock();
try{
  awaitUninterrutibly(condition,1,MINUTE);
}finally{
 lock.unlock();
}
```

**Comment by cpovirk** [comment]
This is a case where this probably won't be a high priority for us but we'd be happy to take a patch. You might also be interested in [`Monitor`](http://google.github.io/guava/releases/snapshot/api/docs/com/google/common/util/concurrent/Monitor.html), which includes `waitForUninterruptibly`.

**Comment by cpiotr** [comment]
Hey, I've created https://github.com/google/guava/pull/3005 and it would be great, if you could review it.

**Comment by cpiotr** [comment]
Hey, I've created #3010 where I squashed commits into one and it would be great, if you could review it.

**Comment by cpovirk** [comment]
Do you care much about the `Date` (`awaitUntilUninterruptibly`) version included in your CL? Even though we're just mirroring an existing API, we're always a little hesitant to even suggest that `Date` is a good idea, especially for elapsed time.

**Comment by cpiotr** [comment]
I don't care much about this one, to be honest. 
Shall I remove it and repeat the process (squash and send PR)?

**Comment by ronshapiro** [comment]
No need to squash and create a new PR, just add new commits to the PR and we'll handle the squashing

**Comment by cpovirk** [comment]
We make the changes internally, anyway, so I can just remove it from my local copy.

**Comment by cpiotr** [comment]
Sounds good to me.
