### ISSUE TITLE
Add default methods to ListenableFuture for chaining

### ISSUE THREAD

**Issue by sfussenegger** [google/guava#2871]
Maybe an idea worth discussing (or at least one to quickly be dismissed): How about adding (some of) the methods from `Futures` as default methods to `ListenableFuture` for nice chaining:

```java
public interface ListenableFuture<V> extends Future<V> {

    void addListener(Runnable listener, Executor executor);

    default <O> ListenableFuture<O> transform(Function<? super V, ? extends O> function) {
        return Futures.transform(this, function);
    }

    default ListenableFuture<V> withFallback(final FutureFallback<? extends V> fallback) {
        return Futures.withFallback(this, function);
    }

    // TODO: add more
}
```

old:

```java
ListenableFuture<Foo> f1 = executor.submit(task);
ListenableFuture<Bar> f2 = Futures.transform(f1, (foo) -> toBar(foo));
ListenableFuture<Bar> f3 = Futures.withFallback(f2, (ex) -> handleEx(ex));
```

new

```java
ListenableFuture<Bar> f = executor.submit(task)
    .transform((foo) -> toBar(foo))
    .withFallback((ex) -> handleEx(ex));
```

Note: The call to `Futures.transform(..)` is ambiguous as the compiler can't figure out if it's `Function` of `FunctionAsync`. Adding methods named `transformSync(..)` and `transformAsync(..)` would help the compiler (and readability).

**Comment by jbduncan** [comment]
@sfussenegger I think that the recent addition of [`FluentFuture`](https://google.github.io/guava/releases/snapshot/api/docs/com/google/common/util/concurrent/FluentFuture.html) (planned for 23.0 IIRC) more or less resolves this (albeit without extending `ListenableFuture` without default methods, as you requested).

What do you think?

**Comment by sfussenegger** [comment]
@jbduncan Nice. Same idea but a different implementation.

**Comment by jrtom** [comment]
FYI, IIUC, Guava is unlikely to be using default methods in the near future because they aren't available in the Java 7 version.  Because we try to keep the 8 and 7 versions as close as possible, we generally end up using mechanisms that don't take advantage of Java 8.
