### ISSUE TITLE
Link to RangeMap documentation is missing in the right panel of the wiki 

### ISSUE THREAD

**Issue by debraj-manna** [google/guava#2872]
The link to [RangeMap](https://github.com/google/guava/wiki/NewCollectionTypesExplained#rangemap) documentation is missing in the right panel of the wiki under pages as shown below:-

<img width="243" alt="screen shot 2017-07-13 at 2 39 02 pm" src="https://user-images.githubusercontent.com/8141860/28159078-6b30d7f8-67d9-11e7-9b61-60d3d1e70e6e.png">

**Comment by kluever** [comment]
Thanks, fixed!
