### ISSUE TITLE
Primitive Lists should overwrite spliterator to return primitive spliterator

### ISSUE THREAD

**Issue by bokken** [google/guava#2874]
Java 8 defined specific primitive spliterators for doubles, ints,  and longs.

The primitive lists of those specific types in com.google.common.primitives should implement spliterator and return those primitive optimized spliterators.

**Comment by bokken** [comment]
The intent of my request is to allow for the framework to provide better optimized Streams. By default, the spliterator provided is based on the iterator implementation. This not only is not going to optimize access for an array, it is not likely to support splitting to allow parallel streams. Additionally, it guarantees auto-boxing is going to take place, as that is how AbstractList implements an Iterator.

**Comment by cpovirk** [comment]
Are we all talking about [`ImmutableIntArray`](http://google.github.io/guava/releases/snapshot/api/docs/com/google/common/primitives/ImmutableIntArray.html) and friends? As Louis says, they currently [expose an `IntStream`](http://google.github.io/guava/releases/snapshot/api/docs/com/google/common/primitives/ImmutableIntArray.html#stream--), from which you can get a `Spliterator.OfInt`, and [it's a "pure" `IntStream`](https://github.com/google/guava/blob/551343910c2974abf0e81d7728d975c6164f26b3/guava/src/com/google/common/primitives/ImmutableIntArray.java#L415), not a boxing one.

**Comment by bokken** [comment]
No, I am talking about the List returned from [Longs.asList(long...)](http://google.github.io/guava/releases/snapshot/api/docs/com/google/common/primitives/Longs.html#asList-long...-) and friends.
I apologize for not stating that more clearly in the original request.

**Comment by lowasser** [comment]
This makes more sense to me now, but it's not automatically clear to me we can get the desired improvements.  `Longs.asList(long...).stream()` still has to return a `Stream<Long>`, not a `LongStream`, and we can't really expose new API methods on it.  It's not super clear to me whether overriding their internal spliterator implementations will actually result in the desired improvements, or just move the boxing from one place to another, but we can investigate.

**Comment by bokken** [comment]
Auto boxing will still (likely) occur through streams. The stream implementation itself will be more efficient based on the backing long[] compared to the List's default Iterator.

**Comment by ronshapiro** [comment]
What about using `ImmutableLongArray.copyOf()`? Then you can get either the boxed or unboxed streams?
