### ISSUE TITLE
MapJoiner does not handle "null value"

### ISSUE THREAD

**Issue by NicolaSpreafico** [google/guava#2876]
I'm using Guava 20 (I cannot use a greater version because I'm running on App Engine standard with Java7 and I haven't migrated to Java8 yet).

Here an example code which reproduce the issue

```
static class B {
    private String value;

    public B(String string) {
        this.value = string;
    }

    @Override
    public String toString() {
        return this.value;
    }
}

public static void main(String[] args) {
    Map<A, B> map = new HashMap<>();

    map.put(new A("one"), new B("1"));
    map.put(new A("two"), null);

    String join = Joiner.on(",").withKeyValueSeparator(": ").join(map);
    System.out.println(join);
}
```

When the map has a null value, a NPE is thrown
```
Exception in thread "main" java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770)
	at com.google.common.base.Joiner.toString(Joiner.java:454)
	at com.google.common.base.Joiner$MapJoiner.appendTo(Joiner.java:385)
	at com.google.common.base.Joiner$MapJoiner.appendTo(Joiner.java:415)
	at com.google.common.base.Joiner$MapJoiner.join(Joiner.java:441)
	at com.google.common.base.Joiner$MapJoiner.join(Joiner.java:430)
	at com.google.common.base.Joiner$MapJoiner.join(Joiner.java:348)
```

Is this a known behaviour?

**Comment by perceptron8** [comment]
http://google.github.io/guava/releases/22.0/api/docs/com/google/common/base/Joiner.html

> If neither skipNulls() nor useForNull(String) is specified, the joining methods will throw NullPointerException if any given element is null.

**Comment by jbduncan** [comment]
To add to @perceptron8's answer, it's a known thing with Guava that when the Javadoc isn't explicit, passing `null` even indirectly to any parameters will cause `NullPointerException` to be thrown.

https://github.com/google/guava/wiki/UsingAndAvoidingNullExplained

**Comment by SangHakLee** [comment]
@perceptron8 

Does it actually work now?

```
java.lang.UnsupportedOperationException: can't use .skipNulls() with maps
```
