### ISSUE TITLE
Consider removing CombinedFutureInterruptibleTask/rejectionPropagatingExecutor tracking of thrownFromDelegate/thrownByExecute

### ISSUE THREAD

**Issue by cpovirk** [google/guava#2877]
...in favor of just calling `setException` unconditionally.

I wrote in a code review:

> There's a decent argument that the work we do here and in MoreExecutors.rejectionPropagatingExecutor isn't really buying us much, since it's not clear where else a RejectedExecutionException would be coming from. And even if it is coming from somewhere else, the most plausible location of all the implausible locations is "somewhere after we already called set/setException/setFuture/cancel," in which case we could still call setException(), confident in the knowledge that it will be a no-op.
> 
> Or maybe I'm forgetting something important. Beats me :) But certainly it's hard (impossible?) to write a test that covers this case.

**Comment by charlesmunger** [comment]
setException() after setFuture is not a noop, but I don't disagree with the general premise. I suppose it's theoretically possible for something to escape when setting the listeners on the Future... but again, Future catches RuntimeExceptions thrown from execute(), and from misbehaving objects passed in to setFuture().

**Comment by cpovirk** [comment]
(`setException()` after `setFuture()` [should still be a no-op](https://github.com/google/guava/blob/71703b40b42c96dd1fef03a760e2e648db11f792/android/guava/src/com/google/common/util/concurrent/AbstractFuture.java#L674), weird as it is for `setException` to fail when the `Future` is not yet done. I actually forget why we did it that way. I guess it's probably faster to do the `setException` CAS that way, but I don't know that that would have driven our decision, especially since we could do an optimistic CAS first.)

**Comment by cpovirk** [comment]
(I see a bit of internal discussion of the "no-op" question in go/hjmjt, but it doesn't go into a ton of detail.)
