### ISSUE TITLE
readFully() in ByteArrayDataInput object isn't marked to throw EOFException, though it does throw it

### ISSUE THREAD

**Issue by shakram02** [google/guava#2879]
`readFully()` on an `ByteArrayDataInput` object is documented to throw an `EOFException` and it actually does. But it seems to override the parent interface `DataInput` and removes the exception from signature [source from guava repo](https://github.com/google/guava/blob/6ded67ff124f1be4f318dbbeae136d0c995faf37/guava/src/com/google/common/io/ByteArrayDataInput.java#L37). I'm using Guava v22 , java8 and intellij

This snippet throws an `EOFException`

```Java 
        ByteArrayDataInput inputStream = ByteStreams.newDataInput(new byte[]{1, 2, 3});
        byte[] largeBuff = new byte[50];
        inputStream.readFully(largeBuff);
```

This snippet doesn't compile (though it would throw an exception if it had compiled)
Error
`java: exception java.io.EOFException is never thrown in body of corresponding try statement`

```Java
        ByteArrayDataInput inputStream = ByteStreams.newDataInput(new byte[]{1, 2, 3});
        byte[] largeBuff = new byte[50];
        try {
            inputStream.readFully(largeBuff);
        } catch (EOFException e) {
            System.out.println(e.getMessage());
        }
```

This sounds like bad news in language design, but I hope I'm wrong, This doesn't compile also with `IOException` is never thrown error
```Java
interface D {
    void f() throws IOException;
}

interface E extends D {
   @Override
    void f();
}

public class Main {
    public static void main(String[] args) {
        E ob = new E() {
            @Override
            public void f() {

            }
        };

        try {
            ob.f();
        } catch (IOException e) {
        }
    }
}

```

**Comment by perceptron8** [comment]
The snippet doesn't throw `EOFException` - it does throw `IllegalStateException` however with `EOFException` as a cause.

**Comment by shakram02** [comment]
aha so it just covers up the exception, I missed that point that you so much
