### ISSUE TITLE
Document EventBus intended working wrt children events

### ISSUE THREAD

**Issue by oliviercailloux** [google/guava#2880]
I have three events: ModelChangedEvent, LabelChangedEvent, and IndexChangeEvent. The last two are children of the first one. My model has labels and indexes.
When a change occurs in my model, I’d like to post either a LabelChangedEvent or an IndexChangeEvent, but not have to post a (redundant) ModelChangedEvent.
Still, I’d like listeners to be able to listen to either ModelChangedEvent (and be called automatically whenever any of the children events, or ModelChangedEvent itself, are raised), or the specific children.

Does that make sense? Does EventBus support such use? Please document accordingly.

**Comment by cgdecker** [comment]
I'm closing this issue because we are no longer going to be making changes to `EventBus` other than important bug fixes. The reasons we're discouraging it and some alternatives are listed in the [EventBus javadoc](https://guava.dev/EventBus).
