### ISSUE TITLE
GraphTraverser?

### ISSUE THREAD

**Issue by jbduncan** [google/guava#2885]
In the Guava 23.0 [release notes](https://github.com/google/guava/wiki/Release23), there was a mention of a class `GraphTraverser` which AFAICT isn't in the open source version of Guava. Is it a real class in Google-internal Guava? If so, are there any plans to eventually release it?

**Comment by kevinb9n** [comment]
Whoops, sorry. No, GraphTraverser is a dead end that you'll never have to see in Guava.

**Comment by jbduncan** [comment]
Okey dokey, thanks for the quick response @kevinb9n!

I'll keep this issue open for now. If or when the Guava 23.0 release notes are fixed, I'll close it. :)

**Comment by cgdecker** [comment]
I've removed that reference from the release notes, thanks.

**Comment by jbduncan** [comment]
Ta @cgdecker! :+1:
