### ISSUE TITLE
UnsignedBytesTest.unsafeComparatorAvailable() should catch NoClassDefFoundError

### ISSUE THREAD

**Issue by pavel-vyssotski** [google/guava#2888]
The method try to initialize unsafeComparator and expect ExceptionInInitializerError or ClassNotFoundException if initialization fails. Actualy the static initializer throws Error if something goes wrong to "force fallback to PureJavaComparator". According to spec JVM transfers it to ExceptionInInitializerError for the first time and starting from second genertates NoClassDefFoundError (not ClassNotFoundException, no exceptions allowed to be thrown from static initializer).
```
   try {
      Class.forName(unsafeComparatorClassName());
      return true;
    } catch (ExceptionInInitializerError | ClassNotFoundException tolerable) {
      // probably running on Android
      return false;
    }
```
Guess this is a missprint and author was intended to use NoClassDefFoundError here.

**Comment by cpovirk** [comment]
The types that we're catching are the ones documented to be thrown by [`Class.forName`](https://docs.oracle.com/javase/8/docs/api/java/lang/Class.html#forName-java.lang.String-). They're also sufficient to catch the failure we've seen if the class fails to load. If you're seeing something else thrown, let us know.

**Comment by pavel-vyssotski** [comment]
For example, the ForNameTest.java:
public class ForNameTest {

  public static void main(String[] argv) {
    System.out.println("sun.arch.data.model: " + System.getProperty("sun.arch.data.model"));
    try {
      Class.forName("unsafeComparator");
    } catch (Throwable t) {
      System.out.println("1st - " + t);
    }
    try {
      Class.forName("unsafeComparator");
    } catch (Throwable t) {
      System.out.println("2nd - " + t);
    }
  }
}

class unsafeComparator {
  static {
    if (!("32".equals(System.getProperty("sun.arch.data.model"))))
      throw new Error();
  }
}

produce the following output:
java -showversion ForNameTest
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

sun.arch.data.model: 64
1st - java.lang.Error
2nd - java.lang.NoClassDefFoundError: Could not initialize class unsafeComparator

**Comment by cpovirk** [comment]
Thanks! Sorry that I didn't try it myself. The failures we've seen have all been under Android, which may be implementing `Class.forName` differently. I'll see what I can do about this (and maybe report an Android bug, too).
