### ISSUE TITLE
Allow ImmutableMap.Builder#build merge

### ISSUE THREAD

**Issue by Maaartinus** [google/guava#2910]
The default conflict resolution by throwing is fine most of the time, but sometimes, conflicting keys are acceptable as you either don't care about the values as in #360 (choosing the bigger city might be an option).

Sometimes, you can't do anything about the conflicts, like when I was importing inconsistent third party data recently. Letting the later inserted values win might help in cases like in #2252. 

Therefore, I'm suggesting `ImmutableMap.Builder#build(BinaryOperator<Entry<K, V>> merger)`. It should be rather easy to implement. In case of no conflict, the merger doesn't get used and building is as efficient as without it. Otherwise, some simple tweaks are needed like possible cloning and final shrinking of `entries` in `fromEntryArray`, something like ten to twenty code lines. To keep things simple, the iteration order would be always according to the first occurrence of the key, regardless of what the `merger` returns.

**Comment by lowasser** [comment]
Note there is [already](http://google.github.io/guava/releases/23.0/api/docs/com/google/common/collect/ImmutableMap.html#toImmutableMap-java.util.function.Function-java.util.function.Function-java.util.function.BinaryOperator-) a `Collector` supporting a merge operation.

**Comment by Maaartinus** [comment]
I missed it. I could have used it, though it'd need some rewrite while the builder feels natural (as two methods are adding entries). This collector is cheating with a `LinkedHashMap` temporary, unlike the two argument variant using the builder.

I guess, the three argument variant could be trivially implemented using my proposed build method. If there are few merges, it'd be probably way more efficient. With many merges, the builder could grow much bigger than the map.

All the alternatives make the builder look an unwanted child.
