### ISSUE TITLE
the  expectedInsertions long or int?

### ISSUE THREAD

**Issue by itismewxg** [google/guava#2915]
in 2 create functions, with fpp setting it's INT, but given the default one (0.03), it's LONG, what is the point? in fact, by the way, can we expect more than MAX_INT insertion for this bloomfilter implementation?

**Comment by itismewxg** [comment]
any clarification?

**Comment by jbduncan** [comment]
@itismewxg Just to be sure, are you talking about BloomFilter or something else?

**Comment by itismewxg** [comment]
Yes, I mean Bloomfilter,

**Comment by itismewxg** [comment]
so, still no answer?

**Comment by kluever** [comment]
I looked back at the history, and we initially had `expectedInsertions` as an `int`, and then changed it to a `long`. However, we later re-added the `int` overloads of `create()` to preserve binary compatibility.

> Re-add create() methods with an int expectedInsertions parameter.
> These methods should probably live on indefinitely for binary compatibility.
> Also add @since 19.0 to the versions with a long parameter, since they're technically newly added methods, and add a paragraph from the 3-param version that was missing to the 2-param version.
