### ISSUE TITLE
Automatic-Module-Name missing from sub-module manifests

### ISSUE THREAD

**Issue by cowwoc** [google/guava#2920]
Version 23 was supposed to add `Automatic-Module-Name` to the manifest file but it only did so for `guava-parent`: https://github.com/google/guava/blob/v23.0/pom.xml#L119

Please add `Automatic-Module-Name` for all sub-modules otherwise JDK9 clients will end up with the wrong module name.

**Comment by jodastephen** [comment]
I just hit this too. The `Automatic-Module-Name` needs to go in the main Guava jar file, not the parent (or any other jar files (eg. not in guava-testlib or guava-tests).

**Comment by zyxist** [comment]
I think this should be fixed and released ASAP as 23.1 for example, given the fact that there is less than 20 days to JDK9 General Availability.

**Comment by orionll** [comment]
Any progress on this issue? 23.1 was released today, but I do not see `Automatic-Module-Name` in the manifest/
