### ISSUE TITLE
Get All Classes by a Package Name

### ISSUE THREAD

**Issue by gilshamgar** [google/guava#2923]
I needed a way to get all classes that starts with a certain package name, followed by a ".".
The only way to do that is by getting all the classes (ClassPath.getAllClasses()) and filtering the result by yourself. There's no reason that we could only get the top classes by a certin package name, and not all.
I'm asking for a simple change, to add the following 2 methodes:

```
  /** Returns all classes whose package name is {@code packageName}. */
  public ImmutableSet<ClassInfo> getAllClasses(String packageName) {
    checkNotNull(packageName);
    ImmutableSet.Builder<ClassInfo> builder = ImmutableSet.builder();
    for (ClassInfo classInfo : getAllClasses()) {
      if (classInfo.getPackageName().equals(packageName)) {
        builder.add(classInfo);
      }
    }
    return builder.build();
  }
  
  /**
   * Returns all classes whose package name is {@code packageName} or starts with
   * {@code packageName} followed by a '.'.
   */
  public ImmutableSet<ClassInfo> getAllClassesRecursive(String packageName) {
    checkNotNull(packageName);
    String packagePrefix = packageName + '.';
    ImmutableSet.Builder<ClassInfo> builder = ImmutableSet.builder();
    for (ClassInfo classInfo : getAllClasses()) {
      if (classInfo.getName().startsWith(packagePrefix)) {
        builder.add(classInfo);
      }
    }
    return builder.build();
  }
```

**Comment by perceptron8** [comment]
How about [ClassPath.getTopLevelClasses(String)](https://google.github.io/guava/releases/23.0/api/docs/com/google/common/reflect/ClassPath.html#getTopLevelClasses-java.lang.String-) and [ClassPath.getTopLevelClassesRecursive(String)](https://google.github.io/guava/releases/23.0/api/docs/com/google/common/reflect/ClassPath.html#getTopLevelClassesRecursive-java.lang.String-)?

**Comment by gilshamgar** [comment]
I need all mthe classes, that's including inner classes, not just top level classes.

**Comment by perceptron8** [comment]
Oh, I was misled by code (`getTopLevelClasses()` instead of `getAllClasses()` in for loops). It makes sense now.

**Comment by gilshamgar** [comment]
You are correct, my bad. Edited.

**Comment by perceptron8** [comment]
One more catch: in `getAllClassesRecursive(String packageName)`, similar to [ClassPath.html#line.151](https://google.github.io/guava/releases/23.0/api/docs/src-html/com/google/common/reflect/ClassPath.html#line.151), you should check that `classInfo.getName().startsWith(packagePrefix)` instead of `classInfo.getPackageName().startsWith(packagePrefix)`, otherwise you exclude base package (`packageName` doesn't start with `packageName + "."`).

**Comment by gilshamgar** [comment]
Thanks again man! Fixed

**Comment by ronshapiro** [comment]
I don't think the code that this saves is common enough/complicated enough to warrant a method in Guava. It's also much simpler with Streams.

**Comment by Tacodiva** [comment]
I disagree with the above.
If your criteria is "if it's easy to implement with streams it shouldn't be a part of Guava" then why is there `getTopLevelClasses(package)` and `getTopLevelClassesRecursive(package)` at all? Both of these can be implemented from `getTopLevelClasses()`, in the exact manor that the new methods suggest here could be from `getAllClasses()`. 

| | Every Class | Top Level Only |
| --- | --- | --- |
| **Everything**| `getAllClasses()` | `getTopLevelClasses()` |
| **In Package** | ??? | `getTopLevelClasses(packageName)` |
| **In Package Recursive** | ??? | `getTopLevelClassesRecursive(packageName)` |

It seems blindingly obvious to me that there should be two more methods `getAllClasses(packageName)` and `getAllClassesRecursive(packageName)`, as this issue suggests.
