### ISSUE TITLE
Guava 23 `edgeValueOrDefault` missing edge returns non-default value

### ISSUE THREAD

**Issue by rocketraman** [google/guava#2924]
In Guava 23...

Assume `nodeA` exists but  #`nodeU` does not exist. Execute:

`graph.edgeValueOrDefault(nodeA, nodeU, 5)`

The result is `null`. I would expect the result to be `5`, given that there is no edge between `nodeA` and non-existent `nodeU`. Guava 22 an earlier have the expected behavior.

I see that Guava 23 now returns an `Optional` for `edgeValue`, so the statement can easily be converted to `graph.edgeValue(nodeA, nodeU, 5).orElse(5)`, however if this is the intended behavior of the `edgeValueOrDefault` method for this situation, it deserves some additional explanation in the Javadoc. Or simply deprecate this method and recommend people transition to `edgeValue().orElse()`.

**Comment by jbduncan** [comment]
Now that Guava going to have more frequent releases and thus 23.2 is likely to be released before 24, I wonder if it would make sense to shift the milestone to 23.x.

@cpovirk, do you have any thoughts on this?

**Comment by cpovirk** [comment]
Thanks. Tentatively renamed to "NEXT." @ronshapiro @cgdecker may have more thoughts.

**Comment by cpovirk** [comment]
(And I moved the 2 closed issues that were tagged 24.0 to a new 23.1 milestone, since they both made it into that release.)

**Comment by jrtom** [comment]
Somehow I completely failed to notice this issue previously; my apologies.

The behavior of `edgeValueOrDefault()` wasn't intended to change from 22.0 to 23.0; I introduced a regression when doing some internal refactoring that apparently wasn't caught by our tests.  Sorry about that.

I'll get a fix out for that as soon as I can.

**Comment by jrtom** [comment]
Fixed (see above commit).  Thanks, @rocketraman.
