### ISSUE TITLE
Feature request: ImmutableSet.toImmutableSet

### ISSUE THREAD

**Issue by phillipao** [google/guava#2925]
There's probably a good reason why we've had ImmutableList.toImmutableList since 21, but not this yet. But hey, doesn't hurt to ask :)

**Comment by lowasser** [comment]
https://google.github.io/guava/releases/21.0/api/docs/com/google/common/collect/ImmutableSet.html#toImmutableSet--

This has been there since 21.0, too =)

**Comment by phillipao** [comment]
Thanks! 🤦
