### ISSUE TITLE
Suppliers.memoize should take an option to memoize exceptions

### ISSUE THREAD

**Issue by kannanekanath** [google/guava#2928]
Related Pull request to fix the documentation https://github.com/google/guava/pull/2916 has been merged. 

If the delegate in the Suppliers.memoize throws an exception on calling get() then further calls to the get() method of the Memoized suppliers still goes to the delegate. With the pull request the Javadocs clarify that there is a danger that the underlying delegate could be called more than once. 

What we need is a method with the following signature

`Suppliers.memoize(Supplier<T> delegate, boolean memoizeExceptions)`

By default the single argument memoize method could delegate to the above method with a "false" flag i.e, exceptions are NOT memoized by default. However if true is passed then even when the delegate throws an exception, that exception is stored by the memoized supplier and is re-thrown everytime it is called.

**Use cases where this can be used**

- A class X uses a memoized Supplier the delegate talks to an external Paypal like service or a configuration service. When the delegate fails we do not want to retry the external service (until such time as we have a notification that the external service is back up in which case class X re-initializes the supplier)
- A class X has a memoized supplier with expiration of 5 seconds and wants an absolute guarantee that even in the case of failures the underlying delegate is NEVER called more than once in 5 seconds.

I am happy to contribute a patch if this new API is accepted.

**Comment by kannanekanath** [comment]
Any updates? I am very happy to contribute a patch if people think this is a sensible change to implement

**Comment by kevinb9n** [comment]
I will express the opinion that I don't think it is a good idea to memoize an exception. When it is thrown or logged later, the stack trace may be highly confusing.

I believe you want to create a result object that encapsulates whatever the state is that you want to have memoized. If this is an object that embodies either a successful or failed result, I think this satisfies both of your use cases.

**Comment by PierceHanley** [comment]
Just an opinion, but I feel like memoizing the exception could have some "surprising" behavior:

- As @kevinb9n mentioned, it would still have the original stacktrace when it's rethrown on subsequent calls, which could be confusing and unhelpful to people trying to debug it.
- Exception classes sometimes assume that they're going to be immediately used by the "catch" block and then discarded. Some of them might store "heavyweight" data, expecting that will be garbage collected shortly. Or they may even reuse and modify objects within the exception at a later time, which would be (incorrectly) reflected when the original exception is rethrown later.

I think it's better if it's responsibility of the original supplier to provide additional behavior like memoizing exceptions (as appropriate to your application) or throttling calls.

**Comment by kevinb9n** [comment]
I wonder if a useful generalization of this advice is, "don't threat Throwable instances as data."

**Comment by tgdavies** [comment]
You can make the type of the Supplier `Supplier<Either<Exception,T>>` and catch in your Supplier implementation.

**Comment by kdvolder** [comment]
> , it would still have the original stacktrace when it's rethrown on subsequent calls, which could be confusing and unhelpful to people trying to debug it.

I disagree. The stacktrace is helpful because it will actually point directly to the point where the problem occurred (i.e where the value was being computed). Which usually what you want to know. Gramted, it won't point to the call that requested the value from the cache. But if guava library wanted to address that concern, it could do so simply by wrapping the exception in a new exception and using the memoized exception as it's cause.

You can debate around whether the objects are 'too heavy' to store in a cache. But isn't that choice ultimately upto the user of the library to make? After all guava doesn't stop me in general from memomizing any other kinds of 'heavy object' which I could returned as regular return values.

**Comment by tkruse** [comment]
Even if the first exception is not memoized, the behavior of a second call in case the first call threw an exception could be configurable. Such that the second time throws a new Exception that just states that no memoized value is available. The point is that the memoize function might be used to protect some resource, and the repeated calling might defeat the purpose of having a memoized supplier for protection.

**Comment by kannanekanath** [comment]
As original requestor of this issue and having read Guava guideline that "If you find something is missing in guava, you should log a request and do your own thing" that is exactly what I did. 

In general I agree it is perhaps not a good idea to store an exception as a member variable which we have to store if we are to throw the exact exception. In my code I have done exactly that. As @tkruse points out if that is a problem you can store a boolean variable to throw some generic exception message. 

The key problem here is that the original purpose of **protecting** an underlying resource from being flooded is actually made **more worse** by Guava as it gives the impression to the developer that it is a good idea to wrap expensive calls into this method. If not already done this should at least be clarified in the javadoc to avoid confusion.
