### ISSUE TITLE
Guava's Maven dependencies are suddenly extensive

### ISSUE THREAD

**Issue by shs96c** [google/guava#2932]
Animal Sniffer and Error Prone would seem to be compile-time dependencies. JSR305 isn't needed at runtime either, particularly from Find Bugs. Previously, guava had no additional runtime dependencies, which is one of the things that made it attractive.

**Comment by jbduncan** [comment]
Related issues: https://github.com/google/guava/issues/2824, https://github.com/google/guava/issues/2721.

I personally agree that these dependencies shouldn't be needed at all for any other than compile time, but those issues seem to point out that certain people had problems with that arrangement, so the Guava team decided to accommodate them.

**Comment by shs96c** [comment]
What a pity that maven doesn't have a mechanism for saying "this dependency is needed at compile time, but not at runtime"

**Comment by jgangemi** [comment]
it does...you can use `<optional>true</optional>` on the dependency.

https://maven.apache.org/guides/introduction/introduction-to-optional-and-excludes-dependencies.html

consumers who need the dep at runtime still need to declare it.

**Comment by kashike** [comment]
@jgangemi https://github.com/google/guava/commit/0e29934933f33379de953727171f7ca1ec616a58

**Comment by jgangemi** [comment]
mmm - should have read those related issues first as well. still seems incorrect to add those deps and then require ppl to explicitly exclude them but this isn't the place to continue that conversation.
