### ISSUE TITLE
why we made the bloomfilter as the final class

### ISSUE THREAD

**Issue by itismewxg** [google/guava#2933]
here is the requirements:

I need to manipulate the bits array directly in my case, but since the bloomfilter is a final class, I cannot extend and use such private member directly.
the only way I can do is to hack, use the bloomfilter instance as a member, and repeat what you do for the bitarray. :(
any explanation why set it to be final class?

**Comment by itismewxg** [comment]
still it's about the implementation of the bloomfilter
https://github.com/google/guava/blob/master/guava/src/com/google/common/hash/BloomFilter.java

**Comment by jbduncan** [comment]
> any explanation why set it to be final class?

I think it's final for the reason given in [Effective Java 2nd Edition](https://www.amazon.co.uk/Effective-Java-Second-Joshua-Bloch/dp/0321356683), _Item 16: Favor composition over inheritance_.

**Comment by jbduncan** [comment]
...but the Guava team may be able to clarify if I'm mistaken on this. :)

**Comment by lowasser** [comment]
It's more item 17: design and document for inheritance <i>or else prohibit it</i>.

If we let `BloomFilter` be subclassable, then we can't change its implementation later if we have a better implementation.  IIRC this has <i>already</i> been an issue for BloomFilter in terms of changes to its serialization behavior?  In any case, the best practice is to make classes final wherever possible.  BloomFilter is not designed to let you manipulate the bit array directly; it's not even guaranteed to have a bit array, or to have that bit array implemented in any particular way.  If you need a particular implementation, the best way to do it is to make your own.
