### ISSUE TITLE
add getDefault(object, index, default) method to ObjectArrays and Lists

### ISSUE THREAD

**Issue by bramhaag** [google/guava#2940]
Scenarios like the following happen way too often:
```java
List<Integer> myList = ...;
int myInt = myList.size > 1 ? myList.get(1) : -1;
```
My suggestion is to add a method to the `ObjectArrays` and `Lists` classes which gets an element out of a list/array or returns the default value when the index of the element is out of bounds.

Example usage:
```java
List<Integer> myList = ...;
int myInt = Lists.getDefault(myList, 1, -1);
```
This could also be done with `Optional`s:
```java
List<Integer> myList = ...;
int myInt = Lists.get(myList, 1).orElse(-1);
```

**Comment by jrtom** [comment]
IMO, it is a bad idea to use `myInt` to store something that is either (1) a valid entry or (2) an indicator that the someone tried to access an element using a bad index.

I'm curious about a couple of things:
(1) What are you doing with the value of myInt after that point?
(2) What is the actual problem for which this seems to you like the best solution?

**Comment by cardamon** [comment]
This is already in `Iterables`, no?
```java
Iterables.get(myList, 1, -1);
```
And its docs also note the JDK8 equivalent, which could also be used for arrays:
```java
Arrays.stream(myArray).skip(1).findFirst().orElse(-1);
```

**Comment by kluever** [comment]
+1 to what @cardamon said. `Iterables.get()` even does an `instanceof` check to support `O(1)` access for a `List` vs. `O(n)` for an unknown `Iterable`.
