### ISSUE TITLE
ImmutableMap's key set's spliterator is not splittable

### ISSUE THREAD

**Issue by epkugelmass** [google/guava#2948]
Java 8u144 (Mac 10.11.6)
Guava 23.0

Expected: Calling `parallelStream()` on an ImmutableMap-derived Set should lead to pipeline execution on multiple threads. Calling `spliterator()` on a ImmutableMap-derived Set should yield a splittable (`trySplit() != null`) spliterator.

Actual: Pipeline executes on main thread only. Spliterator is not splittable.

Diagnosis:
The spliterator is ultimately constructed using an `IntStream#range` which is sequential. The `AbstractWrappingSpliterator` that results from the `mapToObj` checks the stream context and refuses to split if the stream is sequential (even though the underlying spliterator is splittable, see `trySplit:189, StreamSpliterators$AbstractWrappingSpliterator (java.util.stream)`). `RegularImmutableSet` and friends are constructed using `ArraySpliterator`, which don't have this problem.

```
range:798, IntStream (java.util.stream)
indexed:94, CollectSpliterators (com.google.common.collect)
indexed:40, CollectSpliterators (com.google.common.collect)
spliterator:386, ImmutableSet$Indexed (com.google.common.collect)
parallelStream:602, Collection (java.util)
```

```
public class Problem {

  public static void main(String[] args) {
    Set<String> list = Stream.iterate("a", str -> str + "a")
        .limit(1000)
        .collect(toImmutableMap(Function.identity(), Function.identity()))
        .keySet();

    Logger logger = Logger.getAnonymousLogger();
    logger.info("Parallel stream is parallel: " + list.parallelStream().isParallel());
    logger.info("Parallel stream's spliterator can be split: "
        + (list.parallelStream().spliterator().trySplit() != null));

    ThreadLocal<Boolean> invoked = ThreadLocal.withInitial(() -> false);

    list.parallelStream()
        .map(str -> {
          if (invoked.get()) {
            return str;
          }
          invoked.set(true);
          logger.info("Parallel stream executed on thread " + Thread.currentThread().getName());
          return str;
        })
        .forEach(str -> {});
  }

}
```

Expected:
```
INFO: Parallel stream is parallel: true
INFO: Parallel stream's spliterator can be split: true
INFO: Parallel stream executed on thread main
INFO: Parallel stream executed on thread ForkJoinPool.commonPool-worker-4
INFO: Parallel stream executed on thread ForkJoinPool.commonPool-worker-2
...
```

Actual:
```
INFO: Parallel stream is parallel: true
INFO: Parallel stream's spliterator can be split: false
INFO: Parallel stream executed on thread main
```

**Comment by lowasser** [comment]
*sigh* Confirmed.  That's...a little embarrassing, on the built-in stream library's part?  That `mapToObj` destroys splittability.  But I've confirmed it.  A fix won't be difficult.

**Comment by cpovirk** [comment]
https://github.com/google/guava/commit/e2a4a28427011c05702cf2c1568c5067baed5337
