### ISSUE TITLE
airportdiffusion.alwaysdata.net is not under public suffix

### ISSUE THREAD

**Issue by jozsefilles** [google/guava#2950]
Hi,

I ran into the domain name _airportdiffusion.alwaysdata.net_ which seems to be a valid one under the public suffix _alwaysdata.net._ Surprisingly, the following Junit test piece fails:

```
    @Test
    public void isUnderPublicSuffix() throws MalformedURLException {
        InternetDomainName name = InternetDomainName.from("airportdiffusion.alwaysdata.net");
        Assert.assertTrue(name.isUnderPublicSuffix());
    }
```

After debugging the Guava code, I found that _findPublicSuffix()_ returns zero index. This means that the whole domain name is a public suffix.

https://github.com/google/guava/blob/e2a4a28427011c05702cf2c1568c5067baed5337/guava/src/com/google/common/net/InternetDomainName.java#L169

Could you please point me in the right direction whether I use Guava the wrong way or it's a bug in the Trie pattern or the code?

Thanks,
Jozsef

**Comment by swankjesse** [comment]
Compare these two registrations in publicsuffix.org:

```
// alwaysdata : https://www.alwaysdata.com
// Submitted by Cyril <admin@alwaysdata.com>
*.alwaysdata.net

// Amazon CloudFront : https://aws.amazon.com/cloudfront/
// Submitted by Donavan Miller <donavanm@amazon.com>
cloudfront.net
```

The leading `.*` in the first one says that _every_ subdomain of `alwaysdata.net` is a publicsuffix, and you need two subdomains `a.b.alwaysdata.com` to have a private domain.

The second one says that every subdomain of `cloudfront.net` is itself a private domain.

**Comment by jozsefilles** [comment]
Thanks for the info!
