### ISSUE TITLE
Incomplete `com.google.common.graph.Traverser` implementation in 23.1?

### ISSUE THREAD

**Issue by jbduncan** [google/guava#2953]
In version 23.1, it looks to me that `com.google.common.graph.Traverser` has been released, but that the class has not been fully implemented yet. Was it intended to release Traverser so soon?

/cc @cgdecker

**Comment by jrtom** [comment]
It wasn't, but I hadn't known that we were releasing a point version of 23.  

I mean, IMO it doesn't hurt anything, but I would prefer to wait on releasing such things until they're done.  Meanwhile, enjoy the sneak preview, I guess... :)

**Comment by jbduncan** [comment]
SGTM @jrtom. I'll close this issue then, as I anticipate this will resolve itself eventually. :)
