### ISSUE TITLE
Any contributors interested in participating in Hacktoberfest? 

### ISSUE THREAD

**Issue by jspengeman** [google/guava#2958]
Hacktoberfest looks like a good opportunity to get some project exposure as well as get some issues worked. Any contributors/maintainers interested in tagging some issues with the `hacktoberfest` label?

**Comment by ronshapiro** [comment]
I don't think it makes sense to start tagging particular issues for particular events/hackathons, but we're always open to receive contributions. Hackathoners are welcome to check the issue list and see what speaks to them!

**Comment by jspengeman** [comment]
Awesome! Just thought I would toss the idea out there.
