### ISSUE TITLE
ClassPath.getTopLevelClasses() returns empty list (Again)

### ISSUE THREAD

**Issue by UnAfraid** [google/guava#2959]
Hello,

This is continue of #2152 the problem still exists, but this time on java 9.

```log
java version "9"
Java(TM) SE Runtime Environment (build 9+181)
Java HotSpot(TM) 64-Bit Server VM (build 9+181, mixed mode)
```
I've tested with 22.0, 23.0, 23.1

**Comment by cpovirk** [comment]
The problem with special characters? Or just that it doesn't work with Java 9 at all? If the latter, it should be fixed in [23.1](https://github.com/google/guava/releases/tag/v23.1).

**Comment by UnAfraid** [comment]
Tested with 23.1 as well, on java 8 it works fine but on java 9 not discovering anything.

**Comment by cpovirk** [comment]
How are you constructing the `ClassPath` instance?

**Comment by UnAfraid** [comment]
Same way as shown in #2152 
```java
    @Test
    public void testMain() throws Exception {
        ClassLoader loader = this.getClass().getClassLoader();
        ClassPath p = ClassPath.from(loader);
        ImmutableSet<ClassPath.ClassInfo> list = p.getTopLevelClasses("testpackage");
        Assert.assertEquals(3, list.size());
    }
```

**Comment by vstepchik** [comment]
Upgrading to 23.1 fixed the issue for me.
```
openjdk version "9"
OpenJDK Runtime Environment (build 9+181)
OpenJDK 64-Bit Server VM (build 9+181, mixed mode)
```
Using like this from kotlin:
```kotlin
val topClasses = ClassPath.from(SomeClass::class.java.classLoader).topLevelClasses
```
