### ISSUE TITLE
API report for Guava

### ISSUE THREAD

**Issue by lvc** [google/guava#2963]
Hi,

I'd like to share the report on API changes and backward compatibility for the Guava library, which I maintain as a hobby: https://abi-laboratory.pro/java/tracker/timeline/guava/

It's generated by the https://github.com/lvc/japi-tracker tool according to the article https://wiki.eclipse.org/Evolving_Java-based_APIs_2.

Hope it will be helpful for users and maintainers of the library.

Thank you.

![guava-2](https://user-images.githubusercontent.com/1517837/31373004-03ee7b5a-ada1-11e7-8307-1186db74f83a.png)
![guava-1](https://user-images.githubusercontent.com/1517837/31373005-040f91a0-ada1-11e7-8376-d2a89a917753.png)

**Comment by netdpb** [comment]
This looks like a really interesting tool! Maybe we should incorporate it into our release pages.

**Comment by lvc** [comment]
See also report for Guava GWT: https://abi-laboratory.pro/java/tracker/timeline/guava-gwt/

**Comment by kluever** [comment]
The page hasn't been updated since Guava 23.0.

If we wanted to incorporate it into our release pages, we'd need to have it automatically generated/updated regularly.

**Comment by cpovirk** [comment]
(23.0 was the last Guava release with a "normal" version number. As of 23.1, the the release to analyze would be of the form "23.1-jre." I suspect that that's the problem here.)
