### ISSUE TITLE
Any way to redirect http://google.github.io/guava/releases/snapshot/api/docs/ to http://google.github.io/guava/releases/snapshot-jre/api/docs/?

### ISSUE THREAD

**Issue by cpovirk** [google/guava#2968]
I had the old location bookmarked, and I was wondering why it wasn't updating :) I figured it out, but it would be nice if we had a way to redirect the old, since links exist (though perhaps [not very many](https://www.google.com/search?q=%22google.github.io%2Fguava%2Freleases%2Fsnapshot%22+-inurl%3A%22google.github.io%2Fguava%22)).

**Comment by kashike** [comment]
A symlink should work.

**Comment by cgdecker** [comment]
I wasn't expecting that simply replacing the `snapshot` directory with a symlink to the `snapshot-jre` directory would work, but it actually does. Ok, it does _sort of_: it doesn't actually _redirect_ to the `snapshot-jre` URL, it just sort of aliases `snapshot-jre` as `snapshot` (which is probably expected, really, given how symlinks work). Actual redirects would probably be better (to canonicalize the URLs), but I'm inclined to think this is good enough for now.

Actual redirects could probably be handled by populating the `snapshot` directory with a "copy" of the `snapshot-jre` directory where every `.html` file is replaced with a `.html` file that simply has a `meta` redirect to the `snapshot-jre` location. The script that generates Javadoc/JDiff could be updated to ensure that the set of files under `snapshot` matches that under `snapshot-jre` at all times.
