### ISSUE TITLE
Custom exceptions in Preconditions

### ISSUE THREAD

**Issue by ptomaszek** [google/guava#2972]
Could you please reconsider extending `Preconditions` with custom exceptions?
This is a follow up on #1388.

First, reasoning against such feature summed up from #1388 (mostly [this comment](https://github.com/google/guava/issues/1388#issuecomment-61351926)):
1. `Preconditions` are for programming errors (e.g. NPEs), not business logic
2. Performance issues in creating exceptions

Counterargument:
1. Looks programmers would appreciate it :) , see https://www.google.com/search?q=guava+preconditions+custom+exception& 
2. Newest Guava leverages Java 8, so now a lightweight implementation is possible:
    ```java
    public final class Preconditions {
    (...)
        public static void checkArgument(boolean expression, Supplier<? extends RuntimeException> exceptionSupplier) {
            if (!expression) {
                throw exceptionSupplier.get();
            }
        }
    (...)
    }
    ```
    and usage:
    ```java
    checkArgument(expression, () -> new MyCustomRuntimeException());
    ```

**Comment by cpovirk** [comment]
I've replied on #1388 to keep the discussion in one place.

**Comment by ptomaszek** [comment]
Thanks
