### ISSUE TITLE
Suppliers class should provide a valueOf(Supplier) method

### ISSUE THREAD

**Issue by yijunwu** [google/guava#2975]
Suppliers class has an ofInstance(T instance) method which accept a object of type T as value and return a supplier that provides that value. It would be better off that it also has a method for the opposite direction: given a supplier, return it's value. Although we can easily get the value of a supplier by calling supplier.get(), it is feasible only when we already defined a supplier explicitly, we can not do it with a **Lambda** expression. For example:

`String str = (() -> { return "abc" + "def"; }).get();` 

The code above is invalid. We have to write this: 
```
Supplier<String> supplier = () -> {return "abc" + "def"; }; 
String str = supplier.get();
```

But if Suppliers class can have a valueOf method, we can write this:

`String str = valueOf(() -> {return "abc" + "def"; });`

That would be much more elegant. Of course, with a very short amount of inner code, it's not necessary to put code into lambda, but if there are many lines of code, putting it into a Lambda will give us better code separation of concern, hence easier to understand. Besides, providing such a method does no harm to the class.

**Comment by cardamon** [comment]
> but if there are many lines of code

Wouldn't you then just typically put the code in a separate private method and just call it?

**Comment by lowasser** [comment]
If there are "many lines of code," you should pull out a method.  If there aren't, then you should just execute the logic directly in the function, not in a lambda.

**Comment by yijunwu** [comment]
> If there are "many lines of code," you should pull out a method. If there aren't, then you should just execute the logic directly in the function, not in a lambda.

Of course that's the usual way people doing that, but lambda provides an alternative way, which might be useful in some cases, e.g. 5 or 10 lines of code that I wouldn't like to put to a separate method? After all, extracting method requires clearly defining the parameters of the new method, while with lambda, we can refer to the local variables very conveniently. And I believe there are some other benefits.

**Comment by ronshapiro** [comment]
I think you've demonstrated how easy it would be to define this on your own. This API doesn't serve much use in Guava but you can surely add it to your code and use it as you wish.

**Comment by liach** [comment]
You can just cast it into one supplier.
