### ISSUE TITLE
Can i get a Generic Type Class from a T?

### ISSUE THREAD

**Issue by cao19920425** [google/guava#2978]
```
List<String> list=Lists.newArrayList();

  public static <T> void tokenTest(T object) throws Exception{
//    TypeToken<T> token=new TypeToken<T>() {};
    TypeToken<T> token=(TypeToken<T>) TypeToken.of(object.getClass());
    System.out.println(token.getRawType());
    System.out.println(token.resolveType(object.getClass().getTypeParameters()[0]));
  }
```

if i use the "TypeToken<T> token=new TypeToken<T>() {};",it will throw IllegalStateException.
if i use the "TypeToken.of(object.getClass())",it will get Class of ArrayList,but i want to get the Class of List.
Can i get the Class of List?
Can i get the Class of String?

**Comment by lowasser** [comment]
No, there is no possible way in Java to do either of those things.  You will have to construct the `TypeToken` at the site where you know the exact type, and pass it around.
