### ISSUE TITLE
Cannot compile Guava

### ISSUE THREAD

**Issue by DPLL** [google/guava#2981]
Hi I am new to Guava. I just pull the latest code from master, and run 'mvn install -DskipTests' in my local, and I got the following errors:

[ERROR] /Users/ygao/Documents/github/guava/guava-tests/target/classes/com/google/common/primitives/UnsignedLongsBenchmark.class:110: Undefined reference: String com.google.common.primitives.UnsignedLongs.toString(long, int)
[ERROR] /Users/ygao/Documents/github/guava/guava-tests/target/classes/com/google/common/primitives/UnsignedLongsBenchmark.class:111: Undefined reference: String com.google.common.primitives.UnsignedLongs.toString(long, int)
[ERROR] /Users/ygao/Documents/github/guava/guava-tests/target/classes/com/google/common/primitives/UnsignedLongsBenchmark.class:130: Undefined reference: long com.google.common.primitives.UnsignedLongs.remainder(long, long)

Do I miss anything?

Any help would be appreciated! Thanks!

**Comment by nageshever** [comment]
Hi, I have the goal as test and it worked fine.

**Comment by jhmanson** [comment]
This works for me, too.  Did you try building in a freshly cloned branch to make sure that you don't have old artifacts preventing a clean build?

**Comment by DPLL** [comment]
Thanks for the reply, after I ran "man clean install -DskipTests", it works. I think it just cleaned the old artifacts.
