### ISSUE TITLE
Feature Request: Guava Cache Configurable Item Drain Limit

### ISSUE THREAD

**Issue by saumilhukerikar** [google/guava#2984]
Currently cache cleanUp is amortized across callers during read and writes so as to avoid overly penalizing one in a bad scenario, causing odd timeouts. Hence, a single call to cleanUp() would  remove few items from cache, even though a lot more have expired. The limit on number of items that can be removed during a single call to cleanUp() [defined here](https://www.google.com/url?q=https%3A%2F%2Fgithub.com%2Fgoogle%2Fguava%2Fblob%2Fmaster%2Fguava%2Fsrc%2Fcom%2Fgoogle%2Fcommon%2Fcache%2FLocalCache.java%23L154&sa=D&sntz=1&usg=AFQjCNGqv1QW_YjlrwtGXWDVUtQdPkTvZw) is non-configurable.  

I believe this limit should be made configurable to allow developers the flexibility in configuring how the cache should be cleaned up.
 A potential use case for this would allow developers to use RemovalListener to perform business logic based on item removed and have a guarantee that all expired items would be removed from the cache by a single invocation of cleanUp(), whilst being fully aware that incase of large number of expired items there would be a possibility of a timeout.

**Comment by kluever** [comment]
@lowasser can probably give a better answer, but in general, we're not investing any more feature development into `common.cache`. Our recommendation is to use @ben-manes 's excellent [Caffeine](https://github.com/ben-manes/caffeine) cache.

**Comment by ben-manes** [comment]
Oh, in the thread I meant it could be parameterized in the internals and not as an API change. The external `cleanUp()` method could pass Integer.MAX_VALUE to the private one, or the constant for amortized usages. I don't think this should be relied upon, so it is only a nicety and wouldn't be a proper fix to your original problem.

Thanks @kluever for the shout out.
