### ISSUE TITLE
Does guava has an ECCN?

### ISSUE THREAD

**Issue by otramony** [google/guava#2985]
Hello. Our team would like to use/include your library in our product, and since we export outside of the U.S., we're required to provide ECCN (Export Control Classification Number) information for all 3rd-party libraries that may use/include encryption.

**Comment by lowasser** [comment]
Guava does not include any encryption.  The closest thing it does is provide hashing algorithms, for which it only delegates to Java's implementations; it does not include their implementations itself.

**Comment by otramony** [comment]
Thank you, Louis.

**Comment by kluever** [comment]
I'm not sure if it's a big deal for you, but it's worth nothing that we _do_ include some implementations of hashing algorithms (e.g., `Murmur3`, `SipHash`, and `FarmHash`); not all of the hashing APIs simply delegate to the Java implementations.

They are all "one-way" hashes though, and do not provide encryption/decryption functionality.
