### ISSUE TITLE
AsyncEventBus: Add options to enable ImmediateDispatcher

### ISSUE THREAD

**Issue by markowitz73** [google/guava#2986]
Since ImmediateDispatcher is depth-first and somehow "[preferable](https://github.com/google/guava/blob/master/guava/src/com/google/common/eventbus/Dispatcher.java#L54)", we should offer a choice to use this dispatcher. And for now dispatcher in AsyncEventBus is always coded to legacyDispatcher while constructing(See [AsyncEventBus](https://github.com/google/guava/blob/master/guava/src/com/google/common/eventbus/AsyncEventBus.java)).

**Comment by ronshapiro** [comment]
Should this be incorporated into https://github.com/google/guava/pull/3002?

**Comment by busybee1149** [comment]
I'm thinking another public constructor to AsyncEventBus which takes a Dispatcher would suffice. Let me know what you guys think.  
```
public AsyncEventBus(Executor executor, Dispatcher dispatcher, SubscriberExceptionHandler subscriberExceptionHandler) {
    super("default", executor, dispatcher, subscriberExceptionHandler);
  }
```

**Comment by netdpb** [comment]
Thanks for your feature request. At this point we are not actively developing EventBus. There are several more modern frameworks for event-driven or reactive programming, including [RxJava](https://github.com/ReactiveX/RxJava) among others.
