### ISSUE TITLE
Small problem compiling in Fedora 26

### ISSUE THREAD

**Issue by enriqueartal** [google/guava#2987]
I got an error when compiling the package; adding a ";" at the end of line 178 of src/leon/src/wtdist.c solves the issue

**Comment by cardamon** [comment]
Are you sure you got the right repo? I'm not seeing see such a file or folder.

**Comment by kluever** [comment]
I think you want to report this here: https://github.com/gap-packages/guava

**Comment by enriqueartal** [comment]
You are right, sorry for the noise.
