### ISSUE TITLE
ThrowablesExplained wiki link is broken

### ISSUE THREAD

**Issue by winteryoung** [google/guava#2991]
https://github.com/google/guava/wiki/ThrowablesExplained

The link to `void propagateIfPossible(Throwable, Class<X extends Throwable>) throws X` is broken.

**Comment by kluever** [comment]
Thanks! A fix will be submitted shortly!

**Comment by avarzar** [comment]
Note that another link in the table, to 'void propagateIfInstanceOf', is broken.
