### ISSUE TITLE
`Throwables.propagate` is deprecated

### ISSUE THREAD

**Issue by winteryoung** [google/guava#2992]
https://github.com/google/guava/wiki/ThrowablesExplained

`Throwables.propagate` is deprecated. The doc is outdated.

**Comment by liach** [comment]
The documentation is not outdated.
There is [Why we deprecated `Throwables.propagate`](https://github.com/google/guava/wiki/Why-we-deprecated-Throwables.propagate) addressing the deprecation.
The deprecation was mentioned at first; however, it was removed in [this change](https://github.com/google/guava/wiki/ThrowablesExplained/_compare/92190ee7e37d334fa5fcdb6db8d0f43a2fdf02e1...226a3060445716d479981e606f589c99eee517ca).
