### ISSUE TITLE
How to excute that Objects.Method of Circular reference?

### ISSUE THREAD

**Issue by cao19920425** [google/guava#3000]
I should not say that this is a guava  problem. 
In fact,  this a  common problem in Java.
How these these mehtods that include hashCode and toString excute Circular reference?

Actually,it is easy to avoid the OutOfMemory .
But i want to get a common way that correctly excute circular reference,not manual handle.

I think that way should be refer to the the serialization method of java object and json.
For example,is there such an ideal situation that the method of toString use the memory address as field value to show that this is a circular reference?

So,keep the circular reference and two objects are equal only if all the field values that  including the circular reference object are equal,do you have any suggestions?

**Comment by ooxi** [comment]
Sorry, it's not clear to me, what exactly you are asking for? However, I would suggest taking this question to a platform like stackoverflow, which is more suitable than this bug tracker
