### ISSUE TITLE
Add InetAddresses.forString() version that returns Optional

### ISSUE THREAD

**Issue by electrum** [google/guava#3001]
The current API is unwieldy when you have a string that might be an IP address literal. Catching an exception in this case feels wrong because it's not an exceptional condition and it can have performance implications (due to throw/catch + message construction).

For example, suppose you are writing an async resolver that wants to avoid executor overhead for IP address literals. With try/catch:
```java
ListenableFuture<InetAddress> resolve(String host) {
  try {
    return immediateFuture(InetAddresses.forString(host));
  } catch (IllegalArgumentException e) {
    return executor.submit(() -> resolveName(host));
  }
}
```

Parsing twice:
```java
ListenableFuture<InetAddress> resolve(String host) {
  if (InetAddresses.isInetAddress(host)) {
    return InetAddresses.forString(host);
  }
  return executor.submit(() -> resolveName(host));
}
```

We could avoid this with `Optional`:
```java
ListenableFuture<InetAddress> resolve(String host) {
  return InetAddresses.optionalForString(host)
    .map(Futures::immediateFuture)
    .orElseGet(() -> executor.submit(() -> resolveName(host)));
}
```

**Comment by ronshapiro** [comment]
The second snippet looks fine to me, what don't you like about it? The double parsing should be negligible - are you often resolving so many addresses in a tight loop for which this would really be an issue?

**Comment by ronshapiro** [comment]
I still think the second snippet looks fine, if not better, than the third. I'm going to close, and we can reopen if we get more feedback/data.
