### ISSUE TITLE
ConcurrentHashMultiset#createEntrySet() is public

### ISSUE THREAD

**Issue by Xaerxess** [google/guava#3003]
`ConcurrentHashMultiset#createEntrySet()` has public visibility, although it seems like an internal method, not meant to be in public API. 

Whole `ConcurrentHashMultiset` is not in `@Beta`, so I'm not sure if simply changing visibility to package-private is what you really want, hence no PR from my side.

**Comment by cpovirk** [comment]
Yep, that's a mistake. Want to send us a deprecation PR?

(Looks like that's the only such method that's `public`, or even `protected`, at least based on a quick search.)

**Comment by cpovirk** [comment]
(And yeah, we won't remove it, but we can steer people away. No callers inside Google, at least.)

**Comment by Xaerxess** [comment]
Sure, created PR #3004.
