### ISSUE TITLE
Guava won't transpile with j2objc with the --nullability flag

### ISSUE THREAD

**Issue by mikelikespie** [google/guava#3009]
It fails with errors like

```
/external/guava/guava/src/com/google/common/collect/Maps.java:3333:57: error: nullability specifier '_Nonnull' conflicts with existing specifier '_Nullable'
- (jboolean)testWithId:(id<JavaUtilMap_Entry> __nonnull)arg0 {
                                                        ^
```

(not sure if this is actually a j2objc bug, or a bug with the annotations. assuming guava supports j2objc cuz there are annotations all over the place)

**Comment by cpovirk** [comment]
My suspicion is that it's just that different tools treat nullability annotations as meaning different things, and j2objc/Objective C's interpretation is different from our own. This specific error looks like it may be objecting to an `apply` method that has its parameter annotated non-null but overrides a method that has its parameter annotated nullable. That's fine under our interpretation, under which "nullable" means "might accept null," but apparently not under theirs, in which it means "must accept null." Neither of those interpretations is great, but they're the best tools can do without a full [Checker Framework](https://checkerframework.org/)-style approach.

So you'd probably have to build without `--nullability`, sorry :(

(Guava does aim to support j2objc. It has some big users internally, but I have no idea whether others have tried externally. Please do let us know about other problems, assuming that the nullability one doesn't force you away.)

**Comment by cpovirk** [comment]
Realistically, I don't think we're going to be able to support another tool's interpretation of nullability annotations.
