### ISSUE TITLE
Guava cache does not have a way for providing custom eviction strategy.

### ISSUE THREAD

**Issue by ScrapCodes** [google/guava#3013]
Currently, a user can not provide a custom eviction strategy, which is evaluated at the time of eviction. The common use case scenario can be close all the producers which are recently created but are no longer used, rather than producers which are lately created and are still being used.

**Comment by lowasser** [comment]
We are not doing any active feature development on common.cache at this time.  I think at this point we recommend you investigate https://github.com/ben-manes/caffeine.

**Comment by ben-manes** [comment]
I don't think I understand the example, but you are welcome to open an issue on the Caffeine project. There are many extension points and tricks to coerce behavior, but we do prefer to encapsulate algorithmic details from the user. So delegating whether to evict an entry is an implementation detail (frequency + recency) with a limited ability to influence the choice (e.g. you can pin using a zero weight).
