### ISSUE TITLE
custom StatsCounter in CacheBuilder

### ISSUE THREAD

**Issue by solosky** [google/guava#3014]
Hi guys, I want to thank you to contribute such a great library to java community!

I want customed StatsCounter in CacheBuilder, but I found there isn't a build method for statsCounterSupplier. Since StatsCounter is a interface, I cannot figure out why did not allow user to setup a customed StatsCounter.

```
public final class CacheBuilder<K, V> {
...
 Supplier<? extends StatsCounter> statsCounterSupplier = NULL_STATS_COUNTER;
```
so would please add this feature to next release ? 
Thanks.

**Comment by liach** [comment]
I think the team would suggest using caffeine library instead.

**Comment by solosky** [comment]
@liach  Thank you suggestion. 
After looking into caffeine library,  I think it's exactly what we want. Thanks. 
Any way, I stil would happy to see the feature could add to guava library. 
Thanks everyone.
