### ISSUE TITLE
Comparators.least() parallelism

### ISSUE THREAD

**Issue by eklinger** [google/guava#3019]
Hello,
Can `Comparators.least()` be collected from a parallel stream? Does it make any sense to do so? 
In other words:
```
List<String> list = new ArrayList<>(...);
list.parallelStream().collect(least(limit, ...));
```

I am seeing a noticeable improvement in performance but want to be sure I am not going to hit any memory inconsistency effects.
Thanks!

**Comment by lowasser** [comment]
*All* properly written Collectors can be used from parallel streams; that's part of the design of the streams framework.

Performance guarantees aren't guaranteed, though.
