### ISSUE TITLE
Interval Tree Data Structure

### ISSUE THREAD

**Issue by eklinger** [google/guava#3020]
Would love to see an interval tree in Guava. Request is already being tracked in [https://github.com/google/guava/issues/1778](url) but wanted to bring it back in the limelight as it would be super useful for any time related applications and I haven't found a solid one in Java yet.
Thanks!

**Comment by liach** [comment]
#1778 (the link above broke)

**Comment by phil15world988** [comment]
how are you

**Comment by eklinger** [comment]
If it could be made thread safe that would be a big plus.

**Comment by liach** [comment]
I assume thread safety can be guaranteed by a simple wrapper.

**Comment by ronshapiro** [comment]
Let's keep conversation on the original issue for clarity

**Comment by eklinger** [comment]
Why was this closed?

**Comment by lowasser** [comment]
There was already an issue discussing interval trees.  Please keep the discussion there.
