### ISSUE TITLE
CompletionService giving out results in the order they came in

### ISSUE THREAD

**Issue by JanecekPetr** [google/guava#3021]
Three times already have I implemented a `CompletionService` that hands out completed futures in the order they came in (so, not in completion order - I believe this does not break its contract, but its shady...). The use case was similar every time: an incoming stream of messages needs to parsed and somewhat post-processed concurrently (and sometimes the process takes a lot longer than usual). The processed messages need to come out in the same order they came in.

Maybe I missed something obvious with `ListenableFuture` or `Futures`, but I never found a utility from Guava that would help achieving such a task.

I found Apache Camel's [`SubmitOrderedCompletionService`](http://static.javadoc.io/org.apache.camel/camel-core/2.20.1/org/apache/camel/util/concurrent/SubmitOrderedCompletionService.html) which does what I need, and as I said, it's not very hard to implement the service on my own. I simply think that such a often used utility might have a place in Guava? I'm _sure_ someone in Google needs this, so perhaps you guys already have one internally?

**Comment by cpovirk** [comment]
My perception is that people who want a stream-like API end up using [RxJava](https://github.com/ReactiveX/RxJava), the Java 9 [`Flow`](https://docs.oracle.com/javase/9/docs/api/java/util/concurrent/Flow.html) API, and so forth. Those frameworks can provide features like flow control, multiple consumers, and so forth.

For what it's worth, I searched internally for people using the "CompletionService" name in their own classes, and I didn't turn up anything related. That might mean that they call it something different, but I suspect it's more evidence that they're using some higher-level API.

**Comment by JanecekPetr** [comment]
I see your point.

No need to keep an issue opened if there's no demand and potential users have alternatives. I'll close this in a week or so if no further information / ideas surface.

Poor `CompletionService` only wants our love :(.

**Comment by cpovirk** [comment]
OK, I'll close it. I've always wanted to like `CompletionService`, too....
