### ISSUE TITLE
Can't cast ChildClass to ParentClass

### ISSUE THREAD

**Issue by KinoamyFx** [google/guava#3024]
# Can't cast ChildClass to ParentClass
```java
            Class<?> childClass= info.load();
            try {

               //error
                Parent parent =(Parent)childClass.newInstance();

            } catch (InstantiationException | IllegalAccessException e) {
               
            }
```

Parent parent =(Parent)clazz.newInstance(); wille throw a ClassCastException

I do confirm that childClass extends Parent.

could anyone explain it?

**Comment by Stephan202** [comment]
This doesn't sound like a Guava-specific question, but assuming `ChildClass` does indeed `ParentClass`: maybe the classes were loaded by different classloaders? Attaching a debugger may help.

**Comment by lowasser** [comment]
This is not a question related to Guava. I recommend you ask it (with more context) on StackOverflow.
