### ISSUE TITLE
Topological sort

### ISSUE THREAD

**Issue by jbduncan** [google/guava#3025]
Yesterday, I had a discussion with @jrtom about introducing a ["topological sort"](https://en.wikipedia.org/wiki/Topological_sorting) function to JUNG, as I had gone and implemented a prototype over at https://github.com/jrtom/jung/pull/174 for fun. I understand, however, that there's actually an implementation for this already in the internal version of Guava. So I'm raising this issue firstly in the hope that it encourages the internal implementation to be open sourced, and secondly to see if any aspects of my own implementation could be used to improve the internal one.

(For those who do not know what a topological sort is, it is a function that returns the nodes in a graph in an order where it's guaranteed that, by the time one visits any given node, one has already visited all of it's predecessors if it has any.)

**Comment by ben-manes** [comment]
See #2641. I also implemented Kahn's algorithm on top of Guava's graph to order executions in a workflow. Simple code to write, but will gladly remove it when built in.

**Comment by jbduncan** [comment]
Oh cool, thanks @ben-manes, I missed that #2641 was raised already!

**Comment by cgdecker** [comment]
Closing as a duplicate.

**Comment by jbduncan** [comment]
@cgdecker Alrighty!

I'll consider opening a PR if the topological sort function gets open sourced and I believe it could be improved somehow. :)
