### ISSUE TITLE
Guava Dependency Not Added to Classpath with ant+ivy repo and Gradle Plugin 3.0.x+

### ISSUE THREAD

**Issue by Sean-Waitkus** [google/guava#3028]
Hi all,

We are trying to use dagger 2 with our Android project. dagger-compiler and dagger-android-processor have Guava as a dependency.

Our environment is pretty restricted and we cannot connect to mavenCentral(), jcenter() or google(),  etc. We have an ant+ivy repo set up locally and have confirmed all necessary dependencies are in our repo for Guava.

This is our ivy file:

```  xml

<?xml version="1.0" encoding="UTF-8"?>
<ivy-module version="2.0" xmlns:m="http://ant.apache.org/ivy/maven">
	<info organisation="com.google.guava"
		module="guava"
		revision="23.3-jre"
		status="release"
		publication="20171026160611"
	>
		<description homepage="">
		Guava is a suite of core and expanded libraries that include
    utility classes, google&apos;s collections, io classes, and much
    much more.
		</description>
	</info>
	<configurations>
		<conf name="default" visibility="public" description="runtime dependencies and master artifact can be used with this conf" extends="runtime,master"/>
		<conf name="master" visibility="public" description="contains only the artifact published by this module itself, with no transitive dependencies"/>
		<conf name="compile" visibility="public" description="this is the default scope, used if none is specified. Compile dependencies are available in all classpaths."/>
		<conf name="provided" visibility="public" description="this is much like compile, but indicates you expect the JDK or a container to provide it. It is only available on the compilation classpath, and is not transitive."/>
		<conf name="runtime" visibility="public" description="this scope indicates that the dependency is not required for compilation, but is for execution. It is in the runtime and test classpaths, but not the compile classpath." extends="compile"/>
		<conf name="test" visibility="private" description="this scope indicates that the dependency is not required for normal use of the application, and is only available for the test compilation and execution phases." extends="runtime"/>
		<conf name="system" visibility="public" description="this scope is similar to provided except that you have to provide the JAR which contains it explicitly. The artifact is always available and is not looked up in a repository."/>
		<conf name="sources" visibility="public" description="this configuration contains the source artifact of this module, if any."/>
		<conf name="javadoc" visibility="public" description="this configuration contains the javadoc artifact of this module, if any."/>
		<conf name="optional" visibility="public" description="contains all optional dependencies"/>
	</configurations>
	<publications>
		<artifact name="guava" type="bundle" ext="jar" conf="master"/>
		<artifact name="guava" type="source" ext="jar" conf="sources" m:classifier="sources"/>
		<artifact name="guava" type="javadoc" ext="jar" conf="javadoc" m:classifier="javadoc"/>
	</publications>
	<dependencies>
		<dependency org="com.google.code.findbugs" name="jsr305" rev="1.3.9" force="true" conf="compile->compile(*),master(*);runtime->runtime(*)"/>
		<dependency org="com.google.errorprone" name="error_prone_annotations" rev="2.0.18" force="true" conf="compile->compile(*),master(*);runtime->runtime(*)"/>
		<dependency org="com.google.j2objc" name="j2objc-annotations" rev="1.1" force="true" conf="compile->compile(*),master(*);runtime->runtime(*)"/>
		<dependency org="org.codehaus.mojo" name="animal-sniffer-annotations" rev="1.14" force="true" conf="compile->compile(*),master(*);runtime->runtime(*)"/>
		<override org="org.easymock" module="easymock" matcher="exact" rev="3.0"/>
		<override org="com.google.errorprone" module="error_prone_annotations" matcher="exact" rev="2.0.18"/>
		<override org="com.google.j2objc" module="j2objc-annotations" matcher="exact" rev="1.1"/>
		<override org="com.google.caliper" module="caliper" matcher="exact" rev="1.0-beta-2"/>
		<override org="org.mockito" module="mockito-core" matcher="exact" rev="2.7.19"/>
		<override org="com.google.truth" module="truth" matcher="exact" rev="0.35"/>
		<override org="com.google.jimfs" module="jimfs" matcher="exact" rev="1.1"/>
		<override org="com.google.truth.extensions" module="truth-java8-extension" matcher="exact" rev="0.35"/>
		<override org="junit" module="junit" matcher="exact" rev="4.11"/>
		<override org="com.google.code.findbugs" module="jsr305" matcher="exact" rev="1.3.9"/>
	</dependencies>
</ivy-module>

```

What we have found after a couple of days of troubleshooting is that while Gradle resolves the Guava dependency it does not add it to the class/annotationProcessor path. We have even taken dagger out of the picture and just tried to import Guava 23.3-jre itself as a compile dependency to no avail.

It is worth noting that this issue only happens with Guava 23.x+ and not 22.0 for example.  If we specify ```implementation 'com.google.guava:guava:22.0``` it IS added to the class path, but this ```implementation 'com.google.guava:guave:23.3-jre'``` is not.

This is our how our dagger dependencies are configured:

```

    implementation'com.google.dagger:dagger:2.14.1'

    annotationProcessor'com.google.dagger:dagger-compiler:2.14.1'

    annotationProcessor 'com.google.dagger:dagger-android-processor:2.14.1'
    implementation'com.google.dagger:dagger-android-support:2.14.1'

```
I noticed some differences in the pom files between 22.0 and 23.3-jre notably that 23.3-jre uses the maven-jar-plugin where 22.0 does not.

I know I am listing dagger configurations, but we have isolated the issue to the Guava dependency as we get the following error when building the project:

```

Error:Bad service configuration file, or exception thrown while constructing Processor object: javax.annotation.processing.Processor: Provider dagger.internal.codegen.ComponentProcessor could not be instantiated: java.lang.NoClassDefFoundError: com/google/common/collect/SetMultimap

```

This error tells me that SetMultimap which is part of com.google.common.collect which itself is part of Guava, is not on the Classpath/annotationProcessor path like it should be.

We feel that our ivy file might be missing something needed to get this all to work as this problem does not persist when using mavenCentral(), jcenter() and google();  We also noticed that using Android Studio Gradle plugin 2.3.3 that there are again no issues with compilation.

It seems to be an issue when using 3.0.x+ in combination with our internal ant+ivy repo.

Any help with this issue is much appreciated.  We have also filed a bug report with the Android Studio Gradle team here: https://issuetracker.google.com/issues/71711793

I could post the same in the Dagger repo but I felt that the issue presenting from a lack of Guava I'd post here before the Dagger repo.

Thanks.

**Comment by Sean-Waitkus** [comment]
<img width="776" alt="Guava 22.0 Added to Path am" src="https://user-images.githubusercontent.com/30660396/34719839-52d1e332-f50a-11e7-8663-53adafd06fff.png">

<img width="926" alt="Guava 23.3-jre NOT added to path at 6 56 43 am" src="https://user-images.githubusercontent.com/30660396/34719860-69239f86-f50a-11e7-97b2-9c38af8f1d3c.png">

Adding a couple of screenshot illustrating that 22.0 works while 23.3-jre does not.

**Comment by ronshapiro** [comment]
I don't believe this is a Guava or a Dagger issue, as everything builds correctly when using the default gradle/maven instructions. It's pretty hard to debug this without a sample project (and a sample maven cache, which is what it sounds like you have?).

Some areas to look:
  - Does the guava-23.3-jre jar exist anywhere? Perhaps it's missing from your cache?
  - Are the pom files in the cache all correct?
  - I don't see Dagger in your Ivy file. Is that intentional? I know nothing about Ivy, but that sounds like a problem?

**Comment by Sean-Waitkus** [comment]
Thanks for replying.

The Ivy file is for the Guava dependency itself.  Each dependency version gets it's own Ivy.xml. It sort of equates to a POM file to the best of my knowledge. This tells the dependency manager what to pull in for a given dependency. 

So in this case Guava needs:

``` xml

<dependency org="com.google.code.findbugs" name="jsr305" rev="1.3.9" force="true" conf="compile->compile(*),master(*);runtime->runtime(*)"/>
		<dependency org="com.google.errorprone" name="error_prone_annotations" rev="2.0.18" force="true" conf="compile->compile(*),master(*);runtime->runtime(*)"/>
		<dependency org="com.google.j2objc" name="j2objc-annotations" rev="1.1" force="true" conf="compile->compile(*),master(*);runtime->runtime(*)"/>
		<dependency org="org.codehaus.mojo" name="animal-sniffer-annotations" rev="1.14" force="true" conf="compile->compile(*),master(*);runtime->runtime(*)"/>

```

We do have these dependencies available for gradle.

I know I mentioned dagger. I found this issue when trying to use dagger, but ultimately the problem is that there is some trouble getting Guava 23.x+ onto the class path so it can be used as a dependency. 22.0 and below work fine.

The dagger dependencies have their own Ivy.xml files so it not being in there is not a problem.

Guava 23.3-jre is available in our repo as well as all of it's dependencies.

It's possible the issue lies in how we import the dependencies, which is why I was hoping someone could illuminate us on what exactly is different between 22.0 and 23+ as far as dependency management goes because something is clearly wrong somewhere.

Thanks.

**Comment by cgdecker** [comment]
As Ron says, I don't think there's anything to be fixed with Dagger/Guava here. I'm not sure any of us are particularly familiar with configuring Ivy either, so we probably can't help you much there either. In general, it's better to ask questions about Guava on stackoverflow. If you think there's a specific problem with Guava that's causing your issue, you can report that as an issue here.
