### ISSUE TITLE
whether guava cache can clear expire entity when has access for the entity during expire period?

### ISSUE THREAD

**Issue by LouisLei** [google/guava#3030]
Use guava cache with java G1 collector( xms:1g,xmx:8g) , when the application run 3days will oom 
guava cache config : 
                maximumSize(1024)
                .concurrencyLevel(Runtime.getRuntime().availableProcessors())
                .initialCapacity(60)
                .expireAfterWrite(30, TimeUnit.SECONDS)

I dump the file found the concurrenthasmap&node size is 23406,773 , the java heap is full and cannot gc so that the application become bad.

i wonder if the loaded entity clear up for this sceneriio:
the entity expired;
the entity need be use during the period.

**Comment by cgdecker** [comment]
I'm not clear on what you're asking. What do you mean by "the entity need be use during the period"?

I'm not an expert on it, but AFAIK the most common cause of entries in caches not being cleared as you expect is that the cache isn't being used. I believe that by default, cache cleanup occurs on every cache write and on occasional cache reads.

You may want to try [caffeine](https://github.com/ben-manes/caffeine), which is based on Guava's cache API but has had significantly more work put into its implementation in recent years.
