### ISSUE TITLE
Add a page to reflect functional equivalents for Apache Commons commons-io packages

### ISSUE THREAD

**Issue by 62mkv** [google/guava#3036]
Something similar to [this page](https://github.com/google/guava/wiki/ApacheCommonCollectionsEquivalents) should be very helpful

**Comment by cgdecker** [comment]
I don't really feel that it's worth the time to try to go through and exhaustively document equivalences and differences between different libraries like that. I'd support getting rid of the collections page too, but since it already exists I'm not going to go out of my way for that.
