### ISSUE TITLE
Consider introducing JUnit Jupiter variant of Collection Suite Builders

### ISSUE THREAD

**Issue by jbduncan** [google/guava#3039]
Currently, classes for testing the implementations of collections like `ListTestSuiteBuilder` are dependent on JUnit 3 `TestSuite`s to do their job.

This is perfectly fine in the land of JUnit 3 & 4. However, with the relatively modern [JUnit Jupiter](http://junit.org/junit5/docs/current/user-guide/#overview-what-is-junit-5) testing framework (part of [JUnit 5](https://github.com/junit-team/junit5)), `TestSuite`s no longer exist, so I'm making an educated guess that one would need to use [JUnit Vintage](http://junit.org/junit5/docs/current/user-guide/#migrating-from-junit4) (a bridge built into JUnit 5 to run JUnit3/4 tests) instead of Jupiter to run tests based on `ListTestSuiteBuilder` et al, which is far from ideal, especially for new JUnit 5-based tests and greenfield projects.

I imagine that this feature would be implemented with JUnit Jupiter's [`DynamicTest`](http://junit.org/junit5/docs/current/user-guide/#writing-tests-dynamic-tests) support.

**Comment by jbduncan** [comment]
Note that I'm raising this issue not because I have an immediate need for this feature, but because I think it would be interesting to implement and nice-to-have from a JUnit 5 perspective.

If the Guava team decides that this is not worth pursuing, or that it's not important enough to be at the top of the TODO list, I'm thinking about writing my own implementation in the medium-to-long term future which would ideally be hosted over at [junit-pioneer](https://github.com/junit-pioneer/junit-pioneer).

**Comment by netdpb** [comment]
We have no plans to move to JUnit 5 for our tests. I'm guessing that this feature request is only relevant if we decide to use JUnit 5. Is that right?

**Comment by jbduncan** [comment]
Yep, that's right @netdpb. :)

**Comment by netdpb** [comment]
I'm pretty sure we're not planning to do that anytime in the near future, so I'm going to close this. If we ever do move to JUnit 5 for our tests, please reopen it then.
