### ISSUE TITLE
ClassPath.getTopLevelClasses() return empty set

### ISSUE THREAD

**Issue by sean-xiaoyin** [google/guava#3043]
In Guava 19.0, ClassPath.getTopLevelClasses(String packageName) returns empty set on Java 9. 

The reason is that, in ClassPath class, the method getClassPathEntries() checks whether the classloader is a URLClassLoader, which was the default of Java 8, but Java 9 is using PlatformClassLoader now.

**Comment by JakeWharton** [comment]
Have you tried 24.0?

**Comment by jbduncan** [comment]
~~I don't know if there's been any change to `ClassPath` since Guava 24-jre, but have you tried Guava 24-jre to see if this problem has been fixed?~~

Ah, @JakeWharton got there before me. :)
