### ISSUE TITLE
TypeToken.getSubtype() inconsistency

### ISSUE THREAD

**Issue by shmosel** [google/guava#3048]
I came across this anomaly while trying to (mis)use `getSubtype()` in place of a [narrowing cast](https://github.com/google/guava/issues/1852). Consider this snippet:

```java
package com.github;

import java.util.ArrayList;
import java.util.List;

import com.google.common.reflect.TypeToken;

@SuppressWarnings("serial")
public class Test {
    static class StringList extends ArrayList<String> {}
    
    public static void main(String[] args) {
        TypeToken<List<Number>> type = new TypeToken<List<Number>>() {};
        System.out.println(type.isSupertypeOf(StringList.class));
        System.out.println(type.getSubtype(StringList.class));
    }
}
```
This produces the following output:
```
false
Exception in thread "main" java.lang.IllegalArgumentException: No type mapping from class java.lang.String to class java.lang.Number
	at com.google.common.reflect.TypeResolver$1.visitClass(TypeResolver.java:181)
	at com.google.common.reflect.TypeVisitor.visit(TypeVisitor.java:80)
	at com.google.common.reflect.TypeResolver.populateTypeMappings(TypeResolver.java:183)
	at com.google.common.reflect.TypeResolver.access$000(TypeResolver.java:54)
	at com.google.common.reflect.TypeResolver$1.visitParameterizedType(TypeResolver.java:159)
	at com.google.common.reflect.TypeVisitor.visit(TypeVisitor.java:78)
	at com.google.common.reflect.TypeResolver.populateTypeMappings(TypeResolver.java:183)
	at com.google.common.reflect.TypeResolver.where(TypeResolver.java:91)
	at com.google.common.reflect.TypeToken.resolveTypeArgsForSubclass(TypeToken.java:1164)
	at com.google.common.reflect.TypeToken.getSubtype(TypeToken.java:410)
	at com.github.Test.main(Test.java:15)
```
This is expected, considering `StringList` is incompatible with `List<Number>`. But now let's change the type to a bounded wildcard:
```java
TypeToken<List<? extends Number>> type = new TypeToken<List<? extends Number>>() {};
```
Suddenly it runs without error, producing the following:
```
false
com.github.Test$StringList
```
Shouldn't it throw the same error?

**Comment by fluentfuture** [comment]
Yeah. We took a short-cut there when wildcard is involved by saying that no type variable substitution is necessary anyway so just leave it as is.

It turns out properly validating the input types with presence of type variables, wildcards and upper/lower bounds isn't easy. Always checking isSubtypeOf() as a precondition won't work because String.isSubtypeOf(<T>) would be false and vice versa.

The reason the first one threw an exception is because it was trying to do type variable substitution of List<Number> to List<String> and failed.

**Comment by kluever** [comment]
@fluentfuture Should this be closed then?

**Comment by fluentfuture** [comment]
I just realized that we could do isSubtypeOf() *after* type variable substitutions.

I'm running some experiments.

**Comment by basinilya** [comment]
Still an issue when the subclass itself is parameterized with wildcards.

    public class TestGetSubtyp2
        extends TestCase
    {
        private int counter;
        static class StringList extends ArrayList<String> {}
        static class StringList2<V extends String> extends ArrayList<V> {}
        private TypeToken getSubtype(TypeToken resolvedSuperTt, Class<?> subclass) {
            try {
                TypeToken res = resolvedSuperTt.getSubtype( subclass );
                System.out.println(res + " o" + (counter++) + ";");
                return res;
            } catch (IllegalArgumentException e) {
                return null;
            }
        }
        public void testGetSubtype()
            throws Exception
        {
            TypeToken<List<? extends Number>> type = new TypeToken<List<? extends Number>>() {};
            // bad: List<? extends Number> x = new StringList2<Number>();
            assertNull(getSubtype(type, StringList.class));
            assertNull(getSubtype(type, StringList2.class));
        }        
    }

**Comment by basinilya** [comment]
> Do you have a use case where this is causing problems?
Yes. I have the web POJO editor that offers candidate implementation classes as values for property setters. 
Today I noticed that it offers `java.util.EnumMap<String, Object>` for the property of type `java.util.Map<String, Object>` as the result of `getSubclass`.

EnumMap's key is declared as `K extends Enum<K>`

**Comment by fluentfuture** [comment]
Enum is particular challenging because the type bound recursively defined.

Even JDK reflection doesn't get it strictly right. If you call `getGenericReturnType()` for a method like:

```java
Enum<?> foo();
```

You get back `Enum<? extends Object>`, even though it should at least be `Enum<? extends Enum<?>>`.

**Comment by fluentfuture** [comment]
`getTypeParameters()` is member of `Class`. It can be used together with `getActualTypeArguments()` to resolve things like "the return type of List<String>.get".

For a `ParameterizedType` obtained from reflection, there is no need to do the resolution.

**Comment by fluentfuture** [comment]
I don't think we'll get to this any time soon.

It's a defect, but we don't have a good fix.

**Comment by fluentfuture** [comment]
Trying to close but it looks like I cannot. Anybody know how to close this bug?
