### ISSUE TITLE
De-beta-ify Invokable and TypeToken

### ISSUE THREAD

**Issue by gaul** [google/guava#3051]
Apache jclouds makes extensive use of Invokable and TypeToken.  Could you promote these?

**Comment by nikhilbarar** [comment]
Are we doing this?

**Comment by netdpb** [comment]
`Invokable` was made obsolete by `java.lang.reflect.Executable` in Java 8. We should probably deprecate it (and `Parameter`, obsoleted by `java.lang.reflect.Parameter`) and provide a migration strategy.

In the meantime, we can remove `@Beta` from other APIs in `com.google.common.reflect`.
