### ISSUE TITLE
Unresolved task detected: AbstractFuture "TODO(lukes): investigate using the @Contended annotation on these fields when jdk8 is available."

### ISSUE THREAD

**Issue by Prodigysov** [google/guava#3058]
We're working on a technique to automatically detecting unresolved
trigger-action todo comments in codebase. Here is what we found in
this project:

- guava/src/com/google/common/util/concurrent/AbstractFuture.java:329
```
  // TODO(lukes): investigate using the @Contended annotation on these fields when jdk8 is
  // available.
```

- The trigger: "when jdk8 is available" happened around commit <86fb7001aecb8954dd15ee3c64e7172b4a6e512a> (Nov 4 2016).

- But the action: "investigate using the @Contended annotation on these fields" never happened since then.

- "These fields" are referencing `AbstractFuture#value`, `AbstractFuture#listeners` and `AbstractFuture#waiters`.

**Comment by cpovirk** [comment]
The comment should say something like "when jdk8 is available to all flavors of Guava." We currently maintain a backport that targets JDK7 and older versions of Android, and we try to keep the backport and mainline mostly in sync. That's not to say that we couldn't do this, but we'd have to weigh the benefits against the cost of diverging the two.
