### ISSUE TITLE
Unresolved task detected: ClassPath "TODO(benyu): Try java.nio.file.Paths#get() when Guava drops JDK 6 support." 

### ISSUE THREAD

**Issue by Prodigysov** [google/guava#3059]
We're working on a technique to automatically detecting unresolved
trigger-action todo comments in codebase. Here is what we found in
this project:

- guava/src/com/google/common/reflect/ClassPath.java:582
```
  // TODO(benyu): Try java.nio.file.Paths#get() when Guava drops JDK 6 support.
```

- The trigger: "Guava drops JDK 6 support" happened around commit <9ebd95a9a84a21e96bf2f077f4cc93efc14e9b86> (Feb 20 2018).

- But the action: "Try java.nio.file.Paths#get()" never happened since then.

- The task should be replacing `new File(url.toURL())` with `Paths.get(url.toURI()).toFile()`.

**Comment by cpovirk** [comment]
Thanks, but while we have dropped support for JDK6, we still support older versions of Android that don't contain `Path` ([as old as Ice Cream Sandwich](https://github.com/google/guava#important-warnings)).
