### ISSUE TITLE
Request to add nonNullOrEmpty method to Strings class

### ISSUE THREAD

**Issue by try0** [google/guava#3064]
I request to add the nonNullOrEmpty method to the String class.
When use stream,  can use method reference to write whether the string is null or empty.

```java
stringStream.filter(Strings::nonNullOrEmpty) ...
```

I think this is useful.
What do you think?

**Comment by kashike** [comment]
https://github.com/google/guava/blob/master/guava/src/com/google/common/base/Strings.java#L34-L42

**Comment by jrtom** [comment]
@kashike, I don't see how that would solve the problem that @try0 is trying to solve.  `Strings.nullToEmpty()` converts a possibly-null string to an empty string (or returns the original if non-null).  

I _think_ that you are trying to filter out strings that are neither null nor empty, but the "non" prefix is ambiguous (does that apply to just null or to both null and empty?), so the naming would need some work.

The closest that exists at the moment is `Strings.isNullOrEmpty()`, which is obviously close but not close enough.  :)

I can see why you would want that, but I'm not sure that there's enough demand for such a method to warrant its creation, though, considering that the corresponding lambda expression is simple enough:

```
stringStream.filter(s -> !(s == null || s.isEmpty())) ...
```

**Comment by try0** [comment]
@kashike, @jrtom 
I'm sorry I didn't make it clear enough.
What I hope is a method that returns values equivalent to the following results.
```java
!(str == null || str.isEmpty())
```
I often use java.util.Objects#nonNull. This method  returns the opposite value to the isNull method.
```java
stream.filter(Objects::nonNull)...
```
In the same way as above, I thought would like to check if the string is null or empty.

but, As @jrtom  have written
```java
stringStream.filter(s -> !(s == null || s.isEmpty())) ...
```
may be this is enough.


Sorry if my English is wrong.

**Comment by kashike** [comment]
@jrtom Oops. I misread `filter` as `map`. :smile_cat:

**Comment by cgdecker** [comment]
Though we do have some methods (well, `Strings.isNullOrEmpty()`, at any rate) that do so, we generally don't encourage methods that treat `null` and non-`null` values the same. There are a lot of ways you could deal with this situation without us needing to add a new method:

- `filter(not(Strings::isNullOrEmpty))` (Guava's `Predicates.not()`)
  - or `filter((Strings::isNullOrEmpty).negate())`, but this probably doesn't work without casting `Strings::isNullOrEmpty` to `Predicate<String>`
- `map(Strings::emptyToNull).filter(Objects::notNull)`
- etc.

**Comment by try0** [comment]
@cgdecker 
Thank you for presenting an example. I'll use those.
