### ISSUE TITLE
Comparators.least() performance

### ISSUE THREAD

**Issue by eklinger** [google/guava#3075]
Hello,
In the docs for Comparators.least() it recommends using the collector version for Java 8 users. Is that still true even if the source collection is an ArrayList? What about if the source list is small (<20) and k is 5. Currently I'm doing list.stream().collect(Comparators.least(5, ....)) but I'm wondering if this is more overhead to construct the stream than to either sort the array directly or if Ordering.leastOf would be faster. 
Thanks!

**Comment by lowasser** [comment]
If the list is small, it's not likely to make a significant difference in any direction, and not likely to have any more performance overhead than other stream based operations.  You will have to do benchmarks on your own devices to determine exactly what is best for you.

Ordering.leastOf delegates to the same backing implementation, basically.
