### ISSUE TITLE
cleanup cache when read cache

### ISSUE THREAD

**Issue by MarvellousLiang** [google/guava#3082]
As I Know,`postReadCleanup(); `will be called when read cache ;and will call `cleanUp();` when read count reach 64; But it just clean the expired cache that we read the key? Whether the 'read CleanUp' just clean what we read that cache?   Others' expired cache will be kept util we write/read it or call `Cache.cleanUp()`?

**Comment by lowasser** [comment]
I don't believe we offer any guarantees there.  (Currently I believe that cleanup occurs for the _segment_ of the cache where the key is found, which is approximately 1/concurrencyLevel of the cache.)
