### ISSUE TITLE
Missing test case for Comparators.emptiesLast

### ISSUE THREAD

**Issue by ineuwirth** [google/guava#3088]
There are two new utility methods added in a1a83d407f3f19891b7032e151d945363c441780 however only one of them is covered by unit tests. Maybe a synchronization issue between the Google-internal and the public Guava repository?

**Comment by ineuwirth** [comment]
Please find #3089

**Comment by ronshapiro** [comment]
Closed in https://github.com/google/guava/commit/69912164fdbaaa8d14befa73451e7d6f4c5bc587
