### ISSUE TITLE
LoadingCache code example has issues

### ISSUE THREAD

**Issue by batilei** [google/guava#3094]
I tried to create a simple example of LoadingCache, but the code in the example doesn't work
A simple case:
```
        CacheLoader<String, String> loader;
        loader = new CacheLoader<String, String>() {
            @Override
            public String load(String key) {
                return key.toUpperCase();
            }
        };
        LoadingCache<String, String> cache;
        cache = CacheBuilder.newBuilder().build(loader);
```

But compiler complain that
The method build(CacheLoader<? super K1,V1>) in the type CacheBuilder<Object,Object> is not applicable for the arguments (CacheLoader<String,String>)

Please correct. Thanks

**Comment by lowasser** [comment]
This example works for me.  Can you give some more details about the version of Java and of Guava you are using?

**Comment by batilei** [comment]
Hello, I use  guava " compile 'com.google.guava:guava:24.1-jre'" and JRE 1.8.Is this ok?

**Comment by lowasser** [comment]
Are you certain you have the right imports?  The correct `CacheLoader`, `LoadingCache`, and `CacheBuilder`?

**Comment by batilei** [comment]
I think so?
Does the import package look correct?
import com.google.common.cache.CacheLoader;
import com.google.common.cache.LoadingCache;

**Comment by batilei** [comment]
Oh, I found I used the wrong CacheBuilder....It is from org.apache.curator.shaded.com.google.common.cache.CacheBuilder<K, V>

Thank you so much
