### ISSUE TITLE
Add some "dangerous" APIs

### ISSUE THREAD

**Issue by SoniEx2** [google/guava#3106]
It would be nice if guava added some "dangerous" APIs e.g. for starting/running/managing processes, because [ppl keep using guava wrong](https://github.com/MovingBlocks/Terasology/issues/2791) and we should do something about it.

**Comment by jbduncan** [comment]
@SoniEx2 It's not clear to me personally how the people in that issue are using Guava incorrectly. Could you clarify things for me?

**Comment by SoniEx2** [comment]
they do the thing the README says not to do - expose a guava from trusted code straight to untrusted code.

the guava in terasology is NOT subject to sandbox restrictions.

**Comment by jbduncan** [comment]
Hmm... :thinking: 

I think that purposely adding "dangerous" APIs is the wrong way to go about encouraging the Terasology guys from using Guava this way, if they're in fact exposing Guava in such a way that it's causing a security problem for Terasology.

However, I'm admittedly far from an expert on this topic, and I'm just an external Guava contributor (I ain't a Googler), so I'll wait for someone from the Guava team to give their thoughts on this. :)

**Comment by jrtom** [comment]
I'm an internal contributor to Guava, but I don't speak for the team (except perhaps about common.graph-related stuff :) ).

I'm not at all clear on what you think that Guava should actually do here.

If you think that Terasology is using Guava in a way that's potentially unsafe, it seems like you've already raised that issue with that team.

**Comment by SoniEx2** [comment]
Why can't you, idk, put a sandboxed guava in the sandbox, rather than exposing an unsandboxed guava to the sandbox?

**Comment by jbduncan** [comment]
@SoniEx2 I might be misunderstanding what @immortius said, but isn't Terasology already sandboxing Guava by only allowing mod authors to use all packages except `com.google.common.io`? :thinking:

**Comment by SoniEx2** [comment]
and I believe guava is still dangerous even without the io package.

**Comment by Cervator** [comment]
🍿

Suffice to say, we've talked this and other issues to death with Soni already. I suggest this issue be closed.

**Comment by jrtom** [comment]
@SoniEx2 I still don't understand what you're actually proposing here.  

As such, I'm closing this issue for now.

If you can give a concrete example of a single specific API that you would like the Guava team to add, feel free to add a comment and we can then reopen this issue and have a discussion about that specific proposal.  If you do so, and we think it sounds like something that we'd like to add, we can then discuss further additions along the same lines.
