### ISSUE TITLE
InternetDomainName.findSuffixOfType() in junit test returns java.lang.NoSuchFieldError: EXACT

### ISSUE THREAD

**Issue by nitrocode** [google/guava#3108]
I'm using guava `24.1-jre` and jdk `1.8.0.162`

```
InternetDomainName.from("google.com");
```

causes

```
java.lang.NoSuchFieldError: EXACT

	at com.google.common.net.InternetDomainName.findSuffixOfType(InternetDomainName.java:172)
	at com.google.common.net.InternetDomainName.<init>(InternetDomainName.java:153)
	at com.google.common.net.InternetDomainName.from(InternetDomainName.java:212)
	at com.dnb.vici.formfill.common.UtilFunctions.getCustomerAndDomainId(UtilFunctions.java:73)
	at com.dnb.vici.formfill.ut.UtilFunctionsTest.getCustomerAndDomainIdTest(UtilFunctionsTest.java:73)
```

It's failing on [InternetDomainName.java Line #172](https://github.com/google/guava/blob/26b09c1fd30c23bc0e48701ff7131f2de1e5fe35/guava/src/com/google/common/net/InternetDomainName.java#L172) and this [old storm issue](https://www.mail-archive.com/search?l=dev@storm.apache.org&q=subject:%22%5C%5Bjira%5C%5D+%5C%5BUpdated%5C%5D+%5C(STORM%5C-538%5C)+Guava+com.google.thirdparty.publicsuffix+is+not+shaded%22&o=newest&f=1) returns a very similar error.

In IntelliJ when I evaluate the expression, it returns `false` as expected but running through the code will throw the exception and it only happens during a unit test... Why does this happen?

**Comment by netdpb** [comment]
This looks to me like there is some problem with the Guava in your classpath. `PublicSuffixPatterns` has existed, and had the field `EXACT`, since v16. The storm issue mentions shading. Are you shading Guava, and not shading all of the packages? `PublicSuffixPatterns` is in `com.google.thirdparty.publicsuffix`.

**Comment by nitrocode** [comment]
Hi @netdpb thanks for replying. None of the jars are shaded. I'm compiling the app as a fat jar. 

I can see the `EXACT` field is there when I step through the code. I've tried blowing out the `~/.m2/` directory and reinstalling the app. Also tried removing the project from Intellij and re-adding it and I get the same issue.

My workaround has been recently to comment out the unit tests around the issue. 😢

**Comment by netdpb** [comment]
What else is in your classpath? I cannot replicate this error.

**Comment by Stephan202** [comment]
The `maven-enforcer-plugin` has the [`banDuplicateClasses`](http://www.mojohaus.org/extra-enforcer-rules/banDuplicateClasses.html) and [`requireUpperBoundDeps`](https://maven.apache.org/enforcer/enforcer-rules/requireUpperBoundDeps.html) rules; they can help track down this issue. (There are others, but I suspect one of these will point you in the right direction.)

**Comment by nitrocode** [comment]
@Stephan202 let me debug this at work on Monday using the tools @Stephan202 provided. I can try to create a mwce if I cannot find the root of it. Thank you!

**Comment by nitrocode** [comment]
Ok so I found out that this was related to standalone wiremock uses [guava version 20.0](https://github.com/tomakehurst/wiremock/blob/master/build.gradle#L51) and the standalone shades guava. To fix the issue, I reordered the dependencies to make guava load before wiremock and it worked.

{code}
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>24.1-jre</version>
        </dependency>

        <dependency>
            <groupId>com.github.tomakehurst</groupId>
            <artifactId>wiremock-standalone</artifactId>
            <version>2.17.0</version>
            <scope>test</scope>
        </dependency>
{code}

Is there a better way to debug this kind of dependency conflict in the future?

Thank you for taking the time to help me with this.

**Comment by Stephan202** [comment]
@nitrocode I'd add the aforementioned checks to your build by default; they could be part of a shared company POM. Others I recommend:
* The `maven-enforcer-plugin`'s [`dependencyConvergence`](https://maven.apache.org/enforcer/enforcer-rules/dependencyConvergence.html).
* The `maven-dependency-plugin`'s various [`analyze*`](https://maven.apache.org/plugins/maven-dependency-plugin/plugin-info.html) goals.

At Picnic we use a parent which has these and other checks; it ensures that each of our projects has a well-behaved build. (Open-sourcing (a variation of) this `pom.xml` is on my TODO list, but realistically it's a few months out.)

**Comment by nitrocode** [comment]
That's awesome, thank you @Stephan202!
