### ISSUE TITLE
Queues.descending(Deque)

### ISSUE THREAD

**Issue by ogregoire** [google/guava#3110]
Currently, to use `Deque.descendingIterator()`, we have to write code like this:

    for(Iterator<T> it = myDeque.descendingIterator(); it.hasNext(); ) {
      T element = it.next();
      // Do something
    }

Would it be possible to have something akin to the following:

    for(T element: Queues.descending(myDeque)) {
      // Do something
    }

Ideally the method content would be something like:

    static <T> Iterable<T> descending(final Deque deque) {
      checkNotNull(deque);
      return ()-> deque.descendingIterator();
    }

**Comment by Stephan202** [comment]
That does require repeating `T` and is cumbersome for "long" instances of `T`, though. Tough one ;)

**Comment by cpovirk** [comment]
I see only ~10 hits in Google's repo, so this is probably going to be tough to prioritize, [as much sense as it makes](https://stackoverflow.com/a/3883636/28465) :(

If I expected it to be completely uncontroversial, I'd just say "send a pull request," but I'd expect questions about whether we should return a full `Queue` (rather than just an `Iterable`).

**Comment by ogregoire** [comment]
Noted. I created PR #3111 to tackle the issue.

**Comment by cpovirk** [comment]
I was wrong when I said "10 hits": I was looking only for people who had actually written a foreach using an approach like the one above. But plenty of people do it with an old-style `for` or `while` loop. Estimating from the total number of `descendingIterator` calls, I'd say more like 100 hits. So this is worth a look eventually. (I am personally feeling extra behind schedule right now, but I'll put it on my list and hope someone else on my team swoops in in the meantime.)

**Comment by cpovirk** [comment]
It probably would have been good to do this 6 years ago. Now that [`Deque.reversed`](https://docs.oracle.com/en/java/javase/22/docs/api/java.base/java/util/Deque.html#reversed()) has landed in Java 21, we at least have a good reason to not do it now :(
