### ISSUE TITLE
Small mistake in precondition check example

### ISSUE THREAD

**Issue by michalfotyga** [google/guava#3114]
```java
checkArgument(i < j, "Expected i < j, but %s > %s", i, j);
```

should be  
```java
checkArgument(i < j, "Expected i < j, but %s >= %s", i, j);
```

😉 🤓

**Comment by jbduncan** [comment]
Hi @michalfotyga, whereabouts in the Guava code did you find this mistake? :)

**Comment by michalfotyga** [comment]
Aaa whoops, sorry :bow:  
https://github.com/google/guava/wiki/PreconditionsExplained

**Comment by jbduncan** [comment]
Not a problem! Thanks for the clarification. :)

**Comment by jbduncan** [comment]
I believe this is something that only the Guava team can resolve? It doesn't look like the Wiki has public write access to me.

**Comment by michalfotyga** [comment]
Ah, I see. Creating PR is also not possible for wiki content unfortunately.

**Comment by jrtom** [comment]
I've fixed it.  Thanks for the catch!  :)
