### ISSUE TITLE
InetAddresses support for IPv4 addr containing netmask

### ISSUE THREAD

**Issue by devikasondhi** [google/guava#3115]
The InetAddresses class does not seem to support IPv4 addresses containing CIDR netmask (like /24)
Example:
InetAddresses.isInetAddress("192.168.2.0/24") returns false, while this should be considered valid and return true.
Please look into it. Thanks.

**Comment by netdpb** [comment]
Strings like "192.168.2.0/24" refer to a network prefix, not a single address. `InetAddress` is meant to represent a single IP address, not a prefix.

See `java.net.InterfaceAddress` for comparison.
