### ISSUE TITLE
InternetDomainName.from("s3.amazonaws.com").topPrivateDomain fails

### ISSUE THREAD

**Issue by dportabella** [google/guava#3120]
`com.google.common.net.InternetDomainName.from("s3.amazonaws.com").topPrivateDomain`
fails with
`Exception in thread "main" java.lang.IllegalStateException: Not under a public suffix: s3.amazonaws.com`

**Comment by netdpb** [comment]
It turns out that s3.amazonaws.com is itself a public suffix, so that exception should in fact be thrown in that case. Check `InternetDomainName.from("s3.amazonaws.com").isPublicSuffix()`.
