### ISSUE TITLE
Memoized throwing-suppliers are improperly tested

### ISSUE THREAD

**Issue by ogregoire** [google/guava#3122]
[The current test](https://github.com/google/guava/blob/acf29b389bc9ff8701f69d05b30e9d899bc10e35/guava-tests/test/com/google/common/base/SuppliersTest.java#L110) expects to get exceptions thrown again and again. But `Suppliers::memoize` is not called in the "testMemoizeExceptionThrown" test.

The line 115 should be replaced:

    private void memoizeExceptionThrownTest(ThrowingSupplier memoizedSupplier) {

To:

    private void memoizeExceptionThrownTest(ThrowingSupplier throwingSupplier) {
      Supplier<Integer> memoizedSupplier = Suppliers.memoize(throwingSupplier);

**Comment by netdpb** [comment]
www.sadtrombone.com
