### ISSUE TITLE
InternetDomainName.topPrivateDomain() Fails on Suffix .site

### ISSUE THREAD

**Issue by WammKD** [google/guava#3128]
I have the following code:

```
private static String getDomainName(final String url) throws MalformedURLException {
     final URL u = new URL(url);
    return InternetDomainName.from(u.getHost()).topPrivateDomain().toString();
}
```

The String `http://opticafsm.business.site/` is what's passed to `getDomainName()`.

Unfortunately, it results in the error

```
Caused by: java.lang.IllegalStateException: Not under a public suffix: opticafsm.business.site
	at com.google.common.base.Preconditions.checkState(Preconditions.java:177)
	at com.google.common.net.InternetDomainName.topPrivateDomain(InternetDomainName.java:447)
	at Links.getDomainName(Links.java:119)
```

The version of Guava being used was, original, version 16 which I thought might be causing the issue but, after upgrading to 24.1-jre, the behavior didn't change in any way.

It seems that it's not recognizing `.site` as a public suffix in spite of being listed here: https://publicsuffix.org/list/public_suffix_list.dat

```
// site : 2015-01-15 DotSite Inc.
site
```

which causes `topPrivateDomain()` to fail, when it's called.

**Comment by cgdecker** [comment]
I just tried this with `24.0-jre` and it returned `business.site` as expected. You should check that there aren't older versions of Guava on your classpath somehow after upgrading to `24.1-jre`.

**Comment by Stephan202** [comment]
(For some tips on how to debug such classpath issues, see the comment section of #3108.)
