### ISSUE TITLE
Create ForwardingSpliterator

### ISSUE THREAD

**Issue by thecoop** [google/guava#3131]
As a counterpart to `ForwardingIterator`, create a `ForwardingSpliterator`. This is useful for, say, asserting characteristics, or a `Comparator`, onto a spliterator that doesn't know about those things by itself.

**Comment by kevinb9n** [comment]
I don't feel too good about this, because *most* users should virtually never interact with `Spliterator` in any way. It is a very "behind-the-curtain" type.

**Comment by nikhilbarar** [comment]
Is this still open? Can i pick it?

**Comment by lowasser** [comment]
We have not decided whether or not we think this ought to be added to Guava in the first place, but are leaning towards "it shouldn't."
