### ISSUE TITLE
Don't break the backward compatibility!

### ISSUE THREAD

**Issue by orionll** [google/guava#3133]
After upgrade from Guava 18 to Guava 23 our software stopped working for some customers because the visibility of `Iterators.emptyIterator` was changed from `public` to `package`.

Can you please stop breaking the backward compatibility?

**Comment by cardamon** [comment]
They only did so after a 2 year deprecation cycle...
Deprecated: May 7, 2014. Made package private: May 5, 2016

**Comment by orionll** [comment]
There should not be deprecation cycle at all. Just deprecate methods, but do not remove them. Millions of users depend on Guava, and we make them sad when the backward compatibility breaks.

**Comment by jbduncan** [comment]
Hi @orionll, good news (I think)! It seems that some time ago, the README was changed to say the following:

> APIs without @Beta will remain binary-compatible for the indefinite future. (Previously, we sometimes removed such APIs after a deprecation period. The last release to remove non-@Beta APIs was Guava 21.0.) Even @Deprecated APIs will remain (again, unless they are @Beta). We have no plans to start removing things again, but officially, we're leaving our options open in case of surprises (like, say, a serious security problem).

So I believe that versions of Guava 21.0 onwards are safe!

WDYT?

**Comment by cgdecker** [comment]
Yep, as @jbduncan says we are in fact committing to not break backwards compatibility for non-`@Beta` APIs. To ensure you aren't using `@Beta` APIs (which you shouldn't if other code outside your control is using your code, which it sounds like is the case here) you can use https://github.com/google/guava-beta-checker.
