### ISSUE TITLE
Add an .ifPresent(Consumer<? super T>) method to Optional

### ISSUE THREAD

**Issue by kevinmost** [google/guava#3135]
One of the best features of `java.util.Optional` is the ability to call `.ifPresent` on it, executing an action only if the Optional is populated: https://docs.oracle.com/javase/8/docs/api/java/util/Optional.html#ifPresent-java.util.function.Consumer-

Guava's Optional has no equivalent. Currently, there are 3 ways to achieve this behavior, from what I can tell:

1) Just manually unwrap the object. The most sane way, in my opinion, but very non-functional.
```
if (optional.isPresent()) {
  T optionalUnwrapped = optional.get();
  ...
}
```

2) Use `.transform` and do your side-effect-performing code in there, and just `return this` at the end. This is not semantically correct and will probably cause confusion for readers of the code.

3) Write a static utility method that looks something like `Optionals.ifPresent(optional, (value) -> ...);`. Unfortunately this is not as fluent as a method on `Optional`, and would be duplicated across projects.

I'd imagine the implementation would be as simple as:

```
public void ifPresent(Consumer<? super T> action) {
  if (isPresent()) {
    action.call(get());
  }
}
```

If there's any interest, I'd be happy to add this, along with Javadocs and tests, and send a PR.

Thanks for reading.

**Comment by kevinmost** [comment]
I would be open to that, I just thought it would be a safer change to put an implementation in the `Optional` class (maybe someone has implemented another subclass of `Optional` elsewhere for whatever reason, and we don't want to break their class and force them to implement a new method). But if that doesn't seem like a big deal then I am fine with implementing it either way, where `Present`'s entire method body would be `action.call(get());`, and `Absent` would have a no-op method.

**Comment by kluever** [comment]
I think we've been avoiding adding additional functionality to `c.g.c.base.Optional` since `j.u.Optional` has been released... @kevinb9n ?

**Comment by kevinmost** [comment]
I can understand that, but I think there is still value in `c.g.c.base.Optional`, for example, on Android. We can't use `j.u.Optional` because we still have to support phones that run Java 6 in our projects. Especially with Guava now having a specific Android-friendly artifact, I think a lot of people started using it on Android.

For us, seeing `@Deprecated` ever added to `c.g.c.base.Optional` would definitely make us very sad, haha.

Let me know if you're open to adding this. If not, thanks for considering anyway. :)

**Comment by kevinb9n** [comment]
I'm sorry, but the legacy Optional class is indeed frozen.
