### ISSUE TITLE
PatternCompiler should have public modifier

### ISSUE THREAD

**Issue by jreznot** [google/guava#3147]
At the moment, we are trying to modularize guava on the fly before linking with jlink.

In order to use modular JAR in the future PatternCompiler must have public modifier.

Otherwise: ServiceLoader throws exception - java.util.ServiceConfigurationError: com.google.common.base.PatternCompiler: module com.google.common does not declare `uses`

Also, we cannot define "uses" in module-info.java for com.google.common.base.PatternCompiler:
```
~/com.google.common/module-info.java:27: error: PatternCompiler is not public in com.google.common.base; cannot be accessed from outside package
uses com.google.common.base.PatternCompiler;
```

Solution: define com.google.common.base.PatternCompiler as public, any way, split packages are not allowed in modular environment

**Comment by jreznot** [comment]
Also, we could move `ServiceLoader.load(PatternCompiler.class)` call into the next `try {} ` block: https://github.com/google/guava/blob/master/guava/src/com/google/common/base/Platform.java#L82

**Comment by jreznot** [comment]
I've tried to fix this in the fork and successfully built module with the following module-info.java https://github.com/cuba-platform/cuba-cli/blob/feature/jlink/bundles/com.google.common/module-info.java

Thus, it definitely helps using guava in modular builds.

**Comment by lowasser** [comment]
Is there any alternative that keeps PatternCompiler package-private?  I think we wanted to avoid exposing that implementation detail, since it's mostly simply there for Google-internal reasons.

**Comment by jreznot** [comment]
You could move this line https://github.com/google/guava/blob/master/guava/src/com/google/common/base/Platform.java#L80 into try block. Anyway, ServiceLoader will throw exception for package-private class in modularized environments, thus custom PatternCompiler will not work.

**Comment by wangbo911** [comment]
1. wb1063916463@163.com

**Comment by wangbo911** [comment]
#3155

**Comment by cpovirk** [comment]
Sorry for the slow response. I think we'll just strip out the `ServiceLoader` usage entirely, since it's never been usable in public Guava, anyway (relying, as it does, on the ability to implement a package-private type).

**Comment by cpovirk** [comment]
And thank you for uncovering and reporting this! As you can tell, our Java 9 testing and fixes addressed only some of the issues that the module system can cause.
