### ISSUE TITLE
no main manifest attribute, in com.google.guava.guava-22.0.jar

### ISSUE THREAD

**Issue by Azimboy** [google/guava#3155]
I want to run `BaseEncoding.base64().encode()` method on Bash and trying to execute jar file but there is  following error. How can I this issue?
> comp@comp$ java -jar com.google.guava.guava-22.0.jar 
no main manifest attribute, in com.google.guava.guava-22.0.jar

**Comment by Azimboy** [comment]
@jbduncan thanks for your response! You are right, it is not an application and I've confused a little)). Yesterday I wanted to encode array of bytes to base64 on Bash and I did it with following way:
1) Created `EncodeBytes` class and implemented this logic:
```
import com.google.common.io.BaseEncoding;
import java.util.Random;

class EncodeBytes {
    public static void main(String[] args) {
        byte[] bytes = new byte[16];
        new Random().nextBytes(bytes);
        System.out.println(BaseEncoding.base64().encode(bytes));
    }
}
```
2) Executed following commands on Bash:
```
comp@comp$ javac -cp com.google.guava.guava-22.0.jar: EncodeBytes.java
comp@comp$ java -cp com.google.guava.guava-22.0.jar: EncodeBytes
comp@comp$ 2XN6/1KKsW7BbU/GD0iT8A==
```

**Comment by jbduncan** [comment]
@Azimboy Cool, glad to hear you managed to solve your problem!

I found this link the other day that I think should allow you to base64-encode a string without depending on Java, if that would be of interest to you: https://scottlinux.com/2012/09/01/encode-or-decode-base64-from-the-command-line/. :)
