### ISSUE TITLE
BiFunction separator provider for Joiner

### ISSUE THREAD

**Issue by rgoldberg** [google/guava#3164]
I have a use case for `Joiner` where the separator must be obtained from the next part to be joined.  I can imagine situations where the separator must be obtained from the previous part to be joined, or from some logic operating on both the previous and the next parts.

Would you consider allowing a `BiFunction<T, T, String>` to be a separator provider, where the previous part is the first argument, the next part is the second argument, and the return value is the separator?

This would require either having `Joiner<T>`, or casting within a raw-type or wildcard `BiFunction`.

If this were implemented, I'd imagine that `MapJoiner` should support an analogous key separator provider, too.

**Comment by kevinb9n** [comment]
We're actually de-emphasizing `Joiner` now in favor of `Collectors.joining()`, `String.join()`, and `StringJoiner`, all in the JDK. I don't think we'll be adding more features to it, sorry!
