### ISSUE TITLE
Possible typos: @javax.annotation.Nullable is only used in two places

### ISSUE THREAD

**Issue by rgoldberg** [google/guava#3166]
There is probably a typo in each of the two following lines of `NullPointerTesterTest`:

https://github.com/google/guava/blob/0a2258e6691a22aa7ff2604871b520d44bbac01f/guava-testlib/test/com/google/common/testing/NullPointerTesterTest.java#L89

https://github.com/google/guava/blob/0a2258e6691a22aa7ff2604871b520d44bbac01f/guava-testlib/test/com/google/common/testing/NullPointerTesterTest.java#L553

They use `@javax.annotation.Nullable`, but all other `@Nullable` uses seem to be `@org.checkerframework.checker.nullness.qual.Nullable`.

**Comment by cpovirk** [comment]
Thanks, but these are intentional tests that `NullPointerTester` recognizes the `javax` `@Nullable`.
