### ISSUE TITLE
Wiki: typo in the CaseFormat example code snippet

### ISSUE THREAD

**Issue by jmini** [google/guava#3167]
I have spotted a small typo in the “CaseFormat” section, in the code snippet: there should be only one closing bracket instead of two.

---

This is a patch for the wiki repository:
```
git clone https://github.com/google/guava.wiki.git
```

Patch:
[patch.diff](https://github.com/google/guava/files/2049421/patch.diff.txt)

---

Is:
 ```java
CaseFormat.UPPER_UNDERSCORE.to(CaseFormat.LOWER_CAMEL, "CONSTANT_NAME")); // returns "constantName"
```

Should be:
 ```java
CaseFormat.UPPER_UNDERSCORE.to(CaseFormat.LOWER_CAMEL, "CONSTANT_NAME"); // returns "constantName"
 ```

**Comment by jrtom** [comment]
I've fixed it.  Thanks!  :)
