### ISSUE TITLE
ImmutableRangeSet.intersection generates empty ranges

### ISSUE THREAD

**Issue by FranckDG** [google/guava#3177]
ImmutableRangeSet.intersection can generate some empty ranges in specific cases. In my example, I have this:
- Set #1 contains this range [10210..10211)
- Set #2 contains this range (10210..10211]
- The resulting intersection set contains (10210..10211) which is essentially empty

**Comment by jrtom** [comment]
This is true.  It's not clear what you're suggesting should be done about this (if anything), though.  

The documentation for [Range.isEmpty()](https://google.github.io/guava/releases/snapshot/api/docs/com/google/common/collect/Range.html#isEmpty--) may be of interest here.

**Comment by kevinb9n** [comment]
Yes, that documentation explains as a *Range*, such a case is not in fact "empty".

**Comment by lowasser** [comment]
A reliable way of addressing this is to canonicalize all ranges in all the RangeSets.  But a RangeSet cannot, by itself, canonicalize ranges or determine that that range is "empty," since it isn't .isEmpty.
