### ISSUE TITLE
Iterables.concat has unexpected behaviour

### ISSUE THREAD

**Issue by jbee** [google/guava#3178]
I was looking for a convenient way to build a `Iterable` for a collection of `Iterable`s and tried `Iterables.concat(Iterable<? extends Iterable<? extends T>> inputs)` (v25.1)

My expectation is that this is functionally equivalent to iterating all `Iterable`s and appending all the elements into a new collection that is the merged `Iterable` (just without creating an actual intermediate collection). This does not seamed to be true as it was failing my tests both due to lack of expected elements and throwing `NoSuchElementException` unexpectedly. Building the intermediate collection works fine. 

To cross check I wrote a naive version myself that looks like this:

```
final Iterable<Iterable<String>> sources = ....
return new Iterable<String>() {

            @Override
            public Iterator<String> iterator() {
                return new Iterator<String>() {

                    Iterator<Iterable<String>> iter = sources.iterator();
                    Iterator<String> cur;

                    @Override
                    public boolean hasNext() {
                        if (cur == null && !iter.hasNext())
                            return false;
                        if (cur == null)
                            cur = iter.next().iterator();
                        while (!cur.hasNext()) {
                            if (!iter.hasNext())
                                return false;
                            cur = iter.next().iterator();
                        }
                        return true;
                    }

                    @Override
                    public String next() {
                        if (cur == null)
                            throw new NoSuchElementException();
                        return cur.next();
                    }
                };
            }
        };
```
This also has the expected behavior. So I cannot put my finger on what goes wrong with `Iterables.concat` but it surely is not transparent. Or I misunderstand its use case.

**Comment by jrtom** [comment]
If you can provide a self-contained example that demonstrates the behavior you're talking about, then we can try to investigate it.  Otherwise, it's going to be difficult to help you.

**Comment by jbee** [comment]
I wasn't asking for help. Just wanted to point your attention to something that might be a defect. I have no small self-contained example I can give you therefore I gave you two scenarios that work as expected (my naive `Iterable` of `Iterable`s and building an intermediate list) while `Iterables.concat` does not.

**Comment by kevinb9n** [comment]
Thanks for trying to report this problem, but unfortunately there's no way for us to take action on your report. We would need to try writing random variations of code until we just happened to stumble upon a bug, which might be the same as whatever problem you observed. But we already tried testing everything we could think of and have thousands of internal usages that seem to be working. If you can provide code that produces the wrong behavior, we can look at it (please reopen in that case). Thanks!

**Comment by jbee** [comment]
Debugged it. Problem occurs in case the underlying iterators behave differently in case `hasNext` is called multiple times before `next` is called. So this is not strictly a defect in `ConcatenatedIterator` but its implementation could avoid the problem by making sure `hasNext` is only called once before `next` is called.

**Comment by kevinb9n** [comment]
Thanks for looking into it. An iterator whose `hasNext` changes the iterator's observable state is broken, so we would not be inclined to modify our implementation to work around that.

**Comment by cpovirk** [comment]
(Does it sound anything like https://github.com/google/guava/issues/2804?)

**Comment by reschke** [comment]
Absolutely.
