### ISSUE TITLE
InternetDomainName possibly misbehaving — request for clarification

### ISSUE THREAD

**Issue by jiraky90** [google/guava#3182]
I'm finding troubles in understanding the behaviour of the method `com.google.common.net.InternetDomainName#isValid(String domain)`.
It is supposed to validate a domain name but with certain inputs such as the following it looks like it is misbehaving. For example:
```
a17c49l68ntkqnuhvkrmyb28fubvn30e31g43dq
bcjnlreouu
b18p12jzcudyowntgxh64kygvd30pwgto51lz
b18dto41jugvitb68mqc69ltkwe51l58j66k37p22
b18n10fxbqlzd50iujzfsn10fqoujrfyetoz
```
For each one of them the method returns `true`.
In comparison, the Apache `org.apache.commons.validator.routines.DomainValidator#isValid(String domain)` class returns `false`.

Is this behaviour intentional? 

----
Libraries from maven:
- Google Guava: `com.google.guava:guava:24.0-jre`
- Apache Validator: `commons-validator:commons-validator:1.6`

Code to reproduce the issue
```java
import com.google.common.net.InternetDomainName;
import org.apache.commons.validator.routines.DomainValidator;
public class Test {
    public static void main(String[] args) {
        String domainName = "a17c49l68ntkqnuhvkrmyb28fubvn30e31g43dq";
    
        System.out.println(InternetDomainName.isValid(domainName));
        System.out.println(DomainValidator.getInstance().isValid(domainName));
    }
}
```

**Comment by cgdecker** [comment]
It looks to me like this behavior is intended because those strings could, syntactically, be domain names.

@cdberry is my understanding correct?

**Comment by cdberry** [comment]
Yes, that's the correct behavior. isValid simply checks that the form of the string is syntactically correct per the relevant RFCs. If you want to determine whether the string represents a plausible host address, you probably want InternetDomainName#hasPublicSuffix:

https://google.github.io/guava/releases/snapshot/api/docs/com/google/common/net/InternetDomainName.html#hasPublicSuffix--

There's a useful explanation of this here: https://github.com/google/guava/wiki/InternetDomainNameExplained

**Comment by cgdecker** [comment]
Thanks!
