### ISSUE TITLE
Potential issues with File.length() calls in Files

### ISSUE THREAD

**Issue by leventov** [google/guava#3190]
3 calls to `File.length()` in [`Files`](https://github.com/google/guava/blob/0cd4e9faa1360da4a343f84cb275d6eda0c5e732/guava/src/com/google/common/io/Files.java): in `FileByteSource.sizeIfKnown()`, `FileByteSource.size()` and `Files.map()` might be problematic because they don't check if `File.length()` returns 0 or not, that may signify an I/O error.

**Comment by cgdecker** [comment]
Other than changing `Files.asByteSource` to delegate to `MoreFiles.asByteSource` (which, as I mentioned in the other issue, we could only do for non-Android), there's not much we can do about this. That said, maybe it's worth the diff if it solves both this and the finalizer thing.

**Comment by cgdecker** [comment]
That said, I'm also not terribly worried about this in practice: both `size()` and `sizeIfKnown()` check `file.isFile()` before trying to read the length, which seems highly likely to return `false` if the file doesn't exist or there's any issue that would cause the code to be unable to read the attributes of the file, which seems like the most likely error cases where `length()` would return 0.

**Comment by leventov** [comment]
I probably realise the problem now: there is no way to distinguish benign file size of 0 from an I/O error. However, at least in case of `Files.map()`, it might be worthwhile to resort to `RandomAccessFile.length()` (JDK 1.0+), since file descriptor is created later in this procedure anyway.

**Comment by cgdecker** [comment]
Yeah exactly, that's the main issue here with the `File.length()` API itself.

Good suggestion about getting the file size later. I'm making that change.
