### ISSUE TITLE
Feature Request: Make MinMaxPriorityQueue Serializable

### ISSUE THREAD

**Issue by elbaulp** [google/guava#3192]
[Long time ago someone proposed to serialize some collections](https://github.com/google/guava/issues/615). It would be nice if one of them were MinMaxPriorityQueue.

For a few days I am struggling with unexpected functionality in my Flink application, and now it seems I found the problem. Its because MinMaxPriorityQueue is not serializable. 

You can check the following links:

- https://stackoverflow.com/questions/51058968/mapping-values-returns-nothing-in-scala-flink
- https://stackoverflow.com/questions/51086803/serialize-guavas-minmaxpriorityqueue

I've tried to check the code for MinMaxPriorityQueue to make it Serializable, but I do not know how to do it. It is feasible?

Bests

**Comment by jbduncan** [comment]
Effective Java 3rd Edition, Item 85: "Prefer alternatives to Java serialization" provides a great explanation IMO of why one should avoid Java's built-in serialization if at all possible (basically, it opens up Java applications to a very big, difficult-to-avoid security hole by today's standards), but I recognise that perhaps Flink doesn't provide a way of serializing MinMaxPriorityQueue without resorting it to having it implement `Serializable`.

But having said this, it looks to me that [this StackOverflow answer](https://stackoverflow.com/a/51089059/2252930) may be able to help you in this particular case without forcing the Guava developers make MinMaxPriorityQueue implement `Serializable`.

Can you let us know if it works for you or not? :)

**Comment by tlinkowski** [comment]
I agree that making `MinMaxPriorityQueue` `Serializable` does not sound like a good idea.

As @jbduncan mentioned, Java serialization is considered risky, and there are even [plans to remove it at all](https://www.infoworld.com/article/3275924/java/oracle-plans-to-dump-risky-java-serialization.html).

**Comment by elbaulp** [comment]
Thanks both (@tlinkowski & @jbduncan) for your reply. I didn't know it
was so risky.

@jbduncan I am trying to apply
[Tomasz](https://stackoverflow.com/a/51089059/2252930) answer to my
question in scala. I will inform you as soon as I try it.


-- 
elbauldelprogramador.com

**Comment by cgdecker** [comment]
I think we would generally prefer to avoid making more things serializable, though with all the serializable collection types we already have I wouldn't necessarily rule this out.

**Comment by elbaulp** [comment]
@jbduncan After trying the answer proposed by @tlinkowski without luck, I finally implemented other solution ([you can check it here](https://stackoverflow.com/a/51106451/1612432)).

Could you guys explain to me why it is a security risk to Serialize some collections? I would like to know.

Best

/cc @cgdecker

**Comment by elbaulp** [comment]
@jbduncan Thank you very much!

**Comment by cpovirk** [comment]
While I'm not ruling out that we'd someday make some type serializable, it seems unlikely that we'll do it for many, given all the trouble that serialization can cause (including increasing the surface for security problems, even for users who don't "use" a type).

`MinMaxPriorityQueue` has probably a better case than some other types we've heard requests for (e.g., https://github.com/google/guava/issues/1922), but I still think it's unlikely, especially since it's mutable.
