### ISSUE TITLE
Support for JWTs

### ISSUE THREAD

**Issue by perezd** [google/guava#3199]
I'd love to see JWT support in Guava, Auth0 team has an example java impl that relies on apache commons and jackson. I'd love to see this done with Guava primitives instead and exposed as a proper API from Guava.
https://github.com/auth0/java-jwt/tree/master/lib/src/main/java/com/auth0/jwt

**Comment by ronshapiro** [comment]
Is this better suited in a library like Gson? Guava doesn't do anything with JSON currently

**Comment by perezd** [comment]
Possibly. JWT has way more to do with hashing and signing which is in the
Guava wheel house..but its encoded as JSON + base64.

**Comment by cgdecker** [comment]
This seems like something that could be implemented as a separate API using things from Guava, but it doesn't really seem to me like something we'd want to include in Guava. For the most part, where Guava includes things related to specific technologies such as this, they're extremely widely used things like HTTP and/or things that have been very commonly needed within Google. This also isn't something anyone on our team has any expertise in AFAIK, which makes maintenance difficult and makes me think it wouldn't be a good fit for Guava.
