### ISSUE TITLE
MoreFiles.deleteRecursively() doesn't throw NoSuchFileException if the given path doesn't exist

### ISSUE THREAD

**Issue by leventov** [google/guava#3203]
Instead, it throws a `FileSystemException` with a `NoSuchFileException` suppressed, making it impossible to distinguish "the root path doesn't exist" from "impossible to delete one of the children of the root path". That would be the way to implement "deleteRecursivelyIfExists" kind of operation, atomic with regard to the root existence:
```java
try {
  MoreFiles.deleteRecursively(path);
} catch (NoSuchFileException e) {
  // ignore
}
```

BTW, it's not obvious what does _(optional specific exception)_ construction mean in Javadocs, and I didn't find the definition or elaboration of this construction.

**Comment by awesomefei** [comment]
Hello, I am new here and I wonder if I can join you guys and work on this stuff since this is low priority and seems a good starter?
