### ISSUE TITLE
Not able to build the source code v18.0

### ISSUE THREAD

**Issue by jayanth-ganganahalli** [google/guava#3207]
Hi,
I took source code from "https://github.com/google/guava/tree/v18.0". While trying to build, I am getting the below error:
"D:\NMS_NG\V1.0SinecDev\src>mvn clean verify
Done: MAVEN_OPTS="-Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.al
lowall=true -Dmaven.wagon.http.ssl.ignore.validity.dates=true"
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Child module D:\NMS_NG\V1.0SinecDev\src\guava of D:\NMS_NG\V1.0SinecDev\
src\pom.xml does not exist @
[ERROR] Child module D:\NMS_NG\V1.0SinecDev\src\guava-gwt of D:\NMS_NG\V1.0Sinec
Dev\src\pom.xml does not exist @
[ERROR] Child module D:\NMS_NG\V1.0SinecDev\src\guava-testlib of D:\NMS_NG\V1.0S
inecDev\src\pom.xml does not exist @
[ERROR] Child module D:\NMS_NG\V1.0SinecDev\src\guava-tests of D:\NMS_NG\V1.0Sin
ecDev\src\pom.xml does not exist @
@
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project com.google.guava:guava-parent:18.0 (D:\NMS_NG\V1.0SinecDev
\src\pom.xml) has 4 errors
[ERROR]     Child module D:\NMS_NG\V1.0SinecDev\src\guava of D:\NMS_NG\V1.0Sinec
Dev\src\pom.xml does not exist
[ERROR]     Child module D:\NMS_NG\V1.0SinecDev\src\guava-gwt of D:\NMS_NG\V1.0S
inecDev\src\pom.xml does not exist
[ERROR]     Child module D:\NMS_NG\V1.0SinecDev\src\guava-testlib of D:\NMS_NG\V
1.0SinecDev\src\pom.xml does not exist
[ERROR]     Child module D:\NMS_NG\V1.0SinecDev\src\guava-tests of D:\NMS_NG\V1.
0SinecDev\src\pom.xml does not exist
[ERROR]"

I am using Windows 10, JDK 1.8 and Maven 3.3.

Please help me in building the source code.

**Comment by netdpb** [comment]
I don't think we can help you without seeing your configuration. We can't provide personalized support for Maven.

It looks like maybe you don't have all the source? (You're also trying to build quite an old version.) Have you asked on StackOverflow for help from the community?
