### ISSUE TITLE
==Preconditions.checkPositionIndexes==wiki may be incorrect

### ISSUE THREAD

**Issue by deathbit** [google/guava#3208]
wiki says "Checks that [start, end)"
I think it should be [start, end]

hope for your reply

**Comment by jonahgreenthal** [comment]
Ranges in Java are almost always right-half-open. See e.g. [the documentation for `List.sublist()`](https://docs.oracle.com/javase/8/docs/api/java/util/List.html#subList-int-int-).

**Comment by cpovirk** [comment]
The quote:

> Checks that `[start, end)` is a valid sub range of a list

Like jonahgreenthal says, I think that's accurate but confusing. ["A position index may range from zero to `size`, inclusive."](https://google.github.io/guava/releases/snapshot/api/docs/com/google/common/base/Preconditions.html#checkPositionIndexes-int-int-int-), just like the indexes to a `subList` call.

The more direct statement would be something like:

> Checks that `start` are `end` both in the range `[0, size]` (and that `end` is at least as large as `start`)
