### ISSUE TITLE
Large Regression in Performance of ImmutableSet Building.

### ISSUE THREAD

**Issue by bobyangyf** [google/guava#3223]
https://github.com/google/guava/commit/a98632ee83a6c4c93f4b31820437f68ddde041dd#diff-439cf531381acbc7a3a95b99000d22ca
Introduced a significant performance regression.

The regression caused certain commands of our project to regression 50%.

I performed JMH benchmarks and got the following results (Note: small set is 3 distinct elements, large set is 1000000 insertions, 500000 distinct elements, elements are Integers, building is `add()` and `build()` operations)

testname | Without Mentioned Changed: | With Mentioned Changes 
----------|-------------------------------|--------------------------
addAndBuildSmallSet | 11841379.432 ± 605281.339 ops/s | 11402608.445 ± 145690.757 ops/s 
addAndBuildLargeSet | 16.375 ± 4.594  ops/s |  11.539  ± 1.504  ops/s

This is almost a 100% regression in small set building and 50% regression in large set building.

**Comment by bobyangyf** [comment]
I already have some local changes that seems to solve this regression. Expect PR soon as I verify :)

**Comment by kevinb9n** [comment]
Thanks for looking into this. Have you been able to identify which revision might have been responsible?

**Comment by lowasser** [comment]
@kevinb9n , the OP posted a link in the first line of their comment.

I can readily believe that this would have introduced a regression, and would be eager to see a PR to fix it.  I'd hope we can make sure we keep the key features of the original change, though

* recognizing hash flooding and falling back
* O(1) build
* up-front deduplication at add() time

**Comment by bobyangyf** [comment]
Seems like something was a bit off with the small set profiling. Updated the numbers a bit in this task. The regression is only limited to large sets, which is reasonable.

A pull request has been submitted which greatly improves the performance of large sets.
https://github.com/google/guava/pull/3225

I would like to point out that the current build is not O(1), but O(n) as we go through the entire hashtable for `hashFloodingProtection()`.

I kept the following features:
- recognizing hash flooding and falling back
- O(n) build as before
- partial deduplication at add() time with expected average of O(m) memory usage.

**Comment by bobyangyf** [comment]
So the regression is actually due to higher allocation rates from resizing.
Ex: Benchmarks of various scenarios showed that if we preallocate all the array space needed, but still hash and resize with the current table size algorithm, we'll see only minor regressions.
benchmarkOfBeforeRegression      thrpt    2775.109 ops/s
benchmarkOfRegression      thrpt    2632.751 ops/s
benchmarkOfRegressionPreallocate thrpt    2776.495 ops/s

This isn't really solvable if we want to deduplicate elements as we get them. The PR previously mentioned fixed this in benchmarks by changing the resize rate slightly, but in real world it is not always beneficial.

Before the regression diff, we would only resize one array consistently, whereas we now resize that array + a hashtable array, which is twice the allocations.

Using `builderWithExpectedSize` in most places solves this problem, but it is not always feasible to know the size ahead of time.
The current solution to this would be to build an "ImmutableList" first, and then create the set based on the List with expectedSize.
We "could" add a new "DedupDeferringBuilder" that doesn't dedup and hash as elements come so we only need to keep one array that is resized and only hashes on build, but with fall back for hash collisions.

**Comment by bobyangyf** [comment]
@lowasser @kevinb9n Wondering what your thoughts are regarding the comment above.

**Comment by lowasser** [comment]
So, a breakdown of my thoughts:

* I think it's good to only allocate O(distinct) memory.  I think there's honestly a lot of cases where `ImmutableSet` is used to deduplicate collections with potentially _many_ duplicates, for example, and I think it'd be surprising if the asymptotics of `Sets.newHashSet(collection)` and `ImmutableSet.copyOf(collection)` were different.
* I would be very sad to add more "knobs" that users would need to know and care about.  I would prefer _not_ to have a different builder or configurability on how the builder works.
* I'd be interested in heuristic or other clever ideas for bringing constant factors down, and I'm not yet certain I'm out of ideas there.

**Comment by bobyangyf** [comment]
>> I think it's good to only allocate O(distinct) memory. I think there's honestly a lot of cases where ImmutableSet is used to deduplicate collections with potentially many duplicates, for example, and I think it'd be surprising if the asymptotics of Sets.newHashSet(collection) and ImmutableSet.copyOf(collection) were different.

I agree with O(distinct), but not necessarily at the expense of performance we are seeing right now.
In fact, with so many reallocations due to resizing the array, we could end up allocating more memory in total (although true that they can be GC'ed). Which is why I'm proposing alternatives that lets us keep both.

>> I'd be interested in heuristic or other clever ideas for bringing constant factors down, and I'm not yet certain I'm out of ideas there.
We want to bring the total # of reallocation down, which requires tuning the resize ratios. Perhaps a dynamic one that estimates the expected size depending on the # duplicates inserted so far?

**Comment by wolfs** [comment]
Any ideas if this regression will/can be fixed? It currently block the Gradle project from using the non-android variant of guava. We tried gathering the elements in an `ArrayList`/`HashSet` first, though that did not help. See https://github.com/gradle/gradle/pull/9002.

**Comment by bobyangyf** [comment]
Ah I had a CR for this that would optimize since scenarios but not fix the entire regression. 
I should fix that for java 11 and see it through

**Comment by lowasser** [comment]
FWIW, I would expect that you could always work around this by presizing the builder?

This also should never perform significantly worse than creating a HashSet and calling addAll, so I'm a little surprised that this would be blocking for anyone.
