### ISSUE TITLE
Formatting of links broken in Wiki

### ISSUE THREAD

**Issue by kaibolay** [google/guava#3230]
For example in a couple of places on https://github.com/google/guava/wiki/ThrowablesExplained

![image](https://user-images.githubusercontent.com/9759792/43927000-0e877ac4-9bfa-11e8-9124-e80a4d6897c9.png)

**Comment by jrtom** [comment]
Thanks for the report.  We'll have a fix for that soon.

**Comment by elharo** [comment]
This one appears to be fixed? I think it can be closed.

**Comment by kaibolay** [comment]
Yes, it's fixed.
