### ISSUE TITLE
POM file does not have a license section.

### ISSUE THREAD

**Issue by DamianReeves** [google/guava#3233]
The company I work for is looking to use on-board its own in-house maven repo via Artifactory. There are certain safe guards in place, one of which is that packages with no license or an unapproved license are automatically blocked.

Since guave is Apache 2, which is an allowed license it seems that the blocker on me using this is that the pom files that are published do not contain a license section.

Can such a section be added to future deployments?

**Comment by ronshapiro** [comment]
Does the license in the parent pom not get inherited?

**Comment by DamianReeves** [comment]
This seems to be a non-issue, I was looking at an older version of the package.
