### ISSUE TITLE
What's the status of ByteStreams API?

### ISSUE THREAD

**Issue by pluttrell** [google/guava#3239]
The `com.google.common.io.ByteStreams` class is marked with `@Beta`, which I understand to mean that it's public API might change and thus we're warned about using it with libraries ([reference](https://google.github.io/guava/releases/26.0-jre/api/docs/com/google/common/annotations/Beta.html)).

Is there an ETA when the API might be considered stable enough to remove `@Beta`?

**Comment by cgdecker** [comment]
`ByteStreams`, and much of `common.io`, is definitely on the list of things we should be trying to get out of `@Beta`, we just haven't been good about prioritizing reviewing things for graduation from beta. Thanks for the reminder.

**Comment by kluever** [comment]
@elharo just requested (internally) a de-@Beta'ing of `ByteStreams.exhaust()`
