### ISSUE TITLE
Java 11 Compatibility check: guava

### ISSUE THREAD

**Issue by KryniuPL** [google/guava#3241]
Hi,
We are reaching out to you to check Java 11 compatibility of the library: guava.

Could you help us by answering the following questions:

1. Library Name: <library name.="" e.g:="" activation="">
2. Latest version: <latest 1.1.1="" eg:="" version.="">
3. Latest version Is the library compatible with Java 11 Compatible? (Y/N)
4. Is the library supported with Java 11? (Y/N)
5. (If “N” in compatibility or support) What is the versions that would be compatible and Supported?
6. Date of support availability?</latest></library>

Appreciate your response by 19.08.2018.

Thanks,
Krzysztof Dragan,
PTC Inc. Contractor

**Comment by cgdecker** [comment]
As far as I know, we haven't done any specific testing of Guava with Java 11. I don't anticipate there should be many issues.
