### ISSUE TITLE
Add java.time.Duration overloads to TimeLimiter

### ISSUE THREAD

**Issue by simon04** [google/guava#3242]
The `TimeLimiter` interface specifies five methods taking `long timeoutDuration, TimeUnit timeoutUnit`. Consider adding a `java.time.Duration` overload similar to #2999, #3169.

**Comment by omkarnix** [comment]
Hi. Is anyone working on this? Also is it the beginner/first timer issue?

**Comment by nglorioso** [comment]
@kluever did this in 1ef1d52a53b5eabadc859bbd40b11d8c6fa424dd
