### ISSUE TITLE
add JVMLaunchers

### ISSUE THREAD

**Issue by harbby** [google/guava#3246]
Like this: The Callable event is executed by the child process (jvm)
```
        JVMLauncher<Integer> launcher = JVMLaunchers.<Integer>newJvm()
                .setCallable(() -> {
                    TimeUnit.SECONDS.sleep(1);
                    System.out.println("************ job start ***************");
                    return 1;
                })
                .addUserjars(Collections.emptyList())
                .setConsole((msg) -> System.out.println(msg))
                .build();

        VmFuture<Integer> out = launcher.startAndGet();
```

**Comment by harbby** [comment]
I used the above method to simplify the simple operation of multi-process

**Comment by cgdecker** [comment]
A better API for running commands would be nice, but I don't think that we'd want to make one specific to running JVMs. It's something we might get to eventually, but it's very low priority so I'm just going to go ahead and close this. Thanks for the suggestion though!

**Comment by harbby** [comment]
Very looking forward to
