### ISSUE TITLE
jarroddeming@gmail.com

### ISSUE THREAD

**Issue by JarrodDeming** [google/guava#3250]
Bypass 2 step verification

**Comment by jbduncan** [comment]
Hi @JarrodDeming. I am struggling to understand what you're requesting here. Would you kindly clarify things for us? 🤔

**Comment by jrtom** [comment]
@JarrodDeming I'm not clear on what you're asking for either, but it's pretty clear to me that it's not related to Guava, so I'm closing this issue.

My best guess is that you're trying to sort something out with git or with GitHub; the Guava project does not encompass either of these.

**Comment by JarrodDeming** [comment]
jarroddeming@gmail.com account login
