### ISSUE TITLE
TypeParameter.of()

### ISSUE THREAD

**Issue by basinilya** [google/guava#3260]
I need to construct a resolved type token from an arbitrary raw class and an array of actual type arguments. In particular, I manually replace some wildcards in actual type arguments with their bounds. Unlike in the `mapToken` example from https://github.com/google/guava/wiki/ReflectionExplained#introduction I can't create anonymous TypeParameter subtypes, because the types are only known at runtime.

Please add TypeParameter.of() similar to TypeToken.of() . Or overload `where()` to accept TypeVariable. Or make Types.newParameterizedTypeWithOwner() public.

	// returns Map<String, BigInteger>
	anyToken(Map.class, new Type[] { String.class, BigInteger.class });
	
	static TypeToken anyToken(Class rawClass, Type[] actualTypeArguments) {
		TypeToken genericType = TypeToken.of(Object.class).getSubtype(rawClass);
		TypeVariable[] tvars = rawClass.getTypeParameters();
		for (int i = 0; i < tvars.length; i++) {
			TypeVariable tvar = tvars[i];
			Type realTarg = actualTypeArguments[i];
			genericType = genericType.where(TypeParameter.of(tvar), TypeToken.of(realTarg));
		}
		return genericType;
	}

**Comment by fluentfuture** [comment]
Yeah. Probably either `newParameterizedType()`, or if we could support `type.toGenericForm()`, you can then take the generic form and do the reflection magic, as in:

```java
// Turn Map<...> to Map<K, V>
TypeToken<?> generic = type.toGenericForm();
generic.where(k, keyBound).where(v, valueBound);
```

Will that work for you? 

(not really sure about the method name though)

**Comment by basinilya** [comment]
In your example how do you obtain k and v?

**Comment by fluentfuture** [comment]
Potentially by calling `Class#getTypeParameters()`. `newParameterizedType()` could be implemented as:

```java
Type newParameterizedType(Class<?> cls, Type... args) {
  TypeToken<?> type = TypeToken.of(cls).toGenericForm();
  for (int i = 0; i < args.length; i++) {
    type = type.where(cls.getTypeParameters()[i], args[i]);
  }
  return type;
}
```

**Comment by basinilya** [comment]
For that to work we need to at least overload `TypeToken.where()`. 

Adding `toGenericForm()` is optional, because `TypeToken.of(Object.class).getSubtype(cls)` does the same.

**Comment by fluentfuture** [comment]
Sorry I confused `TypeToken.where()` with `TypeResolver.where()`. It should have been:

```java
Type newParameterizedType(Class<?> cls, Type... args) {
  TypeResolver resolver = new TypeResolver();
  for (int i = 0; i < args.length; i++) {
    resolver = resolver.where(cls.getTypeParameters()[i], args[i]);
  }
  return resolver.resolveType(toGenericForm(cls));
}
```

Does `getSubtype()` do this? Never thought of this use case.

**Comment by basinilya** [comment]
Yes. Thank you. Then no API change needed.

**Comment by basinilya** [comment]
> Does getSubtype() do this?
Almost. It doesn't create `java.util.List<E>[]` out of `List[].class`
