### ISSUE TITLE
Uninterruptibles.sleepUninterruptibly Accuracy

### ISSUE THREAD

**Issue by JerryChin** [google/guava#3263]
I have a question regarding the following lines:

https://github.com/google/guava/blob/e2cf262d89c65a701de72df20c38808640e7e86c/guava/src/com/google/common/util/concurrent/Uninterruptibles.java#L310-L315

As you see, the line for `interrupted ` assignment comes before `remainingNanos ` calculation, I think it will cause the calculation to be less accurate for the prior assigment cost a little bit cpu time.

Any more thoughts on this?

Here's a snippet of assigment performence test I wrote:

    int TEST_TIMES = 100000;
    boolean interrupted = false;
    long start;
    long[] stat = new long[TEST_TIMES];
    for(int i = 0; i < TEST_TIMES; i++) {
         boolean updated = !interrupted;
         
         start = System.nanoTime();
         interrupted = updated;
         stat[i] = System.nanoTime() - start;
    }
    long sum = 0;
    for (long s : stat) {
    sum += s;
    }

    System.err.println("avg s: " + (sum/TEST_TIMES));

It's about **30ns** for an assignment on my machine(Intel Core i7-7700 3.60GHz), for anyone who wants to sleep, let's say 100ns( not sure if it's possible to do so), the impact could be huge.

**Comment by JerryChin** [comment]
That makes a lot of sense, thank you for reviewing this issue!

**Comment by BartlomiejTerenowicz** [comment]
Fix and close.

**Comment by JakubGarbacz** [comment]
fix like in

**Comment by nglorioso** [comment]
I'm not sure what's left to do here. Hope the response from @dimo414 was helpful!
