### ISSUE TITLE
Can guava 25 support guava 19

### ISSUE THREAD

**Issue by huyuechy** [google/guava#3264]
In my project ,I need two jars. One jar needs guava 19,while other  jar needs guava 25.It seems that  guava 25 are not compatible with guava 19.
In guava 19   one method of the class  "Futures"  is as follow:
`public static <I, O> ListenableFuture<O> transform(ListenableFuture<I> input, AsyncFunction<? super I, ? extends O> function) {
        return transformAsync(input, function);
    }`

while in guava 25  the corresponding method of the class  "Futures"  is as follow:
`public static <I, O> ListenableFuture<O> transform(ListenableFuture<I> input, Function<? super I, ? extends O> function) {
        return AbstractTransformFuture.create(input, function, MoreExecutors.directExecutor());
    }`

The same method of two version jar are conflict。

The  two jars in my project are third party. What should I do?

**Comment by ChristianCiach** [comment]
Ah yes, that's a classic :) As I see it, you have no other choice than to update or fork the library depending on the old version of guava. I remember having this exact same problem with the datastax Cassandra connector, that was eventually fixed on their side. 

If the library depending on the old version of guava is open source, you may want to send a pull request to them. You can maintain a private fork of the library until your pull request has been merged upstream. That's the way I usually handle this.

**Comment by ronshapiro** [comment]
This appears to be a question - please use StackOverflow with the `dagger-2` tag instead, as that is a better forum for questions.
