### ISSUE TITLE
guava-26.0-android introduces jdk 1.8 jar

### ISSUE THREAD

**Issue by henrik242** [google/guava#3271]
26.0-android depends on checker-compat-qual-2.5.2.jar, which is built with target jdk 1.8 (version 52.0), which makes it impossible to use with jdk 1.7.

Should checker-compat-qual be downgraded, or the readme updated to reflect this?

**Comment by cpovirk** [comment]
Hmm, what error are you seeing? I'm seeing major version 50 for that jar:

```
$ javap -v -cp Downloads/checker-compat-qual-2.5.2.jar org/checkerframework/checker/nullness/compatqual/NullableType | grep 'major version'
  major version: 50
```

**Comment by henrik242** [comment]
Weird.  I'm sure I saw major version: 52 there yesterday.  Today it looks fine.  Never mind, thanks for looking into it anyway.
