### ISSUE TITLE
Only one of the ImmutableTable collectors is @Beta

### ISSUE THREAD

**Issue by mjustin** [google/guava#3278]
I notice that only one of the two `ImmutableTable.toImmutableTable` collectors is marked as `@Beta`.  Looking at the commit history, [9d028d0](https://github.com/google/guava/commit/9d028d0014840f295c35e1edd85e049d561864a3) was the commit that added the `@Beta` annotation with a message of "Add @beta to the ImmutableTable collectors."  However, despite the commit message, only the one collector was annotated as `@Beta` at that time.

I would guess, therefore, that we would want either both of the collectors marked as `@Beta`, or neither.

**Comment by cpovirk** [comment]
Finally solved by removing it entirely.
