### ISSUE TITLE
Remove @Beta from Utf8

### ISSUE THREAD

**Issue by robeden** [google/guava#3286]
The `Utf8` class has been around since 16.0 and would be nice to remove it from beta.
(FYI, our main need at the moment is the `encodedLength` method).

**Comment by shirishp** [comment]
@netdpb @kluever Are you looking for a PR for this and similar issues #3285 and #3284?

I can work on the PRs if nobody else is working on it.

**Comment by LianyanGu** [comment]
@shirishp Hi, I just created a PR for issue number #3285

**Comment by nuzayats** [comment]
+1, the encodedLength method is really useful and I'd like to use it from libraries. Is there any blocker for this?

**Comment by kluever** [comment]
Done --- should be mirrored out shortly.
