### ISSUE TITLE
composable annotations

### ISSUE THREAD

**Issue by xenoterracide** [google/guava#3291]
Spring allows you to write your own named annotations by allowing `ElementType.TYPE` or `ElementType.ANNOTATION_TYPE`

```
@Service
@Retention( RetentionPolicy.RUNTIME)
@Target( ElementType.TYPE )
@Inherited
public @interface EventHandler {}
```
so a class annotated with this will also be a `@Service`

what I really wanted to do though, which is not possible with guava as written.

```
@Subscribe
@AllowConcurrentEvents
@Retention( RetentionPolicy.RUNTIME)
@Target( { ElementType.METHOD, ElementType.ANNOTATION_TYPE } )
@Inherited
public @interface GlobalEventHandler {}
```
now I could write just a single annotation on my service method, and target the bus registration by looking for `@GlobalEventHandler`

I could see about writing a patch if this is an interesting feature

**Comment by netdpb** [comment]
I think I understand. Could you show examples of doing the same thing today without the proposed feature, and how much easier it would be for a user with the proposed feature?

I think we only consider adding features like this if they make users' lives significantly easier, and they do so for a significant number of cases. If it's only a little bit easier, or there are only a few cases where it'll be used, we tend not to add features even if they're interesting.

**Comment by xenoterracide** [comment]
I had to select a completely different design in order to do it without this feature, I'll see what I can do though.

**Comment by xenoterracide** [comment]
It may also be worth looking at what the vaadin4spring did to achieve a similar result 

https://github.com/peholmst/vaadin4spring/tree/master/addons/eventbus/src/main/java/org/vaadin/spring/events

**Comment by cpovirk** [comment]
Realistically, we're unlikely to add functionality to EventBus at this point.
