### ISSUE TITLE
Suggestion: ImmutableMap building convenience method

### ISSUE THREAD

**Issue by ashleyfrieze** [google/guava#3292]
Using `ImmutableMap.builder()` is a bit clunky. You need to specialise the type like this:

```java
Map<SomeKey, SomeValue> someMap =
      ImmutableMap.<SomeKey, SomeValue>builder()
         .put(key1, value1)
         .put(key2, value2)
... etc
```

It would be way easier if the type could be inferred. Allowing us to provide the first entry at the same time as creating the builder would do that:

```java
Map<SomeKey, SomeValue> someMap =
      ImmutableMap.builder(key1, value2)
         .put(key2, value2)
... etc
```

All this would take is a minor overload in the `ImmutableMap` class

E.g.

```java
  /**
   * Returns a new builder. The generated builder is equivalent to the builder created by the {@link
   * Builder} constructor. Provide the first values for adding to the map to utilise type inference
   * in place of having to specialise the type at the call site.
   * @param key initial key to add to the map
   * @param value initial value to add to the map
   */
  public static <K, V> Builder<K, V> builder(K key, V value) {
    return new Builder<>()
      .put(key, value);
  }
```

**Comment by jrtom** [comment]
I don't think I understand the problem that you say you're having.  This works:

```
ImmutableMap.Builder<String, String> builder = ImmutableMap.builder();
```

Even if it didn't, however, I don't think that your proposal would be a good idea.  There are occasionally reasons to include configuration information in the creation of a builder, but I don't think that you would ever want to have a builder invocation whose functionality overlapped one of the methods of the builder itself.

**Comment by kevinb9n** [comment]
We did work hard to try to find a way to avoid the need for these type parameters, and we considered this idea at the time. We ultimately decided that the lack of parallel structure between the first entry and other entries caused too many readability and maintainability problems. Also, it broke arbitrarily in some situations where the actual keys and values can occasionally be subtypes of the map's key/value types.
