### ISSUE TITLE
StackOverflowError caused，I need help pls

### ISSUE THREAD

**Issue by lasting0001** [google/guava#3293]
For guava-cache,How could I stop the cache removed from the cache in some condition?

SomeTimes,I need to put the cache back to guava at the RemovalListener when db saving failed,but it  will cause StackOverflowError

![tim 20181014135839](https://user-images.githubusercontent.com/10528816/46913094-5c587300-cfb9-11e8-93a2-e669c2f3c415.png)

**Comment by ronshapiro** [comment]
This appears to be a question - please use StackOverflow with the `guava` tag instead, as that is a better forum for questions.
