### ISSUE TITLE
GraphBuilder.directed() and GraphBuilder.undirected() should not be parameterized on Object

### ISSUE THREAD

**Issue by ParceledTongue** [google/guava#3299]
I feel like I must be missing something, but I can't figure out at all why these methods don't look like:

```
public static <N> GraphBuilder<N> directed() { ... }
public static <N> GraphBuilder<N> undirected() { ... }
```

The current design means that it's not possible to get a `GraphBuilder` parameterized on anything besides `Object` using these patterns until you call `nodeOrder`, which will properly infer the generic type and perform a cast. (Incidentally, it feels strange that `nodeOrder` has this generic downcasting behavior but, e.g., `allowsSelfLoops` does not.)

**Comment by jrtom** [comment]
It's a bit nonintuitive, but it's the same thing that `MultimapBuilder` and `CacheBuilder` does, and for the same reasons.

Note that `build()` also performs the cast, of course.

The methods that don't take typed parameters (e.g. `allowsSelfLoops()`) don't do any casting because there's no type information to use.

**Comment by ParceledTongue** [comment]
If you could elaborate or provide a link to what you're referring to when you say "the same reasons," I'd appreciate it. That may clear this whole thing up for me.

In the cases I'm thinking of, there is type information; it's just provided by the context, as it is when calling `build()`.

I understand why the generic type binding technically can't be put off any longer once you call `nodeOrder`, but that just seems to indicate that the binding should occur as early as possible . Otherwise `nodeOrder` is special compared to other operations, which feels pretty incidental.

```
GraphBuilder<String> builder1 = GraphBuilder.directed() // illegal
GraphBuilder<String> builder2 = GraphBuilder.directed().allowSelfLoops(true) // illegal
GraphBuilder<String> builder3 = GraphBuilder.directed().allowSelfLoops(true).nodeOrder(ElementOrder.unordered()); // legal
```

**Comment by kevinb9n** [comment]
`nodeOrder` *is* special, because it naturally restricts what type of graphs the builder will be capable of producing.  You're proposing a way to "artificially" restrict the type of graphs ahead of time, but calling `nodeOrder` would *still* be "special" because unlike other methods you may break your compile if you hand it a conflicting type.

The equivalent CacheBuilder issue (resolved WAI) is issue 738.

**Comment by kevinb9n** [comment]
Oh, I will say that CacheBuilder has the following doc, and GraphBuilder should probably have the equivalent:

```
@param <K> the most general key type this builder will be able to create caches for. This is
     normally {@code Object} unless it is constrained by using a method like {@code
     #removalListener}
 ```

**Comment by ParceledTongue** [comment]
Oh, I see now! I never imagined the type of a builder as communicating, "I can create graphs of `N` and all its subtypes," so I didn't understand why you wouldn't want this behavior. Makes sense. :)

**Comment by lowasser** [comment]
Additionally, at least for older compilers, type inference in Java tends to work better when the generics come at the end of a chain rather than the beginning.

**Comment by jrtom** [comment]
I've got an update to the docs out for review now, so it should hopefully be in the next release of Guava.

Thanks for encouraging us to improve our documentation.  :)

**Comment by ParceledTongue** [comment]
You probably thought of this, but `ValueGraphBuilder` and `NetworkBuilder` could use param docs like this too ✌️

**Comment by jrtom** [comment]
Yup, the change covers them too, but thanks for asking.  :)  
It also mentions that the types _do_ get specified (i.e., don't start out as `Object`) if you create a `*Builder` using the `from()` static method.
