### ISSUE TITLE
{Boolean,Byte,Char,Double,Float,Int,Long,Short}s.concat() may throw {NegativeArraySize,ArrayIndexOutOfBounds}Exception

### ISSUE THREAD

**Issue by ineuwirth** [google/guava#3303]
The `concat()` method in the per-type primitive utility classes throws unexpected `NegativeArraySizeException` or `ArrayIndexOutOfBoundsException` if the input arrays contain too many elements.

`NegativeArraySizeException` is being thrown if there is an overflow ending up with a negative `int`. In this case, the result array cannot be constructed with this number.

`ArrayIndexOutOfBoundsException` is being thrown if there is an overflow ending up with a non-negative `int`. In this case, the result array will be shorter than expected and `System.arraycopy()` will throw `AIOOBE`.

**Comment by ineuwirth** [comment]
Test cases to demonstrate the issue can be found in #3304.

I am happy to cover other classes and modules (android, gwt) as well if you think the test cases/provided fix are good.

**Comment by kluever** [comment]
This isn't actually a bug, right? It's just improving the API docs?

**Comment by ineuwirth** [comment]
Well, a similar issue has been fixed in code instead of documenting the behavior e.g. in #3026.
Also, in case of an overflow ending up with a positive number, we could prevent a potentially big array from being allocated for nothing.

**Comment by cpovirk** [comment]
I _think_ the PR from last year and the followup today have covered all this, but let me know if I'm missing anything.
