### ISSUE TITLE
Add Strings.nonEmpty(String)

### ISSUE THREAD

**Issue by simon04** [google/guava#3307]
Please add the following function to `Strings` in order to allow testing for non-empty strings in `Stream`s or `Optional`s:

```java
public static boolean nonEmpty(@Nullable String s) {
    return s != null && !s.isEmpty();
}
```

This follows the pattern of [`Objects.nonNull`](https://download.java.net/java/early_access/jdk11/docs/api/java.base/java/util/Objects.html#nonNull(java.lang.Object)).

**Comment by jrtom** [comment]
I believe that `Strings.isNullOrEmpty()` does what you want, although the sense is reversed: re/api/docs/com/google/common/base/Strings.html#isNullOrEmpty-java.lang.String-

**Comment by simon04** [comment]
True, semantically the proposed function is the negation of `Strings.isNullOrEmpty`, but I'd like to `.filter(Strings::nonEmpty)` (using the `::` shorthand notation).

**Comment by lowasser** [comment]
I can see the desire for a single method reference in the filter, but I'd be concerned about naming.  Guava has been pretty firm about not _conflating_ nullness and emptiness...which would mean, what, `neitherNullNorEmpty`?  A simpler possibility might be a `notEmpty` method, in which case you could do `.filter(Objects::nonNull).filter(Strings::nonEmpty)`, or the like.

**Comment by jrtom** [comment]
I can understand wanting to do that, but I think it's highly unlikely that the Guava team is going to introduce a new method whose semantics are the negation of an existing method to save people from having to do this:

```
filter(s -> !isNullOrEmpty(s))
```

I mean, method references are nifty but lambdas make this pretty painless IMO.

**Comment by perceptron8** [comment]
Duplicate of #3064?

**Comment by perceptron8** [comment]
Also note that since Java 11 there is [Predicate.not(Predicate)](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/function/Predicate.html#not(java.util.function.Predicate)), so you can negate/filter like this too:

```
filter(Objects::nonNull).filter(not(String::empty))
```
