### ISSUE TITLE
Graph: Beta api

### ISSUE THREAD

**Issue by vijaygopal** [google/guava#3316]
Hi Team,

Will Google Graphs be supported in the future or will this be removed from Guava?

Regards
Vijay Gopal

**Comment by jrtom** [comment]
As the person with primary responsibility for this package, I certainly intend to continue supporting it, and I hope to continue to attract people (inside and outside Google) to both maintain and extend it.  Many projects inside Google make use of it and I think that it would be problematic to start using something else instead.  In addition, at least one other project I run ([JUNG](https://github.com/jrtom/jung)) is putting out a new version that depends on it, so I have a personal interest in keeping it going.  :)

If you're wondering when it's going to come out of beta, the answer is that we don't know yet.  There are aspects of the basic APIs that are still being modified, and we don't want to commit right now to freezing them.

**Comment by vijaygopal** [comment]
Thanks for the clarification Joshua. I hope Guava continues to support the Graph API as I don't see any other implementation of the Graph API which is simpler to use and has a good documentation.

**Comment by jrtom** [comment]
We're glad that it's working out for you.  :)
