### ISSUE TITLE
OSGI: Upgrading from 24 to 27.0.1 fails with missing requirement [com.google.guava/27.0.1.jre] osgi.wiring.package; filter:="(&(osgi.wiring.package=com.google.common.util.concurrent.internal)(version>=1.0.0)(!(version>=2.0.0)))"]

### ISSUE THREAD

**Issue by lichtin** [google/guava#3328]
OSGI: 
Upgrading from 24 to 27.0.1 fails with 

missing requirement [com.google.guava/27.0.1.jre] osgi.wiring.package; filter:="(&(osgi.wiring.package=com.google.common.util.concurrent.internal)(version>=1.0.0)(!(version>=2.0.0)))"]

**Comment by cgdecker** [comment]
I don't know much of anything about OSGi, but do you have `com.google.guava:failureaccess` on your classpath? Guava 27.0.1 depends on `failureaccess` 1.0.1, which has OSGi metadata that exports package `com.google.common.util.concurrent.internal` version 1.0.1.

**Comment by talios** [comment]
Oh look - here's that binary incompatible change I was talking about. As @cgdecker says you'll need to also deploy `com.google.guava:failureaccess` to your OSGi container can resolve the new public `internal` API requirement ( it feels awkward having `internal` as a public contract to me, but that's what we have now.)

Hope this works for you @lichtin.

**Comment by lichtin** [comment]
Ah yes, thanks both, I totally missed that new dependency.
