### ISSUE TITLE
guava-beta-checker fails to detect @Beta APIs in method references

### ISSUE THREAD

**Issue by c2nes** [google/guava#3335]
`ImmutableMap.copyOf(Iterable<? extends Map.Entry<? extends K,? extends V>> entries)` is marked `@Beta`, but the following snippet gets through the BetaApi check without an error,

```java
Function<Iterable<Entry<?, ?>>, ?> f = ImmutableMap::copyOf;
f.apply(Collections.emptyList());
```

whereas,

```java
ImmutableMap.copyOf(Collections.emptyList());
```

gives the expected `@Beta APIs should not be used in library code as they are subject to change`

**Comment by cgdecker** [comment]
This has been fixed, but we need to make a release with the fix in it.
