### ISSUE TITLE
Java8 JaCoCo Coverage missing “new TypeToken” code inside anonymous class

### ISSUE THREAD

**Issue by abarik1981** [google/guava#3336]
So, I wrote a small piece of code to get class object of a generic using Java Reflection and Guava `TypeToken`, but for some reason JaCoCo coverlay 
is missing lines inside the `TypeToken`, specifcally here: `      final TypeToken<PHASE> typeTokenPhase = new TypeToken<PHASE (getClass()) {};`

In the report, I see `0%` coverage in section: `new TypeToken() {...}`

    import java.lang.reflect.Type;
    import com.google.common.reflect.TypeToken;

    public class MyClass<PHASE> {

        public Class<PHASE> getPhaseClass() {
          final TypeToken<PHASE> typeTokenPhase = new TypeToken<PHASE     (getClass()) {};
          final Type typePhase = typeTokenPhase.getType();
          Assert.assertEquals(true, typePhase instanceof Class);
          return (Class<PHASE>) typePhase;
        }
    }

Am I missing anything?

Using GoogleGuava-0.23

**Comment by netdpb** [comment]
This seems like a JaCoCo issue, and not a Guava issue. Please ask on forums for JaCoCo, or reopen and help me to understand why this is Guava-specific.
