### ISSUE TITLE
AbstractFuture.setFuture(...) return value semantics

### ISSUE THREAD

**Issue by njhill** [google/guava#3348]
Apologies if I'm mistaken about this. It's kind of subtle and might be inconsequential, but I'm wondering whether it's correct to return `false` in the case that the receiving future is already cancelled and the cancellation gets successfully propagated to the provided future.

I think of `false` as indicating the action "failed" and had no effect, but in this case it did have an effect (essentially successfully "binding" the fate of the two futures as is the purpose of the method), and could be considered a success.

Another way to look at it is that concurrency-wise it's essentially the same as the case where the recieving future isn't initially cancelled so the `setFuture` "succeeds", but is cancelled immediately after by some other thread, prior to that `setFuture` invocation returning `true`. The difference between the two cases just depends on the winner of that cancellation race, and the outcome and final state in each case is identical, but in one it returns `false` and the other `true`.

**Comment by cpovirk** [comment]
Sorry, OOO last quarter and catching up now.

This is definitely weird, and I think we talked about it at the time, even considering returning an `enum` with multiple states to be clear about what happened. (Another weird thing: Once you call `setFuture` methods like `set` will return `false`, which used to mean "The `Future` is done," but once we added `setFuture`, that was no longer the case). We looked around some and found that basically no one cared about the return values of the methods, and we couldn't do the right thing without changing the return type of methods like `set`, too, so we decided to live with it.

So hopefully it ends up being inconsequential, as you've said.

**Comment by njhill** [comment]
Thanks @cpovirk and I hope you had a good break! While acknowledging the discussion may be academic, I do think this case is slightly different. It's true that `set` returning `false` used to correlate with the future being done, but a nicer interpretation of the meaning i.m.o, which still holds, is that `true` corresponds to whether any state was changed, analogous to methods like `Collection.add/remove`. 

When viewed in that light there's no need for different return types and the behaviour is still completely correct/consistent across all of `set`, `setException`, `setFuture`, _apart from_ the edge case described here.

**Comment by cpovirk** [comment]
Fair enough -- we could do the right thing in this case even without touching the `set` case. I do suspect that we'd need an enum to offer everything that we want (since people might genuinely want to know if `setFuture` "worked" in some cases, even with the possibility of a race), and any change we make now might break something, so we'll probably just live with the wart.

**Comment by cpovirk** [comment]
I raised this again and found another person who regrets it, but we regret more than `setFuture` is still `@Beta` after all these years, so we're removing `@Beta` and living with the imperfection.
