### ISSUE TITLE
CharMatcher.countIn should account for null sequence

### ISSUE THREAD

**Issue by devikasondhi** [google/guava#3352]
The documentation for the ```CharMatcher.countIn``` method does not state the expected behaviour if the input sequence is ```null```. The user may expect the method to return 0 for such a case but the implementation throws NullPointerException (which could also be considered as a valid output). This ambiguity should be explicitly clarified in the documentation or else handled well in the code.

**Comment by perceptron8** [comment]
> "Guava's utilities are designed to fail fast in the presence of null rather than allow nulls to be used, so long as there is a null-friendly workaround available" ([wiki/UsingAndAvoidingNullExplained](https://github.com/google/guava/wiki/UsingAndAvoidingNullExplained))

I would say that NPE is expected by default.

As for workaround, you can use `Strings.nullToEmpty` to normalize your string before passing it to `CharMatcher.countIn`.
