### ISSUE TITLE
MultiSet not keeping duplicate elements(defined by comparator)

### ISSUE THREAD

**Issue by ShivKJ** [google/guava#3354]
`
import java.util.Comparator;

import com.google.common.collect.Multiset;
import com.google.common.collect.TreeMultiset;

class Element {
    String id;
    int    weight;

    public Element(String id, int weight) {
        this.id = id;
        this.weight = weight;
    }

    @Override
    public String toString() {
        return "[id=" + id + ", weight=" + weight + "]";
    }

    public int getW() {
        return weight;
    }

    public String getId() {
        return id;
    }

    public static void main(String[] args) {
        Multiset<Element> multiset = TreeMultiset.create(Comparator.comparing(Element::getId));
        multiset.add(new Element("a", 0));
        multiset.add(new Element("a", 1));

        System.out.println(multiset);

        for (Element a : multiset)
            System.out.println(a);

    }
}
`

We find that element with weight 1 is lost.

**Comment by ShivKJ** [comment]
"so the multiset makes a memory optimization: it only keeps the first element in-memory ...."
I actually wanted to a Collection which keeps element in sorted order and allows duplicate elements.
I find that this functionality is not provided by MultiSet Interface.
thanks @jbduncan.

**Comment by jbduncan** [comment]
Well, actually, I believe that `TreeMultiset` can work in this situation if you swap out the comparator for `Comparator.comparing(Element::getId).the comparing(Element::getWeight)` (or if `Element` were to implement `Comparable<Element>`).

Multisets _do_ allow duplicates, but the existing comparator is tricking it into thinking that `Element` only has one field: `id`, so if my suggested comparator above were to be used instead, then things should work fine. :)

But if that's not feasible, then yeah you'll need to find an alternative data structure. (Perhaps an auto-sorting list? Apache Commons Collections might have an implementation for that.)
