### ISSUE TITLE
Consider adding an implies method to Booleans

### ISSUE THREAD

**Issue by oliviercailloux** [google/guava#3357]
Say I want to check whether `!exists` implies `!hasContent`, these being two `boolean` variables.

Currently I must call: `Preconditions.checkState(exists || !hasContent)`, which I find very difficult to understand when reading it after the fact. I feel the urge to add a comment: `/** Checks that not exists implies not hasContent. **/`

In order to make my code auto-documented, I prefer to add a one-line method in a utility class: `public static boolean implies(boolean a, boolean b)`, that returns `!a || b`.

Then the check above reads `Preconditions.checkState(implies(!exists, !hasContent))`. A much clearer statement, I would say.

Would you please consider adding such a method where appropriate, perhaps in `Booleans`?

**Comment by ChristianCiach** [comment]
I don't really like this. Here are my thoughts about it:

* I think your original boolean expression is expressive enough. Actually, I think your added comment just repeats the boolean expression, leading to confusion, if anything. I think a better comment would be something like `If the file doesn't exist, it cannot have content.`.
* Lucky, my proposed comment can almost be directly expressed as Java :) If you think `exists || !hasContent` is not expressive enough, I would write it this way:

   ```
   if(!exists) {
       Preconditions.checkState(!hasContent, "Non-existing files cannot have content");
   }
   ```
* The method `implies` is an odd name. If you see a method with that name, you would expect the method to answer a question like "Does a imply b?". The method cannot answer that. In your proposed case `implies(a, b)` would be a statement (and not a question) that can only be applied to this specific use case. (Sorry, english is not my native language and I hava a hard time expressing my thoughts here). Anyway, I think I would have a hard time writing JavaDoc for that method. 
* `Booleans` would be a bad class to put such a method. If anything, I would see this as another method on the `Preconditions` class. But again, I cannot think of a suitable method name and specification that answers more questions than it would rise.

**Comment by ronshapiro** [comment]
This is a great example of a method that's great for project-specific code, or if you have many projects that want it, in it's own library that's shared between them. 

It doesn't have much value besides a personal readability preference. There's little value in predefining this in a place like Guava.

**Comment by oliviercailloux** [comment]
For the record, I think that the argument about “implies” being not the right name is incorrect (from a logical point of view). But because of the subjectivity in what’s “clear” or “readable”, as indicated in the other arguments, it seems other voices are needed to counter the “personal readability” argument, thus it seems to be a lost cause for now and I don’t want to argue pointlessly.

In case others reading this want to side with me, I am available to defend the logic behind my proposal.
