### ISSUE TITLE
Remove @Beta from EventBus

### ISSUE THREAD

**Issue by AlekssGu** [google/guava#3360]
EventBus has been marked as Beta for 8 years already (since Jul 25, 2011).

**Comment by nglorioso** [comment]
Thanks for the issue opening! We're looking through our `@Beta` API's and will keep this in mind.

**Comment by philipwhiuk** [comment]
Did the review go anywhere @nglorioso?

**Comment by SwingGuy1024** [comment]
Why is EventBus still @Beta? I keep getting inspection warnings from my IDE whenever I use it. It's a pretty old and stable class. Isn't it time to remove @Beta?

**Comment by gm100861** [comment]
Please remove it, please, please , pleassssssssssssssssssssssssssssssse

**Comment by AmerAlsabbagh** [comment]
Yes please remove it!

**Comment by jerryoung** [comment]
EventBus is unstable? It make me puzzled. Anyone can talk me why?

**Comment by nanachimi** [comment]
Yes please!

**Comment by zhuhaoman** [comment]
Now is 2022, @Beta is still there...
