### ISSUE TITLE
guava Java 11 Compatibility

### ISSUE THREAD

**Issue by marioradev** [google/guava#3361]
Hi experts,

Are you planning to release a guava version which is compatible with Java 11? If yes, when do you expect this will happen?
The jdeps report is complaining:
guava.jar -> jdk.unsupported com.google.common.primitives.UnsignedBytes$LexicographicalComparatorHolder$UnsafeComparator -> sun.misc.Unsafe JDK internal API (jdk.unsupported) com.google.common.primitives.UnsignedBytes$LexicographicalComparatorHolder$UnsafeComparator$1 -> sun.misc.Unsafe JDK internal API (jdk.unsupported) JDK Internal API Suggested Replacement ---------------- --------------------- sun.misc.Unsafe See http://openjdk.java.net/jeps/260

Thanks in advance for the reply.

Regards,
Mario

**Comment by ajrepp** [comment]
Might this be a duplicate of #3272, #3241, or #3288?

**Comment by netdpb** [comment]
Yes, a dupe of #3272.
