### ISSUE TITLE
add wiki link from graph documentation to JGraphT adapter

### ISSUE THREAD

**Issue by jsichi** [google/guava#3365]
As part of the JGraphT project, we've developed adapters which allow a Guava Graph to be viewed as a JGraphT graph, making it possible to run JGraphT algorithms against it:

https://jgrapht.org/guide/GuavaAdapter

Developers who prefer using Guava Graph for its user-friendliness (or other reasons) may want to take advantage of the rich library of algorithms provided by JGraphT; the adapters make this easy.

Currently, the Guava Graph wiki has a section which mentions JGraphT:

https://github.com/google/guava/wiki/GraphsExplained#why-should-i-use-it-instead-of-something-else

So it might make sense to add the adapter link there.

**Comment by nglorioso** [comment]
Added in https://github.com/google/guava/wiki/GraphsExplained/6155ff307639cdd998fd76f2de27e744dd022026

**Comment by jsichi** [comment]
Thanks!
