### ISSUE TITLE
Add Support For Calendar Instance in MoreObjects#toStringHelper()

### ISSUE THREAD

**Issue by Sawon90** [google/guava#3367]
Currently there is not handling for ```java.util.Calendar``` in ```MoreObjects#toStringHelper()```. So when I try to add ```Calendar``` instance in ```toStringHelper()```, it print default String return from Calendar instance, which is very bad. For example, if I try the following-
```
public String toString() {
    return MoreObjects.toStringHelper(this)
            .add("name", name)
            .add("beginDate", beginDate)
            .add("endDate", endDate)
            .toString();
```
It return something like below-
```
SearchRequest{name=test, beginDate=java.util.GregorianCalendar[time=1548050448000,areFieldsSet=true,areAllFieldsSet=true,lenient=true,zone=sun.util.calendar.ZoneInfo[id="Asia/Dhaka",offset=21600000,dstSavings=0,useDaylight=false,transitions=8,lastRule=null],firstDayOfWeek=1,minimalDaysInFirstWeek=1,ERA=1,YEAR=2019,MONTH=0,WEEK_OF_YEAR=4,WEEK_OF_MONTH=4,DAY_OF_MONTH=21,DAY_OF_YEAR=21,DAY_OF_WEEK=2,DAY_OF_WEEK_IN_MONTH=3,AM_PM=1,HOUR=0,HOUR_OF_DAY=12,MINUTE=0,SECOND=48,MILLISECOND=0,ZONE_OFFSET=21600000,DST_OFFSET=0], endDate=null}
```
Which is not readable at all. It will be good to print some user friendly formatted Calendar instance, or there should be some way to configure ```Calendar``` or any type.

**Comment by kluever** [comment]
Sorry, we don't special case any types inside of `ToStringHelper`, but instead rely on their `toString()` implementation.

I'd suggest creating a wrapper around your `Calendar` instance which has a `toString()` format that you prefer (and then passing that to `ToStringHelper`.
