### ISSUE TITLE
What happens if you don't set any refreshAfterWrite for loadingCache

### ISSUE THREAD

**Issue by MrXavier** [google/guava#3369]
Debugging this situation I see refreshAfterWrite is set to -1. I suppose that the cache will never refresh.
I tried to find this information in the documentation and javadoc but couldn't find it anywhere. It should be good to have this in the docs.

**Comment by cgdecker** [comment]
It's documented that if no options are set, a cache created by `CacheBuilder` will never do any kind of eviction. This applies to refresh as well, as it is a form of eviction.

It's possible we could make this a little clearer, but the Javadoc is already pretty thorough, I think.
