### ISSUE TITLE
Is jsr305 end-of-life?

### ISSUE THREAD

**Issue by moaxcp** [google/guava#3375]
Out of security concerns the latest version of guava is being denied for a project I'm working on. This is due to https://jcp.org/en/jsr/detail?id=305 being marked as dormant. The artifact being denied is:
```
<dependency>
    <groupId>com.google.code.findbugs</groupId>
    <artifactId>jsr305</artifactId>
    <version>3.0.2</version>
</dependency>
```
#2960 was also brought up as a concern but I think that if I can show that the above artifact is still supported I can get guava approved.  Is this artifact EOL? Is it being maintained by google?

**Comment by kevinb9n** [comment]
It is indeed in some process of being phased out. I don't know if you can point out to your people that it is very difficult for an annotation to cause a security problem....

**Comment by moaxcp** [comment]
No not really. Why think about the code when there is a "rule" to follow and the jcp page. Thanks anyway...
