### ISSUE TITLE
CharMatcher deprecations are uncalled for

### ISSUE THREAD

**Issue by mirraj2** [google/guava#3391]
I've been using CharMatcher.javaDigit() for a long time and it has never given me any issues.  I think it's a step in the wrong direction to force people to say CharMatcher.inRange('0', '9') because it is making an extremely common use-case more difficult.

**Comment by Stephan202** [comment]
Just a thought: perhaps it makes sense to introduce `CharMatcher.asciiDigit()`?

**Comment by mirraj2** [comment]
@Stephan202 Good idea.  I've created a pull request here:  https://github.com/google/guava/pull/3392

**Comment by perceptron8** [comment]
@mirraj2 What about `CharMatcher.asciiLetter()` and `CharMatcher.asciiLetterOrDigit()`? Note deprecation of `CharMatcher.javaLetter()` and `CharMatcher.javaLetterOrDigit()`).

**Comment by netdpb** [comment]
We're not going to remove `javaDigit()` or the other deprecated methods. They're still there for you to use. They're deprecated for the reasons listed in the documentation: they're not Unicode safe and don't really do what they sound like they do.
