### ISSUE TITLE
Concurrent (atomic) access to ByteBuffers

### ISSUE THREAD

**Issue by SoniEx2** [google/guava#3395]
I'd like to see utilities/wrappers for getting good concurrent (atomic) access to ByteBuffers. I've been reading [these posts](http://psy-lob-saw.blogspot.com/2013/07/atomicity-of-unaligned-memory-access-in.html) and they're a little bit old but I don't see any reason why they aren't still accurate - especially on older CPUs.

ByteBuffers are very interesting because I believe they can provide the experience and performance of manual memory management in Java. but some way to access concurrency primitives would be necessary to make it practical. Additionally, Java's JIT might be able to runtime-optimize some algorithms based on constant inputs so it'd be faster than the native equivalents, and it'd also be faster than going through the JNI. This is very use-case-specific tho so not something that can be relied on.

But yeah. I just want to port some high-performance libraries to Java and I don't feel like trying to fine-tune Java implementations when I can just convert the original.

**Comment by lowasser** [comment]
Can you use Java 9?  Java 9 provides some VarHandles that cover this issue
about as well as you can.  I don't think there's a universal way to view an
*arbitrary* ByteBuffer as a byte sequence where you can modify individual
bytes atomically, but you can use MethodHandles.byteBufferViewVarHandle
<https://docs.oracle.com/javase/9/docs/api/java/lang/invoke/MethodHandles.html#byteBufferViewVarHandle-java.lang.Class-java.nio.ByteOrder->
to
access four or eight byte chunks, or use arrayElementVarHandle
<https://docs.oracle.com/javase/9/docs/api/java/lang/invoke/MethodHandles.html#arrayElementVarHandle-java.lang.Class->
to interact with raw byte arrays.  You can also explicitly query
<https://docs.oracle.com/javase/9/docs/api/java/nio/ByteBuffer.html#alignmentOffset-int-int->
the alignment of a ByteBuffer.

Louis Wasserman
wasserman.louis@gmail.com

**Comment by SoniEx2** [comment]
hm. how well does the JIT handle those? I thought reflection was slow?

I don't believe I can use Java 9 APIs, however. currently stuck on java 8 :/

**Comment by lowasser** [comment]
They're not reflective; the JIT is specifically designed to handle
VarHandles and MethodHandles effectively.  A constant VarHandle (you'd only
need one) should get JITted away entirely.

Louis Wasserman
wasserman.louis@gmail.com

**Comment by cgdecker** [comment]
It seems like `VarHandle` likely provides the access that's needed here, and given that, I don't think we're likely to work on an API for providing similar functionality for Java 8.
