### ISSUE TITLE
Dead link in Javadoc for HashFunction

### ISSUE THREAD

**Issue by rdicroce** [google/guava#3396]
The Javadoc for HashFunction says:

> We have published microbenchmark results for many common hash functions.

And "microbenchmark results" is a link... to the anchor noWeHaventYet. I'd suggest that either such benchmarks should be published and linked, or the suggestion that they have should be removed from the Javadoc.

For fun, I went back through the history of that file, and this link has been there since the hash package was open-sourced in Guava 11, some 7 years ago.

**Comment by kevinb9n** [comment]
Guilty. :-)  It's being removed.
