### ISSUE TITLE
RateLimiter works beyond my expection

### ISSUE THREAD

**Issue by User979269852** [google/guava#3397]
I try to use Ratelimiter to limit the access trafic，I set RateLimiter.create(2000);but unfortunately when I use wrk to test whether the flow control works, the tps is up to 2700.can some one help to release my confusion，thank you very much。

**Comment by nglorioso** [comment]
Hi!

Unfortunately, it's hard to specifically help here without some example. Can you describe *how* you're testing RateLimiter to come up with 2700 units per second when you expected the rate limiter to grant 2000 units per second?

Note that RateLimiter's behavior will allow a 'large' request that would exceed the units per second at the expense of future requests (https://google.github.io/guava/releases/23.0/api/docs/com/google/common/util/concurrent/RateLimiter.html)

It may also help to look at some of the unit tests for RateLimiter:  https://github.com/google/guava/blob/5f3507252d43c0e9c4e7f16dfddb08c387435eb1/guava-tests/test/com/google/common/util/concurrent/RateLimiterTest.java#L451

**Comment by User979269852** [comment]
my server runs on containers and my test like this " ./wrk  -t 4 -c 50  -d 60 -T 30s --latency --script=get.lua ${request_url}".Thanks you for your ansrwer and the information you supplied

**Comment by User979269852** [comment]
> Hi!
> 
> Unfortunately, it's hard to specifically help here without some example. Can you describe _how_ you're testing RateLimiter to come up with 2700 units per second when you expected the rate limiter to grant 2000 units per second?
> 
> Note that RateLimiter's behavior will allow a 'large' request that would exceed the units per second at the expense of future requests (https://google.github.io/guava/releases/23.0/api/docs/com/google/common/util/concurrent/RateLimiter.html)
> 
> It may also help to look at some of the unit tests for RateLimiter:
> 
> [guava/guava-tests/test/com/google/common/util/concurrent/RateLimiterTest.java](https://github.com/google/guava/blob/5f3507252d43c0e9c4e7f16dfddb08c387435eb1/guava-tests/test/com/google/common/util/concurrent/RateLimiterTest.java#L451)
> 
> Line 451 in [5f35072](/google/guava/commit/5f3507252d43c0e9c4e7f16dfddb08c387435eb1)
> 
>  public void testWeNeverGetABurstMoreThanOneSec() {

my server runs on containers and my test like this " ./wrk -t 4 -c 50 -d 60 -T 30s --latency --script=get.lua ${request_url}".Thanks you for your ansrwer and the information you supplied

**Comment by User979269852** [comment]
I am so sorry, My server has two instance,so in that environment the tps should be 1350 per instance,whithin the setting value 2000.
