### ISSUE TITLE
Invalid OSGi headers in v27.1-jre

### ISSUE THREAD

**Issue by hamid-nazari** [google/guava#3400]
The OSGi headers (`Import-Packages` and `uses` directive of `Export-Packages`) in MANIFEST.MF are referring to a missing package `com.google.common.util.concurrent.internal`.

I've managed to fix it by manually editing the manifest, but since the package is actually removed, the BND file must be fixed to account for this change.

**Comment by talios** [comment]
On 11 Mar 2019, at 0:41, hamid-nazari wrote:

> The OSGi headers (`Import-Packages` and `uses` directives of `Export-Packages`) in MANIFEST.MF are referring to a missing package `com.google.common.util.concurrent.internal`.

That's the code that's provided (unfortunately) by the new `failureaccess` dependency of Guava. There's whole a thread on the topic you can follow....

Mark


---
"The ease with which a change can be implemented has no relevance at all to whether it is the right change for the (Java) Platform for all time." &mdash; Mark Reinhold.

Mark Derricutt
http://www.theoryinpractice.net
http://www.chaliceofblood.net
http://plus.google.com/+MarkDerricutt
http://twitter.com/talios
http://facebook.com/mderricutt

**Comment by cgdecker** [comment]
I believe it should be correct given the fact that the package is in a dependency of Guava, but let me know if you think there's still something wrong about how it's specified.
