### ISSUE TITLE
MutableClassToInstanceMap returns issues 

### ISSUE THREAD

**Issue by ThomasKoreman** [google/guava#3409]
I recently cloned google/guava to work on stuff but while importing it to my IDE (Eclipse) it returned a redline under the function: ``cast(entry.getKey(), entry.getValue());`` this is in the method: ``public void putAll(Map<? extends Class<? extends B>, ? extends B> map) {``. Is this just a compiling fault of me or does this methods needs to be changed or created according to my IDE's  *Quick Fix*?

**Comment by ronshapiro** [comment]
This appears to be a question - please use StackOverflow instead, as that is a better forum for questions.
