### ISSUE TITLE
Splitter#splitToStream

### ISSUE THREAD

**Issue by trejkaz** [google/guava#3411]
Java lets me do this:

    Pattern.compile(" ").splitAsStream().map(...).collect(...);

I don't know whether the way this splits has the same questionable behaviour as `String.split` or not, but we use `Splitter` everywhere else anyway (and it's annoying to have to have two static fields which represent the same split rule in two different ways), so it would be nice if we could do this:

    Splitter.on(" ").splitToStream().map(...).collect(...);

**Comment by ronshapiro** [comment]
We have reviewed an identical API internally and I believe we are just waiting for the implementation to land. /cc @elharo or @kevinb9n

**Comment by cgdecker** [comment]
Added in 5a8f19bd3556012ed9e65cd4268a85ddde95733f and will be in the next release as `@Beta`.
