### ISSUE TITLE
Remove @Beta from MediaType

### ISSUE THREAD

**Issue by cpovirk** [google/guava#3414]
Possible concerns:

- MediaType isn't lenient enough for real-world media types (#1726).
- It's still arguably kind of sad that "withParameter(s)" deletes things.
- Do we have any hope that this would ever be suitable for use on Android? (And do enough people use/want it there that we'd bother?) We would at least need to convert the constants to static methods, but even then, we'd be pulling in a lot of code through ImmutableListMultimap, Multimaps.transformValues, and perhaps other APIs we use. (We could probably avoid transformValues if that's significant, but ImmutableListMultimap is baked deep in, and justifiably so.)
- We have an internal spreadsheet called "Media Type Audit." I think it mostly covers features that we could add (without changing any existing API), but we could check.

**Comment by cpovirk** [comment]
It looks like we also had extremely mild reservations about the name `create` for a method that doesn't always create a new instance. We probably wouldn't bother to fix that. But I guess if we cared enough to change from static fields to static methods, maybe we'd do that while we're at it. (But we probably won't do that, either.)

**Comment by thinkerou** [comment]
any update? thanks!
