### ISSUE TITLE
Remove @Beta from Resources.getResource

### ISSUE THREAD

**Issue by cpovirk** [google/guava#3415]
Possible concerns:

- There's a TODO here, but I'm not sure if we care enough to actually change the API \[edit: see internal bug 147880516\]:
https://github.com/google/guava/blob/be92294be598b9b6ff0bd1cae3335759dafcb534/guava/src/com/google/common/io/Resources.java#L188-L189

- I've always felt weird about how reading a resource is a 2-step process (string -> URL -> ByteSource/etc.), but I don't know if that's worth caring about, either.

- I've never understood ClassLoaders, and for all I know, this method might be an attractive nuisance in environments where ClassLoaders really matter. But I don't know if we care enough to ask intelligent people

**Comment by skingsland** [comment]
When you say remove it from "Resources.getResource", you're _actually_ talking about removing `@Beta` from the [class itself](https://github.com/google/guava/blob/master/guava/src/com/google/common/io/Resources.java#L45), which is not specific to the `getResource()` method, correct?

**Comment by kluever** [comment]
This happened already back in Jan 2022. Closing.
