### ISSUE TITLE
Remove @Beta from common.graph

### ISSUE THREAD

**Issue by cpovirk** [google/guava#3421]
I have no idea how close we are to this; I just know that `MutableGraph.putEdge` in particular has a lot of callers inside Google.

**Comment by jrtom** [comment]
I don't think we're ready for that yet.  There are some definitional things that I want to get sorted out first.  But thanks for filing the issue.  :)

**Comment by kluever** [comment]
Given we still have pending `common.graph` API review topics, I'd say we are a LONG way away from de-@Beta'ing, so I'm going to close this for now.

**Comment by davidhan-stripe** [comment]
Hi! Just checking in almost three years later. How are we feeling about retaining the beta tag?

**Comment by oliviercailloux** [comment]
Still a LONG way away from de-beta'ing?
