### ISSUE TITLE
Remove @Beta from Ints.tryParse and Longs.tryParse

### ISSUE THREAD

**Issue by cpovirk** [google/guava#3422]
- We would have to wait a while to switch it to OptionalInt.... But we could add differently named "overloads" now to try to start shifting users that way....
- Accept CharSequence? https://github.com/google/guava/issues/2549
- Any regrets over the overload "Long.tryParse(foo, 10)," where "10" might look like a default value rather than a radix?

**Comment by kluever** [comment]
This is now fixed.
