### ISSUE TITLE
Remove @Beta from Futures.getChecked (or deprecate and remove)

### ISSUE THREAD

**Issue by cpovirk** [google/guava#3424]
I admit that I included this method in part because I felt bad having _only_ `Futures.getUnchecked`, but I feel a little sad about it, especially its use of reflection, which is Android/Proguard-hostile. That said, would we care enough to delete it?

(One crazy possibility is to supply a way to codegen compile-time equivalents to the method.)

**Comment by claudivanmoreira** [comment]
Hello @cpovirk , is anyone solving this issue or can I get her to make the adjustment?

**Comment by MorrisLaw** [comment]
@ddunig2 check this one out

**Comment by kluever** [comment]
This is now fixed.
