### ISSUE TITLE
Remove @Beta from FluentIterable.of

### ISSUE THREAD

**Issue by cpovirk** [google/guava#3425]
I'm not sure there are any blockers here other than concerns over whether to commit to more `FluentIterable` methods now that we'd prefer users to use `Stream`.

**Comment by kluever** [comment]
This becomes a bit more complicated because we may want to discourage `FluentIterable` in favor of streams.

**Comment by kevinb9n** [comment]
(We *do* already lightly discourage it vs. Stream, in its javadoc.)

**Comment by kluever** [comment]
Well, my point is that we probably don't want to de-@Beta stuff in `FluentIterable` as this point...

**Comment by kluever** [comment]
Apologies for the inexcusably long delay here. This is now fixed.
