### ISSUE TITLE
Remove @Beta from FluentIterable.from(E[])

### ISSUE THREAD

**Issue by cpovirk** [google/guava#3426]
We already did this for `from(Iterable)`.

As noted in #3425, we might have general reservations about committing to more `FluentIterable` methods now that `Stream` exists.

Aside from that, the only reservations I know of are:

- Arguably "from" was the wrong name for this, since it reflects changes to the backing array. (But this is equally true of the `Iterable` overload.) We might have preferred "for" (though that's a keyword, so we'd have to pick a longer name...).
- I think that it might not actually be truly 100% unmodifiable, since the returned iterator might be able to be cast to `ListIterator`, on which users could call `set`.

**Comment by kluever** [comment]
Apologies for the inexcusably long delay here. This is now fixed.
