### ISSUE TITLE
Please return the removed value in LoadingCache.invalidate(key)

### ISSUE THREAD

**Issue by dungba88** [google/guava#3430]
Hi

I have an use case where I need to get the value of the removed key on invalidate(). I have stored a Netty direct ByteBuf inside the cache, and it needs to be released so the memory can be returned to the pool. Here is an example

```
var buf = cache.get(key);
if (buf != null) {
    buf.release();
}
cache.invalidate(key);
```

But there might be a race condition, causing the buf not released (e.g when it's created after the call to `get()` but before the call to `invalidate`). If it's a Map, I can use the `remove()` method and get the returned value. But the `invalidate` method of Guava returns void, so it's not possible. The expectation is like this to prevent race condition:

```
var buf = cache.invalidate(key);
if (buf != null)
    buf.release();
```

Note: I rather not used synchronized or any sort of locking, since everywhere else they are already non-blocking.

**Comment by dungba88** [comment]
After debugging some more, it seems the main problem coming from the cache eviction when the cache is full. When that happens, the cache entry is removed and the buffer didn't have any chance to be released. There should be a mechanism to notify whenever a cache entry is removed.

**Comment by ronshapiro** [comment]
I think you're looking for [`RemovalListener`](https://google.github.io/guava/releases/snapshot-jre/api/docs/com/google/common/cache/CacheBuilder.html#removalListener-com.google.common.cache.RemovalListener-)

**Comment by dungba88** [comment]
@ronshapiro thank you. I'm checking it.

**Comment by ronshapiro** [comment]
Feel free to comment if you have more info and we can always reconsider this. Closing for now as I think that's a good API for what you need.
