### ISSUE TITLE
Cleanup DoubleUtils.bigToDouble

### ISSUE THREAD

**Issue by turbanoff** [google/guava#3432]
Method `DoubleUtils.bigToDouble` can be replaced with direct `BigInteger.doubleValue` call.
[JDK-7131192](https://bugs.openjdk.java.net/browse/JDK-7131192) was fixed in JDK 8.

**Comment by Klapsa2503** [comment]
Do you think that the method `DoubleUtils.bigToDouble` should be removed or just marked as depracated?

**Comment by netdpb** [comment]
Do we know whether that fix was backported to Java 7, or is also evident in the Android SDK?

I don't think it's worth deprecating it, since it's not public. @lowasser, your thoughts?

**Comment by Klapsa2503** [comment]
@netdpb i have deleted this method completely to clean things up.

**Comment by lowasser** [comment]
I would specifically expect that we still need this method on Android.  No real objection to removing it for Java 8, other than the general desire to keep the implementations matching where possible.

**Comment by umairaziz1** [comment]
👤

**Comment by sananta** [comment]
Has this issue been taken care of? If not, I can take a look.

**Comment by umairaziz1** [comment]
☺

**Comment by kluever** [comment]
I think we'd prefer to minimize the diffs between the branches when possible.
