### ISSUE TITLE
Make extending of ContiguousSet possible

### ISSUE THREAD

**Issue by TuomasKiviaho** [google/guava#3442]
I have to place `ContiguousSet` extensions into the same package due to `package-private` restrictions of the constructor. I understand that this is a choice of a design that allows empty contiguous set to be returned from the create static method. Binary compatibility of course suffers if the constructor would be changed to `protected` but I'm not sure if that change would be necessarily backwards incompatible in a breaking manner.

* * *

Here a gist (lacking a better name for the time being) of a use case where this change would be welcomed. 

This one tries to circumvent the following restriction with a predicate by allowing partial continuity by further restricting the given range.. 

> A discrete domain always represents the entire set of values of its type; it cannot represent partial domains such as "prime integers" or "strings of length 5." So you cannot, for example, construct a DiscreteDomain to view a set of days in a range, with a JODA DateTime that includes times up to the second: because this would not contain all elements of the type.

https://gist.github.com/TuomasKiviaho/2ccfa28d26956c46fa8ec70c6c37cb97

**Comment by cpovirk** [comment]
The package-private constructor is intentional so that we can ensure that all implementations of `ContiguousSet` (which extends `ImmutableSortedSet`) are immutable. For your particular case, would you be able to operate on [`LocalDate`](https://www.joda.org/joda-time/apidocs/org/joda/time/LocalDate.html) objects instead of `DateTime` objects? We've seen some people do this successfully internally.

**Comment by nglorioso** [comment]
Hello Tuomas!

It sounds like you're trying to use a `ContiguousSet` to represent a domain of values that are not necessarily contiguous (e.g.: the set of values in domain `Y` matching predicate `P`).

If you were to use a custom `DiscreteDomain` that efficiently implemented the above predicate (and ensured that all calls to the ContiguousSet include ranges with endpoints that also matched the predicate), then maybe this might work, but `ContiguousSet` might not be the right abstraction for what you're trying to do.

Do you have an example client usage of this extension? (e.g.: sample ranges, domains, and predicates)

**Comment by nglorioso** [comment]
I'm going to close this issue for now, but if you have examples of where you'd like to use `ContiguousSet` in this way, please feel free to reopen with some example usages which can help us understand this feature request more or point you at better alternatives.

**Comment by TuomasKiviaho** [comment]
Here's one example. A discrete domain capable of distance as well as traversing backwards/forwards while implementing the `Predicate`. 

One other possibility would be to utilize https://github.com/jmrozanec/cron-utils to make even more complex predicates at the price of time taken to calculate the distance. 

``` java
private static abstract class DayOfWeekLocalDateDiscreteDomain extends DiscreteDomain<LocalDate> implements Predicate<LocalDate>
    {

        public static DayOfWeekLocalDateDiscreteDomain newInstance(
            final DayOfWeek wrapped)
        {
            if (wrapped == null)
            {
                throw new NullPointerException();
            }
            DayOfWeekLocalDateDiscreteDomain instance = new DayOfWeekLocalDateDiscreteDomain()
            {

                @Override
                protected DayOfWeek getWrapped()
                {
                    return wrapped;
                }

            };
            return instance;
        }

        public DayOfWeekLocalDateDiscreteDomain()
        {
            super();
        }

        protected abstract DayOfWeek getWrapped();

        @Override
        public long distance(LocalDate localDate1, LocalDate localDate2)
        {
            DayOfWeek wrapped = this.getWrapped();
            long days = ChronoUnit.DAYS.between(
                localDate1.with(TemporalAdjusters.nextOrSame(wrapped)),
                localDate2.with(TemporalAdjusters.previousOrSame(wrapped)));
            long distance = Math.floorDiv(days, DayOfWeek.values().length);
            return distance;
        }

        @Override
        public LocalDate next(LocalDate localDate)
        {
            DayOfWeek wrapped = this.getWrapped();
            LocalDate next = localDate.with(TemporalAdjusters.next(wrapped));
            return next;
        }

        @Override
        public LocalDate previous(LocalDate localDate)
        {
            DayOfWeek wrapped = this.getWrapped();
            LocalDate previous = localDate.with(TemporalAdjusters.previous(wrapped));
            return previous;
        }

        @Override
        public boolean test(LocalDate localDate)
        {
            DayOfWeek wrapped = this.getWrapped();
            DayOfWeek dayOfWeek = localDate.getDayOfWeek();
            return wrapped.equals(dayOfWeek);
        }

    }
```

**Comment by lowasser** [comment]
Note that the ability to make such a set would, for example, break existing code built around the currently valid assumption that a `ContiguousSet<LocalDate>` is a representation of a continuous sequence of dates without skips.

**Comment by nglorioso** [comment]
Agreeing with @lowasser here in my earlier comment:
>  but ContiguousSet might not be the right abstraction for what you're trying to do.

Tuomas, I see that you've made an implementation of a DiscreteDomain that appears to get at the idea of:
> All of the `LocalDate`s between two points that represent `MONDAY`

However, how is this thing being *used* in a client application?

Would it be more appropriate to model set of LocalDates from X to Y matching a predicate as an `Iterable<LocalDate>` based on [`AbstractSequentialIterator`](https://github.com/google/guava/wiki/CollectionHelpersExplained#abstractsequentialiterator)?

**Comment by TuomasKiviaho** [comment]
> Note that the ability to make such a set would, for example, break existing code built around the currently valid assumption that a ContiguousSet<LocalDate> is a representation of a continuous sequence of dates without skips.

What I present is `SortedSet` (navigable would have been even better). Abstract class to derive from would be the ideal solution since I don't even need to extend the `ContiguousSet`. Hence I left this issue in closed state.

**Comment by TuomasKiviaho** [comment]
> However, how is this thing being used in a client application?

I need fast way to see whether or not I'm inside the range. 

> Would it be more appropriate to model set of LocalDates from X to Y matching a predicate as an Iterable<LocalDate> based on AbstractSequentialIterator?

I need to be able do further head/tail/subsets thus `Iterable` is not enough. `Range` and `DiscreteDomain` provide me the building blocks for a `SortedSet` but I seem to be lacking a proper base class to derive it from. `ContiguousSet` obviously isn't one.
