### ISSUE TITLE
How can I get nodes by node's property

### ISSUE THREAD

**Issue by terence1984** [google/guava#3458]
Can i get nodes by providing node property?

**Comment by jrtom** [comment]
Which API are you referring to?  I'm guessing perhaps common.graph but your question does not make it clear.

If you are talking about common.graph, then it does not support retrieving nodes according to a property of the node; you would need to provide your own data structure to do that.

**Comment by jbduncan** [comment]
@terence1984 If you're indeed using one of the `common.graph` classes that @jrtom mentioned, e.g. `Graph` or `Network`, then you might find these two StackOverflow questions useful, both of which I answered:
1. https://stackoverflow.com/questions/47337142/simple-example-of-guava-valuegraph
2. https://stackoverflow.com/questions/50396569/get-a-node-by-id-with-guava-graph

I hope this helps. :)

**Comment by ronshapiro** [comment]
Let's use StackOverflow for questions like this.
