### ISSUE TITLE
ImmutableEnumSet should implement ImmutableSortedSet

### ISSUE THREAD

**Issue by Pr0methean** [google/guava#3461]
Since an `ImmutableEnumSet`'s delegate will always implement `SortedSet`, so should the `ImmutableEnumSet` itself be one. Then `ImmutableSortedSet.copyOf` would be able to return one for optimization, as `ImmutableSet.copyOf` already does.

**Comment by lowasser** [comment]
I'm not sure I follow.  EnumSet does not implement SortedSet in any version of Java I'm aware of.
