### ISSUE TITLE
j2objc-annotations version 1.3

### ISSUE THREAD

**Issue by suztomo** [google/guava#3496]
The latest j2objc-annotations is version 1.3. It's a good practice to catch up latest version. Shall we upgrade the dependency?

```
      <dependency>
        <groupId>com.google.j2objc</groupId>
        <artifactId>j2objc-annotations</artifactId>
        <version>1.1</version>
      </dependency>
```

https://search.maven.org/artifact/com.google.j2objc/j2objc-annotations/1.3/jar

**Comment by cpovirk** [comment]
This was done back in https://github.com/google/guava/commit/fa6c4bd2d095700b8883ede96da601fce131a728. We have a release coming today that will include the change.

**Comment by suztomo** [comment]
Thank you.
