### ISSUE TITLE
Slicing a ByteSource twice throws an unexpected IllegalArgumentException

### ISSUE THREAD

**Issue by Maxi17** [google/guava#3501]
Currently, trying to slice a `ByteSource` twice throws an unexpected `IllegalArgumentException` if the `ByteSource` returned after the first slice has a length smaller than the offset of the subsequent slice. For example, this code throws an `IllegalArgumentException`:

```
import com.google.common.io.ByteSource;

public class GuavaTest {
    public static void main(String[] args) {
        ByteSource.concat().slice(0, 3).slice(4, 3);
    }
}
```

That is against the documentation, where it is specified that it should return an empty `ByteSource`.

**Comment by kelloggm** [comment]
@cpovirk Should this issue be closed? It looks like it was fixed in #3830.
