### ISSUE TITLE
size limits for performance

### ISSUE THREAD

**Issue by vineela-gampa** [google/guava#3506]
Hi We are planning to cache around 17 million records in guava cache on each node. 
Is there a size limitation per each cache object and entire size of the cache that we can keep in memory. We can adjust vm's heapsize to accomodate .

Would there be any performance implication on guava bcoz of data ?

**Comment by kluever** [comment]
As long as you have enough memory, there shouldn't be a size limitation AFAIK.

That being said, you may want to consider using [Caffeine](https://github.com/ben-manes/caffeine) which is under active development instead of Guava's cache (which is mostly in maintenance mode).
