### ISSUE TITLE
Method Maps.newHashMapWithExpectedSize can allocate too much memory for size of power of two

### ISSUE THREAD

**Issue by ikocev** [google/guava#3509]
In the method `newHashMapWithExpectedSize` it's called method `capacity` to determine the size of the map where this line is being used:

`return expectedSize < 1073741824 ? (int)((float)expectedSize / 0.75F + 1.0F) : 2147483647;`

This will allocate twice the size, if the expectedSize is equal to a power of 2 because of "+1.0F". It could be a big issue for capacity of big size. Maybe check should be added for the case where the `expectedSize` is equal to a power of 2?!

**Comment by cgdecker** [comment]
The only power of 2 for which it will allocate twice the size is 1073741824, and that's just because there's a special case for which any expected size >= 1073741824 (i.e. any expected size that's more than half of `Integer.MAX_VALUE`) gets a capacity of `Integer.MAX_VALUE`. And it looks to me like in any of those cases, `HashMap` will just use a capacity of 1073741824 anyway, because AFAIK the JVM can't allocate an array of size `Integer.MAX_VALUE`.

Here's a table of all the `int` powers of 2, the capacity that the `capacity` method produces for each, and what percent of the expected size that capacity is for each. As you can see, for all but the smallest ones, the capacity is such that the expected size is about 75% of the capacity, which is appropriate for the target 0.75 load factor.

```
2  -  3  (0.6666667)
4  -  6  (0.6666667)
8  -  11  (0.72727275)
16  -  22  (0.72727275)
32  -  43  (0.74418604)
64  -  86  (0.74418604)
128  -  171  (0.748538)
256  -  342  (0.748538)
512  -  683  (0.74963397)
1024  -  1366  (0.74963397)
2048  -  2731  (0.74990845)
4096  -  5462  (0.74990845)
8192  -  10923  (0.7499771)
16384  -  21846  (0.7499771)
32768  -  43691  (0.7499943)
65536  -  87382  (0.7499943)
131072  -  174763  (0.74999857)
262144  -  349526  (0.74999857)
524288  -  699051  (0.74999964)
1048576  -  1398102  (0.74999964)
2097152  -  2796203  (0.74999994)
4194304  -  5592406  (0.74999994)
8388608  -  11184812  (0.74999994)
16777216  -  22369624  (0.74999994)
33554432  -  44739244  (0.75)
67108864  -  89478488  (0.75)
134217728  -  178956976  (0.75)
268435456  -  357913952  (0.75)
536870912  -  715827904  (0.75)
1073741824  -  2147483647  (0.5)
```

**Comment by eamonnmcmanus** [comment]
> If `expectedSize` is equal to a power of 2 multiplied by `loadFactor`, then "+ 1.0F" will allocate twice the size.

The code no longer uses the expression from the [original comment](https://github.com/google/guava/issues/3509#issue-458403709). The expression is [now](https://github.com/google/guava/blob/7a56cefdd14a3454c7b481d45182105612600f99/guava/src/com/google/common/collect/Maps.java#L304)

```java
(int) Math.ceil(expectedSize / 0.75)
```

**Comment by rishiraj88** [comment]
@xinbimingjingtai , could you please show an example for understanding the relation? [@eamonnmcmanus , I duly respect the update from you about the changed expression. I just like to learn the Maths about "+ 1.0F". ]

**Comment by xinbimingjingtai** [comment]
@rishiraj88 

`
expectedSize: 0, initialCapacity: 1, HashMap.threshold: 1
expectedSize: 1, initialCapacity: 2, HashMap.threshold: 2
expectedSize: 3, initialCapacity: 5, HashMap.threshold: 8
expectedSize: 6, initialCapacity: 9, HashMap.threshold: 16
expectedSize: 12, initialCapacity: 17, HashMap.threshold: 32
expectedSize: 24, initialCapacity: 33, HashMap.threshold: 64
expectedSize: 48, initialCapacity: 65, HashMap.threshold: 128
expectedSize: 96, initialCapacity: 129, HashMap.threshold: 256
expectedSize: 192, initialCapacity: 257, HashMap.threshold: 512
expectedSize: 384, initialCapacity: 513, HashMap.threshold: 1024
expectedSize: 768, initialCapacity: 1025, HashMap.threshold: 2048
expectedSize: 1536, initialCapacity: 2049, HashMap.threshold: 4096
expectedSize: 3072, initialCapacity: 4097, HashMap.threshold: 8192
expectedSize: 6144, initialCapacity: 8193, HashMap.threshold: 16384
expectedSize: 12288, initialCapacity: 16385, HashMap.threshold: 32768
expectedSize: 24576, initialCapacity: 32769, HashMap.threshold: 65536
expectedSize: 49152, initialCapacity: 65537, HashMap.threshold: 131072
expectedSize: 98304, initialCapacity: 131073, HashMap.threshold: 262144
expectedSize: 196608, initialCapacity: 262145, HashMap.threshold: 524288
expectedSize: 393216, initialCapacity: 524289, HashMap.threshold: 1048576
expectedSize: 786432, initialCapacity: 1048577, HashMap.threshold: 2097152
expectedSize: 1572864, initialCapacity: 2097153, HashMap.threshold: 4194304
expectedSize: 3145728, initialCapacity: 4194305, HashMap.threshold: 8388608
expectedSize: 6291456, initialCapacity: 8388609, HashMap.threshold: 16777216
expectedSize: 12582912, initialCapacity: 16777216, HashMap.threshold: 16777216
expectedSize: 25165824, initialCapacity: 33554432, HashMap.threshold: 33554432
expectedSize: 50331648, initialCapacity: 67108864, HashMap.threshold: 67108864
expectedSize: 100663296, initialCapacity: 134217728, HashMap.threshold: 134217728
expectedSize: 201326592, initialCapacity: 268435456, HashMap.threshold: 268435456
expectedSize: 402653184, initialCapacity: 536870912, HashMap.threshold: 536870912
expectedSize: 805306368, initialCapacity: 1073741824, HashMap.threshold: 1073741824

`
