### ISSUE TITLE
Memory Leak Issue

### ISSUE THREAD

**Issue by GAURAVJAYSWAL** [google/guava#3511]
JAVA 10, Guava Version => 18.0, I have analysed my application memory consumption and found memory leak over LoadingCache. 

private static LoadingCache<Integer, Map<String, String>> userSettingMap = CacheBuilder.newBuilder().expireAfterAccess(1, TimeUnit.DAYS)
			.build(new CacheLoader<>() {
				@Override
				public Map<String, String> load(Integer userId) throws Exception {
				}
			});
 
![jmx memory analyse snapshot](https://user-images.githubusercontent.com/19775539/59914351-d6d66e00-9437-11e9-8411-97aec3f235e4.png)

**Comment by nglorioso** [comment]
The cache you've configured is set to hold onto values for 1 day after their last access: `expireAfterAccess(1, TimeUnit.DAYS)` It's expected that you would have ~23k entries for a busy application. 

Is there evidence that elements are staying in the cache longer than that? I see "LEAK CANDIDATE" in your tool, but is that just because of a large array?

**Comment by cgdecker** [comment]
Yeah, it looks to to me like this is just your cache behaving as expected. Please reopen if you have evidence that there's actually a leak.

**Comment by a-omy** [comment]
Hi,

This leak report was rediscovered in production and I can consistently reproduce it. It is not a cache entries leak, but an unbounded number of `recencyQueue` items that point to exact same cache entry.

Specific workloads can cause the Guava cache's `recencyQueue` to grow faster than items on the queue are processed/drained, resulting in unbounded memory utilization.

See next code pointers and code snippet to demonstrate it.

*(all links within recent commit [`58e30d60` on github](https://github.com/google/guava/commit/58e30d60ac49d5726031da338bf2e13afd553798) from Feb 27 of 2024 which suggests that issue isn’t resolved yet)*

> Call chain for `#get`:
>
> -   [`LoadingCache#get` implementation in `LocalLoadingCache`](https://github.com/google/guava/blob/58e30d60ac49d5726031da338bf2e13afd553798/guava/src/com/google/common/cache/LocalCache.java#L5022-L5025)
> -   which forwards to [`LocalCache#getOrLoad`](https://github.com/google/guava/blob/58e30d60ac49d5726031da338bf2e13afd553798/guava/src/com/google/common/cache/LocalCache.java#L4041-L4043)
> -   which eventually forwards to [`LocalCache.Segment#get`](https://github.com/google/guava/blob/58e30d60ac49d5726031da338bf2e13afd553798/guava/src/com/google/common/cache/LocalCache.java#L2058-L2069)
> -   which first calls [`Segment#getLiveValue`](https://github.com/google/guava/blob/58e30d60ac49d5726031da338bf2e13afd553798/guava/src/com/google/common/cache/LocalCache.java#L2743) that checks if we've hit expired entry to drain expiring queues (`writeQueue`, `accessQueue`)
> -   then it calls [`Segment#recordRead`](https://github.com/google/guava/blob/58e30d60ac49d5726031da338bf2e13afd553798/guava/src/com/google/common/cache/LocalCache.java#L2547-L2552) that only adds current entry to the queue without removing identical records and without lock.
> -   then it calls `#postReadCleanup` that may start draining `recencyQueue` in only one thread.
>
> And we only drain that queue in [`Segment#drainRecencyQueue`](https://github.com/google/guava/blob/58e30d60ac49d5726031da338bf2e13afd553798/guava/src/com/google/common/cache/LocalCache.java#L2598) which is called from:
>
> -   [`#recordWrite`](https://github.com/google/guava/blob/58e30d60ac49d5726031da338bf2e13afd553798/guava/src/com/google/common/cache/LocalCache.java#L2576) which triggered when we put new value to cache entry.
> -   [`#expireEntries`](https://github.com/google/guava/blob/58e30d60ac49d5726031da338bf2e13afd553798/guava/src/com/google/common/cache/LocalCache.java#L2625) which is triggered when we hit expired cache entry and as part of [`#postReadCleanup`](https://github.com/google/guava/blob/58e30d60ac49d5726031da338bf2e13afd553798/guava/src/com/google/common/cache/LocalCache.java#L3465-L3497) under `#tryLock`.
> -   [`#evictEntries`](https://github.com/google/guava/blob/58e30d60ac49d5726031da338bf2e13afd553798/guava/src/com/google/common/cache/LocalCache.java#L2667) which triggered when we replace cache entry by reaching limit or putting entries directly.
>
> Effectively draining `recencyQueue` can be slower for next reasons:
>
> -   Draining done under wide exclusive lock allowing only one thread to perform drain.
> -   Adding to the queue done likely through atomics or through short locking.
> -   [During draining we also check `accessQueue` for every removed element](https://github.com/google/guava/blob/58e30d60ac49d5726031da338bf2e13afd553798/guava/src/com/google/common/cache/LocalCache.java#L2598-L2603) which is a bit heavier than [adding entry into `recencyQueue`](https://github.com/google/guava/blob/58e30d60ac49d5726031da338bf2e13afd553798/guava/src/com/google/common/cache/LocalCache.java#L2551). And having complex cache key aggravates it.

Code to reproduce memory leak relatively consistently:

```
import static java.lang.String.format;

import java.time.Duration;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.BrokenBarrierException;
import java.util.concurrent.CyclicBarrier;

import com.google.common.cache.CacheBuilder;
import com.google.common.cache.CacheLoader;
import com.google.common.cache.CacheStats;
import com.google.common.cache.LoadingCache;
import com.google.common.util.concurrent.AbstractScheduledService;

import org.junit.jupiter.api.RepeatedTest;

// Tested with JVM args: -ea -Xmx2g -Xms2g -XX:MaxMetaspaceSize=500m
public class GuavaCacheTest {
    private static final DummyKey DUMMY_KEY = new DummyKey();

    @RepeatedTest(5)
    void whenGet_thenLeak() throws InterruptedException, BrokenBarrierException {
        LoadingCache<DummyKey, Integer> cache = CacheBuilder.newBuilder()
                .maximumSize(1000L)
                .recordStats()
                .expireAfterWrite(Duration.ofDays(1))
                .build(new CacheLoader<DummyKey, Integer>() {
                    @Override
                    public Integer load(DummyKey key) {
                        return 42;
                    }
                });

        Runtime runtime = Runtime.getRuntime();
        long initialTotalMemory = runtime.totalMemory();
        System.out.println("initialTotalMemory = " + toHumanBytes(initialTotalMemory));

        // Monitor heap utilization/size
        new AbstractScheduledService() {
            @Override
            protected void runOneIteration() {
                runtime.gc(); // trigger full GC to keep only live objects
                long totalMemory = runtime.totalMemory();
                long freeMemory = runtime.freeMemory();
                System.out.printf("Free memory %s (%.1f%%), heap size %s (%.1f%%)%n",
                        toHumanBytes(freeMemory), freeMemory * 100.0 / totalMemory,
                        toHumanBytes(totalMemory), totalMemory * 100.0 / initialTotalMemory);
                CacheStats stats = cache.stats();
                System.out.println("cache.size() = " + cache.size());
                System.out.println("stats.hitCount() = " + stats.hitCount());
                System.out.println("stats.evictionCount() = " + stats.evictionCount());
            }

            @Override
            protected Scheduler scheduler() {
                return Scheduler.newFixedDelaySchedule(Duration.ZERO, Duration.ofSeconds(1));
            }
        }.startAsync();

        int parties = runtime.availableProcessors() * 2;  // make readers/writers compete for CPU
        CyclicBarrier barrier = new CyclicBarrier(parties);

        List<Thread> threads = new ArrayList<>(parties);

        // Optional wind up of recencyQueue so its draining will take some time
        for (int i = 0; i < (64-parties-1); i++) {
            cache.getUnchecked(DUMMY_KEY);
        }

        for (int i = 0; i < parties-1; i++) {
            Thread thread = new Thread(() -> {
                try {
                    barrier.await();
                } catch (InterruptedException | BrokenBarrierException e) {
                    throw new RuntimeException(e);
                }

                // By this moment all parties are ready to start
                for (;;) {
                    cache.getUnchecked(DUMMY_KEY);
                }
            });
            threads.add(thread);
            thread.start();
        }

        barrier.await();
        // By this moment all parties are ready to start
        cache.invalidate(DUMMY_KEY);  // triggers drain of recencyQueue

        // Likely not reached
        threads.forEach(Thread::interrupt);
        for (Thread thread : threads) {
            thread.join();
        }
    }

    private static String toHumanBytes(long freeMemory) {
        return format("%.1f GiB", freeMemory / (1024f * 1024 * 1024));
    }

    public static class DummyKey {
        @Override
        public boolean equals(Object obj) {
            // simulate complex key comparison
            sleep(10);  // delays draining of recencyQueue vs its population
            return super.equals(obj);
        }
    }

    private static void sleep(int millis) {
        try {
            Thread.sleep(millis);
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }
    }
}
```

**Comment by a-omy** [comment]
@cgdecker, would it make sense to re-open this bug given example of how to reproduce leak of entry access references?
