### ISSUE TITLE
Add skipRemaining() method to HashingInputStream

### ISSUE THREAD

**Issue by Marcono1234** [google/guava#3522]
Blocked by #3521

There are cases where you are not interested in the complete content of an input stream, but to have `HashingInputStream` calculate the correct hash you have to read the remaining data. Ideally you would want to skip all remaining data, but the methods provided by `InputStream` do not allow you to do this easily:
- `skip(long)` might skip less data and does not indicate if the end of the stream has been reached.
- `skipNBytes(long)` (Java 12) throws an `EOFException` if you try to skip too many bytes.
- `read` methods allocate arrays or require existing arrays.

It would be useful to have a `HashingInputStream.skipRemaining()` method which could be implemented like this:
```
public void skipRemaining() throws IOException {
    while (read() != -1) {
        skip(Long.MAX_VALUE);
    }
}
```
Even though it might be appealing to `close()` the stream as well, I think this should not be done (and this behavior should be documented). "Special" streams like `ZipInputStream` might have more data even after they reached the "end" of data (in this case more data becomes available by calling `getNextEntry()`).

A case where this request method would be useful can be seen in #3521.

**Comment by ChristianCiach** [comment]
Have a look at `ByteStreams.exhaust(InputStream)`.

**Comment by Marcono1234** [comment]
Yes that is exactly what I am looking for. I still think it might be worth it to add the method to `HashingInputStream` and then delegate it to that method or the implementation described above, because it appears this is a common use case when working with `HashingInputStream`s.

However, I can understand if this is not desired or not considered worth it and if this issue is therefore closed.

**Comment by nglorioso** [comment]
Thanks for the recommended replacement @ChristianCiach! Closing this issue.
