### ISSUE TITLE
Ints.join() why StringBuilder size is  array.length*5

### ISSUE THREAD

**Issue by feiyanwuhen** [google/guava#3532]
StringBuilder builder = new StringBuilder(array.length * 5);
if can be changed 
StringBuilder builder = new StringBuilder(array.length * 2);

**Comment by ljacqu** [comment]
As the comment above says, "get the right order of magnitude". Integers in the array might have more than one digit, and the separator could also be more than one char

**Comment by feiyanwuhen** [comment]
I got it ,thank you very much!

**Comment by netdpb** [comment]
This seems more like a question appropriate for StackOverflow than a bug or feature request. But I'm glad you got your answer anyway!
