### ISSUE TITLE
Iterables.toArray() gives "java.lang.OutOfMemoryError: Java heap space" when used with Iterables.cycle

### ISSUE THREAD

**Issue by jarodriguez-itsoft** [google/guava#3536]
Seems Iterables.toArray() doesn't correctly handle cycled iterables.

Easily reproduced using the following code:

```
List<Integer> exampleList = new ArrayList<Integer>();
exampleList.add(new Integer(0));
Iterable<Integer> cycleIterable = Iterables.cycle(exampleList);
Integer[] exampleArray = com.google.common.collect.Iterables.toArray(cycleIterable, Integer.class);
```

**Comment by nglorioso** [comment]
From the [Javadoc on Iterables.cycle](https://guava.dev/releases/21.0/api/docs/com/google/common/collect/Iterables.html#cycle-java.lang.Iterable-):

> Warning: Typical uses of the resulting iterator may produce an infinite loop. You should use an explicit break or be certain that you will eventually remove all the elements.

`Iterables.cycle()` is the underlying cause - `Iterables.toArray` will just blindly copy elements from the Iterable to an array without giving you an opportunity to remove elements from the Iterable in the meantime.

**Comment by jarodriguez-itsoft** [comment]
It was evident Iterables.cycle() was the cause and specifically the endless iteration nature of it.
I opened this PR to show that the usage of 2 specific components of this library (cycle and toArray) ends up causing quite a big issue.

I hoped that a feature request to add built-it handling of this case could be added to the toArray() function.
There are many alternatives, from a simple one such as throwing an Exception if a cycled iterator is passed to the function, to the ideal one which would be creating an array with the elements the undelaying structure the cycle iterator is wrapping.

**Comment by nglorioso** [comment]
Right, but it wouldn't be appropriate for our libraries to special-case how to interact with `Iterables.cycle()`. The same vulnerability exists, for example, if you pass some other infinite Iterable, like:

```java
Iterable<Double> infiniteIterable = Stream.generate(new Random()::nextDouble)::iterator;
Double[] dbls = Iterables.toArray(infiniteIterable);
```
