### ISSUE TITLE
Minor bug in Preconditions wiki page

### ISSUE THREAD

**Issue by mavicon** [google/guava#3546]
On wiki page https://github.com/google/guava/wiki/PreconditionsExplained

`checkArgument(i < j, "Expected i < j, but %s > %s", i, j);`

should be either
`checkArgument(i < j, "Expected i < j, but %s >= %s", i, j);`
or 
`checkArgument(I <= j, "Expected I <= j, but %s > %s", i, j);'`

**Comment by mavicon** [comment]
I'll try to make a pull request on the wiki myself.

**Comment by mavicon** [comment]
Have no permissions to do so. Patch file added
[Fix_bug__https___github_com_google_guava_issues_3546_Minor_bug_in_message_.patch.zip](https://github.com/google/guava/files/3455420/Fix_bug__https___github_com_google_guava_issues_3546_Minor_bug_in_message_.patch.zip)

**Comment by cgdecker** [comment]
Thanks, I'm fixing this internally and it'll be synced out soon.
