### ISSUE TITLE
Deadlock in HashBiMap#seekByValue

### ISSUE THREAD

**Issue by sfuhrm** [google/guava#3548]
We experienced an application deadlock in the `seekByValue()` method in the `HashBiMap` class.

This is the relevant application stacktrace we've seen:

    "Consumer-56" #229 prio=5 os_prio=0 cpu=62908744.70ms elapsed=865617.45s tid=0x00007fc39c63f800 nid=0x1c6a runnable  [0x00007fc371a9f000]
       java.lang.Thread.State: RUNNABLE
            at com.google.common.collect.HashBiMap.seekByValue(HashBiMap.java:234)
            at com.google.common.collect.HashBiMap.put(HashBiMap.java:274)
            at com.google.common.collect.HashBiMap.put(HashBiMap.java:260)
            at ...
            - locked <0x00000001c7a40130> (a [Ljava.lang.Object;)
            at ...
        at java.lang.Thread.run(java.base@11.0.3/Thread.java:834)

The HashBiMap is always executed in a critical section, so the data structures of the map should be ok.
My lucky guess is that the condition `entry != null` in the loop in `seekByValue()` is not met under certain circumstances and needs to be refined.

See the line here
https://github.com/google/guava/blob/82988bb2cafb95fd5dde57720024112c20891ac3/guava/src/com/google/common/collect/HashBiMap.java#L233

**Comment by ben-manes** [comment]
> The HashBiMap is always executed in a critical section, so the data structures of the map should be ok.

Are both __reads__ and __writes__ guarded by the lock? A common mistake with `HashMap` is to believe you only need to lock on writes and can read outside of that critical section, which can lead to infinite loops. You probably want to use `Maps.synchronizedBiMap` to protect it.

**Comment by sfuhrm** [comment]
@ben-manes  I've re-checked the locking patterns in the application and I think that the problem is there. Thanks for your inspiration!
