### ISSUE TITLE
listeningDecorator(ScheduledExecutorService) should cancel scheduled tasks when terminating

### ISSUE THREAD

**Issue by cpovirk** [google/guava#3554]
I got an email when #3553 was filed about this, but it seems to have been deleted.

The spec for `ScheduledExecutorService` added this new requirement when moving from [Java 8](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ScheduledExecutorService.html#scheduleAtFixedRate-java.lang.Runnable-long-long-java.util.concurrent.TimeUnit-) to [Java 9](https://docs.oracle.com/javase/9/docs/api/java/util/concurrent/ScheduledExecutorService.html#scheduleAtFixedRate-java.lang.Runnable-long-long-java.util.concurrent.TimeUnit-):

> The sequence of task executions continues indefinitely until one of the following exceptional completions occur:
> ...
> - The executor terminates, _also resulting in task cancellation_.

(Yes, the old spec says "Otherwise, the task will only terminate via cancellation _or termination of the executor_." But it's not clear that "task termination" (presumably meaning "Is the `Runnable` run again?") implies "`Future` cancellation." In particular, if termination implied cancellation, I would expect the spec to just say "Otherwise, the task will only terminate via cancellation [, such as by termination of the executor]." Anyway, it's mostly academic; the spec now says what is says, and I don't think the old spec _forbids_ that behavior.)

**Comment by GeorgiPetkov** [comment]
Hi Chris, I hope #3553 is visible now, my GitHub account was temporarily hidden from the public due to wrong spam detection (and probably that's why it appeared as missing/deleted to you). If that is the case we can close this and if put your thoughts in #3553.

**Comment by cpovirk** [comment]
Thanks! Will do.
