### ISSUE TITLE
Rolling upgrade to Guava 28.0 breaks due to backward in-compatible change

### ISSUE THREAD

**Issue by SElab2019** [google/guava#3562]
Hi,

When I try to update Guava from 18.0 to the last version 28.0, it breaks backward compatibility due to the changes in com.google.common.util.concurrent.MoreExecutors. This also breaks rolling upgrades since any client implementing this - like Apache Curator. 

-The following code will fail to run with the error: `java.lang.NoSuchMethodError: com.google.common.util.concurrent.MoreExecutors.sameThreadExecutor()Lcom/google/common/util/concurrent/ListeningExecutorService;`

```
public class GuavaTest {

	private static CuratorFramework buildCuratorFramework() {
		String connectionString = "localhost:21818";
		RetryPolicy retryPolicy = new ExponentialBackoffRetry(1000, 3);
		CuratorFramework newCurator = CuratorFrameworkFactory.newClient(connectionString, retryPolicy);
		newCurator.start();
		return newCurator;
	}
	
	@Test
	public void test(){
		CuratorFramework curator = buildCuratorFramework();		
	}
}
```

Thanks.

**Comment by cpovirk** [comment]
This is expected: `sameThreadExecutor` was removed in favor of `directExecutor` in [Guava 21](https://github.com/google/guava/wiki/Release21#commonutilconcurrent). This is permitted under [our policy for changes to `@Beta` APIs](https://github.com/google/guava#important-warnings). The good news is:

- [`directExecutor`](https://guava.dev/releases/snapshot-jre/api/docs/com/google/common/util/concurrent/MoreExecutors.html#directExecutor--) is _not_ `@Beta`, so it's now safe to use from libraries.
- In response to [this problem](https://github.com/apache/curator/pull/199) and others, it sounds like Curator changed a few years ago to [shade Guava](https://issues.apache.org/jira/browse/CURATOR-200) (see [pom](https://github.com/apache/curator/blob/c670844a8c5bdaec94ca4b7becea5df734cf5a47/pom.xml#L883)), as required for libraries that use `@Beta` APIs.
