### ISSUE TITLE
Add "not-null" in code comment

### ISSUE THREAD

**Issue by XZ-X** [google/guava#3567]
In the class `com.google.common.base.Throwables`, the method depicted below has a parameter whose value should not be null. The method invocation `throwable.getCause()` in the while condition could throw an unexpected NullPointerException if the `throwable` is null. 

In this case, we might mark this parameter as "not-null" in the Javadoc comment above the method.

```java
 /**
   * Returns the innermost cause of {@code throwable}. The first throwable in a chain provides
   * context from when the error or exception was initially detected. Example usage:
   *
   * <pre>
   * assertEquals("Unable to assign a customer id", Throwables.getRootCause(e).getMessage());
   * </pre>
   *
   * @throws IllegalArgumentException if there is a loop in the causal chain
   */
  public static Throwable getRootCause(Throwable throwable) {
    // Keep a second pointer that slowly walks the causal chain. If the fast pointer ever catches
    // the slower pointer, then there's a loop.
    Throwable slowPointer = throwable;
    boolean advanceSlowPointer = false;

    Throwable cause;
    while ((cause = throwable.getCause()) != null) {
      throwable = cause;

      if (throwable == slowPointer) {
        throw new IllegalArgumentException("Loop in causal chain detected.", throwable);
      }
      if (advanceSlowPointer) {
        slowPointer = slowPointer.getCause();
      }
      advanceSlowPointer = !advanceSlowPointer; // only advance every other iteration
    }
    return throwable;
  }
```

**Comment by ogregoire** [comment]
Guava is not a null-friendly API and [the default is that `null` will throw `NullPointerException`](https://github.com/google/guava/wiki/UsingAndAvoidingNullExplained#using-and-avoiding-null):

> For these reasons, many of Guava's utilities are designed to fail fast in the presence of null rather than allow nulls to be used, so long as there is a null-friendly workaround available. Additionally, Guava provides a number of facilities both to make using `null` easier, when you must, and to help you avoid using `null`.

Furthermore, the package [`com.google.common.base`](https://guava.dev/releases/snapshot-jre/api/docs/com/google/common/base/package-summary.html) is appropriately annotated with [`@ParametersAreNonnullByDefault`](https://static.javadoc.io/com.google.code.findbugs/jsr305/3.0.1/javax/annotation/ParametersAreNonnullByDefault.html?is-external=true).

**Comment by XZ-X** [comment]
Got it! Thank you for your reply!
