### ISSUE TITLE
Reuse of ImmutableSet.Builder with expected size leading to infinite loop on ImmutableSet.contains

### ISSUE THREAD

**Issue by tomasisonfire** [google/guava#3570]
The following snippet produces an infinite loop inside the method ImmutableSet.contains:

```java
ImmutableSet.Builder<Object> builder = ImmutableSet.builderWithExpectedSize(6);
builder.add(0);
builder.build();
ImmutableSet<Object> subject = builder.add(1).add(2).add(3).build();
boolean contains = subject.contains(4);
```

This behavior was first observed in guava 25.1-jre and it still happens in version 28.0-jre.

Analyzing the source code, I think there is a problem in the implementation of ImmutableSet.RegularSetBuilderImpl.review(). As it decides to reduce the _hashTable_, it does not recompute the _expandTableThreshold_ nor _maxRunBeforeFallback_. From this point, I observed two consequences:

1. Given a RegularSetBuilderImpl with D distinct elements. 
After resizing the hashTable to size N, if the (N-D) distinct elements are added, the subsequent build() method would return an instance of ImmutableSet that reproduces the infinite loop on method contains.
2. In the same scenario as above, when the (N+1)th element is added to the builder, the RegularSetBuilderImpl will iterate _maxRunBeforeFallback_ times in a full hashTable, until it falls back to the JdkBackedSetBuilderImpl.

**Comment by cpovirk** [comment]
Thank you for catching this!

**Comment by tomasisonfire** [comment]
You are welcome :)
