### ISSUE TITLE
Upgrading incompatible issue

### ISSUE THREAD

**Issue by SElab2019** [google/guava#3574]
Hi,

The following code snippets throw an incompatible issue when I try to upgrade Guava from 19.0 to 28.0.

```
@Test
public void find_element_in_iterable () {
    checkArgument(
        Boolean.TRUE,
        "test string",
        1,
        2);
}
```

It throws an error:
```
reference to checkArgument is ambiguous
[ERROR]   both method checkArgument(boolean,java.lang.String,int,java.lang.Object) in com.google.common.base.Preconditions and method checkArgument(boolean,java.lang.String,int,int) in com.google.common.base.Preconditions match
```

Thanks a lot

**Comment by cpovirk** [comment]
Sorry for the trouble. We are aware that this change is [not always source-compatible](https://github.com/google/guava/commit/892e323fca32945cdfb25395ca6e346dd0fffa5b) (though it is binary compatible, in accordance with [our policy for non-`@Beta` APIs](https://github.com/google/guava#important-warnings)). We estimated that something like a hundredth of a percent of calls would break, so we decided it was a beneficial change overall. That might not be much consolation if it's biting you, though :(

As a workaround, you can cast any arguments that cause ambiguity to types that more directly match one of the available overloads. In this case, the trigger seems to be the boxed `Boolean` passed as the first parameter. If you cast it to primitive `boolean`, most ambiguities will go away.

**Comment by cpovirk** [comment]
Here's [a little more detail on boxed `Boolean`](https://github.com/google/guava/blob/794a10a4495fd7cd554eb0a9e480708d0277aced/guava-tests/test/com/google/common/base/PreconditionsTest.java#L525-L526).
