### ISSUE TITLE
Guava Cache Cleanup is not documented correctly

### ISSUE THREAD

**Issue by rahulsahadevan** [google/guava#3593]
At https://github.com/google/guava/wiki/CachesExplained
in the subsection titled "When Does Cleanup Happen?",
the following 2 lines (or a rewording) needs to be added

a) Although cache evictions happen randomly, the value returned by the get method is guaranteed not to have expired.
b) If it was expired at the time when the get call was made, Guava will immediately discard the expired value and load the latest value from the underlying store.

Currently these 2 statements do not exist,
and my colleague showed me the existing incomplete documentation,
and was able to convince me that based on what is currently documented,
  Guava cache is unreliable because it is lazy and does not evict values when they expire.
  So if you try to read a value that has expired, you will get the expired value since it has not been evicted.

Please add the above 2 statements I mentioned above so that people do not conclude incorrectly that,
Guava cache will return expired values because Guava is lazy on eviction.

**Comment by ben-manes** [comment]
Please provide a unit test showing the incorrect behavior. The cache will not return an expired value to the caller. However, it will not notify the removal listener promptly when the entry expires, and delay until there is other activity causing a maintenance routine. This does not seem to violate the api or documentation.

**Comment by rahulsahadevan** [comment]
>> Please provide a unit test showing the incorrect behavior.
   I am not referring to an incorrect behavior in this issue.
   Rather I am referring to an ambiguity in the documentation.

>> The cache will not return an expired value to the caller.
   The above statement needs to be explicitly mentioned in the documentation.

   With the current documentation, after someone reads the following
--
Caches built with CacheBuilder do not perform cleanup and evict values "automatically," or instantly after a value expires, or anything of the sort. Instead, it performs small amounts of maintenance during write operations, or during occasional read operations if writes are rare.`
--
   some people will incorrectly conclude that,
   since cache cleanup happens infrequently(small amounts of maintenance during write operations, or during occasional read operations if writes are rare)
   then if cache clearnup has not happened by the time you read a value,
   the cache will return stale(expired) values to the caller

>> However, it will not notify the removal listener promptly when the entry expires, and delay until there is other activity causing a maintenance routine. This does not seem to violate the api or documentation.
   I agree with this statement.


To prevent the confusion my colleague had, I need the following statement to be explicitly mentioned in the documentation
  >> The cache will not return an expired value to the caller.

**Comment by lowasser** [comment]
The CacheBuilder documentation specifies the correct behavior, in the line "Expired entries may be counted by Cache.size(), but will never be visible to read or write operations."

**Comment by rahulsahadevan** [comment]
Ok, I missed that.
