### ISSUE TITLE
Utils for comparison of Time objects

### ISSUE THREAD

**Issue by rkinabhi** [google/guava#3594]
I would love to have utilities that can be used for comparing Dates and Times.
I have frequently built helper methods to perform tasks such as getting the earliest / latest DateTime object in java using collections.

But It would be great if we could have utilities built for `java.time`... 
such as `Instants.earliest(...)` or `Times.earliest(...)`

Is Guava the right place to build such tools? If not... where should I be looking to find/build such tools?

**Comment by ben-manes** [comment]
Some times are comparable, you can use generic methods like Collections' min/max, Guava's Ordering, etc?

**Comment by kluever** [comment]
+1 for using `Comparable`-based APIs. We're also considering adding `Comparators.min(E, E)` and `max(E, E)`, which would let you do this more easily.
