### ISSUE TITLE
add FutureCallback<Void> failed

### ISSUE THREAD

**Issue by zhouzach** [google/guava#3604]
My scala code:
```scala
        ExecutorService executor = Executors.newFixedThreadPool(1);
        ListeningExecutorService listeningExecutor = MoreExecutors.listeningDecorator(executor);

        ListenableFuture<?> future = listeningExecutor.submit(() -> {
            System.out.println("task1 starts");
            try {
                Thread.sleep(10000);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        });

        Futures.addCallback(future,
                new FutureCallback<Void>() {

                    @Override
                    public void onFailure(Throwable t) {
                        System.out.println("failure");
                    }

                    @Override
                    public void onSuccess(Void result) {

                        System.out.println("I am informed ");
                    }
                },
                executor);
```
Intellij Idea reports:

Error:(61, 16) java: 无法将类 com.google.common.util.concurrent.Futures中的方法 addCallback应用到给定类型; 需要: com.google.common.util.concurrent.ListenableFuture<V>,com.google.common.util.concurrent.FutureCallback<? super V>,java.util.concurrent.Executor 找到: com.google.common.util.concurrent.ListenableFuture<capture#1, 共 ?>,<匿名com.google.common.util.concurrent.FutureCallback<java.lang.Void>>,java.util.concurrent.ExecutorService 原因: 推论变量 V 具有不兼容的限制范围 等式约束条件: capture#1, 共 ? 上限: java.lang.Void,java.lang.Object

who can help me?

**Comment by cgdecker** [comment]
The return type of `submit(Runnable)` is `ListenableFuture<?>`, so you can't just change it to `ListenableFuture<Void>`.

As I said, the thing you need to change is `FutureCallback<Void>` to `FutureCallback<Object>`.
