### ISSUE TITLE
Consider adding RateLimiter cancel/clear or pause functionality.

### ISSUE THREAD

**Issue by paulnadler** [google/guava#3608]
I don't see a way to remove queued requests in the RateLimiter. Pausing/resuming all requests would be even better for my use case. When the user leaves the app I need to stop any requests that have not already started execution.

`tryAcquire()` isn't quite right to solve this problem because I need to respond to user action rather than a timeout, but I am doing this as a workaround, which hopefully doesn't lead to unintended consequences. 

Setting the canceled flag to true I can make sure no new requests will start past 5 seconds.

    boolean acquired = false;
    while (!canceled && !acquired) {
        acquired = rateLimiter.tryAcquire(5, TimeUnit.SECONDS);
        if (!acquired) {
            try {
                Thread.sleep(1000);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }
    }
    downloadFile()

**Comment by netdpb** [comment]
`RateLimiter` doesn't make any requests, and doesn't have a queue. There's nothing to cancel or pause. That seems to be something you'd want to do at the level of the object that is _using_ a `RateLimiter`, that actually represents outstanding cancellable requests. See the comment on the Javadoc about using a `Semaphore` to limit concurrent requests, which might be more relevant for cancelling.

You may have more luck asking about this on stackoverflow.com or other similar places.

**Comment by paulnadler** [comment]
I'm not sure I understand this reasoning. Are you saying conceptually a RateLimiter shouldn't be able to do this? In the code there are permits and reservations which is what the RateLimiter "has" to cancel. Or specifically "interrupt". But I guess there is a reason it was decided to do this "uninterruptibly". 

Conceptually I don't see why a rate limiter wouldn't be able to pause or stop rate limiting, even if that meant letting everything through. It would still be better than all those threads blocking. Anyways, I guess I will stick with the workaround above which essentially does this.

As you said, a Semaphore limits concurrent requests not based on rate. I need to limit the rate.

**Comment by netdpb** [comment]
I guess I'm saying if you want to pause or stop rate limiting, you could just stop asking the `RateLimiter` for permits and make whatever requests you want.

Your original question was about stopping queued requests, for instance when the user leaves the app. `RateLimiter` isn't a request queue.

If you _have_ a request queue, and taking requests from that queue to actually process is gated by a `RateLimiter`, then if you want to pause or cancel, I think it makes sense to pause the thing reading from the queue, or cancel individual requests in the queue.
