### ISSUE TITLE
Wiki doc “ThrowablesExplained” has a markdown symbol error 

### ISSUE THREAD

**Issue by LENSHOOD** [google/guava#3613]
There is a markdown symbol error in the Wiki page: [ThrowablesExplained](https://github.com/google/guava/wiki/ThrowablesExplained), at the line above of`Unnecessary: Converting from "throws Throwable" to "throws Exception"`

The original text is:
*Additionally, use of propagate [makes it easy to accidentally wrap checked exceptions] (https://github.com/google/guava/commit/287bc67cac97052b13cbbc0358aed8054b14bd4a).*

But the correct one might be: *Additionally, use of propagate [makes it easy to accidentally wrap checked exceptions](https://github.com/google/guava/commit/287bc67cac97052b13cbbc0358aed8054b14bd4a).*

There is a space character between brackets and parentheses.

**Comment by jrtom** [comment]
Thanks!  Fixed.
