### ISSUE TITLE
why guava not split into some maven modules?

### ISSUE THREAD

**Issue by yx91490** [google/guava#3619]
Mostly my project only need few classes in guava, for example I only need "Lists, Maps" , but  I alse need to dependent the full guava jar. why guava not split into some maven modules? like collection module..., then I will only dependent a smaller jar in my project.

**Comment by ogregoire** [comment]
You can drastically shrink your Guava library with [ProGuard](https://github.com/google/guava/wiki/UsingProGuardWithGuava), if you want

**Comment by netdpb** [comment]
Guava itself uses different parts of itself. For instance, the `collect` package uses the `base` package. We long ago decided to release it as one JAR. As @ogregoire noted, you can use ProGuard if you're interested in shrinking your binary size.
