### ISSUE TITLE
Why ImmutableSortedSet use comparator to determine equals?

### ISSUE THREAD

**Issue by liudaomanbu** [google/guava#3625]
version:28.1-jre
```java
@Test
  public void equals(){
    Ordering<Person> ORDERING = Ordering.natural().onResultOf(Person::getAge);
    Person john = new Person("john", 18);
    Person bob = new Person("bob", 18);
    ImmutableSortedSet<Person> set1=ImmutableSortedSet.orderedBy(ORDERING).add(john).build();
    ImmutableSortedSet<Person> set2=ImmutableSortedSet.orderedBy(ORDERING).add(bob).build();
    System.out.println("set1.equals(set2):"+set1.equals(set2));
    System.out.println("john.equals(bob):"+john.equals(bob));
  }
```

> set1.equals(set2):true
john.equals(bob):false

Why ImmutableSortedSet use comparator to determine equals?

If I want to rank by age, the order of person objects of equal age is arbitrary.

How should I write my comparator?

**Comment by Stephan202** [comment]
Given that you use variable names `list1` and `list2`, it seems that you actually want immutable _lists_. Thus, consider using `ImmutableList.sortedCopyOf` instead.

If you do need to use `ImmutableSortedSet`, then your comparator must be made consistent with `#equals(Object)`. In the general case this requires a comparator which considers all properties also considered by `equals`, but often one can get away by breaking ties based on the object's ID. (Assuming there is one.)

**Comment by liudaomanbu** [comment]
> Given that you use variable names `list1` and `list2`, it seems that you actually want immutable _lists_. Thus, consider using `ImmutableList.sortedCopyOf` instead.
> 
> If you do need to use `ImmutableSortedSet`, then your comparator must be made consistent with `#equals(Object)`. In the general case this requires a comparator which considers all properties also considered by `equals`, but often one can get away by breaking ties based on the object's ID. (Assuming there is one.)

list is only a variable name,i want to have sort set,Orderly and non-repetitive

**Comment by Stephan202** [comment]
Using Java 8+, assuming your `Person` class has only the mentioned two properties:
```java
Comparator<Person> TOTAL_ORDER_BY_AGE =
    Comparator.comparing(Person::getAge)
              .thenComparing(Person::getName);
```

**Comment by liudaomanbu** [comment]
> Using Java 8+, assuming your `Person` class has only the mentioned two properties:
> 
> ```java
> Comparator<Person> TOTAL_ORDER_BY_AGE =
>     Comparator.comparing(Person::getAge)
>               .thenComparing(Person::getName);
> ```

What if there are more attributes?

Continue using thenComparing method?

I hope I can use the equals method as the object itself.

**Comment by Stephan202** [comment]
> Continue using thenComparing method?

In the general case, yes. (Unless, as stated, there's an ID field or some other property guaranteed to be unique for each object. Then you can stop after comparing that one.)

> I hope I can use the equals method as the object itself.

`ImmutableSortedSet`, just like Java's own `TreeSet`, fundamentally relies on the given `Comparator` for determining equality. I am not aware of a JDK/Guava collection which has the property you're looking for.

**Comment by liudaomanbu** [comment]
> > Continue using thenComparing method?
> 
> In the general case, yes. (Unless, as stated, there's an ID field or some other property guaranteed to be unique for each object. Then you can stop after comparing that one.)
> 
> > I hope I can use the equals method as the object itself.
> 
> `ImmutableSortedSet`, just like Java's own `TreeSet`, fundamentally relies on the given `Comparator` for determining equality. I am not aware of a JDK/Guava collection which has the property you're looking for.

Thanks for your answer,i kown

**Comment by Stephan202** [comment]
For completeness one other thought: if you want the `Set`'s _iteration order_ to be sorted but don't need any of the operations provided by `SortedSet`/`NavigableSet`, then you can build a regular `ImmutableSet` by inserting the elements in already sorted order. E.g.:
```java
ImmutableSet<Person> persons
    = ImmutableSet.copyOf(ImmutableList.sortedCopyOf(cmp, myElements));
```
or:
```java
ImmutableSet<Person> persons = myElements.stream().sorted(cmp).collect(toImmutableSet());
```

This works because `ImmutableSet` (like e.g. a `LinkedHashSet`) iterates over its elements in insertion order.
