### ISSUE TITLE
Util methods to make Comparable#compareTo more readable

### ISSUE THREAD

**Issue by wilmol** [google/guava#3632]
I had a problem where I had some code like this:
```
    Duration oneWeek = Duration.ofDays(7);
    Duration oneMonth = Duration.ofDays(28);
    return oneWeek.compareTo(oneMonth) < 0;
```

The issue is only those that know how ```compareTo``` works realise it returns ```true```.

So I suggest adding some static methods like (e.g. in a class called ```Comparables```) to make it more readable:
```
  public static <C extends Comparable<? super C>> boolean isLessThan(C left, C right) {
    return left.compareTo(right) < 0;
  }
```

So the above can be expressed as:
```
    Duration oneWeek = Duration.ofDays(7);
    Duration oneMonth = Duration.ofDays(28);
    return isLessThan(oneWeek, oneMonth);
```

Would have other methods like ```isLessThanOrEqual```, ```isGreaterThan```, ```isGreaterThanOrEqual```

---

Or maybe, a class that wraps a ```Comparable``` (similar idea to ```Equivalence.Wrapper```) so it can be expressed like: 
```
    Wrapper<Duration> oneWeek = Wrapper.wrap(Duration.ofDays(7));
    Wrapper<Duration> oneMonth = Wrapper.wrap(Duration.ofDays(28));
    return oneWeek.isLessThan(oneMonth);
```

E.g. ```Wrapper``` looks like:
```
  public static class Wrapper<C extends Comparable<? super C>> {
    private final C object;

    public static <C extends Comparable<? super C>> Wrapper<C> wrap(C object) {
      return new Wrapper<>(object);
    }

    private Wrapper(C object) {
      this.object = requireNonNull(object);
    }

    public boolean isLessThan(Wrapper<? extends C> other) {
      return object.compareTo(other.object) < 0;
    }
  }
```

**Comment by cpovirk** [comment]
This is something that we've been very conflicted about. The readability win is often nice, but we haven't been able to convince ourselves that it's worth the debates it would cause in code review over which pattern to use. This is probably still a library that should exist somewhere, but it's most likely not going to be Guava, for better or for worse.

**Comment by wilmol** [comment]
@cpovirk fair enough. 

FYI I have found ```Range``` suits my need:
```
Range.lessThan(oneMonth).contains(oneWeek)
```
