### ISSUE TITLE
Strings Repeat method potential issue

### ISSUE THREAD

**Issue by johnsoneal** [google/guava#3642]
In the Strings.repeat method checks are performed to ensure that the resulting char[] array is not to large. In JDK9 or greater compact string are enabled by default so this check may produce a large char array which is less than Integer.MAX_VALUE but may result in a OutOfMemoryError if the string being repeated contains a single value that is not LATIN-1.

I'm not sure that this is a bug as such, only that the checks are performed
and it may be possible to prevent the array creation in the first place. For example, it may be possible to check that the repeat string has only LATIN-1 and then proceed as is; if not use a length value that is larger:

        int a = s.length();
        int b = s.codePointCount(0, s.length());
        int len = (a <= b) ? a : b*2;

**Comment by cpovirk** [comment]
I see, makes sense. Given that Guava aims to be run in any environment that can ultimately consume Java sources, though, I think it's best not to specialize for particular VMs, even extremely popular ones, unless the gain is large.
