### ISSUE TITLE
Lists.newArrayListWithExpectedSize Issues

### ISSUE THREAD

**Issue by Jshen6** [google/guava#3659]
I just wanna 30 length, why give me 38 length?
![image](https://user-images.githubusercontent.com/37428835/67062259-5f221100-f195-11e9-932e-900531fb0240.png)
![image](https://user-images.githubusercontent.com/37428835/67062312-7eb93980-f195-11e9-999f-71de08c98045.png)
p.s. I can fix that by pr.

**Comment by Maaartinus** [comment]
That's documented:

> Creates an ArrayList instance to hold estimatedSize elements, plus an unspecified amount of padding; you almost certainly mean to call newArrayListWithCapacity (see that method for further advice on usage).

It adds space for 10% and 5 more elements, so you get 30 + 3 + 5 = 38. But note that

> This method will soon be deprecated. Even in the rare case that you do want some amount of padding, it's best if you choose your desired amount explicitly.
