### ISSUE TITLE
Inheriting Javadoc from the JDK is broken on Travis

### ISSUE THREAD

**Issue by cpovirk** [google/guava#3669]
This means that our snapshots are missing doc for methods like `equals`:

https://guava.dev/releases/snapshot-jre/api/docs/com/google/common/primitives/UnsignedInteger.html#equals-java.lang.Object-

Note that our releases are fine. This suggests that there's something insufficient about our setup specifically on Travis. (e.g., maybe it omits `src.zip` there to improve performance.)

I made one attempt to fix this (based on a different theory) in https://github.com/google/guava/commit/4497e2a620892a0540a7d739519cdf77612539fc, but it didn't work, and I've rolled it back internally (to be mirrored out shortly).

We could probably play around with submitting PRs that run `ls -lR $JAVA_HOME` or something, but I don't plan to look into it at the moment.

**Comment by developerhb** [comment]
Hello @cpovirk 

I am Hem Bhagat. I am in 3rd year of Bachelor in Computer Engineering. I am interested in open source projects and want to contribute in them. I chose this project because I am quite interested in Java programming language and want to make a career in it. 

I would like to get detail information about what the problem is?

Please also provide me information about the prerequisites that are necessary for me to solve this problem.

Thank you.

**Comment by developerhb** [comment]
@cpovirk I am waiting for your reply.

**Comment by cpovirk** [comment]
Hello,

The main thing we need to do is figure out if `src.zip` (a zip file containing the source `.java` files for the JDK) is available on Travis for openjdk11.

One thing that you could do is create a pull request that edits [our Travis configuration](https://github.com/google/guava/blob/31999ae6f56e71c341333afde90fcf66c13ce657/.travis.yml#L12). Instead of running our tests, you could tell it to run commands like `ls -lR` on the directory that contains the JDK. When you submit the PR, Travis will run, and you could look for a `src.zip` in its output.

It's possible that [`src.zip` exists but is a symlink pointing to the wrong location](https://bugs.launchpad.net/ubuntu/+source/openjdk-lts/+bug/1791219), or maybe [we need to install an additional package to get the sources](https://askubuntu.com/a/1104463).

If we can't find a JDK 11 `src.zip` at all, then another alternative is to see if we can install the `src.zip` from an older version of Java and use that instead.

**Comment by developerhb** [comment]
Hello @cpovirk 

I had a look at the travis configuration and travis documentation for using different configuration. From that understanding we can have following configuration to list all the files in the JDK folder.

```
deploy:
       provider: script
       script: "ls -l $JAVA_HOME"
       on:
          branch: master
```

Please correct me if I am wrong.

**Comment by cpovirk** [comment]
That looks like it could work. You might also pass `-R` (in addition to `-l`) to see all the contents of subdirectories in case `src.zip` is in a subdirectory. But feel free to submit a PR and watch for the Travis results.

**Comment by developerhb** [comment]
@cpovirk I have created the PR. Here's the link to PR https://github.com/google/guava/pull/3849. I have described the results of Travis CI in the comments section. Please have a look at it.

Please also give me details about what is CLA?

**Comment by developerhb** [comment]
@cpovirk Hello.

Can you please tell me what is the use of `src.zip` in Travis CI and how you access it?
I found out that for versions lower than JDK-9 the src.zip is located in JAVA_HOME/src.zip and from version JDK-9 it is located in JAVA_HOME/lib/src.zip.

So, we can have a condition as mentioned below, where the src.zip file is accessed.

```
if(JDKVERSION<=8)
{
  use JAVA_HOME/src.zip
} 
else
{
  use JAVA_HOME/lib/src.zip
}
```

**Comment by cpovirk** [comment]
Thanks.

It sounds like you have seen [the link to information about the CLA in your PR](https://github.com/google/guava/pull/3849#issuecomment-610789448).

Here's a lot more background on how we use `src.zip` and generate Javadoc:

Our Travis configuration runs a script:
https://github.com/google/guava/blob/31999ae6f56e71c341333afde90fcf66c13ce657/.travis.yml#L16

That script runs another script in the `gh-pages` branch:
https://github.com/google/guava/blob/31999ae6f56e71c341333afde90fcf66c13ce657/util/update_snapshot_docs.sh#L20

That script runs `mvn javadoc:javadoc`:
https://github.com/google/guava/blob/041ffdb5a88b5d3e9bfbe8ab4cbb92355e520405/updaterelease.sh#L120-L123

We have Maven set up to unpack `src.zip` and pass it to the Javadoc binary:
https://github.com/google/guava/blob/31999ae6f56e71c341333afde90fcf66c13ce657/guava/pom.xml#L204-L250

I'll post some more in a minute.

**Comment by cpovirk** [comment]
First, I apologize: We are generating snapshot Javadoc with openjdk8, not openjdk11:
https://github.com/google/guava/blob/31999ae6f56e71c341333afde90fcf66c13ce657/util/update_snapshot_docs.sh#L8

You've said that `src.zip` is in `$JAVA_HOME` for Java 8. This matches what I see on my own computer.

Our `pom.xml` configuration (shown above) doesn't look for `src.zip` in `$JAVA_HOME`, only in `$JAVA_HOME/..` (that is, the parent directory) or `$JAVA_HOME/lib`.

I once tried to fix this by looking in `$JAVA_HOME` itself, as you'd suggested:
https://github.com/google/guava/commit/4497e2a620892a0540a7d739519cdf77612539fc#diff-e407b6f223ee6c04116a91ead9f5e100R193

But when I looked at the docs generated after that, they still didn't look as I expected.

To be clear, what I expect is for our classes to include the Javadoc method descriptions from the JDK methods they override. For example, [we should see this](https://guava.dev/releases/28.2-jre/api/docs/com/google/common/primitives/UnsignedInteger.html#equals-java.lang.Object-), but [instead we see this](https://guava.dev/releases/snapshot-jre/api/docs/com/google/common/primitives/UnsignedInteger.html#equals-java.lang.Object-).

We don't see the problem on our local computers. (This is especially strange because we are using JDK 8, so I wouldn't expect for Maven to find the `src.zip` file at all!) But we do see it on Travis -- even when I tried to fix the problem by configuring Maven to look for `src.zip` in `$JAVA_HOME`.

**Comment by cpovirk** [comment]
I just looked into why Maven can find `src.zip` locally. It turns out that, if I set `$JAVA_HOME` to some path, Java sets its `java.home` property to that path _plus_ `jre`. So the reason that we tell Maven to look for `${java.home}/../src.zip` is that that makes it look for `$JAVA_HOME/src.zip`.

It sounds like this is [expected behavior](https://stackoverflow.com/a/15279640/28465).

So the remaining question now is why this doesn't work on Travis. Maybe I should submit a change that makes `updaterelease.sh` run `mvn` with the `-X` flag and with `help:active-profiles` so that we can get some more information about what's happening there.

**Comment by cpovirk** [comment]
I submitted https://github.com/google/guava/commit/5b2694ad1c8cd9a67c84ccff48d65a499ceb028b

I meant to refer to this issue from the commit description, but I must have deleted the reference by mistake.

The next time we commit some changes to the master branch, we should have some more information in the Maven logs.

**Comment by cpovirk** [comment]
[The logs](https://travis-ci.org/github/google/guava/jobs/673078230) show neither `srczip` profile as active:

> [INFO] 
> Active Profiles for Project 'com.google.guava:guava:bundle:HEAD-jre-SNAPSHOT':
> 
> The following profiles are active:
> 
>  - standard-with-extra-repos (source: external)

Contrast to what I see on my local computer:

> [INFO]
> Active Profiles for Project 'com.google.guava:guava:bundle:HEAD-jre-SNAPSHOT':
>
> The following profiles are active:
>
>  - srczip-parent (source: com.google.guava:guava:HEAD-jre-SNAPSHOT)

In the Travis log, I see:

> Java version: 1.8.0_242, vendor: Private Build, runtime: /usr/lib/jvm/java-8-openjdk-amd64/jre

So, based on this...

https://github.com/apache/maven/blob/bf7b99ab5959d78a7370af3b56c298f60154159c/maven-embedder/src/main/java/org/apache/maven/cli/CLIReportingUtils.java#L69-L70

...I would say that `$JAVA_HOME` is /usr/lib/jvm/java-8-openjdk-amd64.

On my local computer, /usr/lib/jvm/java-8-openjdk-amd64/src.zip is a broken link until I run:

> sudo apt-get install openjdk-8-source

So we probably do just need to request `openjdk-8-source` in our Travis configuration -- maybe `addons` > `apt` > `packages`, following what [I see in Dagger](https://github.com/google/dagger/blob/a0b14342c97b398f365aff4d2654d4a6f1450a2c/.travis.yml#L6-L13)??

**Comment by cpovirk** [comment]
OK, sorry: While I was trying to find this additional information for you, I ended up figuring out what was wrong. I fixed it in https://github.com/google/guava/commit/067129401668d9be2d5fe4c3e40b8afef663b52c (plus https://github.com/google/guava/commit/9537f78cc652a4f5e77f4f418d5bbf4f49674515).

The results look good:
https://github.com/google/guava/commit/7ea12157715b2f9fc33015cdc2e8dfbb79fea388#diff-13b7cd2a718ca585bb8faf63fca868e9R205

Though I think something is still caching the old version, as I don't see the description live yet:
https://guava.dev/releases/snapshot-jre/api/docs/com/google/common/util/concurrent/ForwardingFuture.html#cancel-boolean-

(Update: I just refreshed and saw the description, so I guess it's live. It might take time to become visible to everyone.)

**Comment by developerhb** [comment]
@cpovirk 
So, the problem is solved by adding addon packages `open-jdk8-source`.

Please suggest me a new issue on which I could work as a beginner.

**Comment by cpovirk** [comment]
A couple possibilities just came up:

- Create a multi-release jar that includes a module-info.class, as discussed in https://github.com/google/guava/issues/2970#issuecomment-626684027
- Add more methods to [`Uninterruptibles`](https://guava.dev/releases/snapshot-jre/api/docs/com/google/common/util/concurrent/Uninterruptibles.html), such as those requested in #1315 and #1409.
