### ISSUE TITLE
Various cast() methods that work around JDK-6558557 are no longer necessary

### ISSUE THREAD

**Issue by aepshteyn** [google/guava#3679]
https://github.com/google/guava/blob/49f5a6332a63737dff70cf77472f9867bc7ca6eb/guava/src/com/google/common/collect/Collections2.java#L355-L358

It's probably not worth the effort to refactor all the callers of this method, but I just wanted to bring to your attention that [JDK-6558557](https://bugs.java.com/bugdatabase/view_bug.do?bug_id=6558557) was fixed in Java 1.7, so if that's the only reason for that method to exist, it's no longer necessary.  

That's all 🙂

**Comment by netdpb** [comment]
Thanks!

**Comment by Saucistophe** [comment]
I'm having trouble with the CLA, but the PR is here.

**Comment by cpovirk** [comment]
Reopening, as I've noticed that we still have similar methods in classes other than `Collections2`:
https://github.com/search?q=6558557+repo%3Agoogle%2Fguava+path%3A%2Fguava&type=Code&ref=advsearch&l=&l=

**Comment by tanmauec** [comment]
As discussed with @cpovirk, I am taking this up.
