### ISSUE TITLE
MultiMap concurrency unclear Javadoc

### ISSUE THREAD

**Issue by Katharsas** [google/guava#3682]
From https://github.com/google/guava/issues/135#issuecomment-472966705

The [javadoc for HashMultimap](https://google.github.io/guava/releases/27.0-jre/api/docs/com/google/common/collect/HashMultimap.html)  states:  

> This class is not threadsafe when any concurrent operations update the multimap. Concurrent read operations will work correctly.

Does this mean that it is thread-safe if only one thread writes to the map (while any number of threads may read simultaniously) ? The javadoc for [other MultiMap implementations](https://google.github.io/guava/releases/27.0-jre/api/docs/com/google/common/collect/ArrayListMultimap.html) is the same and i think it should be clearer on that.

**Comment by kevinb9n** [comment]
This text indeed should be revised.  The only way that concurrent reads are safe is if the last write "happens-before" every one of them.  You can't have one thread continuing to write.
