### ISSUE TITLE
Technical Support Expiration Date

### ISSUE THREAD

**Issue by Sergindra** [google/guava#3697]
Hello,

I work for a long-term project which requires strong and stable technical support for every software used.

I want to know how long you are providing technical support for Google Guava 13.0.1.

Please I appreciate so much that you can give me expiration dates for this software product or expectations of its EOL.

Thank you!
Sergi

**Comment by cpovirk** [comment]
Guava 13.0.1 is 7 years old. I wouldn't expect us to address issues with it unless they reproduce in newer versions of Guava. Even then, we are unlikely to backport any fixes to make a Guava 13.0.2.
