### ISSUE TITLE
Predicates.fromBoolean

### ISSUE THREAD

**Issue by 414owen** [google/guava#3717]
Passing a Boolean to `Functions.constant()` gives us a `Function<Object, Boolean>`, which can't be used as a `Predicate<Object>`.

It would be great to get a util to convert a `Boolean` into a `Predicate<Object>` directly, where the predicate ignores its parameter.

It might be nice to have a util to convert between `Function<A, Boolean>` and `Predicate<A>`, too...

These utils should look something like this:

```java
Predicate<Object> fromBoolean(Boolean b) {
  return arg -> b;
}

<A> Predicate<A> fromBooleanFn(Function<A, Boolean> fn) {
  return arg -> fn.apply(arg);
}
```

Thoughts?

**Comment by lowasser** [comment]
What advantage would you expect these to have over `arg -> b` and `fn::apply`?

**Comment by 414owen** [comment]
ooh, I hadn't thought of using `fn::apply` as my predicate, good pickup.

As for using `arg -> b` directly, in the same way that we provide `Functions.constant`, it gives developers a base from which to compose functions, and I think it's worth putting in the infrastructure around the identity function.

It's also arguably a nice semantic label to have, writing `arg -> <expr>` means you have to search the expression  for uses or `arg`, but `Predicates.fromBoolean(<expr>)` transfers the knowledge that the argument is ignored.

I went looking for something to create a predicate from a boolean, but if the java community doesn't have a use case for an identity predicate, fair enough, feel free to close this :)

**Comment by perceptron8** [comment]
@414owen If you want to avoid writing unused `arg`... how about `b ? Predicates.alwaysTrue() : Predicates:alwaysFalse()`? One thing to note is that `b` should be primitive `boolean`, otherwise you risk NPE.

**Comment by 414owen** [comment]
Okay, thanks for the suggestions. I wish we had more utilities to transform / create common functions, but it looks like this is a problem I shouldn't have tried to solve in pointfree style :)
