### ISSUE TITLE
ImmutableNetwork can report adjacent nodes that are not in its `nodes()`

### ISSUE THREAD

**Issue by lukeu** [google/guava#3718]
I have found that it is possible to build Networks such that this call:

            String left = // ...
            MyNode rightNode = network
                    .incidentNodes(edge)
                    .adjacentNode(new MyNode(left));

returns an object in `rightNode` that is `equal()` to, but not identical (==) to objects inside the graph, as reported by `nodes()`. This is a problem if `class MyNode` contains other data, which is to be populated in a 2nd phase traversal of the network, as later queries upon the network may not find that populated data.

For sake of keeping my code simple (less book-keeping) I construct the graph like this:

    static void addEdge(String from, String to) {
        builder.addEdge(
                new MyNode(from),
                new MyNode(to),
                from + "->" + to);
    }

The javadoc of `addEdge` states that:
  * it can silently add either node to the graph, if not present 
  * when **both** nodes are already in the graph, the operation has no effect.

It however notably leaves unspecified what happens if **one** of the nodes is already in the graph.

I would expect that for consistency, this method should notice when one node is already `equal()` to an existing node and make use of the existing one, discarding argument passed in. However it seems that it must however store this duplicate node somewhere else in its structure, leading to some inconsistent internal state.

Here's a complete example demonstrating:

    public static void main(String[] args) {
        var builder = NetworkBuilder.directed()
                .allowsParallelEdges(true)
                .<MyNode, String>immutable();

        addEdge(builder, "start1", "end");
        addEdge(builder, "start2", "end");
        addEdge(builder, "start3", "end");

        var network = builder.build();
        var edgeSet = network.edges();

        for (String edge : edgeSet) {
            String left = edge.substring(0, edge.indexOf("->"));
            var rightNode = network
                    .incidentNodes(edge)
                    .adjacentNode(new MyNode(left));
            System.out.println("From " + left + " found adjacent '" + rightNode.key
                    + "' which is a node in the graph..."
                    + "\n  by equality: " + network.nodes().contains(rightNode)
                    + "\n  by identity: " + containsByIdentity(network.nodes(), rightNode));
        }
    }

    static void addEdge(Builder<MyNode, String> builder, String from, String to) {
        builder.addEdge(
                new MyNode(from),
                new MyNode(to),
                from + "->" + to);
    }

    static boolean containsByIdentity(Set<MyNode> nodeSet, MyNode n) {
        for (MyNode m : nodeSet) {
            if (m == n) {
                return true;
            }
        }
        return false;
    }

    static final class MyNode {
        final String key;
        final Map<String,Object> properties = new HashMap<>();

        MyNode(String key) {
            this.key = key;
        }

        //
        // equals and hashCode based on 'key' only...
        //

        @Override
        public int hashCode() {
            return key.hashCode();
        }

        @Override
        public boolean equals(Object obj) {
            if (this == obj) {
                return true;
            }
            if (!(obj instanceof MyNode)) {
                return false;
            }
            MyNode other = (MyNode) obj;
            return key.equals(other.key);
        }

        @Override
        public String toString() {
            return key;
        }
    }

Which produces the following output:

```
From start1 found adjacent 'end' which is a node in the graph...
  by equality: true
  by identity: true
From start2 found adjacent 'end' which is a node in the graph...
  by equality: true
  by identity: false
From start3 found adjacent 'end' which is a node in the graph...
  by equality: true
  by identity: false
```

**Comment by nglorioso** [comment]
This is discussed in the the `GraphsExplained` wiki:
https://github.com/google/guava/wiki/GraphsExplained#elements-and-mutable-state
