### ISSUE TITLE
java.lang.NoSuchMethodError: 'java.util.stream.Collector com.google.common.collect.ImmutableList.toImmutableList()'

### ISSUE THREAD

**Issue by kumarkrish85** [google/guava#3722]
Hi,

I am using guava-25.0-jre jar in my automation framework. And i am using Open JDK 11 to trigger an automation. Every time i get this error

> java.lang.NoSuchMethodError: 'java.util.stream.Collector com.google.common.collect.ImmutableList.toImmutableList()'
at org.openqa.selenium.chrome.ChromeOptions.asMap(ChromeOptions.java:292)
at org.openqa.selenium.MutableCapabilities.merge(MutableCapabilities.java:73) 

Please help me to resolve an error

Thanks,

**Comment by kumarkrish85** [comment]
Issue resolved. Kindly ignore :)

**Comment by dacloutier-logmein** [comment]
Just curious, how did you solve it ?

I am facing the same issue.
