### ISSUE TITLE
splitToList should return ImmutableList

### ISSUE THREAD

**Issue by trejkaz** [google/guava#3728]
I find myself constantly writing things like this:

```
ImmutableList<String> parts = ImmutableList.copyOf(Splitter.on("/").split(path));
```

I'd like to use `splitToList` but it doesn't return an immutable list.

I was wondering how the Guava team justifies this method returning a mutable list. What's the use case for this list being mutable?

**Comment by trejkaz** [comment]
(Or as a good enough second option, can we at least get `splitToImmutableList` as an alternative?)

**Comment by lowasser** [comment]
`com.google.common.base` cannot depend on `com.google.common.collect`, as we can't support cyclic package dependencies.

**Comment by trejkaz** [comment]
Ah. Are we saying that Splitter probably should have been in its own package, as it does conceptually seem to deal with collections, so you'd expect it to depend on that... :(

**Comment by cpovirk** [comment]
I don't know if we'd even considered putting `Splitter` (and probably `Joiner` for symmetry) in `common.collect`. I tend to think of them as "text utilities," which feel a little more like they belong in `common.base` (alongside `Strings`, for example), but they're certainly related to collections. And I don't see any usages of `Splitter` and `Joiner` that would prevented putting them in `common.collect`. Maybe that would have been the way to go.

Nowadays it's at least possible to write `splitToStream().collect(toImmutableList())`. Not as convenient as `splitToList()`, but at least there's a way to do it without breaking the call chain.

**Comment by trejkaz** [comment]
I'm afraid I'll probably be making a `BetterSplitter` class which just has the method return the right list type in the first place.
