### ISSUE TITLE
No such bean: org.springframework.cloud.stream.binder.Binder<?, ?, ?>

### ISSUE THREAD

**Issue by Maxeh** [google/guava#3733]
Hello, in our spring boot project we get the following error when the guava dependency with version 21.0-rc1 or higher is on the classpath (the error only occurs when our junit tests are executed).

`Caused by: org.springframework.context.ApplicationContextException: Failed to start bean 'outputBindingLifecycle'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.springframework.cloud.stream.binder.Binder<?, ?, ?>' available`

When guava version 20.0 is defined in the dependencyManagement section, everything works fine. Our project uses spring boot 2.2.1.RELEASE and spring cloud Hoxton.RELEASE. Does the library expect a bean that does not exist?

For now we just use guava 20.0 but this behavior is really strange, and we were not able to fix it.

**Comment by cgdecker** [comment]
Given that the error message you've provided doesn't have any mention of Guava or any Guava type, it's unclear to me how this has to do with Guava (which doesn't have anything Spring-related in it). If you can narrow it down to a specific issue with Guava, feel free to open an issue for that, but it sounds like an issue with either Spring or your application's configuration.
