### ISSUE TITLE
When will CacheLoader use load function

### ISSUE THREAD

**Issue by haohancom** [google/guava#3737]
I want to use Cache::refreshAfterWrite so that i follow the [official tutorial](https://github.com/google/guava/wiki/CachesExplained#refresh), but "load" function made me confused.
I write a oad function and when will CacheLoader use it? I supposed when i invode Cache::getIfPresent, and the result is not in cache map, CacheLoader will invoke load and get result from DB, meanwhile write a backup into cache map. But it seems that my suspicion is wrong, when i test it. 
So when exactly is this method called?

**Comment by kevinb9n** [comment]
To ask a question, please post to stackoverflow.com with the "guava" tag. Thanks!
