### ISSUE TITLE
Cache.RemovalListener never called

### ISSUE THREAD

**Issue by Frintrop** [google/guava#3738]
Created a cache with

	cacheTempFiles = CacheBuilder.newBuilder().maximumSize(250).expireAfterWrite(15, TimeUnit.SECONDS).removalListener(new RemovalListener<String, Path>()
			{

				@Override
				public void onRemoval(RemovalNotification<String, Path> notification)
				{
					deleteTemporaryFile(notification.getValue());

				}
			}).build();

also calling every 2 minutes 	cacheTempFiles.cleanUp(); 

but onRemoval never called.

**Comment by kevinb9n** [comment]
It is *possible* that there is a bug here, but it is more likely a misunderstanding of how these features work. I would recommend asking this question on stackoverflow. If the feeling there is that it's a bug, it would help a lot if you could provide a more complete code example. Thanks!
