### ISSUE TITLE
 Futures.immediateFailedCheckedFuture in version 28.2-jre is undefined

### ISSUE THREAD

**Issue by gilv** [google/guava#3762]
I updated guava to 28.2 and get issues with my code that previously worked with 27.1

"The method immediateFailedCheckedFuture(InterruptedException) is undefined for the type Futures"

Can someone suggest how to adapt this to  28.2-jre

 try {
      ....
    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      return Futures.immediateFailedCheckedFuture(e);
    }

thanks

**Comment by netdpb** [comment]
`CheckedFuture` and related utilities were deprecated in v22 (2017) and removed in v28.

I'm not sure what you're using `CheckedFuture` for there; can you return `Futures.immediateFailedFuture(e)` instead?

From the deprecation note:

> `CheckedFuture` cannot properly support the chained operations that are the primary goal of `ListenableFuture`. `CheckedFuture` also encourages users to rethrow exceptions from one thread in another thread, producing misleading stack traces. Additionally, it has a surprising policy about which exceptions to map and which to leave untouched. Guava users who want a `CheckedFuture` can fork the classes for their own use, possibly specializing them to the particular exception type they use. We recommend that most people use `ListenableFuture` and perform any exception wrapping themselves. This class is scheduled for removal from Guava in Feburary 2018.

**Comment by netdpb** [comment]
I'm going to close this issue for now.
