### ISSUE TITLE
Swarmup RateLimiter seems not work for large permitsPerSecond

### ISSUE THREAD

**Issue by hujianxin** [google/guava#3770]
I need to limit the bandwidth of the file downloading, and limit the bandwidth to 50MB/s, but the real download bandwidth can only reach 7MB/s.

```java
@RestController
class HelloWorldController {
    @GetMapping("/")
    public String sayHello() {
        return "hello world";
    }

    @GetMapping("/download")
    public ResponseEntity<Resource> download() throws FileNotFoundException {
        RateLimiter rateLimiter = GuavaRateLimiter.create(52428800L, 500, TimeUnit.MILLISECONDS)
        FileInputStream in = new FileInputStream("/home/hujianxin/Downloads/officesp2010-kb2687455-fullfile-x64-en-us.exe");
        InputStreamResource resource = new InputStreamResource(new InputStream() {
            @Override
            public int read() throws IOException {
                rateLimiter.acquire();
                return in.read();
            }

            @Override
            public int read(byte[] b) throws IOException {
                rateLimiter.acquire(b.length);
                return in.read(b);
            }

            @Override
            public int read(byte[] b, int off, int len) throws IOException {
                rateLimiter.acquire(len);
                return in.read(b, off, len);
            }
        });
        return ResponseEntity.ok().body(resource);
    }
}
```

**Comment by hujianxin** [comment]
If I remove the rateLimiter code, the real bandwidth can reach to 200MB/s

**Comment by OLPMO** [comment]
Could you tell me what is the GuavaRateLimiter?Or you could provide a complete, minimal, verifiable sample that reproduces the problem?

**Comment by hujianxin** [comment]
@hujianxin sorry for that, GuavaRateLimiter is a RateLimiter copy with renaming RateLimiter to GuavaRateLimiter, I did this because of some wierd reason. But anyway, I can repreduce this issue using the real Guava RateLimiter.

**Comment by cgdecker** [comment]
One thing I'll note is that you're acquiring a number of permits equal to the number of bytes you're _requesting_ in each operation, not necessarily the number that is actually being read. Imagine that the buffer being passed to `read(byte[] b)` is 10 MB but the underlying `InputStream` is only actually reading 4 KB into it each call. Your `RateLimiter` is acting as if it read 10 MB.

**Comment by cgdecker** [comment]
I think what I said above is likely the root of the issue you're having. If you have evidence there's an issue with `RateLimter` here, feel free to reopen.
