### ISSUE TITLE
in graphs need api for get target node of edge

### ISSUE THREAD

**Issue by igoryan17** [google/guava#3776]
To perform relaxation procedure of Dijkstra algorithm need get out edges of reached node and these targets nodes

**Comment by jrtom** [comment]
Issues like this are best [asked on StackOverflow](https://stackoverflow.com/questions/ask?tags=guava+java+graph); please ask them there in future.

Assuming that `graph` is directed:

Given an already extracted outgoing `edge`

If `graph` is a `[Value]Graph`, then `edge` is an `EndpointPair`, and you can just call `target`:

```
N target = edge.target();
```

If `graph` is a `Network`, then `edge` is a first-class object, and you must first get its endpoints:

```
N target = graph.incidentNodes(edge).target();
```

If `graph` is _not_ directed, then given your original node `n` for which you acquired your outgoing edge, just ask the `EndpointPair` for the corresponding "other" node:

```
N otherNode = edge.adjacentNode(n);
```

Hope this helps.
