### ISSUE TITLE
Guava 28.2 adds DoNotMock Annotation to PeekingIterator which causes Jackson to fail to serialize

### ISSUE THREAD

**Issue by mglazer** [google/guava#3779]
Example code:

```
Iterator<SomeObject> data = new ArrayList<>().iterator();
PeekingIterator<SomeObject> it = Iterators.peekingIterator(data);

ObjectMapper mapper = new ObjectMapper();
mapper.writeValue(outputStream, it);
```

On Guava 28.1-jre, this works perfectly fine, and it gets serialized to an array of objects.

On Guava 28.2-jre, this serializes an empty object `{}`. This is because of the addition of `DoNotMock` in:

https://github.com/google/guava/commit/4eea0f79c27864039a653ec4ca09ef7585e439fc

This causes Jackson to report that there exist known annotations on the class, which makes it attempt to serialize the class as a Bean rather than falling back to an Iterator:

https://github.com/FasterXML/jackson-databind/blob/master/src/main/java/com/fasterxml/jackson/databind/ser/BeanSerializerFactory.java#L367

I honestly don't know if I should file this as a Guava or a Jackson issue, however, since this issue started when we upgraded to Guava 28.2-jre, it seems like there is potentially some arguable regression in Guava.

**Comment by kevinb9n** [comment]
Jackson's reaction to this annotation seems unwarranted/erroneous. I believe Guava should be free to add annotations like this when necessary.
