### ISSUE TITLE
EvictingQueue should offer a blocking pull

### ISSUE THREAD

**Issue by thhart** [google/guava#3791]
Would be nice to have a blocking fetch/pull until an element is available.

**Comment by Koellewe** [comment]
I think what you want here is probably a new type of `Queue` implementation. The (inherited) definitions for `EvictingQueue`'s `poll()` and `remove()` methods are to be non-blocking. As such I would suspect that making them block would cause breaking changes.

**Comment by kluever** [comment]
`EvictingQueue` is a bounded, non-blocking queue.

If you want a bounded, blocking queue, check out `ArrayBlockingQueue`, `LinkedBlockingDeque`, or `LinkedBlockingQueue`.

**Comment by thhart** [comment]
Sorry folks but I can not follow your reasoning. Remove() would break nothing and is not blocking nowhere especially not in LinkedBlockingDeque. Poll() is not contained in EvictingQueue yet and so it would not break anything.
