### ISSUE TITLE
ListeningExecutorService.invokeAll() not returning List of ListenableFutures

### ISSUE THREAD

**Issue by leventov** [google/guava#3792]
Is there any reason why `ListeningExecutorService.invokeAll()` is not overridden to return `List<ListenableFuture<T>>`? It would allow to directly pass the result into `Futures.allAsList()`.

**Comment by szarnekow** [comment]
It is not possible to use `List<ListenableFuture<T>>` as the return type of the overriding method since the return types would not be compatible. `List<ListenableFuture<T>>` is not a subtype of `List<Future<T>>`
