### ISSUE TITLE
ImmutableMap.ofEntries()

### ISSUE THREAD

**Issue by orionll** [google/guava#3803]
Currently, `Immutable.of()` supports only up to 5 key-value pairs. I suggest adding a new method `ImmutableMap.ofEntries(Entry<K, V>...)` similar to [Map.ofEntries()](https://docs.oracle.com/en/java/javase/13/docs/api/java.base/java/util/Map.html#ofEntries(java.util.Map.Entry...)) that appeared in Java 9. This will allow creating `ImmutableMap` with any number of key-value pairs.

I also suggest making `ImmutableMap.entryOf(K, V)` public so it can be used in `ofEntries()`:

```
ImmutableMap.ofEntries(
    ImmutableMap.entryOf("a", 1),
    ImmutableMap.entryOf("b", 2));
```

**Comment by dimo414** [comment]
Why is this pattern preferable to just using the `Builder`?

```java
new ImmutableMap.Builder<String, Integer>()
    .put("a", 1)
    .put("b", 2)
    .build();
```

**Comment by kluever** [comment]
+1 to @dimo414 

Also, if you have entry instances for some reason, then how about:
`new ImmutableMap.Builder<K, V>().put(entry).put(entry).put(entry).build();`

Re. `ImmutableMap.entryOf(K, V)`, see `Maps.immutableEntry(K, V)` or `Map.entry(K, V)` (in Java 9+).

**Comment by orionll** [comment]
Using `ImmutableMap.Builder` is cumbersome. `ImmutableMap.ofEntries` is much more straightforward:

```
ImmutableMap.ofEntries(immutableEntry("a", 1), immutableEntry("b", 2));
```
```
new ImmutableMap.Builder<String, Integer>().put("a", 1).put("b", 2).build();
```
The amount of ceremony is much less in the first example. Also, it doesn't require type arguments.

**Comment by kluever** [comment]
How about `ImmutableMap.copyOf(Maps.ofEntries(...))`?

**Comment by dimo414** [comment]
I have to disagree that `ofEntries()` involves less ceremony than a builder pattern. Notably you're assuming a static import of `immutableEntry()` (which would only be discoverable to a caller by reading documentation), and constructing `Entry` objects that will immediately be discarded. A fluent API is easier to work with (IDEs can provide autocomplete) and builders are more standard and unsurprising.

While I agree it's a little obnoxious to have to swap from `ImmutableMap.of()` to a builder past five key-value pairs, the resulting code is clearer than a longer `of(...)` overload.

**Comment by orionll** [comment]
> ... and constructing Entry objects that will immediately be discarded

In `ImmutableMap.Builder.put()` and `ImmutableMap.of()` there are also temporary `Entry` objects that are discarded.

**Comment by orionll** [comment]
`ImmutableMap.ofEntries()` has been added in https://github.com/google/guava/commit/cd3b4197fb523bf26f9122492915006ad306b3f3. It's now available since [Guava 31](https://github.com/google/guava/releases/tag/v31.0).
