### ISSUE TITLE
Some methods' description of behavior for different equivalence relations is unclear

### ISSUE THREAD

**Issue by ivangreene** [google/guava#3808]
Some methods dealing with Sets declare that their results are undefined when passing Sets that are based on different equivalence relations, and give HashSet as an example. Unless I'm missing something, I believe that HashSet is not an example of this and should be removed from the examples (TreeSet and the keySet of IdentityHashMap are, however, examples of Sets using different equivalence relations.)

An example from Sets.java:
https://github.com/google/guava/blob/87a383e06a30c89e1e07689c2ea7a005a1379743/guava/src/com/google/common/collect/Sets.java#L721-L723

**Comment by perceptron8** [comment]
@ivangreene I believe it means that HashSet is based on different equivalence relation than TreeSet and so on. At least that's how I understand it.

**Comment by cpovirk** [comment]
Yep, that's the idea. We should definitely make this clearer. It's especially weird when we list 3 classes for a method that takes only 2 parameters.

**Comment by ivangreene** [comment]
Ok this makes sense. So this would mean that results _are_ defined if using for example two TreeSets with a common Comparator? I would agree and say this is not very clear from the current documentation

**Comment by ivangreene** [comment]
I updated the title to match more of what the problem is. Let me know if a separate issue should be opened

**Comment by shireeshaBongarala** [comment]
How about this one? 
Would be happy to raise a PR if this looks good.
 > Results are undefined if set1 and set2 are sets based on different equivalence relations (as the pairs (HashSet, TreeSet), (keySet of an IdentityHashMap, TreeSet), and (HashSet, keySet of an IdentityHashMap) all are.
