### ISSUE TITLE
Why RateLimiter is still Beta

### ISSUE THREAD

**Issue by MrXionGe** [google/guava#3813]
package: com.google.common.util.concurrent
class: RateLimiter
### So I wonder why RateLimiter has always been Beta.

**Comment by JakeWharton** [comment]
Dupe of #2797

**Comment by MrXionGe** [comment]
@JakeWharton 
It looks like we don't have an exact plan yet, do we?

**Comment by BEE-JN** [comment]
RateLimiter is still be beta in 31.0, but it seems work fine.
