### ISSUE TITLE
Typo in StringsExplained wiki

### ISSUE THREAD

**Issue by andreibelcin** [google/guava#3817]
I was reading through the wiki and I saw that on [this page](https://github.com/google/guava/wiki/StringsExplained) there's a "[TOC]" tag showing up, probably just a typo in the wiki's markdown.

**Comment by nglorioso** [comment]
Fixed as of https://github.com/google/guava/wiki/StringsExplained/6bbf87f0d94a451017e8a77b46ad0b47af2f0514
