### ISSUE TITLE
Remove @Beta from ArrayTable

### ISSUE THREAD

**Issue by amanmehara** [google/guava#3821]

**Comment by kluever** [comment]
FWIW, the non-inherited API for `ArrayTable` is:

- `public V at(int rowIndex, int columnIndex) { ... }`
- `public V set(int rowIndex, int columnIndex, @Nullable V value) { ... }`
- `public V erase(@Nullable Object rowKey, @Nullable Object columnKey) { ... }`
- `public void eraseAll() { ... }`
- `public ImmutableList<C> columnKeyList() { ... }`
- `public ImmutableList<R> rowKeyList() { ... }`
- `public V[][] toArray(Class<V> valueClass) { ... }`

(These are the API's we'd need to consider when removing `@Beta` from the type -- although we could leave these 7 APIs as `@Beta` and remove `@Beta` from the type itself...)

**Comment by ananthshenoy** [comment]
@kluever Can I pick this up?

**Comment by kluever** [comment]
Unless this is actively causing trouble for someone, this is a fairly low priority issues for us.

Use of `@Beta` APIs should only be a concern when the types are exposed across API boundaries, and it seems unlikely that someone would do so with the `ArrayTable` type (you'd most likely expose a `Table`).

**Comment by cpovirk** [comment]
Questions around `ArrayTable` include:

- Should it be renamed? Users who are familiar with `List` and `ArrayList` might expect for `ArrayTable` to be "just like that but for `Table`." But it's not.
- Should it not implement `Table` at all (though perhaps still provide a `Table` _view_ for users who really need it)? Reasoning: Some of the `Table` methods are odd on `ArrayTable`, notably [`clear()`](https://guava.dev/releases/snapshot-jre/api/docs/com/google/common/collect/ArrayTable.html#clear--) and [`remove(...)`](https://guava.dev/releases/snapshot-jre/api/docs/com/google/common/collect/ArrayTable.html#remove-java.lang.Object-java.lang.Object-) -- not to mention `ImmutableTable.copyOf(arrayTable)`, which will throw if any cells are empty.

(Putting those two together, maybe it should be "`Grid`" or something.)

Additionally, I'll contradict Kurt on one point: Even when types are _not_ exposed in API boundaries -- that is, even when they're used internally only -- using `@Beta` APIs can _still_ lead to breakages for any code that might run with a newer version of Guava than it's compiled against. This is the reason for the [warning](https://github.com/google/guava#important-warnings):

> If your code is a library itself (i.e., it is used on the CLASSPATH of users outside your own control), you should not use beta APIs unless you [repackage](https://github.com/google/guava/wiki/UseGuavaInYourBuild#what-if-i-want-to-use-beta-apis-from-a-library-that-people-use-as-a-dependency) them.

**Comment by cpovirk** [comment]
We did this a while back.
