### ISSUE TITLE
License issue with GPL in Checker Qual

### ISSUE THREAD

**Issue by MichaelHornung** [google/guava#3838]
Hi,

we are using google guave as a deep dependeny in our microservices. There are issues in our foss compliance tool FOSSA after scanning.
![image](https://user-images.githubusercontent.com/53259450/78009207-f42e5600-7340-11ea-83e6-182bb8209eaf.png)

![image](https://user-images.githubusercontent.com/53259450/78009360-36f02e00-7341-11ea-90ce-a3904973b635.png)

Checker Qual Framework includes a copy left and therefore i think also guava has this copy left effect.
Here is the license of Checker Qual: https://github.com/typetools/checker-framework/blob/master/LICENSE.txt
Why can you license guava under Apache 2.0 although there are dependencies with copy left included?

Thankx!
Michael

**Comment by cpovirk** [comment]
Lines 9-20 of the license you linked to explain that checker-qual is under the MIT license. Maybe the tool you're using could be modified to look for a license elsewhere (jar? pom? I haven't checked where checker-qual has one), or maybe you'll need a special case for this artifact.
