### ISSUE TITLE
Enums.getIfPresent returns null for Regions Enum in AWS SDK

### ISSUE THREAD

**Issue by jaympatel-sf** [google/guava#3848]
I am not sure if this should be an issue in Guava or AWS SDK. 

Enums.getIfPresent(Regions.class, "us-west-2") doesnt work right now because Guava uses Enum.name() as hashmap key. 
Reference here: https://github.com/google/guava/blob/master/guava/src/com/google/common/base/Enums.java#L81

**Comment by nglorioso** [comment]
`Enums.getIfPresent` uses the enum `name()` (which would succeed in looking up [`"US_WEST_2"`](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/regions/Regions.html#US_WEST_2)), not the [`getName()`](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/regions/Regions.html#getName--) property which is defined by the Regions enum: 

It looks like the Regions enum has a method to give you the `Region` corresponding to the friendly name (`Regions.fromName(...)`)

**Comment by jaympatel-sf** [comment]
Yes, thanks, I have used it. Was wondering if we can fix this?
