### ISSUE TITLE
when oldMaxPermits == 1.0D / 0.0 

### ISSUE THREAD

**Issue by njsunjian** [google/guava#3850]
com.google.common.util.concurrent.SmoothRateLimiter  line 71

        void doSetRate(double permitsPerSecond, double stableIntervalMicros) {
            double oldMaxPermits = this.maxPermits;
            this.maxPermits = this.maxBurstSeconds * permitsPerSecond;
            if (oldMaxPermits == 1.0D / 0.0) {
                this.storedPermits = this.maxPermits;
            } else {
                this.storedPermits = oldMaxPermits == 0.0D ? 0.0D : this.storedPermits * this.maxPermits / oldMaxPermits;
            }
        }

**Comment by kevinb9n** [comment]
Unless I am misunderstanding what is really being requested here, the code seems clearer as it is.

**Comment by theguynext** [comment]
Just waiting on a confirmation from my lawyer regarding a woo technological advance

**Comment by theguynext** [comment]
Litigations until fiesal and google approve the be ai aspects

**Comment by theguynext** [comment]
And Microsoft
