### ISSUE TITLE
Release 28.2-jre on maven contains a spurious file

### ISSUE THREAD

**Issue by netomi** [google/guava#3861]
During some minimization efforts on the previous released version 28.2-jre, I noticed a spurious file in the published version on maven central:

```
tn@proteus:~/Downloads$ unzip -l guava-28.2-jre.jar  | grep swp
    16384  2019-09-18 17:29   com/google/common/collect/.ImmutableListMultimap.java.swp
```

Looks like an transient artefact from an editor that slipped into the release. It is not present in the android variant or in older releases (I checked at least 28.1-jre).

Minor things that can not be changed anymore but maybe a trigger for improvement of future releases.

Edit: I noticed that 29.0 has been released that does not contain this spurious file.

**Comment by cpovirk** [comment]
Thanks -- will fix.

**Comment by netomi** [comment]
Super, thanks!
