### ISSUE TITLE
SHA256 HashFunction.hashBytes(ByteBuffer) Does Not Work

### ISSUE THREAD

**Issue by GuyPaddock** [google/guava#3867]
It seems that either the `com.google.common.hash.HashFunction.hashBytes(java.nio.ByteBuffer)` method does not function properly, or that it functions differently than I'd expect given the interface.

Consider this code:
```java
final ByteBuffer buffer1 = ByteBuffer.allocate(4),
                 buffer2 = ByteBuffer.allocate(4);

buffer1.put((byte)0xAB);
buffer1.put((byte)0xCD);
buffer1.put((byte)0x12);
buffer1.put((byte)0x34);

buffer2.put((byte)0x12);
buffer2.put((byte)0x34);
buffer2.put((byte)0xAB);
buffer2.put((byte)0xCD);

System.out.println(Hashing.sha256().hashBytes(buffer1).toString());
System.out.println(Hashing.sha256().hashBytes(buffer1.array()).toString());

System.out.println(Hashing.sha256().hashBytes(buffer2).toString());
System.out.println(Hashing.sha256().hashBytes(buffer2.array()).toString());
```

The output is this (with Guava 28.2-jre):
```
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
777907d54b6a4502bd654cb4ae81c5f727013b5e3b93cd8b53d721344269d3b0
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
9b11457aa29d65e4940b67b7da16bd370d29bf6a3247a28066f93ac407b8b811
```

But I would expect this:
```
777907d54b6a4502bd654cb4ae81c5f727013b5e3b93cd8b53d721344269d3b0
777907d54b6a4502bd654cb4ae81c5f727013b5e3b93cd8b53d721344269d3b0
9b11457aa29d65e4940b67b7da16bd370d29bf6a3247a28066f93ac407b8b811
9b11457aa29d65e4940b67b7da16bd370d29bf6a3247a28066f93ac407b8b811
```

**Comment by nglorioso** [comment]
I noticed a subtle bug in your sample code: The `ByteBuffer`s need to be `flip()`-ped before passing it to the hasher function.

In your code, both `ByteBuffer` instances have no data to read, resulting in the same `SHA256("")`.

Since using `ByteBuffer.array()` returns the underlying array, the results for lines 2 and 4 are appropriately different.

**Comment by GuyPaddock** [comment]
Just wanted to thank you, @nglorioso! That was exactly the issue I was having. I hadn't used `ByteBuffer` much previously; now we use it a lot, and this was an important point.
