### ISSUE TITLE
[QUESTION] Guava filter behaviour

### ISSUE THREAD

**Issue by evivar** [google/guava#3889]
When using guava to filter a list p.e, the behaviour and the complexity are the same as using a foreach loop and check the conditions inside it?

**Comment by cpovirk** [comment]
> [StackOverflow: Ask "how-to" and "why-didn't-it-work" questions](https://stackoverflow.com/questions/ask?tags=guava+java)

**Comment by cpovirk** [comment]
Sorry, I was a little quick there: Your question isn't exactly a how-to. Still, I think this is better suited to a Q&A forum than the issue tracker.

**Comment by evivar** [comment]
Okey, don't worry, I understand it, but I didn't know where to ask the
question so I put it on the issues



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Remitente
notificado con
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
05/05/20
17:17:11
