### ISSUE TITLE
PowerSet.equals depends on set's iteration order

### ISSUE THREAD

**Issue by RyanSkonnord** [google/guava#3890]
If `com.google.common.collect.Sets.powerSet` is called with two different sets that contain the same elements but in a different iteration order, the returned power sets will also contain the same elements but in a different iteration order. Therefore, `Set.equals` on those power sets is `true`, but `com.google.common.collect.Sets.PowerSet.equals` incorrectly returns `false`.

**Comment by cpovirk** [comment]
Wow, almost 7 years old! Nice find.

**Comment by RyanSkonnord** [comment]
Thanks! :grin:

**Comment by mattysday** [comment]
👍👍👍👍😀😀
