### ISSUE TITLE
InternetDomainName.topDomainUnderRegistrySuffix() / topPrivateDomain() do not correctly handle .bw and .gh domains

### ISSUE THREAD

**Issue by mads1980** [google/guava#3896]
Run the following test program:

```
	public static void main(String[] args) throws Exception {
		String domain = "ns1.orange.net.bw";
		InternetDomainName idn = InternetDomainName.from(domain);
		System.out.println(idn.topDomainUnderRegistrySuffix());
		System.out.println(idn.topPrivateDomain());
	}
```

Output:

```
net.bw
net.bw

```
Whereas output should be:

```
orange.net.bw
orange.net.bw

```

Wikipedia indicates the following:
https://en.wikipedia.org/wiki/.bw

"Most current registrations are at the third level beneath second-level names such as co.bw and org.bw, but some second-level registrations also exist."

2nd level domains
.org.bw – Botswana organizations[3]
.net.bw – Botswana Network service providers
.ac.bw – Botswana academic and tertiary societies[4]
.co.bw – general use by Botswana and non-Botswana persons and entities[5]
.gov.bw – Botswana government & its departments and entities[6]

It is possible that other lesser-known country TLDs suffer from similar behaviour. Some testing and initial review shows that the following TLDs also have similar issues:
https://en.wikipedia.org/wiki/.gh

**Comment by cpovirk** [comment]
Thanks. We take our data directly from the Mozilla Public Suffix List.

I see a relevant-looking comment in the public-suffix list's section about `bw`:
`// list of other 2nd level tlds ?`

So they probably suspect that the list is incomplete.

You can [see how to contribute changes to the list](https://github.com/publicsuffix/list/wiki/Guidelines). The Guava master branch will pick up any changes to the official list, usually about every 6 weeks, after which they'll appear in a release.

**Comment by mads1980** [comment]
Thanks, we have now contributed to the Mozilla Public List thanks to your guidance.
