### ISSUE TITLE
Question: How to invalidate certain key in reload?

### ISSUE THREAD

**Issue by vonjackustc** [google/guava#3903]
I want to make a special cache, refresh the key / value every 10 minutes use refreshAfterAccess mechanism.
In the reload function of CacheLoader, I want to analyze the old value. If the value satisfy certain condition, invalidate the key.
How can I do this?
Thank you very much!

**Comment by kluever** [comment]
Please ask "how-to" and "why-didn't-it-work" questions on StackOverflow.com with the tag `guava`.
