### ISSUE TITLE
Feature Request: Time based evicting queue

### ISSUE THREAD

**Issue by jimmyzzxhlh** [google/guava#3914]
Hi, 

Our team is looking into a data structure that meets the following need:
- Allow storing a collection of values
- Each value will be expired and removed from the collection after a period of time. 
- Callers can grab one value from the collection and remove it in a thread safe way, i.e. two callers cannot grab the same value object from the collection at the same time (Bonus point: allow grabbing the value that was inserted at the earliest/latest time).

Example use case: Our dependency service requires us to make a request and get an authorization token, and then the token can be used to make a call to their API. However the latency is high if every client call needs two calls to our dependency service. Therefore we want to maintain a pool of tokens in our service, with expiration time specified. In this way when a client calls our API, we just need to grab a token from the pool and make a call to our dependency service. We want to make sure no two clients are using the same token. 

It seems like there is no solution that completely fits our need, and the closest solutions that we can find are:
- Guava LoadingCache: It supports expiring elements, but it does not support polling and removing an element from the cache in one shot. 
- Java DelayQueue: It only supports polling from the queue for expired elements, so we need to implement logic for evicting all expired elements and polling the first non-expired element. 

Essentially we need a time based evicting queue and a thread-safe poll() function.

**Comment by Maaartinus** [comment]
IIUIC a simple `ConcurrentLinkedQueue` storing both the value and expiration time would do. The consumers simply `poll` the oldest entry, repeating if expired. This way all the expired tokens get removed whenever there's at least one consumer. As you deal with a remote API, the performance should be more than good enough.

I'm assuming you can put the entries in in proper order. Otherwise, you'd need a `PriorityBlockingQueue`.

**Comment by jimmyzzxhlh** [comment]
@Maaartinus Thanks for the idea. I think the challenge here is that when two threads are polling from the same queue we want to ensure that they do not get the same token. `ConcurrentLinkedQueue` seems to only guarantee weak iterator consistency.

> Iterators are weakly consistent, returning elements reflecting the state of the queue at some point at or since the creation of the iterator. They do not throw ConcurrentModificationException, and may proceed concurrently with other operations. Elements contained in the queue since the creation of the iterator will be returned exactly once.

That being said I guess we can potentially create a synchronized wrapper for `poll()` as a workaround.

**Comment by Maaartinus** [comment]
@jimmyzzxhlh `Iterator` consistency doesn't matter as you don't iterate, just poll. And while I can see `ConcurrentLinkedQueue#poll` mentioned explicitly, I'm sure, it won't ever return one element twice - this would be unusable.
