### ISSUE TITLE
Java “Resources.asByteSource(URI” via http proxy without using system.setProperty or JVM wide options

### ISSUE THREAD

**Issue by tooptoop4** [google/guava#3916]
https://github.com/ebyhr/presto-flex/blob/master/src/main/java/org/ebyhr/presto/flex/operator/CsvPlugin.java#L48 has an example of reading data from a URL, how to make it connect to the URL via a corporate HTTP proxy? Guava docs were not helpful, using system.setProperty was able to go via the proxy but issue is that it affected other classes that should not go via the proxy

**Comment by jbduncan** [comment]
I'm pleasantly surprised that `Resources::asByteSource(URL)` actually works for URLs that don't point to resources on the classpath. I'm not sure that using it for HTTP URLs was an intended use case.

Have you considered using Java's `HttpClient` (for Java 11+) or a third party library like OkHttp or Apache Commons for downloading something over a proxy, and wrapping the operation in a custom `ByteSource` if needed?

**Comment by jbduncan** [comment]
I've done some more research, and this StackOverflow page explains why using `Resources` methods for URLs other than those pointing to the classpath is not ideal: https://stackoverflow.com/questions/21288139/using-guavas-resources-readlines-to-read-from-an-http-service

**Comment by netdpb** [comment]
As the documentation says, `Resources` is not meant to be used for loading from arbitrary URLs that aren't part of the class path.

I'll close this issue.
