### ISSUE TITLE
Remove section on Emulating Java 7 multi-catch and rethrow

### ISSUE THREAD

**Issue by elharo** [google/guava#3918]
https://github.com/google/guava/wiki/ThrowablesExplained

This is no longer relevant now that Java 7 is the minimum supported version for Guava

**Comment by ddunig2** [comment]
If not already taken, may I take this issue?

**Comment by netdpb** [comment]
That whole doc should be updated to reflect new methods and remove references to deprecated methods.

**Comment by netdpb** [comment]
@ddunig2 If the task is just to remove a section, it's easier for us to just do so internally. If the task is to update what should remain, then that's not trivial. Let us remove the obsolete sections, and then if you want to propose some rewording, that would be okay.

**Comment by netdpb** [comment]
We have prepared an internal change. @ddunig2, take a look at that before you rewrite anything.

**Comment by ddunig2** [comment]
@netdpb, I am still kind of new-ish to open source, where would I find these internal changes

**Comment by netdpb** [comment]
Sorry. For these projects we make all changes on our internal VCS, and then push them to GitHub on a regular basis. Even PRs that others write go through that process.

In any case, the doc has now been updated. Please take a look, and if you still want to suggest changes, please do.
