### ISSUE TITLE
ImmutableValueGraph.Builder does not respect iteration order

### ISSUE THREAD

**Issue by oliviercailloux** [google/guava#3927]
The [doc](https://github.com/google/guava/wiki/GraphsExplained#immutable-implementations), if I understand it correctly, states that iteration order of successors nodes should follow insertion order in the following case.

```
Person root = new Person("ROOT");
Person personLeft = new Person("l");
Person personRight = new Person("r");
ImmutableValueGraph.Builder<Person, Integer> builder = ValueGraphBuilder.directed().immutable();
builder.putEdgeValue(root, personLeft, 1);
builder.putEdgeValue(root, personRight, 2);
ImmutableValueGraph<Person, Integer> tree = builder.build();
Iterator<Person> iterator = tree.successors(root).iterator();
LOGGER.info("First successor of root: {}.", iterator.next());
LOGGER.info("Second successor of root: {}.", iterator.next());
```
I expect, thus, to see “l” as the first successor of root, and “r” as the second one. But I observe the reverse instead.

Here is the `Person` class.
```
private static class Person {
	String name;

	public Person(String name) {
		this.name = name;
	}

	@Override
	public String toString() {
		return name;
	}
}
```
(This does not happen, on my computer where I tested this, with `String` instead of `Person`, or with `Graph` instead of `ValueGraph`.)

**Comment by oliviercailloux** [comment]
Thanks. I had seen the issue, but didn’t look at it carefully because it seemed irrelevant to the case of `Immutable` structures.

I still believe these discussions to be only vaguely related to my case, as I deal with immutable graph builders, which, as you quoted, should not be affected by the change.

Anyway, it’s quite possible that closing this for now in wait that someone can reproduce the problem would be a reasonable reaction.

**Comment by perceptron8** [comment]
> I still believe these discussions to be only vaguely related to my case, as I deal with immutable graph builders, which, as you quoted, should not be affected by the change.

@oliviercailloux Please review linked javadoc once more. Immutable graph builders _are_ affected. Before 29.0, all incident edges were implicitly `ElementOrder.unordered()`. There were no guarantees at all. Since 29.0 once can choose between `ElementOrder.unordered()` (which is the default for mutable graph / network builders) and `ElementOrder.stable()` (which is the default for immutable graph / network builders).
