### ISSUE TITLE
com.google.guava:guava version is compatible with Gradle 6.3

### ISSUE THREAD

**Issue by ramakrishnakaushik97** [google/guava#3935]
which com.google.guava:guava version is compatible with Gradle 6.3 ?
Can you please provide the compatibility matrix

**Comment by jbduncan** [comment]
What do you mean by "compatible"? All recent versions of Gradle (maybe even as far back as the oldest version) should be able to import Guava as a Java dependency, so I feel like I'm missing something here. 🤔

**Comment by aniketvsawant** [comment]
@jbduncan Even i am facing issue with Gradle 5.6 with Guava 16.0.1. 
Getting error as "_tried to access method com.google.common.io.Files.fileTreeTraverser()Lcom/google/common/collect/TreeTraverser;_". So compatibility matrix would help to resolve such issues.

**Comment by jbduncan** [comment]
@aniketvsawant Guava 16 came out a long time ago. Have you read the README.md file in this project for information on what version of Guava to use now? :)

**Comment by jbduncan** [comment]
I ask because if you upgrade your version of Guava, you'll most likely find that this error will disappear.

**Comment by aniketvsawant** [comment]
@jbduncan I tried all guava versions till 29.0-jre but no luck. Same error for all versions with Gradle 5.6. Interestingly Guava 16 working with Gradle 4.4.
