### ISSUE TITLE
Guava 16.0.1 issue with Gradle 5.6

### ISSUE THREAD

**Issue by aniketvsawant** [google/guava#3938]
Hi Team, I am having issue with Guava 16.0.1 using Gradle 5.6 in Spring Boot 2.2 Application.

Getting error as below -
`
tried to access method com.google.common.io.Files.fileTreeTraverser()Lcom/google/common/collect/TreeTraverser;.
` 

Gradle compatibility matrix would help to resolve such issues.

**Comment by jbduncan** [comment]
@aniketvsawant See https://github.com/google/guava/issues/3935#issuecomment-645851521.

**Comment by aniketvsawant** [comment]
Issue got resolved with below snippet 

    configurations.all {
        resolutionStrategy.eachDependency {details ->
            if (details.requested.group == 'com.google.guava') {
                details.useVersion "23.6-jre"
            }
        }
    }
