### ISSUE TITLE
Remove inappropriate comment from BloomFilter#expectedFpp()

### ISSUE THREAD

**Issue by danasilver** [google/guava#3943]
Opening an issue to propose removing [a comment](https://github.com/google/guava/blob/0ad38b88bd92319508ebc0b28bab5be1fbf1891f/guava/src/com/google/common/hash/BloomFilter.java#L180) in the `c.g.c.hash.BloomFilter#expectedFpp()` method. The comment refers to the catchphrase from the song ["O.P.P." by Naughty by Nature](https://en.wikipedia.org/wiki/O.P.P._(song)), which concerns sexual infidelity (see the Wikipedia entry for the acronym). As such, I believe it's inappropriate and unnecessary in the Guava source code. If there's consensus around removing it, I can create a PR with the change.

**Comment by kevinb9n** [comment]
Thank you for spotting it, it certainly is completely unnecessary. I can more easily remove it from my side.

**Comment by danasilver** [comment]
Absolutely, and thanks for taking care of it!

**Comment by kluever** [comment]
Will be fixed in the next push.
