### ISSUE TITLE
Remove @Beta from Multimaps.toMultimap()

### ISSUE THREAD

**Issue by sergeivisotsky** [google/guava#3957]
In some places of our project we are using toMultimap() method which is marked as @Beta and consequently is considered as an unstable API.

See:
https://github.com/google/guava/blob/d7a26416109381a6770681bc6c299567615e8341/guava/src/com/google/common/collect/Multimaps.java#L108

So. There is already 29.0 version of Google Guava. When does it gonna be considered as a "stable API"?
I would provide you more examples of  similar "unstable API" methods from Guava...

**Comment by netdpb** [comment]
Thanks for the request. Please note, as described [here](https://github.com/google/guava/wiki/PhilosophyExplained#beta-apis), Guava's beta APIs are well-tested. If your project is an application and not a library that is meant to be included in a different application, it's safe to use them.

**Comment by sergeivisotsky** [comment]
@netdpb Yes, we use it in proprietary production grade product.

**Comment by sergeivisotsky** [comment]
@netdpb I can even remove it by myself and create a pull request.

**Comment by netdpb** [comment]
Thanks, but because of our internal processes that actually makes it slightly more work for us. :D

**Comment by sergeivisotsky** [comment]
@netdpb OK, won't create in this case :D

**Comment by sergeivisotsky** [comment]
@netdpb Any news?

**Comment by netdpb** [comment]
We're having an internal discussion about how to remove `@Beta` from lots more APIs, including this one. But we'll fast-forward this decision and get it out sooner.

**Comment by sergeivisotsky** [comment]
ok, thanks

**Comment by sergeivisotsky** [comment]
@cgdecker In which release does it doing to be present? Is it available in Maven central for now?

**Comment by cgdecker** [comment]
@sergeivisotsky This was just pushed so it won't be available other than in a snapshot release (e.g. version `HEAD-jre-SNAPSHOT`) until we create a new release.

**Comment by sergeivisotsky** [comment]
@cgdecker OK. When a released is planned?
