### ISSUE TITLE
CacheBuilder not working

### ISSUE THREAD

**Issue by evgeniyasti** [google/guava#3968]
Hello.

I use the `CacheBuilder` with `expireAfterWrite(2000, TimeUnit.Milliseconds)`. I send 10000 requests to my program and I expect the `CacheBuilder` to call `RemovalListener` 10000 times after 2 seconds for each request. I do not observe this behaviour and instead I get `RemovalListener` called 1 or 2 times.

Can someone please explain to me what `CacheBuilder` is doing because as I explained above it is doing something totally different from the [documentation](https://github.com/google/guava/wiki/CachesExplained) that Guava is providing.

In the same spirit as above, I use `maximumSize(1000)` and after sending my program 10000 requests, I expect the `RemovalListener` to be called 9000 times. But it's called only 1 or 2 times.

How does this module works in reality?

**Comment by cpovirk** [comment]
The best way to get answers to "Why didn't it work" is StackOverflow. You can [ask a question with the `guava` tag](https://stackoverflow.com/questions/ask?tags=guava+java).
