### ISSUE TITLE
best Cache pattern for freezing keys on miss?

### ISSUE THREAD

**Issue by dhalperi** [google/guava#3972]
I'm wondering if I'm doing something wrong here:

I have a possibly-mutable cache key `K`, a function to freeze it `K -> FrozenK`, and a function to compute value: `K -> V`.

The `LoadingCache<K,V>` does not let me freeze `K` on miss - it just computes `V` from `K`, and presumably retains a reference to `K` and `V`.

The way I can do this is something like:

```java
@Nullable v = CACHE.getIfPresent(k);
if (v != null) {
  return v;
}
FrozenK frozenK = freeze(k);
v = computeValue(frozenK);
CACHE.put(frozenK, v);
return v;
```

Is there a better way to do something like this? Is maybe-mutable-keys not a common use case for `Cache` inside of Google? In practice, `K` is `Set` and `FrozenK` is `ImmutableSet`, so I assumed this would come up.

**Comment by cpovirk** [comment]
I don't believe we have anything built in for this. You could [ask on StackOverflow](https://stackoverflow.com/questions/ask?tags=guava+java) to see if others have recommendations on how to accomplish this. (I don't recall internal discussions, but I could be forgetting them.)

If you end up wanting a feature built for this, I suggest checking with [Caffeine](https://github.com/ben-manes/caffeine). Really, I suggest Caffeine nowadays in general: It's better than our caching library, and it's more actively maintained.

**Comment by dhalperi** [comment]
Thanks for the pointer, I'll check it out!
