### ISSUE TITLE
Duplicate class error (com.google.common.base.Platform) for guava:29.0-jre and guava-gwt:29.0-jre

### ISSUE THREAD

**Issue by manojpunde91** [google/guava#3976]
We are using gradle for building the project. Guava-gwt(29.0-jre) and Guava(29.0-jre) libraries are used in application.

While building the project compilation error is returned. Here is log details:
----------------------------------------------------------------------------------------
../guava-gwt-29.0-jre.jar(com/google/common/base/Platform.java):32: error: duplicate class: com.google.common.base.Platform
final class Platform {
      ^
../guava-gwt-29.0-jre.jar(com/google/common/collect/ImmutableCollection.java):202: error: cannot access Platform
        return Platform.copy(internal, internalArrayStart(), internalArrayEnd(), other);
               ^
  bad source file: /home/nfs/mpunde/.gradle/caches/modules-2/files-2.1/com.google.guava/guava-gwt/29.0-jre/dfb111aef98561143f5929b64424058c94e2251b/guava-gwt-29.0-jre.jar(com/google/common/collect/Platform.java)
    file does not contain class com.google.common.collect.Platform
    Please remove or make sure it appears in the correct subdirectory of the sourcepath.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors
-------------------------------------------------------------------------------

We replaced guava-gwt:29.0-jre with older version as 25.1 and build runs successful. Guava version is same one as 29.0-jre.

Problem is with 29.0-jre version of guava-gwt.

Kindly check the combination of these libraries and help us to resolve the compilation error.

Thanks,
Manoj.

**Comment by manojpunde91** [comment]
@cpovirk @kluever @cgdecker @lowasser 
Your help is appreciated.

**Comment by nick-someone** [comment]
Hello!

Unfortunately, I'm not sure we're going to be able to help here - the `guava-gwt-29.0-jre` artifact contains GWT-friendly sources, and the jar file definitely contains the right java source for this class:

```
unzip -c guava-gwt-29.0-jre.jar com/google/common/collect/Platform.java | head -50

package com.google.common.collect;
...
final class Platform {
```

I found this link which suggests setting an empty sourcepath may help? https://discuss.gradle.org/t/compilation-fails-when-i-use-guavas-optional-class-duplicate-class-com-google-common-collect-abstractiterator/7370
