### ISSUE TITLE
Probable false positive for InternetDomainName#isPublicSuffix

### ISSUE THREAD

**Issue by fgarit-te** [google/guava#3977]
Hello,

I'll make this short, I was surprised that `InternetDomainName.from("whatever.compute-1.amazonaws.com").isPublicSuffix());` returns `true`. I first noticed this when I ran it against this domain "ec2-34-238-173-81.compute-1.amazonaws.com" but then realized I could substitute the subdomain for apparently anything.
Tested with `guava 29-jre` see https://repl.it/repls/UpsetProductivePipelining#Main.java

Thanks

**Comment by nick-someone** [comment]
From the mozilla public suffix list: https://publicsuffix.org/list/public_suffix_list.dat

```
// Amazon Elastic Compute Cloud : https://aws.amazon.com/ec2/
// Submitted by Luke Wells <psl-maintainers@amazon.com>
*.compute.amazonaws.com
*.compute-1.amazonaws.com
*.compute.amazonaws.com.cn
us-east-1.amazonaws.com
```

(It was surprising to me too - but `whatever.compute-1.amazonaws.com` is a valid public suffix)

**Comment by fgarit-te** [comment]
My bad, thanks!

**Comment by cpovirk** [comment]
Sorry that we haven't improved our docs here yet. https://publicsuffix.org/ has the basic explanation, which surprises everyone who first reads it.

We've also been meaning to link https://github.com/sleevi/psl-problems, which recommends against using the Public Suffix List in anything new. Sadly, part of its recommendations for alternatives is currently ["hope for something better to come along"](https://github.com/sleevi/psl-problems#what-are-we-going-to-do-about-cookies-then) :)
