### ISSUE TITLE
Release pages should have download links for jars again

### ISSUE THREAD

**Issue by Stefan311** [google/guava#3978]
Hello,

I would like to upgrade an old guava version (14.0.1) in a Ant-Build project. So I just need the current guava jar file.
The [documentation](https://github.com/google/guava/wiki/UseGuavaInYourBuild#manual-dependencies) say "just manually download JARs", but **where are the download links** ?

Greetings
Stefan

**Comment by cpovirk** [comment]
https://repo1.maven.org/maven2/com/google/guava/guava/14.0.1/

**Comment by Stefan311** [comment]
Ok thanks, could someone please add this link to the release pages? I have searched half an hour...
PS: I take this one: https://repo1.maven.org/maven2/com/google/guava/guava/29.0-jre/

**Comment by cpovirk** [comment]
It looks like the doc you linked to was true long ago (https://github.com/google/guava/wiki/Release14), but all our recent releases are lacking such links (https://github.com/google/guava/releases/tag/v29.0).

**Comment by amanjha8100** [comment]
hey @kluever can I work on this, since no PR has been submitted yet.

**Comment by kluever** [comment]
It looks like the releases contain links to the jars now.

https://github.com/google/guava/wiki/Release23#using-guava-in-your-project

Please re-open if you're not seeing the links.
