### ISSUE TITLE
Unnecessary boxing in Doubles.constrainToRange()

### ISSUE THREAD

**Issue by mschoth** [google/guava#3984]
Doubles.constrainToRange(double,double,double) and Floats.constrainToRange(float,float,float) both cause unnecessary boxing of their arguments. Both call Preconditions.checkArgument(boolean, String, **Object**, **Object**) which causes the boxing.

Can be easily fixed by introducing an overloaded version of checkArgument for floats and doubles. For ints and longs these versions already exist:
Preconditions.checkArgument(boolean, String, **int**, **int**)
Preconditions.checkArgument(boolean, String, **long**, **long**)
which is also why constrainToRange does not have the same problem in the Ints, Shorts & Longs packages.

**Comment by kluever** [comment]
Fixed - should be mirrored out shortly.
