### ISSUE TITLE
com.google.common.eventbus.EventBus#post，cannot match the basic type

### ISSUE THREAD

**Issue by jcx-1020** [google/guava#3989]
If the post method parameter of the EventBus class is of a basic type, it cannot be recognized. Because the post method parameter is Object, the basic type is automatically boxed into its packaging class, and the corresponding method cannot be matched. You can add the corresponding method of the basic type through the method overload of the post method.

**Comment by netdpb** [comment]
I think you're talking about primitive types (like `int`, `long`, etc.). EventBus doesn't support using primitives as event objects. It's meant for custom event classes. I wouldn't recommend using common reference types like `String` either.

If you really want to consider primitive types as events, you'll have to use the boxed class.

`EventBus` should probably warn or fail when encountering `@Subscribe` methods with primitive parameters. It could be extended to support them, but I think that's probably a dangerous pattern.

**Comment by netdpb** [comment]
I've filed a new issue to document and enforce the restriction. I don't think we will add primitive support, so I'm closing this issue.
