### ISSUE TITLE
Please open a security advisory

### ISSUE THREAD

**Issue by JLLeitschuh** [google/guava#3995]
Please open a security advisory to discuss a potential security vulnerability in guava. Please add me so we can discuss the issue.

https://github.com/google/guava/security/advisories

**Comment by nick-someone** [comment]
Thanks again for being flexible.

Certainly, once things get to public disclosure, I see no reason not to put the advisory in the Security Advisory tab; makes it easy to find!

**Comment by u269c** [comment]
@JLLeitschuh - we (Google) do issue CVEs now :)
That comment you quoted is from 2019, we have the Google LLC CNA as of February 2020.

https://cve.mitre.org/cve/request_id.html#g
https://cve.mitre.org/news/archives/2020/news.html#February042020_Google_Added_as_CVE_Numbering_Authority_CNA
