### ISSUE TITLE
RangeSet.add(...) may cause ConcurrentModificationException

### ISSUE THREAD

**Issue by overheadhunter** [google/guava#3997]
Guava 29.0-jre, JDK 11:

When adding multiple ranges to a RangeSet concurrently, you might end up with this exception:

```
java.util.ConcurrentModificationException: null
	at java.base/java.util.TreeMap$NavigableSubMap$SubMapIterator.nextEntry(TreeMap.java:1700)
	at java.base/java.util.TreeMap$NavigableSubMap$SubMapEntryIterator.next(TreeMap.java:1748)
	at java.base/java.util.TreeMap$NavigableSubMap$SubMapEntryIterator.next(TreeMap.java:1742)
	at java.base/java.util.AbstractCollection.clear(AbstractCollection.java:446)
	at java.base/java.util.AbstractMap.clear(AbstractMap.java:297)
	at com.google.common.collect.TreeRangeSet.add(TreeRangeSet.java:214)
```

The root cause seems to be how submaps of a TreeMap are cleared: Using an iterator over the entryset.

At the moment, you can only create a RangeSet backed by a TreeMap, the contructor is private so as an API user you don't have any other choice than locking access to the whole RangeSet when modifying it.

Here is a test to trigger this exception (most of the times):

```java
RangeSet<Integer> rangeSet = TreeRangeSet.create();
ExecutorService executorService = Executors.newCachedThreadPool();
CountDownLatch cdl = new CountDownLatch(1000);
for (int i = 0; i < 1000; i++) {
	var range = Range.closed(i, i+5);
	executorService.submit(() -> {
		try {
			rangeSet.add(range);
		} catch(ConcurrentModificationException e) {
			e.printStackTrace();
		} finally {
			cdl.countDown();
		}
	});
}
cdl.await();
```

**Comment by overheadhunter** [comment]
To be precise, the contract doesn't promise thread safety explicitly. However this is kind of a de-facto standard for other collections in Guava, so there should at least be a warning about this.

**Comment by netdpb** [comment]
As you note, `RangeSet` is not documented to be thread-safe. But neither are other Guava collection types, except for the `Immutable*` ones and `ConcurrentHashMultiset`.

I could see adding a note to all thread-unsafe collection types to that effect, but I don't think people expect collections to be thread-safe unless they're explicitly marked as such.

**Comment by netdpb** [comment]
Thinking further about this. In general, collection types are presumed not to be thread-safe unless explicitly described as such. That applies just as much to the Guava collections as to those in the JDK. `Set` and `Map` don't mention thread safety; `ConcurrentHashSet` and `ConcurrentHashMap` describe their concurrency semantics. I don't think it's necessary to do anything more than that for the Guava collection types.
