### ISSUE TITLE
Guava RateLimiter doesn't apply throttling after a delay

### ISSUE THREAD

**Issue by wamsea** [google/guava#4014]
I have been playing around with Guava RateLimiter and found that it doesn't apply throttling just after a delay (if the rateLimiter is left unused for period of time).

Below is the sample code.

`public static void main(String[] args) throws Exception{
        RateLimiter rateLimiter = RateLimiter.create(1);
        
        System.out.println("#1 Before delay waitTime= "+  rateLimiter.acquire());
        System.out.println("#2 Before delay waitTime= "+  rateLimiter.acquire());
        System.out.println("#3 Before delay waitTime= "+  rateLimiter.acquire());
        System.out.println("-----------------------------");
        Thread.sleep(4000);
        
        System.out.println("#1 After delay waitTime= "+  rateLimiter.acquire());
        System.out.println("#2 After delay waitTime= "+  rateLimiter.acquire());
        System.out.println("#3 After delay waitTime= "+  rateLimiter.acquire());
        
        System.out.println("-----------------------------");
        Thread.sleep(4000);
        
        System.out.println("#1 After delay waitTime= "+  rateLimiter.acquire());
        System.out.println("#2 After delay waitTime= "+  rateLimiter.acquire());
        System.out.println("#3 After delay waitTime= "+  rateLimiter.acquire());
        
    }`

And here is the result:
`
#1 Before delay waitTime= 0.0
#2 Before delay waitTime= 0.993215
#3 Before delay waitTime= 0.998329
-----------------------------------------------------
**#1 After delay waitTime= 0.0**
**#2 After delay waitTime= 0.0**
#3 After delay waitTime= 0.999903
-----------------------------------------------------
**#1 After delay waitTime= 0.0**
**#2 After delay waitTime= 0.0**
#3 After delay waitTime= 0.999921 `

Wondering as to why the first two attempts after a delay (Highlighted in bold above) are processed with no throttling (waitTime=0.0)

**Comment by nick-someone** [comment]
This is the documented behavior - https://guava.dev/releases/snapshot-jre/api/docs/com/google/common/util/concurrent/RateLimiter.html#create-double-

> When the rate limiter is unused, bursts of up to permitsPerSecond permits will be allowed, with subsequent requests being smoothly limited at the stable rate of permitsPerSecond.

See implementation comments here for why: https://github.com/google/guava/blob/7fd0ff50fbaf0221d9483b99db56ad604ef878d1/guava/src/com/google/common/util/concurrent/RateLimiter.java#L118

**Comment by Koooooo-7** [comment]
Hi, I think it is the feature about the default `RateLimiter` that *the default RateLimiter configuration can save the unused permits of up to one second.*
So, for ur case ` RateLimiter.create(1)`, when you delay more than 1 second，there should have 1 unused permit saved.
