### ISSUE TITLE
Automate generation of https://guava.dev/Foo Javadoc shortlinks

### ISSUE THREAD

**Issue by cpovirk** [google/guava#4023]
I think I generated them once by hand. Generating them automatically during builds shouldn't be too hard.

(I noticed because I just wanted to reference https://guava.dev/ClosingFuture and was reminded that that won't exist until we add it ourselves.)

I may have some other notes about this somewhere. Certainly I have at least some on internal bug 157460102, which is about adding more shortlink conveniences and Javadoc munging.

**Comment by benrkia** [comment]
I would like to work on this issue if it's possible 🙏

**Comment by cpovirk** [comment]
That would be terrific. I'm not 100% sure of the best place to put the code, but maybe [near the end of `main` in `updaterelease.sh`](
https://github.com/google/guava/blob/eab62203255f88968469ac8d910bbbaaf62faf02/updaterelease.sh#L408)? We'd want to do it only if `$RELEASE` is `snapshot`.

I'm also not completely sure what command I ran to generate these. I think I actually had a Java program when I did it for Guava, but I switched to using a shell script when I did the same job for https://truth.dev. I found this in my Bash history. If adapted for Guava, it might work:

```shell
for F in `find api/latest/com/google/common/truth/ -name '[A-Z]*.html' -not -path '*/class-use/*' -not -name '*.*.*'`; do SHORT=$(basename $F .html); SHORT_LOWER=$(echo $SHORT | tr A-Z a-z); mkdir -p api/javadocshortcuts/{$SHORT,$SHORT_LOWER} && ( echo ---; echo "title: $SHORT"; echo "permalink: /$SHORT/"; echo "redirect_to: https://truth.dev/$F"; echo "---" ) | tee api/javadocshortcuts/{$SHORT,$SHORT_LOWER}/index.md > /dev/null; perl -pi -e '$_ = lc $_ if /^permalink/' api/javadocshortcuts/$SHORT_LOWER/index.md; done
```

**Comment by cpovirk** [comment]
(This was fixed by https://github.com/google/guava/pull/5315.)
