### ISSUE TITLE
Graph#successors may return nodes with incorrect data.

### ISSUE THREAD

**Issue by nucz** [google/guava#4027]
Hello. The bug I found in the code bellow. `g.successors` result may differ from same nodes in `g.nodes()`.
```
import com.google.common.graph.Graph;
import com.google.common.graph.MutableNetwork;
import com.google.common.graph.NetworkBuilder;
import lombok.EqualsAndHashCode;
import lombok.RequiredArgsConstructor;
import lombok.ToString;
import org.junit.Assert;
import org.junit.Test;

public class GraphBugTest {

  @Test
  public void bug() {
    final MutableNetwork<Node, String> mutableNetwork = NetworkBuilder
        .directed()
        .expectedEdgeCount(4)
        .expectedNodeCount(4)
        .build();
    mutableNetwork.addEdge(new Node(1), new Node(2), "1->2");
    mutableNetwork.addEdge(new Node(2), new Node(3), "2->3");
    mutableNetwork.addEdge(new Node(3), new Node(1), "3->1");
    mutableNetwork.addEdge(new Node(3), new Node(4), "3->4");
    final Graph<Node> g = mutableNetwork.asGraph();
    g.nodes().forEach(n -> n.visited = true);
    g.nodes().forEach(n -> Assert.assertTrue(n.visited));
    g.successors(new Node(3)).forEach(n -> Assert.assertTrue(n.visited));
  }

  @RequiredArgsConstructor
  @EqualsAndHashCode(onlyExplicitlyIncluded = true)
  @ToString
  static class Node {
    @EqualsAndHashCode.Include
    final Integer data;
    boolean visited;
  }
}
```

**Comment by jbduncan** [comment]
@nucz I'm only an avid user of Guava, but having the [wiki](https://github.com/google/guava/wiki/GraphsExplained#elements-and-mutable-state) on this, I get the impression that the behaviour you're seeing is purposefully undefined.

Have you considered storing the mutable "visited" state in a separate set like the following?

```java
public class GraphSuccessorsExampleTests {
  @Test
  public void theTest() {
    final MutableNetwork<Node, String> mutableNetwork = NetworkBuilder
        .directed()
        .expectedEdgeCount(4)
        .expectedNodeCount(4)
        .build();
    mutableNetwork.addEdge(new Node(1), new Node(2), "1->2");
    mutableNetwork.addEdge(new Node(2), new Node(3), "2->3");
    mutableNetwork.addEdge(new Node(3), new Node(1), "3->1");
    mutableNetwork.addEdge(new Node(3), new Node(4), "3->4");
    final Graph<Node> g = mutableNetwork.asGraph();
    // Change starts here:
    var visitedNodes = new HashSet<Node>();
    g.nodes().forEach(n -> visitedNodes.add(n));
    g.nodes().forEach(n -> Assert.assertTrue(visitedNodes.contains(n)));
    g.successors(new Node(3)).forEach(n -> Assert.assertTrue(visitedNodes.contains(n)));
  }

  @RequiredArgsConstructor
  @EqualsAndHashCode
  @ToString
  static class Node {
    final Integer data;
    // Note the lack of "visited" here
  }
}
```

**Comment by jbduncan** [comment]
That being said, re-reading the wiki, it seems to be a bit of a stretch that the statement "the mutable state must not be reflected in the `equals()/hashCode()` methods (this is discussed in the Map documentation in detail)" would imply the behaviour you're seeing is valid.

Any thoughts, Guava team?

(To clarify, the behaviour that I see from running the OP's code snippet is it throws an `AssertionError`, and when viewing the contents of `g.successors()` and `g.edges()` in IntelliJ IDEA's debugger it shows that not all the nodes have a `visited` value of `true` by the end of the test.)

**Comment by jbduncan** [comment]
Then again, the wiki recommends storing mutable state in a separate data structure (like an element-to-state map), so perhaps this "bug" is intentional after all?

**Comment by nucz** [comment]
@jbduncan the mutable state (visited variable) doesn't reflect in equals/hashcode. Storing mutable state in a separate data structure is only a option. 1 more detail about successors in my example: almost all nodes have visited=true.

**Comment by nick-someone** [comment]
Quoting from the wiki link @jbduncan sent:

> don't construct multiple elements that are equal to each other and expect them to be interchangeable. In particular, when adding such elements to a graph, you should create them once and store the reference if you will need to refer to those elements more than once during creation (rather than passing new MyMutableNode(id) to each add*() call).

The equals/hashCode equivalence between two objects means that the graph library is free to treat these objects as interchangeable (i.e.: we could store just one, or multiple of them). This is what you've run into here - we treat the `Node(3)` added as the starting node as interchangeable with one or either of the `Node(3)` stored as the end node of one of the other two edges. Unfortunately, you want to treat them as the same object, which we don't guarantee.
