### ISSUE TITLE
RateLimitter is not thread Safe

### ISSUE THREAD

**Issue by bmnizar** [google/guava#5262]
Hello,

I have tested RateLimitter with a non synchronized code and it was working as expected.But when in a multi threaded environment,it's not thread safe unless i put acquire method in a synchronized block.

```
	public static void main(String[] args) throws IOException, SAXException, InterruptedException {
		BlockingQueue<Runnable> blockingQueue = new LinkedBlockingQueue<>();
		ThreadPoolExecutor threadPoolExecutor = new ThreadPoolExecutor(4, 4, 100000L, TimeUnit.DAYS, blockingQueue);
		Collection listOfCallable = new ArrayList<Callable>();
		RateLimiter r = RateLimiter.create(1);
		r.setRate(1);
		for (int i = 0; i < 1000; i++) {
			Callable callable = new Callable() {

				@Override
				public Object call() {
//					reentrantLock.lock();
					System.out.println("get 1 tokens: " + r.acquire() + "s");
//					reentrantLock.unlock();
					return "OK";
				}
			};
			listOfCallable.add(callable);
		}
		threadPoolExecutor.invokeAll(listOfCallable);

	}
```

Result:
get 1 tokens: 0.0s
get 1 tokens: 0.987943s
get 1 tokens: 1.987914s
get 1 tokens: 2.9879s
get 1 tokens: 3.985922s
get 1 tokens: 3.997088s
get 1 tokens: 3.997955s
get 1 tokens: 3.997627s
get 1 tokens: 4.000335s
get 1 tokens: 3.998978s
get 1 tokens: 3.999678s
get 1 tokens: 3.998823s
get 1 tokens: 3.999561s
get 1 tokens: 3.999179s
get 1 tokens: 3.998722s

When i activate the synchronized block ,it works perfectly:

```
static ReentrantLock reentrantLock = new ReentrantLock();
	@SuppressWarnings({ "unchecked", "rawtypes" })
	public static void main(String[] args) throws IOException, SAXException, InterruptedException {
		BlockingQueue<Runnable> blockingQueue = new LinkedBlockingQueue<>();
		ThreadPoolExecutor threadPoolExecutor = new ThreadPoolExecutor(4, 4, 100000L, TimeUnit.DAYS, blockingQueue);
		Collection listOfCallable = new ArrayList<Callable>();
		RateLimiter r = RateLimiter.create(1);
		r.setRate(1);
		for (int i = 0; i < 1000; i++) {
			Callable callable = new Callable() {

				@Override
				public Object call() {
					reentrantLock.lock();
					System.out.println("get 1 tokens: " + r.acquire() + "s");
					reentrantLock.unlock();
					return "OK";
				}
			};
			listOfCallable.add(callable);
		}
		threadPoolExecutor.invokeAll(listOfCallable);

	}
```

Result:

get 1 tokens: 0.0s
get 1 tokens: 0.987625s
get 1 tokens: 0.998461s
get 1 tokens: 1.000713s
get 1 tokens: 0.999483s
get 1 tokens: 0.999709s
get 1 tokens: 0.998843s
get 1 tokens: 0.998932s

Why not aquire is not synchronized?

**Comment by netdpb** [comment]
`acquire()` returns how many seconds it blocked. Your executor has only four threads, which means that pretty much every request after the first few has to wait for four seconds for the four previous ones to finish.

If you serialize, as you have, then you're not requesting another permit until there's nothing in the queue.

Closing this for now. If you have further questions, you might find useful information on stackoverflow.com as well: https://stackoverflow.com/search?q=%5Bguava%5D+ratelimiter

**Comment by ChitSuShine** [comment]
Hello, I also have tested for RateLimitter using parallel of IntStream like the below, resulting thread unsafe:


  ```
@Test
public void test() {
    RateLimiter rateLimiter = RateLimiter.create(10);
    long startTime = ZonedDateTime.now().getSecond();
    IntStream.rangeClosed(1, 20)
        .parallel()
        .forEach(i -> {
          //synchronized (obj) {
            boolean result = rateLimiter.tryAcquire(1, 100, TimeUnit.MILLISECONDS);
            if (result) {
              System.out.println("Get Acquired");
            } else {
              System.out.println("Get NON-Acquired");
            }
         // }
        });
    long elapsedTimeSeconds = ZonedDateTime.now().getSecond() - startTime;
    System.out.println("Elapsed Time: " + elapsedTimeSeconds);
  }
```
```
Result:
Get Acquired
Get NON-Acquired
Get NON-Acquired
Get NON-Acquired
Get NON-Acquired
Get NON-Acquired
Get NON-Acquired
Get NON-Acquired
Get NON-Acquired
Get NON-Acquired
Get NON-Acquired
Get NON-Acquired
Get NON-Acquired
Get NON-Acquired
Get NON-Acquired
Get NON-Acquired
Get NON-Acquired
Get NON-Acquired
Get NON-Acquired
Get Acquired
Elapsed Time: 0
```
But if I uncomment synchronized block, the result seems fine.
```
Result:
Get Acquired
Get Acquired
Get Acquired
Get Acquired
Get Acquired
Get Acquired
Get Acquired
Get Acquired
Get Acquired
Get Acquired
Get Acquired
Get Acquired
Get Acquired
Get Acquired
Get Acquired
Get Acquired
Get Acquired
Get Acquired
Get Acquired
Get Acquired
Elapsed Time: 2
```

**Comment by netdpb** [comment]
`tryAcquire()` returns false immediately if it can't acquire a permit. You've set up a rate limiter that gives 10 requests per second, or one every 100ms. You immediately ask 20 times for a permit within 100ms. The first one succeeds, which means the next permit won't be given out for 100ms; the rest fail.

You might have more luck getting the results that you want if you extend the duration past 100ms.

In any case, this issue is still closed. You may have more people looking at your question on stackoverflow.com than here.
