### ISSUE TITLE
Hashing is friendly

### ISSUE THREAD

**Issue by thistanghong** [google/guava#5270]
when i use Hashing.crc32c(), the compiler say ...collect.Hashing is not public in ....collect

**Comment by netdpb** [comment]
I'm not sure how to help here. `com.google.common.hash.Hashing.crc32c()` is public and has no dependencies on `com.google.common.collect.Hashing`.

This isn't really the right forum for general questions on how to use Guava. (It's for bug reports and feature requests.) Maybe look on stackoverflow.com under the `guava` tag: https://stackoverflow.com/questions/tagged/guava

**Comment by thistanghong** [comment]
Thank you for your sincere advice
