### ISSUE TITLE
IteratorTester does not check that iterator throws NoSuchElementException after exhaustion

### ISSUE THREAD

**Issue by jbduncan** [google/guava#5279]
**How to reproduce:**
1. `git clone https://github.com/jbduncan/graphemes-iterable.git`
2. `git checkout 304c99c0ca662f49bbb048098fd0555753c1d58f`
3. Open "src/main/java/org/jbduncan/Graphemes.java"
4. Comment out lines 48-50:
```java
          if (!hasNext()) {
            throw new NoSuchElementException();
          }
```
5. Ensure you're using Java 11+
6. Run `./gradlew :test --tests "org.jbduncan.GraphemesTests.graphemesFulfillsIteratorContract"`

**Expected behaviour**
A red test saying something like:
> junit.framework.AssertionFailedError: failed with stimuli [next, next, next, next, next, hasNext]

**Actual behaviour**
A green test.

Having given this example though, I realise that exhausting an iterator only works if it isn't infinite like `Stream.generate(() -> 1).iterator()`. Perhaps that's why it's only tested in guava-testlib's `CollectionIteratorTester#testIteratorNoSuchElementException` at the moment. Maybe a new protected method could be added to `IteratorTester` like `expectedSize` that a user can override for finite iterators, and that returns -1 by default to signal that the iterator is infinite. Example:

```java
new IteratorTester<>(
    expectedElements.size(),
    IteratorFeature.UNMODIFIABLE,
    expectedElements,
    IteratorTester.KnownOrder.KNOWN_ORDER) {
  @Override
  protected Iterator<String> newTargetIterator() {
    return actualElements.iterator();
  }

  @Override
  protected int expectedSize() {
    return expectedElements.size();
  }
}
```

**Comment by cpovirk** [comment]
Hmm, thanks. I would have guessed that it would catch that somewhere around here:
https://github.com/google/guava/blob/7affc4e29a6dff7bfb5207ebb2f979b849c5dfdd/guava-testlib/src/com/google/common/collect/testing/AbstractIteratorTester.java#L442

Is this because you're limiting the number of steps to the length of the list? That would mean that we can call `next` _n_ times but then don't have another step left to call `next` again.
https://github.com/jbduncan/graphemes-iterable/blob/304c99c0ca662f49bbb048098fd0555753c1d58f/src/test/java/org/jbduncan/IteratorTesters.java#L12

**Comment by cpovirk** [comment]
Tentatively closing, given the above, but please reopen if I have that wrong.

**Comment by jbduncan** [comment]
Ooh, you're absolutely right! I didn't check the case when the `steps` is +1 the length of both the expected and actual lists, only when one list is +1 the length of the other. So indeed this is a misreport. Thank you very much!

**Comment by jbduncan** [comment]
As a follow-up to this, I've raised _yet another_ PR (https://github.com/google/guava/pull/5281) to update the number of `steps` in the `IteratorTester` class javadoc's example from 5 to 6, with a short paragraph on why it's useful. (Thanks for your patience on this!)
