### ISSUE TITLE
ByteStreams.copy() that used FileChannel is been reverted, but still in 30.0 change log 

### ISSUE THREAD

**Issue by moonfruit** [google/guava#5289]
In the 30.0 change log:

![image](https://user-images.githubusercontent.com/1070090/96420575-3f01b380-1228-11eb-9daf-5220bee7f80b.png)

But this is already been reverted in e839f94fb4eb1240f10763586aa92a7f701caa89, and not be included in the 30.0.

Should it be removed from the 30.0 change log?

**Comment by cpovirk** [comment]
Thank you for pointing out my mistake. I went and updated the release notes.
