### ISSUE TITLE
Cool off period

### ISSUE THREAD

**Issue by asarkar** [google/guava#5291]
I’ve a use case where the provider wants us to throttle the calls not by some fixed rate/second, but by individual user ids. In other words, a user must wait for a period x before making a call again. So it’s more like a cool off period than the usual rate limiting.

One obvious way to approach this problem is to create a rate limiter per user. But there will be many such limiters, and very short lived. Are there better ways?

**Comment by nick-someone** [comment]
Unfortunately, Guava doesn't, to my understanding, provide this feature. 

You may want to search StackOverflow for help with this question (see https://github.com/google/guava#links for a link to ask a well-tagged question)
