### ISSUE TITLE
The method getDone() of Futures is rightly invoked here?

### ISSUE THREAD

**Issue by purekeeper** [google/guava#5295]
![image](https://user-images.githubusercontent.com/15372524/97551304-c95acc00-1a0d-11eb-8c9d-a24e5a029b4f.png)

Class is Futures

getDone() means future was already done,but we not sure here,right ? is it  a bug ?

getUninterruptibly() replaced by getDone () after 19.0, could you tell me why do this ?

**Comment by nick-someone** [comment]
This class is `CallbackListener`, a Runnable class which is invoked from a ListenableFuture after it's complete (i.e.: the run() method is only called *after* the underlying Future is done).
