### ISSUE TITLE
Enable multiple Finalizers for FinalizableReferenceQueue

### ISSUE THREAD

**Issue by HannesWell** [google/guava#5311]
At the moment a `com.google.common.base.FinalizableReferenceQueue` has one `com.google.common.base.internal.Finalizer`. This `Finalizer` mainly starts a Thread that calls `finalizeReferent()` for each `FinalizableReference` that is enqueued to the shared `ReferenceQueue` and terminates when the `FinalizableReferenceQueue` is closed or garbage collected.

In situations where finalizeReferent() is a longer running task, more than one `Finalizer`-thread for a `FinalizableReferenceQueue` could be a performance gain.

Therefore I want to propose to enable multiple `Finalizer` for one `FinalizableReferenceQueue`.

As far as I can assess, this feature would only require minor changes to `FinalizableReferenceQueue`. The `Finalizer` class does not need to be changed. It looks like `java.lang.ref.ReferenceQueue` is threadsafe. 
The required change could be:

1. The final field `PhantomReference<Object> frqRef` needs to be changed to be a `List<PhantomReference<Object>> frqRefs`.
2. A second constructor with an int argument for the number of Finalizers needs to be add.
The argument must be greater or equal one. The no-argument constructor calls the int-constructor with value 1.
3. The new constructor is similar to the now existing one, but in contrast it creates a `Finalizer` (everything inside the try-block) and a `PhantomReference` to itself (and adds it to the list `frqRefs`) inside the body of a loop. That loop has as many passes as specified by the int-argument. 
The value of `threadStarted` should be set to true after every successful `Finalizer` creation, so the corresponding field will be true if at least one finalizer was really started.
4. In `FinalizableReferenceQueue.close()` each reference in the list `frqRefs` needs to be enqueued.

If you are interested in such enhancement, I can provide a PR once the change is discussed.

**Comment by netdpb** [comment]
How often do you see `finalizeReferent()` taking a long time or blocking? That seems unusual to me. Can you give some examples?

**Comment by HannesWell** [comment]
I'm using the `FinalizableReferenceQueue` in a Cache (with strongly referenced keys and softly or weakly referenced values) that writes the data-payload of a value to the drive once the value is finalized by the garbage-collector.
In order to speed up writing, I want do it concurrently. Writing the data not only requires to dump bytes from the RAM to the drive, but also to compute the bytes to write.

I already thought about the solution of submitting a task to another Executor, too. But instead of introducing one more intermediate-layer, I would then let the Executor's task poll the `ReferenceQueue` directly and skip the `FinalizableReferenceQueue`.

**Comment by H1414** [comment]
دب

**Comment by netdpb** [comment]
I'm not sure I understand what you mean by having the executor's task "poll the `ReferenceQueue` directly". `ThreadPoolExecutor`s use a `BlockingQueue`, which isn't the same as a `ReferenceQueue`. (I may be missing something.)

Could you set up an executor just for that final data persistence, and make `finalizeReferent()` submit a compute-and-write task to that executor for each referent?

**Comment by HannesWell** [comment]
Sorry, my statement was ambiguous. I meant that in this case I could use an ordinary `java.lang.ref.ReferenceQueue` and submit tasks to the Executor (one per available Thread), that constantly poll from that ordinary ReferenceQueue and call finalize. Just like FinalizableReferenceQueue does but with multiple tasks perspectively Threads.

Yes I could set up an executor for that final data persistence, but it seems cumbersome to me. Then I would do it like I just described and avoid the indirection over multiple threads.
As far as I understand the implementation of FinalizableReferenceQueue  and Finilaizer, the main complexity comes from not keeping a strong reference to the Classloader and a little bit from auto-detecting if the FinalizableReferenceQueue was finalized by the GC. Without that nothing much is left and I see no advantage in using the FinalizableReferenceQueue and then create tasks for another executor over running tasks in an Executor Executor that poll an ordinary ReferenceQueue directly. Always assuming that I only use the `FinalizableReference`s from Guava in conjunction with that queue.

Please correct me if I'm wrong.

**Comment by netdpb** [comment]
So in either case your `Reference`s would implement `finalizeReferent()` to do the compute-and-write work, right? In one case directly, and in another by submitting a runnable to an executor.

I'm not sure that submitting a runnable to an executor is more complex than setting up an executor that polls from a RQ. In fact, the FRQ approach means you don't have to write polling code (or deal with the classloading issue).

In any case, I think that either of those approaches is a more appropriate way of doing what you want to do than making FRQ and its API more complex for everyone.

**Comment by ben-manes** [comment]
> I'm using the FinalizableReferenceQueue in a Cache (with strongly referenced keys and softly or weakly referenced values)

Guava's cache used to use FRQ for reference collection, but this was problematic. I think it was a mixture of being unable to keep up, threads were not permitted on some environments (e.g. JEE, GAE), and classloader problems (e.g. Tomcat). For a while it was deprecated, and then un-deprecated by request but no longer evangelized / used by Google ([thread](https://groups.google.com/g/guava-discuss/c/-_ntQ_4-Gaw/m/D33WcowIIxoJ)). We replaced our usage in Guava's Cache by a much more robust mechanism, which didn't require dedicated thread(s). Is there a reason you prefer FRQ over a Guava/Caffeine cache?

Is `java.lang.ref.Cleaner` preferred over FRQ these days?

**Comment by HannesWell** [comment]
@netdpb yes you are right.

Yes either way is approximately as complex as the other, but in total both are not very complex. That's right the FRQ approach would save me from writing that code. Therefore I suggested this change because I thought it would be a handy features and maybe others also would appreciate it.

Alright. I have now prepared my own Executor that polls a ordinary `ReferenceQueue`, like you suggested it. This also has the advantage that I can await the termination of the finalizer-threads and discard pending finalized references. Although it is not absolutely necessary to control the shutdown, it makes things simpler for me. I don't have to supervise it indirectly.

So if you don't want to proceed on this, from my point of view this issue can be closed.

@ben-manes thanks for this background information. The discussion-thread is interesting. Everything I need was already discussed there. Too bad that it didn't made it into Guava.

To use the Cleaner is actually a good idea, but has the following drawbacks:
- It uses only one thread per Cleaner
- Besides the registration at the cleaner I have to create a separate Soft- or WeakReference (without a ReferenceQueue), if you want such reference and are not only interested in a clean-up action. This isn't a big issue I think.
- You cannot await the shutdown (which for me isn't necessary but handy)
- A `Cleanable` cannot be cleared (only `clean()` can be called). This makes it different to FRQ. If you have a `Finalizable*Reference` you can call `finalizeReferent()` (which is equivalent to `Cleanable.clean()`) and additionally you can call clear(). Calling `clear()` prevents a `Soft-/WeakReference` (I'm not sure about `PhantomReference`) from being enqueued if the referent is finalized in the future.

If you don't need a clear-mechanism, I think `java.lang.ref.Cleaner` is an appropriate replacement for `FinalizableReferenceQueue`.
Nevertheless I need this feature. When I explicitly remove an element from my cache, the reference is cleared to prevent the value-data of being written to drive, when the value-object is finalized afterwards.

If Cleanable would get a `clear()` method with the described effect it would be a good replacement.
Having the possibility to pass an Executor to the Cleaner (for multiple threads and to initiate and await shutdown), like suggested for FRQ in the posted thread, would be a perfect match for me. But this has to go to OpenJDK.

**Comment by HannesWell** [comment]
@ben-manes regarding to your question why I don't use Guava Cache, the answer is: I used it in my first implementation but because I could not find a way to "attach" metadata to a entry or value of the cache another map was necessary. Both maps must be kept in sync.
The metadata contain for example a reference to the value-data to write or a CountDownLatch to synchronise writes to driven with subsequent loads. To avoid the need for synchronization of the cache with the metadata-map I just use one ConcurrentHashMap from key to metadata (which now also have a Soft/WeakReference to the actual value).

I didn't know about Caffeine but I will have a look at it, maybe it can help me better in my case.

**Comment by ben-manes** [comment]
The caches might not be useful themselves, but you might find the approach they use helpful.

Instead of using background thread(s) blocked on `ReferenceQueue#remove()`, the work is amortized across calling threads. When handling a cache operation, like `get(key)`, an atomic counter is retrieved by hash from an array and incremented. When the counter exceeds a maximum, e.g. 16, then the caller attempts to acquire a `tryLock` and perform the maintenance cycle. During that clean up step, the non-blocking `ReferenceQueue#poll()` is called to remove the hashmap entry and defer additional work to the removal listener. This listener might be schedules on an executor service, allowing multiple async removals to be processed while only one thread performs the actual cache cleanup.

This approach removed a dedicated thread-per-cache, quickly drains the queue, and delegates any heavy-weight processing to a thread pool. The per-access cost to trigger the maintenance is fairly low if the counters are striped, e.g. by the thread's id, and allowed us to implement other features like LRU which require access-level tracking. From a library perspective where usages might have dozens or more caches, removing the dedicated thread was an obvious and needed benefit. The cost, though, is that notifying the listener is delayed until other cache activity occurs, so it may not be prompt if under low utilization.

**Comment by netdpb** [comment]
OK, I'm closing this feature request since it seems you have a solution that works for you. Feel free to continue a discussion here if you'd like.

**Comment by HannesWell** [comment]
@netdpb thanks for the discussion.

@ben-manes that's a quite clever approach you use and I agree that avoiding the finalizer-thread-per-cache is definitely a benefit. Nevertheless in my use case the additional removal work (in my case writing data to drive) should be done as soon as possible.

I'm using my `DriveCache` as an extension to the RAM, that only writes data to the drive if the JVM tends to run out of memory. On this way more data can be processed and at the same time drive I/O is avoided as far as possible.

For the background: The `DriveCache` is used as a value storage (where each value is accessible by its key), that can write the "payload-data" of values to the drive and releases the memory of value and its payload, if the JVM tends to run out of memory. Therefore I'm using mainly `SoftReferences` for the values, but `WeakReferences` work too.
When a new entry is add to the DriveCache a `EntryMetadata`-Object is created that has a Soft-/WeakReference to the value-Object and a strong reference to the values "payload-data". The Reference-Object also has a reference to the EntryMetadata-object. Then the key-object is put together with the `EntryMetadata`-object in the `ConcurrentHashMap` backing the cache.
Once the `Reference` of an entry is enqueued into the `ReferenceQueue` of the Cache, the "payload-data" of the entry are written to drive and are then released so they can be garbage collected too. If the written value of a key is requested later, it is loaded from drive.
If the memory pressure never becomes high no value-data are written and `get(key)` just returns the referent of the Soft-/WeakReference.

This only works if the value-object is a wrapper around its actual memory consuming payload-data object and that payload-data can be written to the drive without the value-object. As an example the keys could be some ID, and the values could be Objects of a `FixedSizeArrayList` class, where the backing array is always the same and can be accessed by the Cache-class (a special subclass is intended). So when the Garbage-Collector decides to finalize the `FixedSizeArrayList`-Object the DriveCache writes the content of the array to the drive and then releases its reference to the array, so it becomes eligible for garbage collection too.
Of course this only works if the value-object and especially its payload-data are not permanently strongly referenced from somewhere else.

In my case the values are Graphs and the Program gets and ordinarily strongly references them from the `DriveCache`, if they are needed and just releases them when its done using them. So if the memory pressure becomes high in the meantime the Graph is written to drive, if not it just remains in the RAM.

On this way the Garbage-Collector de-facto manages if the cache should swap data to drive or not, just based on if a value is currently used or not and depending on the available RAM. So it is highly adaptive to the current environment without tweaking parameters manualy.

And because if the JVM runs out of memory I cannot wait a few more accesses for clean up. Because writing and releasing the payload-data requires one more GC-cycle already, this is time critical anyway. And for values that consume a signification portion of the overall RAM (e.g. 10%) it can be too late already and WeakReferences must be used.

**Comment by ben-manes** [comment]
That makes sense. I’m sure you’re aware, but just in case, soft references have a bad reputation. They fill up the heap, require a full GC (STW pause) to collect, and cause GC storms because only enough memory is freed to continue the application. This caused mayhem in traditional collectors like CMS and global lru meant it wasn’t aware of what data was more costly to reload. Newer GCs are more aggressive, e.g. G1 is region based, so the negative impact might be more tolerable. This bad experience led to Guava switching from evangelizing reference collection to size-based caching using weighted values. Hopefully you don’t suffer these problems, but you might find the approach less useful than it originally seemed.

**Comment by HannesWell** [comment]
I was partly aware of what you've mentioned. Until some point it is desired that the SoftReference fill up the heap, because I want to avoid to unnecessarily write data to the drive in case they would have fit in the memory. On the other hand when it comes to the point that the memory is too small, I agree that frequent small GC-cycles are potentially slowing down the application.
It a dilemma.

The problem I have with size limited or weighted Caches is that even it is likely that the Graphs stored in the DriveCache occupy the vast majority of memory of the JVM (even if it has many GiB) it still possible that some other part of our program also requires a significant amount of memory. Additionally the stored graphs can be relatively small or quite big, it depends on what exactly the user is doing. So a suitable size-limit, that neither causes to frequent writes nor too early out-of-memory errors, is de-facto impossible to guess. It depends on what the user is doing and on the user's machine.

What I have experienced so far is that the SoftReferences tend to be cleared too late, which is probably because the write and clear of the payload-data requires at least one more GC-cycle to really release some data and not only the wrapper around it. And that's probably also a problem for the GC because it does not know that finalizing the softly referenced value triggers the payload-data to be released later too. So I'm already some kind of disenchanted.

I already have implemented the option to use WeakReferences (maybe in conjunction with settings Xms to Xmx to avoid to often GC cycles). Alternatively I thought about a daemon thread that regularly monitors the JVM's memory load with `Runtime.get???Memory()` and 'manually' frees some data selected according to the LRU schema, if the used memory occupancy reaches a certain threshold (e.g. 90%). But this approach doesn't feel right.

**Comment by ben-manes** [comment]
A size-limited cache can use soft-references as a failsafe, but as you note it may not be good enough. If you persist on write rather than write on evict, then you won't have those finalization problems. And if your graph is layed out to be disk-friendly, the I/O read/write might not be expensive as the OS's buffer cache is keeping it too. A library that could be interesting (or not, I've never used it) is [Netflix Graph](https://github.com/Netflix/netflix-graph).

Not knowing your use-case, my bias is to use a traditional cache and persist updates on a write. The cache's policy should make a good guess of what to evict, the application behavior will be more predictable, and you can use soft-references as a failsafe if low on memory.

**Comment by HannesWell** [comment]
The data-structure of the Graph is given, we use the `BinaryResource` of the Eclipse Modelling Framework.
But nevertheless thanks for the link, it looks interesting. Maybe it provides some good ideas (Since it seems to be abandon, it is probably not a good idea to use it directly).

Yes, that sounds reasonable. I'll have to think about it again and hopefully find a better solution.
Thanks a lot for your help.
