### ISSUE TITLE
EventBus: Add options to enable ImmediateDispatcher

### ISSUE THREAD

**Issue by ckloner** [google/guava#5336]
This ticket is almost the same as #2986 but deals with the `EventBus` instead of the `AsycEventBus` object. 

I am using the `EventBus` object not as global object (static or singleton) but on a single instance per user session. In this scenario, instantiating for each `EventBus` instance an instance of `PerThreadQueuedDispatcher` with all the `ThreadLocal` variables does not make much sense. It would be better to have the possibility to use `ImmediateDispatcher.INSTANCE` by making `Dispatcher.immediate()` public - as well as changing the package visibility of the class `Dispatcher` to public. Changing the package visible constructor `EventBus(String,Executor,Dispatcher,SubscriberExceptionHandler)` would enable much more flexibility.

**Comment by ckloner** [comment]
Actually I also found issue #3406 related to this problem now. The most problematic thing is only, that the abstract class `Dispatcher` is package visible. If the implementation of `ImmediateDispatcher`can be used or not, is not that important because the code is trivial and can easily be reimplemented by extending `Dispatcher`. I could also create a Pull request to fix this issue if this is OK and is accepted.

**Comment by netdpb** [comment]
Thanks for your feature request. At this point we are not actively developing EventBus. There are several more modern frameworks for event-driven or reactive programming, including [RxJava](https://github.com/ReactiveX/RxJava) among others.
