### ISSUE TITLE
Guava EOL Versions?

### ISSUE THREAD

**Issue by loganbush789** [google/guava#5356]
I am trying to figure out if there are any EOL versions for Guava, and if so, when do these versions become EOL?

Thanks.

**Comment by jbduncan** [comment]
I was under the assumption that only the latest version is supported, given that Google have the luxury of "[living](https://abseil.io/about/philosophy) at [head](https://dl.acm.org/doi/pdf/10.1145/2854146)" internally.

I don't know what the policy re. security patches are, though.

Any clarification on this would be enlightening.

**Comment by netdpb** [comment]
We do not generally backport bug fixes. We encourage users to use the latest compatible version of Guava.
