### ISSUE TITLE
Migration to travis-ci.com

### ISSUE THREAD

**Issue by AlbertoSinigaglia** [google/guava#5368]
Hi,  
I would like to point out that as reported [in this article](https://docs.travis-ci.com/user/migrate/open-source-repository-migration):  
<p align="center"><i>travis-ci.org will be officially closed down completely no later than December 31st, 2020</i></p>
       
and currently this project is still using **travis-ci.org** and so it's probably a good idea to migrate to **travis-ci.com**

**Comment by cpovirk** [comment]
Thanks. Internally, some people told us about this but also told us that travis-ci.com [requires additional permissions](https://docs.travis-ci.com/user/github-oauth-scopes/) that we shouldn't grant. So we may look into [GitHub Actions](https://github.com/features/actions), similar to [what some other Google projects have done](https://github.com/google/error-prone/commit/745c3c7537ff0f13a3090c12ad5375ca9eb434f9). But we don't have a specific plan yet.

**Comment by cpovirk** [comment]
(Supposedly Travis is planning to loosen the permissions requirement before the turndown. But it doesn't sound like we can rely on that.)

**Comment by cpovirk** [comment]
Fixed by the migration to GitHub Actions: https://github.com/google/guava/commit/2cc42ec016d947a6722e09cea49d2092c2ce4f58
