### ISSUE TITLE
There have no log to recorde exception

### ISSUE THREAD

**Issue by smallYellowCat** [google/guava#5369]
https://github.com/google/guava/blob/98b785aada30c1eec8149b10019a67778b4a77b5/guava/src/com/google/common/cache/LocalCache.java#L3549

In my project occurred a NoSucheMethod excpetion,   but there have no log to recorde this exception,  it is  take my long time to located this problem.

**Comment by kluever** [comment]
This report doesn't contain enough information to diagnose anything, but I suspect you have multiple versions of Guava on your class path.

Please ask questions like this on stackoverflow using the tag `guava`.
