### ISSUE TITLE
Add an immutable computing map

### ISSUE THREAD

**Issue by oliviercailloux** [google/guava#5380]
(Sorry, hit `post` by mistake, and the initial post was empty. Edited afterwards.)

Please consider providing an `ImmutableMap` that works by computing _only once_ the value associated to each key, lazily, and storing the result. Concretely, I propose to add: `Maps#immutableComputingMap(Set<K> keys, Function<K, V> valueProvider): ImmutableMap<K, V>`. The returned map has a constant `keySet()`, the one given by the `keys` parameter at creation time (defensively copied, of course). The returned map behaves as follows: if the value corresponding to some key was never computed yet, compute it using the given function and store the result when needed (lazily); if it ever was, return that previously computed result.

The returned map is indeed immutable in the sense that all the calls on the map are idempotent: calling a given method with given parameters twice always returns the same result.

Use case: a class provides a `getSomeData(): ImmutableMap<K, V>` (for some `K, V`) under the form of a map, that is (in some cases) slow to compute. Initially the whole map is computed at once when `getSomeData()` is called. The designer of the class later wants to change it, upon realizing that in some use cases only a small subset of the keys is used by the callers of that method. Thus, the designer wants to compute the values lazily, only when `get(k)` is called on the returned map.

This idea is not to be mixed up [with](https://github.com/google/guava/wiki/IdeaGraveyard#lazycomputing-map-whose-get-method-returns-a-default-value) [similar](https://github.com/google/guava/issues/764) [ideas](https://github.com/google/guava/issues/489) that have been rejected because they do not satisfy the map contract. This proposal does satisfy the map contract, as far as I can see.

**Comment by DJCoding** [comment]
Hello, can I take this issue?
I already started a basic Implementation of this. But I ran into trouble to choose a super class.
Because the `ImmutableMap` has no information about the computing part. Especially the Builder class lacks the param `Function<K, V> valueProvider`

**Comment by perceptron8** [comment]
@oliviercailloux If `ImmutableMap` involved lazy computing, I wouldn't trust any `ImmutableMap` returned by any API ever again. "Is it safe to pass on?", "Should I iterate over `values()` to trigger loading first?" and so on. I know that it is not specified directly to be so, but most of the times I treat "immutable" as "set in stone".

It is pretty easy to get computing map already using guava cache or caffeine like this:
```java
public static <K, V> Map<K, V> toComputingMap(Set<K> set, Function<? super K, V> function) {
	CacheLoader<? super K, V> loader = CacheLoader.from(function);
	LoadingCache<? super K, V> cache = CacheBuilder.newBuilder().build(loader);
	return Maps.asMap(set, cache::getUnchecked);
}
```

You can make it more immutable-like by taking `ImmutableSet<K>` instead of `Set<K>`.

**Comment by ben-manes** [comment]
In the description, a call like `size()` or `keySet()` would change over time. It would therefore not be immutable, but would be not directly modifiable. Instead it seems like @perceptron8 sample, wrapped with `Collections.unmodifiableMap`, would serve this purpose and require no library changes.

**Comment by oliviercailloux** [comment]
> If `ImmutableMap` involved lazy computing, I wouldn't trust any `ImmutableMap` returned by any API ever again.

Unless I missed something in the documentation, it seems to me that my proposition satisfies the contract of `ImmutableMap`. Therefore, if someone wants `ImmutableMap` to guarantee that it does not “lazy compute anything” (if that is what you suggest, or is it?), then that person should enter a proposal for modification and ask that this guarantee be added to its contract. (Not that I currently see a clear advantage of adding this guarantee or even how this could be specified clearly, as there are multiple ways of loading things lazily or “computing” things – basically it seems to me that this would constrain very much `ImmutableMap` to a single model of implementation. Relatedly, note that some methods of `ImmutableMap` currently do compute some things lazily. But this is another discussion, I think.)

> "Is it safe to pass on?"
What do you mean?

> "Should I iterate over `values()` to trigger loading first?"
Can you please provide an example where this should matter, for making the discussion more concrete?

> It is pretty easy to get computing map already using guava cache or caffeine like this:
Thanks, this is useful. I still think that my proposal makes sense, however.

**Comment by oliviercailloux** [comment]
> I already started a basic Implementation of this. But I ran into trouble to choose a super class.
> Because the `ImmutableMap` has no information about the computing part. Especially the Builder class lacks the param `Function<K, V> valueProvider`

AFAIU, Guava requires that immutability be compile-safe, not merely safe by declaration. It therefore refuses to build lazily using a general Function, which in general the compiler can’t prove is not mutable. My proposal is compatible with this requirement because I propose to use a specific way of computing the values, but using some unspecified function would not necessarily be compatible with this requirement.

**Comment by oliviercailloux** [comment]
> In the description, a call like `size()` or `keySet()` would change over time.

No, it would not: “[The returned map has a constant keySet()](https://github.com/google/guava/issues/5380#issue-787248738)”. Similarly, @perceptron8’s implementation never exhibits a change of size. Please correct me if I am wrong or if anything is unclear.

**Comment by perceptron8** [comment]
> Unless I missed something in the documentation, it seems to me that my proposition satisfies the contract of `ImmutableMap`. Therefore, if someone wants `ImmutableMap` to guarantee that it does not “lazy compute anything” (if that is what you suggest, or is it?), then that person should enter a proposal for modification and ask that this guarantee be added to its contract.

Let me repeat: I do know that this is currently not specified *directly*. And I think you may be right! This should be documented. 

> > "Is it safe to pass on?"
> 
> What do you mean?
> 
> > "Should I iterate over `values()` to trigger loading first?"
> 
> Can you please provide an example where this should matter, for making the discussion more concrete?

Have you ever heard of [LazyInitializationException](https://docs.jboss.org/hibernate/orm/current/javadocs/org/hibernate/LazyInitializationException.html) ;)?

---

According to [ImmutableCollectionsExplained](https://github.com/google/guava/wiki/ImmutableCollectionsExplained#why), one of (many!) Immutable objects advantages is thread safety. I don't think you can make such guarantee in *any* computing map implementation. It won't be enough to place a note in javadoc ("`Function` must be pure or bad things are going to happen eventually"). Thread safety is currently something we all can rely on. Predictability is another. As is truly race-free, concurrent access.

**Comment by perceptron8** [comment]
> @perceptron8’s implementation never exhibits a change of size. Please correct me if I am wrong or if anything is unclear.

In fact, @ben-manes is right about missing `Collections.unmodifiableMap` wrapping. In my sample, if `Set` was modifiable, then `Map` would be too. `Maps.asMap` is a live view.

**Comment by oliviercailloux** [comment]
> Have you ever heard of [LazyInitializationException](https://docs.jboss.org/hibernate/orm/current/javadocs/org/hibernate/LazyInitializationException.html) ;)?

> According to [ImmutableCollectionsExplained](https://github.com/google/guava/wiki/ImmutableCollectionsExplained#why), one of (many!) Immutable objects advantages is thread safety.

These are two excellent points. I agree then that one can reasonably say that my proposal does not comply with (the spirit of) an `ImmutableMap`.

> missing `Collections.unmodifiableMap` wrapping

I don’t think that a `Collections.unmodifiableMap` wrapping would solve the problem, or I don’t see what you mean. I think there is no escape from defensively copying the given set: `Maps.asMap(ImmutableSet.copyOf(set), cache::getUnchecked);`.

Anyway, I suppose this issue can be closed.
