### ISSUE TITLE
Configurable log level for AggregateFuture

### ISSUE THREAD

**Issue by anjor** [google/guava#5393]
**Context**
We use the [whenAllSucceed](https://github.com/google/guava/blob/master/guava/src/com/google/common/util/concurrent/Futures.java#L629) method in Futures to combine futures when batching requests. This is done for the ["fast failing"](https://github.com/google/guava/blob/master/guava/src/com/google/common/util/concurrent/AggregateFuture.java#L115) that AggregateFuture provides.

When more than one future throws an exception, one of the exceptions gets propagated, but the others get logged [here](https://github.com/google/guava/blob/master/guava/src/com/google/common/util/concurrent/AggregateFuture.java#L251) at SEVERE level. For our specific use case, the exceptions don't matter as much because we have retry logic on the server side to handle them.

**Problem**
We have monitoring in place for logging at the SEVERE level. As a result of the above behaviour, our monitors keep firing despite the server handling the retry logic correctly.

**Proposed Solution**
Could we make the logging level configurable? 

It will need to be passed from AggregateFuture to CombinedFuture up to Futures#whenAllSucceed. It could be made optional, and if it isn't set then it falls back to SEVERE to preserve backwards compatibility.

**Comment by cpovirk** [comment]
I have felt bad about this for years, but `util.concurrent` has remained not a priority for us for years, so I'm not sure when that will change.

You can follow along on https://github.com/google/guava/issues/2134. I recently suggested [a workaround](https://github.com/google/guava/issues/2134#issuecomment-726833556) that I haven't tested but that I am hopeful would work.
