### ISSUE TITLE
LoadingCache.get(key)  return some Object guess

### ISSUE THREAD

**Issue by PhenJuly** [google/guava#5399]
The list returned by cache.get("") has the some object, which causes an exception in maps.unqueIndex. The test environment cannot reproduce it. Is it possible for loadingcache.get ("") to get the cached data repeatedly

**Comment by PhenJuly** [comment]
> The list returned by cache.get("") has the some object, which causes an exception in maps.unqueIndex. The test environment cannot reproduce it. Is it possible for loadingcache.get ("") to get the cached data repeatedly

**Comment by PhenJuly** [comment]
> The list returned by cache.get("") has the some object, which causes an exception in maps.unqueIndex. The test environment cannot reproduce it. Is it possible for loadingcache.get ("") to get the cached data repeatedly

**Comment by cgdecker** [comment]
Sorry, it's really unclear to me what you're asking here. Can you provide a [short, self-contained, correct example](http://sscce.org/) demonstrating the problem you're having, or at least an example of what the code you're talking about actually looks like? You mention a "list" returned by `cache.get`, which presumably means your cache has `List<Something>` values... in that case, the contents of the list are not controlled by the cache but by whatever code is populating the cache, so your issue would probably be there.

**Comment by stunnamaneee** [comment]
YHANKS SO MUCH
