### ISSUE TITLE
tryAcquire always returns true when timeout set to >= 1 second

### ISSUE THREAD

**Issue by aadityac** [google/guava#5419]
I have been using tryAcquire method to enforce ratelimits on a function. Example shown below. 

```
public class RateLimitedCallable<T> implements Callable<T> {

    @Override
    public T call() {
        Boolean permitAcquired = RateLimitTest.rateLimiter.tryAcquire(1, 1000,
            TimeUnit.MILLISECONDS);

        if (permitAcquired) {
           // do stuff
        } else {
            throw new RuntimeException("Permit was not granted by RateLimiter");
        }
    }
}

public class RateLimitTest {

    public static final RateLimiter rateLimiter = RateLimiter.create(1.0);

    public void test() {
        RateLimitedCallable<String> callable = new RateLimitedCallable<>();
        callable.call();
        callable.call();
        callable.call();
        callable.call();
    }

    public static void main(String[] args) {
        RateLimitTest limiterTest = new RateLimitTest();
        limiterTest.test();
    } 
}
```

RuntimeException never gets thrown. However, if I change the timeout to values below 1000 ms, for eg: - 

`Boolean permitAcquired = RateLimitTest.rateLimiter.tryAcquire(1, 900, TimeUnit.MILLISECONDS);`

I do see the RunTimeException, which means the ratelimiter works as expected. I don't understand why the ratelimiter doesn't enforce limits when timeout period is greater than equal to 1000ms. Am I doing something wrong?

**Comment by nick-someone** [comment]
> `public static final RateLimiter rateLimiter = RateLimiter.create(1.0);`

It looks like your RateLimiter is configured to emit 1 permit per second, so waiting 1 second to acquire a permit seems appropriate.
