### ISSUE TITLE
ImmutableGraph.delegate() exposes package-private BaseGraph

### ISSUE THREAD

**Issue by Marcono1234** [google/guava#5450]
`com.google.common.graph.ImmutableGraph` inherits and overrides the method `delegate()` which returns the package-private type `BaseGraph`:
https://github.com/google/guava/blob/018796b79b314b5b7790c9320c1a7c89140af76d/guava/src/com/google/common/graph/ImmutableGraph.java#L103

It looks like the method is only used within the same package, so this could be fixed by making both `ForwardingGraph.delegate()` and `ImmutableGraph.delegate()` package-private.

**Comment by cpovirk** [comment]
Thanks. I guess the method is more or less inaccessible to actual users, since they can't subclass `ImmutableGraph` from outside the package, anyway. That makes it pretty safe a cleanup to mark them package-private.
