### ISSUE TITLE
Is it safe to do synchronized(cache)?

### ISSUE THREAD

**Issue by xinzheyang** [google/guava#5462]
Suppose I have a Guava cache object

`Cache<String, String> cache = CacheBuilder.newBuilder().build()`

Is it safe to do
```
synchronized (cache) {
        cache.get(a);
        // some other stuff
        cache.put(b, c)
}
```

Want to make sure synchronized(cache) won't block with internal logic of Guava cache.

**Comment by ben-manes** [comment]
Yes, the cache internalizes its locking and doesn't synchronize on itself. However you should prefer a dedicated lock object when possible, preferably `ReentrantLock`.
