### ISSUE TITLE
Documentation Improvement

### ISSUE THREAD

**Issue by Mikhail-Polivakha** [google/guava#5464]
I have read CONTRIBUTING.md file, but I am still confused about how exactly we should create pull requests. Can you please clarify in documentation - From which exactly branch I should start new branch (to implement the feature). If the answer is not that simple, than also point it out in documentation.

**Comment by jbduncan** [comment]
@Mikhail-Polivakha The general rule in GitHub repositories is to branch from `master` (or `main` if it exists), and Guava follows that rule too. :)

**Comment by nick-someone** [comment]
jbduncan@'s got it.

Note that our pull request process doesn't merge commits directly via GitHub pulls, but will be used to generate a new commit internally and vend it outwards, so it's unlikely to be a major concern about the actual branch point (unless of course the file was updated in the interim).
