### ISSUE TITLE
Ambiguity in the description of DoubleMath.fuzzyEquals

### ISSUE THREAD

**Issue by ThisCakeIsALie** [google/guava#5471]
Hello, the description of `DoubleMath.fuzzyEquals` states:

```
public static boolean fuzzyEquals(double a,
                  double b,
                  double tolerance)
...

Technically speaking, this is equivalent to Math.abs(a - b) <= tolerance || Double.valueOf(a).equals(Double.valueOf(b)).

...

Throws:
IllegalArgumentException - if tolerance is < 0 or NaN

...
```

These two statements contradict each other: If the tolerance is negative `fuzzyEquals` throws an exception while `Math.abs(a - b) <= tolerance || Double.valueOf(a).equals(Double.valueOf(b))` does not.

Changing the first sentence to something like
```
Technically speaking, this is equivalent to Math.abs(a - b) <= tolerance || Double.valueOf(a).equals(Double.valueOf(b)),
unless tolerance <= 0 in which case an IllegalArgumentException is thrown.
```
solves the issue.

**Comment by nick-someone** [comment]
Thanks for filing the issue! Generally preconditions like "the tolerance is non-negative" are encoded as the IllegalArgumentException here suggests.

Similarly, the one-line summary states:

`Returns true if a and b are within tolerance of each other`

which doesn't make sense with tolerance as a negative number.
