### ISSUE TITLE
Make Range extendable

### ISSUE THREAD

**Issue by er1992** [google/guava#5522]
`Range` has been set as a `final` class. Is there any particular reason for this? I am trying to include multiple "types" of ranges in a single `RangeSet` and when querying them back out into a list, I need to know what type were they originally.  I would like to achieve this by adding an enum to `Range` that I can check later.

**Comment by lowasser** [comment]
In general, it is best practice to make classes final whenever possible.  A class cannot be immutable if it is extendable, for example.  Additionally, in this specific case, `TreeRangeSet` does not even necessarily retain your original `Range` objects; it rebuilds them as necessary to handle merging, and would know nothing of a `Range` subtype.

It sounds like it might be appropriate for your use to build a `RangeMap` whose values are the enum type you mentioned.
