### ISSUE TITLE
Support of curly brace placeholders in LenientFormat strings

### ISSUE THREAD

**Issue by HaydenMuscat** [google/guava#5540]
Hi Google! I'll cut to the chase:

At our company, we use `Preconditions` checks to cleanly throw exceptions, but recently realise curly braces weren't supported. I would like to propose adding the more modern `{}` as allowed placeholders in lenient format strings, in addition to the classic `%s`.

https://github.com/google/guava/blob/4cacc0e97fce8bae83983584371450641836983f/guava/src/com/google/common/base/Strings.java#L288

A possible suggestion would be a second inner loop for the second placeholder (so that the old placeholder takes precedence):
```
    template = builder.build();
    builder = new StringBuilder(template.length() + 16 * args.length);
    templateStart = 0;
    while (i < args.length) {
      int placeholderStart = template.indexOf("{}", templateStart);
      if (placeholderStart == -1) {
        break;
      }
      builder.append(template, templateStart, placeholderStart);
      builder.append(args[i++]);
      templateStart = placeholderStart + 2;
    }
    builder.append(template, templateStart, template.length());
```

Happy to create a PR and write tests for this if that helps!

**Comment by cgdecker** [comment]
I don't think we want to support brace format. `Preconditions` is intentionally kept very simple in terms of formatting options.
