### ISSUE TITLE
Addition of isNullOrEmpty method to Maps utility class

### ISSUE THREAD

**Issue by vigneshtdev** [google/guava#5557]
Hi team

I am not sure about cretiria for addition of new feature to Guava. So creating the issue as a proposal to include `isNullOrEmpty` method in Maps class of Guava.

As the name suggests it will return a `boolean` which will be true in case the `Map` object received is null or empty.

Can you share your thoughts on this?

**Comment by cpovirk** [comment]
This is similar to `isNullOrEmpty(Collection)`. We discuss the reasons we've chosen not to add that [here](https://github.com/google/guava/wiki/IdeaGraveyard#iterablesisnullorempty).
