### ISSUE TITLE
First timers.

### ISSUE THREAD

**Issue by D3vil-hunt** [google/guava#5568]
There are no issues labeled for first timers, I am a first timer , If I want to contribute where can I start ?

**Comment by nick-someone** [comment]
Hi! Unfortunately, we don't tend to have issues available for first-time-contributors. 

From the [CONTRIBUTING.md](https://github.com/google/guava/blob/master/CONTRIBUTING.md#how-to-contribute), I think it would be best to discover the existing open issues, and help us by providing feedback on your use-case (e.g.: some  program you're working on that would really be improved by X that doesn't exist, and why the existing features don't solve the problem).

Sorry I don't have a better answer!

**Comment by D3vil-hunt** [comment]
I totally understand :) , Thanks for the assistance.
