### ISSUE TITLE
Joiners add skip predicate

### ISSUE THREAD

**Issue by xenoterracide** [google/guava#5570]
I have a use case where I think I'd like to be able to skip a certain string. my code isn't this simple,

```java
Joiners.on(" ")
    .skip( Predicate.isEqual("zero") )
    .join("zero", "five" ); // five
```

**Comment by amalloy** [comment]
This doesn't really belong in Joiner. Filtering functionality belongs to streams. And fortunately, there is an easy way to accomplish your goal using Stream:

Stream.of("zero", "five")
  .filter(s -> !s.equals("zero"))
  .collect(Collectors.joining(" "))
