### ISSUE TITLE
Why guava ImmutableCollection not allowed a null element?

### ISSUE THREAD

**Issue by minseongkimdev** [google/guava#5600]
hi, thanks for provide graet library, but i have a question which is same with this issuse's title.

ill waiting for your answers. thank you!

**Comment by avinash-ak** [comment]
The guava ImmutableCollection returns false for a null element rather than throwing an exception. The developers might have thought null check is not necessary.
you can do something like this to get the job done-- 
return element != null && example.contains(element);

**Comment by kluever** [comment]
A bit more info here: https://github.com/google/guava/wiki/UsingAndAvoidingNullExplained
