### ISSUE TITLE
Allow clients to configure ExceptionTypePolicy in NullPointerTester

### ISSUE THREAD

**Issue by rishkaul** [google/guava#5643]
`NullPointerTester.java` in `guava/guava-testlib/src/com/google/common/testing/` hard-codes the `policy` field to `ExceptionTypePolicy.NPE_OR_UOE`.

[Code reference](https://github.com/google/guava/blob/master/guava-testlib/src/com/google/common/testing/NullPointerTester.java#L78)

NullPointerTester works well with Lombok `@NonNull` annotations. But you can configure Lombok to throw a different exception like `IllegalArgumentException` using `lombok.nonNull.exceptionType` propery in `lombok.config`.

In such a scenario, you see this exception - [Code reference](https://github.com/google/guava/blob/master/guava-testlib/src/com/google/common/testing/NullPointerTester.java#L357)

I have a few suggestions:
1. Expose public constructors to allow clients to configure policy at the time of construction.
2. Instead of maintaining exception policies in the class itself, enable clients to configure a `Predicate` which would be invoked to assert the validity of the thrown exception.
3. Same as 2, but use a custom functional interface

Thank you.

**Comment by cpovirk** [comment]
Let's reopen https://github.com/google/guava/pull/1949 to keep this conversation in one place.
