### ISSUE TITLE
Incorrect hash result from murmur3_32 with String input containing surrogate pairs

### ISSUE THREAD

**Issue by findepi** [google/guava#5648]
Here is the test program comparing behavior of

- Guava's `Hashing.murmur3_32` with `hashBytes(str.getBytes(encoding))`
- Guava's `Hashing.murmur3_32` with `hashString(str, encoding)`
- Airlift's `Murmur3Hash32.hash(str.getBytes(encoding))` (https://github.com/airlift/slice/blob/d3a025291fd8d6a062e44f3823ee49196783ab9c/src/main/java/io/airlift/slice/Murmur3Hash32.java)

```
public class Murmur
{
    public static void main(String[] args)
    {
        for (String string : List.of("plan ascii", "BMP Piękna łąka w 東京都",  "surrogate pair 💰")) {
            for (Charset charset : List.of(StandardCharsets.UTF_16, StandardCharsets.UTF_8)) {
                int airliftValue = Murmur3Hash32.hash(Slices.wrappedBuffer(string.getBytes(charset)));
                int guavaValue1 = Hashing.murmur3_32().hashBytes(string.getBytes(charset)).asInt();
                int guavaValue2 = Hashing.murmur3_32().hashString(string, charset).asInt();
                System.out.println("airliftValue = " + airliftValue);
                System.out.println("guavaValue1  = " + guavaValue1);
                System.out.println("guavaValue2  = " + guavaValue2);
                System.out.println();
            }
        }
    }
}
```

Results when run with Guava `30.1-jre` and Airlift Slice `0.40`:

Note that results agree except for the last case. I expect them to agree in all cases, especially between the two Guava alternative API methods.

```
string: plan ascii, charset: UTF-16
airliftValue = -731716445
guavaValue1  = -731716445
guavaValue2  = -731716445

string: plan ascii, charset: UTF-8
airliftValue = -218266838
guavaValue1  = -218266838
guavaValue2  = -218266838

string: BMP Piękna łąka w 東京都, charset: UTF-16
airliftValue = -989030725
guavaValue1  = -989030725
guavaValue2  = -989030725

string: BMP Piękna łąka w 東京都, charset: UTF-8
airliftValue = 103331700
guavaValue1  = 103331700
guavaValue2  = 103331700

string: surrogate pair 💰, charset: UTF-16
airliftValue = 2147098392
guavaValue1  = 2147098392
guavaValue2  = 2147098392

string: surrogate pair 💰, charset: UTF-8
airliftValue = -1114908744
guavaValue1  = -1114908744
guavaValue2  = -2027737699
```

cc @losipiuk @wendigo @alexjo2144

**Comment by findepi** [comment]
I suspect that the optimized code path for UTF-8 here https://github.com/google/guava/blob/769e1e9c5ea1c6bddf14cec66b71d6824a8d28a6/guava/src/com/google/common/hash/Murmur3_32HashFunction.java#L147
does not take surrogate pairs into account.

**Comment by findepi** [comment]
cc @rdblue as Iceberg uses the allegedly affected code path when bucketing string/varchar data. See https://github.com/trinodb/trino/pull/8104/files#r655190551 for context.
kudos to @wendigo for finding this.

**Comment by lowasser** [comment]
@findepi, are you sure?  https://github.com/google/guava/blob/769e1e9c5ea1c6bddf14cec66b71d6824a8d28a6/guava/src/com/google/common/hash/Murmur3_32HashFunction.java#L187 seems to be where that gets addressed; it bails out of the first loop as soon as it finds anything non-ASCII.

**Comment by findepi** [comment]
@lowasser the place referenced is decorated with a comment:
```
// not a valid code point; let the JDK handle invalid Unicode
```

here, we're not dealing with invalid Unicode, but i admit i do not understand this code yet.

My lack of understanding was what prompted me to write a "test".
Looking at the methods documentation i was under impression that `guavaValue1 == guavaValue2` should always be true (i am referring to variable names from the test code from the issue description), for all inputs and all encodings.
@lowasser What is your expectation here?

**Comment by findepi** [comment]
I posted a PR for this: https://github.com/google/guava/pull/5649

**Comment by eamonnmcmanus** [comment]
Our current plan is to deprecate `Hashing.murmur3_32()` and introduce a new `Hashing.murmur3_32_fixed()` that is identical except that it has correct behaviour for UTF-8 strings with non-BMP characters. That way we avoid breaking anyone who was using the current incorrect hash values to form keys to persistent storage.
