### ISSUE TITLE
.fun verify domain false

### ISSUE THREAD

**Issue by mafei2021** [google/guava#5675]
I want to verify if a string is a domain name， but a.com is true, a.fun is false 

my code : 
`String domain = "a.fun";
InternetDomainName.from(url).isUnderPublicSuffix()`

I tracked down the source code and found that it was verified here，.fun is not exist

https://github.com/google/guava/blob/master/guava/src/com/google/thirdparty/publicsuffix/PublicSuffixPatterns.java#L45

.fun is ok domain suffix
https://www.ovh.com/world/domains/dotfun.xml

**Comment by eamonnmcmanus** [comment]
I tested your code against Guava 30.1.1-jre and it returned true. Perhaps you are using an old version?

`PublicSuffixPatterns` uses a compact encoding. You generally can't tell whether a given suffix is present just by looking at the strings in `PublicSuffixPatterns`.

**Comment by mafei2021** [comment]
thanks ,my version 19.0   repaired after the upgrade
