### ISSUE TITLE
Add CacheBuilder.recordStats(boolean) to simplify inline style configuration

### ISSUE THREAD

**Issue by andi-livn** [google/guava#5680]
This is just a simple feature request to add a parametrised `CacheBuilder.recordStats(boolean)` setter 

```java
public CacheBuilder<K, V> recordStats(boolean enabled) {
	statsCounterSupplier = enabled ? CACHE_STATS_COUNTER : NULL_STATS_COUNTER;
	return this;
}
```

**Comment by eamonnmcmanus** [comment]
`CacheBuilder` is part of an API that is in maintenance mode. We explicitly recommend using [Caffeine](https://github.com/ben-manes/caffeine/wiki) instead.

In general the `CacheBuilder` API has no way to undo the effect of the various option-methods. I don't see a strong reason to introduce one for this case. If you don't want to record stats then don't call `recordStats()`.

Do you have a particular reason to want this?

**Comment by andi-livn** [comment]
Purely for aesthetic reasons and laziness really. I'm enabling stats collection depending on an external configuration property. And in the absence of a setter that takes a boolean, you loose the benefits of the builder of being able to string together calls. You have to first assemble a `CacheBuilder` to only call `recordStats()` in an `if` block, and finally call `build() `.

**Comment by eamonnmcmanus** [comment]
The same argument applies to the other option methods, like `softValues()` and `weakKeys()`. I think if `CacheBuilder` were still under active development we'd consider it, but as it is I don't think there's a strong enough motivation to make the change.

**Comment by ben-manes** [comment]
You might want to look at [CacheBuilderSpec](https://guava.dev/releases/snapshot-jre/api/docs/com/google/common/cache/CacheBuilderSpec.html) as it provides a little convenience for externalized configurations.

**Comment by andi-livn** [comment]
Thanks. I might give that a shot, or check out Caffeine.
