### ISSUE TITLE
Simple and tricky case

### ISSUE THREAD

**Issue by aspanin** [google/guava#5684]
Hello,

Just simple case: no more than 100 RPS, otherwise the controller is blocked for everyone for 1 minute.
I dug the whole documentation and haven't understood, Everything I have is
`        RateLimiterConfig config = RateLimiterConfig.custom().limitRefreshPeriod(Duration.ofMillis(5000))
                .limitForPeriod(5).timeoutDuration(Duration.ofMillis(10000)).build();`
but there's nothing similar to parking time, penalty etc. 
Please, help.

**Comment by eamonnmcmanus** [comment]
Can you clarify what this is about? Guava doesn't have a `RateLimiterConfig` class.
