### ISSUE TITLE
Table toString

### ISSUE THREAD

**Issue by gongxuanzhang** [google/guava#5700]
Is it possible to put the Interface Table and implementation method toString() like mysql 

<pre>
***********************
***c1       ** c2      *c3*
***********************
***c1       ** c2      *c3*
***********************
</pre>

**Comment by jbduncan** [comment]
@gongxuanzhang Am I right to think that you want a way of printing a `Table` to a string, in the format of the SQL command `SELECT * FROM table`?

If so, then I'm pretty sure that Guava doesn't have this. :(

Have you tried asking this question on StackOverflow with the <kbd>guava</kbd> tag already, by any chance? If not, then that's usually the best place for these sorts of questions.

**Comment by nick-someone** [comment]
> Have you tried asking this question on StackOverflow with the `guava` tag already, by any chance? If not, then that's usually the best place for these sorts of questions.

+1 to this suggestion.

(Also, I edited the comment to make the asterisks more clear as GitHub Markdown was eating them)
