### ISSUE TITLE
AtomicDouble/AtomicDoubleArray accumulate and update methods

### ISSUE THREAD

**Issue by chartung17** [google/guava#5742]
The built-in Java classes AtomicInteger, AtomicLong, AtomicIntegerArray, and AtomicLongArray all implement the methods accumulateAndGet(), getAndAccumulate(), updateAndGet(), and getAndUpdate(). The Guava classes AtomicDouble and AtomicDoubleArray do not currently implement any of those methods.

**Comment by allanhaywood** [comment]
Can you assign this to me, I'd like to work on it.

**Comment by rahulsree** [comment]
Hello - If this issue is still available, could you please assign this to me?

**Comment by allanhaywood** [comment]
Created PR here: https://github.com/google/guava/pull/5784

**Comment by allanhaywood** [comment]
@netdpb Hi David, I linked the PR above. Let me know if you need anything else from me.
