### ISSUE TITLE
Description mistake in SmoothRateLimiter's java doc, line 167

### ISSUE THREAD

**Issue by lijinliangyihao** [google/guava#5763]
It says: `The state of the RateLimiter (storedPermits) is a vertical line in this figure.`, but the **horizontal** line is `storedPermits`.

**Comment by amalloy** [comment]
I'm not sure I agree with your reading of the Javadoc. The *axis* is horizontal, but the drawing seems to suggest drawing a vertical line up from a point on that axis. @cpovirk, I'm not sure who the best person to check this with is, but it looks like you've made more edits to SmoothRateLimiter than anyone else in recent history; perhaps you can confirm my assessment or loop in someone who can?

**Comment by chaoren** [comment]
I agree with Alan. `maxPermits` is a vertical line. `thresholdPermits` is a vertical line. `0` (`storedPermits`) is a vertical line. Those are various "state[s] of the RateLimiter," that the comment refers to. The horizontal axis is called `storedPermits`, but each value (state) along the axis is a vertical line.

**Comment by lijinliangyihao** [comment]
@chaoren Thank you for your kindly explanation, now I understand.
