### ISSUE TITLE
Efficient implementation for MapMakerInternalMap#compute

### ISSUE THREAD

**Issue by TheMode** [google/guava#5766]
The map created by `MapMaker#build` currently use the inefficient `compute` implementation from `ConcurrentMap`. I assume that it could be optimized for atomic operations by reducing lookups and locking it. Contention will also cause the mapping function to be ran multiple time, preventing atomic update.

**Comment by ben-manes** [comment]
An implementation for the compute and merge methods exists in `CacheBuilder`, which has an `asMap()` view. It was forked from `MapMaker`, which remains for historical reasons and sneakily used by Interners. Likely you should use that instead and refrain from using MapMaker. There have been pains with those compute methods, though, so another alternative is Caffeine which offers a more robust implementation with fine-grained locking.
