### ISSUE TITLE
testlib should not depend on guava

### ISSUE THREAD

**Issue by h908714124** [google/guava#5796]
Currently guava-testlib has a dependency on guava in its pom.
This is a potential problem when testing guava itself, because now the guava classes are duplicated
in guava's test classpath.

Only package `com.google.common.collect.testing.google` needs the guava dependency. Maybe these specialized testers can be split off as a separate artifact, or moved into guava's `src/test` folder?

**Comment by netdpb** [comment]
Many classes in guava-testlib use classes in guava proper, not only those in that package. And in fact we use the code in guava-testlib to test Guava itself. I'm not sure I understand your question.

Closing, but feel free to add more information.

**Comment by h908714124** [comment]
Take a look at [ImmutableListMultimapTest](https://github.com/google/guava/blob/master/guava-tests/test/com/google/common/collect/ImmutableListMultimapTest.java), for example.
It uses [ListMultimapTestSuiteBuilder](https://github.com/google/guava/blob/master/guava-testlib/src/com/google/common/collect/testing/google/ListMultimapTestSuiteBuilder.java) to verify that `ImmutableListMultimap` implements the `ListMultimap` interface correctly.
But [guava-testlib has a maven dependency on guava](https://repo1.maven.org/maven2/com/google/guava/guava-testlib/31.0.1-jre/guava-testlib-31.0.1-jre.pom). So it pulls `ImmutableListMultimap` from the released guava artifact into the test classpath.
The end result is that `ImmutableListMultimapTest` has `ImmutableListMultimap` twice in its classpath. The test might not be sensitive to changes in guava's `src/main/java` folder because it's testing the wrong copy of `ImmutableListMultimap`, i.e. the one from the released artifact.

One obvious solution would be to split off an artifact `guava-interfaces` which contains `ListMultimap` but not `ImmutableListMultimap`. Then, `guava-testlib` should only depend on `guava-interfaces`, but not on `guava` proper.

**Comment by netdpb** [comment]
`guava-tests` depends on `guava-testlib`, which depends on `guava`. `ImmutableListMultimap` exists only in `guava`, so it should appear only once in the classpath for the tests.

The code at head uses `HEAD-jre-SNAPSHOT` for all modules (except the `guava/android` flavors, which use `HEAD-android-SNAPSHOT`), so there shouldn't be any version skew when running tests either.

```
$ mvn -am -pl guava-tests dependency:tree -Dincludes=com.google.guava:guava
...
[INFO] com.google.guava:guava-tests:jar:HEAD-jre-SNAPSHOT
[INFO] \- com.google.guava:guava-testlib:jar:HEAD-jre-SNAPSHOT:test
[INFO]    \- com.google.guava:guava:jar:HEAD-jre-SNAPSHOT:test
```

Please let me know if I'm misunderstanding something.

**Comment by h908714124** [comment]
OK, fair enough. Why change it when it works? I just thought it looks like a circular dependency.

**Comment by netdpb** [comment]
OK. Thanks for flagging a potential issue!

**Comment by h908714124** [comment]
Sure, you're welcome 😉
