### ISSUE TITLE
Remove @Beta from ListenableScheduledFuture

### ISSUE THREAD

**Issue by ahimani** [google/guava#5806]
ListeningScheduledExecutorService is not marked as beta but using it results in unstable warning as the signature references ListenableScheduledFuture which has been marked as beta.

Today in order to avoid errors consumers need to either suppress the warning or downcast to a ScheduledFuture or ListenableFuture to use the result from `ListeningScheduledExecutorService#schedule` method.

Similar to https://github.com/google/guava/issues/3340

**Comment by kluever** [comment]
This was fixed 2021-12-14.
