### ISSUE TITLE
MAX_LENGTH incorrectly used for length check

### ISSUE THREAD

**Issue by biecho** [google/guava#5808]
In InternetDomainName.java:102 MAX_LENGTH is defined as 253, with the justification that after rfc2181 at most 255 octets may be used (1 is used for the length, 1 for the root). 

In line 145, the MAX_LENGTH variable is used to check name.length(). But length() returns the number of Unicode code units and not octets. I think there is an inconsistency here.

**Comment by cpovirk** [comment]
Interesting. This seems like something that @cdberry-zz may have already thought about?

**Comment by cdberry-zz** [comment]
This is unfortunately an intractable problem. The actual RFC-specified length constraints are on the [Punycode](https://en.wikipedia.org/wiki/Punycode) encodings of the name parts, and `InternetDomainName` can't have a dependency on a third-party Punycode library for various reasons. If more accurate validation of Unicode names is needed, I suggest you use such a library (e.g. [ICU](https://unicode-org.github.io/icu/userguide/icu4j/)), then pass the domain into `InternetDomainName` if it passes validation.

**Comment by biecho** [comment]
Thanks to both of you.
