### ISSUE TITLE
Question: Why RegularImmutableMap.fromEntryArray enforces "not null" policy on values?

### ISSUE THREAD

**Issue by minherz** [google/guava#5844]
I try to use `ImmutableMap.copyOf()` method which eventually calls to `RegularImuutableMap.fromEntryArray()` which eventuall fails on https://github.com/google/guava/blob/448e326ee1ea0b45b81945b57af93198620ada53/guava/src/com/google/common/collect/RegularImmutableMap.java#L128

While it makes sense to enforce non-null keys it is unclear why this generic implementation enforces values to be not null too.
Can you explain what will mean to relax this requirement to allow null values?

**Comment by perceptron8** [comment]
https://github.com/google/guava/wiki/UsingAndAvoidingNullExplained
