### ISSUE TITLE
针对 Rang 函数，建议增加 新的构造器  fromString(....)

### ISSUE THREAD

**Issue by haozm** [google/guava#5853]
example:
Rang<Int> intRang = Rang.fromString("(4,7)");

Rang<Int> intRang = Rang.fromString("[4,7)");

从 toString  的逆向 工程 是很不错的思维模式~~~~~

**Comment by chaoren** [comment]
Thank you for the suggestion, but I don't think this is a good idea.

1. `Range` supports arbitrary `Comparable` type parameters, so we can't just have it parse only integers.
2. Parsing data from a String prevents static type checking and could lead to runtime errors if the input String is malformed.

There's is no clear benefit to adding this either. There's no compelling reason to have an inverse of the `toString()` method.
