### ISSUE TITLE
Vulnerabilities reported by Veracode

### ISSUE THREAD

**Issue by shyam94** [google/guava#5902]
Hi,

Veracode scan reported Medium Vulnerability found in **google-guava-30.0.jar.**

1. **File:** com/google/common/util/concurrent/SequentialExecutor.java
   **Line no:** 235
   **CWE ID:** 117
   **Reason:**  Improper Output Neutralization for Logs. A function call could result in a log forging attack. Writing untrusted data into 
                       a log file allows an attacker to forge log entries or inject malicious content into log files. (More details on CWE).

Please let me know if this can be considered false Positive or needs to be addressed.

Thanks,
Shyam Joshi

**Comment by netdpb** [comment]
Hi @shyam94. Please report potential security vulnerabilities using these instructions: https://github.com/google/guava/security/policy. Thank you.

**Comment by evanyang1** [comment]
anything else for this issue that should be worked on? Or I should work on? Otherwise it should be closed?

**Comment by netdpb** [comment]
Closing for now. Thanks for the ping.
