### ISSUE TITLE
can import be optional - com.google.common.util.concurrent.internal

### ISSUE THREAD

**Issue by flaviodonze** [google/guava#5916]
guava jars after version 27.0-jre to version 31.0.1.jre contain the following Import-Package declaration: `com.google.common.util.concurrent.internal`

Is this dependency really required or could it be optional? Optional would make it less difficult to use the guava bundle.

I also found this description, which sounds like Optional would be possible:
https://mvnrepository.com/artifact/com.google.guava/failureaccess
_Contains com.google.common.util.concurrent.internal.InternalFutureFailureAccess and InternalFutures. Most users will never need to use this artifact. Its classes is conceptually a part of Guava, but they're in this separate artifact so that Android libraries can use them without pulling in all of Guava (just as they can use ListenableFuture by depending on the listenablefuture artifact)._

MANIFEST.MF:
`Import-Package: com.google.common.util.concurrent.internal;version="[1.0
 ,2)",javax.annotation;resolution:=optional;version="[3.0,4)",javax.cryp
 to;resolution:=optional,javax.crypto.spec;resolution:=optional,sun.misc
 ;resolution:=optional`

**Comment by nick-someone** [comment]
The dependency graph is basically:

```dot
Guava -> failureaccess
listenablefuture -> failureaccess
```

In that both artifacts require `failureaccess` as a runtime dependency to perform their work.

Is there a specific issue you're referring to with "Optional would make it less difficult to use the guava bundle."?

**Comment by flaviodonze** [comment]
With "less difficult" I mean "using only one bundle instead of multiple, like in previous versions".

**Comment by cpovirk** [comment]
`com.google.common.util.concurrent.internal` is necessary for users of `com.google.common.util.concurrent`.

"Most users will never need to use this artifact" is not a good explanation -- sorry. The real point that most users will never directly reference the classes from that artifact. However, those classes are still used internally from Guava.

Over time, the decision to add this dependency has continued to look worse: There's been talk of implementing the interfaces it exposes from Android and other libraries, but I don't think it's happened yet. Sorry for the trouble.

**Comment by flaviodonze** [comment]
Thanks for the explanation, was hoping this might be a minor change.
