### ISSUE TITLE
Getting an incorrect value back when the cache reloads.

### ISSUE THREAD

**Issue by srana6** [google/guava#5922]
I am using Guava cache with refreshAfterWrite(). I have set the TTL to 60 sec.

```
        private LoadingCache<ServiceCacheLoader.ServiceKey, Optional<Service>> getOrCreateIfAbsent(CacheConfiguration cacheConfiguration,
                CacheLoader<ServiceCacheLoader.ServiceKey, Optional<Service>> cacheLoader) {
            assert cacheConfiguration != null : "cacheConfiguration:null";
            assert cacheLoader != null : "cacheLoader:null";

            LoadingCache<ServiceCacheLoader.ServiceKey, Optional<Service>> cache = cacheInstance.get();
            if (cache == null) {
                cache = CacheBuilder.newBuilder()
                        .refreshAfterWrite(cacheConfiguration.getTimeToLiveInSeconds(), TimeUnit.SECONDS) // 60 seconds
                        .maximumSize(cacheConfiguration.getMaximumSize())
                        .concurrencyLevel(cacheConfiguration.getConcurrencyLevel()).build(cacheLoader);
                cacheInstance.compareAndSet(null, cache);
            }
            return cache;
        }
```
I am setting the key of type ServiceKey object.

```
public final class ServiceKey {

    private final String authority; // not unique
    private final String serviceKey; // not unique
    private final String consumerKey; // unique 

    // ..other fields like setter getters, hashcode, and equals
}
```

```
private static final Executor BACKGROUND_CACHE_EXECUTOR = MoreExecutors
        .getExitingExecutorService(new ThreadPoolExecutor(1, 5, 30, TimeUnit.SECONDS,
                new LinkedBlockingQueue<Runnable>())); // set on class level
    
public ListenableFuture<Optional<Service>> reload(final ServiceKey serviceKey,
            final Optional<Service> previousValue) {
        final ListenableFutureTask<Optional<Service>> task = ListenableFutureTask
                .create(new Callable<Optional<Service>>() {
                    @Override
                    public Optional<Service> call() throws Exception {
                        try {
                            return load(serviceKey);
                        } catch (final Exception ex) {
                            ERROR_REPORTER.report(ServiceCacheLoader.class.getName() + ".error.loadingService", ex,
                                    serviceKey, ex.getMessage(), previousValue.orNull());
                            throw new RuntimeException(ex);
                        }
                    }
                });
        BACKGROUND_CACHE_EXECUTOR.execute(task);
        return task;
    }
```
I am seeing a strange behavior whenever cache expires and the `reload` function is called. On `reload` I am getting the wrong previous value for the key I am currently querying the cache with. Let's say my cache has Key 1 -> val1 and Key2 -> val2. On reload I get Key1 -> val2 back. Can someone help me understand this behavior? Give me some pointers on why this could be happening? This issue doesn't happen if I use expireAfterWrite().

My suspicion is something funky going on with threading though I can't pinpoint what. I am able to reproduce the issue by doing the following steps in server debug mode.
1. Make call1 with authority ("dev"), serviceKey ("v1"), and consumerKey("1234"). Entry is created in cache and I get back results successfully.
2.  Make call2 with authority ("dev"), serviceKey ("v1"), and consumerKey("4567"). Entry is created in cache and I get back results successfully.
3. Make call1 again. Entry is expired by now so `reload` method is called. This in turn calls the load method and I get back results successfully.
4. Make call2 again. Entry is expired by now so `reload` method is called. This in turn calls the load method and I get back results successfully.
5. Make call2 again. Call fails because now cache returns call1 value. So confused on this step.

**Comment by ben-manes** [comment]
It sounds like your cache loader has some mutable state that is causing it to load for the wrong key. You can also experience surprising behavior if the key or value is mutated, or if the key has an incorrect equals/hashCode implementation.

**Comment by srana6** [comment]
@ben-manes I am using Guava's hashcode and equals generator. Doesn't seem anything funky.

```
        @Override
        public boolean equals(Object o) {
            if (this == o) return true;
            if (o == null || getClass() != o.getClass()) return false;
            ServiceKey that = (ServiceKey) o;
            return Objects.equal(authority, that.authority) && Objects.equal(serviceKey, that.serviceKey) && Objects.equal(consumerKey, that.consumerKey);
        }

        @Override
        public int hashCode() {
            return Objects.hashCode(authority, serviceKey, consumerKey);
        }
```

**Comment by ben-manes** [comment]
yes, that looks good. Is your cache loader dependent on other mutable data? Typically it is that something else is not synchronized correctly and causing data races. Ideally the cache loader is a idempotent, e.g. just runs a SQL query, but you might be calling other internal services that are not thread safe. If I was in your shoes then I would add logging and asserts to track down the problem.

**Comment by srana6** [comment]
Yes, cache brings the data from a service call. Does mutable data play a role in cache? I thought if my keys are unique and the entry expires it will always bring the same data and update the same key.

Thanks for the suggestion I will dig deep.

**Comment by srana6** [comment]
@ben-manes thank you so much for the pointers so by digging deep I found out the issue is with the Oauth session. I make a service call to bring some values which are then inserted into the cache. On cache reload for some reason the Oauth session value is coming out to be the one that should be for User associated with `Key1` therefore the value of `Key1` is inserted into `Key2`. I need to figure out why this weird behavior is happening on cache reload.

**Comment by srana6** [comment]
@ben-manes So found out this piece of code on the class level is causing the issue -
```
private static final Executor BACKGROUND_CACHE_EXECUTOR = MoreExecutors
        .getExitingExecutorService(new ThreadPoolExecutor(1, 5, 30, TimeUnit.SECONDS,
                new LinkedBlockingQueue<Runnable>())); // set on class level
```
This class is instantiated once for the time server is running locally. On cache reload the thread was the same that was used in the context of Key1 hence the wrong OAuth session is pulled which resulted in wrong values. I am not sure if it is a good practice but moving this instantiation to `reload` method fixed the issue. Is it okay to assign executors every time reload is called?

```
public ListenableFuture<Optional<Service>> reload(final ServiceKey serviceKey,
            final Optional<Service> previousValue) {

       Executor BACKGROUND_CACHE_EXECUTOR = MoreExecutors
        .getExitingExecutorService(new ThreadPoolExecutor(1, 5, 30, TimeUnit.SECONDS,
                new LinkedBlockingQueue<Runnable>()));
        final ListenableFutureTask<Optional<Service>> task = ListenableFutureTask
                .create(new Callable<Optional<Service>>() {
                    @Override
                    public Optional<Service> call() throws Exception {
                        try {
                            return load(serviceKey);
                        } catch (final Exception ex) {
                            ERROR_REPORTER.report(ServiceCacheLoader.class.getName() + ".error.loadingService", ex,
                                    serviceKey, ex.getMessage(), previousValue.orNull());
                            throw new RuntimeException(ex);
                        }
                    }
                });
        BACKGROUND_CACHE_EXECUTOR.execute(task);
        return task;
    }
```

**Comment by ben-manes** [comment]
The problem in your fix is that it creates a new thread per call which is never stopped, causing a memory leak and no reuse. It sounds like you don't manage request-scoped / thread-local state cleanly which causes a data leak. If you did this approach then I would use an explicit `Thread` which will exit when the task is done. Ideally the data leak should be fixed, though.
