### ISSUE TITLE
RateLimiter  is marked unstable with @Beta 

### ISSUE THREAD

**Issue by 2625180201** [google/guava#5959]
My compiler shows as below, how should i fix it? use other class?
'com.google.common.util.concurrent.RateLimiter' is marked unstable with @Beta

**Comment by jbduncan** [comment]
Depending on if you're in a team that cares about that sort of compiler message, either ignore the message or look into an equivalent library like [resilience4j](https://resilience4j.readme.io/).

**Comment by eamonnmcmanus** [comment]
Duplicate of #5612.
