### ISSUE TITLE
Too hard to extend Multimaps

### ISSUE THREAD

**Issue by nakulj** [google/guava#5968]
I'd like to create a custom mutable `Multimap` that tracks changed keys. Something like...

```java
class TrackingMultimap<K,V> implements ListMultimap<K,V> {
  private final Set<K> dirtyKeys = new Set<K>();
  private final ArrayListMultimap<K,V> store;

  public TrackingMultimap (ListMultiMap original) {
    store = ArrayListMultimap.copyOf(original);
  }
}
```

The problem with this approach is that it requires me to reimplement the entire `ListMultimap` interface, most of which would just be dummy 'forwarding' to the underlying `store`'s methods. This seems especially tedious considering that most of the methods could have sensible default implementations; for example:

```java
boolean putAll(K key, Iterable<? extends V> values) {
   values.forEach(value->this.put(key ,value));
}
```

It would be nice to be able to just provide a store and hooks to `put` and optionally `remove`, and have the library generate sensible implementations for the rest of the methods.

**Comment by nakulj** [comment]
Nevermind, I think I can do this with `ForwardingMultimap`.

**Comment by kevinb9n** [comment]
Hope it works out well for you.
