### ISSUE TITLE
Evolve CharMatcher

### ISSUE THREAD

**Issue by ohoho7** [google/guava#5987]
We are living in fast pacing world.
To be on top of the IT world we need to evolve quickly.

Having that in mind can we please evolve Charmande... tfu... CharMatcher (https://github.com/google/guava/blob/master/guava/src/com/google/common/base/CharMatcher.java#L65)
to Char(W)izard?

**Comment by kevinb9n** [comment]
Hmm, I need to assign this to Greg Kick

**Comment by digambar-t7** [comment]
Hey there!! I was looking forward to this issue.Can you please elaborate it.

**Comment by JanecekPetr** [comment]
> Hey there!! I was looking forward to this issue.Can you please elaborate it.

It was a Pokémon-based joke. I'm not entirely sure why the ticket is still open.

**Comment by kevinb9n** [comment]
Yeah, I think we like our friend the way she is.
