### ISSUE TITLE
AsyncEventBus: Enhance access to dispatcher queue

### ISSUE THREAD

**Issue by original-codematrix** [google/guava#5991]
At the moment the `AsyncEventBus` doesn't have a way to monitor its `Queue`. The `AsyncEventBus` is using the `LegacyAsyncDispatcher` which has internally a `private final ConcurrentLinkedQueue<EventWithSubscriber> queue = Queues.newConcurrentLinkedQueue();` field. At the current state, we have no way without reflections to gain information about the given queue. It would make it easier to monitor the queue size etc. when we would have access to the field or at least have a getter that returns the size of the queue.

**Comment by cpovirk** [comment]
We've been discouraging use of EventBus: See https://guava.dev/EventBus. Given that, we're not planning to take any further enhancements to it.
