### ISSUE TITLE
Version -jre/-android suffixes throw off automated tools such as (some) security vulnerability scanner upgraders

### ISSUE THREAD

**Issue by vorburger** [google/guava#6001]
Guava's widely used Maven artifacts [releases](https://github.com/google/guava/releases) currently use `-jre` and `-android` suffixes in their `version`. While https://maven.apache.org/pom.html#Dependency_Version_Requirement_Specification seems to allow for such "qualifiers", perhaps simply putting this into the `artifactId` (as `guava-jre` and `guava-android`) could be more appropriate.

This does appear to cause at least some "real issues", e.g. it seems to "throw off" at least some automated tools which try to be "smart" about comparing version numbers.

For example, GitHub's own widely used Dependabot security vulnerability scanner automatic upgrade pull request proposer doesn't seem to correctly dig these "qualifiers". I have an example ([here](https://github.com/vorburger/HoTea/security/dependabot/1), but it's probably not publicly accessible?) where an old Guava version `18.0` fails to be correctly automatically upgraded to a current `31.1-jre` because, supposedly:

    Dependabot cannot update com.google.guava:guava to a non-vulnerable version
    Could not find a compatible non-vulnerable version. Has it been released yet?

Given that [it works for JUnit](https://github.com/vorburger/HoTea/pull/2/files), I suspect what tripped must have been not understanding that `31.1-jre` > `18.0`.

While one could argue that any such tools like Dependabot that compare Maven version numbers should be "smarter", it may be simpler for Guava to just use simpler `x.y.z` version numbers, to avoid such problems. 

https://semver.org doesn't allow for such "special qualifiers" either.

**Comment by jbduncan** [comment]
An alternative to this is PR https://github.com/google/guava/pull/3683, which introduces Gradle module metadata on top of the POM, to allow tools to understand that qualifiers are distinct from the version numbers.

**Comment by cpovirk** [comment]
I have been pleasantly surprised that Dependabot somehow handles the suffix _if_ it's already present, as in https://github.com/google/truth/pull/956. It's unfortunate that it doesn't also upgrade old versions, but it's hard to blame Dependabot for our weird choices :) (I went looking a couple times for the Dependabot code that handles this and didn't find it. Either I was looking in the wrong place, or it's general-purpose enough that my searches for Guava-isms didn't turn it up.)

As @jbduncan says, https://github.com/google/guava/pull/3683 will (eventually...) help at least Gradle. Perhaps Dependabot itself will understand the metadata it provides someday, too.

In any case, all the available options are pretty bad, including having a separate `artifactId` for each. See https://github.com/google/guava/issues/2914 and https://docs.google.com/document/d/1NYGbfz56C0Oh4IGymXjeQUVK4FcRiqDbpc4vGLnDMrY/edit. I still feel least bad about the `version` approach, but it is worth noting that I don't remember discussion of Dependabot in past discussions, so I now feel less less bad....

I don't think there's anything we can do at this point that would make things less bad on net (especially now that we already have `-jre` versions in the wild, so maybe Dependabot would refuse to upgrade _from_ those back to "normal" versions??), much as I would love to be proven wrong.
