### ISSUE TITLE
RateLimiter: the return value of acquire is 0.0 regardless of any values

### ISSUE THREAD

**Issue by timewizhan** [google/guava#6003]
I found the return value is always 0.0 in RateLimiter (version "31.1-jre")
```
val ratelimiter = RateLimiter.create(100000.toDouble(), Duration.ofMillis(100))

while (true) {
    ratelimiter.acquire()
    Thread.sleep(100)
}
1 => 0.0
2 => 0.0
3 => 0.0
4 => 0.0
5 => 0.0
```
If the permitsPerSecond is changed to less than 10.0, the return value is executed well
```
val ratelimiter = RateLimiter.create(5.toDouble(), Duration.ofMillis(100))

while (true) {
    ratelimiter.acquire()
    Thread.sleep(100)
}

1 => 0.0
2 => 0.147916
3 => 0.096518
4 => 0.097566
5 => 0.097957
```
So... weird. Am I using it wrong?

**Comment by nick-someone** [comment]
https://guava.dev/releases/snapshot-jre/api/docs/com/google/common/util/concurrent/RateLimiter.html#acquire()

> Acquires a single permit from this RateLimiter, blocking until the request can be granted. Tells the amount of time slept, if any.

If the rate limiter is only being asked for 1 permit per every 100ms, per your sample code, the behavior you're seeing makes sense. Try sleeping for less time in between permit acquires to see what changes.
