### ISSUE TITLE
Starting from Guava 31.0: android flavor is not Java 7 compatible anymore

### ISSUE THREAD

**Issue by davidvarga** [google/guava#6014]
Tried with Gradle:

`api group: 'com.google.guava', name: 'guava', version: '31.0-android'

The issue is triggered by this transitive dependency `No matching variant of org.checkerframework:checker-qual:3.12.0 was found. `.

Downgrading to Guava 30.1.1 seems to solve the issue:

`implementation group: 'com.google.guava', name: 'guava', version: '30.1.1-android'`

Thanks!

**Comment by cpovirk** [comment]
There's some coverage of this in [the release notes](https://github.com/google/guava/releases/tag/v31.0) (and an associated [announcement](https://groups.google.com/g/guava-announce/c/EIMDZF4dIdY) and [issue](https://github.com/google/guava/issues/5269), plus [some hacky runtime warnings in older versions](https://github.com/google/guava/issues/5269#issuecomment-860766247), though that was a pretty weird thing for us to do :)). At this point, we're committed to keeping it that way. But if this is causing you difficulties, or if there are other ways you can think of that we could get the word out better when we drop support for Java versions, we'd be interested in hearing about it to help our future work.
