### ISSUE TITLE
PerThreadQueuedDispatcher and ImmediateDispatcher

### ISSUE THREAD

**Issue by wy545** [google/guava#6016]
there are four events, their relations are: A -> B , A -> C, B ->D
now, we use eventbus and PerThreadQueuedDispatcher，event execute as follow A B C D. However, we need A B D then C, ImmediateDispatcher can meet our need. But, ImmediateDispatcher is private and we cannot use, why?
please help me

**Comment by wy545** [comment]
<img width="703" alt="image" src="https://user-images.githubusercontent.com/20380902/163580017-bf4a0ce1-7473-43b0-9789-eec894da90a7.png">

I think  dispatching's design is error, you must according to event type to avoid reentrant event dispatching

**Comment by chaoren** [comment]
Thanks for your feature request. At this point we are not actively developing EventBus. There are several more modern frameworks for event-driven or reactive programming, including [RxJava](https://github.com/ReactiveX/RxJava) among others.

See https://github.com/google/guava/issues/2986 and https://github.com/google/guava/issues/5336.
