### ISSUE TITLE
Integration of guava into OSS-Fuzz

### ISSUE THREAD

**Issue by onionpsy** [google/guava#6043]
Hi all,

I have prepared the initial integration https://github.com/CodeIntelligenceTesting/oss-fuzz/commit/a9d7c011c20c7676b9ff3366419ffe69a818ea66 of guava into [google oss-fuzz](https://github.com/google/oss-fuzz). This will enable continuous fuzzing of this project, which will be conducted by Google. Bugs that will be found by fuzzing will be reported to you. After the initial integration of this project into oss-fuzz, I will continue to add additional fuzz tests to improve the code coverage over time.

The integration requires a primary contact, someone to deal with the bug reports submitted by oss-fuzz. The email address needs to belong to an established project committer and be associated with a Google account as per [here](https://google.github.io/oss-fuzz/getting-started/accepting-new-projects/). When a bug is found, you will receive an email that will provide you with access to ClusterFuzz, crash reports, and fuzzer statistics. More than 1 person can be included. Please let me know who I should include, if anyone.

[Jazzer](https://github.com/CodeIntelligenceTesting/jazzer) is used for fuzzing Java applications. Jazzer is a coverage-guided, in-process fuzzer for the JVM platform developed by Code Intelligence. It is based on libFuzzer and brings many of its instrumentation-powered mutation features to the JVM. Jazzer has already found several bugs in JVM applications: [Jazzer Findings](https://github.com/CodeIntelligenceTesting/jazzer#findings)

Please let me know if you have any questions regarding fuzzing or the oss-fuzz integration.

**Comment by eamonnmcmanus** [comment]
Thanks, we're looking into this and will get back to you. Meanwhile, could I ask that the new code be compatible with Google Java Style? That means two-space indentation and imports sorted in one block with no wildcard-imports.

**Comment by onionpsy** [comment]
Perfect thank you. I contacted one of the maintainer of OSS-Fuzz and they don't enforce any coding style for the integration of the projects https://github.com/google/oss-fuzz/issues/7689. So as all the fuzz targets already integrated were written with 4 spaces indentation I prefer to keep this for consistency reasons. However I'll remove the wildcard and the extra lines between import blocks.

**Comment by eamonnmcmanus** [comment]
Hi, you can sign me up as the primary contact. You can find my Google email address [here](https://github.com/google/guava/commit/6e9057d0f28799b7483d96097fc7ea2247ebf8d5.patch).

**Comment by onionpsy** [comment]
Great thank you. I close the issue, feel free to contact me if you have any question.
