### ISSUE TITLE
The Supplier  is difference between guava-jre and guava-andorid, is this expected?

### ISSUE THREAD

**Issue by Kevingu1001** [google/guava#6062]
https://github.com/google/guava/blob/master/guava/src/com/google/common/base/Supplier.java#L42
https://github.com/google/guava/blob/master/android/guava/src/com/google/common/base/Supplier.java#L50

The class in Android version removed the extend relationship of java.util.function.Supplier, but it is retained in the JRE version.

**Comment by cpovirk** [comment]
Yes, we do this to maintain compatibility with older versions of Android for users who don't use library desugaring:

- https://github.com/google/guava#important-warnings
- https://groups.google.com/g/guava-announce/c/EIMDZF4dIdY
- https://github.com/google/guava/releases/tag/v31.0
