### ISSUE TITLE
IndexedLinkedList to Guava?

### ISSUE THREAD

**Issue by coderodde** [google/guava#6075]
I have implemented [IndexedLinkedList](https://github.com/coderodde/IndexedLinkedList) - a succint, heuristic linked list, that runs in a versatile benchmark faster by an order of magnitude than ArrayList/LinkedList.

What do you think? Does it deserve to be included in Guava?

**Comment by amalloy** [comment]
We're not really looking for new collection implementations for Guava at this time.
