### ISSUE TITLE
Step failed java.lang.NoSuchMethodError: 'com.google.common.collect.ImmutableMap com.google.common.collect.ImmutableMap.of(java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object)'

### ISSUE THREAD

**Issue by pjbabin** [google/guava#6081]
I cannot believe I am the only one getting this error:

Step failed
java.lang.NoSuchMethodError: 'com.google.common.collect.ImmutableMap com.google.common.collect.ImmutableMap.of(java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object)'
	at org.openqa.selenium.chrome.AddHasCasting.getAdditionalCommands(AddHasCasting.java:38)
	at org.openqa.selenium.chrome.ChromeDriver$ChromeDriverCommandExecutor.getExtraCommands(ChromeDriver.java:123)
	at org.openqa.selenium.chrome.ChromeDriver$ChromeDriverCommandExecutor.<init>(ChromeDriver.java:118)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:106)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:93)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:48)
	at PageObjectModel.DriverInitializer.getDriver(DriverInitializer.java:31)
	at StepDefinitions.ProductionSmokeTestStepdefs.iOpenTheBrowser(ProductionSmokeTestStepdefs.java:22)
	at ?.I start TC-22827 by opening the browser(file:///C:/Automation/ProductionPatchesSmokeTest/src/test/Resources/Features/ProductionSmokeTest.feature:4)

I see this has been going on for YEARS and YEARS, every search comes up with ideas, that work at that time, but NONE are working for me.

This should be FIXED !

Anyway, not sure what information will help now, but this is my pom.xml - all the latest versions as far as I can tell

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>ProductionPatchesSmokeTest</artifactId>
    <version>1.0-SNAPSHOT</version>
    <dependencies>
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-java</artifactId>
            <version>7.3.4</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-api</artifactId>
            <version>4.2.2</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-chrome-driver</artifactId>
            <version>4.2.2</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.github.bonigarcia</groupId>
            <artifactId>webdrivermanager</artifactId>
            <version>5.2.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <version>3.23.1</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>31.1-jre</version>
        </dependency>
        <dependency>
            <groupId>com.google.javascript</groupId>
            <artifactId>closure-compiler</artifactId>
            <version>v20220601</version>
        </dependency>
    </dependencies>

    <properties>
        <maven.compiler.source>18</maven.compiler.source>
        <maven.compiler.target>18</maven.compiler.target>
    </properties>

</project>

**Comment by chaoren** [comment]
Try clearing out your maven cache at `C:\Users\<user_name>\.m2`.

**Comment by pjbabin** [comment]
As mentioned this has been going on for years, and clearing the cache was one of many suggestions that make no difference.
I am waiting for a reply from org.openqa.selenium.chrome

**Comment by pjbabin** [comment]
Thank you for your reply, I will pass it on

**Comment by pjbabin** [comment]
> `ImmutableMap.ofEntries` was added at the same time as the 6-entry overload, so `ImmutableMap.<K, V>builder()...build()` is your only API option if something is pulling in an older Guava version. You could also try adding an explicit recent Guava dependency to the appropriate `pom.xml`. (Maven has a [weird rule](https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#transitive-dependencies) for resolving dependencies, whereby the "nearest" version gets used instead of the most recent one. If Guava is explicitly in the starting `pom.xml` then that is as near as it can be.)

Thanks for that, however, I was really only pointing out that it should not have happened in the first place. 
I did not make ANY changes, 
I had a working automation and suddenly I get this error, I look it up in google and find it has been happening for years, all suggestions, including yours about 'explicit recent Guava dependency' have been mentioned as fixes, but none work. 
So to me I am doing nothing wrong, it is the people putting out new versions not doing enough regression testing. Which is quite strange as the main use of these things is to do testing.
So, my only way forward is to start from scratch, and when I get to where it gives the error again, try something else

**Comment by chaoren** [comment]
FWIW, I couldn't reproduce your issue with the pom.xml you included in the first comment, so it could be caused by some other factors in your environment.
