### ISSUE TITLE
How the thresholdPermits is calculated regard to the comment in SmoothWarningUp

### ISSUE THREAD

**Issue by NikoTung** [google/guava#6107]
I try to understand how the `thresholdPermits` is calculated in [SmoothWarmingUp](https://github.com/google/guava/blob/master/guava/src/com/google/common/util/concurrent/SmoothRateLimiter.java), but I still can't get the conclusion `thresholdPermits = 0.5 * warmupPeriod / stableInterval`.

>  * 5) When _used_, the time it takes, as explained in the introductory class note, is
     *    equal to the integral of our function, between X permits and X-K permits, assuming
     *    we want to spend K saved permits.
     *
     *    In summary, the time it takes to move to the left (spend K permits), is equal to the
     *    area of the function of width == K.
     *
     *    Assuming we have saturated demand, the time to go from maxPermits to thresholdPermits is
     *    equal to warmupPeriod.  And the time to go from thresholdPermits to 0 is
     *    warmupPeriod/2.  (The reason that this is warmupPeriod/2 is to maintain the behavior of
     *    the original implementation where coldFactor was hard coded as 3.)
     *
     * It remains to calculate thresholdsPermits and maxPermits.
     *
     *  - The time to go from thresholdPermits to 0 is equal to the integral of the function between
     *    0 and thresholdPermits.  This is thresholdPermits * stableIntervals.  By (5) it is also
     *    equal to warmupPeriod/2.  Therefore
     *
     *        thresholdPermits = 0.5 * warmupPeriod / stableInterval.

The docs said it need to maintain the original implemention where `coldFactor` was hard coded as 3. So I wonder if the `coldFactor` was hard coded as **7**, then how the `thresholdPermits` would be calculated, does the conclusion above still work?

So I did the following calculation base on:  `thresholdPermits`  is the cross point of two lines, on the left of that point is the horizontal line (1/QPS), on the right of that point is a slope line.

* a) "warmup period" is the area of the trapezoid between thresholdPermits and maxPermits

`(coldInterval + stableInterval) * (maxPermits - thresholdPermits) / 2 = warmupPeriod`

then I got `maxPermits - thresholdPermits = 2 * warmupPeriod / (coldInterval + stableInterval) `

When `coldFactor = 3`  then `maxPermits - thresholdPermits = 2 * warmupPeriod / (3 * stableInterval + stableInterval) = warmupPeriod / (2 * stableInterval)`

* b) When the rateLimiter reaches to the `thresholdPermits` then it becomes stable which means the rate is `stableInterval`

 `stableInterval = thresholdPermits *  (coldInterval - stableInterval) / (maxPermits - thresholdPermits) `

then I got `thresholdPermits = stableInterval * (maxPermits - thresholdPermits) / (coldInterval - stableInterval)`

When `coldFactor = 3` then `thresholdPermits = stableInterval * (maxPermits - thresholdPermits) / (3 * stableInterval - stableInterval) = (maxPermits - thresholdPermits) / 2`

Combining above two calculation, I got `thresholdPermits = warmupPeriod / (4 * stableInterval) = 0.25 * warmupPeriod / stableInterval` when `coldFactor` is 3.

Anyone can explain to me that I do a wrong calculation or missing something ?

**Comment by cgdecker** [comment]
This issue tracker isn't really the place to ask a question. Do you think there's a bug here?

**Comment by NikoTung** [comment]
Sorry, I'll close this issue.
