### ISSUE TITLE
What if we not write expireAfterWrite? Will the values be in cache all the time?

### ISSUE THREAD

**Issue by fazeelws** [google/guava#6132]
I want to store 3 constant values which should be always in cache and is used almost everytime. I thought of removing expireAfterWrite and will this work?
Currentlly, there are only 3 entries for SystemUser and limiting it to only 100.

private final LoadingCache<String, Optional<SystemUser>> systemUserCache = CacheBuilder
.newBuilder()
.maximumSize(100)
.build(
new CacheLoader<>() {
@Override
public Optional<SystemUser> load(String wsGlobalId) {
return getSystemUser(wsGlobalId);
}
}
);

**Comment by chaoren** [comment]
Please refer to [the documentation](https://guava.dev/releases/19.0/api/docs/com/google/common/cache/CacheBuilder.html#expireAfterWrite(long,%20java.util.concurrent.TimeUnit)). However, if you don't ever want the entries to be evicted, then perhaps a cache might not be the right tool to use.
