### ISSUE TITLE
Make ExceptionTypePolicy in NullPointerTester public

### ISSUE THREAD

**Issue by gandhishrey** [google/guava#6147]
NullPointerTester in guava-testlib has support for testing against different exception types based on a private enum `ExceptionTypePolicy`. However, this is currently set as a private field with no constructor or setter taking this as an input.

Setting an ExceptionTypePolicy or list of expected `Throwable`s will be particularly useful for repos which throw `IllegalArgumentException` instead of `NullPointerException` for null inputs.

**Comment by kevinb9n** [comment]
Dup of #1949
