### ISSUE TITLE
Safari is open

### ISSUE THREAD

**Issue by Dogscat3831** [google/guava#6186]
@googlebot

**Comment by Dogscat3831** [comment]
![image](https://user-images.githubusercontent.com/100335577/192419601-d9370cb0-5360-4a54-a106-db31dba9777e.png)

**Comment by amalloy** [comment]
Can you clarify what this issue is about? There's no context at all, and I don't know what that image means. On the other hand, one other user has filed a similar issue recently (#6190), so maybe there's genuinely something going on here?
