### ISSUE TITLE
Question to some files

### ISSUE THREAD

**Issue by Novarest** [google/guava#6189]
The following information is found in the files
com/google/common/cache/LongAdder.java,
com/google/common/cache/Striped64.java,
com/google/common/hash/LongAdder.java,
com/google/common/hash/Striped64.java,
com/google/common/util/concurrent/AtomicDoubleArray.java:

/*
* Written by Doug Lea with assistance from members of JCP JSR-166
* Expert Group and released to the public domain, as explained at
* http://creativecommons.org/publicdomain/zero/1.0/
*/

The following information is found in the file com/google/common/util/concurrent/AtomicDouble.java:

/*
* Written by Doug Lea and Martin Buchholz with assistance from
* members of JCP JSR-166 Expert Group and released to the public
* domain, as explained at
* http://creativecommons.org/publicdomain/zero/1.0/
*/

The following information is found in the file com/google/common/util/concurrent/MoreExecutors.java:

 /*
   * This following method is a modified version of one found in
   * http://gee.cs.oswego.edu/cgi-bin/viewcvs.cgi/jsr166/src/test/tck/AbstractExecutorServiceTest.java?revision=1.30
   * which contained the following notice:
   *
   * Written by Doug Lea with assistance from members of JCP JSR-166 Expert Group and released to
   * the public domain, as explained at http://creativecommons.org/publicdomain/zero/1.0/
   *
   * Other contributors include Andrew Wright, Jeffrey Hayes, Pat Fisher, Mike Judd.
   */

Because all these files are licensed under CC0 1.0 I would like to ask if you know of any patents these contributors hold? Thank you.

**Comment by amalloy** [comment]
The guava maintainers are not patent lawyers or experts. If you need this information, ask someone who knows about patents.

**Comment by dineshr93** [comment]
@Novarest  Have you found answer to this. We are looking for an answer to this as well.

**Comment by dineshr93** [comment]
Added my detailed analysis

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/DIRA27~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/DIRA27~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">


no | files | file introduced   in commit | date | commiter | comment
-- | -- | -- | -- | -- | --
1 | guava/src/com/google/common/util/concurrent/AtomicDoubleArray.java | https://github.com/google/guava/commit/9b1de11918c7e17b02c883365b1d13532988ee05 | Oct 27, 2011 | Charles Fry   <fry@google.com> no githubid | #All   commiters copied from Original jsr166 tar file can be accessed from        https://web.archive.org/web/20120224145723/http://gee.cs.oswego.edu/cgi-bin/viewcvs.cgi/jsr166/src/jsr166e.tar.gz?view=tar          NOTE: Original guava git-svn-id: https://guava-libraries.googlecode.com/svn     This is mirrored to github via MOE https://github.com/google/moe
2 | guava/src/com/google/common/util/concurrent/AtomicDouble.java
3 | guava\src\com\google\common\cache\LongAdder.java | https://github.com/google/guava/commit/06cbdb1ed84f235b51fec6acc740d8261357545d | Apr 10, 2012 | Gregory Kick   https://github.com/gk5885
4 | guava\src\com\google\common\cache\Striped64.java
5 | guava\src\com\google\common\hash\LongAdder.java | https://github.com/google/guava/pull/2761#issuecomment-286530502 | Mar 14, 2017 | Val Markovic   https://github.com/Valloric (actual)
6 | guava\src\com\google\common\hash\Striped64.java | https://github.com/google/guava/commit/6092a4a8b1087f92d0c3169b9e96d53c54ca95c4 | May 2, 2017 | Louis Wasserman   https://github.com/lowasser
7 | guava\src\com/google/common/util/concurrent/MoreExecutors.java | https://github.com/google/guava/commit/6de50d39a296a3d5f00779dbeaf3b520791b9cda | May 21, 2012 | Chris Povirk   https://github.com/cpovirk | invokeAnyImpl   functiuon
8 | guava/src/com/google/common/util/concurrent/Striped.java | https://github.com/google/guava/commit/61e6a48a69ba09f65499d6e0394d448e9313777c | Jun 6, 2012 | Christian Edward   Gruber https://github.com/cgruber | smear   function original file location is under public domain not cc0-1.0 but not   sure why author has mentioned douglea notice   https://github.com/google/guava/blob/db74bd2fdac443223d45e6fc5c66548542be1081/guava/src/com/google/common/collect/Hashing.java#L47



</body>

</html>

**Comment by dineshr93** [comment]
- jsr166 proposal can be found here  https://www.jcp.org/en/jsr/detail?id=166
- accepted entities of jsr166: https://www.jcp.org/en/jsr/detail?id=176 (search jsr-166) then added in java [JDK 5](http://www.jcp.org/en/jsr/detail?id=176)

Related information
jcp page: jsr166 https://jcp.org/aboutJava/communityprocess/final/jsr166/index.html 
university page on jsr166: https://gee.cs.oswego.edu/dl/concurrency-interest/index.html
