### ISSUE TITLE
Replace Findbugs by Spotbug

### ISSUE THREAD

**Issue by gruenich** [google/guava#6201]
FindBugs has not seen a release since 2015. Citing Spotbug's Github page:

> [SpotBugs](https://spotbugs.github.io) is a fork of [FindBugs](http://findbugs.sourceforge.net/) (which is now an abandoned project), carrying on from the point where it left off with support of its community.

Guava should move away from FindBugs to Spotbugs to have maintained dependencies, profit from their fixes and new features.

Probably related to #2960.

**Comment by cpovirk** [comment]
Thanks, this does sound a lot like #2960.

I know that "findbugs" appears as part of the jsr305 artifact name: https://github.com/google/guava/blob/fde1b8451d8d84c2842cbb75dd66a3d0b58a4274/pom.xml#L272

#2960 is indeed about eliminating that. Are there other ways we use Findbugs for us to also look into eliminating? I wouldn't be surprised if we had some comments lying around, for example, but we at least don't run the tool ourselves nowadays.

**Comment by gruenich** [comment]
You are right, Findbugs only occurs in various pom.xml, some comments, and a package-list. Feel free to close this as a duplicate of #2960 .

My pain is that every project directly or indirectly including Guava, I get Findbugs as a dependency and occurs in the software bill of materials. This triggers a warning because Findbugs is unmaintained for 5 years. I know, it used for testing only, but it generates noise and I would rather concentrate on real dependency issues.

**Comment by cpovirk** [comment]
Tracking on #2960 is probably best so that all interested parties can follow along when we finally do have some updates again.

(We're already quite interested in getting off the Findbugs jsr305 artifact, but it's always good when we hear from users who will benefit when that finally happens :))
