### ISSUE TITLE
Can we have conversions between ImmutablePrimitiveArrays

### ISSUE THREAD

**Issue by digambar-t7** [google/guava#6207]
Hey there!!
       I just thought in case if we could make the conversions of ImmutableArray of one primitive type to other primitive type.
**For example** : ImmutableIntArray.toImmutableLongArray() -> a method that would return an ImmutableLongArray from the provided ImmutableIntArray
Thank You!

**Comment by digambar-t7** [comment]
Yeah this approach is also right

**Comment by JanecekPetr** [comment]
I didn't want to discourage you from the ticket :). If you still think the methods would be worth it and you (and your organization, across a bigger codebase) would be using them a lot, maybe they're worth it.

But yes, there is already a way to convert, albeit slightly manual.
