### ISSUE TITLE
Incorrect domain name for www.amazon.com.be 

### ISSUE THREAD

**Issue by alps99w** [google/guava#6228]
InternetDomainName internetDomainName = InternetDomainName.from("www.amazon.com.be").topPrivateDomain();

I got "com.be"as InternetDomainName. please take a look.

**Comment by CameronUpson** [comment]
https://github.com/google/guava/wiki/InternetDomainNameExplained

"Getting back to InternetDomainName, as long as we limit ourselves to using hasPublicSuffix() to validate that the domain is a plausible Internet domain, all is well. The danger arises from the methods that identify or extract the "top private domain". From a technical point of view, the top private domain is simply the rightmost superdomain preceding the public suffix. So for example, www.foo.co.uk has a public suffix of co.uk, and a top private domain of foo.co.uk."

**Comment by cpovirk** [comment]
Guava is returned the proper result according to the data in https://github.com/publicsuffix/list. It does seem likely that that data should be updated for the creation of www.amazon.com.be, but the Public Suffix maintainers are the experts on this, so we follow them. We'd be happy to see their data updated if appropriate.
