### ISSUE TITLE
Diff multiple maps

### ISSUE THREAD

**Issue by shmueldabomb441** [google/guava#6233]
I need to diff multiple maps across each other. 

Guava currently has a great method for diffing two maps and finding the elements that are `onlyOnRight/Left`, `onBoth`, and `differences`. What object would this function return? Something with `onAll`, `differences`, and function  `Map<~> onlyOn(Map<~> map)` ?

**Comment by netdpb** [comment]
Hi! Questions like these are better answered on stackoverflow (tag [`[guava]`](https://stackoverflow.com/questions/tagged/guava)) or maybe on the [mailing list](https://groups.google.com/g/guava-discuss). We use this issue tracker for bug reports and feature requests.

**Comment by shmueldabomb441** [comment]
This was a feature request. Sorry for not being explicit.
