### ISSUE TITLE
Suggest EventBus#post may support delay queue

### ISSUE THREAD

**Issue by 40lsgy1** [google/guava#6291]
the expected api looks like this: 
`com.google.common.eventbus.EventBus#post(Object event, long delay, TimeUnit timeUnit)`

some distributed message queue has this features, such as kafka or rocketMQ, and I think eventBus can also implements it by modifying `Dispatcher.queue`

I hope you will consider  my suggestion

**Comment by netdpb** [comment]
We now discourage use of `EventBus`. The rationale and alternatives are explained in the [Javadoc](https://guava.dev/releases/snapshot-jre/api/docs/com/google/common/eventbus/EventBus.html). We should also put that information in the [Wiki](https://github.com/google/guava/wiki/EventBusExplained).

In the meantime, we are not considering new features for development. Thanks anyway for your suggestion!
