### ISSUE TITLE
Why do I occasionally get NullPointerException when I access concurrently?

### ISSUE THREAD

**Issue by ChaimNJ** [google/guava#6295]
![image](https://user-images.githubusercontent.com/32725103/212581083-104c962c-751a-41f3-9fe3-a98bb7d8d2c7.png)

guava version is 30.1.1-jre
use jdk17

use example:   cache.get(id, () -> test.query(id))

i can't understand why it throw NullPointException

**Comment by jbduncan** [comment]
@ChaimNJ It's most likely because `id` is sometimes null.

What happens if you ensure that the IDs you pass in are never null?

**Comment by ChaimNJ** [comment]
> @ChaimNJ It's most likely because `id` is sometimes null.
> 
> What happens if you ensure that the IDs you pass in are never null?

Thanks, i will check why id is sometimes null
