### ISSUE TITLE
Add Maps.uniqueIndex with valueMapper

### ISSUE THREAD

**Issue by StefanLobbenmeier** [google/guava#6297]
I was trying to do Maps.uniqueIndex, but realised that I did not need the whole object as the value but only one attribute of the list elements.

I looked around Guava code but did not find it. Here is the implementation I came up with myself:

```java
    private static <T, K, U> Map<K, U> uniqueIndex(
            List<T> list, Function<? super T, ? extends K> keyMapper, Function<? super T, ? extends U> valueMapper) {
        return list.stream().collect(Collectors.toMap(keyMapper, valueMapper));
    }
```

Is this function called something else in Guava or is it missing?

**Comment by eamonnmcmanus** [comment]
I think we should probably document that `Maps.uniqueIndex` is mostly obsolete with the advent of streams.

```
Maps.uniqueIndex(list, function)
```

is equivalent to

```
list.stream().collect(toImmutableMap(function, v -> v))
```

which doesn't require the reader to look up a rather obscure method. Of course with this version you can transform the values too if you like.

**Comment by StefanLobbenmeier** [comment]
Interesting, we follow the opposite approach to replace streams with already methods like this one. But I guess that means that you will not add such a method here right?

**Comment by eamonnmcmanus** [comment]
We've updated the documentation of `Maps.uniqueIndex` to say essentially what I said above: it's really only for pre-Java-8.
