### ISSUE TITLE
Guava artifacts are not bitwise reproducible

### ISSUE THREAD

**Issue by DPUkyle** [google/guava#6321]
In the spirit of the [Reproducible Builds project](https://reproducible-builds.org/), I want to ensure that the jars produced by the Guava build are deterministic.

In other words, if I clone the project, checkout a tag and build the libraries - their checksums should exactly match those publicly released on Maven Central.

Although the libraries built in the above example would be _functionally equivalent_, their checksums will differ.  There are two sources of non-determinism when building the Guava libraries today:

1. File metadata: each class file has the timestamp of when it was compiled, which is persisted in the jar/zip index
2. File contents: jar manifests and pom.properties files contain timestamps

I'll work on a PR to remove these sources of non-determinism, ensuring that the result of building a specific commit or tag can be reproduced bit-by-bit.

Note that Maven also publishes a page on build reproducibility: https://maven.apache.org/guides/mini/guide-reproducible-builds.html

**Comment by eamonnmcmanus** [comment]
Thanks, that sounds very useful!

**Comment by DPUkyle** [comment]
Fixed by [a9a2e95](https://github.com/google/guava/commit/a9a2e9593c520faa1c2edb79c1f5b0f83094d8ea)

**Comment by cpovirk** [comment]
It's also nice that this makes the _Javadoc_ diffs from a commit actually readable: Instead of touching _every_ file, the rebuild now touches only affected files ([example](https://github.com/google/guava/commit/6d0e99260064f1e460ba36ba1099aa79f56fa38d)).

**Comment by algomaster99** [comment]
Hi! I wanted to revisit this topic even though I am aware that the [latest releases of guava are bitwise reproducible](https://github.com/jvm-repo-rebuild/reproducible-central/blob/master/content/com/google/guava/README.md). I am trying to reproduce 32.0.0-jre which is an old version. My purpose to do so it build a list of reasons why builds are unreproducible. The issues related to metadata and manifests are fixed, however, I also see that there are differences in JVM bytecode produced too. In the dataset, given this [buildspec](https://github.com/jvm-repo-rebuild/reproducible-central/blob/master/content/com/google/guava/guava-32.0.0-jre.buildspec), I see two reasons why JVM bytecode differ

Rebuild JDK version
```
openjdk version "11.0.26" 2025-01-21
OpenJDK Runtime Environment (build 11.0.26+4-post-Ubuntu-1ubuntu122.04)
OpenJDK 64-Bit Server VM (build 11.0.26+4-post-Ubuntu-1ubuntu122.04, mixed mode, sharing)
```

1. A synthetic field is missing in the implicit constructor of the following class in [reference version](https://repo1.maven.org/maven2/com/google/guava/guava/32.0.0-jre/guava-32.0.0-jre.jar) https://github.com/google/guava/blob/6b1f97ced922d48f071153ad9e631d06383033a4/guava/src/com/google/common/cache/LocalCache.java#L4558-L4564

```diff
+  final com.google.common.cache.LocalCache this$0;
+    descriptor: Lcom/google/common/cache/LocalCache;
+    flags: (0x1010) ACC_FINAL, ACC_SYNTHETIC
+
   com.google.common.cache.LocalCache$EntryIterator(com.google.common.cache.LocalCache);
     descriptor: (Lcom/google/common/cache/LocalCache;)V
     flags: (0x0000)
@@ -63,17 +69,20 @@
       stack=2, locals=2, args_size=2
          0: aload_0
          1: aload_1
-         2: invokespecial #1                  // Method com/google/common/cache/LocalCache$HashIterator."<init>":(Lcom/google/common/cache/LocalCache;)V
-         5: return
+         2: putfield      #1                  // Field this$0:Lcom/google/common/cache/LocalCache;
+         5: aload_0
+         6: aload_1
+         7: invokespecial #2                  // Method com/google/common/cache/LocalCache$HashIterator."<init>":(Lcom/google/common/cache/LocalCache;)V
+        10: return
```

2. Synthetic method `values()` generated for `Enum`s are structured differently. https://github.com/google/guava/blob/6b1f97ced922d48f071153ad9e631d06383033a4/guava/src/com/google/common/base/Functions.java#L90-L103
This method is deleted from reference version and all its instructions are directly put in `static` block. To me, it simply seems refactoring.
```diff
-  private static com.google.common.base.Functions$IdentityFunction[] $values();
-    descriptor: ()[Lcom/google/common/base/Functions$IdentityFunction;
-    flags: (0x100a) ACC_PRIVATE, ACC_STATIC, ACC_SYNTHETIC
-    Code:
-      stack=4, locals=0, args_size=0
-         0: iconst_1
-         1: anewarray     #1                  // class com/google/common/base/Functions$IdentityFunction
-         4: dup
-         5: iconst_0
-         6: getstatic     #2                  // Field INSTANCE:Lcom/google/common/base/Functions$IdentityFunction;
-         9: aastore
-        10: areturn
-      LineNumberTable:
-        line 90: 0
-
```

<details>
<summary>static block</summary>

```diff
   static {};
     descriptor: ()V
     flags: (0x0008) ACC_STATIC
     Code:
       stack=4, locals=0, args_size=0
-         0: new           #1                  // class com/google/common/base/Functions$IdentityFunction
+         0: new           #4                  // class com/google/common/base/Functions$IdentityFunction
          3: dup
-         4: ldc           #9                  // String INSTANCE
+         4: ldc           #8                  // String INSTANCE
          6: iconst_0
-         7: invokespecial #10                 // Method "<init>":(Ljava/lang/String;I)V
-        10: putstatic     #2                  // Field INSTANCE:Lcom/google/common/base/Functions$IdentityFunction;
-        13: invokestatic  #11                 // Method $values:()[Lcom/google/common/base/Functions$IdentityFunction;
-        16: putstatic     #3                  // Field $VALUES:[Lcom/google/common/base/Functions$IdentityFunction;
-        19: return
+         7: invokespecial #9                  // Method "<init>":(Ljava/lang/String;I)V
+        10: putstatic     #10                 // Field INSTANCE:Lcom/google/common/base/Functions$IdentityFunction;
+        13: iconst_1
+        14: anewarray     #4                  // class com/google/common/base/Functions$IdentityFunction
+        17: dup
+        18: iconst_0
+        19: getstatic     #10                 // Field INSTANCE:Lcom/google/common/base/Functions$IdentityFunction;
+        22: aastore
+        23: putstatic     #1                  // Field $VALUES:[Lcom/google/common/base/Functions$IdentityFunction;
+        26: return
```

</details>

I am not expecting anyone to solve these issues as they are already solved :) But maybe if you could tell me the precise version of the JDK this project used to release, it would help me reproduce it. I can see that you [used zulu 11 for snapshots](https://github.com/google/guava/blob/6b1f97ced922d48f071153ad9e631d06383033a4/.github/workflows/ci.yml#L63C34-L63C74) but I could not remove these differences if I switched to:
```
openjdk version "11.0.18" 2023-01-17 LTS
OpenJDK Runtime Environment Zulu11.62+17-CA (build 11.0.18+10-LTS)
OpenJDK 64-Bit Server VM Zulu11.62+17-CA (build 11.0.18+10-LTS, mixed mode)
```
Moreover, the JDK version for normal releases could be different.

**Comment by cpovirk** [comment]
Hi. At this point, we build our releases by running a script on our local machines. (I expect that to change in the future as part of general security hardening.) Until recently, we even used the default JDK on our machines, which is a version that occasionally has patches to javac. (Nowadays, our default is to use a standard Debian JDK.)

Our JDK 11 has a patch to omit enclosing-class references—much like [JDK-8271717](https://bugs.openjdk.org/browse/JDK-8271717) did for later JDKs but I think perhaps even more aggressive in omitting the reference for `Serializable` types (though I don't think that difference is relevant here)? That should explain the `LocalCache` difference.

For enums, I suspect that we also had a patch like [JDK-8241798](https://bugs.openjdk.org/browse/JDK-8241798).

But in short, we were using a patched javac.

**Comment by cpovirk** [comment]
(I did verify that I can reproduce a bitwise-identical output at v32.0.0 with that custom JDK 11, so that should be the full explanation for the differences.)

**Comment by algomaster99** [comment]
Thank you for your extremely clear answer @cpovirk !

cc @hboutemy
