### ISSUE TITLE
expireAfterWrite的loadAll失效

### ISSUE THREAD

**Issue by github-wuxi** [google/guava#6359]
缓存使用expireAfterWrite时实现了loadAll与load方法，但是调用getAll方法时没有命中loadAll加载缓存，都是走的load，这个怎么解决，多谢

**Comment by ben-manes** [comment]
> When the cache uses expireAfterWrite, the loadAll and load methods are implemented, but when the getAll method is called, the loadAll load cache is not hit, and it is always loaded. How to solve this problem, thank you

Please provide a minimal unit test demonstrating your problem.

**Comment by github-wuxi** [comment]
1、缓存写法：cache = CacheBuilder.newBuilder().maximumSize(1000L).expireAfterWrite(10, TimeUnit.MINUTES)
2、问题为用cache.getAll(keyList)，其中keyList的size为150个，其中10个key是不在缓存内的，结果调用了分批调用了10次load方法，没有将10个key一起调用loadAll

**Comment by ben-manes** [comment]
Again, a unit test is required. I have a complimentary test suite checks against Guava and Caffeine, e.g. [getAll_absent](https://github.com/ben-manes/caffeine/blob/895a46dc9d3806e028cd52792bce2a71ed968148/caffeine/src/test/java/com/github/benmanes/caffeine/cache/LoadingCacheTest.java#L274-L285). Certainly there may be bugs, but after over a decade basic ones like yours are likely rooted out. A test demonstrating might show an incorrect expectation or reveal a scenario that was not considered. A vague description does not help either of us.
