### ISSUE TITLE
Support `last(element)` in `AbstractIterator`

### ISSUE THREAD

**Issue by fluentfuture** [google/guava#6392]
Sometimes my implementation of `AbstractIterator` knows that it's reached the end after finding the last element. Currently I need to do extra bookkeeping like:

```
private boolean done = false;

T computeNext() {
  if (done) return endOfData();
  ...
  T lastElement = ...;  // found the last element. No more.
  done = true;
  return lastElement;
}
```

This is tedious and easy to forget. Would be nice if `AbstractIterator` supports this pattern out of box:

```
T computeNext() {
  // ...
  // found the last element. No More.
  return last(element);
}
```

**Comment by igmtz** [comment]
Heey, can I contribute this issue? 😁

**Comment by kevinb9n** [comment]
Sorry, I wouldn't say this is a good candidate. We might not want this change, and if we do it'll make more sense to have @fluentfuture initiate it internally.

This seems a little opposite to AbstractIterator's use case?

It's made for those cases when you don't know whether you're at the end until you try to fetch the next and can't. I think implementing `Iterator` directly is easy enough in the other case. And in your case it's a bit like you know *even sooner* than that.

Could you flesh out your top code sample and contrast that with implementing Iterator directly?

**Comment by fluentfuture** [comment]
I'll close the issue as I didn't find enough use case internally that could have benefited from it.
