### ISSUE TITLE
topPrivateDomain throws IllegalStateException for krakow.pl

### ISSUE THREAD

**Issue by szpraat** [google/guava#6439]
Hi!

I faced an issue when calling .topPrivateDomain() on domain name of krakow.pl. It throws:

```
java.lang.IllegalStateException: Not under a public suffix: krakow.pl
at com.google.common.base.Preconditions.checkState(Preconditions.java:590)
at com.google.common.net.InternetDOmainName.topPrivateDomain(InternetDomainName.java:414)
```

Unit test:
```
@Test
void krakowPlFails() throws MalformedURLException {
   URL url = new URL("https://krakow.pl");
   Assertions.assertThrows(IllegalStateException.class, () -> InternetDomainName.from(url.getHost()).topPrivateDomain());
}
```
used version is 31.1-jre

**Comment by szpraat** [comment]
> Can you please provide a [MRE](https://stackoverflow.com/help/minimal-reproducible-example) in the form of a unit test?

Added a sample unit test

**Comment by cpovirk** [comment]
That domain is a public suffix, so there is no private domain: https://github.com/publicsuffix/list/blob/c349d29125e1c70d4eafe7e234226fdb6c67ae29/public_suffix_list.dat#L12802
