### ISSUE TITLE
Consider migration from javax.*  to new jakarta.*  ee packages

### ISSUE THREAD

**Issue by danipenaperez** [google/guava#6458]
javax.annotation and other javax.** packages will be great migrate to new EE jakarta packages.  They make it difficult to migrate to jdk 17, spring boot 3, etc.
Thanks in advance

**Comment by chaoren** [comment]
> They make it difficult to migrate to jdk 17, spring boot 3, etc.

Could you please elaborate on how they make those migrations difficult?

I'm not too familiar with Jakarta EE, but is it [compatible with JDK 7](https://github.com/google/guava/wiki/Compatibility#older-jdks)? Or rather the minimum version of it that could replace all of Guava's `javax.*` dependencies.

Also we'll probably just migrate to [jspecify](https://github.com/jspecify/jspecify) annotations once that's ready, so it would be harder to justify the effort to migrate to Jakarta EE in the interim.

**Comment by danipenaperez** [comment]
Hi, Srping Boot 3 (new Release) use Jakarta EE 9 that migrate javax.* to jakarta. packaging. 
[https://jakarta.ee/blogs/javax-jakartaee-namespace-ecosystem-progress/](Jakarta EE)
[https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0.0-M1-Release-Notes](Servlet 5 api, JPA 3.0 Specs).
Migration of Spring boot 2.X to 3.X based apps that used transitive libs that use javax.** package will be in trouble. 
Soon or later I think will be a guava compatibility with Jakarta EE 9.

**Comment by danipenaperez** [comment]
Sorry @chaoren you are correct, I am wrong, I was looking in the wrong repo. Apologies.
