### ISSUE TITLE
Please include LICENSE file under META-INF/ in the release jars

### ISSUE THREAD

**Issue by vlsi** [google/guava#6468]
The current release jars miss `META-INF/LICENSE`.
For instance, see https://repo1.maven.org/maven2/com/google/guava/guava/31.1-jre/ -> guava-31.1-jre.jar

```
% unzip -l guava-31.1-jre.jar  | grep META-INF
     2578  02-28-2022 16:18   META-INF/MANIFEST.MF
        0  02-28-2022 16:18   META-INF/
        0  02-28-2022 16:18   META-INF/maven/
        0  02-28-2022 16:18   META-INF/maven/com.google.guava/
        0  02-28-2022 16:18   META-INF/maven/com.google.guava/guava/
      133  02-28-2022 16:18   META-INF/maven/com.google.guava/guava/pom.properties
    10981  02-28-2022 16:06   META-INF/maven/com.google.guava/guava/pom.xml
```

The license requires to give a copy of the license when redistributing the software:

> See https://www.apache.org/licenses/LICENSE-2.0
> 4.a You must give any other recipients of the Work or Derivative Works a copy of this License; and

Even though the jar file includes a link to http://www.apache.org/licenses/LICENSE-2.0.txt, the link is not a copy as the link might become inaccessible, so the recipients might fail to receive "a copy of the License".

I suggest including the license file as `META-INF/LICENSE`.

By the way, Google Guice does include the license (Apache-2.0) as `META-INF/LICENSE`: https://repo1.maven.org/maven2/com/google/inject/guice/5.1.0/

Just in case, here's the opinion of the Apache Software Foundation: https://issues.apache.org/jira/browse/LEGAL-642

**Comment by cpovirk** [comment]
Thanks, especially for the Guice reference. I haven't found any docs inside Google that speak directly to this, but I'll get this in place for Guava and some of the other libraries we're involved with.
