### ISSUE TITLE
Regression/NPE crash for guava 31.x-jre on JDK 8

### ISSUE THREAD

**Issue by hgschmie** [google/guava#6474]
This test:

```java
    @Test
    public void testGuavaCrash() {
        TypeVariable<Class<Multimap>>[] multimapParams = Multimap.class.getTypeParameters();
        AnnotatedType[] annotatedBounds =  multimapParams[0].getAnnotatedBounds(); // this is line 153
        assertThat(annotatedBounds).isNotNull();
    }
```

works fine on JDK 8 with guava 30.1.1-jre. I use the latest temurin JDK:

```
openjdk version "1.8.0_372"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_372-b07)
OpenJDK 64-Bit Server VM (Temurin)(build 25.372-b07, mixed mode)
```

With guava 31.0-jre, 31.0.1-jre or 31.1-jre:

```
java.lang.NullPointerException
	at sun.reflect.annotation.TypeAnnotationParser.mapTypeAnnotations(TypeAnnotationParser.java:356)
	at sun.reflect.annotation.AnnotatedTypeFactory$AnnotatedTypeBaseImpl.<init>(AnnotatedTypeFactory.java:139)
	at sun.reflect.annotation.AnnotatedTypeFactory.buildAnnotatedType(AnnotatedTypeFactory.java:65)
	at sun.reflect.annotation.TypeAnnotationParser.parseAnnotatedBounds(TypeAnnotationParser.java:279)
	at sun.reflect.annotation.TypeAnnotationParser.parseAnnotatedBounds(TypeAnnotationParser.java:237)
	at sun.reflect.generics.reflectiveObjects.TypeVariableImpl.getAnnotatedBounds(TypeVariableImpl.java:241)
	at org.jdbi.v3.guava.TestGuavaCollectors.testGuavaCrash(TestGuavaCollectors.java:153)
```

There is some magic in the way the 31.x class files are written that seems incompatible to Java 8. Calling the `getAnnotatedBounds()` method on the type variable crashes immediately.

**Comment by hgschmie** [comment]
(In case it was not clear: This crash *only* happens with JDK 8. I tried JDK 11/17/19/20; they all work fine)

**Comment by eamonnmcmanus** [comment]
This looks like [JDK-8152174](https://bugs.openjdk.org/browse/JDK-8152174), which was fixed in JDK 9 but remains unfixed in JDK 8. Probably it is because `Multimap` is now declared as `public interface Multimap<K extends @Nullable Object, V extends @Nullable Object>`, where `Nullable` is `org.checkerframework.checker.nullness.qual.Nullable`. Adding a dependency on `org.checkerframework:checker-qual:3.34.0` might fix it.

**Comment by hgschmie** [comment]
you are correct. I rejiggered our tests to ensure that they have the checker-qual on the classpath and the problem goes away. I understand that this is a JDK problem, but it is (from user PoV) a regression between guava 30.x and guava 31.x

**Comment by eamonnmcmanus** [comment]
I don't think there's much we can do here. These annotations serve a purpose (helping nullness analysis tools) and we're probably not going to remove them to avoid a rare bug in an old JDK that is no longer actively supported. I think your choices are: (1) continue with the workaround of adding the dependency to the classpath; (2) stick with Guava 30; (3) arrange for the bug fix to be backported to Temurin.
