### ISSUE TITLE
RateLimiter SmoothWarmingUp does not limit if warmup period is smaller than 1000 NANOSECONDS

### ISSUE THREAD

**Issue by gerabarna** [google/guava#6475]
Hi!

We have encountered an issue when a Rate limiter has been set up with 1 permits per second, and a ZERO duration. 
This resulted in a RateLimiter, which gave out permits without any limitation.
Further investigation revealed that any warmup period below 1 MICROSECOND will result in a non-limiting rate limiter.

A very simplistic reproducer:
```    
    @Test
    void givenARateLimiterWithWarmupBelowOneMillisec_WhenRequesting_ThenRateLimitIsStillRespected() {
        RateLimiter limiter = RateLimiter.create(1, 999, TimeUnit.NANOSECONDS);
        final long start = System.currentTimeMillis();
        for (int j = 0; j < 5; j++) {
            limiter.acquire();
        }
        final long elapsed = System.currentTimeMillis() - start;
        Assertions.assertTrue(elapsed > 4000);
    }
```

I believe RateLimiter should either validate the input, and disallow such warmup settings, or hanle it porperly

**Comment by netdpb** [comment]
Do you see the same behavior when calling `create(1, Duration.ZERO)`?

**Comment by gerabarna** [comment]
yes

**Comment by netdpb** [comment]
How important is it to support <1µs warmup time? That sounds awfully close to no warmup time. A simple solution would be either to throw in that case or to default to a non-warmup limiter.

**Comment by gerabarna** [comment]
As far as I could understand the RateLimiter classes, limiters without warmup time also have the behaviour of accumulating permits and allow short bursts from the accumulated pool. ( as I saw the SmoothBursty subclass is created )
Our use-case unfortunately cannot allow any such bursts, even if the RateLimiter was left idle for a time. the closest way to simulate such behaviour was to set the lowest possible warmup time instead.
If you have a better suggestion on how to get a RateLimiter without any accumulation, I would be happy to switch.

Regardless, the point of this report was that validation should rule out an incorrectly constructed warmup limiter, which gives out permits without any limiting. Which currently happens with a low enough warmup time. Simply throwing an exception would achieve this I believe.

**Comment by weizheeeeee** [comment]
I have encountered the same issue recently, and I believe you can simply use the constructor with only one param of RateLimiter to generate your limiter, and I believe that solution will meet your demand.

**Comment by cpovirk** [comment]
(It sounds like this is probably the same as https://github.com/google/guava/issues/2730, so let's consolidate the discussion there.)
