### ISSUE TITLE
Unable to load class 'com.google.common.collect.Streams'.

### ISSUE THREAD

**Issue by lmsablot-navagis** [google/guava#6495]
I'm having an issue with this <img width="1309" alt="Screenshot 2023-05-15 at 9 55 19 PM" src="https://github.com/google/guava/assets/122075496/5ca744af-87d1-49c8-9932-3d134f9b023f">

I used  `implementation("com.google.guava:guava:31.0.1-android")` in our android project.

**Comment by cpovirk** [comment]
From the error message, I think this is a problem with IntelliJ. I suggest [filing a bug](https://youtrack.jetbrains.com/newIssue) with them, [including the idea.log](https://intellij-support.jetbrains.com/hc/en-us/articles/207241085-Locating-IDE-log-files).
