### ISSUE TITLE
Add Explore Graph Algorithms

### ISSUE THREAD

**Issue by dippi9845** [google/guava#6504]
It can be useful, in a lot of of scenarios, adding path finding algorihtms for 2 nodes, giving even the chance to choose the algorithm to perform (BFS, DFS, ...). Moreover can be useful adding least cost path finding algorithms, on graphs with weight on edges.

**Comment by jrtom** [comment]
This request is very broad as currently phrased; it's much easier to act on feature requests that are specific.  As such I will be closing this request; please feel free to reopen it with a more specific request if you feel it's appropriate.

Note that `Traverser` (https://guava.dev/releases/31.1-jre/api/docs/com/google/common/graph/Traverser.html) might be part of whatever you have in mind.
