### ISSUE TITLE
There seems to be a problem with the values containing method of TreeMultimap

### ISSUE THREAD

**Issue by kiligzzz** [google/guava#6537]
Hello, this is the first time for me to raise issues. Please forgive me if I can't express it well.
version：31.1-android
environment：Jdk1.8

Here is the test code:

```java
package com.kilig.demo.test;

import com.google.common.collect.TreeMultimap;
import lombok.AllArgsConstructor;
import lombok.Data;

import java.util.Comparator;

/**
 * Guava TreeMultimap Issue
 *
 * @author Ivan
 * @since 2023/6/6
 */
public class GuavaTreeMultimapTest {
    public static void main(String[] args) {
        // group: A (leader) -> B,C (member)
        // other: D (other)
        Student A = new Student("A", 80);
        Student B = new Student("B", 70);
        Student C = new Student("C", 60);
        Student D = new Student("D", 70);

        TreeMultimap<Student, Student> leaderToMemberMap = TreeMultimap.create(
                Comparator.comparing(Student::getName),
                Comparator.comparingInt(Student::getScore)
        );
        leaderToMemberMap.put(A, B);
        leaderToMemberMap.put(A, C);

        System.out.println("Map values: " + leaderToMemberMap.values());
        System.out.println("D: " + D);
        System.out.println("Map values contains D ??? : " + leaderToMemberMap.values().contains(D));
    }

    @Data
    @AllArgsConstructor
    static class Student {
        String name;
        int score;
    }
}

```

Output:

```
Map values: [GuavaTreeMultimapTest.Student(name=C, score=60), GuavaTreeMultimapTest.Student(name=B, score=70)]
D: GuavaTreeMultimapTest.Student(name=D, score=70)
Map values contains D ??? : true
```

I understand that the final output should be false, but in fact it is true. It seems that the method "contains" determines whether the score is equal, that is, the value Comparator when defined. Is it true or is it the characteristic? 

Looking forward to your reply!

**Comment by eamonnmcmanus** [comment]
See the [documentation](https://javadoc.io/doc/com.google.guava/guava/latest/com/google/common/collect/TreeMultimap.html) for `TreeMultimap`:

> Warning: The comparators or comparables used must be _consistent with equals_ as explained by the [`Comparable`](https://docs.oracle.com/en/java/javase/20/docs/api/java.base/java/lang/Comparable.html) class specification. Otherwise, the resulting multiset will violate the general contract of [`SetMultimap`](https://javadoc.io/static/com.google.guava/guava/32.0.0-jre/com/google/common/collect/SetMultimap.html), which is specified in terms of `Object.equals(java.lang.Object)`.

Your value comparator is _not_ consistent with equals: `D.equals(B)` is false but `Comparator.comparingInt(Student::getScore).compare(D, B)` will return 0 (equal) since it is only looking at the score property. Maybe use something like `Comparator.comparingInt(Student::getScore).thenComparing(Student::getName)` so students with the same score are separated based on their names.
