### ISSUE TITLE
What possessed the author of ImmutableList to write it that way?

### ISSUE THREAD

**Issue by RPMYT** [google/guava#6564]
Seriously, it doesn't need twelve methods that all call _the same varargs function_ in the end.
Replacing all twelve with one varargs would (at least, in my opinion) _SIGNIFICANTLY_ improve readability.

**Comment by ben-manes** [comment]
I believe this was due to varargs emitting a warning at the call site of possibly unsafe usage ([background](https://sendilkumarn.medium.com/safevarargs-variable-arguments-in-java-b9fdd5d996bb)). This avoided those warnings for usability, and Java 7’s `@SafeVarargs` resolved it properly. However, while removing those extraneous methods is source compatible, it is not binary compatible. Thus, this relic should remain to avoid breaking any usages.

**Comment by lowasser** [comment]
This is correct.  ImmutableList predates SafeVarargs, and at that time, before SafeVarargs, javac would give a warning when you attempted ImmutableList.of(anyGeneric).  The overloads avoided this for a large majority of ImmutableList.of(...) callers at the time. 
 And then as Ben observes, preserving binary compatibility where possible means they have to stay.

**Comment by orionll** [comment]
Also, this helps to avoid unnecessary garbage for most of usages (varargs creates a new array every time). `List.of()` was introduced in Java 9, and it also has many overloads.

**Comment by kevinb9n** [comment]
I appreciate the attempts to shield me, but the truth is that that week I was briefly inhabited by the remnant spirit of the ancient trickster god Overlödus.

Unfortunately by the time we realized it was actually a good idea (for the reasons stated above) it had been exorcised and banished to the void. We didn't even get to say thanks.

@RPMYT If you have more "why" questions, please feel free to mail https://groups.google.com/g/guava-discuss (a very low-traffic list). That works better than filing an issue and as you can see we'll try to give the honest explanations.

**Comment by danilomo** [comment]
@RPMYT 

No need to be this aggressive, what is wrong with you?

**Comment by RPMYT** [comment]
@danilomo I apologize if I sounded aggressive, this was not my intention; more so exasperated confusion.
