### ISSUE TITLE
Expect Eviction Strategy for Cache with .refreshAfterWrite()

### ISSUE THREAD

**Issue by vivian-liu0** [google/guava#6593]
If I construct a Cache using CacheBuilder, along with .maximumSize() and .refreshAfterWrite(), will the configured eviction strategy be only by least-recently-used when the maximum size is exceeded, or also by time-based expiration of entries? 

This is example of the constructed cache:

``` 
CacheBuilder
        .newBuilder()
        .maximumSize(2)
        .refreshAfterWrite(5, TimeUnit.SECONDS)
        .build(cacheLoader)
```

Thanks!

**Comment by kluever** [comment]
Please ask "how-to" and "why-didn't-it-work" questions on [StackOverflow](https://stackoverflow.com/questions/ask?tags=guava+java)

Note: `com.google.common.cache` is lightly discouraged in favor of https://github.com/ben-manes/caffeine
