### ISSUE TITLE
Sloppy code in SimpleTimeLimiter

### ISSUE THREAD

**Issue by tohidemyname** [google/guava#6599]
I find a try statement inside another try statement in InterruptedException:

private <T extends @Nullable Object> T callWithTimeout(
  ...
Future<T> future = executor.submit(callable);

    try {
      if (amInterruptible) {
        try {
          return future.get(timeoutDuration, timeoutUnit);
        } catch (InterruptedException e) {
          future.cancel(true);
          throw e;
        }
      } else {
        return Uninterruptibles.getUninterruptibly(future, timeoutDuration, timeoutUnit);
      }
    } catch (ExecutionException e) {
      throw throwCause(e, true /* combineStackTraces */);
    } catch (TimeoutException e) {
      future.cancel(true);
      throw new UncheckedTimeoutException(e);
    }
}
The code looks sloppy. Can it be improved?

**Comment by cpovirk** [comment]
Sometimes nesting of `try`-`catch` is the best we can do. It's probably avoidable here. If it's fixable in a couple minutes, I'll take care of it.
