### ISSUE TITLE
Cannot use latest vulnerability fix release 32.1.0-jre  

### ISSUE THREAD

**Issue by shantanu-vsbhosale** [google/guava#6610]
Issue: 
Maven does not show build `32.1.0-jre` build and hence we are not able to use this latest build with fix.
<img width="1706" alt="image" src="https://github.com/google/guava/assets/80242052/b769a2e9-1e15-40e2-b4f2-283e2862b328">

**Comment by chadlwilson** [comment]
mvnrepository is a 3rd party service unaffiilated with Maven Central and does not update its index in realtime. The dependencies are on Maven central: https://repo1.maven.org/maven2/com/google/guava/guava/32.1.0-jre/
