### ISSUE TITLE
cache.getIfPresent(key) cause load?

### ISSUE THREAD

**Issue by Sky12321** [google/guava#6619]
code：
public class CacheTestService {

    public static void main(String[] args) throws ExecutionException, InterruptedException {

        LoadingCache<String, String> cache = CacheBuilder.newBuilder()
                .maximumSize(100)
                .refreshAfterWrite(5, TimeUnit.SECONDS)
                .expireAfterWrite(10, TimeUnit.SECONDS)
                .build(new CacheLoader<String, String>() {
                    @Override
                    public String load(String key) throws Exception {
                        Thread.sleep(1000);
                        return key + ":" +  System.currentTimeMillis();
                    }
                });

        cache.put("key", "origin value");

        for (int i = 0; i < 20; i++) {
            long start = System.currentTimeMillis();
            String value = cache.getIfPresent("key");
            System.out.println(i + " load time: " + (System.currentTimeMillis() - start) + "ms, value: " + value);
            Thread.sleep(1000);
        }
    }
}

and result：
0 load time: 0ms, value: origin value
1 load time: 0ms, value: origin value
2 load time: 0ms, value: origin value
3 load time: 0ms, value: origin value
4 load time: 0ms, value: origin value
5 load time: 1018ms, value: key:1688292041268
6 load time: 0ms, value: key:1688292041268
7 load time: 0ms, value: key:1688292041268
8 load time: 0ms, value: key:1688292041268
9 load time: 0ms, value: key:1688292041268
10 load time: 1001ms, value: key:1688292047282
11 load time: 0ms, value: key:1688292047282
12 load time: 0ms, value: key:1688292047282
13 load time: 0ms, value: key:1688292047282
14 load time: 0ms, value: key:1688292047282
15 load time: 1001ms, value: key:1688292053284
16 load time: 0ms, value: key:1688292053284
17 load time: 0ms, value: key:1688292053284
18 load time: 0ms, value: key:1688292053284
19 load time: 0ms, value: key:1688292053284

When refreshAfterWrite time out, method getIfPresent will load.
My understanding of from LoadingCache java doc, is that getIfPresent will not cause value to be loaded,  how to wxplain my result?

**Comment by ben-manes** [comment]
> My understanding of from LoadingCache java doc, is that getIfPresent will not cause value to be loaded

The documentation does not state that. It simply says the following,
```console
Returns the value associated with {@code key} in this cache, or {@code null} if there is no cached
value for {@code key}.
```

> how to wxplain my result?

See the `refreshAfterWrite` documentation,

```console
Specifies that active entries are eligible for automatic refresh once a fixed duration has elapsed after
the entry's creation, or the most recent replacement of its value.

Currently automatic refreshes are performed when the first stale request for an entry occurs. The 
request triggering refresh will make a synchronous call to {@link CacheLoader#reload} to obtain a
future of the new value. If the returned future is already complete, it is returned immediately. Otherwise,
the old value is returned.
```

**Comment by Sky12321** [comment]
Yes, in the source code of com.google.common.cache.LocalCache#getIfPresent, when the refreshAfterWrite time is reached, the scheduleRefresh method is called to refresh the cache.
