### ISSUE TITLE
MutableNetwork should support anonymous edges

### ISSUE THREAD

**Issue by rick4096** [google/guava#6629]
None of the graphs support my use case well. My use case requires a directed acylic graph with edges that hold a time stamp, and nodes with unique names. Due to a preexisting schema I have to serialize each node in its own row in a table, and have added a column to store the JSON-encoded source edges which emanate from the node in that row.

I want to use Network as it enforces the DAG constraints and gives me methods to iterate over in and out edges which make my code much simpler. However, Network requires unique edges, and if two edges happen to have the same timestamp, they will not be unique. I have worked around this by adding a UUID to each edge, however it bloats the JSON-encoded representation of a node and its out-edges when stored in my DB table by injecting unnecessary UUIDs. Furthermore, I have to carefully use the same UUIDs in cases where I am adding potentially overlapping nodes, e.g., adding the same node twice, or else trigger the no-parallel-edge check since tho the edges are logically equivalent, by adding the UUID "salt" they are not actually the same and fail the no-parallel-edge test.

Ideally, the Network should have an option to not require unique edges. Thanks for hearing me out.

**Comment by jrtom** [comment]
If you don't need parallel edges, then it sounds like [ValueGraph](https://guava.dev/releases/snapshot-jre/api/docs/com/google/common/graph/ValueGraph.html) should do what you want.  It was specifically designed for the case in which you need to have values associated with the edges (in your case, a timestamp) that are not unique.

`Network`, by contrast, is specifically defined by edges that are first-class objects, and there's no coherent way for it to allow anonymous edges.

https://github.com/google/guava/wiki/GraphsExplained#choosing-the-right-graph-type goes into this in more detail, but basically:
* `Graph`: edges are anonymous (characterized entirely by their endpoints/ordering); analogous to `Set`
* `ValueGraph`: edges *have* (possibly non-unique) values; analogous to `Map`
* `Network`: edges *are* first-class unique objects; analogous to `BiMultimap`

If `ValueGraph` does not do what you want, please explain your needs in more detail (and how `ValueGraph` fails to meet them).

One last comment: I'm not sure what you mean by "Network...enforces the DAG constraints", but `Network`s are definitely not constrained to be DAGs, so I hope you're not assuming that they are.  (One can impose that constraint on a particular `Network` by constraining what edges you add, but you don't get that for free.)

**Comment by jrtom** [comment]
To traverse the outbound edges of a node `n` in a `[Value]Graph graph`, you use `successors()`, which gives you the other end of the edge.  You can then fetch the timestamp (etc.) based on that node pair:

```java
ValueGraph<String, Timestamp> valueGraph = ... 
String n = ...

for (String succ : graph.successors(n)) {
  Timestamp t = graph.edgeValue(n, succ).get(); // if you want the edge value
  ...
}
```

We've considered added `inEdges()` and `outEdges()` for `[Value]Graph` but so far haven't seen sufficiently compelling arguments.

Does this satisfy your requirements?

**Comment by rick4096** [comment]
This meets my requirements, and I think I'll use this approach, thank you.

**Comment by jrtom** [comment]
Glad to hear it; thanks for checking in.  :)
