### ISSUE TITLE
The lates guava-jre pom doesn't contain versions

### ISSUE THREAD

**Issue by artemptushkin** [google/guava#6635]
The build fails to find the dependencies

* `guava:32.1.1-jre` doesn't contain versions - https://repo1.maven.org/maven2/com/google/guava/guava/32.1.1-jre/guava-32.1.1-jre.pom

* The `bom` doesn't contain too - https://repo1.maven.org/maven2/com/google/guava/guava-bom/32.1.1-jre/guava-bom-32.1.1-jre.pom

* but the `parent` does - https://repo1.maven.org/maven2/com/google/guava/guava-parent/32.1.1-jre/guava-parent-32.1.1-jre.pom

So the solution is to import the parent and the bom both, example with spring dependency management plugin is below but we can make the same with Gradle `platform`:

```
mavenBom("com.google.guava:guava-bom:$guava_version")
mavenBom("com.google.guava:guava-parent:$guava_version")
```

It popped up after the spring:dependency-management update to 1.1.11 [here](https://github.com/spring-gradle-plugins/dependency-management-plugin/pull/355)

**Comment by aggeboe** [comment]
Another workaround: Downgrade to `32.0.1-jre`

**Comment by wilkinsona** [comment]
@artemptushkin I think this is a regression in the dependency management plugin a not a problem with Guava.

**Comment by wilkinsona** [comment]
It was indeed due to the Gradle module metadata. You mentioning that made me realise that the fix for the regression was incomplete so thank you for pointing me in that direction.
