### ISSUE TITLE
checkNotNull() method cannot check for each elements in newArrayList(E...)

### ISSUE THREAD

**Issue by yoon1fe** [google/guava#6636]
Hi, I was creating a arrayList via `newArrayList(E...)` method with a single object and null checking was not working properly.

Varargs(variable arguments) are converted to an array at compile time. However, the `checkNotNull()` method in the `Preconditions` class determines whether the object itself is null or not.

Therefore, I think it is reasonable to use the `checkElementsNotNull()` method in the `ObjectArrays` class instead of the `checkNotNull()` method in methods that take varargs as a parameter.

**Comment by eamonnmcmanus** [comment]
The [documentation](https://javadoc.io/static/com.google.guava/guava/32.1.1-jre/com/google/common/collect/Lists.html#newArrayList(E...)) of `newArrayList(E...)` specifically mentions null elements so clearly it is not a bug that it doesn't reject them. If you want a new unmodifiable list that cannot contain nulls, you can use `ImmutableList.of(E...)` or `List.of(E...)`. Those will throw an exception if any of the elements are null. If you want a new modifiable list that _initially_ doesn't contain nulls, you could do something like this:

```java
static List<String> stringList(String... elements) {
  List<String> list = Arrays.asList(elements);
  Preconditions.checkArgument(!elements.contains(null));
  return list;
}
```

I'm not aware of anything in the JDK or in Guava that would give you a modifiable list that can _never_ contain nulls, but I don't think that's what you're asking about here.
