### ISSUE TITLE
Is range meant to work with java.time?

### ISSUE THREAD

**Issue by 1goldenboy** [google/guava#6690]
Stumbled into this when some tests failed in a project, specifically because ZonedDateTime.parse() where used without zoneId. Simple example below:

var atMidnight = LocalDate.now().atStartOfDay(ZoneId.of("Europe/Oslo"));
var nextMidnight = atMidnight.plusDays(1);
var range = Range.closedOpen(atMidnight, nextMidnight);

ZonedDateTime atMidnightWithoutZoneID = ZonedDateTime.from(atMidnight.toOffsetDateTime());
System.out.println(range.contains(atMidnight)); // This returns true, as expected
System.out.println(range.contains(atMidnightWithoutZoneID)); // This returns false, but should return true
System.out.println(range.contains(nextMidnight)); // This returns false, as expected

**Comment by kluever** [comment]
This question might be better suited for Stackoverflow, but `Range` works with any `Comparable` type.
