### ISSUE TITLE
Suggestions for task pipelines

### ISSUE THREAD

**Issue by Sia-Lan** [google/guava#6706]
Hello dear google engineers, I designed and implemented the task pipeline, the tasks that need to ensure the sequence of execution can be arranged in a pipeline through the same pipeline key, and different pipelines can be executed in parallel. Hope to have the opportunity to contribute to the guava codebase.

https://github.com/Sia-Lan/sia

Thanks.

**Comment by eamonnmcmanus** [comment]
Please see the [How to contribute](https://github.com/google/guava/blob/master/CONTRIBUTING.md) document. If you are interested in contributing a feature, we would need a detailed discussion, in English, of the use cases it addresses and how it does so. Be aware that Guava is not adding many new features these days, so we probably wouldn't add this even with that extra information. You might be able to find a more appropriate home for it.
