### ISSUE TITLE
R8 issue with android version

### ISSUE THREAD

**Issue by SamYStudiO** [google/guava#6767]
Hello,

When trying to add guava 32.1.2-android to my project i get the following R8 issue 

`Missing class com.google.auto.service.AutoService (referenced from: org.robolectric.RobolectricTestRunner$DeprecatedTestRunnerDefaultConfigProvider and 15 other contexts)
Missing class org.apiguardian.api.API$Status (referenced from: org.junit.jupiter.api.extension.ExtensionConfigurationException and 12 other contexts)
Missing class org.apiguardian.api.API (referenced from: org.junit.jupiter.api.extension.ExtensionConfigurationException and 12 other contexts)`

If i add these to my proguard file it works but my apk size increase from 30mo to 190mo

I tried previous guava version but still the same

Any ideas?
Thx

**Comment by chaoren** [comment]
None of those classes seem to have anything to do with Guava. The fact that the same problem happens with the previous version seems to confirm that as well. What makes you think that Guava is causing this?
