### ISSUE TITLE
Add checksums for Maven wrapper

### ISSUE THREAD

**Issue by Marcono1234** [google/guava#6805]
It is possible to specify the expected checksums for the Maven wrapper and the Maven distribution using `wrapperSha256Sum` and `distributionSha256Sum` in the `maven-wrapper.properties` file, see https://maven.apache.org/wrapper/index.html#checksum-verification-of-downloaded-binaries.

Do you think it would make sense to specify these checksums for Guava? This could cause issues though if the user does not have the needed packages installed locally, see for example:
https://github.com/google/guava/blob/050f89f39f3a0e3276cd5696a82e0bb050915b52/mvnw#L271-L272

(As side note, if the files had already been downloaded before, their checksums are apparently not checked anymore, see [MWRAPPER-93](https://issues.apache.org/jira/browse/MWRAPPER-93))

**Comment by cpovirk** [comment]
Thanks. I'd say that it's probably worth doing. In the worst case, users can use plain old `mvn` directly. (Now is probably the best time to do it, even, since users are unlikely to have come to rely on `mvnw` yet.)

Do you want to send a PR, or should I take care of it?

**Comment by Marcono1234** [comment]
Have created #6807
