### ISSUE TITLE
Set up CI for newer JDK versions

### ISSUE THREAD

**Issue by cpovirk** [google/guava#6830]
I learned while looking at https://github.com/google/guava/issues/4005#issuecomment-1806237141 that our build fails under JDK 21+ with a legitimate Animal Sniffer error as of https://github.com/google/guava/commit/945ce37fd615ae976f4aefc40df8d2f4b67acf5e. That seems like the kind of thing that we'd want to know.

I do have some fear about multiplying the increasing of JDK versions that we test against, though, given that CI is already slow. I wonder if we can convince ourselves that we could remove either 11 or 17 as part of adding 21 (or even 22).

This leads me to a thought about toolchains, which I'll leave in https://github.com/google/guava/issues/6549.

**Comment by sgammon** [comment]
@cpovirk I think this can be closed :) JDK 22 did come out yesterday, but the distance between 17 and 21 is much greater than the distance between 21 and 22.
