### ISSUE TITLE
Bundle-Version format in MANIFEST.MF differs from Maven coordinate's version

### ISSUE THREAD

**Issue by veita** [google/guava#6840]
### Description

The format of the Bundle-Version format in MANIFEST.MF differs from Maven version. Manifest uses `.jre` while Maven version has `-jre` as suffix.

This makes it necessary to map the suffixes in places where checks for equality between the two values are made.

### Example

```java
`Bundle-Version: 32.1.1.jre` vs. `32.1.1-jre` (https://repo1.maven.org/maven2/com/google/guava/guava/maven-metadata.xml).
```

### Expected Behavior

Version format is consistent.

### Actual Behavior

Version format differs.

### Checklist

- [X] I agree to follow the [code of conduct](https://github.com/google/.github/blob/master/CODE_OF_CONDUCT.md).

**Comment by cpovirk** [comment]
I know very little about OSGi, so take all this with a grain of salt.

We [do whatever the Apache Felix `maven-bundle-plugin`](https://github.com/google/guava/blob/2982e9de13ec3722ac9144492e4cda75ed677bcc/guava/pom.xml#L750) does. It apparently [normalizes separators to periods](https://felix.apache.org/documentation/subprojects/apache-felix-maven-bundle-plugin-bnd.html#:~:text=normalized%20to%20the%20osgi%20version%20format), as required [by the OSGi specification](https://docs.osgi.org/specification/osgi.core/8.0.0/framework.module.html#i2655136). So I suspect that any code that relies on the two versions to match is broken. (It sounds like there may be [other problems with trying to match version numbers between Maven, SemVer, and OSGi](https://mnlipp.github.io/osgi-getting-started/Versions.html#pre--vs-post-qualifiers). Not to mention that it's iffy not just [under OSGi](https://docs.osgi.org/whitepaper/semantic-versioning/040-semantic-versions.html#:~:text=different%20qualifiers%20do%20not%20signal%20any%20backward%20compatibility%20issues.) but also under the other systems for our `32.1.1.-jre` and `32.1.1.-android` to expose different APIs.)

I suspect that there is nothing we can do here, but let me know if you know more.

**Comment by cpovirk** [comment]
Closing on the theory I laid out above, but I'm happy to reconsider if there is something better that we can do.

**Comment by veita** [comment]
> I suspect that there is nothing we can do here, but let me know if you know more.

Thank you for your response. I wasn't aware of the fact that OSGI requires the dot as a qualifier separator. We'll rewrite our test to match against the version from the `META-INF/maven/com.google.guava/guava/pom.properties`.
