### ISSUE TITLE
Help Jackson with Guava Deserializers

### ISSUE THREAD

**Issue by paulmarcelinbejan** [google/guava#6899]
### 1. What are you trying to do?

It is not possible to read an object with a Table as a field from Kafka since behind the scenes, spring framework uses Jackson to deserialize objects, and at the moment there are a lot of Guava Data Types that are not handled by Jackson

https://github.com/FasterXML/jackson-datatypes-collections/blob/2.17/guava/src/main/java/com/fasterxml/jackson/datatype/guava/GuavaDeserializers.java

### 2. What's the best code you can write to accomplish that without the new feature?

I have switched from Guava Table to Map<C, Map<R, V>>

### 3. What would that same code look like if we added your feature?

probably something like:

public HashBasedTable(Map<R, Map<C, V>> table);

### Concrete Use Cases

I need to deserialize an object that has a Table as a field.
The serialization is already implemented.

### Packages

com.google.common.collect

### Checklist

- [X] I agree to follow the [code of conduct](https://github.com/google/.github/blob/master/CODE_OF_CONDUCT.md).

- [X] I have read and understood the [contribution guidelines](https://github.com/google/guava/wiki/HowToContribute#feature-requests).

- [X] I have read and understood [Guava's philosophy](https://github.com/google/guava/wiki/PhilosophyExplained), and I strongly believe that this proposal aligns with it.

- [X] I have visited the [idea graveyard](https://github.com/google/guava/wiki/IdeaGraveyard), and did not see anything similar to this idea.

**Comment by Stephan202** [comment]
This issue looks a lot like #6893. Is there anything that blocks Jackson from implementing the missing deserialization support?

(Related Jackson ticket: FasterXML/jackson-datatypes-collections#1. CC @cowtowncoder.)

**Comment by netdpb** [comment]
It does seem to me that the proper path forward is for Jackson to implement a deserializer for Guava's `ImmutableTable` rather than to introduce a public constructor.

**Comment by cowtowncoder** [comment]
Agreed: I don't think there is anything Guava should need to add (besides, any new addition would be for latest Guava and Jackson module is designed to work with a wide range of Guava versions so cannot rely on latest).
Someone just needs to take time to write a Jackson `JsonDeserializer` for `Table` type.

**Comment by netdpb** [comment]
OK, thanks for confirming. I'll go ahead and close this issue then.
