### ISSUE TITLE
debug android

### ISSUE THREAD

**Issue by sadra139113911391** [google/guava#6994]
### 1. What are you trying to do?

debug

### 2. What's the best code you can write to accomplish that without the new feature?

debug

### 3. What would that same code look like if we added your feature?

debug

### Concrete Use Cases

debug

### Packages

com.google.common.annotations

### Checklist

- [X] I agree to follow the [code of conduct](https://github.com/google/.github/blob/master/CODE_OF_CONDUCT.md).

- [X] I have read and understood the [contribution guidelines](https://github.com/google/guava/wiki/HowToContribute#feature-requests).

- [X] I have read and understood [Guava's philosophy](https://github.com/google/guava/wiki/PhilosophyExplained), and I strongly believe that this proposal aligns with it.

- [X] I have visited the [idea graveyard](https://github.com/google/guava/wiki/IdeaGraveyard), and did not see anything similar to this idea.

**Comment by chaoren** [comment]
Please stop spamming the repo with these nonsense issues and pull requests. You don't have to actually send these to us if you're doing some kind of debugging.
