### ISSUE TITLE
Addition of Built-In Methods for Primitive Math operations

### ISSUE THREAD

**Issue by harishwar-babu** [google/guava#7050]
### 1. What are you trying to do?

*  I would like to add a new feature that focus on performing addition of 2 numbers irrespective of type (int,int) or (long,long) or (short,short). that too with the help of bitwise operators(^,&).
* similarly for checking whether the number is even or odd. using & operator.
* Note: The above 2 features will not work for double/floating point numbers It will work only for whole/natural numbers.
* so, these are the above 2 features I would like to add to the Guava Math library.

### 2. What's the best code you can write to accomplish that without the new feature?

[ExisitingFeature.txt](https://github.com/google/guava/files/14427887/ExisitingFeature.txt)

### 3. What would that same code look like if we added your feature?

[NewFeature.txt](https://github.com/google/guava/files/14427892/NewFeature.txt)

### (Optional) What would the method signatures for your feature look like?

```java
// for addition of two numbers.
public int add(int value1,int value2);
public long add(long value1,long value2);
public short add(short value1,short value2);

//for even number check
public int isEven(int value);
public long isEven(long value);
public short isEven(short value);
```

### Concrete Use Cases

[use-case.txt](https://github.com/google/guava/files/14428076/use-case.txt)

### Packages

com.google.common.math

### Checklist

- [X] I agree to follow the [code of conduct](https://github.com/google/.github/blob/master/CODE_OF_CONDUCT.md).

- [X] I have read and understood the [contribution guidelines](https://github.com/google/guava/wiki/HowToContribute#feature-requests).

- [X] I have read and understood [Guava's philosophy](https://github.com/google/guava/wiki/PhilosophyExplained), and I strongly believe that this proposal aligns with it.

- [X] I have visited the [idea graveyard](https://github.com/google/guava/wiki/IdeaGraveyard), and did not see anything similar to this idea.

**Comment by cpovirk** [comment]
As discussed in https://github.com/google/guava/pull/6982#issuecomment-1939290459, the performance argument for the bitwise addition operations these is difficult to believe. For previous discussion of `isEven`, see https://github.com/google/guava/issues/1229.
