### ISSUE TITLE
class file for com.google.errorprone.annotations.CompatibleWith not found

### ISSUE THREAD

**Issue by cowwoc** [google/guava#7233]
### Description

As a follow-up for https://github.com/google/guava/issues/2721, I am getting this problem using JDK 22, -Werror, and -Wlint:all

I tried adding:

```
<dependency>
	<groupId>com.google.errorprone</groupId>
	<artifactId>error_prone_annotations</artifactId>
	<version>2.26.1</version>
</dependency>
```

but it did not help. I will include the maven -X (full debug) output for you to review.

This only seems to occur when compiling unit tests though. `default-compile` works fine but `default-testCompile` fails

[build.log](https://github.com/google/guava/files/15417637/build.log)

As you can see at the end of the log, errorprone *is* on the compiler classpath, so I'm at a loss as to why this is failing.

### Expected Behavior

No compiler warnings/errors

### Actual Behavior

Compiler warnings/errors

### Checklist

- [X] I agree to follow the [code of conduct](https://github.com/google/.github/blob/master/CODE_OF_CONDUCT.md).

**Comment by cowwoc** [comment]
Correction, errorprone is on the module path, not class path, but so are all the other JARs. I don't have a choice because my library uses Java Modules and if I try running with `<useModulePath>false</useModulePath>` I get an error in my own `module-info.java`. In any case, I don't think this is the source of the problem.

**Comment by cowwoc** [comment]
Gah! I figured it out.

If guava or the annotation JAR is placed on the module-path then the project must explicitly add `requires com.google.errorprone.annotations` to its `module-info`; otherwise, the compiler will behave as if the class cannot be found (when in fact, it can be).

Another workaround, for anyone wanting to try something different, is to add `-Xlint:classfile`. This will suppress these kind of warnings.

**Comment by cpovirk** [comment]
Ah, thanks. This is another reason for us to get our modules story in order. (I double-checked that you've been on https://github.com/google/guava/issues/2970....)

(I'd not sure I was aware of `-Xlint:classfile`!)
