### ISSUE TITLE
The PSL has been not been updated for over 3 months

### ISSUE THREAD

**Issue by jerechenamz** [google/guava#7268]
### Description

According to the file history of the PSL https://github.com/google/guava/commits/v33.2.0/guava/src/com/google/thirdparty/publicsuffix/PublicSuffixPatterns.java?before=73856da06403d5d087007d3924c168c822dea23c+35

It updates at least every 6 weeks, but it has been 3 months since this was updated. Do we know how long it will take until the PSL is updated?

### Example

```java
File history of the PSL https://github.com/google/guava/commits/v33.2.0/guava/src/com/google/thirdparty/publicsuffix/PublicSuffixPatterns.java?before=73856da06403d5d087007d3924c168c822dea23c+35
```

### Expected Behavior

PSL is updated every 6 weeks.

### Actual Behavior

PSL hasn't been updated for 3 months.

### Checklist

- [X] I agree to follow the [code of conduct](https://github.com/google/.github/blob/master/CODE_OF_CONDUCT.md).

**Comment by cpovirk** [comment]
Thanks for checking on this. The last I saw, the update had gotten hung up on a failure from a completely bogus test in another team's project, and they'd refused to take responsibility for fixing it. The person who was trying to submit the update then left for a long vacation.

We could eventually try to push this through ourselves, but I'm not sure when we'd get around for it. Are you mostly checking to make sure that the process will eventually be restored, or is the current lack of updates potentially causing problems (either from specific missing updates or from a general reliance on up-to-date info)? (In their case, this is more fodder for https://github.com/google/guava/issues/475 and/or a more regular release cadence.)

**Comment by jerechenamz** [comment]
> Are you mostly checking to make sure that the process will eventually be restored, or is the current lack of updates potentially causing problems (either from specific missing updates or from a general reliance on up-to-date info)?

Really both, but more the latter.  By using Guava, we would expect regular updates to the PSL on a set schedule.  We are seeing changes over 3 months old on the PSL that are not reflected. This was brought to our attention when a specific update was missing in our software.

**Comment by cpovirk** [comment]
Thanks.

It looks like the anonymous team I was implicitly blaming was the wrong anonymous team to blame. I think I have now tracked down the team actually responsible, and I've proposed a change to unblock the update.

**Comment by cpovirk** [comment]
Two updates landed in time for https://github.com/google/guava/releases/tag/v33.3.0
