### ISSUE TITLE
Bug - com.google.common.collect.ConcurrentHashMultiset.setCount(Object, int)

### ISSUE THREAD

**Issue by d-ferra** [google/guava#7312]
### Guava Version

33.2.1

### Description

A "NullPointerException" can be generated by setting args[0]=null, but not described into the specification.

### Example

```java
public class ConcurrentHashMultiset_5_failure_Test{
	
	public void testSetCount_IllegalArgumentException_CountIsNegative() throws Throwable {
        ConcurrentHashMultiset<Locale.Category> concurrentHashMultiset0 = ConcurrentHashMultiset.create();
        ConcurrentHashMultiset<Object> concurrentHashMultiset1 = ConcurrentHashMultiset.create((Iterable<?>) concurrentHashMultiset0);
		try {
			concurrentHashMultiset1.setCount((Object) null, (-2031));
                        org.junit.Assert.fail();
		} catch (NullPointerException e) {
			
		}
	}
}
```

### Expected Behavior

The code should throw an IllegalArgumentException.
Description in the JavaDoc: @throws IllegalArgumentException if {@code count} is negative.

### Actual Behavior

The code generate a NullPointerException.

### Packages

com.google.common.collect

### Checklist

- [X] I agree to follow the [code of conduct](https://github.com/google/.github/blob/master/CODE_OF_CONDUCT.md).

- [X] I can reproduce the bug with the [latest](https://github.com/google/guava/releases/latest) version of Guava available.

**Comment by perceptron8** [comment]
See https://guava.dev/releases/33.2.1-jre/api/docs/com/google/common/collect/ConcurrentHashMultiset.html#:~:text=Null%20elements%20are%20not%20supported.
> Null elements are not supported.

**Comment by cpovirk** [comment]
See also https://github.com/google/guava/issues/7307.
