### ISSUE TITLE
Bug - com.google.common.collect.ConcurrentHashMultiset.setCount(Object, int, int)

### ISSUE THREAD

**Issue by d-ferra** [google/guava#7313]
### Guava Version

33.2.1

### Description

A "NullPointerException" can be generated by setting args[0]=null, but not described into the specification.

### Example

```java
public class ConcurrentHashMultiset_6_failure_Test{
	
	public void testSetCount_IllegalArgumentException_ExpectedOldCountOrNewCountIsNegative() throws Throwable {
		ConcurrentHashMultiset<Locale.Category> concurrentHashMultiset0 = ConcurrentHashMultiset.create();
                ConcurrentHashMultiset<Object> concurrentHashMultiset1 = ConcurrentHashMultiset.create((Iterable<?>) concurrentHashMultiset0);
		try {
			concurrentHashMultiset1.setCount((Object) null, (-2031), 67);               
                        org.junit.Assert.fail();
		} catch (NullPointerException e) {

			}
	}
}
```

### Expected Behavior

The code should throw an IllegalArgumentException.
Description in the JavaDoc:@throws IllegalArgumentException if {@code expectedOldCount} or {@code newCount} is negative

### Actual Behavior

The code generate a NullPointerException.

### Packages

com.google.common.collect

### Checklist

- [X] I agree to follow the [code of conduct](https://github.com/google/.github/blob/master/CODE_OF_CONDUCT.md).

- [X] I can reproduce the bug with the [latest](https://github.com/google/guava/releases/latest) version of Guava available.

**Comment by cpovirk** [comment]
Similar to https://github.com/google/guava/issues/7307.
