### ISSUE TITLE
Bug - com.google.common.collect.Iterators.partition(Iterator<Object>, int)

### ISSUE THREAD

**Issue by d-ferra** [google/guava#7314]
### Guava Version

33.2.1

### Description

A "NullPointerException" can be generated by setting args[0]=null, but not described into the specification

### Example

```java
public class Iterators_5_failure_Test{
	public void testPartition_IllegalArgumentException_SizeIsNonpositive() throws Throwable {
		try {
			Iterators.partition((Iterator<Object>) null, 0);
                        org.junit.Assert.fail();
		} catch (NullPointerException e) {
            
        }
	}
}
```

### Expected Behavior

The code should throw an IllegalArgumentException.
Description in the JavaDoc: @throws IllegalArgumentException if {@code size} is nonpositive.

### Actual Behavior

The code generate a NullPointerException.

### Packages

com.google.common.collect

### Checklist

- [X] I agree to follow the [code of conduct](https://github.com/google/.github/blob/master/CODE_OF_CONDUCT.md).

- [X] I can reproduce the bug with the [latest](https://github.com/google/guava/releases/latest) version of Guava available.

**Comment by cpovirk** [comment]
Similar to https://github.com/google/guava/issues/7307.
