### ISSUE TITLE
Bug - com.google.common.collect.Iterators.limit(Iterator<FilteringMode>, int)

### ISSUE THREAD

**Issue by d-ferra** [google/guava#7316]
### Guava Version

33.2.1

### Description

A "NullPointerException" can be generated by setting args[0]=null, but not described into the specification

### Example

```java
public class Iterators_11_failure_Test{
	public void testLimit_IllegalArgumentException_LimitSizeIsNegative() throws Throwable {
		try {
			 Iterators.limit((Iterator<Locale.FilteringMode>) null, (-14));
                         org.junit.Assert.fail();
		} catch (NullPointerException e) {
        
		}
	}
}
```

### Expected Behavior

The code should throw an IllegalArgumentException.
Description in the JavaDoc: @throws IllegalArgumentException if {@code limitSize} is negative

### Actual Behavior

The code generate a NullPointerException.

### Packages

com.google.common.collect

### Checklist

- [X] I agree to follow the [code of conduct](https://github.com/google/.github/blob/master/CODE_OF_CONDUCT.md).

- [X] I can reproduce the bug with the [latest](https://github.com/google/guava/releases/latest) version of Guava available.

**Comment by cpovirk** [comment]
Similar to https://github.com/google/guava/issues/7307.
