### ISSUE TITLE
bytecode contains unexpected annotations

### ISSUE THREAD

**Issue by GGGTTTTT** [google/guava#7331]
### Guava Version

33.2.1-jre

### Description

In the latest version of Guava, the bytecode for the method com.google.common.base.Joiner#iterable contains unexpected annotations.
![image](https://github.com/user-attachments/assets/a19e7cd8-b8b9-45aa-bb88-f57dc5a53fb9)

### Example

```java
You can simply use the jclasslib ByteCode Viewer to inspect the class files.
```

### Expected Behavior

![image](https://github.com/user-attachments/assets/b27a3ec3-e9f4-4ee0-a963-67d69f21ff7d)

### Actual Behavior

![image](https://github.com/user-attachments/assets/f3544977-5f40-418a-8729-93bd5116b675)

### Packages

com.google.common.base

### Platforms

Java 8

### Checklist

- [X] I agree to follow the [code of conduct](https://github.com/google/.github/blob/master/CODE_OF_CONDUCT.md).

- [X] I can reproduce the bug with the [latest](https://github.com/google/guava/releases/latest) version of Guava available.

**Comment by cpovirk** [comment]
Thanks, that looks like a javac bug from when I switched from using a javac from a Google-built JDK11 to one from a Debian stock JDK11. How much trouble does the problem annotation cause you?

```
$ /usr/local/buildtools/java/jdk11/bin/java -version                                                                                                                                                             
openjdk version "11.0.20.1" 2024-04-11
OpenJDK Runtime Environment (build 11.0.20.1+1-google-release-623923767)
OpenJDK 64-Bit Server VM (build 11.0.20.1+1-google-release-623923767, mixed mode, sharing)

$ JAVA_HOME=/usr/local/buildtools/java/jdk11 mvn clean package -f guava -Dmaven.javadoc.skip -Dmaven.source.skip && javap -private -v -cp guava/target/guava-33.2.1-jre.jar com.google.common.base.Joiner | perl -ne 'print if /iterable[(]/ ... /^\s*$/' | perl -ne 'print if (/RuntimeVisibleTypeAnnotations/ ... /RuntimeVisibleParameterAnnotations/) && !/RuntimeVisibleParameterAnnotations/ && !/RuntimeVisibleTypeAnnotations/'
...
      0: #74(): METHOD_RETURN, location=[TYPE_ARGUMENT(0)]
        org.checkerframework.checker.nullness.qual.Nullable
      1: #74(): METHOD_FORMAL_PARAMETER, param_index=2, location=[ARRAY]
        org.checkerframework.checker.nullness.qual.Nullable
```

```
$ /usr/lib/jvm/java-11-openjdk-amd64/bin/java -version
openjdk version "11.0.22" 2024-01-16
OpenJDK Runtime Environment (build 11.0.22+7-post-Debian-1)
OpenJDK 64-Bit Server VM (build 11.0.22+7-post-Debian-1, mixed mode, sharing)

$ JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64 mvn clean package -f guava -Dmaven.javadoc.skip -Dmaven.source.skip && javap -private -v -cp guava/target/guava-33.2.1-jre.jar com.google.common.base.Joiner | perl -ne 'print if /iterable[(]/ ... /^\s*$/' | perl -ne 'print if (/RuntimeVisibleTypeAnnotations/ ... /RuntimeVisibleParameterAnnotations/) && !/RuntimeVisibleParameterAnnotations/ && !/RuntimeVisibleTypeAnnotations/'
...
      0: #74(): METHOD_RETURN, location=[TYPE_ARGUMENT(0)]
        org.checkerframework.checker.nullness.qual.Nullable
      1: #74(): METHOD_FORMAL_PARAMETER, param_index=2, location=[ARRAY]
        org.checkerframework.checker.nullness.qual.Nullable
      2: #74(): CLASS_EXTENDS, type_index=65535, location=[TYPE_ARGUMENT(0)]
        org.checkerframework.checker.nullness.qual.Nullable
```

The Google version is nominally a lower version number, so either the bug was introduced after that point, the bug was patched in the Google version, or there was some other difference in where Debian gets its version from. Hmm, a `openjdk-11.0.16` that I have lying around also shows the bug. That sounds like further reason to believe that Google patched the bug. And it looks like the bug is [JDK-8198945](https://bugs.openjdk.org/browse/JDK-8198945).

As the bug report suggests, the problem goes away if I use `/usr/lib/jvm/java-17-openjdk-amd64`. The problem with that is that it [breaks JDiff](https://github.com/google/guava/issues/6549#issuecomment-1761654083) (which we should probably [migrate away from](https://github.com/google/guava/issues/6549#issuecomment-1995843132)). But the right thing to do would be to automatically download and use the newest javac that we can, presumably by [using Maven toolchains](https://github.com/google/guava/issues/3990#issuecomment-1444307178).

I _might_ just be able to perform future releases with `jdk-12.0.2`, which has the fix but doesn't yet break JDiff :) I'll test it out now and report back if there are any problems.

**Comment by cpovirk** [comment]
With JDK12, I see failures in Javadoc:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.5.0:jar (attach-docs) on project guava: MavenReportException: Error while generating Javadoc: 
[ERROR] Exit code: 1
[ERROR] javadoc: error - The code being documented uses modules but the packages defined in https://errorprone.info/api/latest/ are in the unnamed module.
[ERROR] javadoc: error - The code being documented uses modules but the packages defined in https://static.javadoc.io/com.google.j2objc/j2objc-annotations/1.1/ are in the unnamed module.
[ERROR] javadoc: warning - URL https://docs.oracle.com/javase/9/docs/api/element-list was redirected to https://docs.oracle.com/en/java/javase/22/ -- Update the command-line options to suppress this warning.
[ERROR] javadoc: error - The code being documented uses modules but the packages defined in https://checkerframework.org/api/ are in the unnamed module.
```

Updating to maven-javadoc-plugin:3.8.0 doesn't help (though I should probably do that anyway). There may be a way to work around the problem, but I should probably make a quick attempt at changing our maven-compiler-plugin setup to use a toolchain instead.

**Comment by ben-manes** [comment]
> [ERROR] javadoc: error - The code being documented uses modules but the packages defined in https://errorprone.info/api/latest/ are in the unnamed module.

I believe that is the `-link-modularity-mismatch` warning that can be downgraded to `info` in jdk18. It shouldn't be an error unless you fail on warnings (e.g. `-Werror`). When multi-release jars add the module metadata, they don't usually generate modular javadoc which causes this mismatch warning. It is harmless though.

**Comment by cpovirk** [comment]
Reopening temporarily to get this into our internal tracking system.

**Comment by GGGTTTTT** [comment]
Thank you very much for your response. Due to usage of agent developed based on byte-buddy, it caused unexpected errors, but it hasn't caused significant problems.

**Comment by cpovirk** [comment]
Thanks. I'm not sure yet when our next release will be, but this will be in it.

**Comment by cpovirk** [comment]
The fix is now released in https://github.com/google/guava/releases/tag/v33.3.0. Please let us know if you see any similar trouble on the future.
