### ISSUE TITLE
Add constant for 'Alt-Svc' to com.google.common.net.HttpHeaders

### ISSUE THREAD

**Issue by sdavids** [google/guava#7373]
### API(s)

```java
com.google.common.net.HttpHeaders
```

### How do you want it to be improved?

Please add a constant for [Alt-Svc](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Alt-Svc).

### Why do we need it to be improved?

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Alt-Svc

### Example

```java
response.setHeader(HttpHeaders.ALT_SVC, "h3-25=\":443\"; ma=3600, h2=\":443\"; ma=3600");
```

### Current Behavior

no constant

### Desired Behavior

constant for "Alt-Svc" exists

### Concrete Use Cases

HTTP/3 endpoint advertisement in Java-based API gateway.

### Checklist

- [X] I agree to follow the [code of conduct](https://github.com/google/.github/blob/master/CODE_OF_CONDUCT.md).

- [X] I have read and understood the [contribution guidelines](https://github.com/google/guava/wiki/HowToContribute#feature-requests).

- [X] I have read and understood [Guava's philosophy](https://github.com/google/guava/wiki/PhilosophyExplained), and I strongly believe that this proposal aligns with it.

**Comment by kluever** [comment]
Fixed via https://github.com/google/guava/commit/503ba429f9fbd4d2ef9a4c0ea28ccf62bed36afc
