### ISSUE TITLE
Query in Release strategy and Support 

### ISSUE THREAD

**Issue by ramkumar-92** [google/guava#7384]
Hello,

I am planning to use Guava version 33.3.0 in my application, and I have a couple of questions regarding the release and support strategy:

**Release Strategy:**

I noticed that new versions are released approximately every two months this year. Could you please clarify if this is the standard release calendar for Guava ? Is there a fixed schedule or criteria for releasing new versions?

**Long-Term Support:**

What is the long-term support policy for version 33.3.0 ? Specifically, until when can I expect to receive support, including bug fixes or security updates for this version?
If I encounter any bugs or issues in version 33.3.0, how should I report them, and what is the typical response time or process for addressing such issues?
Any insights or additional information regarding the release and support strategy would be greatly appreciated.

Thank you!

**Comment by eamonnmcmanus** [comment]
A reminder that Guava is free software.

We do not commit to any release schedule, though the release cadence you have observed is typical.

We do not formally support Guava, but we will usually fix important issues fairly promptly.

We do not usually patch old releases. To get a bugfix, you need to update to at least the release where it was added.
