### ISSUE TITLE
#toString() for Immutable*.Builder (incl. e.g. ImmutableEntry)

### ISSUE THREAD

**Issue by vorburger** [google/guava#7408]
### API(s)

* `com.google.common.collect.ImmutableMap.Builder`
* ...
* `com.google.common.collect.ImmutableEntry`

### How do you want it to be improved?

When debugging, it would be neat if these had working `toString()` ... at least I was just missing it, while debugging something.

### Why do we need it to be improved?

As far as I can tell, this seems to be more of an oversight / lack of any previously expressed user request, than intentional design?

Background: #82

### Example

```java
ImmutableMap.<String,Integer>builder().put("a", 123).toString()
```

### Current Behavior

```com.google.common.collect.ImmutableMap$Builder@ffaa6af```

### Desired Behavior

```{a = 123}```

### Concrete Use Cases

Debugging.

### Checklist

- [X] I agree to follow the [code of conduct](https://github.com/google/.github/blob/master/CODE_OF_CONDUCT.md).

- [X] I have read and understood the [contribution guidelines](https://github.com/google/guava/wiki/HowToContribute#feature-requests).

- [X] I have read and understood [Guava's philosophy](https://github.com/google/guava/wiki/PhilosophyExplained), and I strongly believe that this proposal aligns with it.

**Comment by vorburger** [comment]
If anyone reviewing this would welcome a contribution for this, I'm happy to have a go at it and propose something.

**Comment by lowasser** [comment]
What would you expect from an `ImmutableSet.Builder` that has _partially_ deduplicated its elements? (`ImmutableSortedSet.Builder` does this, for example.)

That's the main reason I'd hesitate for this.  I would never want to guarantee consistency between releases, for example, of the `toString` behavior.

**Comment by vorburger** [comment]
> What would you expect from an `ImmutableSet.Builder` that has _partially_ deduplicated its elements? (`ImmutableSortedSet.Builder` does this, for example.)

Hm, interesting. I guess, particularly as intended for debugging output, one would simply want it to "look more like the current state of the Builder, not how the built object might look like" - sort of thing? So looking at `com.google.common.collect.ImmutableSortedSet.Builder`, (something like) this would IMHO be just fine:

```java
@Override
public String toString() {
  return Arrays.deepToString(copy());
}
```

> That's the main reason I'd hesitate for this. I would never want to guarantee consistency between releases, for example, of the `toString` behavior.

Fully agreed, and I wouldn't / one shouldn't expect this. I am only suggesting this for viewing (without IDE configuration for customer viewer) in the debugger.

**Comment by ben-manes** [comment]
I use `ToStringBuilder.reflectionToString(builder)` when necessary, which I think is ugly enough to convey it’s for debugging only. For public apis this [recommendation](https://www.infoq.com/articles/API-Design-Joshua-Bloch/) always concerns me about being too liberal with offering a toString() in my libraries.

> Provide programmatic access to all data available in string form. Otherwise, programmers will be forced to parse strings, which is painful. Worse, the string forms will turn into de facto APIs

**Comment by cpovirk** [comment]
I share the nervousness discussed above. While _extremely_ unlikely to be a problem for any individual user, it may eventually come up, and then we'll be hearing from someone who used `ImmutableMap.Builder.toString()` to detect whether `buildOrThrow()` was going to throw or to even extract the multiple values for a given key or something, only for that to predictably break in the future :)

I do wonder if there would occasionally be things that we could do to better support debuggers without custom configuration. For example, it is probably the case that we could _currently_ give `ImmutableSet.SetBuilderImpl` a good `toString()`, which would then be rendered for someone who selects `Builder.impl` in a debugger but which wouldn't be exposed anywhere that a normal program could get at it.

**Comment by vorburger** [comment]
Thanks for all the feedback! (It's IMHO great to have this recorded, in case anyone searches the issue tracker in the future about this.)

It sounds like the conclusion here is  "nah, we really don't want this".

Let's just close this issue then? Totally fine!
