### ISSUE TITLE
`checkNotNull` method cannont perform non-null validation

### ISSUE THREAD

**Issue by yashuangyi** [google/guava#7409]
### Guava Version

32.1.2-jre

### Description

com.google.common.collect.Lists#newArrayList(E... elements)
```  @SafeVarargs
  @GwtCompatible(serializable = true)
  public static <E extends @Nullable Object> ArrayList<E> newArrayList(E... elements) {
    checkNotNull(elements); // for GWT
    // Avoid integer overflow when a large array is passed in
    int capacity = computeArrayListCapacity(elements.length);
    ArrayList<E> list = new ArrayList<>(capacity);
    Collections.addAll(list, elements);
    return list;
  }```

When the input parameter of this method (E... elements) is null, this parameter will automatically be converted into an empty array. At this point, the ‘checkNotNull’ method cannot effectively perform non-null validation and throw an exception.

### Example

```java
public static void main(String[] args) {
    TestResult data = null;
    ArrayList list = Lists.newArrayList(data);
    System.out.println(list);
}

Run once with data null, the result is [null](the list is not null while it's element is null) but not null. So the method `checkNotNull` don't work for com.google.common.collect.Lists#newArrayList(E... elements)
```

### Expected Behavior

when input is null, the  ‘checkNotNull’ method should effectively perform non-null validation and throw an exception.

### Actual Behavior

when input is null, the  ‘checkNotNull’ method cannot effectively perform non-null validation and throw an exception.

### Packages

com.google.common.collect

### Platforms

Java 8

### Checklist

- [X] I agree to follow the [code of conduct](https://github.com/google/.github/blob/master/CODE_OF_CONDUCT.md).

- [X] I can reproduce the bug with the [latest](https://github.com/google/guava/releases/latest) version of Guava available.

**Comment by eamonnmcmanus** [comment]
Duplicate of #7410.
