### ISSUE TITLE
Add omitEmpty flag setter to toStringHelper

### ISSUE THREAD

**Issue by YutaHiguchi-bsn** [google/guava#7415]
### 1. What are you trying to do?

This is similar to #1404 adding support of omitting empty values from toStringHelper output.

What I noticed is that the current code already has the feature,
just that there is no public method like `omitNullValues()` to enable the `omitEmptyValues` flag.

https://github.com/google/guava/blob/5da71a77865cbab3d0609b7faf8509685241ffce/guava/src/com/google/common/base/MoreObjects.java#L155

It supports various types detecting empty-ness
https://github.com/google/guava/blob/5da71a77865cbab3d0609b7faf8509685241ffce/guava/src/com/google/common/base/MoreObjects.java#L334-L356

Can `omitEmptyValues()` be added to `ToStringHelper` methods, so that the implemented feature can be exercised?

### 2. What's the best code you can write to accomplish that without the new feature?

```java
        return MoreObjects.toStringHelper(this)
            .omitNullValues()
            .add("optional", optional.orElse(null))
            .add("array", Array.getLength(array) == 0 ? null : array)
            .add("collection", collection.isEmpty() ? null : collection)
            .toString();
```

### 3. What would that same code look like if we added your feature?

```java
        return MoreObjects.toStringHelper(this)
            .omitEmptyValues()
            .add("optional", optional)
            .add("array", array)
            .add("collection", collection)
            .toString();
```

### Concrete Use Cases

Exclude empty Optional, Collection, etc. from toString() output.

### Packages

com.google.common.base

### Checklist

- [X] I agree to follow the [code of conduct](https://github.com/google/.github/blob/master/CODE_OF_CONDUCT.md).

- [X] I have read and understood the [contribution guidelines](https://github.com/google/guava/wiki/HowToContribute#feature-requests).

- [X] I have read and understood [Guava's philosophy](https://github.com/google/guava/wiki/PhilosophyExplained), and I strongly believe that this proposal aligns with it.

- [X] I have visited the [idea graveyard](https://github.com/google/guava/wiki/IdeaGraveyard), and did not see anything similar to this idea.

**Comment by kluever** [comment]
Good eye --- we have this exact feature available internally (which is why some of the implementation bits have "leaked" into Guava). I'm not opposed to open-sourcing it, given that "emptiness" seems to be a fairly well-understood (but not officially documented or statically encoded) concept.

I think we'll need to beef up the javadocs on our API a bit --- we may want to explicitly list the current types we check for emptiness, and also give ourselves some wiggle room for expanding (or shrinking) that list in the future.
