### ISSUE TITLE
Mention `Thread.Builder` in `ThreadFactoryBuilder`s javadocs

### ISSUE THREAD

**Issue by bjmi** [google/guava#7427]
### API(s)

com.google.common.util.concurrent.ThreadFactoryBuilder

### How do you want it to be improved?

Just as you can assign the the starting value of the counter for a Thread Builder / ThreadFactory  (`java.lang.Thread.Builder.name(String prefix, long start)`), 
you should also be able to assign the start value for Guava's `com.google.common.util.concurrent.ThreadFactoryBuilder`.

How about adding the following overload `ThreadFactoryBuilder.setNameFormat(String nameFormat, long start)`?

### Checklist

- [x] I agree to follow the [code of conduct](https://github.com/google/.github/blob/master/CODE_OF_CONDUCT.md).

- [x] I have read and understood the [contribution guidelines](https://github.com/google/guava/wiki/HowToContribute#feature-requests).

- [x] I have read and understood [Guava's philosophy](https://github.com/google/guava/wiki/PhilosophyExplained), and I strongly believe that this proposal aligns with it.

**Comment by xc-x** [comment]
Hi I would like to complete this issue. Can you plz assign it to me?

**Comment by u7683345** [comment]
take

**Comment by u7683345** [comment]
I am new to open source and think I know how to solve this. Can I get assigned? Thanks!
-Andrew
@bjmi

**Comment by MsSteph74** [comment]
?

**Comment by kluever** [comment]
Is there any reason you can't use the `Thread.Builder` API in Java 21? I think that mostly obsoletes our `ThreadFactoryBuilder` API.

**Comment by netdpb** [comment]
Hi @xc-x and @u7683345. Thanks for your interest in helping here. We're still not sure whether we want to add this feature at all. If we do decide to add it, we might be able to use your help.

**Comment by bjmi** [comment]
> Is there any reason you can't use the `Thread.Builder` API in Java 21? I think that mostly obsoletes our `ThreadFactoryBuilder` API.

That's right. Then this request will benefit those who do not yet have Java 21 in use.

**Comment by kluever** [comment]
In general, we don't add features just for parity with JDK releases. If you have a compelling use case, we can discuss it, but the fact that it's been 14 years since this was created, and nobody has asked for it, makes me hesitant. The ID number is fairly arbitrary, and just meant to be a unique name to identify the thread. Why do you care if the numbering starts at 0 or 999 or whatever?

**Comment by bjmi** [comment]
We mainly use `setDaemon` and `setNameFormat` of the `ThreadFactoryBuilder` and both is supported by JDK `Thread.Builder`.  
We will follow the suggestion and switch to the JDK variant and makes this issue obsolete.
Nevertheless, a reference to the JDK counterpart in the Javadoc would be helpful.

**Comment by kluever** [comment]
Closing for now...happy to re-evaluate if someone has a strong use case for caring about the # that the thread name starts at.
