### ISSUE TITLE
Feature Request: Random Data Population for Model/Entity Classes

### ISSUE THREAD

**Issue by Mamun-Al-Babu-Shikder** [google/guava#7512]
### 1. What are you trying to do?

The primary goal of this feature is to create a utility that can **automatically populate Java model or entity classes with random data**. This is particularly useful in testing scenarios, where developers need to quickly generate realistic data to fill databases, verify application functionality, or conduct load testing.

**Key Objectives:**

1. Enable Quick Data Generation: Automate the creation of random data for model classes to streamline the setup of test environments.
2. Support Complex Models: Handle both simple fields and nested/recursive fields, so model classes with associated or nested objects are fully populated. 
3. Customizable and Flexible Population: Provide customization options to ignore specific fields, specify ranges or formats for data, and support extensibility with custom data generators. This ensures developers can adapt the tool to various needs without rewriting data-generation code each time.

### 2. What's the best code you can write to accomplish that without the new feature?

Without implementing a dedicated feature, we can create a basic solution by combining Java’s reflection capabilities with random data generation using libraries like java.util.Random or java-faker. Here’s an example of how you can accomplish random data population for a simple model class without the dedicated utility:

**Example: Basic Random Data Populator Using Reflection**
This approach will:

1. Iterate over fields in a class using reflection.
2. Use random data generation based on field types.
3. Populate nested objects recursively.
4. Allow for basic customization by specifying fields to ignore.

public class RandomDataPopulator {

    private static final Random random = new Random();

    public static <T> T populate(Class<T> clazz, Set<String> ignoreFields) {
        try {
            T instance = clazz.getDeclaredConstructor().newInstance();
            for (Field field : clazz.getDeclaredFields()) {
                field.setAccessible(true);

                // Skip ignored fields
                if (ignoreFields.contains(field.getName())) continue;

                // Generate random data based on field type
                if (field.getType() == String.class) {
                    field.set(instance, "RandomString" + random.nextInt(1000));
                } else if (field.getType() == int.class || field.getType() == Integer.class) {
                    field.set(instance, random.nextInt(100));
                } else if (field.getType() == boolean.class || field.getType() == Boolean.class) {
                    field.set(instance, random.nextBoolean());
                } else if (field.getType().isAssignableFrom(List.class)) {
                    // Populate list fields if needed (basic example here)
                } else if (!field.getType().isPrimitive()) {
                    // Recursive population for nested objects
                    Object nestedObject = populate(field.getType(), ignoreFields);
                    field.set(instance, nestedObject);
                }
            }
            return instance;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

    // Testing the basic populator
    public static void main(String[] args) {
        Set<String> ignoreFields = Set.of("id"); // Example of ignoring fields
        MyModel randomModel = RandomDataPopulator.populate(MyModel.class, ignoreFields);
        System.out.println(randomModel);
    }
}

### 3. What would that same code look like if we added your feature?

With the proposed feature, the code would become significantly simpler, more readable, and more flexible. By using a builder pattern, the new utility would allow us to specify customization options, including ignored fields and specific ranges or formats for random data. Here’s how the code would look using the new feature:

public class TestRandomDataPopulation {

    public static void main(String[] args) {
        // Create a random instance of MyModel with specified configurations
        MyModel randomModel = RandomDataPopulator.builder(MyModel.class)
            .ignoreField("id")                // Skip setting the 'id' field
            .ignoreField("timestamp")          // Skip setting the 'timestamp' field
            .range("age", 18, 65)              // Set age within the range 18-65
            .format("name", RandomDataPopulator.Format.NAME) // Generate a realistic name for 'name' field
            .depthLimit(3)                     // Limit recursive population depth to prevent infinite loops
            .build();
        
        System.out.println(randomModel);  // Print populated model for testing
    }
}

### (Optional) What would the method signatures for your feature look like?

```java

```

### Concrete Use Cases

Here are some concrete, real-world use cases where random data population for model or entity classes can be highly beneficial:

1. Database Seeding for Testing and Development Environments
2. Load Testing and Performance Benchmarking
3. Automated End-to-End Testing of REST APIs
4. Simulating User Behavior in QA Environments
5. Data-Driven Testing of Machine Learning Models
6. Testing Data Serialization and Deserialization Logic
7. Generating Data for Graph-Based Relationship Testing
8. Validating Constraints and Edge Cases in Database Schemas

### Checklist

- [x] I agree to follow the [code of conduct](https://github.com/google/.github/blob/master/CODE_OF_CONDUCT.md).

- [x] I have read and understood the [contribution guidelines](https://github.com/google/guava/wiki/HowToContribute#feature-requests).

- [x] I have read and understood [Guava's philosophy](https://github.com/google/guava/wiki/PhilosophyExplained), and I strongly believe that this proposal aligns with it.

- [x] I have visited the [idea graveyard](https://github.com/google/guava/wiki/IdeaGraveyard), and did not see anything similar to this idea.

**Comment by kluever** [comment]
This is definitely a neat idea, but I'm not sure it's a great match for Guava. Seems like it might be a better fit for an existing fuzzing framework/library like https://github.com/google/oss-fuzz or https://github.com/fuzzitdev/javafuzz.

**Comment by ben-manes** [comment]
or maybe a library like https://github.com/instancio/instancio, https://github.com/j-easy/easy-random, and many other similar model data generators

**Comment by Mamun-Al-Babu-Shikder** [comment]
@ben-manes thanks for your valuable comment.
