### ISSUE TITLE
Add Priority-Based Eviction Policy to Guava Cache

### ISSUE THREAD

**Issue by RaviSadam** [google/guava#7520]
### Description

Currently, the Guava Cache module provides several eviction policies such as size-based eviction, time-based eviction, and reference-based eviction. However, it lacks a priority-based eviction mechanism, which can be essential in scenarios where cached items have varying levels of importance.

For instance, in systems where some cached data is critical and needs to be retained as long as possible, a priority-based eviction policy would ensure that lower-priority items are evicted first when the cache reaches capacity. Without this feature, it is challenging to implement advanced caching strategies that depend on item importance.

**Feature Proposal:**

Introduce a priority-based eviction policy to the Guava Cache module. The proposed feature would allow developers to assign a priority level to each cache entry during insertion. The cache would then evict the lowest-priority entries first when necessary to maintain the defined constraints (e.g., size or memory limit).

### 2. What's the best code you can write to accomplish that without the new feature?

By the combination of **custom eviction strategies** and the **RemovalListener** feature provided by the library.

### 3. What would that same code look like if we added your feature?

If Guava Cache were to support built-in priority-based eviction, the API might include methods to define and use priorities directly. Below is an imagined implementation where the CacheBuilder allows you to define priorities, and the eviction mechanism is managed internally by the cache itself.

### (Optional) What would the method signatures for your feature look like?

```java

```

### Concrete Use Cases

- **Session Management in Web Applications**: A web application may need to cache user sessions or tokens for faster authentication and state management. However, not all sessions have the same importance. Some users (like administrators) may require their sessions to be retained in the cache for longer, while less critical sessions (like guest users) can be evicted first.
- **Financial and Trading Systems**: In trading systems, caching real-time data such as stock prices, market trends, and trade information can significantly improve performance. However, some trades, users, or assets may be more important than others, requiring the retention of certain information while evicting less critical data.
- Geospatial Data Caching: Applications that use geospatial data (like maps or location-based services) often cache the results of expensive geographic queries. Some areas (e.g., major cities or highly requested locations) are more important to cache than others (e.g., remote areas with low traffic).
Many more....

### Packages

com.google.common.cache

### Checklist

- [x] I agree to follow the [code of conduct](https://github.com/google/.github/blob/master/CODE_OF_CONDUCT.md).

- [x] I have read and understood the [contribution guidelines](https://github.com/google/guava/wiki/HowToContribute#feature-requests).

- [x] I have read and understood [Guava's philosophy](https://github.com/google/guava/wiki/PhilosophyExplained), and I strongly believe that this proposal aligns with it.

- [x] I have visited the [idea graveyard](https://github.com/google/guava/wiki/IdeaGraveyard), and did not see anything similar to this idea.

**Comment by cpovirk** [comment]
Thanks, but at this point, we're not adding features to our caching library, since [Caffeine is a better option](https://guava.dev/cachebuilder).
