### ISSUE TITLE
WARNING: A terminally deprecated method in sun.misc.Unsafe has been called

### ISSUE THREAD

**Issue by khmarbaise** [google/guava#7565]
### Guava Version

guava-33.3.1-jre.jar

### Description

While using a EA build of JDK 24 (24.ea.28) the following WARNING is emitted:

```
WARNING: A terminally deprecated method in sun.misc.Unsafe has been called
WARNING: sun.misc.Unsafe::objectFieldOffset has been called by com.google.common.util.concurrent.AbstractFuture$UnsafeAtomicHelper (file:/Users/khm/tools/maven/lib/guava-33.3.1-jre.jar)
WARNING: Please consider reporting this to the maintainers of class com.google.common.util.concurrent.AbstractFuture$UnsafeAtomicHelper
WARNING: sun.misc.Unsafe::objectFieldOffset will be removed in a future release
```
Also check the newer version `guava-33.4.0-jre.jar`
```
$> mvn verify
WARNING: A terminally deprecated method in sun.misc.Unsafe has been called
WARNING: sun.misc.Unsafe::objectFieldOffset has been called by com.google.common.util.concurrent.AbstractFuture$UnsafeAtomicHelper (file:/Users/khm/tools/maven/lib/guava-33.4.0-jre.jar)
WARNING: Please consider reporting this to the maintainers of class com.google.common.util.concurrent.AbstractFuture$UnsafeAtomicHelper
WARNING: sun.misc.Unsafe::objectFieldOffset will be removed in a future release
```

### Example

```java
Using Apache Maven 4.0.0-rc-2 will emit this warning based on the usage of guava. Any project which will be built with Apache Maven 4.0.0-rc-2 will emit this WARNING...
```

### Expected Behavior

The WARNINGs should not emitted anymore based on the deprecation of the usage.

### Actual Behavior

As described in description.

### Checklist

- [x] I agree to follow the [code of conduct](https://github.com/google/.github/blob/master/CODE_OF_CONDUCT.md).

- [x] I can reproduce the bug with the [latest](https://github.com/google/guava/releases/latest) version of Guava available.

**Comment by cpovirk** [comment]
Thanks. We're tracking this in https://github.com/google/guava/issues/6806, which I'll give a better title to.

For `AbstractFuture` specifically, the fix is in #7555, which I have ready to submit in the new year.
